describe('Workflow Group Functionality', () => {
    it('TC381_DeleteApprovalStage', () => {

        cy.server();
        cy.route({
            method: 'GET',
            url: '/v1/WorkflowGroup',
            response: {
                "object": [{
                    "name": "ab2",
                    "lastUpdatedOn": "2020-08-24T22:41:19.83",
                    "lastUpdatedBy": 73,
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Alexanderrrrrgg Elliss",
                    "createdOn": "2020-06-28T13:29:22.29",
                    "createdBy": 73,
                    "id": 10,
                    "isActive": true,
                    "groupRoles": [{
                        "roleId": 27,
                        "name": null,
                        "workflowGroupId": 10
                    }, {
                        "roleId": 2,
                        "name": null,
                        "workflowGroupId": 10
                    }, {
                        "roleId": 3,
                        "name": null,
                        "workflowGroupId": 10
                    }, {
                        "roleId": 17,
                        "name": null,
                        "workflowGroupId": 10
                    }],
                    "groupUsers": [{
                        "userId": 73,
                        "workflowGroupId": 10
                    }]
                }, {
                    "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
                    "lastUpdatedOn": "2020-07-11T19:24:10.507",
                    "lastUpdatedBy": 45,
                    "lastUpdatedByName": "Mike Harvey",
                    "createdByName": "David  Dombrowsky",
                    "createdOn": "2020-06-30T15:03:04.1",
                    "createdBy": 43,
                    "id": 24,
                    "isActive": false,
                    "groupRoles": [],
                    "groupUsers": []
                }, {
                    "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
                    "lastUpdatedOn": "2020-06-30T20:52:04.997",
                    "lastUpdatedBy": 43,
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "createdOn": "2020-06-30T20:52:04.997",
                    "createdBy": 43,
                    "id": 27,
                    "isActive": true,
                    "groupRoles": [],
                    "groupUsers": []
                }, {
                    "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
                    "lastUpdatedOn": "2020-08-06T23:36:04.983",
                    "lastUpdatedBy": 78,
                    "lastUpdatedByName": "Diamond Brown",
                    "createdByName": "David  Dombrowsky",
                    "createdOn": "2020-07-08T18:33:57.48",
                    "createdBy": 43,
                    "id": 31,
                    "isActive": true,
                    "groupRoles": [{
                        "roleId": 6,
                        "name": null,
                        "workflowGroupId": 31
                    }],
                    "groupUsers": [{
                        "userId": 78,
                        "workflowGroupId": 31
                    }]
                }, {
                    "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
                    "lastUpdatedOn": "2020-07-08T18:58:43.093",
                    "lastUpdatedBy": 43,
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "createdOn": "2020-07-08T18:58:43.093",
                    "createdBy": 43,
                    "id": 32,
                    "isActive": true,
                    "groupRoles": [],
                    "groupUsers": []
                }, {
                    "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
                    "lastUpdatedOn": "2020-07-11T03:45:21.97",
                    "lastUpdatedBy": 43,
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "createdOn": "2020-07-11T03:45:21.97",
                    "createdBy": 43,
                    "id": 33,
                    "isActive": true,
                    "groupRoles": [],
                    "groupUsers": []
                }, {
                    "name": "Workflow Test",
                    "lastUpdatedOn": "2020-07-15T19:44:31.453",
                    "lastUpdatedBy": 134,
                    "lastUpdatedByName": "Admin Msrfsr",
                    "createdByName": "Admin Msrfsr",
                    "createdOn": "2020-07-15T19:44:31.453",
                    "createdBy": 134,
                    "id": 37,
                    "isActive": true,
                    "groupRoles": [{
                        "roleId": 27,
                        "name": null,
                        "workflowGroupId": 37
                    }],
                    "groupUsers": [{
                        "userId": 2,
                        "workflowGroupId": 37
                    }]
                }, {
                    "name": "Workflow Test",
                    "lastUpdatedOn": "2020-07-21T00:00:56.387",
                    "lastUpdatedBy": 134,
                    "lastUpdatedByName": "Admin Msrfsr",
                    "createdByName": "Admin Msrfsr",
                    "createdOn": "2020-07-21T00:00:56.387",
                    "createdBy": 134,
                    "id": 38,
                    "isActive": true,
                    "groupRoles": [{
                        "roleId": 27,
                        "name": null,
                        "workflowGroupId": 38
                    }],
                    "groupUsers": [{
                        "userId": 2,
                        "workflowGroupId": 38
                    }]
                }, {
                    "name": "Workflow Test",
                    "lastUpdatedOn": "2020-08-24T22:41:57.687",
                    "lastUpdatedBy": 73,
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Admin Msrfsr",
                    "createdOn": "2020-07-29T19:20:07.703",
                    "createdBy": 134,
                    "id": 39,
                    "isActive": true,
                    "groupRoles": [{
                        "roleId": 27,
                        "name": null,
                        "workflowGroupId": 39
                    }, {
                        "roleId": 1,
                        "name": null,
                        "workflowGroupId": 39
                    }],
                    "groupUsers": [{
                        "userId": 119,
                        "workflowGroupId": 39
                    }, {
                        "userId": 121,
                        "workflowGroupId": 39
                    }, {
                        "userId": 119,
                        "workflowGroupId": 39
                    }, {
                        "userId": 121,
                        "workflowGroupId": 39
                    }, {
                        "userId": 121,
                        "workflowGroupId": 39
                    }, {
                        "userId": 2,
                        "workflowGroupId": 39
                    }]
                }, {
                    "name": "Approval Group Add Test 2 8.6.2020",
                    "lastUpdatedOn": "2020-08-24T22:42:38.453",
                    "lastUpdatedBy": 73,
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Diamond Brown",
                    "createdOn": "2020-08-06T21:18:09.647",
                    "createdBy": 78,
                    "id": 40,
                    "isActive": false,
                    "groupRoles": [{
                        "roleId": 1,
                        "name": null,
                        "workflowGroupId": 40
                    }, {
                        "roleId": 27,
                        "name": null,
                        "workflowGroupId": 40
                    }],
                    "groupUsers": [{
                        "userId": 121,
                        "workflowGroupId": 40
                    }, {
                        "userId": 78,
                        "workflowGroupId": 40
                    }, {
                        "userId": 119,
                        "workflowGroupId": 40
                    }, {
                        "userId": 78,
                        "workflowGroupId": 40
                    }]
                }, {
                    "name": "Test Approval Group 8.6.20",
                    "lastUpdatedOn": "2020-08-06T23:57:18.633",
                    "lastUpdatedBy": 78,
                    "lastUpdatedByName": "Diamond Brown",
                    "createdByName": "Diamond Brown",
                    "createdOn": "2020-08-06T23:57:18.633",
                    "createdBy": 78,
                    "id": 41,
                    "isActive": true,
                    "groupRoles": [{
                        "roleId": 16,
                        "name": null,
                        "workflowGroupId": 41
                    }],
                    "groupUsers": [{
                        "userId": 78,
                        "workflowGroupId": 41
                    }]
                }, {
                    "name": "CreateWorkflowGroupRequest-8faf6491cf88817e",
                    "lastUpdatedOn": "2020-08-10T17:58:17.91",
                    "lastUpdatedBy": 43,
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "createdOn": "2020-08-10T17:58:17.91",
                    "createdBy": 43,
                    "id": 42,
                    "isActive": true,
                    "groupRoles": [],
                    "groupUsers": []
                }],
                "successMessage": null,
                "errorMessages": [],
                "id": 0,
                "hasErrors": false,
                "hasValidationErrors": false
            }
        });

        cy.route({
            method: 'GET',
            url: '/v1/WorkflowStage',
            response: {
                "object": [{
                    "name": "OP and WI Document Approvals",
                    "lastUpdatedByName": "Diamond Brown",
                    "createdByName": "Mike Harvey",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-08-05T00:17:21.74",
                    "lastUpdatedBy": 78,
                    "lastUpdated": {
                        "id": 78,
                        "isActive": true,
                        "userRoleId": "f6b01ff6-0568-4feb-9afb-29525cad8430",
                        "userName": "dbrown",
                        "firstName": "Diamond",
                        "lastName": "Brown",
                        "fullName": "Diamond Brown",
                        "title": "Administrators",
                        "email": "diamond.brown@cmhworks.com",
                        "securityStamp": "ed548a82-4da5-4825-9d4a-fcffcfb8bde6",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-05-31T13:17:16.807",
                        "lastUpdatedBy": 78,
                        "createdOn": "2019-07-05T14:47:32.4",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2019-04-26T13:13:54.303",
                    "createdBy": 45,
                    "created": {
                        "id": 45,
                        "isActive": true,
                        "userRoleId": "9c096045-0b58-4a8d-98d8-2cd5d7661f1e",
                        "userName": "mharvey",
                        "firstName": "Mike",
                        "lastName": "Harvey",
                        "fullName": "Mike Harvey",
                        "title": "Dev Administrator",
                        "email": "mike.harvey@cmhworks.com",
                        "securityStamp": "57a57397-f709-43f8-a5bd-e9a3d4ed060b",
                        "phone": "7032145629",
                        "supervisorId": 71,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-06-11T19:24:28.78",
                        "lastUpdatedBy": 45,
                        "createdOn": "2018-07-01T00:58:16.707",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 3
                }, {
                    "name": "Reference Document Approvals",
                    "lastUpdatedByName": "Diamond Brown",
                    "createdByName": "Mike Harvey",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-08-05T00:17:23.377",
                    "lastUpdatedBy": 78,
                    "lastUpdated": {
                        "id": 78,
                        "isActive": true,
                        "userRoleId": "f6b01ff6-0568-4feb-9afb-29525cad8430",
                        "userName": "dbrown",
                        "firstName": "Diamond",
                        "lastName": "Brown",
                        "fullName": "Diamond Brown",
                        "title": "Administrators",
                        "email": "diamond.brown@cmhworks.com",
                        "securityStamp": "ed548a82-4da5-4825-9d4a-fcffcfb8bde6",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-05-31T13:17:16.807",
                        "lastUpdatedBy": 78,
                        "createdOn": "2019-07-05T14:47:32.4",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2019-04-26T13:21:18.47",
                    "createdBy": 45,
                    "created": {
                        "id": 45,
                        "isActive": true,
                        "userRoleId": "9c096045-0b58-4a8d-98d8-2cd5d7661f1e",
                        "userName": "mharvey",
                        "firstName": "Mike",
                        "lastName": "Harvey",
                        "fullName": "Mike Harvey",
                        "title": "Dev Administrator",
                        "email": "mike.harvey@cmhworks.com",
                        "securityStamp": "57a57397-f709-43f8-a5bd-e9a3d4ed060b",
                        "phone": "7032145629",
                        "supervisorId": 71,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-06-11T19:24:28.78",
                        "lastUpdatedBy": 45,
                        "createdOn": "2018-07-01T00:58:16.707",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 4
                }, {
                    "name": "Admin Stage",
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Mike Harvey",
                    "groups": [{
                        "workflowStageId": 5,
                        "workflowGroupId": 10
                    }, {
                        "workflowStageId": 5,
                        "workflowGroupId": 39
                    }, {
                        "workflowStageId": 5,
                        "workflowGroupId": 40
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-08-24T23:26:21.783",
                    "lastUpdatedBy": 73,
                    "lastUpdated": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "createdOn": "2015-04-06T22:18:50.077",
                    "createdBy": 45,
                    "created": {
                        "id": 45,
                        "isActive": true,
                        "userRoleId": "9c096045-0b58-4a8d-98d8-2cd5d7661f1e",
                        "userName": "mharvey",
                        "firstName": "Mike",
                        "lastName": "Harvey",
                        "fullName": "Mike Harvey",
                        "title": "Dev Administrator",
                        "email": "mike.harvey@cmhworks.com",
                        "securityStamp": "57a57397-f709-43f8-a5bd-e9a3d4ed060b",
                        "phone": "7032145629",
                        "supervisorId": 71,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-06-11T19:24:28.78",
                        "lastUpdatedBy": 45,
                        "createdOn": "2018-07-01T00:58:16.707",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 5
                }, {
                    "name": "wwwww23",
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Alexanderrrrrgg Elliss",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-08-24T23:34:42.787",
                    "lastUpdatedBy": 73,
                    "lastUpdated": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "createdOn": "2020-06-29T05:40:07.097",
                    "createdBy": 73,
                    "created": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "id": 6
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-06-30T19:21:13.487",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-30T19:21:13.487",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 7
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-06-30T19:21:53.397",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-30T19:21:53.397",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 8
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-06-30T20:29:00.94",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-30T20:29:00.94",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 9
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-06-30T20:52:00.027",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-30T20:52:00.027",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 10
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-02T00:50:59.803",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-02T00:50:59.803",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 11
                }, {
                    "name": "wewe2",
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Alexanderrrrrgg Elliss",
                    "groups": [{
                        "workflowStageId": 12,
                        "workflowGroupId": 10
                    }, {
                        "workflowStageId": 12,
                        "workflowGroupId": 24
                    }],
                    "isActive": false,
                    "lastUpdatedOn": "2020-08-25T00:38:14.78",
                    "lastUpdatedBy": 73,
                    "lastUpdated": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "createdOn": "2020-07-06T17:54:00.83",
                    "createdBy": 73,
                    "created": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "id": 12
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-08T18:16:44.577",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-08T18:16:44.577",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 13
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-08T18:33:56.62",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-08T18:33:56.62",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 14
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-08T18:58:41.187",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-08T18:58:41.187",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 15
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-11T03:44:58.257",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-11T03:44:58.257",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 16
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-11T04:55:44.947",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-11T04:55:44.947",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 17
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-07-11T20:09:50.363",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-11T20:09:50.363",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 18
                }, {
                    "name": "Workflow Stage Test",
                    "lastUpdatedByName": "Admin Msrfsr",
                    "createdByName": "Admin Msrfsr",
                    "groups": [{
                        "workflowStageId": 20,
                        "workflowGroupId": 10
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-07-15T19:13:07.507",
                    "lastUpdatedBy": 134,
                    "lastUpdated": {
                        "id": 134,
                        "isActive": true,
                        "userRoleId": null,
                        "userName": "admin",
                        "firstName": "Admin",
                        "lastName": "Msrfsr",
                        "fullName": "Admin Msrfsr",
                        "title": "Admin",
                        "email": "admin-msrfsr@cmhworks.com",
                        "securityStamp": null,
                        "phone": "5552221212",
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-06-05T23:16:32.637",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-06-05T19:13:53",
                        "createdBy": 68,
                        "roles": []
                    },
                    "createdOn": "2020-07-15T19:13:07.507",
                    "createdBy": 134,
                    "created": {
                        "id": 134,
                        "isActive": true,
                        "userRoleId": null,
                        "userName": "admin",
                        "firstName": "Admin",
                        "lastName": "Msrfsr",
                        "fullName": "Admin Msrfsr",
                        "title": "Admin",
                        "email": "admin-msrfsr@cmhworks.com",
                        "securityStamp": null,
                        "phone": "5552221212",
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-06-05T23:16:32.637",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-06-05T19:13:53",
                        "createdBy": 68,
                        "roles": []
                    },
                    "id": 20
                }, {
                    "name": "Workflow Stage Test",
                    "lastUpdatedByName": "Admin Msrfsr",
                    "createdByName": "Admin Msrfsr",
                    "groups": [{
                        "workflowStageId": 21,
                        "workflowGroupId": 10
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-07-21T00:01:54.113",
                    "lastUpdatedBy": 134,
                    "lastUpdated": {
                        "id": 134,
                        "isActive": true,
                        "userRoleId": null,
                        "userName": "admin",
                        "firstName": "Admin",
                        "lastName": "Msrfsr",
                        "fullName": "Admin Msrfsr",
                        "title": "Admin",
                        "email": "admin-msrfsr@cmhworks.com",
                        "securityStamp": null,
                        "phone": "5552221212",
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-06-05T23:16:32.637",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-06-05T19:13:53",
                        "createdBy": 68,
                        "roles": []
                    },
                    "createdOn": "2020-07-21T00:01:54.113",
                    "createdBy": 134,
                    "created": {
                        "id": 134,
                        "isActive": true,
                        "userRoleId": null,
                        "userName": "admin",
                        "firstName": "Admin",
                        "lastName": "Msrfsr",
                        "fullName": "Admin Msrfsr",
                        "title": "Admin",
                        "email": "admin-msrfsr@cmhworks.com",
                        "securityStamp": null,
                        "phone": "5552221212",
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-06-05T23:16:32.637",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-06-05T19:13:53",
                        "createdBy": 68,
                        "roles": []
                    },
                    "id": 21
                }, {
                    "name": "Workflow Stage Test",
                    "lastUpdatedByName": "Admin Msrfsr",
                    "createdByName": "Admin Msrfsr",
                    "groups": [{
                        "workflowStageId": 22,
                        "workflowGroupId": 10
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-07-31T16:11:20.467",
                    "lastUpdatedBy": 134,
                    "lastUpdated": {
                        "id": 134,
                        "isActive": true,
                        "userRoleId": null,
                        "userName": "admin",
                        "firstName": "Admin",
                        "lastName": "Msrfsr",
                        "fullName": "Admin Msrfsr",
                        "title": "Admin",
                        "email": "admin-msrfsr@cmhworks.com",
                        "securityStamp": null,
                        "phone": "5552221212",
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-06-05T23:16:32.637",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-06-05T19:13:53",
                        "createdBy": 68,
                        "roles": []
                    },
                    "createdOn": "2020-07-31T16:11:20.467",
                    "createdBy": 134,
                    "created": {
                        "id": 134,
                        "isActive": true,
                        "userRoleId": null,
                        "userName": "admin",
                        "firstName": "Admin",
                        "lastName": "Msrfsr",
                        "fullName": "Admin Msrfsr",
                        "title": "Admin",
                        "email": "admin-msrfsr@cmhworks.com",
                        "securityStamp": null,
                        "phone": "5552221212",
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-06-05T23:16:32.637",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-06-05T19:13:53",
                        "createdBy": 68,
                        "roles": []
                    },
                    "id": 22
                }, {
                    "name": "Test Approval Stage",
                    "lastUpdatedByName": "Diamond Brown",
                    "createdByName": "Diamond Brown",
                    "groups": [{
                        "workflowStageId": 23,
                        "workflowGroupId": 37
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-08-05T00:03:36.86",
                    "lastUpdatedBy": 78,
                    "lastUpdated": {
                        "id": 78,
                        "isActive": true,
                        "userRoleId": "f6b01ff6-0568-4feb-9afb-29525cad8430",
                        "userName": "dbrown",
                        "firstName": "Diamond",
                        "lastName": "Brown",
                        "fullName": "Diamond Brown",
                        "title": "Administrators",
                        "email": "diamond.brown@cmhworks.com",
                        "securityStamp": "ed548a82-4da5-4825-9d4a-fcffcfb8bde6",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-05-31T13:17:16.807",
                        "lastUpdatedBy": 78,
                        "createdOn": "2019-07-05T14:47:32.4",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-08-05T00:03:36.86",
                    "createdBy": 78,
                    "created": {
                        "id": 78,
                        "isActive": true,
                        "userRoleId": "f6b01ff6-0568-4feb-9afb-29525cad8430",
                        "userName": "dbrown",
                        "firstName": "Diamond",
                        "lastName": "Brown",
                        "fullName": "Diamond Brown",
                        "title": "Administrators",
                        "email": "diamond.brown@cmhworks.com",
                        "securityStamp": "ed548a82-4da5-4825-9d4a-fcffcfb8bde6",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-05-31T13:17:16.807",
                        "lastUpdatedBy": 78,
                        "createdOn": "2019-07-05T14:47:32.4",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 23
                }, {
                    "name": "Approval Stage Test 1",
                    "lastUpdatedByName": "Diamond Brown",
                    "createdByName": "Diamond Brown",
                    "groups": [{
                        "workflowStageId": 24,
                        "workflowGroupId": 10
                    }, {
                        "workflowStageId": 24,
                        "workflowGroupId": 40
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-08-06T21:49:56.11",
                    "lastUpdatedBy": 78,
                    "lastUpdated": {
                        "id": 78,
                        "isActive": true,
                        "userRoleId": "f6b01ff6-0568-4feb-9afb-29525cad8430",
                        "userName": "dbrown",
                        "firstName": "Diamond",
                        "lastName": "Brown",
                        "fullName": "Diamond Brown",
                        "title": "Administrators",
                        "email": "diamond.brown@cmhworks.com",
                        "securityStamp": "ed548a82-4da5-4825-9d4a-fcffcfb8bde6",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-05-31T13:17:16.807",
                        "lastUpdatedBy": 78,
                        "createdOn": "2019-07-05T14:47:32.4",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-08-05T00:05:12.923",
                    "createdBy": 78,
                    "created": {
                        "id": 78,
                        "isActive": true,
                        "userRoleId": "f6b01ff6-0568-4feb-9afb-29525cad8430",
                        "userName": "dbrown",
                        "firstName": "Diamond",
                        "lastName": "Brown",
                        "fullName": "Diamond Brown",
                        "title": "Administrators",
                        "email": "diamond.brown@cmhworks.com",
                        "securityStamp": "ed548a82-4da5-4825-9d4a-fcffcfb8bde6",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 11,
                        "lastUpdatedOn": "2020-05-31T13:17:16.807",
                        "lastUpdatedBy": 78,
                        "createdOn": "2019-07-05T14:47:32.4",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 24
                }, {
                    "name": "d8f75230c904a614",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createdByName": "David  Dombrowsky",
                    "groups": [],
                    "isActive": false,
                    "lastUpdatedOn": "2020-08-10T17:58:16.477",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-08-10T17:58:16.477",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": "Mike Harvey",
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 26
                }, {
                    "name": "Workflow Stage Test2",
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createdByName": "Alexanderrrrrgg Elliss",
                    "groups": [{
                        "workflowStageId": 29,
                        "workflowGroupId": 10
                    }],
                    "isActive": true,
                    "lastUpdatedOn": "2020-08-25T06:29:30.0840998Z",
                    "lastUpdatedBy": 73,
                    "lastUpdated": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "createdOn": "2020-08-25T06:29:30.0840998Z",
                    "createdBy": 73,
                    "created": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "id": 29
                }],
                "successMessage": null,
                "errorMessages": [],
                "id": 0,
                "hasErrors": false,
                "hasValidationErrors": false
            }
        });

        cy.route({
            method: 'Delete',
            url: '/v1/WorkflowStage/29',
            response: {
                "successMessage": "WorkflowGroup was successfully removed.",
                "errorMessages": [],
                "id": 0,
                "hasErrors": false,
                "hasValidationErrors": false
            }
        });

        cy.beginWebConsoleTracking();
        cy.login('admin');
        cy.navigateToPage('Workflow', 'Approval Stages');

        cy.get(".ui-blockui-document", { timeout: 8000 }).should("not.be.visible");

        cy.showDropdownTrackableModel('usergrid-options');

        //delete item
        var wfstageNewName = 'Workflow Stage Test2';
        cy.get(".ui-blockui-document", { timeout: 4000 }).should("not.be.visible");
        cy.get('[data-cy=searchbyname-grid]').clear();
        cy.get('[data-cy=searchbyname-grid]').type(wfstageNewName).should('have.value', wfstageNewName);
        cy.get('tbody').find('tr:first-child td').contains(wfstageNewName);
        cy.get('tbody').find('tr:first-child td').get('[data-cy=deleteRow').click();
        //delete item

        cy.waitpost();
        cy.get('[data-cy=searchbyname-grid]').clear();
        cy.writeAndValidate('searchbyname-grid', wfstageNewName);
        cy.get('[data-cy=deleteRow]').should('not.exist');

        cy.get('@warningMessage').should("not.called")
        cy.get('@errorMessage').should("not.called")
    })
})
