
import { ColumnsSaved } from '../../../src/app/models/lib/ColumnsSaved';

describe('Parts Functionality', () => {
    it('TC71_TC320_PartFilterGrid', () => {
        cy.server();
        cy.route({
            method: 'GET',
            url: '/v1/Part',
            response: {
                "object": [{
                    "name": "DD Part B 1592421221",
                    "partNumber": "1592421221b",
                    "oemPartNumber": "1592421221b-OEM",
                    "isKit": false,
                    "nickName": "DD Part B Nick",
                    "maximumCycles": 9999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-06-17T19:18:20.603",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-17T19:18:20.603",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 3
                }, {
                    "name": "DD Part C 1592421221",
                    "partNumber": "1592421221c",
                    "oemPartNumber": "1592421221c-OEM",
                    "isKit": false,
                    "nickName": "DD Part C Nick",
                    "maximumCycles": 9999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-06-17T19:18:34.747",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-17T19:18:34.747",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 4
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:22:28.937",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:22:28.937",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 6
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:26:20.86",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:26:20.86",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 7
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:27:05.57",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:27:05.57",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 8
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:54:34.08",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:54:34.08",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 9
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:57:52.7",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:57:52.7",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 10
                }, {
                    "name": "NAME159430341000000",
                    "partNumber": "PARTNUM159430341000000",
                    "oemPartNumber": "OEM159430341000000",
                    "isKit": false,
                    "nickName": "NICK159430341000000",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T14:03:38.34",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T14:03:38.34",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 11
                }, {
                    "name": "NAME159430341000001",
                    "partNumber": "PARTNUM159430341000001",
                    "oemPartNumber": "OEM159430341000001",
                    "isKit": false,
                    "nickName": "NICK159430341000001",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T14:03:39.7",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T14:03:39.7",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 12
                }, {
                    "name": "TESTNAME1594327266",
                    "partNumber": "TESTPARTNUM1594327266",
                    "oemPartNumber": "TESTOEMPARTNUM1594327266",
                    "isKit": false,
                    "nickName": "DD Part A Nick",
                    "maximumCycles": 9999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-11T20:25:58.74",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-17T19:17:55.29",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 2
                }],
                "successMessage": null,
                "errorMessages": [],
                "id": 0,
                "hasErrors": false,
                "hasValidationErrors": false
            }
        });

        cy.beginWebConsoleTracking();
        cy.login('admin');
        cy.navigateToPage('Parts', 'Parts');

        const parts = [
            new ColumnsSaved({ id: 'id', label: 'Id', visible: true }),
            new ColumnsSaved({ id: 'name', label: 'Name', visible: true }),
            new ColumnsSaved({ id: 'partNumber', label: 'Part Number', visible: true }),
            new ColumnsSaved({ id: 'oemPartNumber', label: 'OEM Part Number', visible: true }),
            new ColumnsSaved({ id: 'isKit', label: 'Is Kit', visible: true }),
            new ColumnsSaved({ id: 'isActive', label: 'Is Active', visible: true }),
            new ColumnsSaved({ id: 'maximumCycles', label: 'Maximun Cycles', visible: true }),
            new ColumnsSaved({ id: 'files', label: 'Reference Files', visible: true }),
            new ColumnsSaved({ id: 'createdOn', label: 'Created On', visible: false }),
            new ColumnsSaved({ id: 'createdByName', label: 'Created By', visible: false }),
            new ColumnsSaved({ id: 'lastUpdatedOn', label: 'Updated On', visible: false }),
            new ColumnsSaved({ id: 'lastUpdatedByName', label: 'Updated By', visible: false })
        ];

        cy.showDropdownTrackableModel('usergrid-options');
        parts.forEach(element => {
            cy.get('[data-cy=usertable-header]').contains(element.label).click();
        });

        cy.multiselectClick('isKit-grid','No');
        cy.multiselectClick('isActive-grid','No');
        cy.writeAndValidate('id-grid','3');
        cy.writeAndValidate('name-grid','DD Part B 1592421221');
        cy.writeAndValidate('partNumber-grid','1592421221b');   
        cy.writeAndValidate('oemPartNumber-grid','1592421221b-OEM');
        cy.writeAndValidate('maximumCycles-grid','9999');
        cy.writeAndValidate('createdByName-grid','David  Dombrowsky');
        cy.writeAndValidate('lastUpdatedByName-grid','David  Dombrowsky');
        cy.writeAndValidateDate('createdOn-grid','06/17/2020');
        cy.writeAndValidateDate('lastUpdatedOn-grid','06/17/2020');
        cy.get('[data-cy=row]').find('td:first').contains('3');

        cy.logout();
        cy.checkWebConsoleTracking();
    })
})

