CREATE TABLE [dbo].[A_ACTUAL_PARTS_RELATED_FILES] (
    [ID]             VARCHAR (50) NOT NULL,
    [ACTUAL_PART_ID] VARCHAR (50) NOT NULL,
    [FILE_ID]        VARCHAR (50) NOT NULL,
    [STATUS]         VARCHAR (50) NULL,
    [DATE_DELETED]   DATETIME     NULL,
    [DELETED_BY]     VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACTUAL_PARTS_RELATED_FILES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

