CREATE TABLE [dbo].[A_ACTUAL_PART_STATUSES] (
    [ID]    VARCHAR (50) NOT NULL,
    [DRCM]  DATETIME     NULL,
    [MODBY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACTUAL_PART_STATUSES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

