CREATE TABLE [dbo].[A_ACTUAL_PARTS] (
    [ID]             VARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    [STATUS]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACTUAL_PART] PRIMARY KEY CLUSTERED ([ID] ASC)
);




GO


CREATE         TRIGGER A_ACTUAL_PARTS_INSERT_UPDATE
ON dbo.A_ACTUAL_PARTS
AFTER INSERT,UPDATE
AS
declare @ID varchar(50)
SELECT @ID = ID FROM INSERTED
print'The ID of the inserted ACTUAL_PART is ' + @ID
exec dbo.A_SP_ACTUAL_PART_UPDATE_MY_CHILDREN_PARTS @ID


GO
CREATE NONCLUSTERED INDEX [IX_A_ACTUAL_PARTS_EXECPLAN_01]
    ON [dbo].[A_ACTUAL_PARTS]([HISTORY_REF_ID] ASC, [STATUS] ASC);

