CREATE TABLE [dbo].[A_ACCOUNT_ORDER_ITEM_STATUS] (
    [ID]            VARCHAR (50) NOT NULL,
    [ACCOUNT_ID]    VARCHAR (50) NOT NULL,
    [ORDER_ITEM_ID] VARCHAR (50) NOT NULL,
    [STATUS]        VARCHAR (50) NOT NULL,
    [MODBY]         VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL,
    CONSTRAINT [PK_A_ACCOUNT_ORDER_ITEM_STATUS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

