CREATE TABLE [dbo].[A_ACCOUNT_INVOICE_PAYMENT_LINK] (
    [ID]         VARCHAR (50) NOT NULL,
    [PAYMENT_ID] VARCHAR (50) NULL,
    [INVOICE_ID] VARCHAR (50) NULL,
    [AMOUNT]     MONEY        NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACCOUNT_INVOICE_PAYMENT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

