CREATE TABLE [dbo].[A_ACCOUNT_INVOICE_ITEMS] (
    [ID]             VARCHAR (50)    NOT NULL,
    [INVOICE_ID]     VARCHAR (50)    NOT NULL,
    [ACCOUNT_ID]     VARCHAR (50)    NOT NULL,
    [PURCH_ITEM_ID]  VARCHAR (50)    NULL,
    [STATUS]         VARCHAR (50)    NOT NULL,
    [DRCM]           DATETIME        NULL,
    [MODBY]          VARCHAR (50)    NULL,
    [AMOUNT]         MONEY           NULL,
    [DESCRIPTION]    NVARCHAR (2000) NULL,
    [DATE_INVOICED]  DATETIME        NULL,
    [AMT_PAID]       MONEY           NULL,
    [LATE_FEES]      MONEY           NULL,
    [TOTAL]          MONEY           NULL,
    [PURCHASER_ID]   VARCHAR (50)    NULL,
    [DISPUTED_LINK]  VARCHAR (50)    NULL,
    [COMMENTS]       NVARCHAR (2000) NULL,
    [PURCHASE_ID]    VARCHAR (50)    NULL,
    [ITEM_TYPE]      VARCHAR (50)    NULL,
    [CUSTOMER_CO]    VARCHAR (50)    NULL,
    [SUPPLIER_CO]    VARCHAR (50)    NULL,
    [QUOTE_ID]       VARCHAR (50)    NULL,
    [DATE_POSTED]    DATETIME        NULL,
    [CUST_SINGLE_PO] VARCHAR (50)    NULL,
    [CUST_LINE_ITEM] VARCHAR (50)    NULL,
    [FAILED_MONITOR] TINYINT         NULL,
    [FILL_ID]        VARCHAR (50)    NULL,
    [TAX]            MONEY           NULL,
    [TAX_RATE]       FLOAT (53)      NULL,
    [QTY]            FLOAT (53)      NULL,
    [UNIT_PRICE]     MONEY           NULL,
    CONSTRAINT [PK_A_ACCOUNT_INVOICE_ITEMS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO






CREATE     TRIGGER A_ACCOUNT_INVOICE_ITEMS_UPDATE
ON dbo.A_ACCOUNT_INVOICE_ITEMS
AFTER UPDATE
AS
if update(TAX) or update(AMOUNT)
	begin
	declare @ID varchaR(50),@TAX money,@AMOUNT money
	SELECT @ID = ID,@TAX = isNull(TAX,0),@AMOUNT = isNull(AMOUNT,0)
	FROM INSERTED
	UPDATE A_ACCOUNT_INVOICE_ITEMS SET TOTAL = @AMOUNT + @TAX WHERE ID = @ID
	end



