CREATE TABLE [dbo].[A_ACCOUNT_PURCHASABLE_ORDERS_LINK] (
    [ID]         VARCHAR (50) NOT NULL,
    [ACCOUNT_ID] VARCHAR (50) NOT NULL,
    [ORDER_ID]   VARCHAR (50) NOT NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACCOUNT_QUOTE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

