CREATE TABLE [dbo].[A_ACTUAL_PARTS_CALL_DATA] (
    [ID]               VARCHAR (50) NOT NULL,
    [PERSON_ID]        VARCHAR (50) NOT NULL,
    [ACTUAL_PART_ID]   VARCHAR (50) NOT NULL,
    [PURCHASE_HIST_ID] VARCHAR (50) NULL,
    [DRCM]             DATETIME     NULL,
    [MODBY]            VARCHAR (50) NULL,
    [ROOT_TASK]        VARCHAR (50) NOT NULL,
    [REASON]           VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACTUAL_PARTS_CALL_DATA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

