CREATE TABLE [dbo].[A_ACCOUNT_PRODUCT_EXCEPTIONS] (
    [ID]         VARCHAR (50) NOT NULL,
    [ACCT_ID]    VARCHAR (50) NULL,
    [PRODUCT_ID] VARCHAR (50) NULL,
    [EX_TYPE]    VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACCOUNT_PRODUCT_EXCEPTIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

