CREATE TABLE [dbo].[A_ACCOUNTS_RELATED_OBJECTS] (
    [ID]         VARCHAR (50) NOT NULL,
    [ACCOUNT_ID] VARCHAR (50) NULL,
    [OBJ_ID]     VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACCOUNTS_RELATED_OBJECTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

