CREATE TABLE [dbo].[A_ACTUAL_PART_PRODUCTS_INSIDE_LINK] (
    [ID]             VARCHAR (50) NOT NULL,
    [ACTUAL_PART_ID] VARCHAR (50) NULL,
    [PRODUCT_ID]     VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACTUAL_PART_PRODUCTS_INSIDE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

