CREATE TABLE [dbo].[A_ACCOUNTS_PART_EXCEPTIONS] (
    [ID]      VARCHAR (50) NOT NULL,
    [ACCT_ID] VARCHAR (50) NULL,
    [PART_ID] VARCHAR (50) NULL,
    [EX_TYPE] VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ACCOUNTS_PART_EXCEPTIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

