CREATE TABLE [dbo].[A_ADMIN_PROCEDURE_TYPES] (
    [ID]    VARCHAR (50) NOT NULL,
    [NAME]  VARCHAR (50) NULL,
    [MODBY] VARCHAR (50) NULL,
    [DRCM]  DATETIME     NULL,
    CONSTRAINT [PK_A_ADMIN_RATE_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

