CREATE TABLE [dbo].[A_ADMIN_ROLE_JOBS_LIST_OF_JOBS] (
    [ID]    VARCHAR (50) NOT NULL,
    [DRCM]  DATETIME     NULL,
    [modby] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ADMIN_ROLE_JOBS_LIST_OF_JOBS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

