CREATE TABLE [dbo].[A_ADMIN_SQL_TO_RUN] (
    [ID]          VARCHAR (50)   NOT NULL,
    [CODE]        VARCHAR (7500) NULL,
    [DRCM]        DATETIME       NULL,
    [MODBY]       VARCHAR (50)   NULL,
    [STATUS]      VARCHAR (50)   NULL,
    [RUN_TIME]    DATETIME       NULL,
    [RUN]         VARCHAR (50)   NULL,
    [RUN_AT_DATE] DATETIME       NULL,
    [FINISH_TIME] DATETIME       NULL,
    [ATTEMPT]     TINYINT        CONSTRAINT [DF_A_ADMIN_SQL_TO_RUN_ATTEMPT] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_A_ADMIN_SQL_TO_RUN] PRIMARY KEY CLUSTERED ([ID] ASC)
);

