CREATE TABLE [dbo].[A_ADMIN_ROLE_JOBS] (
    [ID]      VARCHAR (50) NOT NULL,
    [CO_ID]   VARCHAR (50) NULL,
    [ROLE_ID] VARCHAR (50) NULL,
    [JOB]     VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ADMIN_ROLE_JOBS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

