CREATE TABLE [dbo].[A_ADMIN_SQL_TO_RUN_STATS] (
    [ID]          VARCHAR (50) NOT NULL,
    [SUCCESSES]   INT          NULL,
    [FAILURES]    INT          NULL,
    [START_TIME]  DATETIME     NULL,
    [FINISH_TIME] DATETIME     NULL,
    CONSTRAINT [PK_A_ADMIN_SQL_TO_RUN_STATS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

