CREATE TABLE [dbo].[A_ADMIN_EMAIL_SEND_LIST] (
    [ID]            VARCHAR (50)  NOT NULL,
    [ADDY]          VARCHAR (200) NULL,
    [EMAIL_BODY_ID] VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_ADMIN_EMAIL_SEND_LIST] PRIMARY KEY CLUSTERED ([ID] ASC)
);

