CREATE TABLE [dbo].[A_ADDRESSES] (
    [ID]             NVARCHAR (50) NOT NULL,
    [SOURCE_ID]      NVARCHAR (50) NOT NULL,
    [SOURCE_TABLE]   NVARCHAR (50) NOT NULL,
    [ADDRESS1]       NVARCHAR (50) NULL,
    [ADDRESS2]       NVARCHAR (50) NULL,
    [CITY]           NVARCHAR (50) NULL,
    [STATE_PROVINCE] NVARCHAR (50) NULL,
    [COUNTRY]        NVARCHAR (50) NULL,
    [POSTAL_CODE]    NVARCHAR (50) NULL,
    [DRCM]           DATETIME      NULL,
    [MODBY]          NVARCHAR (50) NULL,
    [ADDRESS_TYPE]   NVARCHAR (50) NULL,
    [SOURCE]         NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_ADDRESSES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

