CREATE TABLE [dbo].[A_ADMIN_EMAIL_BODIES] (
    [ID]         VARCHAR (50)   NULL,
    [CNT]        INT            NULL,
    [TXT]        VARCHAR (7800) NULL,
    [STAT]       VARCHAR (50)   CONSTRAINT [DF_A_ADMIN_EMAIL_BODIES_STAT] DEFAULT ('CREATING') NULL,
    [IS_SUBJECT] TINYINT        CONSTRAINT [DF_A_ADMIN_EMAIL_BODIES_IS_SUBJECT] DEFAULT ((0)) NULL
);

