CREATE TABLE [dbo].[A_ADMIN_PROCEDURES] (
    [ID]           VARCHAR (50) NOT NULL,
    [COMPANY]      VARCHAR (50) NULL,
    [PROCEDURE_ID] VARCHAR (50) NULL,
    [PROC_TYPE]    VARCHAR (50) NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [PRINT_ORDER]  TINYINT      NULL,
    CONSTRAINT [PK_A_ADMIN_RATE_PROCEDURES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

