CREATE TABLE [dbo].[A_APPROVED_OBJECTS] (
    [ID]         VARCHAR (50) NOT NULL,
    [OBJ_REF_ID] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_APPROVED_OBJECTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

