CREATE TABLE [dbo].[A_BUSINESS_PURPOSES] (
    [ID]    VARCHAR (50) NOT NULL,
    [NAME]  VARCHAR (50) NULL,
    [DRCM]  DATETIME     NULL,
    [MODBY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_BUSINESS_PURPOSES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

