CREATE TABLE [dbo].[A_COMPANIES] (
    [ID]             VARCHAR (50)   NOT NULL,
    [DRCM]           DATETIME       NULL,
    [MODBY]          VARCHAR (50)   NULL,
    [HISTORY_REF_ID] VARCHAR (50)   NULL,
    [STATUS]         VARCHAR (50)   NULL,
    [NAME]           VARCHAR (2000) NULL,
    CONSTRAINT [PK_A_COMPANIES] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE         TRIGGER A_COMPANIES_UPDATE
ON dbo.A_COMPANIES
AFTER UPDATE
AS
declare @HIST_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
SELECT
@ID = ID,
@HIST_ID = HISTORY_REF_ID
FROM INSERTED
SELECT @NAME = NAME FROM A_COMPANIES_HISTORY WHERE ID = @HIST_ID
UPDATE A_PEOPLE_SEARCH_TABLE SET
COMPANY_NAME = @NAME WHERE COMPANY_ID = @ID

