CREATE TABLE [dbo].[A_COUNTERS_RECORDINGS] (
    [ID]            VARCHAR (50) NOT NULL,
    [DATE_RECORDED] VARCHAR (50) NULL,
    [RECORDED_BY]   VARCHAR (50) NULL,
    [VAL]           VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    [COUNTER]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_COUNTERS_RECORDINGS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

