CREATE TABLE [dbo].[A_COMPANY_HOLIDAYS] (
    [ID]          VARCHAR (50)  NOT NULL,
    [DESCRIPTION] NVARCHAR (50) NULL,
    [MO]          SMALLINT      NULL,
    [DA]          SMALLINT      NULL,
    [YR]          SMALLINT      NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       VARCHAR (50)  NULL,
    [CO_ID]       VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_COMPANY_HOLIDAYS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

