CREATE TABLE [dbo].[A_COUNTERS] (
    [ID]             VARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    CONSTRAINT [PK_A_COUNTERS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

