CREATE TABLE [dbo].[A_COMPANIES_HISTORY] (
    [ID]            VARCHAR (50)   NOT NULL,
    [NAME]          NVARCHAR (50)  NULL,
    [CO_TYPE]       NCHAR (10)     NULL,
    [PARENT]        NVARCHAR (50)  NULL,
    [PHONE]         NVARCHAR (20)  NULL,
    [LOCATION]      VARCHAR (50)   NULL,
    [LOCATION_NAME] NVARCHAR (200) NULL,
    [PARENT_NAME]   NVARCHAR (50)  NULL,
    [DRCM]          DATETIME       NULL,
    [MODBY]         NVARCHAR (50)  NULL,
    [OBJECT_ID]     VARCHAR (50)   NULL,
    [ROOT_CO_ID]    VARCHAR (50)   NULL,
    CONSTRAINT [PK_A_COMPANIES_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO



CREATE          TRIGGER A_COMPANIES_HISTORY_INSERT
ON dbo.A_COMPANIES_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_COMPANIES_HISTORY',@ID,@NAME,@MODBY,null,null,null


declare @TOP_ID as varchar(50)
select @TOP_ID = dbo.A_FN_COMPANY_GET_TOP_COMPANY(@ID)
UPDATE A_COMPANIES_HISTORY SET ROOT_CO_ID = @TOP_ID WHERE ID = @ID



GO





CREATE             TRIGGER A_COMPANIES_HISTORY_UPDATE
ON dbo.A_COMPANIES_HISTORY
AFTER UPDATE
AS

declare @OBJ_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
declare @LOCATION_ID as nvarchar(50)
SELECT
@ID = ID,
@OBJ_ID = OBJECT_ID,
@NAME = NAME,
@MODBY = MODBY,
@LOCATION_ID = LOCATION
FROM INSERTED
UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID

print 'If the location was updated we need to do this'
if update(LOCATION)
begin
print 'Location was updated'
declare @LOC_NAME as nvarchar(50)
SELECT @LOC_NAME = NAME FROM A_APPROVED_LOCATIONS WHERE ID = @LOCATION_ID
UPDATE A_COMPANIES_HISTORY SET LOCATION_NAME = @LOC_NAME WHERE ID = @ID
end

declare @TOP_ID as varchar(50)
select @TOP_ID = dbo.A_FN_COMPANY_GET_TOP_COMPANY(@ID)
UPDATE A_COMPANIES_HISTORY SET ROOT_CO_ID = @TOP_ID WHERE ID = @ID


