CREATE TABLE [dbo].[A_COMPANY_HEAD_PEOPLE] (
    [ID]        VARCHAR (50) NOT NULL,
    [CO_ID]     VARCHAR (50) NULL,
    [PERSON_ID] VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_COMPANY_HEAD_PEOPLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

