CREATE TABLE [dbo].[A_COLORS] (
    [RGB_CODE] VARCHAR (50)  NOT NULL,
    [NAME]     VARCHAR (50)  NULL,
    [DRCM]     DATETIME      NULL,
    [MODBY]    NVARCHAR (50) NULL,
    [NUM]      REAL          NULL,
    CONSTRAINT [PK_A_COLORS] PRIMARY KEY CLUSTERED ([RGB_CODE] ASC)
);

