CREATE TABLE [dbo].[A_COMPANY_CONTACTS] (
    [ID]          VARCHAR (50)   NOT NULL,
    [FIRST_NAME]  VARCHAR (200)  NULL,
    [LAST_NAME]   VARCHAR (200)  NULL,
    [PHONE]       VARCHAR (50)   NULL,
    [COMPANY_ID]  VARCHAR (50)   NULL,
    [CREATING_CO] VARCHAR (50)   NULL,
    [DRCM]        DATETIME       NULL,
    [MODBY]       VARCHAR (50)   NULL,
    [FULL_NAME]   VARCHAR (3000) NULL,
    CONSTRAINT [PK_A_COMPANY_CONTACTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO


CREATE            TRIGGER A_COMPANY_CONTACTS_INSERT_UPDATE
ON dbo.A_COMPANY_CONTACTS
AFTER INSERT, UPDATE
AS
declare @ID as varchar(50),@FIRST_NAME as varchar(2000),@LAST_NAME as varchar(2000),@FULL_NAME as varchar(2000)
SELECT 	@ID = ID,
	@FIRST_NAME = FIRST_NAME,
	@LAST_NAME = LAST_NAME
FROM INSERTED
set @FULL_NAME = @FIRST_NAME + ' ' + @LAST_NAME
UPDATE A_COMPANY_CONTACTS SET FULL_NAME=@FULL_NAME WHERE ID = @ID

