CREATE TABLE [dbo].[A_COMPANIES_THAT_CAN_VIEW_ME] (
    [ID]            VARCHAR (50) NOT NULL,
    [ME]            VARCHAR (50) NOT NULL,
    [CO_CAN_SEE_ME] VARCHAR (50) NOT NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_COMPANIES_THAT_CAN_VIEW_ME] PRIMARY KEY CLUSTERED ([ID] ASC)
);

