CREATE TABLE [dbo].[A_COMPANIES_IMPORT_OES] (
    [IMPORT_CO_ID] VARCHAR (50) NOT NULL,
    [OE_LOGIN]     VARCHAR (50) NOT NULL,
    [OE_PASSWORD]  VARCHAR (50) NOT NULL,
    [IMPORTER]     VARCHAR (50) NOT NULL,
    [DRCM]         DATETIME     NOT NULL,
    [ID]           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_COMPANIES_IMPORT_OES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

