CREATE TABLE [dbo].[A_DISCUSSION_RESPONSE_ALERTS] (
    [ID]            VARCHAR (50) NOT NULL,
    [DISCUSSION_ID] VARCHAR (50) NOT NULL,
    [R_TYPE]        VARCHAR (50) NOT NULL,
    [ALERTEE_ID]    VARCHAR (50) NOT NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_DISCUSSION_RESPONSE_ALERTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

