CREATE TABLE [dbo].[A_DISCUSSION_ATTACHMENTS] (
    [RESPONSE_ID] VARCHAR (50) NOT NULL,
    [DOC_ID]      VARCHAR (50) NOT NULL,
    [MODBY]       VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL
);

