CREATE TABLE [dbo].[A_DISCUSSION_COLORS] (
    [ID]            VARCHAR (50) NOT NULL,
    [DISCUSSION_ID] VARCHAR (50) NOT NULL,
    [COLOR]         VARCHAR (50) NOT NULL,
    [PERSON_ID]     VARCHAR (50) NOT NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_DISCUSSION_COLORS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

