CREATE TABLE [dbo].[A_DISCUSSION_VIEWED_BY_PEOPLE] (
    [ID]            VARCHAR (50) NOT NULL,
    [DISCUSSION_ID] VARCHAR (50) NOT NULL,
    [PERSON_ID]     VARCHAR (50) NOT NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    [ALERT_ME]      INT          NULL,
    CONSTRAINT [PK_A_DISCUSSION_VIEW_RESPONSE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

