CREATE TABLE [dbo].[A_DISCUSSION_REALLY_INIVTED_COMPANY] (
    [ID]            VARCHAR (50) NOT NULL,
    [DISCUSSION_ID] VARCHAR (50) NULL,
    [COMPANY_ID]    VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_DISCUSSION_REALLY_INIVTED_COMPANY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

