CREATE TABLE [dbo].[A_DISCUSSION_RESPONSE] (
    [ID]            VARCHAR (50)    NOT NULL,
    [DISCUSSION_ID] VARCHAR (50)    NOT NULL,
    [RESPONSE]      NVARCHAR (3800) NULL,
    [PARENT_ID]     VARCHAR (50)    NULL,
    [WRITER]        VARCHAR (50)    NULL,
    [COLOR]         VARCHAR (50)    NULL,
    [DRCM]          DATETIME        NULL,
    [MODBY]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_DISCUSSION_RESPONSE] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE  TRIGGER A_DISCUSSION_RESPONSE_INSERT
ON dbo.A_DISCUSSION_RESPONSE
AFTER INSERT, UPDATE
AS
declare @DID as varchar(50)
SELECT @DID = DISCUSSION_ID FROM INSERTED
UPDATE A_DISCUSSIONS SET LAST_RESPONSE = getDate() WHERE ID = @DID