CREATE TABLE [dbo].[A_DISCUSSION_INV_COMPANY] (
    [DISCUSSION_ID] VARCHAR (50) NULL,
    [COMPANY_ID]    VARCHAR (50) NULL,
    [MODBY]         VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL
);

