CREATE TABLE [dbo].[A_DISCUSSIONS] (
    [ID]            VARCHAR (50)    NOT NULL,
    [SUBJECT]       NVARCHAR (1000) NOT NULL,
    [INITIATOR]     VARCHAR (50)    NOT NULL,
    [DATE_CREATED]  DATETIME        NOT NULL,
    [DRCM]          DATETIME        NULL,
    [MODBY]         VARCHAR (50)    NULL,
    [STATUS]        VARCHAR (50)    NULL,
    [LAST_RESPONSE] DATETIME        NULL,
    CONSTRAINT [PK_A_DISCUSSIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

