CREATE TABLE [dbo].[A_DNR_PART_INFO] (
    [ID]              VARCHAR (50)   NOT NULL,
    [ACT_PART_ID]     VARCHAR (50)   NOT NULL,
    [DNR_ID]          VARCHAR (50)   NOT NULL,
    [DNR_STATUS]      VARCHAR (50)   NULL,
    [ORIG_OWNER_ID]   VARCHAR (50)   NULL,
    [ORIG_OWNER_NAME] VARCHAR (1000) NULL,
    [CUR_OWNER_ID]    VARCHAR (50)   NULL,
    [CUR_OWNER_NAME]  VARCHAR (1000) NULL,
    [TASK_ID]         VARCHAR (50)   NULL,
    CONSTRAINT [PK_A_DNR_PART_INFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

