CREATE TABLE [dbo].[A_DNR_PROC_INFO] (
    [ID]           VARCHAR (50) NOT NULL,
    [DNR_ID]       VARCHAR (50) NOT NULL,
    [PROC_ID]      VARCHAR (50) NOT NULL,
    [PROC_HIST_ID] VARCHAR (50) NOT NULL,
    [PROC_OBJ_ID]  VARCHAR (50) NOT NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [TASK_ID]      VARCHAR (50) NULL
);

