CREATE TABLE [dbo].[A_DNR_TASK_INFO] (
    [ID]         VARCHAR (50) NULL,
    [TASK_ID]    VARCHAR (50) NULL,
    [DNR_ID]     VARCHAR (50) NULL,
    [DNR_STATUS] VARCHAR (50) NULL,
    [TASK_TYPE]  VARCHAR (50) NULL,
    [DRCM]       DATETIME     CONSTRAINT [DF_A_DNR_TASK_INFO_DRCM] DEFAULT (getdate()) NULL
);


GO


CREATE  TRIGGER A_DNR_TASK_INFO_INSER_UPDATE
ON dbo.A_DNR_TASK_INFO
AFTER INSERT, UPDATE
AS
declare @ID as nvarchar(50)
declare @TYP as nvarchar(50)
SELECT @ID = ID,
	@TYP = TASK_TYPE
	FROM INSERTED

IF @TYP = 'CORRECTIVE_ACTION'
	UPDATE A_DNR_TASK_INFO SET TASK_TYPE = 'Corrective Action' WHERE ID = @ID

