CREATE TABLE [dbo].[A_DOCUMENTS] (
    [ID]          VARCHAR (50)    NOT NULL,
    [DOC_ID]      VARCHAR (50)    NOT NULL,
    [NAME]        NVARCHAR (4000) NOT NULL,
    [SOURCE_ID]   VARCHAR (50)    NULL,
    [DRCM]        DATETIME        NULL,
    [MODBY]       VARCHAR (50)    NULL,
    [DELETED]     BIT             NULL,
    [DOC_TYPE]    VARCHAR (50)    NULL,
    [SERVER_PATH] NVARCHAR (4000) NOT NULL,
    [APPROVED]    BIT             NULL,
    [DESCRIPTION] NVARCHAR (4000) NULL,
    [ACTIVE]      BIT             NULL,
    [CONTENTTYPE] NVARCHAR (200)  NULL,
    [OBJECT_ID]   VARCHAR (50)    NULL,
    [CREATOR_ID]  VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_DOCUMENTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE    TRIGGER A_DOCUMENT_INSERT
ON dbo.A_DOCUMENTS
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_DOCUMENTS',@ID,@NAME,@MODBY,null,null,null
UPDATE A_DOCUMENTS SET CREATOR_ID = @MODBY WHERE ID = @ID

GO
CREATE   TRIGGER A_DOCUMENTS_UPDATE
ON dbo.A_DOCUMENTS
AFTER UPDATE
AS
declare @OBJ_ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT  @OBJ_ID = OBJECT_ID,@NAME = NAME,@MODBY = MODBY FROM INSERTED
UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID
