CREATE TABLE [dbo].[A_DOCUMENT_LINK] (
    [ID]            NVARCHAR (50) NOT NULL,
    [LINKED_DOC_ID] VARCHAR (50)  NOT NULL,
    [OBJECT_ID]     VARCHAR (50)  NOT NULL,
    [MODBY]         NVARCHAR (50) NULL,
    [DRCM]          DATETIME      NULL,
    [SHOW_IN_LINE]  BIT           NULL,
    [TYPE]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_DOCUMENT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

