CREATE TABLE [dbo].[A_DURATION_TYPES] (
    [ID]    NVARCHAR (50)  NOT NULL,
    [NAME]  NVARCHAR (100) NULL,
    [DRCM]  DATETIME       NULL,
    [modby] NVARCHAR (50)  NULL,
    [SECS]  FLOAT (53)     NULL,
    CONSTRAINT [PK_A_DURATION_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

