CREATE TABLE [dbo].[A_EMAILS] (
    [ID]         VARCHAR (50)   NOT NULL,
    [ADDY]       NVARCHAR (100) NULL,
    [TYPE]       NVARCHAR (50)  NULL,
    [MODBY]      VARCHAR (50)   NULL,
    [DRCM]       DATETIME       NULL,
    [OBJECT_ID]  VARCHAR (50)   NOT NULL,
    [EMAIL_TYPE] VARCHAR (10)   NULL,
    CONSTRAINT [PK_A_EMAILS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE      TRIGGER A_EMAILS_INSERT
ON dbo.A_EMAILS
AFTER INSERT,UPDATE
AS
declare @objID as nvarchar(50)
SELECT @objID = OBJECT_ID FROM INSERTED
exec A_SP_PEOPLE_UPDATE_PERSON_SEARCH_TABLE @objID

