CREATE TABLE [dbo].[A_ENGINEER_SCREEN_REPORTS] (
    [ID]           VARCHAR (50)   NOT NULL,
    [NAME]         VARCHAR (500)  NOT NULL,
    [FILE_ID]      VARCHAR (50)   NULL,
    [DESCRIPTION]  VARCHAR (2000) NULL,
    [ROOT_COMPANY] VARCHAR (50)   NOT NULL,
    [DATE_ADDED]   DATETIME       NOT NULL,
    [DATE_REMOVED] DATETIME       NULL,
    [ADDED_BY]     VARCHAR (50)   NULL,
    [DRCM]         DATETIME       NULL,
    [MODBY]        VARCHAR (50)   NULL
);

