CREATE TABLE [dbo].[A_FORECAST_ROLL_UP] (
    [ID]     VARCHAR (50) NOT NULL,
    [PARENT] VARCHAR (50) NULL,
    [CHILD]  VARCHAR (50) NULL,
    [DRCM]   DATETIME     NULL,
    [MODBY]  VARCHAR (50) NULL,
    CONSTRAINT [PK_A_FORECAST_ROLL_UP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

