CREATE TABLE [dbo].[A_FORECAST_CUSTOMER_LIST] (
    [ID]          VARCHAR (50) NOT NULL,
    [FORECAST_ID] VARCHAR (50) NULL,
    [CO]          VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_FORECAST_CUSTOMER_LIST] PRIMARY KEY CLUSTERED ([ID] ASC)
);

