CREATE TABLE [dbo].[A_FORECAST_SALES_FUNNEL] (
    [ID]    VARCHAR (50) NOT NULL,
    [NAME]  VARCHAR (50) NULL,
    [DRCM]  DATETIME     NULL,
    [MODBY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_FORECAST_SALES_FUNNEL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

