CREATE TABLE [dbo].[A_FORECAST_ROLLUP_TYPES] (
    [ID]          VARCHAR (50) NOT NULL,
    [FORECAST_ID] VARCHAR (50) NULL,
    [F_TYPE_ID]   VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_FORECAST_ROLLUP_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

