CREATE TABLE [dbo].[A_LAST_UPLOAD_FILE_INFO] (
    [ID]        VARCHAR (50)  NOT NULL,
    [PERSON_ID] VARCHAR (50)  NOT NULL,
    [PAGE_ID]   VARCHAR (200) NOT NULL,
    [CNT]       INT           NULL,
    [drcm]      DATETIME      NULL,
    CONSTRAINT [PK_A_LAST_UPLOAD_FILE_INFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

