CREATE TABLE [dbo].[A_LOCATIONS_CHILD_LOOKUP] (
    [ID]        VARCHAR (50) NULL,
    [LOCATION]  VARCHAR (50) NULL,
    [CHILD_LOC] VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL
);

