CREATE TABLE [dbo].[A_LOCATIONS_RELATED_LOCATIONS] (
    [LOCATION_ID] VARCHAR (50) NULL,
    [RELATED_ID]  VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL
);

