CREATE TABLE [dbo].[A_MACHINE_PART_LOCATION] (
    [ID]    NVARCHAR (50) NOT NULL,
    [NAME]  NVARCHAR (50) NOT NULL,
    [DRCM]  DATETIME      NULL,
    [MODBY] CHAR (10)     NULL,
    CONSTRAINT [PK_A_MACHINE_PART_LOCATION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

