CREATE TABLE [dbo].[A_MACHINE_PART_STATUS_TYPES] (
    [ID]    NVARCHAR (50) NOT NULL,
    [NAME]  NVARCHAR (50) NOT NULL,
    [DRCM]  DATETIME      NULL,
    [MODBY] NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_MACHINE_PART_STATUS_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

