CREATE TABLE [dbo].[A_MENU_ROLES] (
    [MENU_ID] NVARCHAR (50) NOT NULL,
    [ROLE_ID] VARCHAR (50)  NOT NULL,
    [ID]      NVARCHAR (50) NOT NULL,
    [DRCM]    DATETIME      NULL,
    [MODBY]   NVARCHAR (50) NULL,
    [CO]      VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_A_MENU_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

