CREATE TABLE [dbo].[A_MEETING_AGENDA_ITEM_RELATED_OBJECTS] (
    [ID]         VARCHAR (50) NOT NULL,
    [AGENDA_ID]  VARCHAR (50) NULL,
    [REL_OBJECT] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_MEETING_AGENDA_ITEM_RELATED_OBJECTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

