CREATE TABLE [dbo].[A_MEETING_INV_COMPANY] (
    [MEETING_ID] VARCHAR (50) NULL,
    [COMPANY_ID] VARCHAR (50) NULL,
    [MODBY]      VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [ID]         VARCHAR (50) NOT NULL,
    [OPTIONAL]   SMALLINT     NULL,
    CONSTRAINT [PK_A_MEETING_INV_COMPANY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

