CREATE TABLE [dbo].[A_MEETING_RESPONSES] (
    [ID]         VARCHAR (50) NOT NULL,
    [MEETING_ID] VARCHAR (50) NULL,
    [PERSON_ID]  VARCHAR (50) NULL,
    [RESPONSE]   VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_MEETING_RESPONSES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

