CREATE TABLE [dbo].[A_MEETING_AGENDA_ITEM_DOC_LINK] (
    [AGENDA_ID]  VARCHAR (50) NULL,
    [DOC_ID]     VARCHAR (50) NULL,
    [CREATOR_ID] VARCHAR (50) NULL,
    [MODBY]      VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [ID]         VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_MEETING_AGENDA_ITEM_DOC_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

