CREATE TABLE [dbo].[A_MEETING_TOPICS] (
    [ID]         VARCHAR (50) NOT NULL,
    [MEETING_ID] VARCHAR (50) NULL,
    [NOTE_ID]    VARCHAR (50) NULL,
    [DURATION]   FLOAT (53)   NULL,
    [CNT]        INT          NULL,
    CONSTRAINT [PK_A_MEETING_TOPICS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

