CREATE TABLE [dbo].[A_MEETING_AGENDA_KEY_STATEMENTS] (
    [ID]             VARCHAR (50)   NOT NULL,
    [AGENDA_ID]      VARCHAR (50)   NULL,
    [NUM]            REAL           NULL,
    [KEY_STATEMENTS] VARCHAR (4000) NULL,
    [DRCM]           DATETIME       NULL,
    [MODBY]          VARCHAR (50)   NULL,
    CONSTRAINT [PK_A_MEETING_AGENDA_KEY_STATEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

