CREATE TABLE [dbo].[A_MEETING_INV_PEOPLE] (
    [MEETING_ID] VARCHAR (50) NULL,
    [PEOPLE_ID]  VARCHAR (50) NULL,
    [MODBY]      VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [ID]         VARCHAR (50) NOT NULL,
    [OPTIONAL]   SMALLINT     NULL,
    CONSTRAINT [PK_A_MEETING_INV_PEOPLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

