CREATE TABLE [dbo].[A_MONITOR_TEMPLATES_MULT_CHOICE] (
    [ID]           VARCHAR (50)   NOT NULL,
    [MONITOR_ID]   VARCHAR (50)   NOT NULL,
    [TXT]          NVARCHAR (200) NULL,
    [IS_ANSWER]    SMALLINT       NULL,
    [ORD]          INT            NULL,
    [USE_PUT_TEXT] SMALLINT       NULL,
    [DRCM]         DATETIME       NULL,
    [MODBY]        VARCHAR (50)   NULL,
    [ROOT_ID]      VARCHAR (50)   NULL,
    CONSTRAINT [PK__A_KPI_MULTIPLE_C__26DAAD2D] PRIMARY KEY CLUSTERED ([ID] ASC)
);

