CREATE TABLE [dbo].[A_MONITOR_TEXT_THESAURUS] (
    [ID]             VARCHAR (50)   NOT NULL,
    [MON_ROLL_UP_ID] VARCHAR (50)   NULL,
    [MAIN_TEXT]      VARCHAR (2000) NULL,
    [SIMILAR_TEXT]   VARCHAR (2000) NULL,
    [DESCRIPTION]    VARCHAR (2000) NULL,
    CONSTRAINT [PK_A_MONITOR_TEXT_THESAURUS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

