CREATE TABLE [dbo].[A_MONITOR_SKIP_STEPS] (
    [ID]         VARCHAR (50) NOT NULL,
    [MONITOR_ID] VARCHAR (50) NOT NULL,
    [STEP_ID]    VARCHAR (50) NOT NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_MONITOR_SKIP_STEPS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

