CREATE TABLE [dbo].[A_NAV_HISTORY] (
    [ID]      NVARCHAR (50)   NOT NULL,
    [PAGE]    NVARCHAR (50)   NOT NULL,
    [QS]      NVARCHAR (4000) NULL,
    [USER_ID] NVARCHAR (50)   NOT NULL,
    [DRCM]    DATETIME        NULL,
    [MODBY]   NVARCHAR (50)   NULL,
    CONSTRAINT [PK_A_NAV_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

