CREATE TABLE [dbo].[A_NEEDS_PEOPLE_ALLOWED] (
    [ID]        VARCHAR (50) NOT NULL,
    [NEED_ID]   VARCHAR (50) NULL,
    [PERSON_ID] VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_NEEDS_PEOPLE_ALLOWED] PRIMARY KEY CLUSTERED ([ID] ASC)
);

