CREATE TABLE [dbo].[A_NOTE_TEXT_HISTORY] (
    [ID]       VARCHAR (50)    NOT NULL,
    [NOTE_ID]  VARCHAR (50)    NOT NULL,
    [TXT]      NVARCHAR (4000) NULL,
    [DRCM]     DATETIME        NOT NULL,
    [MODBY]    VARCHAR (50)    NULL,
    [REVISION] INT             NULL,
    CONSTRAINT [PK_A_NOTE_TEXT_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

