CREATE TABLE [dbo].[A_NOUN_HIERARCHY_CHILDREN] (
    [ID]              NVARCHAR (50) NOT NULL,
    [ROOT_ID]         NVARCHAR (50) NULL,
    [APPROVED_OBJ_ID] VARCHAR (50)  NULL,
    [PARENT_ID]       NVARCHAR (50) NULL,
    [HIERARCHY_ID]    NVARCHAR (50) NULL,
    [DRCM]            NVARCHAR (50) NULL,
    [MODBY]           NVARCHAR (50) NULL,
    [HIDDEN]          NVARCHAR (20) NULL,
    CONSTRAINT [PK_A_OBJECT_HIERARCHY_CHILDREN] PRIMARY KEY CLUSTERED ([ID] ASC)
);

