CREATE TABLE [dbo].[A_NOTE_FILES] (
    [ID]      VARCHAR (50) NOT NULL,
    [NOTE_ID] VARCHAR (50) NULL,
    [FILE_ID] VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_A_NOTE_FILES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

