CREATE TABLE [dbo].[A_NOTE_ROLES_TO_VIEW] (
    [ID]         VARCHAR (50) NOT NULL,
    [ROLE_ID]    VARCHAR (50) NOT NULL,
    [NOTE_ID]    VARCHAR (50) NOT NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    [CREATED_BY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_NOTE_ROLES_TO_VIEW] PRIMARY KEY CLUSTERED ([ID] ASC)
);

