CREATE TABLE [dbo].[A_NOUN_HIERARCHIES] (
    [ID]             NVARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] NVARCHAR (50) NULL,
    [DRCM]           DATETIME      NULL,
    [MODBY]          NVARCHAR (50) NULL,
    [ROOT_CHILD]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_NOUN_HIERARCHIES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

