CREATE TABLE [dbo].[A_NOTE_CHILDREN] (
    [ID]     VARCHAR (50) NULL,
    [PARENT] VARCHAR (50) NULL,
    [CHILD]  VARCHAR (50) NULL,
    [DRCM]   DATETIME     NULL,
    [MODBY]  VARCHAR (50) NULL
);

