CREATE TABLE [dbo].[A_NOTE_RELATIONS] (
    [ID]         VARCHAR (50) NOT NULL,
    [NOTE_ID]    VARCHAR (50) NULL,
    [RELATED_TO] VARCHAR (20) NULL,
    [IS_ITEM]    TINYINT      NULL,
    CONSTRAINT [PK_A_NOTE_RELATIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

