CREATE TABLE [dbo].[A_NOTE_PEOPLE_TO_VIEW] (
    [ID]         VARCHAR (50) NOT NULL,
    [NOTE_ID]    VARCHAR (50) NOT NULL,
    [PERSON_ID]  VARCHAR (50) NOT NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    [IS_READ]    TINYINT      NULL,
    [CREATED_BY] VARCHAR (50) NULL
);

