CREATE TABLE [dbo].[A_OBJECT_RELATIONS] (
    [ID]        NVARCHAR (50) NOT NULL,
    [CHILD_ID]  VARCHAR (50)  NOT NULL,
    [PARENT_ID] VARCHAR (50)  NOT NULL,
    [DRCM]      DATETIME      NULL,
    [MODBY]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_OBJECT_RELATIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

