CREATE TABLE [dbo].[A_OBJECT_HIERARCHIES] (
    [ID]        NVARCHAR (50)  NOT NULL,
    [PARENT]    NVARCHAR (50)  NULL,
    [OBJ_ID]    VARCHAR (50)   NOT NULL,
    [TYPE]      NVARCHAR (50)  NOT NULL,
    [DRCM]      SMALLDATETIME  NULL,
    [MODBY]     NVARCHAR (50)  NULL,
    [NAME]      NVARCHAR (100) NULL,
    [OBJECT_ID] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_A_OBJECT_HIERARCHIES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

