CREATE TABLE [dbo].[A_OBJECT_EXTERNAL_REF] (
    [ID]              VARCHAR (50)  NOT NULL,
    [HISTORY_ID]      VARCHAR (50)  NULL,
    [ROOT_OBJ_ID]     VARCHAR (50)  NULL,
    [ITEM_TABLE]      VARCHAR (50)  NULL,
    [EXTERNAL_REF_ID] VARCHAR (100) NULL,
    [DRCM]            DATETIME      NULL,
    [MODBY]           VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_OBJECT_EXTERNAL_REF] PRIMARY KEY CLUSTERED ([ID] ASC)
);

