CREATE TABLE [dbo].[A_OBJECT_ITEM_LINK] (
    [ID]        VARCHAR (50) NOT NULL,
    [OBJECT_ID] VARCHAR (50) NOT NULL,
    [ITEM_ID]   VARCHAR (50) NOT NULL,
    [ITEM_TYPE] VARCHAR (50) NOT NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_OBJECT_ITEM_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

