CREATE TABLE [dbo].[A_ORDER_ITEMS_PURCHASE_DATA] (
    [ORDER_ITEM_ID]     VARCHAR (50) NOT NULL,
    [PRODUCT_HIST_ID]   VARCHAR (50) NULL,
    [PROCEDURE_HIST_ID] VARCHAR (50) NULL,
    [DRCM]              DATETIME     NULL,
    [MODBY]             VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ORDER_ITEMS_PURCHASE_DATA] PRIMARY KEY CLUSTERED ([ORDER_ITEM_ID] ASC)
);

