CREATE TABLE [dbo].[A_ORDER_SUPPLIER_SUMMARY] (
    [ID]           VARCHAR (50) NOT NULL,
    [ORDER_ID]     VARCHAR (50) NOT NULL,
    [SUPPLIER_ID]  VARCHAR (50) NULL,
    [NUM_SUPPLIED] INT          NULL,
    [TOTAL_PRICE]  REAL         NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ORDER_SUPPLIER_SUMMARY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

