CREATE TABLE [dbo].[A_ORDERS_HISTORY] (
    [ID]              VARCHAR (50)   NOT NULL,
    [OBJECT_ID]       VARCHAR (50)   NULL,
    [CUSTOMER_PERSON] VARCHAR (50)   NULL,
    [CUSTOMER_CO]     VARCHAR (50)   NULL,
    [DESCRIPTION]     NVARCHAR (500) NULL,
    [BUDGETARY_ONLY]  SMALLINT       NULL,
    [EXPIRATION_DATE] DATETIME       NULL,
    [DRCM]            DATETIME       NULL,
    [MODBY]           VARCHAR (50)   NULL,
    [PROGRESS]        VARCHAR (50)   NULL,
    [RFQ_ID]          VARCHAR (50)   NULL,
    [SUPPLIER_ID]     VARCHAR (50)   NULL,
    [CREATION_DATE]   DATETIME       NULL,
    [PERSON_SUPPLIER] VARCHAR (50)   NULL,
    [TYPE]            VARCHAR (50)   NULL,
    [PRICE]           MONEY          NULL,
    CONSTRAINT [PK_A_ORDERS_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);










GO

CREATE           TRIGGER A_ORDERS_HISTORY_INSERT
ON dbo.A_ORDERS_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = DESCRIPTION FROM INSERTED

print 'the name of the PA = ' + @NAME

exec A_SP_OBJECT_ADD 'A_ORDERS_HISTORY',@ID,@NAME,@MODBY,null,null,null


GO

CREATE TRIGGER [dbo].[A_ORDERS_HISTORY_UPDATE]
ON [dbo].[A_ORDERS_HISTORY]
AFTER UPDATE
AS

DECLARE @OBJ_ID AS NVARCHAR(50)
DECLARE @ID AS NVARCHAR(50)
DECLARE @NAME AS NVARCHAR(50)
DECLARE @MODBY AS NVARCHAR(50), @OLDCO AS VARCHAR(50), @NEWCO VARCHAR(50)

PRINT 'IN THE ORDERS HISTORY UPDATE TRIGGER'

SELECT	  @ID = ID
		, @OBJ_ID = [OBJECT_ID]
		, @NAME = [DESCRIPTION]
		, @MODBY = MODBY
		, @NEWCO = CUSTOMER_CO 
FROM INSERTED

PRINT ' THIS NAME IS ' + @NAME

DECLARE @MYOBJNAME AS NVARCHAR(100)

SELECT @MYOBJNAME = OBJ_DESC
FROM A_OBJECTS
WHERE ID = @OBJ_ID

IF @MYOBJNAME <> @NAME
BEGIN
	UPDATE A_OBJECTS SET
	OBJ_DESC = @NAME,
	MODBY = @MODBY,
	DRCM = GETDATE()
	WHERE ID = @OBJ_ID
END

GO

GO

GO


