CREATE TABLE [dbo].[A_ORDER_ITEM_PRECEDENTS] (
    [ID]    VARCHAR (50) NOT NULL,
    [PREV]  VARCHAR (50) NULL,
    [FOL]   VARCHAR (50) NULL,
    [DRCM]  DATETIME     NULL,
    [MODBY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ORDER_ITEM_PRECEDENTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

