CREATE TABLE [dbo].[A_ORDERS_HISTORY] (
    [ID]              VARCHAR (50)   NOT NULL,
    [OBJECT_ID]       VARCHAR (50)   NULL,
    [CUSTOMER_PERSON] VARCHAR (50)   NULL,
    [CUSTOMER_CO]     VARCHAR (50)   NULL,
    [DESCRIPTION]     NVARCHAR (500) NULL,
    [BUDGETARY_ONLY]  SMALLINT       NULL,
    [EXPIRATION_DATE] DATETIME       NULL,
    [DRCM]            DATETIME       NULL,
    [MODBY]           VARCHAR (50)   NULL,
    [PROGRESS]        VARCHAR (50)   NULL,
    [RFQ_ID]          VARCHAR (50)   NULL,
    [SUPPLIER_ID]     VARCHAR (50)   NULL,
    [CREATION_DATE]   DATETIME       NULL,
    [PERSON_SUPPLIER] VARCHAR (50)   NULL,
    [TYPE]            VARCHAR (50)   NULL,
    [PRICE]           MONEY          NULL,
    CONSTRAINT [PK_A_ORDERS_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);










GO

CREATE           TRIGGER A_ORDERS_HISTORY_INSERT
ON dbo.A_ORDERS_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = DESCRIPTION FROM INSERTED

print 'the name of the PA = ' + @NAME

exec A_SP_OBJECT_ADD 'A_ORDERS_HISTORY',@ID,@NAME,@MODBY,null,null,null


GO


CREATE TRIGGER [dbo].[A_ORDERS_HISTORY_UPDATE]
ON [dbo].[A_ORDERS_HISTORY]
AFTER UPDATE
AS

DECLARE @OBJ_ID AS NVARCHAR(50)
DECLARE @ID AS NVARCHAR(50)
DECLARE @NAME AS NVARCHAR(50)
DECLARE @MODBY AS NVARCHAR(50), @OLDCO AS VARCHAR(50), @NEWCO VARCHAR(50)

PRINT 'IN THE ORDERS HISTORY UPDATE TRIGGER'

SELECT	  @ID = ID
		, @OBJ_ID = [OBJECT_ID]
		, @NAME = [DESCRIPTION]
		, @MODBY = MODBY
		, @NEWCO = CUSTOMER_CO 
FROM INSERTED

PRINT ' THIS NAME IS ' + @NAME

DECLARE @MYOBJNAME AS NVARCHAR(100)

SELECT @MYOBJNAME = OBJ_DESC
FROM A_OBJECTS
WHERE ID = @OBJ_ID

IF @MYOBJNAME <> @NAME
BEGIN
	UPDATE A_OBJECTS SET
	OBJ_DESC = @NAME,
	MODBY = @MODBY,
	DRCM = GETDATE()
	WHERE ID = @OBJ_ID
END

-- JUSTIN - BUG FIX - MAKE SURE TO UPDATE THE PRODUCTS ON THE PURCHASE ORDER TO THE LATEST

DECLARE @NEW_ORDER_ID_BEING_INSERTED VARCHAR(50)

DECLARE @PRODUCT_ROOT_ID VARCHAR(50)
DECLARE @TOTAL_RELATED_REVISED_PRODUCTS INT

SET @NEW_ORDER_ID_BEING_INSERTED = @OBJ_ID

IF EXISTS (SELECT 'T' FROM A_OBJECTS WHERE ID = @NEW_ORDER_ID_BEING_INSERTED AND [STATUS] LIKE '%APPROVED%')
BEGIN

	SELECT @PRODUCT_ROOT_ID = [ROOT]
	FROM A_PRODUCTS_HISTORY PH
	INNER JOIN A_OBJECTS O ON O.ID = PH.OBJECT_ID
	INNER JOIN A_PRODUCTS_QUICK_PRICE QP ON QP.PROD_HIST_ID = PH.ID
	--INNER JOIN A_QUOTES_HISTORY QH ON QH.ID = QP.QUOTE_ID
	INNER JOIN A_ORDERS_HISTORY OH ON OH.OBJECT_ID = QP.ORDER_ID
	WHERE OH.OBJECT_ID = @NEW_ORDER_ID_BEING_INSERTED

	SELECT @TOTAL_RELATED_REVISED_PRODUCTS = COUNT(*)
	FROM A_OBJECTS O
	WHERE O.[ROOT] = @PRODUCT_ROOT_ID

	--SELECT DISTINCT OH.OBJECT_ID AS ORDERID
	--FROM A_PRODUCTS_HISTORY PH
	--INNER JOIN A_OBJECTS O ON O.ID = PH.OBJECT_ID
	--INNER JOIN A_PRODUCTS_QUICK_PRICE QP ON QP.PROD_HIST_ID = PH.ID
	--INNER JOIN A_ORDERS_HISTORY OH ON OH.OBJECT_ID = QP.ORDER_ID
	--WHERE O.[ROOT] = @PRODUCT_ROOT_ID
	--ORDER BY OH.OBJECT_ID

	IF @TOTAL_RELATED_REVISED_PRODUCTS >= 1
	BEGIN
		UPDATE A_ACCOUNT_PURCHASABLE_ORDERS_LINK SET
		ORDER_ID = @NEW_ORDER_ID_BEING_INSERTED
		WHERE ORDER_ID IN (
							SELECT DISTINCT OH.OBJECT_ID AS ORDERID
							FROM A_PRODUCTS_HISTORY PH
							INNER JOIN A_OBJECTS O ON O.ID = PH.OBJECT_ID
							INNER JOIN A_PRODUCTS_QUICK_PRICE QP ON QP.PROD_HIST_ID = PH.ID
							INNER JOIN A_ORDERS_HISTORY OH ON OH.OBJECT_ID = QP.ORDER_ID
							WHERE	O.[ROOT] = @PRODUCT_ROOT_ID
							AND		OH.OBJECT_ID <> @NEW_ORDER_ID_BEING_INSERTED
						  )

		-- SELECT *
		-- FROM A_PURCHASES_HISTORY PH
		UPDATE A_PURCHASES_HISTORY SET
		ORDER_ID = @NEW_ORDER_ID_BEING_INSERTED
		WHERE ORDER_ID IN (
							SELECT DISTINCT OH.OBJECT_ID AS ORDERID
							FROM A_PRODUCTS_HISTORY PH
							INNER JOIN A_OBJECTS O ON O.ID = PH.OBJECT_ID
							INNER JOIN A_PRODUCTS_QUICK_PRICE QP ON QP.PROD_HIST_ID = PH.ID
							INNER JOIN A_ORDERS_HISTORY OH ON OH.OBJECT_ID = QP.ORDER_ID
							WHERE	O.[ROOT] = @PRODUCT_ROOT_ID
							AND		OH.OBJECT_ID <> @NEW_ORDER_ID_BEING_INSERTED
						  )
		AND ID NOT IN	  (
							-- IF THE PURCHASE HISTORY ID IS IN THIS LIST, THEN THAT MEANS IT HAS WORK-IN-PROGRESS
							SELECT DISTINCT PH.ID AS PURCHASE_HISTORY_ID
							FROM A_PURCHASES_HISTORY PH
							INNER JOIN A_TASK_ORDER_INFORMATION TOI ON TOI.PURCHASE_HIST_ID = PH.ID
							INNER JOIN A_TASKS T ON T.ID = TOI.TASK_ID
							WHERE	T.[STATUS] NOT IN ('PENDING_PARENT_ACCEPTANCE', 'REQUESTED')
							AND		T.PARENT_ID IS NOT NULL
						  )

	END

END

GO

GO

GO


