CREATE TABLE [dbo].[A_ORDERS_SUPPLIERS_TO_SHARE_WITH] (
    [ID]          VARCHAR (50) NOT NULL,
    [SUPPLIER_ID] VARCHAR (50) NULL,
    [ORDER_ID]    VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ORDERS_SUPPLIERS_TO_SHARE_WITH] PRIMARY KEY CLUSTERED ([ID] ASC)
);

