CREATE TABLE [dbo].[A_ORDER_ITEM_SHIP_TRAV_LINK] (
    [ID]              VARCHAR (50) NOT NULL,
    [SHIP_ORDER_ITEM] VARCHAR (50) NULL,
    [SHIPPING_ITEM]   VARCHAR (50) NULL,
    [MODBY]           VARCHAR (50) NULL,
    [DRCM]            DATETIME     NULL,
    [TYP]             VARCHAR (50) NULL,
    [DEST]            VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ORDER_ITEM_SHIPPING_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

