CREATE TABLE [dbo].[A_OUTSIDE_EMAIL_LINK] (
    [ID]           NVARCHAR (50) NOT NULL,
    [EMAIL_ID]     NVARCHAR (50) NOT NULL,
    [LINKED_ID]    NVARCHAR (50) NOT NULL,
    [LINKED_TABLE] NVARCHAR (50) NOT NULL,
    [DRCM]         DATETIME      NULL,
    [MODBY]        NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_OUTSIDE_EMAIL_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

