CREATE TABLE [dbo].[A_OUTSIDE_EMAIL_ADDRESSES] (
    [ID]         NVARCHAR (50) NOT NULL,
    [FIRST_NAME] NVARCHAR (50) NULL,
    [LAST_NAME]  NVARCHAR (50) NULL,
    [ADDY]       NVARCHAR (50) NOT NULL,
    [DRCM]       DATETIME      NULL,
    [modby]      NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_OUTSIDE_EMAIL_ADDRESSES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

