CREATE TABLE [dbo].[A_PARTS_SAFETY_STOCK_ROLES] (
    [SAFETY_STOCK_ID] VARCHAR (50) NOT NULL,
    [ROLE_ID]         VARCHAR (50) NOT NULL,
    [EMAIL_TYPE]      VARCHAR (50) NULL,
    [DRCM]            DATETIME     NULL,
    [MODBY]           VARCHAR (50) NULL,
    [ID]              VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_PARTS_SAFETY_STOCK_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

