CREATE TABLE [dbo].[A_PARTS_FUTURE_SPECIAL_DISTRIBUTIONS] (
    [ID]      VARCHAR (50) NULL,
    [PART_ID] VARCHAR (50) NULL,
    [SPEC_ID] VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL
);

