CREATE TABLE [dbo].[A_PARTS_INTERNAL_EQUALS] (
    [ID]            VARCHAR (50) NOT NULL,
    [PART_ID]       VARCHAR (50) NULL,
    [EQUAL_PART_ID] VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PARTS_INTERNAL_EQUALS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

