CREATE TABLE [dbo].[A_PARTS_FUTURE_CUSTOMERS] (
    [ID]      VARCHAR (50) NULL,
    [PART_ID] VARCHAR (50) NULL,
    [CUST_ID] VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL
);

