CREATE TABLE [dbo].[A_PARTS_SUB_PARTS] (
    [ID]        VARCHAR (50)   NOT NULL,
    [PART_ID]   VARCHAR (50)   NULL,
    [DRCM]      DATETIME       NULL,
    [MODBY]     VARCHAR (50)   NULL,
    [QTY]       FLOAT (53)     NULL,
    [PARENT]    VARCHAR (50)   NULL,
    [NICK_NAME] NVARCHAR (200) NULL,
    CONSTRAINT [PK_A_PARTS_SUB_PARTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

