CREATE TABLE [dbo].[A_PAGE_PERMISSIONS] (
    [ID]        NVARCHAR (50) NOT NULL,
    [OBJ_ID]    NVARCHAR (50) NOT NULL,
    [ROLE_ID]   NVARCHAR (50) NULL,
    [DRCM]      DATETIME      NULL,
    [MODBY]     NVARCHAR (50) NULL,
    [PERM_TYPE] NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_PAGE_PERMISSIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

