CREATE TABLE [dbo].[A_PARTS_FUTURE_EXCEPTIONS] (
    [ID]      VARCHAR (50) NOT NULL,
    [CUST_ID] VARCHAR (50) NULL,
    [PART_ID] VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PARTS_FUTURE_EXCEPTIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

