CREATE TABLE [dbo].[A_PEOPLE_PAGE_TRACKING] (
    [ID]          VARCHAR (50)   NOT NULL,
    [USER_ID]     VARCHAR (50)   NOT NULL,
    [PAGE]        VARCHAR (900)  NOT NULL,
    [DRCM]        DATETIME       NOT NULL,
    [QUERYSTRING] VARCHAR (2000) NULL,
    CONSTRAINT [PK_A_PEOPLE_PAGE_TRACKING] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_A_PEOPLE_PAGE_TRACKING]
    ON [dbo].[A_PEOPLE_PAGE_TRACKING]([PAGE] ASC);

