CREATE TABLE [dbo].[A_PEOPLES_FAVORITES] (
    [ID]    NVARCHAR (50) NOT NULL,
    [GROUP] NVARCHAR (50) NOT NULL,
    [ITEM]  NVARCHAR (50) NOT NULL,
    [MODBY] NVARCHAR (50) NULL,
    [DRCM]  DATETIME      NULL,
    [NUM]   NUMERIC (18)  NULL,
    CONSTRAINT [PK__A_PEOPLES_FAVORI__540C7B00] PRIMARY KEY CLUSTERED ([ID] ASC)
);

