CREATE TABLE [dbo].[A_PEOPLE_SUB_LOOKUP_TABLE] (
    [ID]          VARCHAR (50) NOT NULL,
    [BOSS]        VARCHAR (50) NOT NULL,
    [SUBORDINATE] VARCHAR (50) NOT NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_SUBORDINATES_LOOKUP_TABLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

