CREATE TABLE [dbo].[A_PEOPLES_FAVORITE_GROUPS] (
    [ID]         NVARCHAR (50)  NOT NULL,
    [FAV_TYPE]   NVARCHAR (100) NOT NULL,
    [GROUP_NAME] NVARCHAR (200) NOT NULL,
    [PERSON]     VARCHAR (50)   NOT NULL,
    [MODBY]      NVARCHAR (50)  NULL,
    [DRCM]       DATETIME       NULL,
    CONSTRAINT [PK__A_PEOPLES_FAVORI__208CD6FA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

