CREATE TABLE [dbo].[A_PEOPLE_LINKED_LOGINS] (
    [ID]          VARCHAR (50)  NOT NULL,
    [ROOT_ID]     VARCHAR (50)  NOT NULL,
    [LINKED_ID]   VARCHAR (50)  NOT NULL,
    [NICK_NAME]   VARCHAR (100) NULL,
    [LINKED_PASS] NVARCHAR (50) NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_PEOPLE_LINKED_LOGINS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

