CREATE TABLE [dbo].[A_PEOPLE_NEW_UNENCRYPTED_PASSWORDS] (
    [ID]             VARCHAR (50) NOT NULL,
    [OBJECT_ID]      VARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] VARCHAR (50) NOT NULL,
    [PASSWORD]       VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL
);

