CREATE TABLE [dbo].[A_PEOPLE] (
    [ID]             VARCHAR (50) NOT NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [STATUS]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PEOPLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE          TRIGGER A_PEOPLE_UPDATE
ON dbo.A_PEOPLE
AFTER UPDATE
AS

declare @ID as nvarchar(50)
declare @HIST_ID as nvarchar(50)
declare @NAME as nvarchar(50)
print 'In the Poeple History Update Trigger'
SELECT
@ID = ID,
@HIST_ID = HISTORY_REF_ID
FROM INSERTED

SELECT @NAME = FULL_NAME FROM A_PEOPLE_HISTORY WHERE ID = @HIST_ID
UPDATE A_OBJECTS SET LOCKED_BY_NAME = @NAME WHERE LOCKED_BY = @ID

