CREATE TABLE [dbo].[A_PHONE_NUMBERS] (
    [ID]              VARCHAR (50)  NOT NULL,
    [PHONE_NUMBER]    NVARCHAR (50) NULL,
    [PHONE_TYPE]      VARCHAR (50)  NULL,
    [PHONE_PIN]       NVARCHAR (50) NULL,
    [PHONE_EXTENSION] NVARCHAR (50) NULL,
    [MODBY]           VARCHAR (50)  NULL,
    [DRCM]            DATETIME      NULL,
    [OBJECT_ID]       VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_PHONE_NUMBERS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE      TRIGGER A_PHONE_NUMBERS_INSERT
ON dbo.A_PHONE_NUMBERS
AFTER INSERT,UPDATE
AS
declare @objID as nvarchar(50)
SELECT @objID = OBJECT_ID FROM INSERTED
exec A_SP_PEOPLE_UPDATE_PERSON_SEARCH_TABLE @objID

