CREATE TABLE [dbo].[A_PROPOSAL_CONTACTS] (
    [PROP_HIST_ID] VARCHAR (50) NULL,
    [CONTACT_ID]   VARCHAR (50) NULL,
    [ADDRESS_TO]   TINYINT      NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [ID]           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_PROPOSAL_CONTACTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

