CREATE TABLE [dbo].[A_PROD_REQ_FORM_DATES] (
    [ID]        VARCHAR (50) NOT NULL,
    [PRF]       VARCHAR (50) NULL,
    [DATE_TYPE] VARCHAR (50) NULL,
    [DT]        DATETIME     NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    [PERSON]    VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROD_REQ_FORM_DATES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

