CREATE TABLE [dbo].[A_PROPOSALS_HISTORY] (
    [ID]              VARCHAR (50)   NOT NULL,
    [OBJECT_ID]       VARCHAR (50)   NULL,
    [CUSTOMER_CO]     VARCHAR (50)   NOT NULL,
    [SUPPLIER_CO]     VARCHAR (50)   NOT NULL,
    [PROP_DATE]       DATETIME       NULL,
    [PROP_VALID_DATE] DATETIME       NULL,
    [NAME]            VARCHAR (500)  NULL,
    [DRCM]            DATETIME       NULL,
    [MODBY]           VARCHAR (50)   NULL,
    [OPENING]         VARCHAR (1000) NULL,
    [ADD_NOTES]       VARCHAR (1000) NULL,
    [CLOSING]         VARCHAR (1000) NULL,
    [CREATOR_ID]      VARCHAR (50)   NULL,
    [CREATOR_TITLE]   VARCHAR (1000) NULL,
    CONSTRAINT [PK_A_PROPOSALS_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE TRIGGER A_PROPOSALS_HISTORY_INSERT
ON dbo.A_PROPOSALS_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_PROPOSALS_HISTORY',@ID,@NAME,@MODBY,null,null,null

GO






CREATE              TRIGGER A_PROPOSALS_HISTORY_UPDATE
ON dbo.A_PROPOSALS_HISTORY
AFTER UPDATE
AS
declare @OBJ_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT
@ID = ID,
@OBJ_ID = OBJECT_ID,
@NAME = NAME,
@MODBY = MODBY
FROM INSERTED

UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID

