CREATE TABLE [dbo].[A_PREPOP_HISTORY] (
    [ID]           VARCHAR (50)  NOT NULL,
    [DRCM]         DATETIME      NULL,
    [MODBY]        NVARCHAR (50) NULL,
    [OBJECT_ID]    VARCHAR (50)  NULL,
    [PROC_STEP_ID] VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_PREPOP_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO


CREATE     TRIGGER A_PREPOP_HISTORY_INSERT
ON dbo.A_PREPOP_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @TEXT as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@TEXT = PROC_STEP_ID FROM INSERTED
exec A_SP_OBJECT_ADD 'A_PREPOP_HISTORY',@ID,@TEXT,@MODBY,null,null,null



GO



CREATE      TRIGGER A_PREPOP_HISTORY_UPDATE
ON dbo.A_PREPOP_HISTORY
AFTER UPDATE
AS

declare @OBJ_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @TEXT as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT
@ID = ID,
@OBJ_ID = OBJECT_ID,
@TEXT = PROC_STEP_ID,
@MODBY = MODBY
FROM INSERTED
if update(PROC_STEP_ID)
begin
UPDATE A_OBJECTS SET
OBJ_DESC = @TEXT,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID
end


