CREATE TABLE [dbo].[A_PROPOSALS_QUOTE_LINK] (
    [PROP_HIST_ID] VARCHAR (50) NULL,
    [QUOTE_ID]     VARCHAR (50) NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [ID]           VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_PROPOSALS_QUOTE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

