CREATE TABLE [dbo].[A_PROD_PRICE_LIST_SUB_PRICE_LISTS] (
    [ID]              VARCHAR (50) NOT NULL,
    [PARENT]          VARCHAR (50) NOT NULL,
    [CHILD]           VARCHAR (50) NULL,
    [DRCM]            DATETIME     NULL,
    [MODBY]           VARCHAR (50) NULL,
    [APPROVED_OBJ_ID] VARCHAR (50) NOT NULL,
    [QTY]             REAL         NULL,
    [RELATIONSHIP]    VARCHAR (50) NOT NULL,
    [UNIT_TYPE]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROD_PRICE_LIST_SUB_PRICE_LISTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

