CREATE TABLE [dbo].[A_PROCEDURE_STEP_DESTINATION_TYPES] (
    [ID]    NVARCHAR (50)  NOT NULL,
    [NAME]  NVARCHAR (100) NULL,
    [DRCM]  DATETIME       NULL,
    [MODBY] NVARCHAR (50)  NULL,
    [NUM]   SMALLINT       NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEP_DESTINATION_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

