CREATE TABLE [dbo].[A_PROCEDURE_STEP_FILE_LINK] (
    [ID]      NVARCHAR (50) NOT NULL,
    [STEP_ID] VARCHAR (50)  NULL,
    [FILE_ID] VARCHAR (50)  NULL,
    [DRCM]    DATETIME      NULL,
    [MODBY]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEP_FILE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

