CREATE TABLE [dbo].[A_PROCEDURE_STEP_THEORY_LINK] (
    [ID]           VARCHAR (50) NULL,
    [PROC_STEP_ID] VARCHAR (50) NULL,
    [THEORY_ID]    VARCHAR (50) NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL
);




GO
CREATE NONCLUSTERED INDEX [IX_A_PROCEDURE_STEP_THEORY_LINK_EXECPLAN_02]
    ON [dbo].[A_PROCEDURE_STEP_THEORY_LINK]([PROC_STEP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_A_PROCEDURE_STEP_THEORY_LINK_EXECPLAN_01]
    ON [dbo].[A_PROCEDURE_STEP_THEORY_LINK]([PROC_STEP_ID] ASC);

