CREATE TABLE [dbo].[A_PROCEDURE_STEPS] (
    [ID]                 VARCHAR (50)    NOT NULL,
    [PROCEDURE_ID]       VARCHAR (50)    NULL,
    [STEP_TEXT]          NVARCHAR (4000) NULL,
    [START_ON_COUNTER]   INT             CONSTRAINT [DF_A_PROCEDURE_STEPS_START_ON_COUNTER] DEFAULT ((0)) NULL,
    [COUNTER_VALUE]      NUMERIC (18)    NULL,
    [COUNTER_UNIT]       NVARCHAR (100)  NULL,
    [REL_OR_ABS]         NVARCHAR (10)   NULL,
    [FROM_START_OR_STOP] NVARCHAR (10)   NULL,
    [SYSTEM_TASK]        VARCHAR (50)    NULL,
    [DESTINATION]        NVARCHAR (50)   NULL,
    [SPECIFIC_LOCATION]  VARCHAR (50)    NULL,
    [REFERENCE_VERB]     NVARCHAR (50)   NULL,
    [REFERENCE_OBJECT]   NVARCHAR (50)   NULL,
    [COMMENTS]           NVARCHAR (2000) NULL,
    [GOTO_STEP]          INT             NULL,
    [GOTO_STEP_ID]       VARCHAR (50)    NULL,
    [CYCLES]             NVARCHAR (50)   NULL,
    [CYCLE_ON_COUNTER]   INT             CONSTRAINT [DF_A_PROCEDURE_STEPS_CYCLE_ON_COUNTER] DEFAULT ((0)) NULL,
    [CYCLE_COUNT]        NUMERIC (18)    NULL,
    [CYCLE_UNIT]         NVARCHAR (50)   NULL,
    [DRCM]               DATETIME        NULL,
    [MODBY]              NVARCHAR (50)   NULL,
    [PRINT_ORDER]        FLOAT (53)      NULL,
    [OLD_PROCEDURE_ID]   VARCHAR (50)    NULL,
    [OLD_STEP_ID]        NVARCHAR (50)   NULL,
    [DURATION]           FLOAT (53)      NULL,
    [DURATION_TYPE]      VARCHAR (50)    NULL,
    [DATE_LAST_MODIFIED] DATETIME        NULL,
	[TITLE]      VARCHAR (250)    NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEPS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE TRIGGER A_PROCEDURE_STEPS_UPDATE_INSERT
ON dbo.A_PROCEDURE_STEPS
AFTER UPDATE,INSERT
AS
declare @procID as nvarchar(50)
print 'In A_PROCEDURE_STEPS_UPDATE_INSERT'
SELECT
@procID = PROCEDURE_ID
FROM INSERTED
exec A_SP_PROCEDURE_ROLL_UP_DURATION @procID
