CREATE TABLE [dbo].[A_PROD_PRICE_LIST_VOLUME_DISC] (
    [ID]            VARCHAR (50) NOT NULL,
    [PRICE_LIST_ID] VARCHAR (50) NULL,
    [DISCOUNT]      REAL         NULL,
    [MIN_PUR_QTY]   INT          NULL,
    [DRCM]          VARCHAR (50) NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROD_PRICE_LIST_VOLUME_DISC] PRIMARY KEY CLUSTERED ([ID] ASC)
);

