CREATE TABLE [dbo].[A_PROD_PRICE_LIST_EXTRA_COSTS] (
    [ID]              VARCHAR (50)    NOT NULL,
    [PROD_PRICE_LIST] VARCHAR (50)    NULL,
    [DESCRIPTION]     NVARCHAR (1000) NULL,
    [PRICE_LIST_TYPE] VARCHAR (20)    NULL,
    [DRCM]            DATETIME        NULL,
    [MODBY]           VARCHAR (50)    NULL,
    [UNIT]            VARCHAR (50)    NULL,
    [UNIT_PRICE]      MONEY           NULL,
    CONSTRAINT [PK_A_PROD_PRICE_LIST_EXTRA_COSTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

