CREATE TABLE [dbo].[A_PROJECT_ITEM_LINK] (
    [ID]         VARCHAR (50) NOT NULL,
    [PROJECT_ID] VARCHAR (50) NOT NULL,
    [ITEM_ID]    VARCHAR (50) NOT NULL,
    [ITEM_TYPE]  VARCHAR (50) NOT NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROJECT_ITEM_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

