CREATE TABLE [dbo].[A_PROCEDURE_STEP_PROCEDURE_LINK] (
    [ID]             NVARCHAR (50) NOT NULL,
    [PROCEDURE_STEP] VARCHAR (50)  NULL,
    [PROCEDURE_LINK] VARCHAR (50)  NULL,
    [DRCM]           DATETIME      NULL,
    [MODBY]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEP_PROCEDURE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

