CREATE TABLE [dbo].[A_PROCEDURE_STEP_PRECEDING_STEPS] (
    [ID]               VARCHAR (50) NOT NULL,
    [MY_STEP]          VARCHAR (50) NOT NULL,
    [PREV_STEP]        VARCHAR (50) NOT NULL,
    [DRCM]             DATETIME     NULL,
    [MODBY]            VARCHAR (50) NULL,
    [PROCEDURE_ID]     VARCHAR (50) NOT NULL,
    [OLD_PROCEDURE_ID] VARCHAR (50) NULL,
    [OLD_STEP_ID]      VARCHAR (50) NULL,
    [OLD_PREV_STEP_ID] VARCHAR (50) NULL,
    [DELAY_VAL]        FLOAT (53)   NULL,
    [DELAY_UNIT]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEP_PRECEDING_STEPS] PRIMARY KEY CLUSTERED ([ID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_A_PROCEDURE_STEP_PRECEDING_STEPS_EXECPLAN_01]
    ON [dbo].[A_PROCEDURE_STEP_PRECEDING_STEPS]([MY_STEP] ASC);

