CREATE TABLE [dbo].[A_PROD_PRICE_LIST_SPECIAL_DISTRIBUTIONS] (
    [ID]         VARCHAR (50) NOT NULL,
    [SPEC_ID]    VARCHAR (50) NULL,
    [PP_LIST_ID] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROD_PRICE_LIST_SPECIAL_DISTRIBUTIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

