CREATE TABLE [dbo].[A_PROJECT_SPONSORS] (
    [ID]         VARCHAR (50) NOT NULL,
    [PROJECT_ID] VARCHAR (50) NOT NULL,
    [PEOPLE_ID]  VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROJECT_SPONSORS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

