CREATE TABLE [dbo].[A_PROD_REQ_FORMS] (
    [ID]             VARCHAR (50)    NOT NULL,
    [FILE_ID]        VARCHAR (50)    NULL,
    [FILE_KEYWORDS]  NVARCHAR (4000) NULL,
    [CUST_PERSON_ID] VARCHAR (50)    NULL,
    [CUSTOMER_CO]    VARCHAR (50)    NULL,
    [RESULT_PRODUCT] VARCHAR (50)    NULL,
    [DRCM]           DATETIME        NULL,
    [MODBY]          VARCHAR (50)    NULL,
    [DATE_UPLOADED]  DATETIME        NULL,
    [PRODUCT_ID]     VARCHAR (50)    NULL,
    [PROGRESS]       VARCHAR (50)    NULL,
    [UPLOADER]       VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_PROD_REQ_FORMS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

