CREATE TABLE [dbo].[A_PREPOP] (
    [ID]             VARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    [CREATING_CO]    VARCHAR (50) NULL,
    [STATUS]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PREPOP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

