CREATE TABLE [dbo].[A_PROCEDURE_STEP_SYSTEM_TASK_COMP_TEST_DATA] (
    [STEP_ID]             VARCHAR (50) NOT NULL,
    [NUM_QUESTIONS]       INT          NULL,
    [NUM_CORRECT_TO_PASS] INT          NULL,
    [RETAKE_TILL_PASSING] TINYINT      NULL,
    [DRCM]                DATETIME     NULL,
    [MODBY]               VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEP_SYSTEM_TASK_COMP_TEST_DATA] PRIMARY KEY CLUSTERED ([STEP_ID] ASC)
);

