CREATE TABLE [dbo].[A_PRODUCT_NEEDS_SAT_LINK] (
    [ID]      VARCHAR (50) NOT NULL,
    [PROD_ID] VARCHAR (50) NULL,
    [NEED_ID] VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PRODUCT_NEEDS_SAT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

