CREATE TABLE [dbo].[A_PROJECT_ALLOWED_COMPANIES] (
    [ID]         VARCHAR (50) NOT NULL,
    [PROJECT_ID] VARCHAR (50) NULL,
    [COMPANY_ID] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROJECT_ALLOWED_COMPANIES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

