CREATE TABLE [dbo].[A_PROCEDURES] (
    [ID]             VARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    [STATUS]         VARCHAR (50) NULL,
    [PRIVATE_TO]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TEMPLATE_TASKS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

