CREATE TABLE [dbo].[A_PROJECT_PURPOSE_LINK] (
    [ID]         VARCHAR (50) NOT NULL,
    [PURPOSE_ID] VARCHAR (50) NULL,
    [PROJECT_ID] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_PROJECT_PURPOSE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

