CREATE TABLE [dbo].[A_PROCEDURE_OBJECT_LINK] (
    [ID]                 VARCHAR (50)  NOT NULL,
    [PROCEDURE_ID]       VARCHAR (50)  NULL,
    [STEP_ID]            VARCHAR (50)  NULL,
    [APPROVED_OBJECT_ID] VARCHAR (50)  NULL,
    [QTY]                FLOAT (53)    NULL,
    [QTY_TYPE]           NVARCHAR (50) NULL,
    [RELATIONSHIP]       NVARCHAR (50) NULL,
    [DRCM]               DATETIME      NULL,
    [MODBY]              NVARCHAR (50) NULL,
    [LABOR_ROLE]         VARCHAR (50)  NULL,
    [COPIED_FROM]        VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_PROCEDURE_OBJECT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

