CREATE TABLE [dbo].[A_PROCEDURE_STEP_RECURRENCE] (
    [ID]              VARCHAR (50) NOT NULL,
    [STEP_ID]         VARCHAR (50) NOT NULL,
    [RECUR_TYPE]      VARCHAR (10) NOT NULL,
    [NEXT_STEP]       VARCHAR (50) NOT NULL,
    [DELAY_TYPE]      VARCHAR (50) NOT NULL,
    [DELAY_UNIT]      VARCHAR (50) NULL,
    [DELAY_COUNTER]   VARCHAR (50) NULL,
    [DELAY_VALUE]     FLOAT (53)   NULL,
    [DRCM]            DATETIME     NULL,
    [MODBY]           VARCHAR (50) NULL,
    [TIMES_TO_REPEAT] FLOAT (53)   NULL,
    [SCHED_NUM]       INT          CONSTRAINT [DF_A_PROCEDURE_STEP_RECURRENCE_SCHED_NUM] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_A_PROCEDURE_STEP_RECURRENCE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

