CREATE TABLE [dbo].[A_PURCHASES_HISTORY] (
    [ID]              VARCHAR (50) NOT NULL,
    [DATE_CREATED]    DATETIME     NULL,
    [PURCHASE_STATUS] VARCHAR (50) NULL,
    [ORDER_ID]        VARCHAR (50) NOT NULL,
    [DRCM]            DATETIME     NULL,
    [MODBY]           VARCHAR (50) NULL,
    [OBJECT_ID]       VARCHAR (50) NULL,
    [PURCHASE_TOTAL]  MONEY        NULL,
    [PURCHASER]       VARCHAR (50) NULL,
    [PURCHASING_CO]   VARCHAR (50) NULL,
    [CUST_PURCH_NUM]  VARCHAR (50) NULL,
    [SUP_PURCH_NUM]   VARCHAR (50) NULL,
    [ACCT_FOR_ALL]    VARCHAR (50) NULL,
    [DUE_DATE]        DATETIME     NULL,
    CONSTRAINT [PK_A_PURCHASES_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO






CREATE       TRIGGER A_PURCHASES_HISTORY_INSERT
ON dbo.A_PURCHASES_HISTORY
AFTER INSERT
AS
declare @ID as varchar(50), @NAME as nvarchar(50), 
	@MODBY as varchar(50),@purchaser varchar(50),
	@purchCo varchar(50)
SELECT @ID = ID, @purchaser = PURCHASER,
@MODBY = MODBY, @NAME = 'PURCHASE ' + isNull(OBJECT_ID,'') FROM INSERTED
SELECT @purchCO = COMPANY FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @purchaser
UPDATE A_PURCHASES_HISTORY SET PURCHASING_CO = @purchCo WHERE ID = @ID
exec A_SP_OBJECT_ADD 'A_PURCHASES_HISTORY',@ID,@NAME,@MODBY,null,null,null
SELECT @NAME = 'PURCHASE ' + isNull(OBJECT_ID,'') FROM A_PURCHASES_HISTORY WHERE ID = @ID
UPDATE A_OBJECTS set OBJ_DESC = @NAME WHERE OBJ_ID = @ID
exec A_SP_PURCHASE_ADD_QUOTE_LINK @ID,@MODBY








