CREATE TABLE [dbo].[A_PURCHASE_QUOTE_STATUS] (
    [PURCHASE_ID] VARCHAR (50) NOT NULL,
    [QUOTE_ID]    VARCHAR (50) NOT NULL,
    [STATUS]      VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL,
    [ID]          VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_PURCHASE_QUOTE_STATUS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

