CREATE TABLE [dbo].[A_PURCHASE_FUTURE_FILL_ITEM] (
    [ID]          VARCHAR (50)   NOT NULL,
    [PURCHASE_ID] VARCHAR (50)   NOT NULL,
    [FILL_OBJ_ID] VARCHAR (50)   NOT NULL,
    [DRCM]        DATETIME       NULL,
    [MODBY]       VARCHAR (50)   NULL,
    [COMMENTS]    VARCHAR (4000) NULL,
    CONSTRAINT [PK_A_PURCHASE_FUTURE_FILL_ITEM] PRIMARY KEY CLUSTERED ([ID] ASC)
);

