CREATE TABLE [dbo].[A_QUOTES] (
    [ID]             VARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    [STATUS]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_QUOTES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_QUOTES_A_QUOTES_HISTORY] FOREIGN KEY ([HISTORY_REF_ID]) REFERENCES [dbo].[A_QUOTES_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_QUOTES] NOCHECK CONSTRAINT [FK_A_QUOTES_A_QUOTES_HISTORY];

