CREATE TABLE [dbo].[A_QUOTES_HISTORY] (
    [ID]              VARCHAR (50)    NOT NULL,
    [OBJECT_ID]       VARCHAR (50)    NULL,
    [DESCRIPTION]     NVARCHAR (1000) NULL,
    [PROGRESS]        VARCHAR (50)    NULL,
    [ORDER_ID]        VARCHAR (50)    NOT NULL,
    [DRCM]            DATETIME        NULL,
    [MODBY]           VARCHAR (50)    NULL,
    [CUSTOMER_PERSON] VARCHAR (50)    NULL,
    [CUSTOMER_CO]     VARCHAR (50)    NULL,
    [BUGETARY_ONLY]   SMALLINT        NULL,
    [EXPIRATION_DATE] DATETIME        NULL,
    [SUPPLIER_ID]     VARCHAR (50)    NULL,
    [CREATION_DATE]   DATETIME        NULL,
    [PERSON_SUPPLIER] VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_QUOTES_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_QUOTES_HISTORY_A_OBJECTS] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[A_OBJECTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_QUOTES_HISTORY_A_ORDERS] FOREIGN KEY ([ORDER_ID]) REFERENCES [dbo].[A_ORDERS] ([ID])
);


GO
ALTER TABLE [dbo].[A_QUOTES_HISTORY] NOCHECK CONSTRAINT [FK_A_QUOTES_HISTORY_A_OBJECTS];


GO
ALTER TABLE [dbo].[A_QUOTES_HISTORY] NOCHECK CONSTRAINT [FK_A_QUOTES_HISTORY_A_ORDERS];


GO

CREATE  TRIGGER A_QUOTES_HISTORY_INSERT
ON dbo.A_QUOTES_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = DESCRIPTION FROM INSERTED
exec A_SP_OBJECT_ADD 'A_QUOTES_HISTORY',@ID,@NAME,@MODBY,null,null,null


GO

CREATE  TRIGGER A_QUOTES_HISTORY_UPDATE
ON dbo.A_QUOTES_HISTORY
AFTER UPDATE
AS
declare @OBJ_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
print 'In the Quotes History Update Trigger'
SELECT
@ID = ID,
@OBJ_ID = OBJECT_ID,
@NAME = DESCRIPTION,
@MODBY = MODBY 
FROM INSERTED

declare @myObjName as nvarchar(100)
SELECT @myObjName = OBJ_DESC FROM A_OBJECTS WHERE ID = @OBJ_ID
if @myObjName <> @NAME
	begin
	UPDATE A_OBJECTS SET
	OBJ_DESC = @NAME,
	MODBY = @MODBY,
	DRCM = getDATE()
	WHERE ID = @OBJ_ID
	end

