CREATE TABLE [dbo].[A_QUOTE_ORDER_LINK_STAT_HISTORY] (
    [ID]                  VARCHAR (50) NOT NULL,
    [QOL_ID]              VARCHAR (50) NULL,
    [STATUS_CHANGED_TO]   VARCHAR (50) NULL,
    [STATUS_CHANGED_FROM] VARCHAR (50) NULL,
    [DRCM]                DATETIME     NULL,
    [MODBY]               VARCHAR (50) NULL,
    CONSTRAINT [PK_A_QUOTE_ORDER_LINK_STAT_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_QUOTE_ORDER_LINK_STAT_HISTORY_A_QUOTE_ORDER_LINK] FOREIGN KEY ([QOL_ID]) REFERENCES [dbo].[A_QUOTE_ORDER_LINK] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_QUOTE_ORDER_LINK_STAT_HISTORY] NOCHECK CONSTRAINT [FK_A_QUOTE_ORDER_LINK_STAT_HISTORY_A_QUOTE_ORDER_LINK];

