CREATE TABLE [dbo].[A_RESUME_DATA] (
    [ID]        VARCHAR (50)    NOT NULL,
    [RESUME_ID] VARCHAR (50)    NOT NULL,
    [DATA_TYPE] VARCHAR (50)    NOT NULL,
    [DATA]      NVARCHAR (2000) NULL,
    [DRCM]      DATETIME        NULL,
    [MODBY]     VARCHAR (50)    NULL,
    [CNT]       INT             NULL,
    CONSTRAINT [PK_A_RESUME_DATA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

