CREATE TABLE [dbo].[A_REPLACEMENT_PART_DISPOSITION] (
    [ID]                 NVARCHAR (50) NOT NULL,
    [MACHINE_PART_ID]    VARCHAR (50)  NOT NULL,
    [DOA]                NVARCHAR (10) NULL,
    [SEALED_OPENED]      NVARCHAR (10) NULL,
    [RECEIVER_BROKE]     NVARCHAR (10) NULL,
    [PART_INSTALLED]     NVARCHAR (10) NULL,
    [RETURN_REASON]      NVARCHAR (50) NULL,
    [SOURCE_STOCK_NOT]   NVARCHAR (50) NULL,
    [SOURCE_STOCK]       NVARCHAR (50) NULL,
    [RECOMMENDED_ACTION] NVARCHAR (50) NULL,
    [MODBY]              NVARCHAR (50) NULL,
    [DTRM]               DATETIME      NULL,
    CONSTRAINT [PK_A_REPLACEMENT_PART_DISPOSITION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_REPLACEMENT_PART_DISPOSITION_A_MACHINE_PARTS] FOREIGN KEY ([MACHINE_PART_ID]) REFERENCES [dbo].[A_MACHINE_PARTS] ([ID])
);


GO
ALTER TABLE [dbo].[A_REPLACEMENT_PART_DISPOSITION] NOCHECK CONSTRAINT [FK_A_REPLACEMENT_PART_DISPOSITION_A_MACHINE_PARTS];

