CREATE TABLE [dbo].[A_REGIONS] (
    [ID]             NVARCHAR (50) NOT NULL,
    [MODBY]          NVARCHAR (50) NULL,
    [DRCM]           DATETIME      NULL,
    [HISTORY_REF_ID] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_REGIONS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_REGIONS_A_REGIONS_HISTORY] FOREIGN KEY ([HISTORY_REF_ID]) REFERENCES [dbo].[A_REGIONS_HISTORY] ([ID])
);


GO
ALTER TABLE [dbo].[A_REGIONS] NOCHECK CONSTRAINT [FK_A_REGIONS_A_REGIONS_HISTORY];


GO









CREATE     TRIGGER A_REGIONS_UPDATE
ON dbo.A_REGIONS
AFTER UPDATE
AS
print 'INSIDE A_REGIONS_UPDATE TRIGGER'
declare @ID as nvarchar(50)
SELECT @ID = ID
from INSERTED
--Update the name in the object
print 'We are going to update where the name of this Region is'
exec A_SP_REGIONS_UPDATE_WHERE_USED_NAME @ID






