CREATE TABLE [dbo].[A_RESUMES] (
    [ID]                 VARCHAR (50)   NOT NULL,
    [NAME]               NVARCHAR (200) NULL,
    [STREET]             NVARCHAR (500) NULL,
    [CITY]               VARCHAR (100)  NULL,
    [STATE]              VARCHAR (50)   NULL,
    [POSTAL_CODE]        VARCHAR (15)   NULL,
    [COUNTRY]            VARCHAR (50)   NULL,
    [PHONE]              VARCHAR (30)   NULL,
    [EMAIL]              VARCHAR (100)  NULL,
    [RELOCATE]           VARCHAR (100)  NULL,
    [SALARY]             VARCHAR (100)  NULL,
    [DESIRED_JOB_TYPE]   VARCHAR (200)  NULL,
    [WORK_STATUS]        VARCHAR (300)  NULL,
    [TARGET_LOCATIONS]   VARCHAR (300)  NULL,
    [WILLING_TO_TRAVEL]  VARCHAR (100)  NULL,
    [DESIRED_JOB_STATUS] VARCHAR (200)  NULL,
    [WEEKENDS]           VARCHAR (50)   NULL,
    [OVERTIME]           VARCHAR (50)   NULL,
    [DRCM]               DATETIME       NULL,
    [MODBY]              VARCHAR (50)   NULL,
    [ROOT_CO]            VARCHAR (50)   NULL,
    [CURRENTLY_EMPLOYED] TINYINT        NULL,
    [MONSTER_ID]         VARCHAR (50)   NULL,
    [EDUCATION_SHORT]    VARCHAR (500)  NULL,
    [CREATE_DATE]        DATETIME       NULL,
    CONSTRAINT [PK_A_RESUMES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

