CREATE TABLE [dbo].[A_REGIONS_HISTORY] (
    [ID]        NVARCHAR (50)  NOT NULL,
    [NAME]      NVARCHAR (100) NULL,
    [MODBY]     NVARCHAR (50)  NULL,
    [DRCM]      DATETIME       NULL,
    [OBJECT_ID] VARCHAR (50)   NULL,
    CONSTRAINT [PK_A_REGIONS_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_REGIONS_HISTORY_A_OBJECTS] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[A_OBJECTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_REGIONS_HISTORY] NOCHECK CONSTRAINT [FK_A_REGIONS_HISTORY_A_OBJECTS];


GO

CREATE    TRIGGER A_REGIONS_HISTORY_INSERT
ON dbo.A_REGIONS_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_REGIONS_HISTORY',@ID,@NAME,@MODBY,null,null,null


GO


CREATE      TRIGGER A_REGIONS_HISTORY_UPDATE
ON dbo.A_REGIONS_HISTORY
AFTER UPDATE
AS
if update (NAME)
begin
declare @OBJ_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT
@ID = ID,
@OBJ_ID = OBJECT_ID,
@NAME = NAME,
@MODBY = MODBY 
FROM INSERTED
UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID
end

