CREATE TABLE [dbo].[A_ROLES_HISTORY] (
    [ID]             VARCHAR (50)   NOT NULL,
    [NAME]           NVARCHAR (200) NOT NULL,
    [SOURCE]         NVARCHAR (50)  NULL,
    [HIDDEN]         NUMERIC (18)   NOT NULL,
    [DRCM]           DATETIME       NULL,
    [MODBY]          NVARCHAR (50)  NULL,
    [OBJECT_ID]      VARCHAR (50)   NULL,
    [SECURITY_LEVEL] VARCHAR (50)   NULL,
    [IS_ADMIN]       SMALLINT       NULL,
    CONSTRAINT [PK_A_ROLES_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_ROLES_HISTORY_A_OBJECTS] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[A_OBJECTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_ROLES_HISTORY_A_SECURITY_LEVELS] FOREIGN KEY ([SECURITY_LEVEL]) REFERENCES [dbo].[A_SECURITY_LEVELS] ([ID])
);


GO
ALTER TABLE [dbo].[A_ROLES_HISTORY] NOCHECK CONSTRAINT [FK_A_ROLES_HISTORY_A_OBJECTS];


GO
ALTER TABLE [dbo].[A_ROLES_HISTORY] NOCHECK CONSTRAINT [FK_A_ROLES_HISTORY_A_SECURITY_LEVELS];


GO


CREATE    TRIGGER A_ROLES_HISTORY_INSERT
ON dbo.A_ROLES_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50),
	@isSystem varchar(50)
SELECT  @ID = ID,@NAME = NAME,@MODBY = MODBY,@isSystem = IS_ADMIN FROM INSERTED
exec A_SP_OBJECT_ADD 'A_ROLES_HISTORY',@ID,@NAME,@MODBY,NULL,NULL,NULL

if @isSystem = 1
	begin
	UPDATE A_ROLES_HISTORY SET SECURITY_LEVEL = 5 WHERE ID = @ID

	end


GO


CREATE   TRIGGER A_ROLES_HISTORY_UPDATE
ON dbo.A_ROLES_HISTORY
AFTER UPDATE
AS
if update(NAME)
begin
declare @OBJ_ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT  @OBJ_ID = OBJECT_ID,@NAME = NAME,@MODBY = MODBY FROM INSERTED
UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID
end

