CREATE TABLE [dbo].[A_ROLES_DEPARTMENT_SUB_ROLES] (
    [ID]           VARCHAR (50) NOT NULL,
    [ROLE_HIST_ID] VARCHAR (50) NOT NULL,
    [DEPARTMENT]   VARCHAR (50) NOT NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [SUB_ROLE]     VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_ROLES_DEPARTMENT_SUB_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_ROLES_DEPARTMENT_SUB_ROLES_A_COMPANIES] FOREIGN KEY ([DEPARTMENT]) REFERENCES [dbo].[A_COMPANIES] ([ID]),
    CONSTRAINT [FK_A_ROLES_DEPARTMENT_SUB_ROLES_A_ROLES] FOREIGN KEY ([SUB_ROLE]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_ROLES_DEPARTMENT_SUB_ROLES_A_ROLES_HISTORY] FOREIGN KEY ([ROLE_HIST_ID]) REFERENCES [dbo].[A_ROLES_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_ROLES_DEPARTMENT_SUB_ROLES] NOCHECK CONSTRAINT [FK_A_ROLES_DEPARTMENT_SUB_ROLES_A_COMPANIES];


GO
ALTER TABLE [dbo].[A_ROLES_DEPARTMENT_SUB_ROLES] NOCHECK CONSTRAINT [FK_A_ROLES_DEPARTMENT_SUB_ROLES_A_ROLES];


GO
ALTER TABLE [dbo].[A_ROLES_DEPARTMENT_SUB_ROLES] NOCHECK CONSTRAINT [FK_A_ROLES_DEPARTMENT_SUB_ROLES_A_ROLES_HISTORY];

