CREATE TABLE [dbo].[A_ROLES] (
    [ID]             VARCHAR (50) NOT NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    [HISTORY_REF_ID] VARCHAR (50) NULL,
    [STATUS]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_ROLES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_ROLES_A_ROLES_HISTORY] FOREIGN KEY ([HISTORY_REF_ID]) REFERENCES [dbo].[A_ROLES_HISTORY] ([ID])
);


GO
ALTER TABLE [dbo].[A_ROLES] NOCHECK CONSTRAINT [FK_A_ROLES_A_ROLES_HISTORY];

