CREATE TABLE [dbo].[A_ROLE_ASSIGNEE] (
    [ID]            NVARCHAR (50) NOT NULL,
    [ROLE]          VARCHAR (50)  NOT NULL,
    [PERSON]        VARCHAR (50)  NULL,
    [STATUS]        NVARCHAR (50) NULL,
    [SOURCE]        NVARCHAR (50) NOT NULL,
    [ROLE_ASSIGNED] VARCHAR (50)  NULL,
    [IN_WORKFLOW]   BIT           NULL,
    [WFS_ID]        VARCHAR (50)  NULL,
    [TYPE]          NVARCHAR (50) NULL,
    [DRCM]          DATETIME      NULL,
    [MODBY]         NVARCHAR (50) NULL,
	[StartDate] DATETIME NULL, 
    [EndDate] DATETIME NULL, 
    CONSTRAINT [PK_A_ROLE_ASSIGNEE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_PEOPLE] FOREIGN KEY ([PERSON]) REFERENCES [dbo].[A_PEOPLE] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_ROLES] FOREIGN KEY ([ROLE_ASSIGNED]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_ROLES_HISTORY] FOREIGN KEY ([ROLE]) REFERENCES [dbo].[A_ROLES_HISTORY] ([ID]),
    CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_WORKFLOWSSTARTED] FOREIGN KEY ([WFS_ID]) REFERENCES [dbo].[A_WORKFLOWS_STARTED] ([ID])
);


GO
ALTER TABLE [dbo].[A_ROLE_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_ROLE_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_ROLES];


GO
ALTER TABLE [dbo].[A_ROLE_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_ROLES_HISTORY];


GO
ALTER TABLE [dbo].[A_ROLE_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_ROLE_ASSIGNEE_A_WORKFLOWSSTARTED];


GO

CREATE   TRIGGER A_ROLE_ASSIGNEE_INSERT
ON dbo.A_ROLE_ASSIGNEE
AFTER INSERT
AS
print 'Running Role Assignee insert trigger'
declare @PERSON as nvarchar(50)
SELECT @PERSON = PERSON FROM INSERTED
print 'The person Assigned to the Role is  ' + isnull(@PERSON,'NULL')
declare @objID as nvarchar(50)
SELECT @objID = OBJECT_ID FROM A_PEOPLE_HISTORY WHERE ID = @PERSON
print 'The object ID is ' + @objID
if not(@PERSON is null)
	exec A_SP_PEOPLE_UPDATE_PERSON_SEARCH_TABLE @objID


GO

CREATE   TRIGGER A_ROLE_ASSIGNEE_UPDATE
ON dbo.A_ROLE_ASSIGNEE
AFTER UPDATE
AS
print 'Running Role Assignee update trigger'
declare @PERSON as nvarchar(50)
SELECT @PERSON = PERSON FROM INSERTED
print 'The person Assigned to the Role is  ' + isnull(@PERSON,'NULL')
declare @objID as nvarchar(50)
SELECT @objID = OBJECT_ID FROM A_APPROVED_PEOPLE WHERE ID = @PERSON
print 'The object ID is ' + @objID
if not(@PERSON is null)
	exec A_SP_PEOPLE_UPDATE_PERSON_SEARCH_TABLE @objID

