CREATE TABLE [dbo].[A_SERVICE_CALLS_WEEKLY_REPORTS] (
    [ID]                   VARCHAR (50)   NOT NULL,
    [WORKER_ID]            VARCHAR (50)   NULL,
    [MACHINE_NAME]         VARCHAR (1000) NULL,
    [COMMENTS]             VARCHAR (4000) NULL,
    [DRCM]                 DATETIME       NULL,
    [MODBY]                VARCHAR (50)   NULL,
    [WORK_TYPE]            VARCHAR (50)   NULL,
    [STATUS]               VARCHAR (100)  NULL,
    [START_DAY]            INT            NULL,
    [START_YEAR]           INT            NULL,
    [CHECK_NUM]            VARCHAR (50)   NULL,
    [REASON]               VARCHAR (4000) NULL,
    [START_MONTH]          INT            NULL,
    [ORDER_NUMBER]         VARCHAR (50)   NULL,
    [HOUR_RATE_FIXED]      MONEY          NULL,
    [OT_RATE_FIXED]        MONEY          NULL,
    [INVOICE_DATE]         DATETIME       NULL,
    [REASON_TYPE]          VARCHAR (50)   NULL,
    [EXPENSES_DESCRIPTION] VARCHAR (1000) NULL,
    [EXPENSES_AMOUNT]      MONEY          NULL,
    [ACTUAL_START_DATE]    DATETIME       NULL,
    [IMPORT_ID]            VARCHAR (50)   NULL,
    CONSTRAINT [PK_A_SERVICE_CALLS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_SERVICE_CALLS_WEEKLY_REPORTS_A_PEOPLE] FOREIGN KEY ([WORKER_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_SERVICE_CALLS_WEEKLY_REPORTS_A_SERVICE_CALLS_WORK_TYPES] FOREIGN KEY ([WORK_TYPE]) REFERENCES [dbo].[A_SERVICE_CALLS_WORK_TYPES] ([ID])
);


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_WEEKLY_REPORTS] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_WEEKLY_REPORTS_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_WEEKLY_REPORTS] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_WEEKLY_REPORTS_A_SERVICE_CALLS_WORK_TYPES];

