CREATE TABLE [dbo].[A_SERVICE_CALL_WORK_TIME] (
    [ID]        VARCHAR (50) NOT NULL,
    [WEEKLY_ID] VARCHAR (50) NULL,
    [D]         INT          NULL,
    [MO]        INT          NULL,
    [YR]        INT          NULL,
    [HOUR_TYPE] VARCHAR (50) NULL,
    [HOURS]     FLOAT (53)   NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_SERVICE_CALL_WORK_TIME] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_SERVICE_CALL_WORK_TIME_A_SERVICE_CALLS] FOREIGN KEY ([WEEKLY_ID]) REFERENCES [dbo].[A_SERVICE_CALLS_WEEKLY_REPORTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SERVICE_CALL_WORK_TIME] NOCHECK CONSTRAINT [FK_A_SERVICE_CALL_WORK_TIME_A_SERVICE_CALLS];

