CREATE TABLE [dbo].[A_SERVICE_CALLS_ATTACHMENTS] (
    [ID]        VARCHAR (50) NOT NULL,
    [WEEKLY_ID] VARCHAR (50) NULL,
    [DOC_ID]    VARCHAR (50) NULL,
    [MODBY]     VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    CONSTRAINT [FK_A_SERVICE_CALLS_ATTACHMENTS_A_DOCUMENTS] FOREIGN KEY ([DOC_ID]) REFERENCES [dbo].[A_DOCUMENTS] ([ID]),
    CONSTRAINT [FK_A_SERVICE_CALLS_ATTACHMENTS_A_SERVICE_CALLS_WEEKLY_REPORTS] FOREIGN KEY ([WEEKLY_ID]) REFERENCES [dbo].[A_SERVICE_CALLS_WEEKLY_REPORTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_ATTACHMENTS] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_ATTACHMENTS_A_DOCUMENTS];


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_ATTACHMENTS] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_ATTACHMENTS_A_SERVICE_CALLS_WEEKLY_REPORTS];

