CREATE TABLE [dbo].[A_SERVICE_CALLS_WORK_TYPES] (
    [ID]             VARCHAR (50)   NOT NULL,
    [SUPPLIER_ID]    VARCHAR (50)   NULL,
    [CUSTOMER_ID]    VARCHAR (50)   NULL,
    [WORK_TYPE_NAME] NVARCHAR (200) NULL,
    [APPROVER_ROLE]  VARCHAR (50)   NULL,
    [PAYER_ROLE]     VARCHAR (50)   NULL,
    [MODBY]          VARCHAR (50)   NULL,
    [DRCM]           DATETIME       NULL,
    [HOUR_RATE]      SMALLMONEY     NULL,
    [OT_RATE]        SMALLMONEY     NULL,
    [TAX_RATE]       REAL           NULL,
    [SKIP_BOSS]      TINYINT        NULL,
    [HIDE]           TINYINT        CONSTRAINT [DF_A_SERVICE_CALLS_WORK_TYPES_HIDE] DEFAULT ((0)) NULL,
    [STATUS]         VARCHAR (50)   CONSTRAINT [DF_A_SERVICE_CALLS_WORK_TYPES_DELETED] DEFAULT ('ACTIVE') NULL,
    CONSTRAINT [PK_A_WORK_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_COMPANIES] FOREIGN KEY ([SUPPLIER_ID]) REFERENCES [dbo].[A_COMPANIES] ([ID]),
    CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_COMPANIES1] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[A_COMPANIES] ([ID]),
    CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_ROLES] FOREIGN KEY ([APPROVER_ROLE]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_ROLES1] FOREIGN KEY ([PAYER_ROLE]) REFERENCES [dbo].[A_ROLES] ([ID])
);


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_WORK_TYPES] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_COMPANIES];


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_WORK_TYPES] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_COMPANIES1];


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_WORK_TYPES] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_ROLES];


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_WORK_TYPES] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_WORK_TYPES_A_ROLES1];

