CREATE TABLE [dbo].[A_SEARCHES_SAVED] (
    [ID]          VARCHAR (50)   NOT NULL,
    [SEARCH_NAME] VARCHAR (300)  NULL,
    [PAGE_ID]     VARCHAR (500)  NOT NULL,
    [QS]          VARCHAR (7000) NULL,
    [DRCM]        DATETIME       NULL,
    [PERSON_ID]   VARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_A_SEARCHES_SAVED] PRIMARY KEY CLUSTERED ([ID] ASC)
);

