CREATE TABLE [dbo].[A_SERVICE_CALLS_STATUS_HISTORY] (
    [ID]                VARCHAR (50)    NOT NULL,
    [WEEKLY_ID]         VARCHAR (50)    NULL,
    [STATUS_CHANGED_TO] VARCHAR (100)   NULL,
    [CHANGED_BY]        VARCHAR (50)    NULL,
    [DRCM]              DATETIME        NULL,
    [MODBY]             VARCHAR (50)    NULL,
    [REASON]            NVARCHAR (4000) NULL,
    [DATE_CHANGED]      DATETIME        NULL,
    [REASON_TYPE]       VARCHAR (50)    NULL,
    CONSTRAINT [FK_A_SERVICE_CALLS_STATUS_HISTORY_A_SERVICE_CALLS_WEEKLY_REPORTS] FOREIGN KEY ([WEEKLY_ID]) REFERENCES [dbo].[A_SERVICE_CALLS_WEEKLY_REPORTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SERVICE_CALLS_STATUS_HISTORY] NOCHECK CONSTRAINT [FK_A_SERVICE_CALLS_STATUS_HISTORY_A_SERVICE_CALLS_WEEKLY_REPORTS];

