CREATE TABLE [dbo].[A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE] (
    [ID]               VARCHAR (50) NOT NULL,
    [COMPANY_ID]       VARCHAR (50) NULL,
    [RECIEVABLE_ROLE]  VARCHAR (50) NULL,
    [DRCM]             DATETIME     NULL,
    [MODBY]            VARCHAR (50) NULL,
    [PAYMENT_LOCATION] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

