CREATE TABLE [dbo].[A_SECURITY_LEVELS] (
    [ID]    VARCHAR (50)  NOT NULL,
    [NAME]  VARCHAR (100) NULL,
    [DRCM]  DATETIME      NULL,
    [MODBY] VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_SECURITY_LEVELS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

