CREATE TABLE [dbo].[A_SURVEY_INV_ROLE] (
    [SURVEY_ID] VARCHAR (50) NULL,
    [ROLE_ID]   VARCHAR (50) NULL,
    [MODBY]     VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    CONSTRAINT [FK_A_SURVEY_INV_ROLE_A_ROLES] FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[A_ROLES] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_SURVEY_INV_ROLE_A_SURVEYS] FOREIGN KEY ([SURVEY_ID]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SURVEY_INV_ROLE] NOCHECK CONSTRAINT [FK_A_SURVEY_INV_ROLE_A_ROLES];


GO
ALTER TABLE [dbo].[A_SURVEY_INV_ROLE] NOCHECK CONSTRAINT [FK_A_SURVEY_INV_ROLE_A_SURVEYS];

