CREATE TABLE [dbo].[A_SURVEYS] (
    [ID]           VARCHAR (50)    NOT NULL,
    [SUBJECT]      NVARCHAR (1000) NULL,
    [OWNER]        VARCHAR (50)    NULL,
    [DATE_CREATED] DATETIME        NULL,
    [STATUS]       VARCHAR (50)    NULL,
    [DRCM]         DATETIME        NULL,
    [MODBY]        VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_SURVEYS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_SURVEYS_A_PEOPLE] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[A_PEOPLE] ([ID])
);


GO
ALTER TABLE [dbo].[A_SURVEYS] NOCHECK CONSTRAINT [FK_A_SURVEYS_A_PEOPLE];

