CREATE TABLE [dbo].[A_SURVEY_RESPONSE_ALERTS] (
    [ID]         VARCHAR (50) NOT NULL,
    [SURVEY_ID]  VARCHAR (50) NULL,
    [ALERTEE_ID] VARCHAR (50) NULL,
    [DRCM]       VARCHAR (50) NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_SURVEY_RESPONSE_ALERTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

