CREATE TABLE [dbo].[A_SURVEY_INV_PEOPLE] (
    [SURVEY_ID] VARCHAR (50) NULL,
    [PEOPLE_ID] VARCHAR (50) NULL,
    [MODBY]     VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    CONSTRAINT [FK_A_SURVEY_INV_PEOPLE_A_PEOPLE1] FOREIGN KEY ([PEOPLE_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_SURVEY_INV_PEOPLE_A_SURVEYS] FOREIGN KEY ([SURVEY_ID]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SURVEY_INV_PEOPLE] NOCHECK CONSTRAINT [FK_A_SURVEY_INV_PEOPLE_A_PEOPLE1];


GO
ALTER TABLE [dbo].[A_SURVEY_INV_PEOPLE] NOCHECK CONSTRAINT [FK_A_SURVEY_INV_PEOPLE_A_SURVEYS];

