CREATE TABLE [dbo].[A_SURVEY_ATTACHMENTS] (
    [SURVEY_ID]   VARCHAR (50) NULL,
    [RESPONSE_ID] VARCHAR (50) NULL,
    [DOC_ID]      VARCHAR (50) NULL,
    [MODBY]       VARCHAR (50) NULL,
    [DRCM]        DATETIME     NULL,
    CONSTRAINT [FK_A_SURVEY_ATTACHMENTS_A_DOCUMENTS] FOREIGN KEY ([DOC_ID]) REFERENCES [dbo].[A_DOCUMENTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_SURVEY_ATTACHMENTS_A_SURVEY_REPLIES] FOREIGN KEY ([RESPONSE_ID]) REFERENCES [dbo].[A_SURVEY_REPLIES] ([ID]),
    CONSTRAINT [FK_A_SURVEY_ATTACHMENTS_A_SURVEYS] FOREIGN KEY ([SURVEY_ID]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SURVEY_ATTACHMENTS] NOCHECK CONSTRAINT [FK_A_SURVEY_ATTACHMENTS_A_DOCUMENTS];


GO
ALTER TABLE [dbo].[A_SURVEY_ATTACHMENTS] NOCHECK CONSTRAINT [FK_A_SURVEY_ATTACHMENTS_A_SURVEY_REPLIES];


GO
ALTER TABLE [dbo].[A_SURVEY_ATTACHMENTS] NOCHECK CONSTRAINT [FK_A_SURVEY_ATTACHMENTS_A_SURVEYS];

