CREATE TABLE [dbo].[A_SURVEY_REPLIES] (
    [ID]             VARCHAR (50)    NOT NULL,
    [TEXT]           NVARCHAR (4000) NULL,
    [NUM]            REAL            NULL,
    [ROOT]           VARCHAR (50)    NULL,
    [COLOR]          VARCHAR (50)    NULL,
    [RATE_PROCEDURE] VARCHAR (50)    NULL,
    [PARENT]         VARCHAR (50)    NULL,
    [AUTHOR]         VARCHAR (50)    NULL,
    [MODBY]          VARCHAR (50)    NULL,
    [DRCM]           DATETIME        NULL,
    CONSTRAINT [PK_A_SURVEY_REPLIES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_SURVEY_REPLIES_A_SURVEY_REPLIES1] FOREIGN KEY ([PARENT]) REFERENCES [dbo].[A_SURVEY_REPLIES] ([ID]),
    CONSTRAINT [FK_A_SURVEY_REPLIES_A_SURVEYS] FOREIGN KEY ([ROOT]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SURVEY_REPLIES] NOCHECK CONSTRAINT [FK_A_SURVEY_REPLIES_A_SURVEY_REPLIES1];


GO
ALTER TABLE [dbo].[A_SURVEY_REPLIES] NOCHECK CONSTRAINT [FK_A_SURVEY_REPLIES_A_SURVEYS];

