CREATE TABLE [dbo].[A_SURVEY_REALLY_INIVTED_COMPANY] (
    [ID]         VARCHAR (50) NOT NULL,
    [SURVEY_ID]  VARCHAR (50) NULL,
    [COMPANY_ID] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_SURVEY_REALLY_INIVTED_COMPANY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_SURVEY_REALLY_INIVTED_COMPANY_A_SURVEYS] FOREIGN KEY ([SURVEY_ID]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SURVEY_REALLY_INIVTED_COMPANY] NOCHECK CONSTRAINT [FK_A_SURVEY_REALLY_INIVTED_COMPANY_A_SURVEYS];

