CREATE TABLE [dbo].[A_SURVEY_INV_COMPANY] (
    [SURVEY_ID]  VARCHAR (50) NULL,
    [COMPANY_ID] VARCHAR (50) NULL,
    [MODBY]      VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    CONSTRAINT [FK_A_SURVEY_INV_COMPANY_A_COMPANIES] FOREIGN KEY ([COMPANY_ID]) REFERENCES [dbo].[A_COMPANIES] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_SURVEY_INV_COMPANY_A_SURVEYS] FOREIGN KEY ([SURVEY_ID]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_SURVEY_INV_COMPANY] NOCHECK CONSTRAINT [FK_A_SURVEY_INV_COMPANY_A_COMPANIES];


GO
ALTER TABLE [dbo].[A_SURVEY_INV_COMPANY] NOCHECK CONSTRAINT [FK_A_SURVEY_INV_COMPANY_A_SURVEYS];

