CREATE TABLE [dbo].[A_SYSTEM_TASKS] (
    [ID]    VARCHAR (50) NOT NULL,
    [TYPE]  VARCHAR (50) NULL,
    [DRCM]  DATETIME     NULL,
    [MODBY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_SYSTEM_TASKS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

