CREATE TABLE [dbo].[A_TASK_DISCUSSION_LINK] (
    [ID]            VARCHAR (50) NOT NULL,
    [TASK_ID]       VARCHAR (50) NULL,
    [DISCUSSION_ID] VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_DISCUSSION_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_DISCUSSION_LINK_A_DISCUSSIONS] FOREIGN KEY ([DISCUSSION_ID]) REFERENCES [dbo].[A_DISCUSSIONS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_DISCUSSION_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_DISCUSSION_LINK] NOCHECK CONSTRAINT [FK_A_TASK_DISCUSSION_LINK_A_DISCUSSIONS];


GO
ALTER TABLE [dbo].[A_TASK_DISCUSSION_LINK] NOCHECK CONSTRAINT [FK_A_TASK_DISCUSSION_LINK_A_TASKS];


GO



/*
*/
CREATE  TRIGGER A_TASK_DISCUSSION_LINK_INSERT
ON dbo.A_TASK_DISCUSSION_LINK
AFTER INSERT
AS
declare @taskID varchar(50),@discID varchar(50),@modby varchar(50)
SELECT @taskID = TASK_ID,@discID = DISCUSSION_ID,@modby = MODBY FROM INSERTED
exec A_SP_PROJECT_COPY_ONE_ITEMS_PROJ_OBJ_PURP_TAGS @discID,'A_DISCUSSIONS',@taskID,'A_TASKS',@modby
UPDATE A_TASKS SET HAS_DISCUSSION = 1 WHERE ID = @taskID


print 'Out of the A_TASK_DISCUSSION_LINK_INSERT Trigger'

