CREATE TABLE [dbo].[A_TASK_MEETING_LINK] (
    [MEETING_ID] VARCHAR (50) NULL,
    [TASK_ID]    VARCHAR (50) NULL,
    [DRCM]       VARCHAR (50) NULL,
    [MODBY]      VARCHAR (50) NULL,
    [ID]         VARCHAR (50) NULL,
    CONSTRAINT [FK_A_TASK_MEETING_LINK_A_MEETINGS] FOREIGN KEY ([MEETING_ID]) REFERENCES [dbo].[A_MEETINGS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_MEETING_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_MEETING_LINK] NOCHECK CONSTRAINT [FK_A_TASK_MEETING_LINK_A_MEETINGS];


GO
ALTER TABLE [dbo].[A_TASK_MEETING_LINK] NOCHECK CONSTRAINT [FK_A_TASK_MEETING_LINK_A_TASKS];


GO


/*
*/
CREATE TRIGGER A_TASK_MEETING_LINK_INSERT
ON dbo.A_TASK_MEETING_LINK
AFTER INSERT
AS
declare @taskID varchar(50),@fromID varchar(50),@modby varchar(50)
SELECT @taskID = TASK_ID,@fromID = MEETING_ID,@modby = MODBY FROM INSERTED
exec A_SP_PROJECT_COPY_ONE_ITEMS_PROJ_OBJ_PURP_TAGS @fromID,'A_MEETINGS',@taskID,'A_TASKS',@modby


print 'Out of the A_TASK_MEETING_LINK_INSERT Trigger'