CREATE TABLE [dbo].[A_TASK_ORDER_INFORMATION] (
    [TASK_ID]              VARCHAR (50) NOT NULL,
    [FILL_ID]              VARCHAR (50) NULL,
    [ACTUAL_TO_LOC]        VARCHAR (50) NULL,
    [ACTUAL_FROM_LOC]      VARCHAR (50) NULL,
    [PURCHASE_ITEM_ID]     VARCHAR (50) NULL,
    [PURCHASE_HIST_ID]     VARCHAR (50) NULL,
    [MODBY]                VARCHAR (50) NULL,
    [DRCM]                 DATETIME     NULL,
    [PURCHASE_ITEM_ROLE]   VARCHAR (50) NULL,
    [FILL_ITEM_ID]         VARCHAR (50) NULL,
    [PROD_PRICE_LIST_HIST] VARCHAR (50) NULL,
    CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_FILLS] FOREIGN KEY ([FILL_ID]) REFERENCES [dbo].[A_FILLS] ([ID]),
    CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_LOCATIONS] FOREIGN KEY ([ACTUAL_TO_LOC]) REFERENCES [dbo].[A_LOCATIONS] ([ID]),
    CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_LOCATIONS1] FOREIGN KEY ([ACTUAL_FROM_LOC]) REFERENCES [dbo].[A_LOCATIONS] ([ID]),
    CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_FILLS];


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_LOCATIONS];


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_LOCATIONS1];


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_TASKS];




GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_FILLS];


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_LOCATIONS];


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_LOCATIONS1];


GO
ALTER TABLE [dbo].[A_TASK_ORDER_INFORMATION] NOCHECK CONSTRAINT [FK_A_TASK_ORDER_INFORMATION_A_TASKS];


GO
CREATE NONCLUSTERED INDEX [_TASK_ORDER_INFORMATION_TASK_ID]
    ON [dbo].[A_TASK_ORDER_INFORMATION]([TASK_ID] DESC);


GO
CREATE NONCLUSTERED INDEX [A_TASK_ORDER_INFORMATION_FILL_ID]
    ON [dbo].[A_TASK_ORDER_INFORMATION]([FILL_ID] DESC);


GO
CREATE NONCLUSTERED INDEX [A_TASK_ORDER_INFORMATION_PURCHASE_ITEM_ID]
    ON [dbo].[A_TASK_ORDER_INFORMATION]([PURCHASE_ITEM_ID] DESC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'GROUPER,TO_SHIP,FROM_SHIP,CHILD_PROC', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'A_TASK_ORDER_INFORMATION', @level2type = N'COLUMN', @level2name = N'PURCHASE_ITEM_ROLE';


GO
CREATE NONCLUSTERED INDEX [IX_A_TASK_ORDER_INFORMATION_EXECPLAN_02]
    ON [dbo].[A_TASK_ORDER_INFORMATION]([PURCHASE_HIST_ID] ASC)
    INCLUDE([TASK_ID], [PURCHASE_ITEM_ID]);


GO
CREATE NONCLUSTERED INDEX [IX_A_TASK_ORDER_INFORMATION_EXECPLAN_01]
    ON [dbo].[A_TASK_ORDER_INFORMATION]([FILL_ITEM_ID] ASC);

