CREATE TABLE [dbo].[A_TASK_COMMENT] (
    [ID]              VARCHAR (50)    NOT NULL,
    [TASK_ID]         VARCHAR (50)    NULL,
    [DATE_CREATED]    DATETIME        NULL,
    [COMMENT]         NVARCHAR (4000) NULL,
    [WRITER]          VARCHAR (50)    NULL,
    [WRITER_COMPANY]  VARCHAR (50)    NULL,
    [ALLOWED_TO_VIEW] VARCHAR (50)    NULL,
    [DRCM]            DATETIME        NULL,
    [MODBY]           VARCHAR (50)    NULL
);


GO
CREATE NONCLUSTERED INDEX [A_TASK_COMMENT_TASK_ID]
    ON [dbo].[A_TASK_COMMENT]([TASK_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [A_TASK_COMMENT_WRITER]
    ON [dbo].[A_TASK_COMMENT]([WRITER] ASC);


GO



CREATE         TRIGGER A_TASK_COMMENT_DELETE
ON dbo.A_TASK_COMMENT
AFTER DELETE
AS
declare @taskID as nvarchar(50)
declare @modby as nvarchar(50)


SELECT @taskID = TASK_ID
 	   FROM DELETED
exec A_SP_TASK_ADD_LAST_COMMENT @taskID,@MODBY


GO




CREATE          TRIGGER A_TASK_COMMENT_INSERT_UPDATE
ON dbo.A_TASK_COMMENT
AFTER INSERT,UPDATE
AS
declare @taskID as nvarchar(50)
declare @modby as nvarchar(50)
SELECT @taskID = TASK_ID,
	  	@modby = MODBY	
	   FROM INSERTED
exec A_SP_TASK_ADD_LAST_COMMENT @taskID,@MODBY




