CREATE TABLE [dbo].[A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED] (
    [ID]             VARCHAR (50) NOT NULL,
    [TASK_ID]        VARCHAR (50) NOT NULL,
    [ACTUAL_PART_ID] VARCHAR (50) NOT NULL,
    [DRCM]           DATETIME     NULL,
    [MODBY]          VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED_A_ACTUAL_PARTS] FOREIGN KEY ([ACTUAL_PART_ID]) REFERENCES [dbo].[A_ACTUAL_PARTS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED] NOCHECK CONSTRAINT [FK_A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED_A_ACTUAL_PARTS];


GO
ALTER TABLE [dbo].[A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED] NOCHECK CONSTRAINT [FK_A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED_A_TASKS];

