CREATE TABLE [dbo].[A_TASK_COUNTERS] (
    [ID]           VARCHAR (50) NOT NULL,
    [COUNTER_TYPE] VARCHAR (50) NULL,
    [VAL]          NUMERIC (18) NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [TASK_ID]      VARCHAR (50) NULL,
    [IS_CURRENT]   SMALLINT     NULL,
    CONSTRAINT [PK_A_TASK_COUNTERS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_COUNTERS_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_COUNTERS] NOCHECK CONSTRAINT [FK_A_TASK_COUNTERS_A_TASKS];

