CREATE TABLE [dbo].[A_TASK_REF_FILES] (
    [ID]              VARCHAR (50) NOT NULL,
    [TASK_ID]         VARCHAR (50) NULL,
    [FILE_ID]         VARCHAR (50) NULL,
    [DRCM]            DATETIME     NULL,
    [MODBY]           VARCHAR (50) NULL,
    [STATUS]          VARCHAR (50) NULL,
    [DELETED_BY_NAME] VARCHAR (50) NULL,
    [DATE_DELETED]    DATETIME     NULL,
    [DELETED_BY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_REF_FILES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_REF_FILES_A_DOCUMENTS] FOREIGN KEY ([FILE_ID]) REFERENCES [dbo].[A_DOCUMENTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_REF_FILES_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_REF_FILES] NOCHECK CONSTRAINT [FK_A_TASK_REF_FILES_A_DOCUMENTS];


GO
ALTER TABLE [dbo].[A_TASK_REF_FILES] NOCHECK CONSTRAINT [FK_A_TASK_REF_FILES_A_TASKS];


GO

CREATE   TRIGGER A_TASK_REF_FILES_INSERT_UPDATE
ON dbo.A_TASK_REF_FILES
AFTER INSERT,UPDATE
AS
declare 
@TASK_ID as nvarchar(50)
SELECT @TASK_ID = TASK_ID FROM INSERTED
if exists(SELECT * FROM A_TASK_REF_FILES 
	WHERE TASK_ID = @TASK_ID AND (STATUS IS NULL OR STATUS = 'ACTIVE'))
	UPDATE A_TASKS SET HAS_FILE = 1 WHERE ID = @TASK_ID
else
	UPDATE A_TASKS SET HAS_FILE = NULL WHERE ID = @TASK_ID
	



