CREATE TABLE [dbo].[A_TASK_PROCEDURE_ASSIGNEE] (
    [TASK_ID]     VARCHAR (50) NOT NULL,
    [ASSIGNEE_ID] VARCHAR (50) NOT NULL,
    [DRCM]        DATETIME     NULL,
    [MODBY]       VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_PROCEDURE_ASSIGNEE] PRIMARY KEY CLUSTERED ([TASK_ID] ASC)
);

