CREATE TABLE [dbo].[A_TASK_ACTION_OBJECT_LINK] (
    [ID]           VARCHAR (50) NOT NULL,
    [TASK_ID]      VARCHAR (50) NOT NULL,
    [OBJECT_ID]    VARCHAR (50) NOT NULL,
    [RELATIONSHIP] VARCHAR (50) NOT NULL,
    [DRCM]         DATETIME     NULL,
    [MODBY]        VARCHAR (50) NULL,
    [QTY]          FLOAT (53)   NULL,
    CONSTRAINT [PK_A_TASK_ACTION_OBJECT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [A_TASK_ACTION_OBJECT_LINK_OBJECT_ID]
    ON [dbo].[A_TASK_ACTION_OBJECT_LINK]([OBJECT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [A_TASK_ACTION_OBJECT_LINK_TASK_ID]
    ON [dbo].[A_TASK_ACTION_OBJECT_LINK]([TASK_ID] ASC);

