CREATE TABLE [dbo].[A_TASK_PRIORITY_LEVELS] (
    [ID]    SMALLINT     NOT NULL,
    [NAME]  VARCHAR (50) NULL,
    [DRCM]  DATETIME     NULL,
    [MODBY] VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_PRIORITY_LEVELS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

