CREATE TABLE [dbo].[A_TASK_DATES] (
    [ID]         VARCHAR (50) NOT NULL,
    [DATE_TYPE]  VARCHAR (50) NULL,
    [THE_DATE]   DATETIME     NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    [TASK_ID]    VARCHAR (50) NULL,
    [IS_CURRENT] SMALLINT     NULL,
    CONSTRAINT [PK_A_TASK_DATES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_DATES_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_DATES] NOCHECK CONSTRAINT [FK_A_TASK_DATES_A_TASKS];

