CREATE TABLE [dbo].[A_TASKS] (
    [ID]                         VARCHAR (50)    NOT NULL,
    [PARENT_ID]                  VARCHAR (50)    NULL,
    [Title]                      NVARCHAR (2000) NULL,
    [DESCRIPTION]                NVARCHAR (2000) NULL,
    [STATUS]                     VARCHAR (50)    NULL,
    [COMMENT]                    NVARCHAR (1600) NULL,
    [REQUESTOR]                  VARCHAR (50)    NULL,
    [COMPLETED_BY]               VARCHAR (50)    NULL,
    [MODBY]                      VARCHAR (50)    NULL,
    [DRCM]                       DATETIME        NULL,
    [CHILD_ORDER]                NUMERIC (18)    NULL,
    [CREATED_BY]                 VARCHAR (50)    NULL,
    [CREATE_DATE]                DATETIME        NULL,
    [CLOSED]                     SMALLINT        NULL,
    [OPENED_BY]                  VARCHAR (50)    NULL,
    [OPEN_DATE]                  DATETIME        NULL,
    [SYSTEM_TASK]                VARCHAR (50)    NULL,
    [PROCEDURE_ID]               VARCHAR (50)    NULL,
    [PROCEDURE_STEP_ID]          VARCHAR (50)    NULL,
    [SECURITY_LEVEL]             VARCHAR (50)    NULL,
    [COUNTER]                    VARCHAR (50)    NULL,
    [REQUESTEE_ID]               VARCHAR (50)    NULL,
    [GROUP_REQUESTEE_ID]         VARCHAR (50)    NULL,
    [COUNTER_NAME]               NVARCHAR (50)   NULL,
    [COUNTER_VALUE]              NUMERIC (18)    NULL,
    [ORIG_PLANNED_START_DATE]    DATETIME        NULL,
    [ORIG_PLANNED_STOP_DATE]     DATETIME        NULL,
    [CUR_PLANNED_START_DATE]     DATETIME        NULL,
    [CUR_PLANNED_STOP_DATE]      DATETIME        NULL,
    [ACTUAL_START_DATE]          DATETIME        NULL,
    [ACTUAL_STOP_DATE]           DATETIME        NULL,
    [ORIG_PLANNED_COUNTER_START] NUMERIC (18)    NULL,
    [ORIG_PLANNED_COUNTER_STOP]  NUMERIC (18)    NULL,
    [CUR_PLANNED_COUNTER_START]  NUMERIC (18)    NULL,
    [CUR_PLANNED_COUNTER_STOP]   NUMERIC (18)    NULL,
    [ACTUAL_COUNTER_START]       NUMERIC (18)    NULL,
    [ACTUAL_COUNTER_STOP]        NUMERIC (18)    NULL,
    [LATEST_REQUESTEE_NAME]      NVARCHAR (200)  NULL,
    [HAS_DISCUSSION]             TINYINT         NULL,
    [HAS_SURVEY]                 TINYINT         NULL,
    [HAS_CHILD]                  TINYINT         NULL,
    [HAS_REF_PROC]               TINYINT         NULL,
    [HAS_FILE]                   TINYINT         NULL,
    [ORIG_REQUESTOR_ID]          VARCHAR (50)    NULL,
    [HAS_REF_OBJ]                TINYINT         NULL,
    [HAS_MONITOR]                TINYINT         NULL,
    [COLOR_CODE]                 SMALLINT        NULL,
    [LAST_REQUEST_DATE]          DATETIME        NULL,
    [PRIORITY]                   SMALLINT        NULL,
    [CHILD_STATUS]               VARCHAR (50)    NULL,
    [IS_QUOTE]                   TINYINT         NULL,
    [IS_QUOTE_ACCEPT]            TINYINT         NULL,
    [IS_FILL]                    TINYINT         NULL,
    [MANAGER]                    VARCHAR (50)    NULL,
    [DNR_TYPE]                   VARCHAR (10)    NULL,
    [RECURSION_NUMBER]           INT             CONSTRAINT [DF_A_TASKS_RECURSION_NUMBER] DEFAULT ((1)) NULL,
    [REPEAT_FROM_STEP]           VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_ACTUAL_TASK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE1] FOREIGN KEY ([REQUESTOR]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE2] FOREIGN KEY ([COMPLETED_BY]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE4] FOREIGN KEY ([OPENED_BY]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_COUNTERS] FOREIGN KEY ([COUNTER]) REFERENCES [dbo].[A_COUNTERS] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_PEOPLE] FOREIGN KEY ([REQUESTEE_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_PROCEDURES] FOREIGN KEY ([PROCEDURE_ID]) REFERENCES [dbo].[A_PROCEDURES] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_ROLES] FOREIGN KEY ([GROUP_REQUESTEE_ID]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_SECURITY_LEVELS] FOREIGN KEY ([SECURITY_LEVEL]) REFERENCES [dbo].[A_SECURITY_LEVELS] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_TASK_PRIORITY_LEVELS] FOREIGN KEY ([PRIORITY]) REFERENCES [dbo].[A_TASK_PRIORITY_LEVELS] ([ID]),
    CONSTRAINT [FK_A_TASKS_A_TASKS] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[A_TASKS] ([ID])
);


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE1];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE2];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE4];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_COUNTERS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_PROCEDURES];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_ROLES];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_SECURITY_LEVELS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_TASK_PRIORITY_LEVELS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_TASKS];




GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE1];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE2];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE4];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_COUNTERS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_PROCEDURES];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_ROLES];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_SECURITY_LEVELS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_TASK_PRIORITY_LEVELS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_TASKS];




GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE1];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE2];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_ACTUAL_TASK_A_PEOPLE4];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_COUNTERS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_PROCEDURES];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_ROLES];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_SECURITY_LEVELS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_TASK_PRIORITY_LEVELS];


GO
ALTER TABLE [dbo].[A_TASKS] NOCHECK CONSTRAINT [FK_A_TASKS_A_TASKS];


GO

CREATE                                TRIGGER [dbo].[A_TASKS_INSERT_UPDATE]
ON [dbo].[A_TASKS]
AFTER INSERT,UPDATE
AS
print 'In A_TASKS_INSERT_UPDATE'
declare 
@ID as nvarchar(50), 
@MODBY as nvarchar(50),
@newSTATUS as nvarchar(50),
@oldSTATUS as nvarchar(50),
@procID varchar(50),
@procStepID varchar(50),
@PARENT as varchar(50),@taskName nvarchar(4000),
@SYSTEM_TASK as varchar(50)
SELECT @oldStatus = STATUS FROM DELETED
SELECT @ID = ID,@MODBY = MODBY,@newSTATUS = STATUS,@PARENT = PARENT_ID,
	@procID = PROCEDURE_ID, @procStepID = PROCEDURE_STEP_ID,@taskName = DESCRIPTION,
	@SYSTEM_TASK = SYSTEM_TASK
	FROM INSERTED
IF UPDATE(PARENT_ID)
	BEGIN
	IF @PARENT IS NOT NULL
		BEGIN
		UPDATE A_TASKS SET HAS_CHILD = 1 WHERE ID = @PARENT
		END
	END

if update(STATUS)
	begin
	print 'The status was updated from ' + @oldStatus + ' to ' + @newStatus
	if isNull(@oldStatus,'') <> isNull(@newStatus,'')
		exec A_SP_TASK_FIGURE_COMPLETION_DATA @ID,@MODBY
	if @newSTATUS = 'REQUESTED'
		begin
			UPDATE A_TASKS SET COLOR_CODE = 1 WHERE ID = @ID
		end
	if @newSTATUS = 'ACCEPTED'
		begin
			UPDATE A_TASKS SET COLOR_CODE = 2 WHERE ID = @ID
		end
	if @newSTATUS = 'FINISHED'
		begin
			UPDATE A_TASKS SET COLOR_CODE = 3 WHERE ID = @ID
		end
	if @newSTATUS = 'CLOSED'
		begin
			UPDATE A_TASKS SET COLOR_CODE = 4 WHERE ID = @ID
		end
	if @PARENT is not null
		begin
		print 'This task has a parent'
		if @newSTATUS <> 'FINISHED' and @newSTATUS <> 'CLOSED'
			UPDATE A_TASKS SET CHILD_STATUS = 'NOT_FINISHED' WHERE ID = @PARENT
		else
			exec A_SP_TASK_FIGURE_OUT_CHILD_STATUS @PARENT,@MODBY
		end
	end
IF UPDATE(PROCEDURE_ID) OR UPDATE(PROCEDURE_STEP_ID)
	BEGIN
	if @procID is not null and @procStepID is null
		begin
		declare @newTaskName nvarchar(4000)
		SELECT @newTaskName = dbo.A_FN_TASK_CREATE_NAME(@ID)
		if @newTaskName <> @taskName
			UPDATE A_TASKS SET DESCRIPTION = @newTaskName WHERe ID = @ID
		end
	END

declare @purchHistID varchar(50)
SELECT @purchHistID = PURCHASE_HIST_ID FROM A_TASK_ORDER_INFORMATION 
	WHERE TASK_ID = @ID --AND PURCHASE_ITEM_ID is NULL
declare @sql varchar(2000)
if UPDATE(STATUS) and @newStatus in ('REQUESTED','FINISHED','CLOSED') and @purchHistID is not null
	begin

	set @sql = 'exec A_SP_PURCHASE_UPDATE_PURCHASE_STATUS ''' + @purchHistID + ''',''' + @MODBY + ''''

	 IF  NOT exists(SELECT 1 FROM [dbo].[A_ADMIN_SQL_TO_RUN] WHERE CODE =@sql AND MODBY =@MODBY AND DRCM > DATEADD(hour,-1,GETDATE()))
				BEGIN					
					exec A_SP_ADMIN_SQL_TO_RUN_QUE_UP @sql,@MODBY
				END
	
	end
declare @parentSysTask varchar(50)
SELECT @parentSysTask = SYSTEM_TASK FROM A_TASKS WHERE ID = @PARENT
if @parentSysTask = 'SYS_DNR'
	begin
	CREATE TABLE #tempTable (ID VARCHAR(50))
	declare @caseCount int
	INSERT INTO #TEMPTABLE exec A_SP_DNR_FIND_MATCHING_CASES @PARENT
	SELECT @caseCount = count(ID) FROM #tempTable
	DELETE FROM A_DNR_TASK_NUM_MATCHING_CASES WHERE TASK_ID = @ID
	INSERT INTO A_DNR_TASK_NUM_MATCHING_CASES (ID,TASK_ID,NUM_CASES,DRCM,MODBY)
		VALUES (newID(),@ID,@caseCount,getDate(),@MODBY)
	end

declare @oldParentID as varchar(50)
SELECT @oldParentID = PARENT_ID FROM DELETED
if UPDATE(PARENT_ID) AND @ID is not null and (isnull(@oldParentID,'')<>isNull(@PARENT,''))
	begin
	exec A_SP_TASKS_UPDATE_ONE_TASK_SUB_TABLE @ID,0
	SELECT @purchHistID = PURCHASE_HIST_ID FROM A_TASK_ORDER_INFORMATION WHERE TASK_ID = @PARENT
	if @purchHistID is not null
		if exists(SELECT * FROM A_TASK_ORDER_INFORMATION WHERE TASK_ID = @ID)
			UPDATE A_TASK_ORDER_INFORMATION SET PURCHASE_HIST_ID = @purchHistID WHERE TASK_ID = @ID
		else
			INSERT INTO A_TASK_ORDER_INFORMATION (TASK_ID,PURCHASE_HIST_ID)
				VALUES(@ID,@purchHistID)
	end

IF UPDATE(STATUS)
	exec A_SP_TASK_UPDATE_MINUTES @ID,@MODBY


GO
CREATE NONCLUSTERED INDEX [IX_A_TASKS_EXECPLAN_02]
    ON [dbo].[A_TASKS]([PROCEDURE_STEP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_A_TASKS_EXECPLAN_01]
    ON [dbo].[A_TASKS]([PARENT_ID] ASC, [RECURSION_NUMBER] ASC);

