CREATE TABLE [dbo].[A_TASK_SURVEY_LINK] (
    [ID]        VARCHAR (50) NOT NULL,
    [TASK_ID]   VARCHAR (50) NULL,
    [SURVEY_ID] VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_SURVEY_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_SURVEY_LINK_A_SURVEYS1] FOREIGN KEY ([SURVEY_ID]) REFERENCES [dbo].[A_SURVEYS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_SURVEY_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_SURVEY_LINK] NOCHECK CONSTRAINT [FK_A_TASK_SURVEY_LINK_A_SURVEYS1];


GO
ALTER TABLE [dbo].[A_TASK_SURVEY_LINK] NOCHECK CONSTRAINT [FK_A_TASK_SURVEY_LINK_A_TASKS];


GO



/*
*/
CREATE  TRIGGER A_TASK_SURVEY_LINK_INSERT
ON dbo.A_TASK_SURVEY_LINK
AFTER INSERT
AS
declare @taskID varchar(50),@fromID varchar(50),@modby varchar(50)
SELECT @taskID = TASK_ID,@fromID = SURVEY_ID,@modby = MODBY FROM INSERTED
exec A_SP_PROJECT_COPY_ONE_ITEMS_PROJ_OBJ_PURP_TAGS @fromID,'A_SURVEYS',@taskID,'A_TASKS',@modby
UPDATE A_TASKS SET HAS_SURVEY = 1 WHERE ID = @taskID
