CREATE TABLE [dbo].[A_TASK_MONITORS] (
    [ID]                  NVARCHAR (50)   NOT NULL,
    [TASK_ID]             VARCHAR (50)    NOT NULL,
    [MONITOR_TEMPLATE_ID] VARCHAR (50)    NULL,
    [RESULT]              NVARCHAR (50)   NULL,
    [DATE_RECORDED]       DATETIME        NULL,
    [COMMENT]             NVARCHAR (1600) NULL,
    [MODBY]               VARCHAR (50)    NULL,
    [DRCM]                DATETIME        NULL,
    [DESCRIPTION]         NVARCHAR (100)  NULL,
    [START_TASK]          VARCHAR (50)    NULL,
    [STOP_TASK]           VARCHAR (50)    NULL,
    [START_TYPE]          VARCHAR (50)    NULL,
    [STOP_TYPE]           VARCHAR (50)    NULL,
    [UNITS]               VARCHAR (50)    NULL,
    [CREATE_DATE]         DATETIME        NULL,
    [CREATED_BY]          VARCHAR (50)    NULL,
    [AUTO]                SMALLINT        NULL,
    [IS_SYSTEM]           NUMERIC (18)    NULL,
    [TARGET_TEXT]         NVARCHAR (100)  NULL,
    [RESULT_TEXT]         NVARCHAR (100)  NULL,
    CONSTRAINT [PK_A_ACTUAL_KPIS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_ACTUAL_KPIS_A_KPI_TEMPLATES] FOREIGN KEY ([MONITOR_TEMPLATE_ID]) REFERENCES [dbo].[A_MONITOR_TEMPLATES] ([ID]),
    CONSTRAINT [FK_A_TASK_MONITORS_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_MONITORS] NOCHECK CONSTRAINT [FK_A_ACTUAL_KPIS_A_KPI_TEMPLATES];


GO
ALTER TABLE [dbo].[A_TASK_MONITORS] NOCHECK CONSTRAINT [FK_A_TASK_MONITORS_A_TASKS];

