CREATE TABLE [dbo].[A_TASKS_RELATION_TABLE] (
    [ID]        VARCHAR (50) NOT NULL,
    [PARENT_ID] VARCHAR (50) NOT NULL,
    [CHILD_ID]  VARCHAR (50) NOT NULL,
    [LEV]       SMALLINT     NOT NULL,
    CONSTRAINT [PK_A_TASKS_RELATION_TABLE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASKS_RELATION_TABLE_A_TASKS] FOREIGN KEY ([CHILD_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASKS_RELATION_TABLE] NOCHECK CONSTRAINT [FK_A_TASKS_RELATION_TABLE_A_TASKS];

