CREATE TABLE [dbo].[A_TASK_COMPANIES_TO_VIEW_LINK] (
    [ID]      VARCHAR (50) NOT NULL,
    [TASK_ID] VARCHAR (50) NULL,
    [CO_ID]   VARCHAR (50) NULL,
    [DRCM]    DATETIME     NULL,
    [MODBY]   VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_COMPANIES_TO_VIEW_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_COMPANIES_TO_VIEW_LINK_A_COMPANIES] FOREIGN KEY ([CO_ID]) REFERENCES [dbo].[A_COMPANIES] ([ID]),
    CONSTRAINT [FK_A_TASK_COMPANIES_TO_VIEW_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_COMPANIES_TO_VIEW_LINK] NOCHECK CONSTRAINT [FK_A_TASK_COMPANIES_TO_VIEW_LINK_A_COMPANIES];


GO
ALTER TABLE [dbo].[A_TASK_COMPANIES_TO_VIEW_LINK] NOCHECK CONSTRAINT [FK_A_TASK_COMPANIES_TO_VIEW_LINK_A_TASKS];


GO
CREATE NONCLUSTERED INDEX [A_TASK_COMPAIES_TO_VIEW_CO_ID]
    ON [dbo].[A_TASK_COMPANIES_TO_VIEW_LINK]([CO_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [A_TASK_COMPAIES_TO_VIEW_TASK_ID]
    ON [dbo].[A_TASK_COMPANIES_TO_VIEW_LINK]([TASK_ID] ASC);

