CREATE TABLE [dbo].[A_TASK_REFERENCE_PROCEDURES] (
    [ID]            VARCHAR (50) NOT NULL,
    [TASK_ID]       VARCHAR (50) NULL,
    [REF_PROCEDURE] VARCHAR (50) NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_REFERENCE_PROCEDURES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_REFERENCE_PROCEDURES_A_PROCEDURES] FOREIGN KEY ([REF_PROCEDURE]) REFERENCES [dbo].[A_PROCEDURES] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_REFERENCE_PROCEDURES_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_REFERENCE_PROCEDURES] NOCHECK CONSTRAINT [FK_A_TASK_REFERENCE_PROCEDURES_A_PROCEDURES];


GO
ALTER TABLE [dbo].[A_TASK_REFERENCE_PROCEDURES] NOCHECK CONSTRAINT [FK_A_TASK_REFERENCE_PROCEDURES_A_TASKS];


GO




/*
*/
CREATE TRIGGER A_TASK_REFERENCE_PROCEDURES_INSERT
ON dbo.A_TASK_REFERENCE_PROCEDURES
AFTER INSERT
AS
declare @taskID varchar(50)
SELECT @taskID = TASK_ID FROM INSERTED
UPDATE A_TASKS SET HAS_REF_PROC = 1 WHERE ID = @taskID

