CREATE TABLE [dbo].[A_TASK_LAST_COMMENT] (
    [ID]         VARCHAR (50) NULL,
    [TASK_ID]    VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    [COMMENT_ID] VARCHAR (50) NULL,
    CONSTRAINT [FK_A_TASK_LAST_COMMENT_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_LAST_COMMENT] NOCHECK CONSTRAINT [FK_A_TASK_LAST_COMMENT_A_TASKS];

