CREATE TABLE [dbo].[A_TASK_COMPLETION_STATS] (
    [TASK_ID]                VARCHAR (50)   NOT NULL,
    [PERC_COMPLETE]          FLOAT (53)     NULL,
    [TIME_COMPLETE]          FLOAT (53)     NULL,
    [TOTAL_TIME]             FLOAT (53)     NULL,
    [DRCM]                   DATETIME       NULL,
    [MODBY]                  VARCHAR (50)   NULL,
    [NUM_SUB_TASKS]          INT            NULL,
    [MY_TOT_HOURS]           FLOAT (53)     NULL,
    [MY_COMP_HOURS]          FLOAT (53)     NULL,
    [PARENT_TASK_ID]         VARCHAR (50)   NULL,
    [NUM_SUB_TASKS_COMPLETE] INT            NULL,
    [CUR_STEP_TEXT]          VARCHAR (4000) NULL,
    CONSTRAINT [PK_TASK_COMPLETION_STATS] PRIMARY KEY CLUSTERED ([TASK_ID] ASC),
    CONSTRAINT [FK_TASK_COMPLETION_STATS_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_COMPLETION_STATS] NOCHECK CONSTRAINT [FK_TASK_COMPLETION_STATS_A_TASKS];

