CREATE TABLE [dbo].[A_TASK_CC_PEOPLE] (
    [ID]        VARCHAR (50) NOT NULL,
    [TASK_ID]   VARCHAR (50) NOT NULL,
    [PERSON_ID] VARCHAR (50) NOT NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_CC_PEOPLE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_CC_PEOPLE_A_ACTUAL_TASK] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_CC_PEOPLE_A_PEOPLE] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID])
);


GO
ALTER TABLE [dbo].[A_TASK_CC_PEOPLE] NOCHECK CONSTRAINT [FK_A_TASK_CC_PEOPLE_A_ACTUAL_TASK];


GO
ALTER TABLE [dbo].[A_TASK_CC_PEOPLE] NOCHECK CONSTRAINT [FK_A_TASK_CC_PEOPLE_A_PEOPLE];

