CREATE TABLE [dbo].[A_TASK_LOOK_UP_TABLE] (
    [TASK_ID]               VARCHAR (50)   NOT NULL,
    [LATEST_REQUESTEE_NAME] NVARCHAR (200) NULL,
    [MONITOR_STATUS]        VARCHAR (50)   NULL,
    CONSTRAINT [PK_A_TASK_LOOK_UP_TABLE] PRIMARY KEY CLUSTERED ([TASK_ID] ASC)
);

