CREATE TABLE [dbo].[A_TASK_ASSIGNEE] (
    [ID]                          VARCHAR (50)    NOT NULL,
    [TASK_ID]                     VARCHAR (50)    NULL,
    [PERSON_ASSIGNED]             VARCHAR (50)    NULL,
    [ROLE_ASSIGNED]               VARCHAR (50)    NULL,
    [ASSIGNEE_CURRENTLY_ACCEPTED] SMALLINT        NULL,
    [ASSIGN_DATE]                 DATETIME        NULL,
    [ASSIGNER]                    VARCHAR (50)    NULL,
    [ACCEPTED_DATE]               DATETIME        NULL,
    [REJECTED_BY]                 VARCHAR (50)    NULL,
    [REJECTION_DATE]              DATETIME        NULL,
    [REASON_REJECTED]             NVARCHAR (1000) NULL,
    [REQUESTOR]                   VARCHAR (50)    NULL,
    [REQUEST_DATE]                DATETIME        NULL,
    [DRCM]                        DATETIME        NULL,
    [MODBY]                       VARCHAR (50)    NULL,
    [ROLE_TASK_ACCEPTED_UNDER]    VARCHAR (50)    NULL,
    [ACTIVE]                      SMALLINT        NULL,
    [STATUS]                      VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_TASK_ASSIGNEE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_ASSIGNEE_A_PEOPLE] FOREIGN KEY ([ASSIGNER]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_TASK_ASSIGNEE_A_PEOPLE1] FOREIGN KEY ([PERSON_ASSIGNED]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_TASK_ASSIGNEE_A_PEOPLE2] FOREIGN KEY ([REQUESTOR]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_TASK_ASSIGNEE_A_ROLES] FOREIGN KEY ([ROLE_ASSIGNED]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_TASK_ASSIGNEE_A_ROLES1] FOREIGN KEY ([ROLE_TASK_ACCEPTED_UNDER]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_TASK_ASSIGNEE_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_TASK_ASSIGNEE_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_TASK_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_TASK_ASSIGNEE_A_PEOPLE1];


GO
ALTER TABLE [dbo].[A_TASK_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_TASK_ASSIGNEE_A_PEOPLE2];


GO
ALTER TABLE [dbo].[A_TASK_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_TASK_ASSIGNEE_A_ROLES];


GO
ALTER TABLE [dbo].[A_TASK_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_TASK_ASSIGNEE_A_ROLES1];


GO
ALTER TABLE [dbo].[A_TASK_ASSIGNEE] NOCHECK CONSTRAINT [FK_A_TASK_ASSIGNEE_A_TASKS];

