CREATE TABLE [dbo].[A_TASK_CUSTOMER_LINK] (
    [TASK_ID]     VARCHAR (50)  NULL,
    [CUSTOMER_ID] VARCHAR (50)  NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       NVARCHAR (50) NULL,
    [ID]          NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_A_TASK_CUSTOMER_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_CUSTOMER_LINK_A_ACTUAL_TASK] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_CUSTOMER_LINK_A_ROLES] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[A_ROLES] ([ID])
);


GO
ALTER TABLE [dbo].[A_TASK_CUSTOMER_LINK] NOCHECK CONSTRAINT [FK_A_TASK_CUSTOMER_LINK_A_ACTUAL_TASK];


GO
ALTER TABLE [dbo].[A_TASK_CUSTOMER_LINK] NOCHECK CONSTRAINT [FK_A_TASK_CUSTOMER_LINK_A_ROLES];

