CREATE TABLE [dbo].[A_TASK_EMAIL_PEOPLE_LINK] (
    [ID]        VARCHAR (50) NOT NULL,
    [TASK_ID]   VARCHAR (50) NULL,
    [PERSON_ID] VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_EMAIL_PEOPLE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_EMAIL_PEOPLE_LINK_A_PEOPLE] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_TASK_EMAIL_PEOPLE_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_EMAIL_PEOPLE_LINK] NOCHECK CONSTRAINT [FK_A_TASK_EMAIL_PEOPLE_LINK_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_TASK_EMAIL_PEOPLE_LINK] NOCHECK CONSTRAINT [FK_A_TASK_EMAIL_PEOPLE_LINK_A_TASKS];

