CREATE TABLE [dbo].[A_TASK_PROJECT_LINK] (
    [ID]         VARCHAR (50) NOT NULL,
    [TASK_ID]    VARCHAR (50) NULL,
    [PROJECT_ID] VARCHAR (50) NULL,
    [DRCM]       DATETIME     NULL,
    [MODBY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_PROJECT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_PROJECT_LINK_A_PROJECTS] FOREIGN KEY ([PROJECT_ID]) REFERENCES [dbo].[A_PROJECTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_TASK_PROJECT_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_PROJECT_LINK] NOCHECK CONSTRAINT [FK_A_TASK_PROJECT_LINK_A_PROJECTS];


GO
ALTER TABLE [dbo].[A_TASK_PROJECT_LINK] NOCHECK CONSTRAINT [FK_A_TASK_PROJECT_LINK_A_TASKS];

