CREATE TABLE [dbo].[A_TASK_OBJECT_LINK] (
    [ID]        VARCHAR (50) NOT NULL,
    [TASK_ID]   VARCHAR (50) NULL,
    [OBJECT_ID] VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    [MODBY]     VARCHAR (50) NULL,
    CONSTRAINT [PK_A_TASK_OBJECT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TASK_OBJECT_LINK_A_APPROVED_OBJECTS] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[A_APPROVED_OBJECTS] ([ID]),
    CONSTRAINT [FK_A_TASK_OBJECT_LINK_A_TASKS] FOREIGN KEY ([TASK_ID]) REFERENCES [dbo].[A_TASKS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TASK_OBJECT_LINK] NOCHECK CONSTRAINT [FK_A_TASK_OBJECT_LINK_A_APPROVED_OBJECTS];


GO
ALTER TABLE [dbo].[A_TASK_OBJECT_LINK] NOCHECK CONSTRAINT [FK_A_TASK_OBJECT_LINK_A_TASKS];


GO
CREATE NONCLUSTERED INDEX [A_TASK_OBJECT_LINK_OBJECT_ID]
    ON [dbo].[A_TASK_OBJECT_LINK]([OBJECT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [A_TASK_OBJECT_LINK_TASK_ID]
    ON [dbo].[A_TASK_OBJECT_LINK]([TASK_ID] ASC);


GO


CREATE TRIGGER A_TASK_OBJECT_LINK_INSERT
ON dbo.A_TASK_OBJECT_LINK
AFTER INSERT
AS
declare @TASK_ID as nvarchar(50)
SELECT @TASK_ID = TASK_ID
	FROM INSERTED
UPDATE A_TASKS SET HAS_REF_PROC  = 1 WHERE ID = @TASK_ID


