CREATE TABLE [dbo].[A_TEST_SET_POINTS] (
    [TEST_TASK] VARCHAR (50)  NOT NULL,
    [TASK_TYPE] NVARCHAR (50) NOT NULL,
    [SET_POINT] NVARCHAR (50) NOT NULL,
    [DRCM]      DATETIME      NULL,
    [MODBY]     NVARCHAR (50) NULL,
    CONSTRAINT [FK_A_TEST_SET_POINTS_A_TEMPLATE_TASKS] FOREIGN KEY ([TEST_TASK]) REFERENCES [dbo].[A_PROCEDURES] ([ID])
);


GO
ALTER TABLE [dbo].[A_TEST_SET_POINTS] NOCHECK CONSTRAINT [FK_A_TEST_SET_POINTS_A_TEMPLATE_TASKS];

