CREATE TABLE [dbo].[A_THEORY_REFERENCE_THEORY] (
    [ID]          VARCHAR (50)  NOT NULL,
    [THEORY_ID]   VARCHAR (50)  NOT NULL,
    [THEORY_LINK] VARCHAR (50)  NOT NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_THEORY_REFERENCE_THEORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_REFERENCE_THEORY_A_THEORY_HISTORY] FOREIGN KEY ([THEORY_ID]) REFERENCES [dbo].[A_THEORY_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_REFERENCE_THEORY] NOCHECK CONSTRAINT [FK_A_THEORY_REFERENCE_THEORY_A_THEORY_HISTORY];

