CREATE TABLE [dbo].[A_THEORY_REFERENCE_OBJECTS] (
    [ID]        VARCHAR (50)  NOT NULL,
    [THEORY_ID] VARCHAR (50)  NOT NULL,
    [OBJ_ID]    VARCHAR (50)  NOT NULL,
    [DRCM]      DATETIME      NULL,
    [MODBY]     NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_THEORY_REFERENCE_OBJECTS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_REFERENCE_OBJECTS_A_THEORY_HISTORY] FOREIGN KEY ([THEORY_ID]) REFERENCES [dbo].[A_THEORY_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_REFERENCE_OBJECTS] NOCHECK CONSTRAINT [FK_A_THEORY_REFERENCE_OBJECTS_A_THEORY_HISTORY];

