CREATE TABLE [dbo].[A_THEORY_PARAGRAPH_FILE_LINK] (
    [ID]           NVARCHAR (50) NOT NULL,
    [PARAGRAPH_ID] VARCHAR (50)  NULL,
    [FILE_ID]      VARCHAR (50)  NULL,
    [DRCM]         DATETIME      NULL,
    [MODBY]        NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_THEORY_PARAGRAPH_FILE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_PARAGRAPH_FILE_LINK_A_DOCUMENTS] FOREIGN KEY ([FILE_ID]) REFERENCES [dbo].[A_DOCUMENTS] ([ID]),
    CONSTRAINT [FK_A_THEORY_PARAGRAPH_FILE_LINK_A_THEORY_PARAGRAPHS] FOREIGN KEY ([PARAGRAPH_ID]) REFERENCES [dbo].[A_THEORY_PARAGRAPHS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_PARAGRAPH_FILE_LINK] NOCHECK CONSTRAINT [FK_A_THEORY_PARAGRAPH_FILE_LINK_A_DOCUMENTS];


GO
ALTER TABLE [dbo].[A_THEORY_PARAGRAPH_FILE_LINK] NOCHECK CONSTRAINT [FK_A_THEORY_PARAGRAPH_FILE_LINK_A_THEORY_PARAGRAPHS];

