CREATE TABLE [dbo].[A_THEORY_HISTORY] (
    [ID]             VARCHAR (50)    NOT NULL,
    [OBJECT_ID]      VARCHAR (50)    NULL,
    [NAME]           NVARCHAR (200)  NULL,
    [COMMENTS]       NVARCHAR (4000) NULL,
    [SECURITY_LEVEL] VARCHAR (50)    NOT NULL,
    [DRCM]           DATETIME        NULL,
    [MODBY]          VARCHAR (50)    NULL,
    [CREATING_DEPT]  VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_THEORY_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_HISTORY_A_COMPANIES] FOREIGN KEY ([CREATING_DEPT]) REFERENCES [dbo].[A_COMPANIES] ([ID]),
    CONSTRAINT [FK_A_THEORY_HISTORY_A_OBJECTS] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[A_OBJECTS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_THEORY_HISTORY_A_SECURITY_LEVELS] FOREIGN KEY ([SECURITY_LEVEL]) REFERENCES [dbo].[A_SECURITY_LEVELS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_HISTORY] NOCHECK CONSTRAINT [FK_A_THEORY_HISTORY_A_COMPANIES];


GO
ALTER TABLE [dbo].[A_THEORY_HISTORY] NOCHECK CONSTRAINT [FK_A_THEORY_HISTORY_A_OBJECTS];


GO
ALTER TABLE [dbo].[A_THEORY_HISTORY] NOCHECK CONSTRAINT [FK_A_THEORY_HISTORY_A_SECURITY_LEVELS];


GO




CREATE           TRIGGER A_THEORY_HISTORY_INSERT
ON dbo.A_THEORY_HISTORY
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(2000)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_THEORY_HISTORY',@ID,@NAME,@MODBY,null,null,null

Declare @cID varchar(50)
SELECT @cID = COMPANY FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @MODBY
print 'Creating Department = ' + @cID
UPDATE A_THEORY_HISTORY SET CREATING_DEPT = @cID WHERE ID = @ID





GO



CREATE              TRIGGER A_THEORY_HISTORY_UPDATE
ON dbo.A_THEORY_HISTORY
AFTER UPDATE
AS

declare @OBJ_ID as nvarchar(50)
declare @ID as nvarchar(50)
declare @NAME as nvarchar(2000)
declare @MODBY as nvarchar(50)
print 'In the Theory History Update Trigger'
SELECT
@ID = ID,
@OBJ_ID = OBJECT_ID,
@NAME = NAME,
@MODBY = MODBY 
FROM INSERTED
if update(NAME)
	begin
	UPDATE A_OBJECTS SET
	OBJ_DESC = @NAME,
	MODBY = @MODBY,
	DRCM = getDATE()
	WHERE ID = @OBJ_ID
	end



