CREATE TABLE [dbo].[A_THEORY_PARAGRAPH_PROCEDURE_LINK] (
    [ID]               NVARCHAR (50) NOT NULL,
    [THEORY_PARAGRAPH] VARCHAR (50)  NULL,
    [PROCEDURE_LINK]   VARCHAR (50)  NULL,
    [DRCM]             DATETIME      NULL,
    [MODBY]            NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_THEORY_PARAGRAPH_PROCEDURE_LINK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

