CREATE TABLE [dbo].[A_THEORY_PARAGRAPHS] (
    [ID]                     VARCHAR (50)    NOT NULL,
    [THEORY_ID]              VARCHAR (50)    NULL,
    [PARAGRAPH_STYLE]        NVARCHAR (50)   NULL,
    [PARAGRAPH_NUMBER]       VARCHAR (50)    NULL,
    [PARAGRAPH_INDENT]       VARCHAR (50)    NULL,
    [PARAGRAPH_HEADING]      NVARCHAR (400)  NULL,
    [PARAGRAPH_TEXT]         NVARCHAR (4000) NULL,
    [COMMENTS]               NVARCHAR (4000) NULL,
    [DRCM]                   DATETIME        NULL,
    [MODBY]                  NVARCHAR (50)   NULL,
    [PRINT_ORDER]            NUMERIC (18)    NULL,
    [OLD_THEORY_ID]          VARCHAR (50)    NULL,
    [OLD_PARAGRAPH_ID]       NVARCHAR (50)   NULL,
    [PARAGRAPH_ORDER_NUMBER] REAL            NULL,
    [PARAGRAPH_SPACE_STYLE]  VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_THEORY_PARAGRAPHS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_PARAGRAPHS_A_THEORY_HISTORY] FOREIGN KEY ([THEORY_ID]) REFERENCES [dbo].[A_THEORY_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_PARAGRAPHS] NOCHECK CONSTRAINT [FK_A_THEORY_PARAGRAPHS_A_THEORY_HISTORY];

