CREATE TABLE [dbo].[A_THEORY_COMMENTS] (
    [ID]             VARCHAR (50)    NOT NULL,
    [DATA]           NVARCHAR (4000) NULL,
    [LOC]            VARCHAR (50)    NULL,
    [THEORY_HIST_ID] VARCHAR (50)    NULL,
    [DRCM]           DATETIME        NULL,
    [MODBY]          VARCHAR (50)    NULL,
    [PRINT_ORDER]    REAL            NULL,
    CONSTRAINT [PK_A_THEORY_COMMENT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_COMMENTS_A_THEORY_HISTORY] FOREIGN KEY ([THEORY_HIST_ID]) REFERENCES [dbo].[A_THEORY_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_COMMENTS] NOCHECK CONSTRAINT [FK_A_THEORY_COMMENTS_A_THEORY_HISTORY];

