CREATE TABLE [dbo].[A_THEORY_PARAGRAPH_THEORY_LINK] (
    [ID]               VARCHAR (50)  NOT NULL,
    [THEORY_PARAGRAPH] VARCHAR (50)  NOT NULL,
    [THEORY_LINK]      VARCHAR (50)  NULL,
    [DRCM]             DATETIME      NULL,
    [MODBY]            NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_THEORY_PARAGRAPH_THEORY_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_THEORY_PARAGRAPH_THEORY_LINK_A_THEORY_PARAGRAPHS] FOREIGN KEY ([THEORY_PARAGRAPH]) REFERENCES [dbo].[A_THEORY_PARAGRAPHS] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_THEORY_PARAGRAPH_THEORY_LINK] NOCHECK CONSTRAINT [FK_A_THEORY_PARAGRAPH_THEORY_LINK_A_THEORY_PARAGRAPHS];

