CREATE TABLE [dbo].[A_TT_VERBS_TYPE_LOOKUP] (
    [ID]    NVARCHAR (50) NOT NULL,
    [NAME]  NVARCHAR (50) NULL,
    [DRCM]  DATETIME      NULL,
    [MODBY] NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_TT_VERBS_TYPE_LOOKUP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

