CREATE TABLE [dbo].[A_TT_VERBS] (
    [ID]             NVARCHAR (50) NOT NULL,
    [HISTORY_REF_ID] NVARCHAR (50) NULL,
    [DRCM]           DATETIME      NULL,
    [MODBY]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_TT_VERBS_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_TT_VERBS_A_TT_VERBS_HISTORY] FOREIGN KEY ([HISTORY_REF_ID]) REFERENCES [dbo].[A_TT_VERBS_HISTORY] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_TT_VERBS] NOCHECK CONSTRAINT [FK_A_TT_VERBS_A_TT_VERBS_HISTORY];

