CREATE TABLE [dbo].[A_UNIT_TYPES] (
    [ID]        VARCHAR (50)  NOT NULL,
    [NAME]      VARCHAR (100) NULL,
    [DRCM]      DATETIME      NULL,
    [MODBY]     VARCHAR (50)  NULL,
    [NUM]       SMALLINT      NULL,
    [UNIT_TYPE] VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_UNIT_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

