CREATE TABLE [dbo].[A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS] (
    [ID]      NVARCHAR (50) NOT NULL,
    [WFGS_ID] NVARCHAR (50) NOT NULL,
    [PERSON]  VARCHAR (50)  NOT NULL,
    [DRCM]    DATETIME      NULL,
    [MODBY]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS_A_PEOPLE] FOREIGN KEY ([PERSON]) REFERENCES [dbo].[A_PEOPLE] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS_A_WORKFLOW_GROUP_STARTED] FOREIGN KEY ([WFGS_ID]) REFERENCES [dbo].[A_WORKFLOW_GROUP_STARTED] ([ID])
);


GO
ALTER TABLE [dbo].[A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS] NOCHECK CONSTRAINT [FK_A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS] NOCHECK CONSTRAINT [FK_A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS_A_WORKFLOW_GROUP_STARTED];

