CREATE TABLE [dbo].[A_WF_ACTIVITIES] (
    [ID]       NVARCHAR (50)  NOT NULL,
    [ACTIVITY] NVARCHAR (100) NOT NULL,
    [DRCM]     DATETIME       NULL,
    [MODBY]    CHAR (10)      NULL,
	[Title] NVARCHAR (50) NULL
    CONSTRAINT [PK_A_WF_ACTIVITIES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

