CREATE TABLE [dbo].[A_WF_GROUP_PEOPLE_LINK] (
    [WF_GROUP_ID] NVARCHAR (50) NULL,
    [USER_ID]     VARCHAR (50)  NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       NVARCHAR (50) NULL,
    CONSTRAINT [FK_A_WF_GROUP_APPROVERS_A_PEOPLE] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_WF_GROUP_APPROVERS_A_WF_GROUPS] FOREIGN KEY ([WF_GROUP_ID]) REFERENCES [dbo].[A_WF_GROUPS] ([ID])
);


GO
ALTER TABLE [dbo].[A_WF_GROUP_PEOPLE_LINK] NOCHECK CONSTRAINT [FK_A_WF_GROUP_APPROVERS_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_WF_GROUP_PEOPLE_LINK] NOCHECK CONSTRAINT [FK_A_WF_GROUP_APPROVERS_A_WF_GROUPS];

