CREATE TABLE [dbo].[A_WF_GROUP_SPECIAL_MEMBERS] (
    [ID]    VARCHAR (50)   NOT NULL,
    [NAME]  NVARCHAR (100) NULL,
    [DRCM]  DATETIME       NULL,
    [MODBY] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_A_WF_GROUP_SPECIAL_MEMBERS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

