CREATE TABLE [dbo].[A_WF_STAGE_GROUP_LINK] (
    [WF_STAGE_ID] NVARCHAR (50) NULL,
    [WF_GROUP_ID] NVARCHAR (50) NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       NVARCHAR (50) NULL,
    CONSTRAINT [FK_A_WF_STAGE_GROUP_ASSC_A_WF_GROUPS] FOREIGN KEY ([WF_GROUP_ID]) REFERENCES [dbo].[A_WF_GROUPS] ([ID]),
    CONSTRAINT [FK_A_WF_STAGE_GROUP_ASSC_A_WF_STAGES] FOREIGN KEY ([WF_STAGE_ID]) REFERENCES [dbo].[A_WF_STAGES] ([ID])
);


GO
ALTER TABLE [dbo].[A_WF_STAGE_GROUP_LINK] NOCHECK CONSTRAINT [FK_A_WF_STAGE_GROUP_ASSC_A_WF_GROUPS];


GO
ALTER TABLE [dbo].[A_WF_STAGE_GROUP_LINK] NOCHECK CONSTRAINT [FK_A_WF_STAGE_GROUP_ASSC_A_WF_STAGES];

