CREATE TABLE [dbo].[A_WF_ACT_LINK] (
    [ID]     NVARCHAR (50) NOT NULL,
    [WF_ID]  VARCHAR (50)  NOT NULL,
    [ACT_ID] NVARCHAR (50) NOT NULL,
    [DRCM]   DATETIME      NULL,
    [MODBY]  NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_WF_ACT_LINK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_WF_ACT_LINK_A_WF_ACTIVITIES] FOREIGN KEY ([ACT_ID]) REFERENCES [dbo].[A_WF_ACTIVITIES] ([ID]),
    CONSTRAINT [FK_A_WF_ACT_LINK_A_WORKFLOWS] FOREIGN KEY ([WF_ID]) REFERENCES [dbo].[A_WORKFLOWS] ([ID])
);


GO
ALTER TABLE [dbo].[A_WF_ACT_LINK] NOCHECK CONSTRAINT [FK_A_WF_ACT_LINK_A_WF_ACTIVITIES];


GO
ALTER TABLE [dbo].[A_WF_ACT_LINK] NOCHECK CONSTRAINT [FK_A_WF_ACT_LINK_A_WORKFLOWS];

