CREATE TABLE [dbo].[A_WF_STAGES] (
    [ID]        NVARCHAR (50) NOT NULL,
    [NAME]      NVARCHAR (50) NULL,
    [HIDE]      BIT           NULL,
    [DRCM]      DATETIME      NULL,
    [MODBY]     NVARCHAR (50) NULL,
    [OBJECT_ID] NVARCHAR (50) NULL,
    CONSTRAINT [PK_A_WF_STAGES] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO





CREATE   TRIGGER A_WF_STAGES_INSERT
ON A_WF_STAGES
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT  @ID = ID,@NAME = NAME FROM INSERTED
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_WF_STAGES',@ID,@NAME,@MODBY,null,null,null






GO


CREATE  TRIGGER A_WF_STAGES_UPDATE
ON A_WF_STAGES
AFTER UPDATE
AS
declare @OBJ_ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT  @OBJ_ID = OBJECT_ID,@NAME = NAME,@MODBY = MODBY FROM INSERTED
UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID



