CREATE TABLE [dbo].[A_WF_GROUP_ROLE_LINK] (
    [ROLE_ID]     VARCHAR (50)  NOT NULL,
    [WF_GROUP_ID] NVARCHAR (50) NOT NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       NVARCHAR (50) NULL,
    CONSTRAINT [FK_A_WF_GROUP_ROLE_LINK_A_ROLES] FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[A_ROLES] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_A_WF_GROUP_ROLE_LINK_A_WF_GROUPS] FOREIGN KEY ([WF_GROUP_ID]) REFERENCES [dbo].[A_WF_GROUPS] ([ID])
);


GO
ALTER TABLE [dbo].[A_WF_GROUP_ROLE_LINK] NOCHECK CONSTRAINT [FK_A_WF_GROUP_ROLE_LINK_A_ROLES];


GO
ALTER TABLE [dbo].[A_WF_GROUP_ROLE_LINK] NOCHECK CONSTRAINT [FK_A_WF_GROUP_ROLE_LINK_A_WF_GROUPS];

