CREATE TABLE [dbo].[A_WF_GROUP_SPECIALS_LINK] (
    [SPECIAL_CODE] NVARCHAR (50) NOT NULL,
    [WF_GROUP_ID]  NVARCHAR (50) NOT NULL,
    [DRCM]         DATETIME      NULL,
    [MODBY]        NVARCHAR (50) NULL,
    CONSTRAINT [FK_A_WF_GROUP_SPECIALS_LINK_A_WF_GROUPS] FOREIGN KEY ([WF_GROUP_ID]) REFERENCES [dbo].[A_WF_GROUPS] ([ID])
);


GO
ALTER TABLE [dbo].[A_WF_GROUP_SPECIALS_LINK] NOCHECK CONSTRAINT [FK_A_WF_GROUP_SPECIALS_LINK_A_WF_GROUPS];

