CREATE TABLE [dbo].[A_WORKFLOW_STAGE_LINK] (
    [WF_ID]       VARCHAR (50)  NULL,
    [WF_STAGE_ID] NVARCHAR (50) NULL,
    [NUM]         NUMERIC (18)  NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       NVARCHAR (50) NULL,
    CONSTRAINT [FK_A_WORKFLOW_STAGE_LINK_A_WF_STAGES] FOREIGN KEY ([WF_STAGE_ID]) REFERENCES [dbo].[A_WF_STAGES] ([ID]),
    CONSTRAINT [FK_A_WORKFLOW_STAGE_LINK_A_WORKFLOWS] FOREIGN KEY ([WF_ID]) REFERENCES [dbo].[A_WORKFLOWS] ([ID])
);


GO
ALTER TABLE [dbo].[A_WORKFLOW_STAGE_LINK] NOCHECK CONSTRAINT [FK_A_WORKFLOW_STAGE_LINK_A_WF_STAGES];


GO
ALTER TABLE [dbo].[A_WORKFLOW_STAGE_LINK] NOCHECK CONSTRAINT [FK_A_WORKFLOW_STAGE_LINK_A_WORKFLOWS];

