CREATE TABLE [dbo].[A_WORKFLOWS_STARTED] (
    [ID]                   VARCHAR (50)    NOT NULL,
    [WF_ID]                VARCHAR (50)    NOT NULL,
    [WF_STAGE]             NVARCHAR (50)   NULL,
    [FINISHED]             BIT             NULL,
    [STARTED_BY]           VARCHAR (50)    NULL,
    [START_DATE]           DATETIME        NULL,
    [DENIAL_REASON]        NVARCHAR (4000) NULL,
    [DENIAL_ATTACHMENT]    NVARCHAR (50)   NULL,
    [STATUS_ON_COMPLETION] NVARCHAR (50)   NULL,
    [ALL_REVS]             CHAR (1)        NULL,
    [MODBY]                NVARCHAR (50)   NULL,
    [DRCM]                 DATETIME        NULL,
    [FINISHED_DATE]        DATETIME        NULL,
    CONSTRAINT [PK_A_WORKFLOWSSTARTED] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_WORKFLOWSSTARTED_A_PEOPLE] FOREIGN KEY ([STARTED_BY]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_WORKFLOWSSTARTED_A_WF_STAGES] FOREIGN KEY ([WF_STAGE]) REFERENCES [dbo].[A_WF_STAGES] ([ID]),
    CONSTRAINT [FK_A_WORKFLOWSSTARTED_A_WORKFLOWS] FOREIGN KEY ([WF_ID]) REFERENCES [dbo].[A_WORKFLOWS] ([ID])
);


GO
ALTER TABLE [dbo].[A_WORKFLOWS_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOWSSTARTED_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_WORKFLOWS_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOWSSTARTED_A_WF_STAGES];


GO
ALTER TABLE [dbo].[A_WORKFLOWS_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOWSSTARTED_A_WORKFLOWS];

