CREATE TABLE [dbo].[A_WORKFLOWS] (
    [ID]         VARCHAR (50)  NOT NULL,
    [NAME]       VARCHAR (500) NULL,
    [HIDE]       BIT           NULL,
    [DRCM]       DATETIME      NULL,
    [MODBY]      VARCHAR (50)  NULL,
    [OBJECT_ID]  VARCHAR (50)  NULL,
    [STAMP_NAME] VARCHAR (500) NULL,
    [STAMP_ID]   VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_WORKFLOWS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE TRIGGER A_WORKFLOWS_INSERT
ON dbo.A_WORKFLOWS
AFTER INSERT
AS
declare @ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT @ID = ID,
	@MODBY = MODBY,
	@NAME = NAME FROM INSERTED
exec A_SP_OBJECT_ADD 'A_WORKFLOWS',@ID,@NAME,@MODBY,null,null,null

GO
CREATE   TRIGGER A_WORKFLOWS_UPDATE
ON dbo.A_WORKFLOWS
AFTER UPDATE
AS
declare @OBJ_ID as nvarchar(50)
declare @NAME as nvarchar(50)
declare @MODBY as nvarchar(50)
SELECT  @OBJ_ID = OBJECT_ID,@NAME = NAME,@MODBY = MODBY FROM INSERTED
UPDATE A_OBJECTS SET
OBJ_DESC = @NAME,
MODBY = @MODBY,
DRCM = getDATE()
WHERE ID = @OBJ_ID
