CREATE TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] (
    [ID]           NVARCHAR (50) NOT NULL,
    [WFS_ID]       VARCHAR (50)  NOT NULL,
    [WF_STAGE_ID]  NVARCHAR (50) NOT NULL,
    [WF_GROUP_ID]  NVARCHAR (50) NOT NULL,
    [APPROVED]     BIT           NULL,
    [APPROVER]     VARCHAR (50)  NULL,
    [DENIER]       VARCHAR (50)  NULL,
    [APPROVE_DATE] NVARCHAR (50) NULL,
    [HELD_BY]      VARCHAR (50)  NULL,
    [HOLD_DATE]    DATETIME      NULL,
    [FINISHED]     BIT           NULL,
    [DRCM]         DATETIME      NULL,
    [MODBY]        NVARCHAR (50) NULL,
    [DATE_STARTED] DATETIME      NULL,
    CONSTRAINT [PK_A_WORKFLOW_GROUP_STARTED] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_PEOPLE] FOREIGN KEY ([APPROVER]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_PEOPLE1] FOREIGN KEY ([DENIER]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_PEOPLE2] FOREIGN KEY ([HELD_BY]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_WF_GROUPS] FOREIGN KEY ([WF_GROUP_ID]) REFERENCES [dbo].[A_WF_GROUPS] ([ID]),
    CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_WF_STAGES] FOREIGN KEY ([WF_STAGE_ID]) REFERENCES [dbo].[A_WF_STAGES] ([ID]),
    CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_WORKFLOWSSTARTED] FOREIGN KEY ([WFS_ID]) REFERENCES [dbo].[A_WORKFLOWS_STARTED] ([ID])
);


GO
ALTER TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_PEOPLE1];


GO
ALTER TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_PEOPLE2];


GO
ALTER TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_WF_GROUPS];


GO
ALTER TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_WF_STAGES];


GO
ALTER TABLE [dbo].[A_WORKFLOW_GROUP_STARTED] NOCHECK CONSTRAINT [FK_A_WORKFLOW_GROUP_STARTED_A_WORKFLOWSSTARTED];

