CREATE TABLE [dbo].[A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL] (
    [ID]        VARCHAR (50) NOT NULL,
    [EMAIL_ID]  VARCHAR (50) NOT NULL,
    [PERSON_ID] VARCHAR (50) NOT NULL,
    [PAGE]      TINYINT      CONSTRAINT [DF_A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL_PAGE] DEFAULT ((0)) NOT NULL,
    [MODBY]     VARCHAR (50) NULL,
    [DRCM]      DATETIME     NULL,
    CONSTRAINT [PK_A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL_A_PEOPLE] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[A_PEOPLE] ([ID]),
    CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL_A_Z_EMAILS_TO_SEND] FOREIGN KEY ([EMAIL_ID]) REFERENCES [dbo].[A_Z_EMAILS_TO_SEND] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL] NOCHECK CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL_A_PEOPLE];


GO
ALTER TABLE [dbo].[A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL] NOCHECK CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL_A_Z_EMAILS_TO_SEND];

