CREATE TABLE [dbo].[A_Z_EMAILS_TO_SEND] (
    [ID]            VARCHAR (50) NOT NULL,
    [STATUS]        VARCHAR (50) NOT NULL,
    [DRCM]          DATETIME     NULL,
    [MODBY]         VARCHAR (50) NULL,
    [HIGH_PRIORITY] TINYINT      CONSTRAINT [DF_A_Z_EMAILS_TO_SEND_HIGH_PRIORITY] DEFAULT ((0)) NULL,
    [ALL_ADDIES]    TINYINT      CONSTRAINT [DF_A_Z_EMAILS_TO_SEND_ALL_ADDIES] DEFAULT ((0)) NULL,
    [ADDY]          VARCHAR (50) CONSTRAINT [DF_A_Z_EMAILS_TO_SEND_ADDY] DEFAULT ('SYS_EMAIL-1') NULL,
    CONSTRAINT [PK_A_Z_EMAILS_TO_SEND] PRIMARY KEY CLUSTERED ([ID] ASC)
);

