CREATE TABLE [dbo].[A_Z_DROP_DOWN_POPULATOR] (
    [ID]         VARCHAR (50)   NOT NULL,
    [USER_ID]    VARCHAR (50)   NOT NULL,
    [POP_UP_KEY] VARCHAR (50)   NULL,
    [SHOW]       NVARCHAR (200) NULL,
    [VAL]        VARCHAR (50)   NULL,
    [DRCM]       DATETIME       NULL,
    CONSTRAINT [PK_A_Z_DROP_DOWN_POPULATOR] PRIMARY KEY CLUSTERED ([ID] ASC)
);

