CREATE TABLE [dbo].[A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL] (
    [ID]       VARCHAR (50) NOT NULL,
    [EMAIL_ID] VARCHAR (50) NOT NULL,
    [ROLE_ID]  VARCHAR (50) NOT NULL,
    [DRCM]     DATETIME     NULL,
    [MODBY]    VARCHAR (50) NULL,
    [PAGE]     TINYINT      CONSTRAINT [DF_A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL_PAGE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL_A_ROLES] FOREIGN KEY ([ROLE_ID]) REFERENCES [dbo].[A_ROLES] ([ID]),
    CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL_A_Z_EMAILS_TO_SEND] FOREIGN KEY ([EMAIL_ID]) REFERENCES [dbo].[A_Z_EMAILS_TO_SEND] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL] NOCHECK CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL_A_ROLES];


GO
ALTER TABLE [dbo].[A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL] NOCHECK CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL_A_Z_EMAILS_TO_SEND];

