CREATE TABLE [dbo].[A_Z_ORDER_ITEMS_BILL_TYPES] (
    [ID]          VARCHAR (10)  NOT NULL,
    [DESCRIPTION] VARCHAR (299) NULL,
    [DRCM]        DATETIME      NULL,
    [MODBY]       VARCHAR (50)  NULL,
    CONSTRAINT [PK_A_Z_ORDER_ITEMS_BILL_TYPES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

