CREATE TABLE [dbo].[A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO] (
    [ID]            VARCHAR (50)  NOT NULL,
    [EMAIL_ID]      VARCHAR (50)  NOT NULL,
    [EMAIL_ADDRESS] VARCHAR (500) NOT NULL,
    [EMAIL_TYPE]    VARCHAR (50)  CONSTRAINT [DF_A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO_EMAIL_TYPE] DEFAULT ('TEXT') NULL,
    CONSTRAINT [PK_A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO_A_Z_EMAILS_TO_SEND] FOREIGN KEY ([EMAIL_ID]) REFERENCES [dbo].[A_Z_EMAILS_TO_SEND] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO] NOCHECK CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO_A_Z_EMAILS_TO_SEND];

