CREATE TABLE [dbo].[A_Z_EMAILS_TO_SEND_TEXT] (
    [ID]       VARCHAR (50)    NOT NULL,
    [EMAIL_ID] VARCHAR (50)    NOT NULL,
    [CNT]      INT             NOT NULL,
    [TXT_TYPE] VARCHAR (10)    NOT NULL,
    [TXT]      NVARCHAR (4000) NULL,
    [DRCM]     DATETIME        NULL,
    [MODBY]    VARCHAR (50)    NULL,
    CONSTRAINT [PK_A_Z_EMAILS_TO_SEND_TEXT] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_TEXT_A_Z_EMAILS_TO_SEND] FOREIGN KEY ([EMAIL_ID]) REFERENCES [dbo].[A_Z_EMAILS_TO_SEND] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);


GO
ALTER TABLE [dbo].[A_Z_EMAILS_TO_SEND_TEXT] NOCHECK CONSTRAINT [FK_A_Z_EMAILS_TO_SEND_TEXT_A_Z_EMAILS_TO_SEND];

