CREATE TABLE [dbo].[Portal_CustomerRequirement] (
    [Id]                              NVARCHAR (50)   NOT NULL,
    [RequirementName]                 NVARCHAR (200)  NOT NULL,
    [Location]                        NVARCHAR (50)   NULL,
    [Respresentative]                 NVARCHAR (50)   NOT NULL,
    [Company]                         NVARCHAR (50)   NULL,
    [DivisionFab]                     NVARCHAR (50)   NULL,
    [StreetAddress]                   NVARCHAR (100)  NULL,
    [CityStateZIP]                    NVARCHAR (50)   NULL,
    [CommercialName]                  NVARCHAR (50)   NOT NULL,
    [CommercialTitle]                 NVARCHAR (50)   NULL,
    [CommercialPhone]                 NVARCHAR (50)   NOT NULL,
    [CommercialEmail]                 NVARCHAR (50)   NULL,
    [TechnicalName]                   NVARCHAR (50)   NULL,
    [TechnicalTitle]                  NVARCHAR (50)   NULL,
    [TechnicalPhone]                  NVARCHAR (50)   NULL,
    [TechnicalEmail]                  NVARCHAR (50)   NULL,
    [ShortDescription]                NVARCHAR (100)  NOT NULL,
    [PartKitNo]                       NVARCHAR (50)   NULL,
    [CustomerSpecifications]          NVARCHAR (1000) NULL,
    [InProcessAnalyticalRequirements] NVARCHAR (1000) NULL,
    [DetailedDescription]             NVARCHAR (1000) NULL,
    [CriticalToFunction]              NVARCHAR (1000) NULL,
    [SpecificCustomerQualification]   NVARCHAR (1000) NULL,
    [ForecastedVolumes]               NVARCHAR (1000) NULL,
    [SpecialPackagingShipping]        NVARCHAR (1000) NULL,
    [ExpectedQuoteDate]               DATETIME        NULL,
    [ExpectedCycleTime]               NVARCHAR (50)   NULL,
    [PickupNotification]              NVARCHAR (100)  NULL,
    [ShippingMethod]                  NVARCHAR (50)   NULL,
    [AdditionalInformation]           NVARCHAR (2000) NULL,
    [SubmittedDate]                   DATETIME        NOT NULL,
    [Status]                          NVARCHAR (50)   NOT NULL,
    [SubmittedBy]                     NVARCHAR (50)   NOT NULL,
    CONSTRAINT [PK_Portal_CustomerRequirement] PRIMARY KEY CLUSTERED ([Id] ASC)
);

