CREATE TABLE [dbo].[WF_LOG] (
    [ID]   INT            IDENTITY (1, 1) NOT NULL,
    [TEXT] VARCHAR (6000) NULL,
    [DRCM] DATETIME       CONSTRAINT [DF_WF_LOG_DRCM] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_WF_LOG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

