version: 0.2

phases:
  build:
    commands:
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - sh ${SCRIPT_UPDATE_IMAGE_API} Production ${TAG} ${API_COMPOSE_PROCESSOR}
      - cat ${API_COMPOSE_PROCESSOR}
      - ecs-cli configure --cluster ${PROD_CLUSTER} --default-launch-type FARGATE --config-name ${CLUSTER_CONFIG} --region ${REGION}
      - ecs-cli compose --file ${API_COMPOSE_PROCESSOR} --project-name ${PROD_PROJECT_PROCESSOR} service up --create-log-groups --cluster-config ${CLUSTER_CONFIG} --timeout ${TIMEOUT}
