
CREATE VIEW [dbo].[Report_ActualPartHistory]

AS


SELECT DISTINCT
NewId() AS Id,
dbo.A_V_ACTUAL_PARTS_QUICK.SERIAL SN,
PART.COMPANYPARTNUMBER PN,
toi.PURCHASE_ITEM_ID WorkOrderNumber,
ISNULL(t.ACTUAL_STOP_DATE, purchItem.DUE_DATE) DateCompleted,
ROW_NUMBER() OVER (PARTITION BY A_V_ACTUAL_PARTS_QUICK.SERIAL,PART.COMPANYPARTNUMBER ORDER BY ISNULL(t.ACTUAL_STOP_DATE, purchItem.DUE_DATE))  CycleCount,
isnull(STUFF((    SELECT ',' + n.message
                        FROM [Portal_Note] n
						INNER JOIN AspNetUsers u ON u.Id = n.CreatedBy
                        WHERE n.EntityId=dbo.A_FILLS.ID
						ORDER BY n.CreatedDate DESC
                        FOR XML PATH('')), 1, 1, '' )
						,'') NCDisposition
FROM         dbo.A_V_COMPANIES_APPROVED_DATA_QUICK AS customer 
INNER JOIN dbo.A_V_PURCHASES_APPROVED_DATA AS purch ON customer.ID = purch.CUSTOMER_CO 
RIGHT OUTER JOIN dbo.A_TASK_COMPLETION_STATS 
RIGHT OUTER JOIN dbo.A_TASK_OBJECT_LINK AS T_OBJ 
INNER JOIN dbo.A_V_PROCEDURES_DATA_QUICK AS [PROC] 
INNER JOIN dbo.A_TASK_ORDER_INFORMATION AS toi
INNER JOIN dbo.A_TASKS AS t ON toi.TASK_ID = t.ID ON [PROC].ID = t.PROCEDURE_ID ON T_OBJ.TASK_ID = t.ID 
INNER JOIN dbo.A_FILLS ON toi.FILL_ITEM_ID = dbo.A_FILLS.ID 
INNER JOIN dbo.A_V_PRODUCTS_APPROVED_DATA AS Product 
INNER JOIN dbo.A_ORDER_ITEMS AS purchItem ON Product.ID = purchItem.PRODUCT_ID ON dbo.A_FILLS.PURCH_ITEM_ID = purchItem.ID ON dbo.A_TASK_COMPLETION_STATS.TASK_ID = t.ID 
LEFT OUTER JOIN dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK AS Account ON purchItem.ACCOUNT_ID = Account.ID ON purch.HISTORY_REF_ID = toi.PURCHASE_HIST_ID 
LEFT OUTER JOIN dbo.A_V_ACTUAL_PARTS_QUICK ON T_OBJ.OBJECT_ID = dbo.A_V_ACTUAL_PARTS_QUICK.ID
RIGHT JOIN dbo.A_V_COMPANIES_APPROVED_DATA_QUICK supp on supp.ID = Account.SUPPLIER_CO
INNER JOIN Portal_ActualPartsView AS PA ON PA.ID=dbo.A_V_ACTUAL_PARTS_QUICK.HISTORY_REF_ID
OUTER APPLY 
( 
SELECT top 1 p.CompanyPartNumber FROM Portal_PartsView p
WHERE p.ROOT = dbo.A_V_ACTUAL_PARTS_QUICK.PART_ID
) part
WHERE (t.STATUS IN ('REQUESTED', 'ACCEPTED', 'CLOSED', 'FINISHED')) AND (toi.PURCHASE_ITEM_ID IS NOT NULL) AND (dbo.A_V_ACTUAL_PARTS_QUICK.SERIAL IS NOT NULL)