CREATE PROCEDURE dbo.A_PRODUCT_POP_FILL_APP_OBJECTS
@ID  varchar(50),
@strNTLogin varchar(50)
AS
SELECT o.OBJ_DESC as APP_OBJ_NAME,o.ID as APP_OBJECT
FROM A_OBJECTS o,A_PRODUCT_OBJ_USED_ON_LINK l
WHERE l.PRODUCT_ID = @ID AND
l.OBJECT_ID = o.ID
