CREATE PROCEDURE dbo.A_SP_PROD_PRICE_LIST_GET_CUSTOMER_EXCEPTION_LIST  
@ID varchar(50),
@strNTLogin varchar(50)
AS
SELECT c.NAME AS NAME, c.ID AS ID 
FROM A_PROD_PRICE_LIST_EXCEPTIONS l,A_V_COMPANIES_APPROVED_DATA c
WHERE l.PP_LIST_ID = @ID AND l.CUST_ID = c.ID


