

CREATE   PROCEDURE dbo.A_SP_PROCEDURE_STEP_UPDATE_RECURRENCE
@newID nvarchar(50) OUTPUT,
@messages nvarchar(2000) OUTPUT,
@ID varchar(50),
@STEP_ID varchar(50),
@RECUR_TYPE varchar(50),
@NEXT_STEP varchar(50),
@DELAY_TYPE varchar(50),
@DELAY_UNIT varchar(50),
@DELAY_COUNTER varchar(50),
@DELAY_VALUE float,
@TIMES_TO_REPEAT float,
@SCHED_NUM int,
@strNTLogin varchar(50)
AS
print 'Updating a Steps Recurrence'

if @ID is null
	set @ID = newID()
else
	DELETE FROM A_PROCEDURE_STEP_RECURRENCE WHERE STEP_ID = @STEP_ID

INSERT INTO A_PROCEDURE_STEP_RECURRENCE
	(ID,STEP_ID,RECUR_TYPE,NEXT_STEP,
	DELAY_TYPE,DELAY_UNIT,DELAY_COUNTER,
	DELAY_VALUE,TIMES_TO_REPEAT,DRCM,MODBY,SCHED_NUM)
VALUES
	(@ID,@STEP_ID,@RECUR_TYPE,@NEXT_STEP,
	@DELAY_TYPE,@DELAY_UNIT,@DELAY_COUNTER,
	@DELAY_VALUE,@TIMES_TO_REPEAT,getdate(),@strNTLogin,@SCHED_NUM)

set @newID = @ID






