CREATE PROCEDURE [dbo].[A_SP_MONITOR_TEMPLATES_UPDATE_TEMPLATE]
@newID nvarchar(50) OUTPUT,
@messages nvarchar(2000) OUTPUT,
@ID nvarchar(50),
@MONITOR_TYPE  nvarchar(50),
@Input_type  nvarchar(50),
@LIST_SOURCE VARCHAR(50),
@DESCRIPTION nvarchar(2000),
@START_SYSTEM_TASK nvarchar(50),
@START_TYPE nvarchar(50),
@STOP_SYSTEM_TASK nvarchar(50),
@STOP_TYPE nvarchar(50),
@COUNTER_OR_CLOCK nvarchar(50),
@CLOCK_UNIT nvarchar(50),
@HIGHEST_THRESHOLD nvarchar(50),
@HIGH_THRESHOLD nvarchar(50),
@TARGET nvarchar(50),
@LOW_THRESHOLD nvarchar(50),
@LOWEST_THRESHOLD nvarchar(50),
@SHOULD_BE nvarchar(50),
@OPINION nvarchar(50),
@HIDE_TARGET nvarchar(50),
@USE_RESULT nvarchar(50),
@FAIL_STOP nvarchar(50),
@STEP_ID nvarchar(50),
@CORRECT_ANSWER varchar(50),
@TEXT_TARGET nvarchar(50),
@TASK_ID varchar(50),
@TOLERANCE varchar(50),
@RELATED_OBJECT_ID nvarchar(50),
@FAIL_ACTION varchar(50),
@TARGET_OBJECT_TYPE varchar(50),
@TARGET_OBJECT varchar(50),
@SKIP_MODE varchar(50),
@CANT_CHANGE tinyint,
@ALWAYS_PASS tinyint,
@strNTLogin nvarchar(50),
@SendNcrNotificationEmail Bit
AS
print 'Updating a monitor'
if @ID is null
	begin
		exec sp_GetUniqueID3 @newID OUTPUT
		INSERT INTO A_MONITOR_TEMPLATES (ID,ROLL_UP_ID,CREATED_BY) VALUES (@newID,@newID,@strNTLogin)
	end
else
	begin
		set @newID = @ID
	end
print 'Text Target = ' + @TEXT_TARGET
--Add the link for Procedures
declare @PROCEDURE_ID as nvarchar(50)
SELECT @PROCEDURE_ID = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @RELATED_OBJECT_ID
--Add the link for People
declare @PEOPLE_ID as nvarchar(50)
SELECT @PEOPLE_ID = ID FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @RELATED_OBJECT_ID
--Add the link for Parts
declare @PART_ID as nvarchar(50)
SELECT @PART_ID = ID FROM A_PARTS_HISTORY WHERE OBJECT_ID = @RELATED_OBJECT_ID

declare @relObjType varchar(100),@relObjDesc varchar(1000)
SELECT @relObjType = OBJ_TABLE,@relObjDesc = OBJ_DESC FROM A_OBJECTS WHERE ID = @RELATED_OBJECT_ID

--Update the monitor with the actual data we are looking at
UPDATE A_MONITOR_TEMPLATES SET
RELATED_OBJECT_TYPE = @relObjType,
RELATED_OBJECT_DESCRIPTION = @relObjDesc,
MONITOR_TYPE = @MONITOR_TYPE,
Input_Type = @Input_Type,
LIST_SOURCE = @LIST_SOURCE,
[DESCRIPTION] = @DESCRIPTION,
START_SYSTEM_TASK = @START_SYSTEM_TASK,
START_TYPE = @START_TYPE ,
STOP_SYSTEM_TASK = @STOP_SYSTEM_TASK,
STOP_TYPE = @STOP_TYPE,
COUNTER_OR_CLOCK = @COUNTER_OR_CLOCK,
CLOCK_UNIT = @CLOCK_UNIT,
HIGHEST_THRESHOLD = @HIGHEST_THRESHOLD,
HIGH_THRESHOLD = @HIGH_THRESHOLD,
[TARGET] = @TARGET,
LOW_THRESHOLD = @LOW_THRESHOLD,
LOWEST_THRESHOLD = @LOWEST_THRESHOLD,
SHOULD_BE = @SHOULD_BE,
OPINION = @OPINION,
HIDE_TARGET = @HIDE_TARGET,
USE_RESULT = @USE_RESULT,
FAIL_STOP = @FAIL_STOP,
STEP_ID = @STEP_ID,
RELATED_OBJECT_ID = @RELATED_OBJECT_ID,
PROCEDURE_ID = @PROCEDURE_ID,
PEOPLE_ID = @PEOPLE_ID,
PART_ID = @PART_ID,
DRCM = GETDATE(),
YES_NO_ANSWER = @CORRECT_ANSWER,
TEXT_TARGET = isNull(@TEXT_TARGET,''),
TASK_ID = @TASK_ID,
TOLERANCE = @TOLERANCE,
FAIL_ACTION = @FAIL_ACTION,
TARGET_OBJECT_TYPE = @TARGET_OBJECT_TYPE,
TARGET_OBJECT = @TARGET_OBJECT,
SKIP_MODE = @SKIP_MODE,
CANT_CHANGE = @CANT_CHANGE,
ALWAYS_PASS = @ALWAYS_PASS,
MODBY = @strNTLogin
WHERE ID = @newID

print 'Set Text_Target = ' + @TEXT_TARGET + ' Where ID = ' + @newID





















