




CREATE    PROCEDURE A_SP_ROLES_GET_MY_ROLES_WITHOUT_MY_PRIMARY_ROLE
@myID nvarchar(50),
@strNTLogin nvarchar(50)
as
declare @myPrimaryRole as nvarchar(50)
exec A_SP_GET_PRIMARY_POSITION_BY_NT_LOGIN 87,@myPrimaryRole OUTPUT

SELECT distinct 
ROLE_ID,ROLE,PERSON,STATUS,ROLE_NAME
FROM A_APPROVED_ROLE_ASSIGNEES ra 
WHERE PERSON = @myID 
AND ROLE_ID <> @myPrimaryRole


