
CREATE      PROCEDURE dbo.A_SP_TASK_COPY_TASK_FOR_BATCH_SPLIT
@newID varchar(50) OUTPUT,
@taskID varchar(50),
@newParentID varchar(50),
@strNTLogin varchar(50)
AS
exec sp_GetUniqueID3 @newID OUTPUT
INSERT INTO A_TASKS 
([ID], [PARENT_ID], [DESCRIPTION], [STATUS], [COMMENT], [REQUESTOR], [COMPLETED_BY], [MODBY], [DRCM], 
[CHILD_ORDER], [CREATED_BY], [CREATE_DATE], [CLOSED], [OPENED_BY], [OPEN_DATE], [SYSTEM_TASK], [PROCEDURE_ID], 
[PROCEDURE_STEP_ID], [SECURITY_LEVEL], [COUNTER], [REQUESTEE_ID], [GROUP_REQUESTEE_ID], [COUNTER_NAME], 
[COUNTER_VALUE], [ORIG_PLANNED_START_DATE], [ORIG_PLANNED_STOP_DATE], [CUR_PLANNED_START_DATE], 
[CUR_PLANNED_STOP_DATE], [ACTUAL_START_DATE], [ACTUAL_STOP_DATE], [ORIG_PLANNED_COUNTER_START], 
[ORIG_PLANNED_COUNTER_STOP], [CUR_PLANNED_COUNTER_START], [CUR_PLANNED_COUNTER_STOP], [ACTUAL_COUNTER_START], 
[ACTUAL_COUNTER_STOP], [LATEST_REQUESTEE_NAME], [HAS_DISCUSSION], [HAS_SURVEY], [HAS_CHILD], [HAS_REF_PROC], 
[HAS_FILE], [ORIG_REQUESTOR_ID], [HAS_REF_OBJ], [HAS_MONITOR], [COLOR_CODE], [LAST_REQUEST_DATE], [PRIORITY], 
[CHILD_STATUS], [IS_QUOTE], [IS_QUOTE_ACCEPT], [IS_FILL], [MANAGER], [DNR_TYPE], [RECURSION_NUMBER], 
[REPEAT_FROM_STEP])
SELECT
	@newID, @newParentID, [DESCRIPTION], [STATUS], [COMMENT], [REQUESTOR], [COMPLETED_BY], [MODBY], [DRCM], 
[CHILD_ORDER], [CREATED_BY], [CREATE_DATE], [CLOSED], [OPENED_BY], [OPEN_DATE], [SYSTEM_TASK], [PROCEDURE_ID], 
[PROCEDURE_STEP_ID], [SECURITY_LEVEL], [COUNTER], [REQUESTEE_ID], [GROUP_REQUESTEE_ID], [COUNTER_NAME], 
[COUNTER_VALUE], [ORIG_PLANNED_START_DATE], [ORIG_PLANNED_STOP_DATE], [CUR_PLANNED_START_DATE], 
[CUR_PLANNED_STOP_DATE], [ACTUAL_START_DATE], [ACTUAL_STOP_DATE], [ORIG_PLANNED_COUNTER_START], 
[ORIG_PLANNED_COUNTER_STOP], [CUR_PLANNED_COUNTER_START], [CUR_PLANNED_COUNTER_STOP], [ACTUAL_COUNTER_START], 
[ACTUAL_COUNTER_STOP], [LATEST_REQUESTEE_NAME], [HAS_DISCUSSION], [HAS_SURVEY], [HAS_CHILD], [HAS_REF_PROC], 
[HAS_FILE], [ORIG_REQUESTOR_ID], [HAS_REF_OBJ], [HAS_MONITOR], [COLOR_CODE], [LAST_REQUEST_DATE], [PRIORITY], 
[CHILD_STATUS], [IS_QUOTE], [IS_QUOTE_ACCEPT], [IS_FILL], [MANAGER], [DNR_TYPE], [RECURSION_NUMBER], 
[REPEAT_FROM_STEP]
FROM A_TASKS 
WHERE ID = @taskID

print 'Added that task now I need to copy all the related data to the new task = ' + @newID
print 'Adding the task Dates'
INSERT INTO A_TASK_DATES ([ID], [DATE_TYPE], [THE_DATE], [DRCM], [MODBY], [TASK_ID], [IS_CURRENT])
SELECT newID(), [DATE_TYPE], [THE_DATE], [DRCM], [MODBY], @newID, [IS_CURRENT] FROM A_TASK_DATES WHERE TASK_ID = @taskID
print 'Adding customer Links'
INSERT INTO A_TASK_CUSTOMER_LINK (ID,TASK_ID,CUSTOMER_ID,DRCM,MODBY)
	SELECT newID(),@newID,CUSTOMER_ID,getDate(),@strNTLogin FROM A_TASK_CUSTOMER_LINK WHERE TASK_ID = @taskID
print 'Adding Task Counters'
INSERT INTO A_TASK_COUNTERS (ID,COUNTER_TYPE,VAL,TASK_ID,IS_CURRENT,DRCM,MODBY)
	SELECT newID(),COUNTER_TYPE,VAL,@newID,IS_CURRENT,getDate(),@strNTLogin FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID
print 'Adding Companies to view'
INSERT INTO A_TASK_COMPANIES_TO_VIEW_LINK (ID,TASK_ID,CO_ID,DRCM,MODBY)
	SELECT newID(),@newID,CO_ID,getDate(),@strNTLogin FROM A_TASK_COMPANIES_TO_VIEW_LINK WHERE TASK_ID = @taskID
print 'Adding Ref Procs'
INSERT INTO A_TASK_REFERENCE_PROCEDURES (ID,TASK_ID,REF_PROCEDURE,DRCM,MODBY)
	SELECT newID(),@newID,REF_PROCEDURE,getDate(),@strNTLogin FROM A_TASK_REFERENCE_PROCEDURES WHERE TASK_ID = @taskID
print 'Adding Task Email People Link'
INSERT INTO A_TASK_EMAIL_PEOPLE_LINK (ID,TASK_ID,PERSON_ID,DRCM,MODBY)
	SELECT newID(),@newID,PERSON_ID,getDate(),@strNTLogin FROM A_TASK_EMAIL_PEOPLE_LINK WHERE TASK_ID = @taskID
print 'Adding Task Meeting Link'
INSERT INTO A_TASK_MEETING_LINK (ID,TASK_ID,MEETING_ID,DRCM,MODBY)
	SELECT newID(),@newID,MEETING_ID,getDate(),@strNTLogin FROM A_TASK_MEETING_LINK WHERE TASK_ID = @taskID
print 'Adding Task SURVEY Link'
INSERT INTO A_TASK_SURVEY_LINK (ID,TASK_ID,SURVEY_ID,DRCM,MODBY)
	SELECT newID(),@newID,SURVEY_ID,getDate(),@strNTLogin FROM A_TASK_SURVEY_LINK WHERE TASK_ID = @taskID
print 'Adding Task DISCUSSION Link'
INSERT INTO A_TASK_DISCUSSION_LINK (ID,TASK_ID,DISCUSSION_ID,DRCM,MODBY)
	SELECT newID(),@newID,DISCUSSION_ID,getDate(),@strNTLogin FROM A_TASK_DISCUSSION_LINK WHERE TASK_ID = @taskID
print 'Adding Task Ref Filesk'
INSERT INTO A_TASK_REF_FILES (ID,TASK_ID,FILE_ID,DRCM,MODBY)
	SELECT newID(),@newID,FILE_ID,getDate(),@strNTLogin FROM A_TASK_REF_FILES WHERE TASK_ID = @taskID
print 'Adding Task CC People'
INSERT INTO A_TASK_CC_PEOPLE (ID,TASK_ID,PERSON_ID,DRCM,MODBY)
	SELECT newID(),@newID,PERSON_ID,getDate(),@strNTLogin FROM A_TASK_CC_PEOPLE WHERE TASK_ID = @taskID
print 'Copying all the business purposes and objects and projects as well'
exec A_SP_PROJECT_COPY_ONE_ITEMS_PROJ_OBJ_PURP_TAGS @taskID,'A_TASKS',@newID,'A_TASKS',@strNTLogin
print 'Copying all the Comments as well'
INSERT INTO A_TASK_COMMENT (ID,TASK_ID,DATE_CREATED,COMMENT,WRITER,WRITER_COMPANY,ALLOWED_TO_VIEW,DRCM,MODBY)
SELECT newID(),@newID,DATE_CREATED,COMMENT,WRITER,WRITER_COMPANY,ALLOWED_TO_VIEW,DRCM,MODBY FROM A_TASK_COMMENT
	WHERE TASK_ID = @taskID
declare @curs as cursor,@monID as varchar(50),@newMonID varchar(50)
set @curs = CURSOR FOR SELECT ID FROM A_TASK_MONITORS WHERE TASK_ID = @taskID
open @curs
fetch next from @curs into @monID
while @@fetch_status = 0
	begin
	exec A_SP_MONITOR_COPY @newMonID OUTPUT,@monID,0,@strNTLogin
	INSERT INTO A_MONITOR_RESULTS
		([ID], [MONITOR_TEMPLATE_ID], [NUM_VAL], 
		[TEXT_VAL], [MULT_CHOICE_ANSWER], [DRCM], 
		[MODBY], [PRINT_RESULT], [COMMENT])
	SELECT newID(), @newMonID, [NUM_VAL], [TEXT_VAL], [MULT_CHOICE_ANSWER], 
		[DRCM], [MODBY], [PRINT_RESULT], [COMMENT]
		FROM A_MONITOR_RESULTS WHERE ID = @monID
	
	INSERT INTO A_TASK_MONITORS ([ID], [TASK_ID], [MONITOR_TEMPLATE_ID], [RESULT], 
		[DATE_RECORDED], [COMMENT], [MODBY], [DRCM], [DESCRIPTION], [START_TASK], 
		[STOP_TASK], [START_TYPE], [STOP_TYPE], [UNITS], [CREATE_DATE], [CREATED_BY], 
		[AUTO], [IS_SYSTEM], [TARGET_TEXT], [RESULT_TEXT])
	SELECT newID(),@newID,@newMonID,[RESULT], 
		[DATE_RECORDED], [COMMENT], [MODBY], [DRCM], [DESCRIPTION], [START_TASK], 
		[STOP_TASK], [START_TYPE], [STOP_TYPE], [UNITS], [CREATE_DATE], [CREATED_BY], 
		[AUTO], [IS_SYSTEM], [TARGET_TEXT], [RESULT_TEXT] FROM A_TASK_MONITORS WHERE
		TASK_ID = @taskID and MONITOR_TEMPLATE_ID = @monID



	end













