


CREATE   PROCEDURE A_SP_PROD_PRICE_LIST_GET_VOL_DISCOUNTS_BY_OBJ_ID
@OBJ_ID varchar(50) OUTPUT,
@strNTLogin varchar(50)

AS
declare @myID as varchar(50)
SELECT @myID = ID FROM A_PROD_PRICE_LIST_HISTORY WHERE OBJECT_ID = @OBJ_ID
print 'My ID = ' + @myID
SELECT * FROM A_PROD_PRICE_LIST_VOLUME_DISC WHERE PRICE_LIST_ID = @myID




