


CREATE    PROCEDURE dbo.A_SP_ORDERS_GET_ITEMS_DATA
@orderObjID varchar(50),
@strNTLogin varchar(50)
AS
declare @ordID as varchar(50)
SELECT @ordID = ID FROM A_ORDERS_HISTORY WHERE OBJECT_ID = @orderObjID
SELECT * FROM A_V_ORDER_ITEMS_ALL_DATA WHERE ORDER_ID = @ordID
ORDER BY PARENT_LIST,PROC_NAME



