
CREATE          PROCEDURE A_SP_MONITOR_COPY
@newID nvarchar(50) OUTPUT,
@oldID nvarchar(50),
@propogateRollUp tinyInt,
@strNTLogin nvarchar(50)
AS
exec sp_GetUniqueID3 @newID OUTPUT

INSERT INTO A_MONITOR_TEMPLATES([ID], [MONITOR_TYPE], [DESCRIPTION], [START_SYSTEM_TASK],
 [START_TYPE], [STOP_SYSTEM_TASK], [STOP_TYPE], [COUNTER_OR_CLOCK],
 [CLOCK_UNIT], [HIGHEST_THRESHOLD], [HIGH_THRESHOLD], [TARGET], [LOW_THRESHOLD],
 [LOWEST_THRESHOLD], [SHOULD_BE], [OPINION], [DRCM], [MODBY], [RELATED_OBJECT_TYPE],
 [RELATED_OBJECT_DESCRIPTION], [TARGET_ANSWER_ID], [HIDE_TARGET], [PROCEDURE_ID],
 [STEP_ID], [PEOPLE_ID], [PART_ID], [USE_RESULT], [FAIL_STOP], [YES_NO_ANSWER],
 [CORRECT_ANSWER_ID],[ROLL_UP_ID],[TOLERANCE],FAIL_ACTION,TARGET_OBJECT_TYPE,TARGET_OBJECT,
 PRINT_ORDER,SKIP_MODE,CANT_CHANGE,ALWAYS_PASS,Input_type,Text_Target

)
SELECT @newID, [MONITOR_TYPE], [DESCRIPTION], [START_SYSTEM_TASK],
 [START_TYPE], [STOP_SYSTEM_TASK], [STOP_TYPE], [COUNTER_OR_CLOCK],
 [CLOCK_UNIT], [HIGHEST_THRESHOLD], [HIGH_THRESHOLD], [TARGET], [LOW_THRESHOLD],
 [LOWEST_THRESHOLD], [SHOULD_BE], [OPINION], getDate(), @strNTLogin, [RELATED_OBJECT_TYPE],
 [RELATED_OBJECT_DESCRIPTION], [TARGET_ANSWER_ID], [HIDE_TARGET], [PROCEDURE_ID],
 [STEP_ID], [PEOPLE_ID], [PART_ID], [USE_RESULT], [FAIL_STOP], [YES_NO_ANSWER],
 [CORRECT_ANSWER_ID],[ROLL_UP_ID],[TOLERANCE],FAIL_ACTION,TARGET_OBJECT_TYPE,TARGET_OBJECT,
  PRINT_ORDER,SKIP_MODE,CANT_CHANGE,ALWAYS_PASS,Input_type,Text_Target
FROM A_MONITOR_TEMPLATES WHERE ID = @oldID

INSERT INTO A_MONITOR_TEMPLATES_MULT_CHOICE([ID], [MONITOR_ID], [TXT], 
[IS_ANSWER], [ORD], [USE_PUT_TEXT], [DRCM], [MODBY], ROOT_ID)
SELECT newID(), @newID, [TXT], [IS_ANSWER], [ORD], [USE_PUT_TEXT], getDate(), @strNTLogin, ROOT_ID
FROM A_MONITOR_TEMPLATES_MULT_CHOICE WHERE MONITOR_ID = @oldID

INSERT INTO A_MONITOR_SKIP_STEPS (ID,MONITOR_ID,STEP_ID,DRCM,MODBY)
SELECT newID(),@newID,STEP_ID,getDate(),@strNTLogin FROM A_MONITOR_SKIP_STEPS WHERE MONITOR_ID = @oldID

if @propogateRollUp <> 1 or @propogateRollUp is null
	begin
	UPDATE A_MONITOR_TEMPLATES SET ROLL_UP_ID = NULL
	end















