CREATE PROCEDURE dbo.A_SP_PURCHASE_ITEM_DELETE
@purchItemID varchar(50),
@strNTLogin varchar(50)
AS
create TABLE #myTasks (ID VARCHAR(50))
INSERT INTO #myTasks SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WHERE PURCHASE_ITEM_ID = @purchItemID
INSERT INTO #myTasks SELECT ID FROM A_TASKS WHERE PARENT_ID IN (SELECT ID FROM #myTasks)
DELETE FROM A_MONITOR_RESULTS 
	WHERE MONITOR_TEMPLATE_ID IN 
		(SELECT ID FROM A_MONITOR_TEMPLATES WHERE TASK_ID IN (SELECT ID FROM #myTasks))
DELETE FROM A_MONITOR_TEMPLATES 
	WHERE TASK_ID IN (SELECT ID FROM #myTasks)
DELETE FROM A_TASKS
	WHERE ID IN (SELECT ID FROM #myTasks)
DELETE FROM A_TASK_ORDER_INFORMATION 
	WHERE TASK_ID IN (SELECT ID FROM #myTasks) or 
		FILL_ITEM_ID IN (SELECT ID FROM A_FILLS WHERE PURCH_ITEM_ID = @purchItemID) or
		FILL_ID IN (SELECT ID FROM A_FILLS WHERE PURCH_ITEM_ID = @purchItemID)

DELETE FROM A_FILLS WHERE PURCH_ITEM_ID = @purchItemID
DELETE FROM A_ORDER_ITEMS WHERE PARENT = @purchItemID
DELETE FROM A_ORDER_ITEMS WHERE ID = @purchItemID




