




CREATE      procedure A_SP_ACCOUNTS_COPY_ONE
	@newObjID nvarchar(50) OUTPUT,
	@strID nvarchar(50),
	@strNTLogin nvarchar(50),
	@copyPrefix nvarchar(50)
as
--Make a new ID for the copy
declare @newID as nvarchar(50)
exec sp_getUniqueID3 @newID OUTPUT
--Insert the new one

INSERT INTO A_ACCOUNTS_HISTORY 
([ID], [NAME], [REFERENCE_PO], [REFERENCE_NAME], [OPEN_DATE], 
[CLOSE_DATE], [SUPPLIER_CO], [CUSTOMER_CO], [CUSTOMER_BILL_CO], 
[MAXIMUM_USES], [TOTAL_PURCHASE_LIMIT], [CREDIT_LIMIT], [APPROVAL_WF], 
[INVOICE_TRIGGER], [INVOICE_PERIOD_NUMBER], [INVOICE_PERIOD_TYPE], 
[FIRST_INVOICE_DATE], [NEXT_INVOICE_DATE], [PAYMENT_GRACE_PERIOD], 
[LATE_FEE_PERCENTAGE], [REAPPLY_LATE_FEE], [DRCM], [MODBY], 
[ACCT_TYPE], [TOTAL_PURCHASES], [BALANCE], [AMT_INVOICED], [ACCT_STATUS])
SELECT 
@newID as ID, @copyPrefix + [NAME], 
[REFERENCE_PO], [REFERENCE_NAME], [OPEN_DATE], 
[CLOSE_DATE], [SUPPLIER_CO], [CUSTOMER_CO], [CUSTOMER_BILL_CO], 
[MAXIMUM_USES], [TOTAL_PURCHASE_LIMIT], [CREDIT_LIMIT], [APPROVAL_WF], 
[INVOICE_TRIGGER], [INVOICE_PERIOD_NUMBER], [INVOICE_PERIOD_TYPE], 
[FIRST_INVOICE_DATE], [NEXT_INVOICE_DATE], [PAYMENT_GRACE_PERIOD], 
[LATE_FEE_PERCENTAGE], [REAPPLY_LATE_FEE], getDate(), @strNTLogin, 
[ACCT_TYPE], [TOTAL_PURCHASES], [BALANCE], [AMT_INVOICED], [ACCT_STATUS]
FROM A_ACCOUNTS_HISTORY WHERE ID = @strID

--find out what object id the new one got
SELECT @newObjID = OBJECT_ID FROM A_ACCOUNTS_HISTORY WHERE ID = @newID
print 'The new object ID is ' + @newObjID

print 'Copy all the applicable objects too'
INSERT INTO A_ACCOUNTS_RELATED_OBJECTS (ID,ACCOUNT_ID,OBJ_ID,DRCM,MODBY)
SELECT newID(),@newID,OBJ_ID,DRCM,MODBY FROM A_ACCOUNTS_RELATED_OBJECTS WHERE ACCOUNT_ID = @strID

print 'Copy all product Exceptions'
INSERT INTO A_ACCOUNT_PRODUCT_EXCEPTIONS (ID,ACCT_ID,PRODUCT_ID,EX_TYPE,DRCM,MODBY)
SELECT newID(),@newID,PRODUCT_ID,EX_TYPE,DRCM,MODBY FROM A_ACCOUNT_PRODUCT_EXCEPTIONS WHERE ACCT_ID = @strID

print 'Copy all part Exceptions'
INSERT INTO A_ACCOUNTS_PART_EXCEPTIONS (ID,ACCT_ID,PART_ID,EX_TYPE,DRCM,MODBY)
SELECT newID(),@newID,PART_ID,EX_TYPE,DRCM,MODBY FROM A_ACCOUNTS_PART_EXCEPTIONS WHERE ACCT_ID = @strID

declare @objID varchar(50)
SELECT  @objID = OBJECT_ID FROM A_ACCOUNTS_HISTORY WHERE ID = @strID
INSERT INTO A_ACCOUNT_PURCHASABLE_ORDERS_LINK (ID,ACCOUNT_ID,ORDER_ID,DRCM,MODBY)
SELECT newID(),@newObjID,ORDER_ID,DRCM,MODBY FROM A_ACCOUNT_PURCHASABLE_ORDERS_LINK WHERE ACCOUNT_ID = @objID



