


CREATE  PROCEDURE A_SP_FORECAST_GET_SUB_FORECASTS
@ID varchar(50),
@strNTLogin varchar(50)
AS
SELECT c.NAME as NAME,c.ID AS ID FROM A_FORECAST_ROLL_UP r,A_V_FORECASTS_APPROVED_DATA c WHERE
c.ID = r.CHILD AND r.PARENT = @ID



