/*
STORED PROCEDURE CALLED IN serviceCAll/rejectServiceCall.asp
*/



CREATE PROCEDURE A_SP_SERVICE_CALL_DELETE_SERVICE_CALL 
@weeklyID nvarchar(50),
@strNTLogin nvarchar(50)
AS
DELETE FROM A_SERVICE_CALLS_WEEKLY_REPORTS WHERE 
ID = @weeklyID
