CREATE PROCEDURE DBO.A_SP_PROCEDURE_STEP_ADD_NEW_APPLICABLE_OBJECT
@newID varchar(50) OUTPUT,
@msg varchar(500) OUTPUT,
@stepID varchar(50),
@strNTLogin varchar(50)
AS
if @stepID is null goto fin
declare @procID varchar(50)
SELECT @procID = PROCEDURE_ID FROM A_PROCEDURE_STEPS WHERE ID = @stepID
exec sp_GetUniqueID3 @newID OUTPUT
INSERT INTO A_PROCEDURE_OBJECT_LINK (ID,PROCEDURE_ID,STEP_ID,RELATIONSHIP)
	VALUES(@newID,@procID,@stepID,'STEP_APPLICABLE_OBJECT')



fin:

