



CREATE        PROCEDURE A_SP_ROLES_GET_MY_ROLES
@myID nvarchar(50),
@strNTLogin nvarchar(50)
as
create table #myRoles
	(ROLE_ID varchar(50),ROLE varchar(50),PERSON varchar(50),STATUS varchar(50),ROLE_NAME varchar(1000))

INSERT INTO #myRoles (ROLE_ID,ROLE,PERSON,STATUS,ROLE_NAME)
	SELECT distinct 
	ROLE_ID,ROLE,PERSON,STATUS,ROLE_NAME
	FROM A_APPROVED_ROLE_ASSIGNEES WHERE PERSON = @myID

 INSERT INTO #myRoles (ROLE_ID,ROLE,PERSON,STATUS,ROLE_NAME)
 	SELECT distinct 
 	CO_POSITION,CO_POSITION,ID,'ACTIVE',CO_POSITION
 	FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @myID


declare @cnt int
set @cnt = 0
while exists(
			SELECT ROLE_ID FROM A_APPROVED_ROLE_ASSIGNEES 
				WHERE ROLE_ASSIGNED IN (SELECT ROLE_ID FROM #myRoles)
				AND ROLE_ID NOT IN (SELECT ROLE_ID FROM #myRoles)
			)
		AND @cnt < 30
	begin
	INSERT INTO #myRoles (ROLE_ID,ROLE,PERSON,STATUS,ROLE_NAME)
	SELECT distinct ROLE_ID,ROLE,@strNTLogin,STATUS,ROLE_NAME
	FROM A_APPROVED_ROLE_ASSIGNEES 
				WHERE ROLE_ASSIGNED IN (SELECT ROLE_ID FROM #myRoles)
				AND ROLE_ID NOT IN (SELECT ROLE_ID FROM #myRoles)
	set @cnt = @cnt + 1
	end

DELETE FROM A_PERSON_ROLES WHERE PERSON_ID = @myID
INSERT INTO A_PERSON_ROLES (ID,PERSON_ID,ROLE_ID,DRCM,MODBY)
	SELECT newID(),@myID,ROLE_ID,getDate(),@strNTLogin FROM #myRoles WHERE ROLE_ID IS NOT NULL

SELECT * FROM #myRoles



