
CREATE  Procedure dbo.A_SP_PROCEDURE_STEP_ADD_PREPOP_STEP
@newStepID varchar(50) OUTPUT,
@messages varchar(2000) OUTPUT,
@procObjID varchar(50),
@prevStepID varchar(50),
@prePopID varchar(50),
@strNTLogin varchar(50)
as
declare @prePopStepID varchar(50),@procID varchar(50)
SELECT @procID = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @procObjID
print 'adding a new step to procedure ' + @procObjID
SELECT @prePopStepID = STEP_ID FROM A_V_PREPOP_QUICK WHERE ID = @prePopID
print 'prepop =  ' + @prePopStepID
exec A_SP_PROCEDURE_STEP_COPY
 	@newStepID OUTPUT,@prePopStepID,null,@procID,@strNTLogin
if @prevStepID is null
	SELECT top 1 @prevStepID = ID FROM A_PROCEDURE_STEPS WHERE ID <> @newStepID AND PROCEDURE_ID = @procID ORDER BY PRINT_ORDER DESC
if @prevStepID is not null
	begin
	INSERT INTO A_PROCEDURE_STEP_PRECEDING_STEPS (ID,MY_STEP,PREV_STEP,DRCM,MODBY,PROCEDURE_ID)
		VALUES (newID(),@newStepID,@prevStepID,getDate(),@strNTLogin,@procID)
	if not exists (SELECT * FROM A_PROCEDURE_OBJECT_LINK WHERE PROCEDURE_ID = @procID and STEP_ID = @newStepID and LABOR_ROLE = 'LABOR_OWNER')
		INSERT INTO A_PROCEDURE_OBJECT_LINK (ID,PROCEDURE_ID,STEP_ID,APPROVED_OBJECT_ID,QTY,QTY_TYPE,RELATIONSHIP,DRCM,MODBY,LABOR_ROLE,COPIED_FROM)
		SELECT newID(),PROCEDURE_ID,@newStepID,APPROVED_OBJECT_ID,QTY,QTY_TYPE,RELATIONSHIP,DRCM,MODBY,LABOR_ROLE,STEP_ID FROM
			A_PROCEDURE_OBJECT_LINK WHERE STEP_ID = @prevStepID
	end







