
/*
STORED PROCEDURE CALLED IN discussion/emailDiscussions.asp
*/
CREATE    PROCEDURE A_SP_DISCUSSION_EMAIL_GET_INVITED_PEOPLE
@discussionID varchar(50),
@strNTLogin varchar(50)
AS
print 'Create the temp table'
CREATE TABLE #T (
ID varchar (50)
)

print 'insert the People invited'
INSERT INTO #T SELECT PEOPLE_ID FROM A_DISCUSSION_INV_PEOPLE WHERE DISCUSSION_ID = @discussionID
print 'insert the People invited through their roles'
INSERT INTO #T SELECT PERSON FROM A_V_ROLES_APPROVED_WITH_PEOPLE_IDS 
	WHERE ROLE_ID IN (SELECT ROLE_ID FROM A_DISCUSSION_INV_ROLE WHERE DISCUSSION_ID = @discussionID)
print 'insert the People invited through their companies'
INSERT INTO #T SELECT ID FROM A_V_PEOPLE_APPROVED_DATA 
	WHERE COMPANY IN (SELECT COMPANY_ID FROM A_DISCUSSION_REALLY_INIVTED_COMPANY WHERE DISCUSSION_ID = @discussionID)

SELECT DISTINCT ID FROM #T WHERE ID IS NOT NULL

