






CREATE PROCEDURE dbo.A_SP_COMPANY_HOLIDAYS_UPDATE_HOLIDAY
@HOLIDAY_ID nvarchar(50),
@HOLIDAY_DESCRIPTION nvarchar(2000),
@HOLIDAY_DATE dateTime,
@strNTLogin nvarchar(50)
AS
UPDATE A_COMPANY_HOLIDAYS 
SET DESCRIPTION = @HOLIDAY_DESCRIPTION,
YR = YEAR(@HOLIDAY_DATE),
MO = MONTH(@HOLIDAY_DATE),
DA = DAY(@HOLIDAY_DATE),
DRCM = getDate(),
MODBY = @strNTLogin
WHERE ID = @HOLIDAY_ID






