

CREATE PROCEDURE dbo.A_SP_ACCOUNT_UPDATE_GENERAL_ACCOUNT_DATA
@acctID varchar(50),
@strNTLogin varchar(50)
AS
declare @totCharges money,@totPayments money
SELECT @totCharges = SUM(isNull(AMOUNT,0)) 
	FROM A_ACCOUNT_INVOICE_ITEMS
	WHERE 
		ITEM_TYPE = 'INV_ITEM_DEBIT' 
		AND
		INVOICE_ID IN (SELECT ID FROM A_ACCOUNT_INVOICES WHERE ACCOUNT_ID = @acctID)
SELECT @totPayments = SUM(isNull(AMOUNT,0)) 
	FROM A_ACCOUNT_INVOICE_ITEMS
	WHERE 
		ITEM_TYPE = 'INV_ITEM_PAYMENT' 
		AND
		INVOICE_ID IN (SELECT ID FROM A_ACCOUNT_INVOICES WHERE ACCOUNT_ID = @acctID)

UPDATE A_ACCOUNTS_HISTORY 
	SET 
		TOTAL_PURCHASES = @totCharges,
		BALANCE = isNull(@totCharges,0) + isNull(@totPayments,0)
WHERE OBJECT_ID IN (SELECT ID FROM A_OBJECTS WHERE ROOT = @acctID)







