
CREATE  PROCEDURE dbo.A_SP_DNR_FIND_ACTIONS_FROM_SIMILAR_CASES
@ID varchar(50)
AS

CREATE TABLE #procsToIgnore(ROLL_UP_ID VARCHAR(50))
CREATE TABLE #tempMatchCases(ID VARCHAR(50))
CREATE TABLE #matchCases(ID VARCHAR(50),DROPPED_TESTS int,DROPPED_TEST_ID varchar(50))


declare @procCurs as cursor,@rid varchar(50),@droppedTests int
set @droppedTests = 0
set @procCurs = 
	CURSOR FOR 
		SELECT ROLL_UP_ID
			FROM
			A_V_DNR_TASKS_WITH_TEST_INFO
			WHERE
			DNR_ID = @ID AND IS_PASSING = 0
			ORDER BY ACTUAL_STOP_DATE DESC

open @procCurs
fetch next from @procCurs into @rid
while (@@fetch_status = 0)
	Begin
	set @droppedTests = @droppedTests + 1
	INSERT INTO #procsToIgnore (ROLL_UP_ID) values(@rid)
	INSERT INTO #tempMatchCases exec A_SP_DNR_PERMUTATION_FIND_MATCHING_CASES_PART_2 @ID
	INSERT INTO #matchCases SELECT ID,@droppedTests,@rid FROM #tempMatchCases t 
		WHERE NOT EXISTS (SELECT ID FROM #matchCases WHERE ID = t.ID)
	if dbo.MD() = 1
		begin
		SELECT 'procsToIgnore',i.ROLL_UP_ID,m.DESCRIPTION FROM #procsToIgnore i,A_MONITOR_TEMPLATES m
			WHERE m.ID = i.ROLL_UP_ID
		SELECT 'tempMAtching Cases',* FROM #tempMatchCases
		SELECT 'matching Cases',* FROM #matchCases
		end

	DELETE FROM #tempMatchCases
	fetch next from @procCurs into @rid
	end





create TABLE #CASES (ID varchar(50),DROPPED_TESTS int,DROPPED_TEST_ID varchar(50))
INSERT INTO #CASES SELECT DISTINCT ID,DROPPED_TESTS,DROPPED_TEST_ID FROM #matchCases ORDER BY DROPPED_TESTS

--Corrective Actions will hold all the corrective actions from the DNR's that match
CREATE TABLE #CORRECTIVE_ACTIONS (PARENT_ID varchar(50),TASK_ID varchar(50),
	P_ID varchar(50),PROC_HiST_ID varchar(50),
	PROC_NAME varchar(3000),DNR_STAT varchar(50),
	DROPPED_TEST_ID varchar(50),DROPPED_TEST_NAME varchar(1000),NUM_DROPPED_TESTS int)

-- INSERT INTO #CORRECTIVE_ACTIONS
-- 	SELECT PARENT_TASK_ID,TASK_ID,PROCEDURE_ID,PROC_HIST_ID,PROC_NAME,DNR_STATUS,
-- 	
-- 	FROM
-- 	A_V_DNR_TASKS_WITH_CORRECTIVE_ACTIONS_INFO
-- 	WHERE
-- 	PARENT_TASK_ID IN (SELECT ID FROM #CASES)

print 'Inserting now'
INSERT INTO #CORRECTIVE_ACTIONS
	(PARENT_ID,TASK_ID,P_ID,PROC_HiST_ID,PROC_NAME,DNR_STAT,
		DROPPED_TEST_ID,
		DROPPED_TEST_NAME,
		NUM_DROPPED_TESTS

)
	SELECT DISTINCT 
		t.PARENT_TASK_ID,t.TASK_ID,t.PROCEDURE_ID,t.PROC_HIST_ID,t.PROC_NAME,DNR_STATUS,
		c.DROPPED_TEST_ID,
		m.DESCRIPTION,
		c.DROPPED_TESTS

	FROM A_V_DNR_TASKS_WITH_CORRECTIVE_ACTIONS_INFO t,#CASES c,A_MONITOR_TEMPLATES m
	WHERE 
--	t.IS_PASSING = 0 AND 
	t.PARENT_TASK_ID = c.ID AND
	m.ID = c.DROPPED_TEST_ID --and
--	TASK_ID IN (SELECT ID FROM A_TASKS WHERE PARENT_ID IN (SELECT ID FROM #CASES)) AND
--	t.ROLL_UP_ID not in (SELECT ROLL_UP_ID FROM A_V_DNR_TASKS_WITH_TEST_INFO WHERE PARENT_TASK_ID = @ID)

declare @totActions int
SELECT @totActions = count(TASK_ID) FROM #CORRECTIVE_ACTIONS



CREATE TABLE #DISTINCT_COR_ACTIONS 
	(PROC_ID varchar(50),PROC_HiST_ID varchar(50),PROC_NAME varchar(3000),
	NUM_FIXED int,NUM_FAILED int,PERCENTAGE float,
	DROPPED_TEST_ID varchar(50),DROPPED_TEST_NAME varchar(1000),NUM_DROPPED_TESTS int)

INSERT INTO #DISTINCT_COR_ACTIONS
	(PROC_ID,PROC_HiST_ID,PROC_NAME,DROPPED_TEST_ID,DROPPED_TEST_NAME,NUM_DROPPED_TESTS)
	 SELECT
		P_ID,PROC_HiST_ID,PROC_NAME,DROPPED_TEST_ID,DROPPED_TEST_NAME,NUM_DROPPED_TESTS
		FROM #CORRECTIVE_ACTIONS
		GROUP BY P_ID,PROC_HiST_ID,PROC_NAME,DROPPED_TEST_ID,DROPPED_TEST_NAME,NUM_DROPPED_TESTS

DELETE FROM #DISTINCT_COR_ACTIONS WHERE PROC_ID 
	IN (SELECT PROCEDURE_ID FROM A_V_DNR_TASKS_WITH_CORRECTIVE_ACTIONS_INFO WHERE PARENT_TASK_ID = @ID)

UPDATE #DISTINCT_COR_ACTIONS SET 
	NUM_FIXED = 
	(SELECT COUNT(TASK_ID) FROM #CORRECTIVE_ACTIONS
	WHERE P_ID = #DISTINCT_COR_ACTIONS.PROC_ID AND DNR_STAT = 'GOOD_REPAIR'),
	NUM_FAILED = 
	(SELECT COUNT(TASK_ID) FROM #CORRECTIVE_ACTIONS
	WHERE P_ID = #DISTINCT_COR_ACTIONS.PROC_ID AND DNR_STAT <> 'GOOD_REPAIR')

UPDATE #DISTINCT_COR_ACTIONS SET PERCENTAGE = convert(float,NUM_FIXED) / convert(float,@totActions)


SELECT * FROM #DISTINCT_COR_ACTIONS ORDER BY NUM_DROPPED_TESTS,NUM_FIXED DESC





