CREATE PROCEDURE A_SP_COMPANY_GET_HEAD_PEOPLE_LIST
@coID varchar(50),
@strNTLogin as varchar(50)
AS
SELECT p.ID AS P_ID,p.FULL_NAME AS P_NAME FROM A_COMPANY_HEAD_PEOPLE h,A_V_PEOPLE_APPROVED_DATA p
WHERE h.CO_ID = @coID AND h.PERSON_ID = p.ID
