



CREATE    PROCEDURE A_SP_DD_SYSTEM_TASKS
@strNTLogin nvarchar(50)
AS
declare @myCo varchar(50)
SELECT @myCo = ROOT_COMPANY FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @strNTLogin
SELECT * FROM A_V_PROCEDURES_APPROVED_DATA WHERE IS_SYSTEM = 1 and CREATING_CO = @myCo ORDER BY NAME


