

CREATE PROCEDURE [dbo].[A_SP_FILL_GET_MONITORS_FOR_NCR] 
@fillID varchar(50),
@strNTLogin varchar(50)
AS
BEGIN
declare @taskID varchar(50)
SELECT @taskID = TASK_ID FROM A_TASK_ORDER_INFORMATION with (noLock) WHERE FILL_ITEM_ID = @fillID
SELECT TASK_ID AS STEPPER_ID,* FROM A_V_MONITORS_WITH_TASK_AND_RESULT WHERE TASK_ID IN (SELECT CHILD_ID FROM A_TASKS_RELATION_TABLE WHERE PARENT_ID = @taskID)
END
