
CREATE PROCEDURE dbo.A_SP_ACCOUNT_INVOICES_MARK_AS_INVOICED
@newID varchar(50) OUTPUT,
@msgs varchar(2000) OUTPUT,
@ACCOUNT_ID varchar(50),
@INVOICE_ID varchar(50),
@DATE_INVOICED datetime,
@DUE_DATE datetime,
@strNTLogin varchar(50)
AS
UPDATE A_ACCOUNT_INVOICES SET STATUS = 'INVOICED',
INVOICE_DATE = @DATE_INVOICED,
DUE_DATE = @DUE_DATE
WHERE ID = @INVOICE_ID
exec A_SP_ACCOUNT_FIGURE_TOTALS @ACCOUNT_ID,@strNTLogin

