






CREATE   PROCEDURE dbo.A_SP_PEOPLE_CHECK_PASSWORD
@ID as nvarchar(50),
@PASSWORD as nvarchar(50),
@PASSWORD_NON_ENCRYPT as nvarchar(50)
as
if Exists(SELECT ID FROM A_ADMIN_CONFIGURATION WHERE NAME = 'ALL_PASS' AND VAL = @PASSWORD_NON_ENCRYPT)
		begin
		print 'All PAss'
		SELECT ID,NAME,LAST_NAME,LOGIN 
		FROM A_APPROVED_PEOPLE 
		WHERE SYSTEM_STATUS = 'ACTIVE' AND ID = @ID
		end
	else
		begin
		SELECT ID,NAME,LAST_NAME,LOGIN 
		FROM A_APPROVED_PEOPLE 
		WHERE SYSTEM_STATUS = 'ACTIVE' AND ID = @ID and PASSWORD = @PASSWORD
		end






