
CREATE       PROCEDURE dbo.A_SP_ADMIN_SERVICE_CALL_ACCT_RECEIVABLE_ROLE_UPDATE
@coID nvarchar(50),
@role varchar(50),
@location varchar(50),
@strNTLogin varchar(50)
AS
DELETE FROM A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE WHERE COMPANY_ID  = @coID
INSERT INTO A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE (ID,COMPANY_ID,RECIEVABLE_ROLE,PAYMENT_LOCATION,DRCM,MODBY)
VALUES (newID(),@coID,@role,@location,getDate(),@strNTLogin)

