
CREATE        PROCEDURE A_SP_MONITOR_TEMPLATES_GET_DATA_FOR_OBJECT
@RELATED_OBJECT_ID nvarchar(50),
@PROCEDURE_STEP_ID nvarchar(50),
@TASK_ID nvarchar(50),
@strNTLogin nvarchar(50)
AS

if @TASK_ID is not null
	begin
	SELECT * FROM A_V_MONITOR_TEMPLATES_WITH_RESULTS WHERE TASK_ID = @TASK_ID ORDER BY PRINT_ORDER
	goto fin
	end
if @RELATED_OBJECT_ID is not null
	begin
	if @TASK_ID is not null
		SELECT * FROM A_V_MONITOR_TEMPLATES_WITH_RESULTS WHERE TASK_ID = @TASK_ID ORDER BY PRINT_ORDER
	else
		if @PROCEDURE_STEP_ID IS NULL 
			SELECT * FROM A_V_MONITOR_TEMPLATES_WITH_RESULTS WHERE RELATED_OBJECT_ID = @RELATED_OBJECT_ID and STEP_ID is null ORDER BY PRINT_ORDER
		else
			SELECT * FROM A_V_MONITOR_TEMPLATES_WITH_RESULTS WHERE RELATED_OBJECT_ID = @RELATED_OBJECT_ID and STEP_ID = @PROCEDURE_STEP_ID ORDER BY PRINT_ORDER
	end
else
	if @PROCEDURE_STEP_ID IS not NULL 
		SELECT * FROM A_V_MONITOR_TEMPLATES_WITH_RESULTS WHERE STEP_ID = @PROCEDURE_STEP_ID   ORDER BY PRINT_ORDER



fin:












