CREATE PROCEDURE dbo.A_SP_DNR_GET_PARTS_ON_THIS_CALL
@taskID varchar(50)
AS
declare @callRootTaskID varchar(50)

exec A_SP_TASK_GET_CALL_ROOT_TASK_ID @callRootTaskID OUTPUT,@taskID
print @callRootTaskID

--SELECT * FROM A_TASKS WHERE ID = @callRootTaskID

SELECT l.REASON,
	p.NAME,
	p.QTY,
	t.ID,
	t.DESCRIPTION as TASK_ID,
	t.SYSTEM_TASK,
	p.AP_STATUS AS STATUS
	FROM  A_ACTUAL_PARTS_CALL_DATA l,
	A_V_ACTUAL_PARTS_APPROVED_DATA p, A_TASKS t
 WHERE ROOT_TASK in
(SELECT CHILD_ID FROM A_TASKS_RELATION_TABLE WHERE PARENT_ID = @callRootTaskID)
AND p.ID = l.ACTUAL_PART_ID AND t.ID = l.ROOT_TASK

--SELECT l.RELATIONSHIP,o.OBJ_DESC,t.SYSTEM_TASK FROM A_TASK_ACTION_OBJECT_LINK l,
--	A_V_APPROVED_OBJECTS o, A_TASKS t
--WHERE TASK_ID in
--(SELECT CHILD_ID FROM A_TASKS_RELATION_TABLE WHERE PARENT_ID = @callRootTaskID)
--AND o.ID = l.OBJECT_ID AND t.ID = l.TASK_ID



