




CREATE         procedure A_SP_ACTUAL_PARTS_COPY_ONE
	@newObjID nvarchar(50) OUTPUT,
	@strID nvarchar(50),
	@strNTLogin nvarchar(50),
	@copyPrefix nvarchar(50)
as
--Make a new ID for the copy
declare @newID as nvarchar(50)
exec sp_getUniqueID3 @newID OUTPUT
--Insert the new one
--INSERT INTO A_ACTUAL_PARTS_HISTORY ([ID], [LOCATION], [OBJECT_ID],[DRCM],[MODBY])
--SELECT @newID as ID, [LOCATION], [OBJECT_ID], getDate(), @strNTLogin
--FROM A_ACTUAL_PARTS_HISTORY WHERE ID = @strID
INSERT INTO A_ACTUAL_PARTS_HISTORY
([ID], [LOCATION], [OBJECT_ID], [DRCM], [MODBY], 
[NICK_NAME], [MERGABLE], [PARENT_ID], [PART_ID], 
[QTY], [SERIAL], [CUR_OWNER], [ASSEMBLY_WT], 
[AP_STATUS], [ROOT_ID], [ROOT_STATUS],[RESPONSIBLE_PERSON],[HAS_CHILD])
SELECT @newID, [LOCATION], [OBJECT_ID], getDate(), @strNTLogin,
[NICK_NAME], [MERGABLE], [PARENT_ID], [PART_ID], 
[QTY], [SERIAL], [CUR_OWNER], [ASSEMBLY_WT], 
[AP_STATUS], [ROOT_ID], [ROOT_STATUS],[RESPONSIBLE_PERSON],[HAS_CHILD] FROM
A_ACTUAL_PARTS_HISTORY WHERE ID = @strID

--find out what object id the new one got
SELECT @newObjID = OBJECT_ID FROM A_ACTUAL_PARTS_HISTORY WHERE ID = @newID
print 'The new object ID is ' + @newObjID

INSERT INTO A_ACTUAL_PART_PRODUCTS_INSIDE_LINK (ID,ACTUAL_PART_ID,PRODUCT_ID,DRCM,MODBY)
SELECT newID(),@newID,PRODUCT_ID,getDate(),@strNTLogin FROM A_ACTUAL_PART_PRODUCTS_INSIDE_LINK
	where ACTUAL_PART_ID = @strID








