




CREATE    PROCEDURE A_SP_DD_PROCEDURE_STEP_RELATED_PARTS
@poID nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @pid as nvarchar(50)
SELECT @pid = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @poID
SELECT APPROVED_OBJECT_ID AS ID,NAME AS NAME FROM A_V_PROCEDURE_PART_LINK WHERE PROCEDURE_ID = @pid



