

CREATE   PROCEDURE dbo.A_SP_PURCHASE_UPDATE_FILL_STATUS
@pID varchar(50),
@strNTLogin varchar(50)
AS
if (exists (SELECT * FROM A_V_PURCHASE_HISTORY_WITH_ITEMS_AND_FILLS WHERE FILL_OBJ_ID IS NULL AND PURCHASE_HIST_ID = @pID))
	UPDATE A_PURCHASES_HISTORY SET PURCHASE_STATUS = 'WAITING_FILLS' where ID = @pID
else
	UPDATE A_PURCHASES_HISTORY SET PURCHASE_STATUS = 'ALL_ITEMS_FILLED' where ID = @pID
	


