CREATE PROCEDURE dbo.A_SP_COMPANY_GET_AN_ADMIN_ID_FROM_THIS_COMPANY
@ID varchar(50) OUTPUT,
@coID varchar(50)
AS
declare @rootCo varchar(50)
SELECT @rootCo = ROOT_CO FROM A_V_COMPANIES_APPROVED_DATA WHERE ID = @coID


SELECT @ID = p.ID
	FROM A_V_ROLES_APPROVED_WITH_PEOPLE_IDS ra INNER JOIN
         A_V_PEOPLE_APPROVED_DATA p ON ra.PERSON = p.ID
	WHERE (ra.IS_ADMIN = 1) AND p.ROOT_COMPANY = @rootCo
