




CREATE   PROCEDURE dbo.A_SP_PURCHASE_ITEM_GET_COMBINABLE_PIS
@fillID varchar(50),
@strNTLogin varchar(50)
AS

declare @procID varchar(50),@custID varchar(50)
SELECT @procID = PROC_ID, @custID = CUST_ID FROM A_V_ENGINEER_SCREEN_DATA WHERE FILL_ITEM_ID = @fillID

SELECT DISTINCT 
NICK_NAME,SERIAL,PURCHASE_ID,PURCHASE_HIST_ID,PURCHASE_ITEM_ID,
CUSTOMER_NAME,DUE_DATE,ORIG_DUE_DATE,ACTUAL_PART_ID,ST_DATE,
PROC_ID,CUST_ID,START_DATE,REQUESTEE_ID,GROUP_REQUESTEE_ID,
PRODUCT_NAME,CUST_PURCH_NUM,REFERENCE_PO,PROC_NAME,QTY,STATUS,
FILL_ID,MT_NUM,ACTUAL_START_DATE,ACTUAL_STOP_DATE,
FILL_ITEM_ID,FILL_QTY,BATCHED
FROM
A_V_ENGINEER_SCREEN_DATA t with (noLock) 
WHERE 
BATCHED IS NULL AND
STATUS = 'REQUESTED' AND
CUST_ID = @custID AND
PROC_ID = @procID AND
(
GROUP_REQUESTEE_ID IN 
	(
	SELECT ROLE_ID FROM A_PERSON_ROLES with (noLock)  WHERE PERSON_ID = @strNTLogin
	)
OR 
REQUESTEE_ID = @strNTLogin 
OR
exists
	(
	SELECT ID FROM A_TASKS ts with (noLock)  WHERE ts.PARENT_ID = t.ID and  
	ts.GROUP_REQUESTEE_ID IN 
		(
		SELECT ROLE_ID FROM A_PERSON_ROLES with (noLock)  WHERE PERSON_ID = @strNTLogin
		) 
	OR
	ts.REQUESTEE_ID = @strNTLogin
	)
)





