



CREATE    PROCEDURE dbo.A_SP_PURCHASE_ITEM_PENCIL_WHIP
@fillID varchar(50),
@strNTLogin varchar(50)
AS
print 'Fill ID started as ' + @fillID
SELECT @fillID = isNull(BATCH_PARENT,ID) FROM A_FILLS WHERE ID = @fillID 
print 'FILLID is now ' + @fillID
declare @myStatus as varchar(2000)
set @myStatus = ''
create TABLE #myTasks (ID VARCHAR(50))
create TABLE #myTaskSteps (ID VARCHAR(50))
INSERT INTO #myTasks SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WHERE FILL_ITEM_ID = @fillID
INSERT INTO #myTasks SELECT o.TASK_ID 
	FROM A_FILLS f,A_TASK_ORDER_INFORMATION o 
	WHERE o.FILL_ITEM_ID = f.ID 
		AND 
		f.BATCH_PARENT = @fillID

INSERT INTO #myTaskSteps SELECT ID FROM A_TASKS WHERE PARENT_ID IN (SELECT ID FROM #myTasks)
DELETE FROM A_MONITOR_RESULTS 
	WHERE MONITOR_TEMPLATE_ID IN 
		(SELECT ID FROM A_MONITOR_TEMPLATES WHERE TASK_ID IN (SELECT ID FROM #myTasks))
DELETE FROM A_MONITOR_RESULTS 
	WHERE MONITOR_TEMPLATE_ID IN 
		(SELECT ID FROM A_MONITOR_TEMPLATES WHERE TASK_ID IN (SELECT ID FROM #myTaskSteps))
DELETE FROM A_MONITOR_TEMPLATES 
	WHERE TASK_ID IN (SELECT ID FROM #myTasks)
DELETE FROM A_MONITOR_TEMPLATES 
	WHERE TASK_ID IN (SELECT ID FROM #myTaskSteps)
UPDATE A_TASKS SET STATUS = 'CLOSED'
	WHERE ID IN (SELECT ID FROM #myTaskSteps)

declare @curs as CURSOR,@it varchar(50)
set @curs = CURSOR FOR SELECT ID FROM #myTasks
open @curs
declare @RET_STATUS as varchar(50)
fetch next from @curs into @it
while @@fetch_status = 0
	begin
	exec A_SP_TASK_FIGURE_OUT_CHILD_STATUS @it,@strntLogin
	exec A_SP_TASK_ASSUME_CONTROL @RET_STATUS OUTPUT,null,@it,@strNTLogin
	set @RET_STATUS = ''
	exec A_SP_TASK_QUICK_CLOSE @RET_STATUS OUTPUT,null,@it,@strNTLogin
	set @myStatus = @myStatus + isNull(@RET_STATUS,'')
	print @RET_STATUS
	fetch next from @curs into @it
	end

SELECT @myStatus as STATUS




