





CREATE       PROCEDURE dbo.A_SP_DNR_FIND_ACTIONS_FROM_MATCHING_CASE
@ID varchar(50)
AS

create TABLE #CASES (ID varchar(50))
INSERT INTO #CASES exec A_SP_DNR_FIND_MATCHING_CASES @ID
if dbo.MD() = 1 SELECT 'CASES',* FROM #CASES c,A_TASKS t WHERE t.ID = c.ID


--Corrective Actions will hold all the corrective actions from the DNR's that match
CREATE TABLE #CORRECTIVE_ACTIONS (PARENT_ID varchar(50),TASK_ID varchar(50),P_ID varchar(50),PROC_HiST_ID varchar(50),PROC_NAME varchar(3000),DNR_STAT varchar(50))

INSERT INTO #CORRECTIVE_ACTIONS
	SELECT PARENT_TASK_ID,TASK_ID,PROCEDURE_ID,PROC_HIST_ID,PROC_NAME,DNR_STATUS
	FROM
	A_V_DNR_TASKS_WITH_CORRECTIVE_ACTIONS_INFO
	WHERE
	PARENT_TASK_ID IN (SELECT ID FROM #CASES)
declare @totActions int
SELECT @totActions = count(TASK_ID) FROM #CORRECTIVE_ACTIONS

CREATE TABLE #DISTINCT_COR_ACTIONS 
	(PROC_ID varchar(50),PROC_HiST_ID varchar(50),PROC_NAME varchar(3000),NUM_FIXED int,NUM_FAILED int,PERCENTAGE float)
INSERT INTO #DISTINCT_COR_ACTIONS
	(PROC_ID,PROC_HiST_ID,PROC_NAME)
	 SELECT
		P_ID,PROC_HiST_ID,PROC_NAME
		FROM #CORRECTIVE_ACTIONS
		GROUP BY P_ID,PROC_HiST_ID,PROC_NAME

DELETE FROM #DISTINCT_COR_ACTIONS WHERE PROC_ID 
	IN (SELECT PROCEDURE_ID FROM A_V_DNR_TASKS_WITH_CORRECTIVE_ACTIONS_INFO WHERE PARENT_TASK_ID = @ID)

UPDATE #DISTINCT_COR_ACTIONS SET 
	NUM_FIXED = 
	(SELECT COUNT(TASK_ID) FROM #CORRECTIVE_ACTIONS
	WHERE P_ID = #DISTINCT_COR_ACTIONS.PROC_ID AND DNR_STAT = 'GOOD_REPAIR'),
	NUM_FAILED = 
	(SELECT COUNT(TASK_ID) FROM #CORRECTIVE_ACTIONS
	WHERE P_ID = #DISTINCT_COR_ACTIONS.PROC_ID AND DNR_STAT <> 'GOOD_REPAIR')

UPDATE #DISTINCT_COR_ACTIONS SET PERCENTAGE = convert(float,NUM_FIXED) / convert(float,@totActions)


SELECT * FROM #DISTINCT_COR_ACTIONS ORDER BY NUM_FIXED DESC



