CREATE  PROCEDURE A_SP_PEOPLE_SHOW_POSITION_BY_OBJECT_ID
@ID nvarchar(50),
@strNTLogin nvarchar(50)
as
SELECT POSITION_ID AS ROLE_ID,POSITION_NAME AS ROLE_NAME FROM A_PEOPLE_SEARCH_TABLE WHERE OBJ_ID = @ID
