


CREATE    PROCEDURE DBO.A_SP_ADMIN_GET_NEWS_PROCEDURE
@strNTLogin varchar(50)
AS
declare @myCO as nvarchar(50)
exec A_SP_GET_PERSON_COMPANY @strNTLogin,@myCO OUTPUT
SELECT a.*,p.NAME AS PROC_NAME,p.DRCM AS MOD_DATE
FROM A_ADMIN_PROCEDURES a,A_V_THEORY_APPROVED_DATA p
WHERE a.PROCEDURE_ID = p.ID AND a.PROC_TYPE = '1' and a.COMPANY = @myCO ORDER BY PRINT_ORDER



