/*

STORED PROCEDURE CALLED IN

- Stored Procedure: A_DESCRIPTION_SEARCH
*/

CREATE       PROCEDURE A_SP_GET_PRIMARY_POSITION_BY_NT_LOGIN
@strNTLogin nvarchar(50),
@myRole nvarchar(50) OUTPUT
as
SELECT @myRole = POSITION_ID FROM A_V_APPROVED_ROLES_WITH_NTLOGIN_ID WHERE 
PERSON = @strNTLogin 
