CREATE PROCEDURE [dbo].[A_SP_PROCEDURE_STEP_ACTUALLY_COPY]
@newID varchar(50) OUTPUT,
@oldStep varchar(50),
@oldProc varchar(50),
@newProc varchar(50),
@strNTLogin varchar(50)
AS
exec sp_getUniqueID3 @newID OUTPUT
print 'inserting a new step'
INSERT INTO A_PROCEDURE_STEPS([ID],[PROCEDURE_ID],[STEP_TEXT],[StepTitle],[START_ON_COUNTER],[COUNTER_VALUE],
[COUNTER_UNIT],[REL_OR_ABS],[FROM_START_OR_STOP],[SYSTEM_TASK],[DESTINATION],[SPECIFIC_LOCATION],
[REFERENCE_VERB],[REFERENCE_OBJECT],[COMMENTS],[GOTO_STEP],[GOTO_STEP_ID],[CYCLES],[CYCLE_ON_COUNTER],
[CYCLE_COUNT],[CYCLE_UNIT],[DRCM],[MODBY],[PRINT_ORDER],OLD_PROCEDURE_ID,OLD_STEP_ID,DURATION,DURATION_TYPE)
SELECT @newID,@newProc,[STEP_TEXT],[StepTitle],[START_ON_COUNTER],[COUNTER_VALUE],
[COUNTER_UNIT],[REL_OR_ABS],[FROM_START_OR_STOP],[SYSTEM_TASK],[DESTINATION],[SPECIFIC_LOCATION],
[REFERENCE_VERB],[REFERENCE_OBJECT],[COMMENTS],[GOTO_STEP],[GOTO_STEP_ID],[CYCLES],[CYCLE_ON_COUNTER],
[CYCLE_COUNT],[CYCLE_UNIT],getDate(),@strNTLogin,[PRINT_ORDER],@oldProc,@oldStep,DURATION,DURATION_TYPE
FROM A_PROCEDURE_STEPS WHERE ID = @oldStep
print 'Copying the Monitors for the step' + @oldStep
exec A_SP_PROCEDURE_COPY_MONITORS @oldProc,@oldStep,@newProc,@newID,@strNTLogin
print 'Copying the object Links'
exec A_SP_PROCEDURE_COPY_OBJECT_LINKS @oldProc,@oldStep,@newProc,@newID,@strNTLogin
print 'copying the file links'
INSERT INTO A_PROCEDURE_STEP_FILE_LINK (ID,STEP_ID,[FILE_ID],DRCM,MODBY)
SELECT newID(),@newID,[FILE_ID],getDate(),@strNTLogin FROM A_PROCEDURE_STEP_FILE_LINK WHERE STEP_ID = @oldStep
print 'Copying the Procedure Step Procedure Links'
INSERT INTO A_PROCEDURE_STEP_PROCEDURE_LINK (ID,PROCEDURE_STEP,PROCEDURE_LINK,DRCM,MODBY)
SELECT newID(),@newID,PROCEDURE_LINK,getDate(),@strNTLogin FROM A_PROCEDURE_STEP_PROCEDURE_LINK WHERE PROCEDURE_STEP = @oldStep
print 'Copying the Procedure Step Theory Links'
INSERT INTO A_PROCEDURE_STEP_THEORY_LINK (ID,PROC_STEP_ID,THEORY_ID,DRCM,MODBY)
SELECT newID(),@newID,THEORY_ID,getDate(),@strNTLogin FROM A_PROCEDURE_STEP_THEORY_LINK 
	WHERE PROC_STEP_ID = @oldStep

