



CREATE      PROCEDURE A_SP_PROJECT_GET_DATA_BY_ID
@projectID varchar(50),
@strNTLogin nvarchar(50)
AS

declare @myCo varchar(50)
SELECT @myCo = COMPANY 
FROM A_APPROVED_PEOPLE 
WHERE ID=@strNTLogin

print 'getting data from A_V_PROJECT_DATA '
SELECT * ,
CASE WHEN (@projectID IN (SELECT PROJECT_ID FROM A_PROJECT_ALLOWED_PEOPLE WHERE PROJECT_ID = @projectID AND PEOPLE_ID = @strNTlogin)
		  OR @projectID IN (SELECT PROJECT_ID FROM A_PROJECT_ALLOWED_COMPANIES WHERE PROJECT_ID = @projectID AND COMPANY_ID = @myCo  )
		  OR @projectID IN (SELECT PROJECT_ID FROM A_PROJECT_ALLOWED_ROLES WHERE PROJECT_ID = @projectID AND ROLE_ID IN (SELECT ROLE_ID FROM A_V_ROLES_APPROVED_WITH_PEOPLE_IDS WHERE PERSON = @strNTLogin ))) THEN '1'
			ELSE '0'
		  end isAllowedToView,
CASE WHEN (INITIATOR = @strNTlogin or LEADER= @strNTlogin or @projectID IN (SELECT PROJECT_ID FROM A_PROJECT_MEMBERS WHERE PROJECT_ID = @projectID AND PEOPLE_ID = @strNTlogin)
			OR @projectID IN (SELECT PROJECT_ID FROM A_PROJECT_SPONSORS WHERE PROJECT_ID = @projectID AND PEOPLE_ID = @strNTlogin)) THEN '1'
			ELSE '0'
		  end canSeeProject
FROM A_V_PROJECT_DATA
WHERE ID =@projectID




