










CREATE      PROCEDURE A_SP_FORECAST_GET_ITEMS
@F_OBJ_ID varchar(50),
@strNTLogin nvarchar(50)
AS
CREATE TABLE #myItems (
ID varchar(50),
ACCOUNT_ID varchar(50),
SUPPLIER_NAME nvarchar(200),
CUSTOMER_NAME nvarchar(200),
PRODUCT_NAME nvarchar(200),
QTY float,
F_AMT money,
AVG_MONTHLY money,
DATE_ADDED dateTime,
PROGRESS int,
ACCT_NAME nvarchar(200),
EST_QUAL_START_DATE datetime,
ACT_QUAL_START_DATE datetime,
EST_FIRST_PURCHASE_DATE datetime,
ACT_FIRST_PURCHASE_DATE datetime,
STATUS nvarchar(1000),
CONFIDENCE float,
PRIORITY int,
SUPPLIER_OWNER nvarchar(200),
CUSTOMER_OWNER nvarchar(200),
AMT_INVOICED money,
PARENT_F_ITEM varchar(50),
PARENT_NAME nvarchar(1000),
F_TYPE varchar(50)
)
declare @F_ID varchar(50)
SELECT @F_ID = OBJ_ID FROM A_OBJECTS WHERE ID = @F_OBJ_ID
print 'hist ID = ' + @F_ID
INSERT INTO #myItems
(ID,ACCOUNT_ID,QTY,F_AMT,AVG_MONTHLY,DATE_ADDED,EST_QUAL_START_DATE,F_TYPE,
ACT_QUAL_START_DATE,EST_FIRST_PURCHASE_DATE,ACT_FIRST_PURCHASE_DATE,PROGRESS,STATUS,
CONFIDENCE,PRIORITY,SUPPLIER_OWNER,CUSTOMER_OWNER,AMT_INVOICED)
SELECT 
ID,ACCOUNT_ID,QTY,F_AMT,AVG_MONTHLY,DATE_ADDED,EST_QUAL_START_DATE,F_TYPE,
ACT_QUAL_START_DATE,EST_FIRST_PURCHASE_DATE,ACT_FIRST_PURCHASE_DATE,PROGRESS,convert(nvarchar(1000),STATUS),
CONFIDENCE,PRIORITY,SUPPLIER_OWNER,CUSTOMER_OWNER,AMT_INVOICED
FROM A_FORECAST_ITEMS WHERE FORECAST_ID = @F_ID

Declare @ID varchar(50),@acctID varchar(50),@acctHistID varchar(50),
	@custID varchar(50),@supplierID varchar(50),@productID varchar(50)
Declare @curs Cursor
set @curs = Cursor For SELECT ID,ACCOUNT_ID FROM #myItems
open @curs
Fetch Next from @curs Into @ID,@acctID
while (@@fetch_status = 0)
Begin
	print 'lookind at item = ' + @ID
	SELECT @acctHistID = HISTORY_REF_ID FROM A_ACCOUNTS WHERE ID = @acctID
	SELECT @custID = CUSTOMER_CO,@supplierID = SUPPLIER_CO,
			@productID = PRODUCT_ID
			FROM A_ACCOUNTS_HISTORY WHERE ID = @acctHistID
	UPDATE #myItems 
	SET
	SUPPLIER_NAME = (SELECT NAME FROM A_V_COMPANIES_APPROVED_DATA WHERE ID = @supplierID),
	CUSTOMER_NAME = (SELECT NAME FROM A_V_COMPANIES_APPROVED_DATA WHERE ID = @custID),
	PRODUCT_NAME = (SELECT NAME FROM A_V_PRODUCTS_APPROVED_DATA WHERE ID = @productID),
	PARENT_NAME = (SELECT PARENT_ACCOUNT_NAME FROM A_V_FORECAST_ITEMS_WITH_PARENT_ITEM_NAM WHERE CHILD_ID = @ID)
	WHERE ID = @ID


	Fetch Next from @curs Into @ID,@acctID
End
close @curs
Deallocate @curs

SELECT * FROM #myItems ORDER BY PRIORITY,F_AMT DESC



--SELECT * FROM A_V_FORECAST_ITEMS_WITH_ACCOUNT_PARENTS WHERE F_OBJ_ID = @F_OBJ_ID
--ORDER BY PRIORITY,F_AMT DESC,ACCOUNT_NAME














