


CREATE      PROCEDURE A_SP_PROCEDURE_SHOW_MY_DEPARTMENT_DATA
	@strID nvarchar(50),
	@strNTLogin nvarchar(50)
as
declare @d as varchar(50)
SELECT @d = CREATING_DEPT FROM A_PROCEDURES_HISTORY WHERE ID = @strID

SELECT * FROM A_V_APPROVED_COMPANIES_WITH_LOGOS WHERE ID = @d




