

CREATE  PROCEDURE A_SP_FORECAST_ITEM_GET_DISTRIBUTIONS
@ID varchar(50),
@strNTLogin as varchar(50)
AS
SELECT *,convert(float,AMT) AS AMT_FLOAT FROM A_FORECAST_MONTHLY_BREAKDOWN WHERE FI_ID = @ID ORDER BY YR,MO


