





CREATE    PROCEDURE A_SP_ACTUAL_PARTS_SHOW_PRODUCTS_INSTALLED
	@ID varchar(50),
	@strNTLogin varchar(50)
AS
--find out my Company
declare @myCO as nvarchar(50)
exec A_SP_GET_PERSON_COMPANY @strNTLogin,@myCO OUTPUT

SELECT p.NAME,p.ID FROM A_V_PRODUCTS_APPROVED_DATA P, A_ACTUAL_PART_PRODUCTS_INSIDE_LINK L WHERE
L.PRODUCT_ID = P.ID AND L.ACTUAL_PART_ID = @ID









