

CREATE PROCEDURE A_SP_ACTUAL_PARTS_SHOW_ROOT_CHILD_FOR_OBJECT
@objID varchar(50),
@strNTLogin varchar(50)
AS
declare @RID as varchar(50)
SELECT @RID = ID FROM A_ACTUAL_PARTS_HISTORY WHERE OBJECT_ID = @objID
declare @RCID as varchar(50)
SELECT @RCID = ID FROM A_ACTUAL_PARTS_SUB_PARTS WHERE PARENT_ID is NULL and ROOT_ID = @RID
SELECT * FROM A_V_ACTUAL_PARTS_CHILD_TREE_VIEW WHERE ID = @RCID



