




CREATE      PROCEDURE dbo.A_SP_TASK_COPY_TASK
@newID varchar(50) OUTPUT,
@taskID varchar(50),
@newRequesteeID varchar(50),
@strNTLogin varchar(50)
AS
declare @messages nvarchar(2000),
 @PARENT_ID  varchar(50), @REQUESTOR varchar(50),
 @DESCRIPTION nvarchar(4000), @SYSTEM_TASK varchar(50),
 @COMMENT nvarchar(4000), @SECURITY_LEVEL varchar(50),
 @COUNTER varchar(50), @ORIG_PLANNED_START_DATE dateTime,
 @ORIG_PLANNED_STOP_DATE dateTime, @ORIG_PLANNED_COUNTER_START numeric,
 @ORIG_PLANNED_COUNTER_STOP numeric, @CUR_PLANNED_START_DATE dateTime,
 @CUR_PLANNED_STOP_DATE dateTime, @CUR_PLANNED_COUNTER_START numeric,
 @CUR_PLANNED_COUNTER_STOP numeric, @ACTUAL_START_DATE dateTime,
 @ACTUAL_STOP_DATE dateTime, @ACTUAL_COUNTER_START numeric,
 @ACTUAL_COUNTER_STOP numeric, @PRIORITY smallInt,
 @ADDITIONAL_ASSIGNEES varchar(50)

SELECT 
@PARENT_ID = PARENT_ID,
@REQUESTOR = REQUESTOR,
@DESCRIPTION = DESCRIPTION ,
@SYSTEM_TASK = SYSTEM_TASK,
@COMMENT = COMMENT,
@SECURITY_LEVEL = SECURITY_LEVEL ,
@COUNTER = COUNTER ,
@ORIG_PLANNED_START_DATE = ORIG_PLANNED_START_DATE,
@ORIG_PLANNED_STOP_DATE = ORIG_PLANNED_STOP_DATE,
@ORIG_PLANNED_COUNTER_START = ORIG_PLANNED_COUNTER_START,
@ORIG_PLANNED_COUNTER_STOP = ORIG_PLANNED_COUNTER_STOP,
@CUR_PLANNED_START_DATE = CUR_PLANNED_START_DATE,
@CUR_PLANNED_STOP_DATE = CUR_PLANNED_STOP_DATE,
@CUR_PLANNED_COUNTER_START = CUR_PLANNED_COUNTER_START,
@CUR_PLANNED_COUNTER_STOP = CUR_PLANNED_COUNTER_STOP,
@ACTUAL_START_DATE = ACTUAL_START_DATE,
@ACTUAL_STOP_DATE = ACTUAL_STOP_DATE,
@ACTUAL_COUNTER_START = ACTUAL_COUNTER_START,
@ACTUAL_COUNTER_STOP = ACTUAL_COUNTER_STOP ,
@PRIORITY = PRIORITY
FROM
A_TASKS WHERE ID = @taskID

exec A_SP_TASKS_UPDATE_TASK
@newID OUTPUT,
@messages OUTPUT,
NULL,
@PARENT_ID,
@REQUESTOR,
@newRequesteeID,
NULL,
@DESCRIPTION ,
@SYSTEM_TASK ,
@COMMENT ,
@SECURITY_LEVEL ,
@COUNTER ,
@ORIG_PLANNED_START_DATE ,
@ORIG_PLANNED_STOP_DATE ,
@ORIG_PLANNED_COUNTER_START ,
@ORIG_PLANNED_COUNTER_STOP ,
@CUR_PLANNED_START_DATE ,
@CUR_PLANNED_STOP_DATE ,
@CUR_PLANNED_COUNTER_START ,
@CUR_PLANNED_COUNTER_STOP ,
@ACTUAL_START_DATE ,
@ACTUAL_STOP_DATE ,
@ACTUAL_COUNTER_START ,
@ACTUAL_COUNTER_STOP ,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
@PRIORITY,
NULL,
@strNTLogin 

print 'Added that task now I need to copy all the related data to the new task = ' + @newID
print 'Adding customer Links'
INSERT INTO A_TASK_CUSTOMER_LINK (ID,TASK_ID,CUSTOMER_ID,DRCM,MODBY)
	SELECT newID(),@newID,CUSTOMER_ID,getDate(),@strNTLogin FROM A_TASK_CUSTOMER_LINK WHERE TASK_ID = @taskID
print 'Adding Object Links'
INSERT INTO A_TASK_OBJECT_LINK (ID,TASK_ID,OBJECT_ID,DRCM,MODBY)
	SELECT newID(),@newID,OBJECT_ID,getDate(),@strNTLogin FROM A_TASK_OBJECT_LINK WHERE TASK_ID = @taskID
print 'Adding Task Counters'
INSERT INTO A_TASK_COUNTERS (ID,COUNTER_TYPE,VAL,TASK_ID,IS_CURRENT,DRCM,MODBY)
	SELECT newID(),COUNTER_TYPE,VAL,@newID,IS_CURRENT,getDate(),@strNTLogin FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID
print 'Adding Task Additional Assignees'
INSERT INTO A_TASK_ADDITIONAL_ASSIGNEES_LINK (ID,TASK_ID,PERSON_ID,DRCM,MODBY)
	SELECT newID(),@newID,PERSON_ID,getDate(),@strNTLogin FROM A_TASK_ADDITIONAL_ASSIGNEES_LINK WHERE TASK_ID = @taskID
print 'Adding Companies to view'
INSERT INTO A_TASK_COMPANIES_TO_VIEW_LINK (ID,TASK_ID,CO_ID,DRCM,MODBY)
	SELECT newID(),@newID,CO_ID,getDate(),@strNTLogin FROM A_TASK_COMPANIES_TO_VIEW_LINK WHERE TASK_ID = @taskID
print 'Adding Ref Procs'
INSERT INTO A_TASK_REFERENCE_PROCEDURES (ID,TASK_ID,REF_PROCEDURE,DRCM,MODBY)
	SELECT newID(),@newID,REF_PROCEDURE,getDate(),@strNTLogin FROM A_TASK_REFERENCE_PROCEDURES WHERE TASK_ID = @taskID
print 'Adding Ref Procs'
INSERT INTO A_TASK_REFERENCE_PROCEDURES (ID,TASK_ID,REF_PROCEDURE,DRCM,MODBY)
	SELECT newID(),@newID,REF_PROCEDURE,getDate(),@strNTLogin FROM A_TASK_REFERENCE_PROCEDURES WHERE TASK_ID = @taskID

print 'Adding Task Monitors'
INSERT INTO A_TASK_MONITORS ([ID], [TASK_ID], [MONITOR_TEMPLATE_ID], [RESULT], [DATE_RECORDED], 
	[COMMENT], [MODBY], [DRCM], [DESCRIPTION], [START_TASK], [STOP_TASK], [START_TYPE], 
	[STOP_TYPE], [UNITS], [CREATE_DATE], [CREATED_BY], [AUTO], [IS_SYSTEM], [TARGET_TEXT], [RESULT_TEXT])
	SELECT
	newID(), @newID, [MONITOR_TEMPLATE_ID], [RESULT], [DATE_RECORDED], 
	[COMMENT], [MODBY], [DRCM], [DESCRIPTION], [START_TASK], [STOP_TASK], [START_TYPE], 
	[STOP_TYPE], [UNITS], [CREATE_DATE], [CREATED_BY], [AUTO], [IS_SYSTEM], [TARGET_TEXT], [RESULT_TEXT]
		FROM A_TASK_MONITORS WHERE TASK_ID = @taskID

print 'Adding Task Email People Link'
INSERT INTO A_TASK_EMAIL_PEOPLE_LINK (ID,TASK_ID,PERSON_ID,DRCM,MODBY)
	SELECT newID(),@newID,PERSON_ID,getDate(),@strNTLogin FROM A_TASK_EMAIL_PEOPLE_LINK WHERE TASK_ID = @taskID

print 'Adding Task Meeting Link'
INSERT INTO A_TASK_MEETING_LINK (ID,TASK_ID,MEETING_ID,DRCM,MODBY)
	SELECT newID(),@newID,MEETING_ID,getDate(),@strNTLogin FROM A_TASK_MEETING_LINK WHERE TASK_ID = @taskID

print 'Adding Task SURVEY Link'
INSERT INTO A_TASK_SURVEY_LINK (ID,TASK_ID,SURVEY_ID,DRCM,MODBY)
	SELECT newID(),@newID,SURVEY_ID,getDate(),@strNTLogin FROM A_TASK_SURVEY_LINK WHERE TASK_ID = @taskID

print 'Adding Task DISCUSSION Link'
INSERT INTO A_TASK_DISCUSSION_LINK (ID,TASK_ID,DISCUSSION_ID,DRCM,MODBY)
	SELECT newID(),@newID,DISCUSSION_ID,getDate(),@strNTLogin FROM A_TASK_DISCUSSION_LINK WHERE TASK_ID = @taskID

print 'Adding Task Ref Filesk'
INSERT INTO A_TASK_REF_FILES (ID,TASK_ID,FILE_ID,DRCM,MODBY)
	SELECT newID(),@newID,FILE_ID,getDate(),@strNTLogin FROM A_TASK_REF_FILES WHERE TASK_ID = @taskID

print 'Adding Task CC People'
INSERT INTO A_TASK_CC_PEOPLE (ID,TASK_ID,PERSON_ID,DRCM,MODBY)
	SELECT newID(),@newID,PERSON_ID,getDate(),@strNTLogin FROM A_TASK_CC_PEOPLE WHERE TASK_ID = @taskID

print 'Copying all the business purposes and objects and projects as well'
exec A_SP_PROJECT_COPY_ONE_ITEMS_PROJ_OBJ_PURP_TAGS @taskID,'A_TASKS',@newID,'A_TASKS',@strNTLogin

print 'Copying all the Comments as well'
INSERT INTO A_TASK_COMMENT (ID,TASK_ID,DATE_CREATED,COMMENT,WRITER,WRITER_COMPANY,ALLOWED_TO_VIEW,DRCM,MODBY)
SELECT newID(),@newID,DATE_CREATED,COMMENT,WRITER,WRITER_COMPANY,ALLOWED_TO_VIEW,DRCM,MODBY FROM A_TASK_COMMENT
	WHERE TASK_ID = @taskID










