

CREATE    procedure dbo.A_SP_PURCHASE_ITEM_UPDATE_DUE_DATE
@purchItemID varchar(50),
@myDate datetime,
@strNTLogin varchar(50)
AS
UPDATE A_ORDER_ITEMS SET DUE_DATE = @myDate WHERE ID = @purchItemID
SELECT DISTINCT DUE_DATE,START_DATE FROM A_V_WORKER_SCREEN_TASKS WHERE PURCHASE_ITEM_ID = @purchItemID
fin:



