

CREATE   PROCEDURE dbo.A_SP_PROCEDURE_TASK_PROGRESS_SEARCH
@strWHERE nvarchar(4000),
@procID varchar(50),
@repName varchar(2000),
@strNTLogin nvarchar(50)
as
declare @sql varchar(8000),@myCO varchar(50)

SELECT @myCo = COMPANY 
FROM A_APPROVED_PEOPLE 
WHERE ID=@strNTLogin

set @sql = 'SELECT
                a.ASSIGNEE_ID,
				t.STATUS, 
				COUNT(t.ID) AS CNT
				 FROM A_V_TASK_SEARCH t,A_TASK_PROCEDURE_ASSIGNEE a '
set @sql = @sql + 'WHERE a.TASK_ID = t.ID '
set @sql = @sql + ' AND ' +  @strWhere
set @sql = @sql + ' AND t.PARENT_ID IN (SELECT ID FROM A_TASKS WHERE PROCEDURE_ID = ''' + @procID + ''')'

set @sql = @sql + ' GROUP BY t.PROCEDURE_ID,t.STATUS,a.ASSIGNEE_ID ORDER BY a.ASSIGNEE_ID,t.STATUS' 


print 'SQL = ' + @SQL

CREATE TABLE #RAW_DATA(PERSON_ID varchar(50),STATUS varchaR(50),CNT int)

CREATE TABLE #p
	(PERSON_ID varchar(50),COMPLETED_TASKS int,
	INCOMPLETE_TASKS int,TOTAL_TASKS int,
	REP_NAME varchar(2000),PERCENTAGE_COMPLETE float,
	ROOT_TASK_ID varchar(50)
)

INSERT INTO #RAW_DATA(PERSON_ID,STATUS,CNT) EXEC(@SQL)

--SELECT * FROM #RAW_DATA

INSERT into #p (PERSON_ID,COMPLETED_TASKS,INCOMPLETE_TASKS,TOTAL_TASKS,REP_NAME,PERCENTAGE_COMPLETE) 
	SELECT DISTINCT PERSON_ID,0,0,0,@repName,0 FROM #RAW_DATA

UPDATE #p SET
COMPLETED_TASKS = (SELECT isNull(SUM(r.CNT),0) FROM #RAW_DATA r WHERE r.PERSON_ID = #p.PERSON_ID AND r.STATUS IN ('COMPLETED','FINISHED','CLOSED') ), 
INCOMPLETE_TASKS = (SELECT isNull(SUM(r.CNT),0) FROM #RAW_DATA r WHERE r.PERSON_ID = #p.PERSON_ID AND r.STATUS IN ('ACCEPTED','REQUESTED','PENDING_PARENT_ACCEPTANCE'))

UPDATE #p SET TOTAL_TASKS = COMPLETED_TASKS + INCOMPLETE_TASKS

UPDATE #p SET 
 PERCENTAGE_COMPLETE = 
--(COMPLETED_TASKS / TOTAL_TASKS) 
	case 
		when TOTAL_TASKS > 0 then (convert(float,COMPLETED_TASKS) / convert(float,TOTAL_TASKS) * 100) 
		else 0
	end
		
UPDATE #p SET
ROOT_TASK_ID = (SELECT top 1 ID FROM A_TASKS WHERE PROCEDURE_ID = @procID AND REQUESTEE_ID = #p.PERSON_ID AND PARENT_ID is null )
 


SELECT p.*,per.FULL_NAME FROM #p p, A_V_PEOPLE_APPROVED_DATA per WHERE p.PERSON_ID = per.ID ORDER BY per.LAST_NAME,per.NAME







































