


/*
STORED PROCEDURE CALLED IN
MODULE: procedures/viewProcedure.asp
*/
CREATE    PROCEDURE A_SP_SECURITY_LEVEL_GET_DATA_BY_ID
	@ID nvarchar(50),
	@strNTLogin nvarchar(50)
AS
SELECT * FROM A_SECURITY_LEVELS WHERE ID = @ID



