
/*
STORED PROCEDURE CALLED IN
		needs/search.asp
*/
CREATE  PROCEDURE A_SP_COMPANY_GET_BY_ID_LIST
	@strIDList nvarchar(50),
	@strNTLogin nvarchar(50)
AS
CREATE TABLE #TempItems	(IT varchar(50))
INSERT INTO #TempItems Exec A_SP_Z_SPLIT @strIDList,', '
SELECT ID AS CO_ID,NAME AS CO_NAME 
FROM A_APPROVED_COMPANIES WHERE ID IN (SELECT IT FROM #TempItems)

