CREATE PROCEDURE A_SP_COMPANY_GET_EMPLOYEE_PRODUCTS
@coID varchar(50),
@strNTLogin as varchar(50)
AS
SELECT p.ID AS P_ID,p.NAME AS P_NAME FROM A_COMPANY_EMPLOYEE_PRODUCT_LIST l,
A_V_PRODUCTS_APPROVED_DATA p
WHERE l.CO_ID = @coID AND l.PRODUCT_ID = p.ID
