
CREATE PROCEDURE [dbo].[A_SP_FILL_GET_TASK_TREE] 
@fillID varchar(50),
@strNTLogin varchar(50)

AS
BEGIN
declare @PURCH_ITEM_ID varchar(50)
SELECT @PURCH_ITEM_ID = PURCH_ITEM_ID FROM A_FILLS WHERE ID = @fillID
declare @taskID varchar(50)
SELECT @taskID = TASK_ID FROM [A_V_TASK_WITH_ORDER_INFORMATION] WHERE PURCHASE_ITEM_ID = @PURCH_ITEM_ID
exec [A_SP_TASK_GET_HIEARCHY_FOR_ROOT_TASK] @taskID, null, @taskID, @strNTLogin
END

