


CREATE  PROCEDURE A_SP_POP_FILL_PRODUCT_PARENT_INFO
@pObjID varchar(50) OUTPUT,
@strNTLogin varchar(50)

AS
SELECT o.ROOT AS PARENT_ID,p.NAME AS PARENT_NAME FROM
A_PRODUCTS_HISTORY p, A_OBJECTS o WHERE
o.ID = @pObjID AND
o.ID = p.OBJECT_ID


