

CREATE  PROCEDURE A_SP_PEOPLE_GET_APPROVED_DATA
@ID VARCHAR(50),
@strNTLogin varchar(50)
AS
SELECT P.*,Z.G_DIFF as G_DIFF,Z.DESCRIPTION AS TIME_ZONE_NAME FROM A_V_PEOPLE_APPROVED_DATA P,A_TIME_ZONES Z WHERE P.ID = @ID AND
Z.ID = P.TIME_ZONE



