
CREATE  PROCEDURE dbo.A_SP_PRODUCT_GET_LOCATION_LIST_FOR_PARTS 
@PRODUCT_ID varchar(50),
@PPL_ID varchar(50),
@strNTLogin varchar(50)
AS
print 'getting all the locations that have at least one of these parts at them.'
declare @pplHistID varchar(50),@supplierID varchar(50)
SELECT @pplHistID = HISTORY_REF_ID FROM A_PROD_PRICE_LIST WHERE ID = @PPL_ID
SELECT @supplierID = SUPPLIER_ID FROM A_V_PRODUCTS_APPROVED_DATA WHERE ID = @PRODUCT_ID

CREATE TABLE #partsList (
	PART_ID varchar(50),
	QTY float
)

INSERT INTO #partsList (QTY,PART_ID)
SELECT sl.QTY,o.ROOT FROM 
A_PROD_PRICE_LIST_SUB_PRICE_LISTS sl,
A_APPROVED_OBJECTS ao,
A_OBJECTS o
WHERE 
sl.PARENT = @pplHistID 
and sl.RELATIONSHIP = 'PARTS_PROVIDE_STAY'
and ao.ID = APPROVED_OBJ_ID
and o.ID = ao.OBJ_REF_ID 
and o.OBJ_TABLE = 'A_PARTS_HISTORY'

SELECT * FROM A_V_ACTUAL_PARTS_APPROVED_DATA WHERE PART_ID IN
	(SELECT PART_ID FROM #partsList)


