

CREATE  PROCEDURE dbo.A_SP_ACCOUNT_FIGURE_TOTALS
@acctID varchar(50),
@modby varchar(50)
AS
UPDATE A_ACCOUNTS_HISTORY SET 
INVOICED_BALANCE = (SELECT SUM(AMOUNT) FROM A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS WHERE
	ACCOUNT_ID = @acctID AND STATUS IN ('INVOICED','SENT_TO_CUSTOMER','CLOSED')),
TOTAL_CREDITS = -(SELECT SUM(AMOUNT) FROM A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS WHERE
	ACCOUNT_ID = @acctID AND AMOUNT < 0),
TOTAL_DEBITS = (SELECT SUM(AMOUNT) FROM A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS WHERE
	ACCOUNT_ID = @acctID AND AMOUNT > 0),
TOTAL_TAX = (SELECT SUM(TAX) FROM A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS WHERE
	ACCOUNT_ID = @acctID),
UNINVOICED_BALANCE = (SELECT SUM(AMOUNT) FROM A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS WHERE
	ACCOUNT_ID = @acctID AND STATUS IN ('CREATING')),
BALANCE = (SELECT SUM(AMOUNT) FROM A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS WHERE
	ACCOUNT_ID = @acctID)

WHERE ID IN (SELECT OBJ_ID FROM A_OBJECTS WHERE ROOT = @acctID)


