
CREATE  PROCEDURE  dbo.A_SP_COMPANIES_ROOT_CREATE_ADMINISTRATOR 
@PID varchar(50) OUTPUT,
@CO_ID varchar(50),
@strNTLogin varchar(50)

AS
declare @ROOT_ID as varchar(50),@CO_OBJ_ID as varchar(50)
SELECT @CO_OBJ_ID = OBJECT_ID FROM A_COMPANIES_HISTORY WHERE ID = @CO_ID
SELECT @ROOT_ID = ROOT FROM A_OBJECTS WHERE ID = @CO_OBJ_ID
declare @newID as varchar(50)
exec sp_GetUniqueID3 @newID OUTPUT
INSERT INTO A_PEOPLE_HISTORY (ID,LOGIN,NAME,PASSWORD,LAST_NAME,LANG,COMPANY,SYSTEM_STATUS,ROOT_COMPANY)
SELECT @newID,LOGIN_NAME,FIRST_NAME,PASSWORD,LAST_NAME,'en',@ROOT_ID,'ACTIVE',@ROOT_ID FROM
A_COMPANIES_NEW_PERSON_DATA WHERE CO_ID = @CO_ID
print 'Now we need to manually approve this person'
declare @POID as varchar(50)
SELECT @POID = OBJECT_ID FROM A_PEOPLE_HISTORY WHERE ID = @newID
SELECT @PID = ROOT FROM A_OBJECTS WHERE ID = @POID
declare @newPID as varchar(50)
exec sp_GetUniqueID3 @newPID OUTPUT
INSERT INTO A_PEOPLE (ID,HISTORY_REF_ID,STATUS) VALUES(@PID,@newID,'APPROVED')
UPDATE A_OBJECTS SET LOCKED_BY = NULL,CREATING_CO=@ROOT_ID,STATUS='APPROVED' WHERE ID = @POID

print 'Creating the ADMIN role and putting this person in that role'
declare @adminRoleID as nvarchar(50)
exec sp_GetUniqueID3 @adminRoleID OUTPUT
INSERT INTO A_ROLES_HISTORY (ID,NAME,MODBY,DRCM,SOURCE,HIDDEN,IS_ADMIN) VALUES(@adminRoleID,'Administrators',@POID,getDate(),'ANSWER',1,1)
declare @adminRole as nvarchar(50)
SELECT @adminRole = OBJECT_ID FROM A_ROLES_HISTORY WHERE ID = @adminRoleID
INSERT INTO A_ROLES (ID,HISTORY_REF_ID,STATUS) VALUES (@adminRole,@adminRoleID,'APPROVED')
UPDATE A_OBJECTS SET CREATING_CO=@CO_OBJ_ID,STATUS = 'APPROVED', LOCKED_BY = NULL WHERE ID = @adminRole

print 'Inserting the person into the Admin role'
exec sp_GetUniqueID3 @newID OUTPUT
INSERT INTO A_ROLE_ASSIGNEE(ID,ROLE,PERSON,MODBY,DRCM,STATUS,SOURCE) VALUES (@newID,@adminRoleID,@POID,@POID,getDate(),'ACTIVE','NEW_CO_CREATOR')




