
CREATE PROCEDURE dbo.A_SP_ACCOUNT_INVOICES_MARK_AS_SENT_TO_CUSTOMER
@newID varchar(50) OUTPUT,
@msgs varchar(2000) OUTPUT,
@ACCOUNT_ID varchar(50),
@INVOICE_ID varchar(50),
@strNTLogin varchar(50)
AS
UPDATE A_ACCOUNT_INVOICES SET STATUS = 'SENT_TO_CUSTOMER'
WHERE ID = @INVOICE_ID
exec A_SP_ACCOUNT_FIGURE_TOTALS @ACCOUNT_ID,@strNTLogin

