

CREATE   PROCEDURE dbo.A_SP_RESUMES_UPDATE_ONE
@ID varchar(50),
@MONSTER_ID varchar(50),
@NAME varchar(200),
@STREET varchar(500),
@CITY  varchar(100),
@STATE  varchar(50),
@POSTAL_CODE  varchar(15),
@COUNTRY  varchar(50),
@PHONE  varchar(30),
@EMAIL  varchar(100),
@SALARY varchar(100),
@DESIRED_JOB_STATUS  varchar(200),
@EDUCATION_SHORT varchar(500),
@WORK_STATUS varchar(300),
@TARGET_LOCATIONS  varchar(300),
@RELOCATE varchar(100),
@WILLING_TO_TRAVEL varchar(100),
@strNTLogin varchar(50)
AS
declare @rootCo varchar(50)
SELECT @rootCo = ROOT_COMPANY FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @strNTLogin

if @MONSTER_ID is not null
	begin
	SELECT @ID = ID FROM A_RESUMES WHERE MONSTER_ID = @MONSTER_ID
	end
if @ID is null
	begin
	exec sp_GetUniqueID3 @ID OUTPUT
	INSERT INTO A_RESUMES (ID,MONSTER_ID,CREATE_DATE) VALUES (@ID,@MONSTER_ID,getDate())
	end

UPDATE A_RESUMES 
SET NAME = @NAME,
STREET = @STREET,
CITY = @CITY,
STATE = @STATE,
POSTAL_CODE = @POSTAL_CODE,
COUNTRY = @COUNTRY,
PHONE = @PHONE,
EMAIL = @EMAIL,
SALARY = @SALARY,
DESIRED_JOB_STATUS = @DESIRED_JOB_STATUS,
EDUCATION_SHORT = @EDUCATION_SHORT,
WORK_STATUS = @WORK_STATUS,
TARGET_LOCATIONS = @TARGET_LOCATIONS,
RELOCATE = @RELOCATE,
WILLING_TO_TRAVEL = @WILLING_TO_TRAVEL,
MODBY = @strNTLogin,
ROOT_CO = @rootCo,
DRCM = getDate()
WHERE ID = @ID


SELECT * FROM A_RESUMES WHERE ID = @ID



