




CREATE      PROCEDURE DBO.A_SP_PART_SAVE_SAFETY_LEVEL_SETTINGS 
@locID as nvarchar(50),
@MIN_LEVEL as float,
@MIN_WARNING_LEVEL as float,
@MAX_WARNING_LEVEL as float,
@MAX_LEVEL as float,
@partObjID as nvarchar(50),
@strNTLogin as nvarchar(50)
AS

declare @ph_ID varchar(50)
SELECT @ph_ID = ID FROM A_PARTS_HISTORY WHERE OBJECT_ID = @partObjID
declare @rootPartID varchar(50)
SELECT @rootPartID = ROOT FROM A_OBJECTS WHERE ID = @partObjID
declare @stat varchar(50)
SELECT @stat = STATUS FROM A_OBJECTS WHERE ID = @partObjID
declare @ID varchar(50)
SELECT @ID = ID FROM A_PARTS_SAFETY_STOCK_LEVELS WHERE PART_OBJ_ID = @partObjID
	AND LOCATION_ID = @locID
if @ID is null
	exec sp_GetUniqueID3 @ID OUTPUT
	
DELETE FROM A_PARTS_SAFETY_STOCK_LEVELS WHERE ID = @ID
if not(@locID is null) AND not(@MIN_LEVEL is Null AND @MIN_WARNING_LEVEL is Null AND @MAX_LEVEL is Null AND @MAX_WARNING_LEVEL is Null)
	begin
	INSERT INTO A_PARTS_SAFETY_STOCK_LEVELS 
	(ID,PART_ID,LOCATION_ID,MIN_LEVEL,MAX_LEVEL,
	MIN_WARNING_LEVEL,MAX_WARNING_LEVEL,PART_HIST_ID,
	PART_OBJ_ID,STATUS,DRCM,MODBY)
	VALUES
	(@ID,@rootPartID,@locID,@MIN_LEVEL,@MAX_LEVEL,
	@MIN_WARNING_LEVEL,@MAX_WARNING_LEVEL,@ph_ID,
	@partObjID,@stat,getdate(),@strNTLogin)

declare @myQty float
SELECT @myQty = sum(QTY) FROM A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK WHERE
	PART_ID = @rootPartID AND LOCATION = @locID AND AP_STATUS IN ('ap_available','ap_in_fill','ap_in_call')

UPDATE A_PARTS_SAFETY_STOCK_LEVELS SET CUR_LEVEL = @myQty WHERE
	PART_ID = @rootPartID AND LOCATION_ID = @locID

	end









