



CREATE   PROCEDURE A_SP_PROCEDURE_COMMENTS_GET_DATA
@POID nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @strID as nvarchar(50)
SELECT @strID = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @POID
SELECT * FROM A_PROCEDURE_COMMENTS WHERE PROC_HIST_ID = @strID ORDER BY LOC,PRINT_ORDER


