
CREATE  PROCEDURE DBO.A_SP_TASK_FIGURE_OUT_CHILD_STATUS
@ID varchar(50),
@strNTLogin varchar(50)
AS

if exists (	SELECT * FROM A_TASKS 
			WHERE PARENT_ID = @ID 
			)
		UPDATE A_TASKS SET HAS_CHILD = 1 WHERE ID = @ID
else 
		UPDATE A_TASKS SET HAS_CHILD = 0 WHERE ID = @ID

if exists (
			SELECT * FROM A_TASKS 
			WHERE PARENT_ID = @ID 
			AND STATUS not in ('FINISHED','CLOSED')
			)
		UPDATE A_TASKS SET CHILD_STATUS = 'NOT_FINISHED',HAS_CHILD = 1 WHERE ID = @ID
else 
	UPDATE A_TASKS SET CHILD_STATUS = 'FINISHED' WHERE ID = @ID


