





CREATE    PROCEDURE A_SP_FILES_COPY_FROM_ONE_OBJ_TO_NEXT 
@origID nvarchar(50),
@newID nvarchar(50),
@strNTLogin nvarchar(50)
as
INSERT INTO A_DOCUMENT_LINK (ID,LINKED_DOC_ID,OBJECT_ID,MODBY,DRCM,SHOW_IN_LINE,TYPE)
SELECT newID(),LINKED_DOC_ID,@newID,@strNTLogin,getDate(),SHOW_IN_LINE,TYPE FROM A_DOCUMENT_LINK WHERE OBJECT_ID = @origID







