




CREATE     procedure A_SP_PROCEDURE_GET_APPROVED_OBJECTS_BY_RELATIONSHIP 
@PROC_OBJ_ID nvarchar(50),
@PROC_STEP_ID nvarchar(50),
@RELATIONSHIP nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @pid as nvarchar(50)
SELECT @pid = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @PROC_OBJ_ID
print '@pid = ' + isnull(@pid,'NULL')
if @pid is null and @PROC_STEP_ID is not null
	begin
		SELECT * FROM A_V_PROCEDURE_OBJECT_LINK_DATA WHERE RELATIONSHIP = @RELATIONSHIP AND STEP_ID = @PROC_STEP_ID
	end
if @RELATIONSHIP is not null
	if @PROC_STEP_ID is not null 
		begin
		SELECT * FROM A_V_PROCEDURE_OBJECT_LINK_DATA WHERE PROCEDURE_ID = @pid AND RELATIONSHIP = @RELATIONSHIP AND STEP_ID = @PROC_STEP_ID
		end
	else
		begin
		SELECT * FROM A_V_PROCEDURE_OBJECT_LINK_DATA WHERE PROCEDURE_ID = @pid AND RELATIONSHIP = @RELATIONSHIP AND STEP_ID is null
		end
else
	if @PROC_STEP_ID is not null 
		begin
		print 'SELECT * FROM A_V_PROCEDURE_OBJECT_LINK_DATA WHERE PROCEDURE_ID = ' + @pid + ' AND STEP_ID = ''' + isNULL(@PROC_STEP_ID,'NULL') + ''''
		SELECT * FROM A_V_PROCEDURE_OBJECT_LINK_DATA WHERE PROCEDURE_ID = @pid AND STEP_ID = @PROC_STEP_ID
		end
	else
		begin
		SELECT * FROM A_V_PROCEDURE_OBJECT_LINK_DATA WHERE PROCEDURE_ID = @pid AND STEP_ID is null
		end







