


CREATE    PROCEDURE DBO.A_SP_PURCHASE_GET_EDIT_DATA_BY_HIST_ID
@HID varchar(50),
@strNTLogin varchar(50)
AS
declare @hasShipping tinyInt
SELECT @hasShipping = 
	case when exists(SELECT * FROM A_V_ORDER_ITEMS_ALL_DATA WHERE PURCHASE_HIST_ID = @HID AND SYSTEM_ID = 'SYS_SHIPPING')
		then 1
	else 0
	end
declare @hasWeight tinyInt
SELECT @hasWeight = 
	case when exists(SELECT * FROM A_V_ORDER_ITEMS_ALL_DATA WHERE PURCHASE_HIST_ID = @HID AND PRICE_LIST_TYPE = 'WT_BASED')
		then 1
	else 0
	end



SELECT    oo.CUSTOMER_CO,@hasShipping as HAS_SHIPPING,@hasWeight as HAS_WEIGHT, ph.ID AS HIST_ID, ph.DATE_CREATED, ph.PURCHASE_STATUS, ph.ORDER_ID, ph.DRCM, ph.MODBY, ph.OBJECT_ID, o.LOCKED_BY, 
                      o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.WFS_ID, o.LOCKED_BY_NAME, 
                      o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, o.APPROVAL_DATE,
			ph.CUST_PURCH_NUM,ph.SUP_PURCH_NUM
FROM         dbo.A_PURCHASES_HISTORY ph 
			INNER JOIN dbo.A_OBJECTS o ON ph.OBJECT_ID = o.ID
			INNER JOIN A_V_ORDERS_APPROVED_DATA oo ON ph.ORDER_ID = oo.ID
				
WHERE ph.ID = @HID



