


CREATE     PROCEDURE A_SP_PROCEDURES_REMOVE_ROLES_TO_VIEW
	@POID nvarchar(50),
	@strNTLogin nvarchar(50)
as
declare @PID as nvarchar(50)
SELECT @PID = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @POID 
DELETE FROM A_PROCEDURE_OBJECT_LINK 
WHERE PROCEDURE_ID = @PID AND RELATIONSHIP = 'ROLE_TO_VIEW'






