
CREATE PROCEDURE dbo.A_SP_DNR_FIND_MATCHING_CASES_WITH_TASK_DATA
@ID varchar(50)
AS
create TABLE #CASES (ID varchar(50))
INSERT INTO #CASES exec A_SP_DNR_FIND_MATCHING_CASES @ID
if dbo.MD() = 1 SELECT 'CASES',* FROM #CASES c,A_TASKS t WHERE t.ID = c.ID

SELECT t.* FROM #CASES c, A_V_TASK_SEARCH t WHERE t.ID = c.ID

