

CREATE PROCEDURE A_SP_ACTUAL_PARTS_GET_OWNER_BY_AP_ID
@ID varchar(50),
@strNTLogin varchar(50)
AS
declare @OWNER_ID as varchar(50)
SELECT @OWNER_ID = CUR_OWNER FROM A_ACTUAL_PARTS_SUB_PARTS WHERE ID = @ID
SELECT P_ID,P_NAME FROM A_V_PEOPLE_BY_NTLOGIN WHERE P_ID = @OWNER_ID


