
CREATE  PROCEDURE A_SP_ACCOUNT_GET_PRODUCT_EXCEPTIONS 
@exType varchar(50),
@ID varchar(50),
@strNTLogin varchar(50)
AS
SELECT e.*,p.NAME AS PRODUCT_NAME 
FROM A_ACCOUNT_PRODUCT_EXCEPTIONS e, A_V_PRODUCTS_APPROVED_DATA p
WHERE e.ACCT_ID = @ID
AND p.ID = e.PRODUCT_ID
AND EX_TYPE = @exType

