




CREATE    PROCEDURE A_SP_PROCEDURE_STEP_GET_LIST_OF_OTHER_STEPS
@POID nvarchar(50),
@curStepID nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @strID as nvarchar(50)
SELECT @strID = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @POID
if @curStepID is null
	SELECT * FROM A_PROCEDURE_STEPS WHERE PROCEDURE_ID = @strID ORDER BY PRINT_ORDER
else
	SELECT * FROM A_PROCEDURE_STEPS WHERE PROCEDURE_ID = @strID AND ID <> @curStepID ORDER BY PRINT_ORDER






