

CREATE PROCEDURE dbo.A_SP_ACCOUNT_INVOICES_MANUALLY_CREATE_NEW_ONE
@invoiceID varchar(50) OUTPUT,
@messages varchar(2000) OUTPUT,
@acctID varchar(50),
@strNTLogin varchar(50)
AS

exec sp_GetUniqueID3 @invoiceID OUTPUT
INSERT INTO A_ACCOUNT_INVOICES (ID,ACCOUNT_ID,DRCM,MODBY,STATUS,INVOICE_TYPE)
		VALUES(@invoiceID,@acctID,getDate(),@strNTLogin,'CREATING','MANUAL')

UPDATE A_ACCOUNT_INVOICES SET 
	TOTAL_DUE = null, PREVIOUS_BALANCE = null,
	PAYMENT_AMOUNT = 0,DISPUTED_AMOUNT =0,LATE_FEES = 0
	WHERE ID = @invoiceID




