
CREATE              PROCEDURE A_SP_PEOPLE_UPDATE_PERSON_SEARCH_TABLE
@objID nvarchar(50)
as
--This will put all the search data together for a certain person
--First check to see if this person is even in the table
declare @tester as nvarchar(50)
SELECT @tester = OBJ_ID from A_PEOPLE_SEARCH_TABLE WHERE OBJ_ID = @objID
if @tester is null
	--We just simpy need to add this person
	begin
	INSERT INTO A_PEOPLE_SEARCH_TABLE 
	(OBJ_ID,ID,NAME,LAST_NAME,MIDDLE_NAME,FULL_NAME,TIME_ZONE,
		SYSTEM_STATUS,BOSS_ID,HIRE_DATE,COMPANY_ID,POSITION_ID,IS_HEAD)
	SELECT OBJECT_ID,ID,NAME,LAST_NAME,MIDDLE_NAME,FULL_NAME,TIME_ZONE,SYSTEM_STATUS,
	BOSS,HIRE_DATE,COMPANY,CO_POSITION,IS_HEAD FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID
	end
else
	--We already hae an entry so we should just go ahead and aupdate each field
	begin
		UPDATE A_PEOPLE_SEARCH_TABLE SET ID = (SELECT ID FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET NAME = (SELECT NAME FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET LAST_NAME = (SELECT LAST_NAME FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET MIDDLE_NAME = (SELECT MIDDLE_NAME FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET FULL_NAME = (SELECT FULL_NAME FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET TIME_ZONE = (SELECT TIME_ZONE FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET SYSTEM_STATUS = (SELECT SYSTEM_STATUS FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET BOSS_ID = (SELECT BOSS FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET HIRE_DATE = (SELECT HIRE_DATE FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET COMPANY_ID = (SELECT COMPANY FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET POSITION_ID = (SELECT CO_POSITION FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
		UPDATE A_PEOPLE_SEARCH_TABLE SET IS_HEAD = (SELECT IS_HEAD FROM A_PEOPLE_HISTORY WHERE OBJECT_ID = @objID) WHERE OBJ_ID = @objID
	end
	
--Now we have all the data from the People Table.  We need to get all the data from the other tables
--Get the Boss's name
UPDATE A_PEOPLE_SEARCH_TABLE 
	SET A_PEOPLE_SEARCH_TABLE.BOSS_NAME = 
		(SELECT p.FULL_NAME FROM A_V_PEOPLE_DATA_QUICK p WHERE ID = A_PEOPLE_SEARCH_TABLE.BOSS_ID)
	WHERE OBJ_ID = @objID
--Get The Company Name
UPDATE A_PEOPLE_SEARCH_TABLE SET COMPANY_NAME = (SELECT c.NAME FROM A_PEOPLE_HISTORY p,A_APPROVED_COMPANIES c WHERE 
p.OBJECT_ID = @objID AND p.COMPANY = c.ID)
WHERE OBJ_ID = @objID
--Get The Position Name
UPDATE A_PEOPLE_SEARCH_TABLE SET POSITION_NAME = (SELECT TOP 1 r.NAME FROM A_PEOPLE_HISTORY p,A_APPROVED_ROLES r
WHERE p.OBJECT_ID = @objID AND p.CO_POSITION = r.ID)
WHERE OBJ_ID = @objID
--Location
print 'Updating the location'
UPDATE A_PEOPLE_SEARCH_TABLE SET LOCATION_ID = 
(SELECT TOP 1 LOCATION_ID FROM A_LOCATIONS_OBJECT_LINK WHERE OBJECT_ID = @objID AND LOCATION_TYPE = 'SYS-LOCATION-1')
WHERE OBJ_ID = @objID

UPDATE A_PEOPLE_SEARCH_TABLE SET LOCATION_NAME = 
(SELECT TOP 1 LOCATION_NAME FROM A_LOCATIONS_OBJECT_LINK WHERE OBJECT_ID = @objID AND LOCATION_TYPE = 'SYS-LOCATION-1')
WHERE OBJ_ID = @objID

--Primary Phone
declare @pnum as nvarchar(50)
declare @pID as nvarchar(50)
SELECT @pnum = PHONE_NUMBER + isNULL('ext(' + PHONE_EXTENSION + ')','') + isNULL('pin(' + PHONE_PIN + ')',''),@pID = ID FROM A_PHONE_NUMBERS WHERE OBJECT_ID = @objID and [PHONE_TYPE] = 'SYS-PHONE-1'
UPDATE A_PEOPLE_SEARCH_TABLE SET 
PRIMARY_PHONE_NUMBER = @pnum,PRIMARY_PHONE_ID = @pID WHERE OBJ_ID = @objID
--Secondary Phone
declare @snum as nvarchar(50)
declare @sID as nvarchar(50)
SELECT @snum = PHONE_NUMBER + isNULL('ext(' + PHONE_EXTENSION + ')','') + isNULL('pin(' + PHONE_PIN + ')',''),@sID = ID FROM A_PHONE_NUMBERS WHERE OBJECT_ID = @objID and [PHONE_TYPE] = 'SYS-PHONE-2'
UPDATE A_PEOPLE_SEARCH_TABLE SET 
SECONDARY_PHONE_NUMBER = @snum,SECONDARY_PHONE_ID = @sID WHERE OBJ_ID = @objID
--Email
declare @eADDRESS as nvarchar(50)
declare @eID as nvarchar(50)
SELECT @eADDRESS = ADDY,@eID = ID FROM A_EMAILS WHERE OBJECT_ID = @objID and [TYPE] = 'SYS-EMAIL-1'
UPDATE A_PEOPLE_SEARCH_TABLE SET 
WORK_EMAIL_ADDRESS = @eADDRESS,WORK_EMAIL_ID = @eID WHERE OBJ_ID = @objID



















