
CREATE  PROCEDURE DBO.A_SP_PURCHASE_UPDATE_PURCHASE_STATUS
@purchHistID varchar(50),
@strNTLogin varchar(50)
AS
if (EXISTS (SELECT * FROM A_FILLS WHERE PURCH_ITEM_ID IN (SELECT ID FROM A_ORDER_ITEMS
		WHERE PURCHASE_HIST_ID = @purchHistID AND FILL_OBJ_ID IS NULL)))
	begin
	UPDATE A_PURCHASES_HISTORY SET PURCHASE_STATUS = 'WAITING_FILLS' WHERE ID = @purchHistID
	end
else
	begin
	UPDATE A_PURCHASES_HISTORY SET PURCHASE_STATUS = 'ALL_FILLED' WHERE ID = @purchHistID
	end

declare @taskID varchar(50),@taskStatus varchar(50)
SELECT @taskID = TASK_ID FROM A_TASK_ORDER_INFORMATION WHERE 
	PURCHASE_HIST_ID = @purchHistID 
	AND PURCHASE_ITEM_ID IS NULL
	AND FILL_ID IS NULL
if @taskID is not null
	begin
	SELECT @taskStatus = STATUS FROM A_TASKS WHERE ID = @taskID
	UPDATE A_PURCHASES_HISTORY 
		SET PURCHASE_STATUS = 
		(SELECT case when (@taskStatus = 'REQUESED') then 'ALL_FILLED' 
		when (@taskStatus = 'PURCHASE_EXECUTING') then 'EXECUTING'
		when (@taskStatus = 'FINISHED') then 'FINISHED'
		when (@taskStatus = 'CLOSED') then 'CLOSED'
		else 'ALL_FILLED'
		end)
	WHERE ID = @purchHistID
	end







