


CREATE   PROCEDURE A_SP_PROCEDURE_STEP_GET_REFERENCE_FILES
	@procStepID nvarchar(50),
	@strNTLogin nvarchar(50)
AS

SELECT *,NAME AS SHOW, DOC_ID AS VALUE FROM A_V_PROCEDURE_STEP_DOCUMENT_DATA WHERE STEP_ID = @procStepID





