



CREATE     PROCEDURE dbo.A_SP_ORDERS_GET_ITEMS_DATA_WITH_SHIPPING
@orderObjID varchar(50),
@strNTLogin varchar(50)
AS
declare @ordID as varchar(50)
SELECT @ordID = ID FROM A_ORDERS_HISTORY WHERE OBJECT_ID = @orderObjID
SELECT * FROM A_V_ORDER_ITEMS_DATA_WITH_SHIPPING WHERE ORDER_ID = @ordID 
AND (PROC_SYS_ID is null OR (PROC_SYS_ID <> 'SYS_SHIPPING' AND PROC_SYS_ID <> 'SYS_TRAVEL'))
ORDER BY PARENT_LIST,PROC_NAME




