




CREATE            PROCEDURE A_SP_FAVORITES_SHOW_ITEMS
	@GROUP AS nvarchar(10),
	@strNTLogin AS nvarchar(50)
as
declare @myType as nvarchar(50)
declare @sql as nvarchar(200)
select @myType = FAV_TYPE FROM A_PEOPLES_FAVORITE_GROUPS WHERE ID = @GROUP
if @myType = 'A_MAIN_MENU'
	SELECT * FROM A_V_Z_FAVORITES_MENU_ITEMS WHERE [GROUP] = @GROUP ORDER BY NUM
if @myType = 'A_ROLES'
	SELECT * FROM A_V_Z_FAVORITES_ROLE_ITEMS WHERE [GROUP] = @GROUP ORDER BY NUM
if @myType = 'A_PEOPLE'
	SELECT * FROM A_V_Z_FAVORITES_PEOPLE_ITEMS WHERE [GROUP] = @GROUP ORDER BY NUM
if @myType = 'A_PROCEDURES'
	SELECT * FROM A_V_Z_FAVORITES_PROCEDURE_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_TASKS'
	SELECT * FROM A_V_Z_FAVORITES_TASK_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_PARTS_HISTORY'
	SELECT * FROM A_V_Z_FAVORITES_PARTS_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_MEETINGS'
	SELECT * FROM A_V_Z_FAVORITES_MEETINGS_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_DISCUSSIONS'
	SELECT * FROM A_V_Z_FAVORITES_DISCUSSIONS_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_SURVEYS'
	SELECT * FROM A_V_Z_FAVORITES_SURVEYS_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_SERVICE_CALLS'
	SELECT * FROM A_V_Z_FAVORITES_SERVICE_CALLS_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_NEEDS'
	SELECT * FROM A_V_Z_FAVORITES_NEEDS_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM
if @myType = 'A_MESSAGES'
	SELECT * FROM A_V_Z_FAVORITES_MESSAGES_ITEMS WHERE [GROUP_ID] = @GROUP ORDER BY NUM

















