

CREATE   PROCEDURE dbo.A_SP_FILL_SPLIT_FROM_BATCH
@subFillID varchar(50),
@strNTLogin varchar(50)
AS
print 'Splitting out fill Item with ID = ' + @subFillID
declare @batchFillID varchar(50)
SELECT @batchFillID = BATCH_PARENT FROM A_FILLS WHERE ID = @subFillID
print 'removing Fill ' + @subFillID + ' to Batch Fill ' + @batchFillID
print 'First lets uninstall our part from the batch part'
declare @subPartID varchar(50),@batchPartID varchar(50)
SELECT @batchPartID = FILL_OBJ_ID FROM A_FILLS WHERE ID = @batchFillID
SELECT @subPartID = FILL_OBJ_ID FROM A_FILLS WHERE ID = @subFillID
UPDATE A_ACTUAL_PARTS_HISTORY SET PARENT_ID = null 
	WHERE OBJECT_ID IN (SELECT ID FROM A_OBJECTS WHERE ROOT = @subPartID)
print 'Now lets update our fill info'
UPDATE A_FILLS SET BATCHED = null, BATCH_PARENT = null WHERE ID = @subFillID
exec A_SP_ACTUAL_PARTS_CREATE_CHILD_LIST null,@batchPartID,0,null,@strNTLogin
print 'Now get the copy task id'
declare @copyTaskID varchar(50),@myTaskID varchar(50)
SELECT @copyTaskID = TASK_ID FROM A_TASK_ORDER_INFORMATION WHERE FILL_ITEM_ID = @batchFillID

print 'Batch TASK ID = ' + @copyTaskID
exec sp_GetUniqueID3 @myTaskID OUTPUT
INSERT INTO A_TASKS (

--ID,DESCRIPTION,STATUS,COMMENT,REQUESTOR,CREATED_BY,CREATE_DATE,PROCEDURE_ID,SECURITY_LEVEL,
--GROUP_REQUESTEE_ID,HAS_CHILD,HAS_REF_PROC,ORIG_REQUESTOR_ID,PRIORITY,CHILD_STATUS,RECURSION_NUMBER)

ID,DESCRIPTION,STATUS,COMMENT,REQUESTOR,
[COMPLETED_BY],[MODBY],[DRCM],[CHILD_ORDER],[CREATED_BY],
[CREATE_DATE],[CLOSED],[OPENED_BY],[OPEN_DATE],[SYSTEM_TASK],[PROCEDURE_ID],[PROCEDURE_STEP_ID], 
[SECURITY_LEVEL],[COUNTER],[REQUESTEE_ID],[GROUP_REQUESTEE_ID],[COUNTER_NAME],[COUNTER_VALUE],
[ORIG_PLANNED_START_DATE],[ORIG_PLANNED_STOP_DATE],[CUR_PLANNED_START_DATE],[CUR_PLANNED_STOP_DATE],
[ACTUAL_START_DATE],[ACTUAL_STOP_DATE],[ORIG_PLANNED_COUNTER_START],[ORIG_PLANNED_COUNTER_STOP],
[CUR_PLANNED_COUNTER_START],[CUR_PLANNED_COUNTER_STOP],[ACTUAL_COUNTER_START],[ACTUAL_COUNTER_STOP],
[LATEST_REQUESTEE_NAME],[HAS_DISCUSSION],[HAS_SURVEY],[HAS_CHILD],[HAS_REF_PROC],[HAS_FILE],[ORIG_REQUESTOR_ID],
[HAS_REF_OBJ],[HAS_MONITOR],[COLOR_CODE],[LAST_REQUEST_DATE],[PRIORITY],[CHILD_STATUS],[IS_QUOTE],
[IS_QUOTE_ACCEPT], [IS_FILL], [MANAGER], [DNR_TYPE], [RECURSION_NUMBER], [REPEAT_FROM_STEP]

)
	SELECT 
@myTaskID,DESCRIPTION,STATUS,'Copied from Batch = ' + @BatchFillID,REQUESTOR,
[COMPLETED_BY],[MODBY],[DRCM],[CHILD_ORDER],[CREATED_BY],
[CREATE_DATE],[CLOSED],[OPENED_BY],[OPEN_DATE],[SYSTEM_TASK],[PROCEDURE_ID],[PROCEDURE_STEP_ID], 
[SECURITY_LEVEL],[COUNTER],[REQUESTEE_ID],[GROUP_REQUESTEE_ID],[COUNTER_NAME],[COUNTER_VALUE],
[ORIG_PLANNED_START_DATE],[ORIG_PLANNED_STOP_DATE],[CUR_PLANNED_START_DATE],[CUR_PLANNED_STOP_DATE],
[ACTUAL_START_DATE],[ACTUAL_STOP_DATE],[ORIG_PLANNED_COUNTER_START],[ORIG_PLANNED_COUNTER_STOP],
[CUR_PLANNED_COUNTER_START],[CUR_PLANNED_COUNTER_STOP],[ACTUAL_COUNTER_START],[ACTUAL_COUNTER_STOP],
[LATEST_REQUESTEE_NAME],[HAS_DISCUSSION],[HAS_SURVEY],[HAS_CHILD],[HAS_REF_PROC],[HAS_FILE],[ORIG_REQUESTOR_ID],
[HAS_REF_OBJ],[HAS_MONITOR],[COLOR_CODE],[LAST_REQUEST_DATE],[PRIORITY],[CHILD_STATUS],[IS_QUOTE],
[IS_QUOTE_ACCEPT], [IS_FILL], [MANAGER], [DNR_TYPE], [RECURSION_NUMBER], [REPEAT_FROM_STEP]

	FROM A_TASKS 
	WHERE ID = @copyTaskID

if @@ERROR <> 0 goto problem
INSERT INTO A_TASK_ASSIGNEE (ID,TASK_ID,PERSON_ASSIGNED,ROLE_ASSIGNED,REQUESTOR,REQUEST_DATE,ACTIVE,STATUS)
	SELECT newID(),@myTaskID,PERSON_ASSIGNED,ROLE_ASSIGNED,REQUESTOR,REQUEST_DATE,ACTIVE,STATUS
	FROM A_TASK_ASSIGNEE 
	WHERE TASK_ID = @copyTaskID
if @@ERROR <> 0 goto problem
exec A_SP_TASKS_UPDATE_DATA @myTaskID,@strNTLogin
print 'Created the Task now to copy or create all the other things'
print 'Inserting into A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED'
INSERT INTO A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED (ID,TASK_ID,ACTUAL_PART_ID)
		VALUES (newID(),@myTaskID,@subPartID)
if @@ERROR <> 0 goto problem
print 'Inserting into A_TASK_OBJECT_LINK'
INSERT INTO A_TASK_OBJECT_LINK (ID,TASK_ID,OBJECT_ID)
		VALUES (newID(),@myTaskID,@subPartID)
if @@ERROR <> 0 goto problem
UPDATE A_TASK_ORDER_INFORMATION SET 
	TASK_ID = @myTAskID
WHERE FILL_ITEM_ID = @subFillID

if @@ERROR <> 0 goto problem
INSERT INTO A_TASK_REFERENCE_PROCEDURES (ID,TASK_ID,REF_PROCEDURE)
	SELECT newID(),@myTAskID,REF_PROCEDURE FROM A_TASK_REFERENCE_PROCEDURES WHERE TASK_ID = @copyTaskID
if @@ERROR <> 0 goto problem
print 'Now we have a batch task and we need to steal all the steps from the other one'
declare @curs as CURSOR,@subTaskID as varchar(50),@newID varchar(50)
set @curs = cursor for SELECT ID FROM A_TASKS WHERE PARENT_ID = @copyTaskID
open @curs
fetch next from @curs into @subTaskID
while @@fetch_status = 0
	begin
	exec A_SP_TASK_COPY_TASK_FOR_BATCH_SPLIT @newID OUTPUT,@subTaskID,@myTaskID,@strNTLogin
	INSERT INTO A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED (ID,TASK_ID,ACTUAL_PART_ID)
		VALUES (newID(),@newID,@subPartID)
	if @@ERROR <> 0 goto problem
	INSERT INTO A_TASK_OBJECT_LINK (ID,TASK_ID,OBJECT_ID)
		VALUES (newID(),@newID,@subPartID)
	if @@ERROR <> 0 goto problem
	INSERT INTO A_TASKS_RELATION_TABLE ([ID], [PARENT_ID], [CHILD_ID], [LEV] )
		values (newID(),@myTaskID,@newID,1)
	if @@ERROR <> 0 goto problem
	fetch next from @curs into @subTaskID
	end


print 'Stole all the steps'





goto fin
problem:
print 'THERE WAS AN ERROR'
fin:
print 'Done'


