CREATE PROCEDURE dbo.A_SP_ORDER_ITEM_UPDATE_MY_BILL_TYPE
@it varchar(50)
AS
declare @myProcID varchar(50),@mySysID varchar(50),@myProdID varchar(50)
SELECT @myProdID = PRODUCT_ID FROM A_ORDER_ITEMS WHERE ID = @it
SELECT @myProcID = PROCEDURE_ID  FROM A_V_PRODUCTS_APPROVED_DATA WHERE ID = @myProdID
SELECT @mySysID = SYSTEM_ID FROM A_V_PROCEDURES_APPROVED_DATA WHERE ID = @myProcID
UPDATE A_ORDER_ITEMS SET BILL_TYPE = 
	(select case
		when @mySysID in ('SYS_PROVIDE_AND_STAY','SYS_PROVIDE_AND_CONSUMED') then 'ACT_EST'
		else 'ESTIMATE'
	end)
WHERE ID = @it

