


CREATE        PROCEDURE dbo.A_SP_DNR_FIND_TESTS_FROM_MATCHING_CASE
@ID varchar(50)
AS
create TABLE #CASES (ID varchar(50))
INSERT INTO #CASES exec dbo.A_SP_DNR_FIND_MATCHING_CASES @ID
if dbo.MD() = 1 SELECT 'CASES',* FROM #CASES c,A_TASKS t WHERE t.ID = c.ID

--Now we need to find the failing tests that we have not done on all the matching cases.
--Failing Tests will find all the tests on similar cases that were failing at one point during the case
CREATE TABLE #FAILING_TESTS 
	(PARENT_ID varchar(50),TASK_ID varchar(50),PROC_ID varchar(50),
	PROC_HiST_ID varchar(50),PROC_NAME varchar(3000))
INSERT INTO #FAILING_TESTS
	SELECT DISTINCT PARENT_TASK_ID,TASK_ID,PROCEDURE_ID,PROC_HIST_ID,PROC_NAME
	FROM A_V_DNR_TASKS_WITH_TEST_INFO
	WHERE
	IS_PASSING = 0 AND 
	TASK_ID IN (SELECT ID FROM A_TASKS WHERE PARENT_ID IN (SELECT ID FROM #CASES)) AND
	ROLL_UP_ID not in (SELECT ROLL_UP_ID FROM A_V_DNR_TASKS_WITH_TEST_INFO WHERE PARENT_TASK_ID = @ID) 

if dbo.MD() = 1 SELECT 'Failing Procs',* FROM #FAILING_TESTS

--Passing tests will find all the tests that were only passing on similar cases
CREATE TABLE #PASSING_TESTS (PARENT_ID varchar(50),TASK_ID varchar(50),PROC_ID varchar(50),PROC_HiST_ID varchar(50),PROC_NAME varchar(3000))
INSERT INTO #PASSING_TESTS
	SELECT DISTINCT PARENT_TASK_ID,TASK_ID,PROCEDURE_ID,PROC_HIST_ID,PROC_NAME
	FROM A_V_DNR_TASKS_WITH_TEST_INFO
	WHERE
	IS_PASSING = 1 AND 
	TASK_ID IN (SELECT ID FROM A_TASKS WHERE PARENT_ID IN (SELECT ID FROM #CASES)) AND
	ROLL_UP_ID not in (SELECT ROLL_UP_ID FROM A_V_DNR_TASKS_WITH_TEST_INFO WHERE PARENT_TASK_ID = @ID) 

--Remove all the passing tests that were also failing in the same DNR.  These were probably only
--passing after a repair
DELETE FROM #PASSING_TESTS WHERE PARENT_ID + '---' + PROC_ID IN (SELECT PARENT_ID + '---' + PROC_ID FROM #FAILING_TESTS)

if dbo.MD() = 1 SELECT 'PASSING PROCS',* FROM #PASSING_TESTS


CREATE TABLE #TESTS (P_ID varchar(50),P_HiST_ID varchar(50),P_NAME varchar(3000),NUM_IF_FAILING int,NUM_IF_PASSING int,RATIO float)
INSERT INTO #TESTS 
	SELECT DISTINCT PROC_ID,PROC_HIST_ID,PROC_NAME,0,0,0 FROM #PASSING_TESTS
INSERT INTO #TESTS 
	SELECT DISTINCT PROC_ID,PROC_HIST_ID,PROC_NAME,0,0,0 FROM #FAILING_TESTS
		WHERE PROC_ID NOT IN (SELECT PROC_ID FROM #PASSING_TESTS)

if dbo.MD() = 1 SELECT 'Procs before Removing mine',* FROM #PASSING_TESTS


DELETE FROM #TESTS WHERE P_ID IN
	(
	SELECT DISTINCT PROCEDURE_ID
		FROM
		A_V_DNR_TASKS_WITH_TEST_INFO
		WHERE
		DNR_ID = @ID
	)

if dbo.MD() = 1 SELECT 'Procs after Removing mine',* FROM #PASSING_TESTS


UPDATE #TESTS SET 
	NUM_IF_FAILING = (SELECT isNULL(COUNT(PARENT_ID),0) FROM #FAILING_TESTS WHERE PROC_ID = P_ID),
	NUM_IF_PASSING = (SELECT isNULL(COUNT(PARENT_ID),0) FROM #PASSING_TESTS WHERE PROC_ID = P_ID)

UPDATE #TESTS SET 
	RATIO = abs((convert(float,NUM_IF_PASSING) / (convert(float,NUM_IF_FAILING) + convert(float,NUM_IF_PASSING))) - .5)



SELECT * FROM #TESTS ORDER BY RATIO





