CREATE PROCEDURE  A_SP_ACCOUNT_GET_PART_EXCEPTIONS  
@exType varchar(50),
@ID varchar(50),
@strNTLogin varchar(50)
AS
SELECT e.*,p.NAME AS PART_NAME FROM A_ACCOUNTS_PART_EXCEPTIONS e,A_V_PART_DATA_BY_APPROVED_DATA p
WHERE e.PART_ID = p.ID AND ACCT_ID = @ID AND EX_TYPE = @exType
