
CREATE       PROCEDURE A_SP_POPFILL_EDITROLE_PARENT_ROLES
	@ID nvarchar(50),
	@strNTLogin nvarchar(50)
AS

SELECT ID AS VALUE, ROLE_NAME AS SHOW 
FROM A_V_ROLES_ASSIGNED_ROLES_TO_A_ROLE
WHERE ROLE_ASSIGNED_HISTORY_REF_ID = @ID AND RA_STATUS ='ACTIVE'


--SELECT r.NAME as SHOW, r.ID AS VALUE FROM A_ROLE_ASSIGNEE ra,A_APPROVED_ROLES r 
--WHERE 
--ra.ROLE = r.HISTORY_REF_ID 
--AND ra.ROLE_ASSIGNED = @ID 

