
CREATE  PROCEDURE dbo.A_SP_PART_SHOW_PARTS_THAT_LIST_ME_AS_EQUAL
	@objID nvarchar(50),
	@strNTLogin nvarchar(50)
as
declare @r as varchar(50)
SELECT @r = ROOT FROM A_OBJECTS WHERE ID = @objID
SELECT e.PART_ID AS ID,p.NAME + ' @ ' + p.ROOT_CO_NAME AS NAME
FROM A_PARTS_EXTERNAL_EQUALS e,A_V_PART_DATA_BY_APPROVED_DATA p
WHERE e.EQUAL_PART_ID = @r AND e.PART_ID = p.PARTS_HISTORY_ID


