
CREATE  PROCEDURE dbo.A_SP_PROCEDURE_GET_FINAL_STEP
@strProcObjID varchar(50),
@strNTLogin varchar(50)
AS
declare @procID varchar(50)
SELECT @procID = ID FROM A_PROCEDURES_HISTORY WHERE OBJECT_ID = @strProcObjID
SELECT TOP 1 ID FROM A_PROCEDURE_STEPS WHERE PROCEDURE_ID = @procID ORDER BY PRINT_ORDER DESC



