

/*
STORED PROCEDURE CALLED IN projects/editProjects.asp

*/

CREATE    PROCEDURE A_SP_POP_FILL_PROJECT_ROLES
@projectID varchar(50),
@strNTLogin nvarchar(50)
AS
SELECT * 
FROM A_V_PROJECT_ALLOWED_ROLES_DATA
WHERE PROJECT_ID =@projectID


