

CREATE  PROCEDURE DBO.A_SP_PROD_PRICE_LIST_UPDATE_CHILD_LIST
@pID varchar(50),
@apObjID varchar(50),
@CHILD_ID varchar(50)
AS
declare @par as varchar(50)
SELECT @par = ID FROM A_PROD_PRICE_LIST_HISTORY WHERE OBJECT_ID = @pID

print 'UPDATE A_PROD_PRICE_LIST_SUB_PRICE_LISTS SET CHILD = ''' + @CHILD_ID + ''' WHERE PARENT = ''' + @par + ''' 
AND APPROVED_OBJ_ID = ''' + @apObjID + ''''

UPDATE A_PROD_PRICE_LIST_SUB_PRICE_LISTS SET CHILD = @CHILD_ID WHERE PARENT = @par 
AND APPROVED_OBJ_ID = @apObjID

exec A_SP_PROD_PRICE_LIST_SET_MY_PRICE @par

