


CREATE PROCEDURE A_SP_SECURITY_LEVEL_GET_FOR_PERSON
	@rsl varchar(50) OUTPUT,
	@strNTLogin varchar(50)
AS
set @rsl = '0'
SELECT @rsl = max(isNull(SECURITY_LEVEL,0)) FROM A_V_PERSON_ROLES_WITH_SECURITY WHERE PERSON_ID = @strNTLogin






