
CREATE  PROCEDURE dbo.A_SP_PARTS_SAFETY_STOCK_GET_ONE_PERSONS_WARNINGS
@strNTLogin varchaR(50)
AS



SELECT 
--	*
	DISTINCT l.PART_ID,l.PART_NAME,l.LOCATION_ID,l.LOCATION_COMPLETE_NAME AS LOCATION_NAME,
	CUR_LEVEL,
	MIN_WARNING_LEVEL,MAX_WARNING_LEVEL,MIN_LEVEL,MAX_LEVEL,

	case 
		when(CUR_LEVEL <= MIN_LEVEL) then 'Less than the Minimum'
		when(CUR_LEVEL <= MIN_WARNING_LEVEL) then 'Less than the Min Warning level'
		when(CUR_LEVEL >= MAX_LEVEL) then 'Above the Max Level'
		when(CUR_LEVEL >= MAX_WARNING_LEVEL) then 'Above the Max Warning Level'
		else 'Error'

	end
	as STOCK_STAT,

	case 
		when(CUR_LEVEL <= MIN_LEVEL) then MIN_LEVEL
		when(CUR_LEVEL <= MIN_WARNING_LEVEL) then MIN_WARNING_LEVEL
		when(CUR_LEVEL >= MAX_LEVEL) then MAX_LEVEL
		when(CUR_LEVEL >= MAX_WARNING_LEVEL) then MAX_WARNING_LEVEL
		else 'Error'

	end
	as STOCK_WARNING_NUMBER



	FROM 
	A_V_PARTS_SAFETY_STOCK_LEVELS l
	left join A_PARTS_SAFETY_STOCK_ROLES r on l.ID = r.SAFETY_STOCK_ID
	WHERE
		l.STATUS = 'APPROVED' AND 
		r.ROLE_ID IN 
			(SELECT ROLE_ID FROM A_V_ROLES_APPROVED_WITH_PEOPLE_IDS WHERE PERSON = @strNTLogin)
		and
		(
			(CUR_LEVEL <= MIN_WARNING_LEVEL)
			OR
			(CUR_LEVEL <= MIN_LEVEL)
			OR
			(CUR_LEVEL >= MAX_WARNING_LEVEL)
			OR
			(CUR_LEVEL >= MAX_LEVEL)
		)


