CREATE PROCEDURE dbo.A_SP_PROCEDURE_STEPS_CREATE_RELATED_STEPS_FOR_ONE 
@oldStepID varchar(50)
AS
declare @curs as cursor,@stepID varchar(50)
set @curs = CURSOR FOR SELECT ID FROM A_PROCEDURE_STEPS WHERE OLD_STEP_ID = @oldStepID 
open @curs
fetch NEXT FROM @curs into @stepID
while @@fetch_status = 0
begin
	INSERT INTO A_PROCEDURE_STEPS_RELATED_STEPS (STEP_ID,REL_STEP_ID)
			VALUES (@oldStepID,@stepID)
	INSERT INTO A_PROCEDURE_STEPS_RELATED_STEPS (STEP_ID,REL_STEP_ID)
			VALUES (@stepID,@oldStepID)

	INSERT INTO A_PROCEDURE_STEPS_RELATED_STEPS (STEP_ID,REL_STEP_ID)
		SELECT @stepID,REL_STEP_ID FROM A_PROCEDURE_STEPS_RELATED_STEPS s
		WHERE STEP_ID = @oldStepID and REL_STEP_ID <> @stepID AND
		not exists
			(SELECT STEP_ID FROM A_PROCEDURE_STEPS_RELATED_STEPS 
				WHERE STEP_ID = @stepID AND REL_STEP_ID = s.REL_STEP_ID)


	INSERT INTO A_PROCEDURE_STEPS_RELATED_STEPS (STEP_ID,REL_STEP_ID)
		SELECT STEP_ID,@stepID FROM A_PROCEDURE_STEPS_RELATED_STEPS s
		WHERE REL_STEP_ID = @oldStepID and STEP_ID <> @stepID and
		not exists
			(SELECT REL_STEP_ID FROM A_PROCEDURE_STEPS_RELATED_STEPS 
				WHERE REL_STEP_ID = @stepID AND STEP_ID = s.STEP_ID)


	exec A_SP_PROCEDURE_STEPS_CREATE_RELATED_STEPS_FOR_ONE @stepID
	fetch NEXT FROM @curs into @stepID
end
close @curs

