









CREATE    procedure A_SP_PROD_PRICE_LIST_COPY_ONE
	@newObjID nvarchar(50) OUTPUT,
	@strID nvarchar(50),
	@strNTLogin nvarchar(50),
	@copyPrefix nvarchar(50)
as
--Make a new ID for the copy
declare @newID as nvarchar(50)
exec sp_getUniqueID3 @newID OUTPUT
--Insert the new one
INSERT INTO A_PROD_PRICE_LIST_HISTORY 
(ID,
[PRODUCT], 
[CUSTOMER], 
[UNIT], 
[MIN_QUANTITY], 
[UNIT_PRICE], 
[EST_UNIT_PRICE], 
[EST_LABOR_PRICE], 
[EST_PARTS_PROV_STAY], 
[EST_PARTS_PROV_TAKE_BACK], 
[EST_PARTS_CONSUMED], 
[INVOICE_FROM], 
[PRODUCTION_TIME], 
[PRODUCTION_TIME_UNIT], 
[CAPACITY], 
[CAPACITY_UNIT], 
[DRCM], 
[MODBY], 
[OBJECT_ID], 
[PRODUCT_NAME], 
[CUSTOMER_NAME],
[FOR_INDIVIDUAL_SALE]

)
SELECT 
@newID as ID,
[PRODUCT], 
[CUSTOMER], 
[UNIT], 
[MIN_QUANTITY], 
[UNIT_PRICE], 
[EST_UNIT_PRICE], 
[EST_LABOR_PRICE], 
[EST_PARTS_PROV_STAY], 
[EST_PARTS_PROV_TAKE_BACK], 
[EST_PARTS_CONSUMED], 
[INVOICE_FROM], 
[PRODUCTION_TIME], 
[PRODUCTION_TIME_UNIT], 
[CAPACITY], 
[CAPACITY_UNIT], 
getDate(), 
@strNTLogin, 
NULL, 
[PRODUCT_NAME], 
[CUSTOMER_NAME],
[FOR_INDIVIDUAL_SALE]
 FROM A_PROD_PRICE_LIST_HISTORY WHERE ID = @strID

--find out what object id the new one got
SELECT @newObjID = OBJECT_ID FROM A_PROD_PRICE_LIST_HISTORY WHERE ID = @newID
print 'The new object ID is ' + @newObjID
--Move the volume discounts over
INSERT INTO A_PROD_PRICE_LIST_VOLUME_DISC SELECT newID(),@newID,DISCOUNT,MIN_PUR_QTY,DRCM,MODBY FROM
A_PROD_PRICE_LIST_VOLUME_DISC WHERE PRICE_LIST_ID = @strID
--Move the exempted Companies over
INSERT INTO A_PROD_PRICE_LIST_EXCEPTIONS SELECT newID(),CUST_ID,@newID,DRCM,MODBY FROM
A_PROD_PRICE_LIST_EXCEPTIONS WHERE PP_LIST_ID = @strID
--Move the Special Distributions over
INSERT INTO A_PROD_PRICE_LIST_SPECIAL_DISTRIBUTIONS SELECT newID(),SPEC_ID,@newID,DRCM,MODBY FROM
A_PROD_PRICE_LIST_SPECIAL_DISTRIBUTIONS WHERE PP_LIST_ID = @strID
--Move the Special Distributions over
INSERT INTO A_PROD_PRICE_CUSTOMERS SELECT newID(),CUST_ID,@newID,DRCM,MODBY FROM
A_PROD_PRICE_CUSTOMERS WHERE PP_LIST_ID = @strID
--Move the Real Customers over
INSERT INTO A_PROD_PRICE_LIST_REAL_CUSTOMERS SELECT newID(),CUST_ID,@newID,DRCM,MODBY FROM
A_PROD_PRICE_LIST_REAL_CUSTOMERS WHERE PP_LIST_ID = @strID
--Get the Extra Cost data copied over

declare @curs CURSOR, @it varchar(50),@newECID varchar(50)
set @curs = CURSOR FOR SELECT ID FROM A_PROD_PRICE_LIST_EXTRA_COSTS WHERE PROD_PRICE_LIST = @strID
open @curs
fetch next from @curs into @it
while @@fetch_status = 0
	begin
	exec sp_GetUniqueID3 @newECID OUTPUT
	INSERT INTO A_PROD_PRICE_LIST_EXTRA_COSTS 
		(ID,PROD_PRICE_LIST,[DESCRIPTION],PRICE_LIST_TYPE,DRCM,MODBY,UNIT,UNIT_PRICE)
		SELECT
		@newECID,@newID,[DESCRIPTION],PRICE_LIST_TYPE,getDate(),@strNTLogin,UNIT,UNIT_PRICE
		FROM A_PROD_PRICE_LIST_EXTRA_COSTS where ID = @it
	INSERT INTO A_PROD_PRICE_LIST_EXTRA_COSTS_PRICE_TABLE 
		(ID,MIN_NUM,MAX_NUM,PER_UNIT_COST,FLAT_RATE,PER_UNIT_APPLIES_OVER,DRCM,MODBY,PPLEC_ID)
		SELECT 
		newID(),MIN_NUM,MAX_NUM,PER_UNIT_COST,FLAT_RATE,PER_UNIT_APPLIES_OVER,DRCM,MODBY,@newECID
		FROM A_PROD_PRICE_LIST_EXTRA_COSTS_PRICE_TABLE WHERE PPLEC_ID = @it
	fetch next from @curs into @it
	end
close @curs
deallocate @curs
		
















