


CREATE  PROCEDURE A_SP_PART_SHOW_SUB_PARTS
@ID varchar(50),
@STRNTLogin varchar(50)
AS

--print 'SELECT * FROM A_V_PARTS_GET_SUB_PART_DATA WHERE ROOT = ''' + @ID + ''''

SELECT * FROM A_V_PARTS_GET_SUB_PART_DATA WHERE ROOT = @ID



