


CREATE     procedure dbo.A_SP_ACCOUNT_INVOICES_EDIT
@newID varchar(50) OUTPUT,
@msgs varchar(2000) OUTPUT,
@ACCOUNT_ID varchar(50),
@INVOICE_ID varchar(50),
@NAME varchar(2000),
@STATUS varchar(50),
@CUST_PURCH_NUM varchar(50),
@SALES_TAX float,
@strNTLogin varchar(50)
AS
UPDATE A_ACCOUNT_INVOICES SET
NAME = @NAME,
STATUS = @STATUS
WHERE ID = @INVOICE_ID

if @SALES_TAX is not null
   UPDATE A_ACCOUNT_INVOICE_ITEMS 
	SET 
	TAX_RATE = @SALES_TAX,
	TAX = (@SALES_TAX / 100) * AMOUNT
	WHERE INVOICE_ID = @INVOICE_ID
	

exec A_SP_ACCOUNT_FIGURE_TOTALS @ACCOUNT_ID,@strNTLogin

if @CUST_PURCH_NUM is not null
	begin
	UPDATE A_ACCOUNT_INVOICE_ITEMS SET CUST_SINGLE_PO = @CUST_PURCH_NUM WHERE INVOICE_ID = @INVOICE_ID
	UPDATE A_PURCHASES_HISTORY SET CUST_PURCH_NUM = @CUST_PURCH_NUM WHERE OBJECT_ID = 
		(SELECT PURCHASE_ID FROM A_ACCOUNT_INVOICES WHERE ID = @INVOICE_ID)
	end

fin:




