CREATE PROCEDURE DBO.A_SP_TASK_GET_ADDITIONAL_REQUESTEE_LIST
@TASK_ID as varchar(50),
@strNTLogin as varchar(50)
AS
print 'Getting the additional requestee list for task = ' + @TASK_ID
SELECT p.P_ID AS REQUESTEE_ID,p.P_NAME AS REQUESTEE_NAME
	FROM A_TASK_ADDITIONAL_ASSIGNEES_LINK l, A_V_PEOPLE_BY_NTLOGIN p
	WHERE l.TASK_ID = @TASK_ID
	AND l.PERSON_ID = p.P_ID
