



CREATE   PROCEDURE A_SP_FORECAST_GET_CUSTOMERS
@ID varchar(50),
@strNTLogin varchar(50)
AS
SELECT c.NAME as NAME,c.ID AS ID FROM A_FORECAST_CUSTOMER_LIST r,A_V_COMPANIES_APPROVED_DATA c WHERE
c.ID = r.CO AND r.FORECAST_ID = @ID




