



CREATE     PROCEDURE dbo.A_SP_ACTUAL_PARTS_UPDATE_SAFETY_LEVEL_DATA
@actPartID varchar(50)
AS
declare @pID varchar(50), @lID varchar(50)
SELECT @pID = PART_ID, @lID = LOCATION 
	FROM A_O_ACTUAL_PARTS_HISTORY
	WHERE ROOT = @actPartID

declare @myQty float
SELECT @myQty = sum(QTY) FROM A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK WHERE
	PART_ID = @pID AND LOCATION = @lID AND AP_STATUS in ('ap_available','ap_in_fill','ap_in_call')

UPDATE A_PARTS_SAFETY_STOCK_LEVELS SET CUR_LEVEL = @myQty WHERE
	PART_ID = @pID AND LOCATION_ID = @lID AND STATUS LIKE 'APPROVED%'





