



CREATE   PROCEDURE A_SP_PROCEDURE_STEP_GET_PRECEDING_STEPS
@stepID nvarchar(50),
@strNTLogin nvarchar(50)
AS

SELECT PREV_STEP AS ID FROM A_PROCEDURE_STEP_PRECEDING_STEPS WHERE 
MY_STEP = @stepID


