CREATE PROCEDURE dbo.A_SP_ORDER_GET_SUPPLIER_LIST
@orderObjID varchar(50),
@strNTLogin varchar(50)
AS
declare @orderHistID varchar(50)
SELECT @orderHistID = ID FROM A_ORDERS_HISTORY WHERE OBJECT_ID = @orderObjID
SELECT DISTINCT p.SUPPLIER_ID AS SUPPLIER_ID,c.NAME AS SUPPLIER_NAME FROM
A_ORDER_ITEMS i,
A_V_PRODUCTS_APPROVED_DATA p,
A_V_COMPANIES_APPROVED_DATA c
WHERE
i.ORDER_ID = @orderHistID
AND p.ID = i.PRODUCT_ID 
AND c.ID = p.SUPPLIER_ID




