

CREATE PROCEDURE A_SP_FORECAST_ITEM_GET_FORECAST_OBJECT_ID
@ID varchar(50)
AS
declare @fID as varchar(50)
SELECT @fID = FORECAST_ID FROM A_FORECAST_ITEMS WHERE ID = @ID
SELECT OBJECT_ID FROM A_FORECASTS_HISTORY WHERE ID = @fID



