

/*
STORED PROCEDURE CALLED IN serviceCallsWorkType/editWorkType.asp
*/

CREATE  PROCEDURE DBO.A_SP_SERVICE_CALL_WORK_TYPE_UN_DELETE_ONE_WORK_TYPE 
@workTypeID nvarchar(50),
@strNTLogin nvarchar(50)
AS
UPDATE A_SERVICE_CALLS_WORK_TYPES SET STATUS = 'ACTIVE' WHERE ID = @workTypeID


