CREATE PROCEDURE dbo.A_SP_PURCHASE_SET_SUPPLIER_ID_FOR_ITEMS 
@purchaseHistID varchar(50)
AS
UPDATE A_ORDER_ITEMS SET
	SUPPLIER_ID = 
			(
			SELECT SUPPLIER_ID 
			FROM A_V_PROD_PRICE_LIST_APPROVED_DATA 
			WHERE ID = A_ORDER_ITEMS.PROD_PRICE_LIST
			),
	PROD_PRICE_LIST_HIST_ID =
			(
			SELECT HISTORY_REF_ID FROM A_PROD_PRICE_LIST WHERE ID = A_ORDER_ITEMS.PROD_PRICE_LIST
			)
WHERE PURCHASE_HIST_ID = @purchaseHistID



