


CREATE PROCEDURE A_SP_FILL_ITEM_GET_OBJECT_APPLIES_TO_DATA
	@strID nvarchar(50),
	@strNTLogin nvarchar(50)
as
declare @appObj varchar(50)
SELECT @appObj = OBJ_PROD_APPLIES_TO FROM A_V_FILLS_SEARCH WHERE ID = @strID
SELECT * FROM A_V_APPROVED_OBJECTS WHERE ID = @appObj



