

CREATE PROCEDURE [dbo].[A_SP_FILES_GET_FOR_FILL_TASKS] 
@fillID varchar(50),
@strNTLogin varchar(50)
AS
BEGIN
declare @taskID varchar(50)
SELECT @taskID = TASK_ID FROM A_TASK_ORDER_INFORMATION with (noLock) WHERE FILL_ITEM_ID = @fillID
SELECT * FROM A_V_TASK_REF_FILES WHERE TASK_ID IN (SELECT CHILD_ID FROM A_TASKS_RELATION_TABLE WHERE PARENT_ID = @taskID) AND STATUS = 'ACTIVE'
END
