version: 0.2

phases:
  install:
    commands:
      - cd ./MSR.UI/MSR.UI.Portal/
      - yarn install --frozen-lockfile
  pre_build:
    commands:
      - yarn lint
  build:
    commands:
      - npx ng build --configuration=prod
      - aws s3 cp --recursive dist/  s3://answer-portal-ui-prod
      - aws cloudfront create-invalidation --distribution-id E8747YGK29986 --paths "/*"
