//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Msr.Resources.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Msr.Resources.Templates.Emails", typeof(Emails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Msr.Services.Users.ViewModels.ClientBuyerEmailTemplateViewModel
        ///
        ///@{
        ///    Layout = null;
        ///}
        ///
        ///&lt;p&gt;Welcome &lt;strong&gt;@Model.CompanyName&lt;/strong&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;You have been invited and authorized as a Client Administrator  for the MSR-FSR Portal System for  &lt;strong&gt;@Model.CompanyName &lt;/strong&gt;.&lt;/p&gt;
        ///
        ///Please follow the link below and select a unique password to gain secure access to your Organization&apos;s User Dashboard. As a Client Administrator, you have permission to Add Users to the system for your organi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClientAdmin {
            get {
                return ResourceManager.GetString("ClientAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Msr.Services.Users.ViewModels.ClientBuyerEmailTemplateViewModel
        ///
        ///@{
        ///    Layout = null;
        ///}
        ///
        ///&lt;p&gt;Welcome &lt;strong&gt;@Model.CompanyName&lt;/strong&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;You have been invited and authorized as a Client Buyer for the MSR-FSR Portal System for  &lt;strong&gt;@Model.CompanyName &lt;/strong&gt;.&lt;/p&gt;
        ///
        ///Please follow the link below and select a unique password to gain secure access to your Organization&apos;s User Dashboard.
        ///
        ///If you need assistance or have questions, please click the Help link also located on the main n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClientBuyer {
            get {
                return ResourceManager.GetString("ClientBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Msr.Services.Users.ViewModels.ClientEngineerEmailTemplateViewModel
        ///
        ///@{
        ///    Layout = null;
        ///}
        ///
        ///&lt;p&gt;Welcome &lt;strong&gt;@Model.CompanyName&lt;/strong&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;You have been invited and authorized as a Client Engineer for the MSR-FSR Portal System for  &lt;strong&gt;@Model.CompanyName &lt;/strong&gt;.&lt;/p&gt;
        ///
        ///Please follow the link below and select a unique password to gain secure access to your Organization&apos;s User Dashboard.
        ///
        ///If you need assistance or have questions, please click the Help link also located on the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClientEngineer {
            get {
                return ResourceManager.GetString("ClientEngineer", resourceCulture);
            }
        }
    }
}
