version: 0.0
os: windows
files:
  - source: \publish\publish.zip
    destination: d:\websites\
hooks:
  BeforeInstall:
    - location: \deployment\pre.bat
  AfterInstall:
    - location: \deployment\post.bat
