version: 0.0
os: windows
files:
#  - source: \obj\octopacked\
#    destination: d:\MSRFSR\
#hooks:
#  BeforeInstall:
#    - location: \deployment\pre.bat
#  AfterInstall:
#    - location: \deployment\post.bat
