version: '3'

services:
  api:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-message:1be43534978fa661dbd9d8c9649e3a2cc62495e4
#    build:
#      context: .
#      dockerfile: MSR.Answer.MessageHub/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=QA
    restart: always
    expose:
      - "5001"
    ports:
      - "5001:5001"
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-message-dev
  messageproxy:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-mp:latest
#    build:
#      context: ./reverseproxy
#      dockerfile: Dockerfile
      args:
        - 'NGINX_CONF=localmsg'
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-messageproxy-dev

  status:
    image: nginx
#    ports:
#      - "8080:80"