version: '3'

services:
  messagehub:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-message:1be43534978fa661dbd9d8c9649e3a2cc62495e4
    expose:
      - "5002"
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=QA
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-message-dev
  status:
    image: nginx
    ports:
      - "8080:8080"
  messageproxy:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-message:Dev04
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-messageproxy-dev