version: '3'

services:
#  api:
#    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-api:1be43534978fa661dbd9d8c9649e3a2cc62495e4
#    expose:
#      - "5000"
#    ports:
#      - "5000:5000"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=QA
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: answer3
#        awslogs-region: us-west-2
#        awslogs-stream-prefix: answer3-api-dev
  processor:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-processor:1be43534978fa661dbd9d8c9649e3a2cc62495e4
    environment:
      - ASPNETCORE_ENVIRONMENT=QA
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-processor-dev
#  reverseproxy:
#    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-rp:1be43534978fa661dbd9d8c9649e3a2cc62495e4
#    ports:
#      - "80:80"
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: answer3
#        awslogs-region: us-west-2
#        awslogs-stream-prefix: answer3-rp-dev
