version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}msranswer
    build:
      context: .
      dockerfile: MSR.Answer.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "17777:80"
      #- "5001:443"
    volumes:
      #- ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  app:
    build:
      context: MSR.UI/MSR.UI.Answer
      dockerfile: Dockerfile
    ports:
      - "80:80"

