version: '3'

services:
  api:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-api:Dev19
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=QA
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-api-dev
  reverseproxy:
    image: 425480257575.dkr.ecr.us-west-2.amazonaws.com/msr-rp:Dev04
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: answer3
        awslogs-region: us-west-2
        awslogs-stream-prefix: answer3-rp-dev
