CREATE VIEW Portal_WorkOrders
AS

SELECT DISTINCT 
SUPPLIER_NAME,
SUPPLIER_ID,
HAS_FILE,
ID AS TASK_ID,NUM_SUB_TASKS,
NUM_SUB_TASKS_COMPLETE,
MY_TOT_HOURS,MY_COMP_HOURS,
CUR_STEP_TEXT,TIME_COMPLETE,
PERC_COMPLETE,
BATCH_PARENT,BATCHED,
BATCH_FILL,
FILL_ITEM_ID,
NICK_NAME,SERIAL,
PURCHASE_ID,
PURCHASE_HIST_ID,
PURCHASE_ITEM_ID,
CUSTOMER_NAME,
DUE_DATE,
ORIG_DUE_DATE,
ACTUAL_PART_ID,
ACT_PART_OBJ_ID,
ST_DATE,
PROC_ID,
CUST_ID,
START_DATE,
REQUESTEE_ID,
GROUP_REQUESTEE_ID,
PRODUCT_NAME,
CUST_PURCH_NUM,
REFERENCE_PO,
PROC_NAME,
QTY,
FILL_QTY,
STATUS,
FILL_ID,
MT_NUM,
ACTUAL_START_DATE,
ACTUAL_STOP_DATE  
FROM A_V_ENGINEER_SCREEN_DATA_WIP_ONE_STEP_Simplified t with (noLock) 
--WHERE (CUST_ID = '2' OR (  GROUP_REQUESTEE_ID IN ('','1502','1490','1498','1506','1510','1494') 
--OR  REQUESTEE_ID = '110332' OR  exists( 	  SELECT ID FROM A_TASKS ts 	
--  WHERE ts.PARENT_ID = t.ID and       (ts.REQUESTEE_ID = '110332' or ts.GROUP_REQUESTEE_ID IN ('','1502','1490','1498','1506','1510','1494') )	  )  ) )
--  AND (STATUS IN ('REQUESTED','ACCEPTED')) AND  (SERIAL LIKE '%%' OR SERIAL is NULL ) AND  (CUST_PURCH_NUM LIKE '%%' OR CUST_PURCH_NUM is NULL )
--   AND  (PROC_ID LIKE '%%' OR PROC_ID is NULL ) AND  (PRODUCT_NAME LIKE '%%' OR PRODUCT_NAME is NULL ) AND  (PURCHASE_ITEM_ID LIKE '%%' OR PURCHASE_ITEM_ID is NULL ) 
--   ORDER BY ST_DATE