
CREATE VIEW [dbo].[Portal_WorkOrderPartsWithSubPartsView]
	AS 
	SELECT 
p.Id,
p.PartName,
p.RequesteeName,
p.TaskId,
p.SupplierName,
p.PurchaseId,
p.PurchaseHistId,
p.PurchaseItemId,
p.WoItem,
p.CustomerName,
p.DueDate,
p.OrigDueDate,
p.ProcId,
p.CustId, 
p.StartDate,
p.Status, 
p.RequesteeId,
p.GroupRequesteeId,
p.ProductName,
p.CustPurchNum,
p.ReferencePo, 
p.ProcName,
p.Qty,
p.NickName,
p.Serial,
p.ActualPartId,
p.StDate, 
p.ActualStopDate,
p.ActualStartDate,
p.MtNum, 
p.BatchParent,
p.Batched,
p.BatchEdFill,
p.FillId,
p.FillQty,
p.PercComplete,
p.TimeComplete,
p.MyTotHours,
p.MyCompHours,
p.CurStepText,
p.ActPartObjId,
p.HasFile,
p.SupplierId,
p.Notes
,p.HasMonitor
,p.HasNcr
,p.Threshold
,p.CompanyPartNumber
,p.LocationName
,p.ProcObjId
,p.TotalSalePrice
,p.MaterialCost,
p.PercCompletedText,
p.TimeCompletedText,
p.Amount,
p.Purchaser,
p.CustMttn,
p.PartId,
p.FillItemId,
p.CycleCount,
SubPart.SubPartCount
FROM Portal_workOrders p 
OUTER APPLY (
SELECT COUNT(*) AS SubPartCount FROM A_V_PARTS_GET_SUB_PART_DATA SP WHERE sp.PARENT_OBJECT_ID =p.PartId
) SubPart
