CREATE VIEW dbo.Portal_PartsView
AS
SELECT       
o.LOCKED_BY AS LockedBy,
o.UNLOCKED_BY AS UnLockedBy,
o.CREATED_BY AS CreatedBy, 
o.CREATE_DATE AS CreateDate,
o.ROOT,
o.REV_INFO AS RevInfo, 
o.CREATING_CO AS CreatingCo, 
o.STATUS, o.REV, 
o.WFS_ID AS WfsId,
o.LOCKED_BY_NAME AS LockedByName,
o.CREATING_CO_NAME AS CreatingCoName, 
o.APPROVAL_ACTIVITY AS ApprovalActivity,
PH.OBJECT_ID AS ObjectId, 
PH.ID,
PH.UNIT,
PH.NAME, 
PH.PART_TYPE AS PartType, 
PH.TRACK_FROM_START AS TrackFromStart, 
PH.COMPANY, 
PH.UNIT_SHIPPING_WEIGHT AS UnitShippingWeight,
PH.COMPANY_PART_NUMBER AS CompanyPartNumber, 
PH.SUPPLIER_SEE_INSTALL_BASE AS SupplierSeeInstallBase,
PH.SUPPLIER_SEE_AVAILABILITY AS SupplierSeeAvailability, 
PH.CUSTOMER_SEE_AVAILABILITY AS CustomerSeeAvailability,
c.NAME AS CompanyName, 
PT.NAME AS PartTypeName,
PH.SPARE, 
PH.CONSUMABLE, 
PH.WEIGHT_TYPE AS WeightType, 
PH.CREATE_PROD AS CreateProd, 
PH.PRODUCT_TYPE AS ProductType, 
PH.PROC_VERB AS ProcVerb, 
PH.SUPPLIER_CO AS SupplierCo,
PARENT_CO.NAME AS ParentCoName, 
dbo.A_UNIT_TYPES.NAME AS WeightTypeName,
PH.PRICE AS Price,
isnull(STUFF((
SELECT +','+ DL.NAME+'|'+DL.LINKED_DOC_ID 
FROM A_V_DOCUMENTS_WITH_LINKED_ITEM AS DL 
WHERE DL.OBJECT_ID = o.OBJ_ID
    FOR XML PATH('')), 1, 1,''),'') AS ReferenceFiles
FROM dbo.A_PARTS_HISTORY AS PH INNER JOIN
dbo.A_OBJECTS AS o ON PH.OBJECT_ID = o.ID INNER JOIN
dbo.A_V_COMPANIES_APPROVED_DATA_QUICK AS c ON PH.COMPANY = c.ID LEFT OUTER JOIN
dbo.A_V_COMPANIES_APPROVED_DATA_QUICK AS PARENT_CO ON c.PARENT = PARENT_CO.ID LEFT OUTER JOIN
dbo.A_UNIT_TYPES ON PH.WEIGHT_TYPE = dbo.A_UNIT_TYPES.ID LEFT OUTER JOIN
dbo.A_APPROVED_PART_TYPES AS PT ON PH.PART_TYPE = PT.ROOT

GO

