Create View [dbo].[Portal_PartsView]

AS
SELECT 
Id,
Name,
COMPANY_PART_NUMBER AS CompanyPartNumber,
COMPANY_NAME AS CompanyName,
REV AS Revision,
STATUS AS Status
FROM A_O_PARTS_HISTORY 
WHERE CREATING_CO = '2'
AND   (COMPANY_PART_NUMBER LIKE '%%' OR COMPANY_PART_NUMBER is NULL )
AND  (NAME LIKE '%%' OR NAME is NULL ) 
AND  (COMPANY_NAME LIKE '%%' OR COMPANY_NAME is NULL ) 
AND STATUS IN ('CREATING','DENIED','APPROVED','APPROVED_BUT_REVISING','APPROVED_BUT_DELETING')  

GO
