CREATE VIEW [dbo].[Portal_RolesApprovedDataQuick]
	AS
SELECT dbo.A_OBJECTS.CREATING_CO as creatingCo, dbo.A_ROLES_HISTORY.NAME as Name, dbo.A_ROLES.ID as Id, dbo.A_ROLES.HISTORY_REF_ID
as HistoryRefId
FROM dbo.A_ROLES INNER JOIN
dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID INNER JOIN
dbo.A_OBJECTS ON dbo.A_ROLES_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID
