create view Portal_MonitorView
as
SELECT  TOP (100) PERCENT t.ID as Id,
t.MONITOR_TYPE as MonitorType,
t.DESCRIPTION as Description,
t.START_SYSTEM_TASK as StartSystemTask,
t.START_TYPE as StartType,
t.STOP_SYSTEM_TASK as StopSystemTask,
t.STOP_TYPE as StopType, 
t.COUNTER_OR_CLOCK as CounterOrClock,
t.CLOCK_UNIT as ClockUnit, 
t.HIGHEST_THRESHOLD as HighestThreshold,
t.HIGH_THRESHOLD as HighThreshold,
t.TARGET as Target, 
t.LOW_THRESHOLD as LowThreshold, 
t.LOWEST_THRESHOLD as LowestThreshold, 
t.SHOULD_BE as ShouldBe, 
t.OPINION as Opinion, 
t.TARGET_ANSWER_ID as TargetAnswerId,
t.RELATED_OBJECT_TYPE as RelatedObjectType,
t.RELATED_OBJECT_DESCRIPTION as RelatedObjectDescription,
t.HIDE_TARGET as HideTarget,
t.USE_RESULT as UseResult, 
t.FAIL_STOP as FailStop,
t.YES_NO_ANSWER as YesNoAnswer,
t.CORRECT_ANSWER_ID as CorrectAnswerId,
t.TEXT_TARGET as TextTarget,
t.TASK_ID as TaskId,
t.ROLL_UP_ID as RollUpId,
r.NUM_VAL as NumVal, 
r.TEXT_VAL as TextVal, 
r.MULT_CHOICE_ANSWER as MultChoiceAnswer,
r.PRINT_RESULT as PrintResult, 
r.COMMENT as Comment, 
t.CREATED_BY as CreatedBy, 
t.IS_PASSING as IsPassing, 
t.PROCEDURE_ID as ProcedureId, 
t.STEP_ID as StepId, 
t.PEOPLE_ID as PeopleId, 
t.PART_ID as PartId, 
t.OBJECT_ID as ObjectId,
t.IS_AUTO as IsAuto,
t.MY_ANSWER as MyAnswer, 
t.TOLERANCE as Tolerance,
t.RELATED_OBJECT_ID as RelatedObjectId,
t.FAIL_ACTION as FailAction, 
dbo.A_TASKS.STATUS AS  taskStatus, 
dbo.A_TASKS.ACTUAL_STOP_DATE AS TaskStopDate,
dbo.A_TASKS.PROCEDURE_ID AS TaskProcedureId, 
dbo.A_TASKS.LATEST_REQUESTEE_NAME AS WorkerName, 
dbo.A_TASKS.PARENT_ID AS TaskParent,
t.PRINT_ORDER as PrintOrder, 
t.TARGET_OBJECT_TYPE as TargetObjectType,
t.TARGET_OBJECT as TargetObject, 
t.SKIP_MODE as SkipMode,
t.ALWAYS_PASS as AlwaysPass,
t.CANT_CHANGE as CantChange, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SYS_NAME as ActualPartsApprovedDataSys,
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL as ActualPartsApprovedDataSerial, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.NICK_NAME as ActualPartsApprovedDataNickName, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.LOCATION_NAME as ActualPartsApprovedDataLocationName, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.CURRENT_OWNER_NAME as ActualPartsApprovedDataCurrentOwnerName,
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER as ActualPartsApprovedDataCompnyPartNum, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC as ActualPartsApprovedDataPartDesc,
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_TYPE_NAME as ActualPartsApprovedDataPartTypeName, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.QTY as ActualPartsApprovedDataQty,
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.NAME as ActualPartsApprovedDataName, 
dbo.A_OBJECTS.ROOT AS ObjectsRoot,
r.DRCM AS UpdatedDate
FROM            dbo.A_OBJECTS INNER JOIN
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON dbo.A_OBJECTS.ROOT = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID RIGHT OUTER JOIN
dbo.A_TASK_OBJECT_LINK ON dbo.A_OBJECTS.ID = dbo.A_TASK_OBJECT_LINK.OBJECT_ID RIGHT OUTER JOIN
dbo.A_MONITOR_TEMPLATES AS t INNER JOIN
dbo.A_TASKS ON t.TASK_ID = dbo.A_TASKS.ID ON dbo.A_TASK_OBJECT_LINK.TASK_ID = dbo.A_TASKS.ID LEFT OUTER JOIN
dbo.A_MONITOR_RESULTS AS r ON t.ID = r.MONITOR_TEMPLATE_ID
ORDER BY TaskStopDate DESC