CREATE VIEW [dbo].[Portal_WorkOrders]
AS

SELECT DISTINCT 
NEWID() AS Id,
SUPPLIER_NAME AS SupplierName,
SUPPLIER_ID AS SupplierId,
HAS_FILE AS HasFile,
HAS_MONITOR HasMonitor ,
ID AS TaskId,
NUM_SUB_TASKS AS NumSubTasks,
NUM_SUB_TASKS_COMPLETE AS NumSubTasksComplete,
MY_TOT_HOURS AS MyTotHours,
MY_COMP_HOURS AS MyCompHours,
REPLACE(REPLACE(CUR_STEP_TEXT,'<<bb>>',''),'<</bb>>','')  AS CurStepText,
TIME_COMPLETE AS TimeComplete,
PERC_COMPLETE AS PercComplete,
BATCH_PARENT AS BatchParent,
BATCHED AS Batched,
BATCH_FILL AS BatchEdFill,
FILL_ITEM_ID AS FillItemId,
NICK_NAME AS NickName,
SERIAL AS Serial,
PURCHASE_ID AS PurchaseId,
PURCHASE_HIST_ID AS PurchaseHistId,
PURCHASE_ITEM_ID PurchaseItemId,
CUSTOMER_NAME AS CustomerName,
DUE_DATE AS DueDate,
ORIG_DUE_DATE AS OrigDueDate,
ACTUAL_PART_ID AS ActualPartId,
ACT_PART_OBJ_ID AS ActPartObjId,
ST_DATE AS StDate,
PROC_ID AS ProcId,
CUST_ID AS CustId,
START_DATE AS StartDate,
REQUESTEE_ID AS RequesteeId,
GROUP_REQUESTEE_ID AS GroupRequesteeId,
PRODUCT_NAME AS ProductName,
CUST_PURCH_NUM AS CustPurchNum,
REFERENCE_PO AS ReferencePo,
PROC_NAME AS ProcName,
QTY AS Qty,
FILL_QTY AS FillQty,
STATUS AS Status,
FILL_ID AS FillId,
MT_NUM AS MtNum,
ACTUAL_START_DATE AS ActualStartDate,
ACTUAL_STOP_DATE AS ActualStopDate 
FROM A_V_ENGINEER_SCREEN_DATA_WIP_ONE_STEP_Simplified t with (noLock) 
--WHERE (CUST_ID = '2' OR (  GROUP_REQUESTEE_ID IN ('','1502','1490','1498','1506','1510','1494') 
--OR  REQUESTEE_ID = '110332' OR  exists( 	  SELECT ID FROM A_TASKS ts 	
--  WHERE ts.PARENT_ID = t.ID and       (ts.REQUESTEE_ID = '110332' or ts.GROUP_REQUESTEE_ID IN ('','1502','1490','1498','1506','1510','1494') )	  )  ) )
--  AND (STATUS IN ('REQUESTED','ACCEPTED')) AND  (SERIAL LIKE '%%' OR SERIAL is NULL ) AND  (CUST_PURCH_NUM LIKE '%%' OR CUST_PURCH_NUM is NULL )
--   AND  (PROC_ID LIKE '%%' OR PROC_ID is NULL ) AND  (PRODUCT_NAME LIKE '%%' OR PRODUCT_NAME is NULL ) AND  (PURCHASE_ITEM_ID LIKE '%%' OR PURCHASE_ITEM_ID is NULL ) 
--   ORDER BY ST_DATE

