CREATE VIEW [dbo].Portal_MonitorResults

AS
SELECT
Id,
TASK_ID AS TaskId,
MONITOR_TYPE AS MonitorType
,DESCRIPTION AS Description
,SHOULD_BE AS ShouldBe
,OPINION AS Opinion
,HIDE_TARGET AS HideTarget
,USE_RESULT AS UseResult
,FAIL_STOP AS FailStop
,YES_NO_ANSWER AS YesNoAnswer
,TEXT_VAL As TextVal
,PRINT_RESULT AS PrintResult
,COMMENT AS Comment
,IS_PASSING AS IsPassing
,MY_ANSWER AS MyAnswer
,FAIL_ACTION AS FailAction
,PRINT_ORDER AS PrintOrder
,CANT_CHANGE AS CantChange
,ALWAYS_PASS AS AlwaysPass
FROM
[dbo].A_V_MONITOR_TEMPLATES_WITH_RESULTS

--  exec A_SP_MONITOR_TEMPLATES_GET_DATA_FOR_OBJECT NULL,NULL,'111991','1618'
GO

