CREATE VIEW [dbo].Portal_CompanyView
AS

SELECT        
ID AS Id, 
EXTERNAL_ID AS ExternalId, 
NAME AS Name, 
CO_TYPE AS CoType, 
OBJECT_ID AS ObjectId, 
STATUS AS Status, 
LOCKED_BY AS LockedBy, 
UNLOCKED_BY AS UnlockedBy, 
CREATED_BY AS CreatedBy, 
CREATING_CO AS CreatingCo, 
REV AS Rev, 
WFS_ID AS WfsID, 
LOCKED_BY_NAME AS LockedByName, 
ROOT AS Root, 
CHILDREN_COUNT AS ChildrenCount, 
TOP_COMPANY AS TopCompany, 
picRecord AS PicRecord, 
ROOT_CO_NAME AS RootCoName, 
PARENT_NAME AS ParentName,
PARENT as Parent,
PHONE AS Phone,
LOCATION AS Location,
LOCATION_NAME AS LocationName,
DRCM,
isnull(STUFF((
	SELECT +','+ DL.NAME+'|'+DL.LINKED_DOC_ID 
	FROM A_V_DOCUMENTS_WITH_LINKED_ITEM AS DL 
	WHERE DL.OBJECT_ID = A_V_COMPANIES_APPROVED_DATA.OBJECT_ID
    FOR XML PATH('')), 1, 1,''),'') AS ReferenceFiles
FROM dbo.A_O_COMPANIES A_V_COMPANIES_APPROVED_DATA

GO