CREATE VIEW [dbo].Portal_MonitorResults

AS
SELECT
Id,
TASK_ID AS TaskId,
MONITOR_TYPE AS MonitorType
,DESCRIPTION AS Description
,SHOULD_BE AS ShouldBe
,OPINION AS Opinion
,HIDE_TARGET AS HideTarget
,USE_RESULT AS UseResult
,FAIL_STOP AS FailStop
,YES_NO_ANSWER AS YesNoAnswer
,TEXT_VAL As TextVal
,CASE 
WHEN MONITOR_TYPE = 'YES_NO' THEN REPLACE (REPLACE (YES_NO_ANSWER, 1, 'Yes'), 0, 'No') 
WHEN MONITOR_TYPE = 'USER_NUMBER' THEN CAST(NUM_VAL AS NVARCHAR) 
WHEN MONITOR_TYPE = 'NUMBER' THEN CAST(NUM_VAL AS NVARCHAR)
WHEN MONITOR_TYPE = 'TEXT' THEN TEXT_VAL 
ELSE PRINT_RESULT END AS PrintResult
,COMMENT AS Comment,
CASE
WHEN (MONITOR_TYPE = 'TEXT' AND (TEXT_TARGET IS NULL OR TEXT_TARGET = ''))  AND IS_PASSING  = 0 THEN  'Pass'
WHEN (MONITOR_TYPE = 'TEXT' AND (TEXT_TARGET IS NOT NULL OR TEXT_TARGET <> ''))  AND IS_PASSING  = 0 THEN  'Fail'
ELSE  REPLACE (REPLACE (IS_PASSING, 1, 'Pass'), 0, 'Fail')
END AS IsPassing
,MY_ANSWER AS MyAnswer
,FAIL_ACTION AS FailAction
,PRINT_ORDER AS PrintOrder
,CANT_CHANGE AS CantChange
,ALWAYS_PASS AS AlwaysPass
FROM
[dbo].A_V_MONITOR_TEMPLATES_WITH_RESULTS

--  exec A_SP_MONITOR_TEMPLATES_GET_DATA_FOR_OBJECT NULL,NULL,'111991','1618'
GO

