CREATE VIEW dbo.Portal_ViewHistryActualPartDetails
AS
SELECT DISTINCT 
                         ID, SORT_ID, DESCRIPTION, STATUS, REQUESTOR, CHILD_ORDER, CREATED_BY, CREATE_DATE, SYSTEM_TASK, PROCEDURE_ID, REQUESTEE_ID, GROUP_REQUESTEE_ID, ORIG_PLANNED_START_DATE, 
                         ORIG_PLANNED_STOP_DATE, CUR_PLANNED_START_DATE, CUR_PLANNED_STOP_DATE, ACTUAL_START_DATE, ACTUAL_STOP_DATE, CUR_PLANNED_COUNTER_START, LATEST_REQUESTEE_NAME, 
                         HAS_DISCUSSION, HAS_SURVEY, HAS_CHILD, HAS_REF_PROC, HAS_FILE, ORIG_REQUESTOR_ID, HAS_REF_OBJ, HAS_MONITOR, ORIG_REQUESTOR_NAME, COLOR_CODE, LAST_REQUEST_DATE, 
                         PARENT_ID, PARENT_LIST, isParent, PRIORITY, PRIORITY_NAME, COMPANY_NAME, CHILD_STATUS, PROCEDURE_STEP_ID, LAST_COMMENT_WRITER, LAST_COMMENT_DRCM, LAST_COMMENT, IS_QUOTE, 
                         IS_QUOTE_ACCEPT, IS_FILL, CO_ID, FILL_ID, PURCHASE_ITEM_ID, PURCHASE_HIST_ID, PURCHASE_ITEM_ROLE, ASSIGNEE_NAME, ASSIGNEE_ID, ASSIGNEE_STATUS
FROM            dbo.A_V_TASK_SEARCH
GO
