CREATE VIEW [dbo].[Portal_PeopleObjectSearchView]
	AS
SELECT       
p.ID,
p.NAME AS FirstName,
p.LAST_NAME AS LastName,
p.POSITION_NAME AS PositionName,
p.POSITION_ID AS OfficialPosition,
p.BOSS_NAME AS BossName,
p.BOSS_ID AS BossId,
p.COMPANY_NAME AS CompanyName,
p.LOCATION_NAME AS LocationName, 
p.PRIMARY_PHONE_NUMBER AS PrimaryPhoneNumber,
p.SECONDARY_PHONE_NUMBER AS SecondaryPhoneNumber,
ae.ADDY AS EmailAddress, 
p.SYSTEM_STATUS AS SystemStatus, 
LTRIM(STR(YEAR(p.HIRE_DATE))) + '-' + dbo.leadingZeros(LTRIM(STR(MONTH(p.HIRE_DATE))), 2) + '-' + dbo.leadingZeros(LTRIM(STR(DAY(p.HIRE_DATE))), 2) AS DateHired,
o.STATUS, o.REV, 
dbo.A_FN_FILES_SHOW_ALL_XML_DATA_FOR_OBJECT(p.OBJ_ID, 'PICTURE') AS PicRecord,
dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS RootCoName,
p.OBJ_ID AS ObjectId, 
dbo.A_PEOPLE_HISTORY.SCREEN_TYPE AS ScreenType,
dbo.A_PEOPLE_HISTORY.LANG AS LanguageId, 
dbo.A_PEOPLE_HISTORY.IS_HEAD AS IsHead,
dbo.A_PEOPLE_HISTORY.TIME_ZONE AS TimeZone, 
dbo.A_PEOPLE_HISTORY.LOGIN AS LoginId,
dbo.A_PEOPLE_HISTORY.COMPANY AS Company,
'' LockedByName,
o.ROOT,
isnull(STUFF((
	SELECT +','+ DL.NAME+'|'+DL.LINKED_DOC_ID 
	FROM A_V_DOCUMENTS_WITH_LINKED_ITEM AS DL 
	WHERE DL.OBJECT_ID = p.OBJ_ID
    FOR XML PATH('')), 1, 1,''),'') AS ReferenceFiles
FROM dbo.A_OBJECTS AS o INNER JOIN
dbo.A_PEOPLE_SEARCH_TABLE AS p ON o.ID = p.OBJ_ID INNER JOIN
dbo.A_PEOPLE_HISTORY ON p.ID = dbo.A_PEOPLE_HISTORY.ID LEFT OUTER JOIN
dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_PEOPLE_HISTORY.ROOT_COMPANY = dbo.A_V_COMPANIES_APPROVED_DATA.ID
INNER JOIN dbo.A_EMAILS ae ON dbo.A_PEOPLE_HISTORY.OBJECT_ID = ae.OBJECT_ID
GO