
CREATE VIEW [dbo].Portal_ApprovedPeople
AS
SELECT     P.ID, PH.LOGIN, PH.NAME, PH.PASSWORD, PH.BOSS, PH.SOURCE, PH.LAST_NAME AS LastName, PH.MIDDLE_NAME, PH.NICK_NAME, PH.LANG, PH.HIRE_DATE, PH.DRCM, 
                      PH.MODBY, PH.OBJECT_ID, PH.COMPANY, PH.TIME_ZONE, PH.FULL_NAME,
					   PH.SYSTEM_STATUS AS SystemStatus,
					   PH.CO_POSITION, PH.ROOT_COMPANY, 
                      ROOT_CO.NAME AS ROOT_CO_NAME, CO.NAME AS CO_NAME, dbo.A_TIME_ZONES.G_DIFF, PH.IS_HEAD, P.STATUS, PH.TOOL_BOX, PH.INFO_BOX, 
                      PH.ADV_SEARCH, PH.COLOR_KEY, PH.SCREEN_TYPE, PH.CHANGE_PASS, dbo.A_V_ROLES_APPROVED_DATA_QUICK.NAME AS POSITION_NAME, 
                      P.HISTORY_REF_ID
FROM         dbo.A_PEOPLE AS P INNER JOIN
                      dbo.A_PEOPLE_HISTORY AS PH ON P.HISTORY_REF_ID = PH.ID LEFT OUTER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA_QUICK ON PH.CO_POSITION = dbo.A_V_ROLES_APPROVED_DATA_QUICK.ID LEFT OUTER JOIN
                      dbo.A_TIME_ZONES ON PH.TIME_ZONE = dbo.A_TIME_ZONES.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA AS CO ON PH.COMPANY = CO.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA AS ROOT_CO ON PH.ROOT_COMPANY = ROOT_CO.ID
WHERE     (P.STATUS = 'APPROVED')


