

CREATE VIEW [dbo].[Protal_PendingApprovals]
AS

SELECT        
O.OBJ_TABLE AS ItemType,
WFA.Title AS ITEMTYPETITLE,
 O.OBJ_DESC AS ItemName, 
 O.ROOT AS ItemNumber, 
O.ID AS ObjectId,
O.REV AS Revision,
O.REV_INFO AS RevInfo,
wf.NAME AS WfName, 
s.NAME AS StageName, 
g.NAME AS GroupName, 
STARTER.FULL_NAME AS Initiator, 
APPROVER.FULL_NAME AS ApprovalName,
wfs.START_DATE AS DateStarted,
o.Status AS Status,
d.PERSON AS PersonId,
gs.WFS_ID AS WfsId,
gs.WF_STAGE_ID AS WfStageId, 
gs.WF_GROUP_ID AS WfGroupId,
APPROVER AS Approver,
'IN_WORKFLOW' AS NotificationType
FROM         dbo.A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS d INNER JOIN
                      dbo.A_WORKFLOW_GROUP_STARTED gs ON d.WFGS_ID = gs.ID INNER JOIN
                      dbo.A_WF_STAGES s ON gs.WF_STAGE_ID = s.ID INNER JOIN
                      dbo.A_WF_GROUPS g ON gs.WF_GROUP_ID = g.ID INNER JOIN
                      dbo.A_WORKFLOWS_STARTED wfs ON gs.WFS_ID = wfs.ID INNER JOIN
                      dbo.A_WORKFLOWS wf ON wfs.WF_ID = wf.ID INNER JOIN
                      dbo.A_APPROVED_PEOPLE APPROVER ON d.PERSON = APPROVER.ID INNER JOIN
                      dbo.A_OBJECTS O ON wfs.ID = O.WFS_ID INNER JOIN
                      dbo.A_APPROVED_PEOPLE STARTER ON wfs.STARTED_BY = STARTER.ID LEFT JOIN
					  dbo.A_WF_ACTIVITIES WFA ON WFA.ACTIVITY = O.OBJ_TABLE
WHERE O.OBJ_TABLE IN (
'A_PROCEDURES_HISTORY',
'A_PARTS_HISTORY',
'A_PART_TYPES_HISTORY',
'A_ROLES_HISTORY',
'A_PROCEDURES_HISTORY',
'A_PEOPLE_HISTORY',
'A_REGIONS_HISTORY',
'A_LOCATIONS_HISTORY',
'A_COMPANIES_HISTORY',
'A_THEORY_HISTORY',
'A_ACCOUNTS_HISTORY', --'Purchase Orders
'A_PRODUCTS_HISTORY'
)

UNION

SELECT 
o.OBJ_TABLE AS ITEM_TYPE,
WFA.Title AS ITEMTYPETITLE,
o.OBJ_DESC AS ITEM_NAME,
o.ROOT AS ITEM_NUMBER,
o.ID AS ObjectId, 
o.REV AS Revision, 
O.REV_INFO AS RevInfo,
wf.NAME AS WF_NAME,
'' AS StageName, 
'' AS GroupName, 
STARTER.FULL_NAME AS Initiator, 
'' AS ApprovalName, 
'' AS DateStarted, 
o.STATUS, 
o.LOCKED_BY AS PersonId, 
'' AS WfsId, 
'' AS WfStageId, 
'' AS WfGroupId, 
'' AS Approver, 
'CREATING' AS NotificationType
FROM A_OBJECTS o
LEFT JOIN dbo.A_WORKFLOWS_STARTED wfs ON wfs.ID = O.WFS_ID
LEFT JOIN dbo.A_WORKFLOWS wf ON wfs.WF_ID = wf.ID 
LEFT JOIN dbo.A_APPROVED_PEOPLE STARTER ON wfs.STARTED_BY = STARTER.ID 
LEFT JOIN dbo.A_WF_ACTIVITIES WFA ON WFA.ACTIVITY = O.OBJ_TABLE
WHERE o.STATUS ='CREATING' AND o.OBJ_TABLE IN (
'A_PROCEDURES_HISTORY',
'A_PARTS_HISTORY',
'A_PART_TYPES_HISTORY',
'A_ROLES_HISTORY',
'A_PROCEDURES_HISTORY',
'A_PEOPLE_HISTORY',
'A_REGIONS_HISTORY',
'A_LOCATIONS_HISTORY',
'A_COMPANIES_HISTORY',
'A_THEORY_HISTORY',
'A_ACCOUNTS_HISTORY', --'Purchase Orders
'A_PRODUCTS_HISTORY'
)

GO
GO