<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSR.Domain\MSR.Domain.csproj" />
    <ProjectReference Include="..\MSR.Infrastructure\MSR.Infrastructure.csproj" />
  </ItemGroup>

</Project>
