export enum EnumReport {
    WorkOrderPartsHistorybyPartNumber = 1,
    WorkOrderPartsHistorybySerialNumber = 5,
    SerialNumberHistorybySerialNumber = 7,
    WorkInProcessbyWorkOrder = 10,
    MonitorsHistorybyWorkOrder = 11,
    CombinedFinancialDatabyWorkOrder = 13,
    WorkOrdersNotInvoicedbyWorkOrder = 14,
    RevenuebyCustomerbyTimePeriod = 15,
    RevenuebyKitbyPartKit = 16,
    CountofKitsbyPartKit = 18,
    PartsCycleCount = 20,
    Monitors = 22,
    NCRReport = 23,
}
