/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Runtime.Serialization;

namespace MSR.Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MonitorModel
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets MonitorType
        /// </summary>
        [DataMember(Name="monitorType")]
        public string MonitorType { get; set; }

        /// <summary>
        /// Gets or Sets MonitorTypeId
        /// </summary>
        [DataMember(Name="monitorTypeId")]
        public int MonitorTypeId { get; set; }

        /// <summary>
        /// Gets or Sets Result
        /// </summary>
        [DataMember(Name="result")]
        public string Result { get; set; }

        /// <summary>
        /// Gets or Sets Passing
        /// </summary>
        [DataMember(Name="passing")]
        public bool? Passing { get; set; }

        /// <summary>
        /// Gets or Sets TaskCompleted
        /// </summary>
        [DataMember(Name="taskCompleted")]
        public DateTime? TaskCompleted { get; set; }

        /// <summary>
        /// Gets or Sets SerialNumber
        /// </summary>
        [DataMember(Name="serialNumber")]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Gets or Sets WorkerName
        /// </summary>
        [DataMember(Name="workerName")]
        public UserModel WorkerName { get; set; }

        /// <summary>
        /// HighTarget
        /// </summary>
        public float? HighTarget { get; set; }

        /// <summary>
        /// LowTarget
        /// </summary>
        public float? LowTarget { get; set; }
    }
}
