/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Runtime.Serialization;

namespace MSR.Domain.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public class WorkOrderGridSummary
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseId
        /// </summary>
        [DataMember(Name="purchaseId")]
        public int? PurchaseId { get; set; }

        /// <summary>
        /// This is a combination of: {CustomerName}-{CustomerPurchaseNumber}
        /// </summary>
        /// <value>This is a combination of: {CustomerName}-{CustomerPurchaseNumber}</value>
        [DataMember(Name="workOrderItemNumber")]
        public string WorkOrderItemNumber { get; set; }

        /// <summary>
        /// Gets or Sets CustomerName
        /// </summary>
        [DataMember(Name="customerName")]
        public string CustomerName { get; set; }

        /// <summary>
        /// Gets or Sets LocationName
        /// </summary>
        [DataMember(Name="locationName")]
        public string LocationName { get; set; }

        /// <summary>
        /// This is the serial Number from the parent part, not the child parts
        /// </summary>
        /// <value>This is the serial Number from the parent part, not the child parts</value>
        [DataMember(Name="serialNumber")]
        public string SerialNumber { get; set; }

        /// <summary>
        /// This is the Purchase Order Database Id
        /// </summary>
        /// <value>This is the Purchase Order Id</value>
        [DataMember(Name="purchaseOrderNumber")]
        public int? PurchaseOrderNumber { get; set; }

        /// <summary>
        /// This is from the parent part and not the child part
        /// </summary>
        /// <value>This is from the parent part and not the child part</value>
        [DataMember(Name="quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// Gets or Sets ScheduledStartDate
        /// </summary>
        [DataMember(Name="scheduledStartDate")]
        public DateTime? ScheduledStartDate { get; set; }

        /// <summary>
        /// Gets or Sets ScheduledEndDate
        /// </summary>
        [DataMember(Name="scheduledEndDate")]
        public DateTime? ScheduledEndDate { get; set; }

        /// <summary>
        /// Gets or Sets ActualStartDate
        /// </summary>
        [DataMember(Name="actualStartDate")]
        public DateTime? ActualStartDate { get; set; }

        /// <summary>
        /// Gets or Sets ActualEndDate
        /// </summary>
        [DataMember(Name="actualEndDate")]
        public DateTime? ActualEndDate { get; set; }

        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name="productName")]
        public string ProductName { get; set; }

        /// <summary>
        /// Gets or Sets ProcedureName
        /// </summary>
        [DataMember(Name="procedureName")]
        public string ProcedureName { get; set; }

        /// <summary>
        /// Status of Work Order, case-sensitive string
        /// </summary>
        /// <value>['Waiting Start', 'In Progress', 'Cancelled', 'Completed']</value>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// If the Work Order has an NCR, this is the disposition result of the monitor
        /// </summary>
        /// <value>If the Work Order has an NCR, this is the disposition result of the monitor</value>
        [DataMember(Name="disposition")]
        public string Disposition { get; set; }

        /// <summary>
        /// Name of the current task that is active
        /// </summary>
        /// <value>Name of the current task that is active</value>
        [DataMember(Name="currentActiveTaskName")]
        public string CurrentActiveTaskName { get; set; }

        /// <summary>
        /// Tasks Completed / Total Tasks
        /// </summary>
        /// <value>Tasks Completed / Total Tasks</value>
        [DataMember(Name="percentageOfTasksCompleted")]
        public decimal? PercentageOfTasksCompleted { get; set; }

        /// <summary>
        /// Sum of time logged per a task / Sum of the expected duration time of all tasks
        /// </summary>
        /// <value>Sum of time logged per a task / Sum of the expected duration time of all tasks</value>
        [DataMember(Name="percentageOfExpectedDurationTimeLogged")]
        public decimal? PercentageOfExpectedDurationTimeLogged { get; set; }

        /// <summary>
        /// Has NCR
        /// </summary>
        [DataMember(Name="HasNcr")]
        public bool HasNcr { get; set; }
    }
}
