/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Domain.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public class WorkOrderSummary
    {
        /// <summary>
        /// Gets or Sets WorkOrderId
        /// </summary>
        [DataMember(Name="workOrderId")]
        [Required]
        public int WorkOrderId { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrderItemNumber
        /// </summary>
        [DataMember(Name="workOrderItemNumber")]
        public string WorkOrderItemNumber { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseOrderLineNumber
        /// </summary>
        [DataMember(Name="purchaseOrderLineNumber")]
        public string PurchaseOrderLineNumber { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrderPartSerialNumber
        /// </summary>
        [DataMember(Name="workOrderPartSerialNumber")]
        public string WorkOrderPartSerialNumber { get; set; }

        /// <summary>
        /// The three possible status are [In Progress, Waiting to Start, In Progress]
        /// </summary>
        /// <value>The three possible status are [In Progress, Waiting to Start, In Progress]</value>
        [DataMember(Name="workOrderStatus")]
        [Required]
        public string WorkOrderStatus { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrderAssignedTo
        /// </summary>
        [DataMember(Name="workOrderAssignedTo")]
        public string WorkOrderAssignedTo { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrderHasNcr
        /// </summary>
        [DataMember(Name="workOrderHasNcr")]
        [Required]
        public bool WorkOrderHasNcr { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrderScheduledEndDate
        /// </summary>
        [DataMember(Name="workOrderScheduledEndDate")]
        public DateTime? WorkOrderScheduledEndDate { get; set; }
    }
}
