/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public class WorkOrderStatus
    {
        /// <summary>
        /// Gets or Sets ProductName
        /// </summary>
        [DataMember(Name="productName")]
        [Required]
        public string ProductName { get; set; }

        /// <summary>
        /// Gets or Sets PartNumber
        /// </summary>
        [DataMember(Name="partNumber")]
        [Required]
        public string PartNumber { get; set; }

        /// <summary>
        /// Gets or Sets ProcedureName
        /// </summary>
        [DataMember(Name="procedureName")]
        [Required]
        public string ProcedureName { get; set; }

        /// <summary>
        /// Gets or Sets LocationName
        /// </summary>
        [DataMember(Name="locationName")]
        [Required]
        public string LocationName { get; set; }

        /// <summary>
        /// Gets or Sets WorkOrderSummary
        /// </summary>
        [DataMember(Name="workOrderSummary")]
        public WorkOrderSummary WorkOrderSummary { get; set; }
    }
}
