

CREATE   PROCEDURE A_SP_TASK_GET_DISCUSSIONS_FOR_ONE_TASK
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting DISCUSSIONS'
SELECT p.ID AS [ID],p.SUBJECT AS NAME FROM A_DISCUSSIONS p,A_TASK_DISCUSSION_LINK r WHERE
p.ID = r.DISCUSSION_ID AND r.TASK_ID = @ID