


/*
STORED PROCEDURE CALLED IN serviceCallWorkTypes/editWorkType.asp

*/
CREATE     PROCEDURE A_SP_SERVICE_CALL_WORK_TYPE_GET_DATA_BY_ID
@workTypeID varchar(50),
@strNTLogin nvarchar(50)
AS
SELECT *
FROM A_V_SERVICE_CALL_WORK_TYPE_DATA
WHERE ID =@workTypeID