




/*
STORED PROCEDURE CALLED IN serviceCallsWorkType/editServiceCall.asp
*/
CREATE     PROCEDURE A_SP_SERVICE_CALL_GET_WORK_TYPE_LIST_WITHOUT_COMPANY 
@strNTLogin varchar(50)
AS
print 'getting my company because those are the only work types i can see'

declare @myCo as varchar(50)
SELECT @myCo = COMPANY 
FROM A_APPROVED_PEOPLE 
WHERE ID=@strNTLogin
print 'my company is' + @myCo + ''

SELECT ID, WORK_TYPE_NAME AS WORK_TYPE_NAME
FROM A_V_SERVICE_CALL_WORK_TYPE_DATA
WHERE SUPPLIER_ID IN (SELECT CHILD_COMPANY FROM A_COMPANIES_CHILD_LOOKUP_TABLE WHERE COMPANY =@myCo)
or SUPPLIER_ID = @myCo
ORDER BY WORK_TYPE_NAME