CREATE PROCEDURE DBO.A_SP_PROJECT_COPY_ONE_ITEMS_PROJ_OBJ_PURP_TAGS
@fromID varchar(50),
@fromType varchar(50),
@toID varchar(50),
@toType varchar(50),
@strNTLogin varchar(50)
AS
print 'Copying all the items over'
INSERT INTO A_OBJECT_ITEM_LINK (ID,OBJECT_ID,ITEM_ID,ITEM_TYPE,DRCM,MODBY)
	SELECT newID(),OBJECT_ID,@toID,@toType,getDate(),@strNTLogin FROM A_OBJECT_ITEM_LINK
	WHERE ITEM_ID = @fromID AND ITEM_TYPE = @fromType
INSERT INTO A_BUSINESS_PURPOSES_ITEM_LINK (ID,BUSINESS_PURPOSE_ID,ITEM_ID,ITEM_TYPE,DRCM,MODBY)
	SELECT newID(),BUSINESS_PURPOSE_ID,@toID,@toType,getDate(),@strNTLogin FROM A_BUSINESS_PURPOSES_ITEM_LINK
	WHERE ITEM_ID = @fromID AND ITEM_TYPE = @fromType
INSERT INTO A_PROJECT_ITEM_LINK (ID,PROJECT_ID,ITEM_ID,ITEM_TYPE,DRCM,MODBY)
	SELECT newID(),PROJECT_ID,@toID,@toType,getDate(),@strNTLogin FROM A_PROJECT_ITEM_LINK
	WHERE ITEM_ID = @fromID AND ITEM_TYPE = @fromType