
/*
STORED PROCEDURE CALLED IN disucssion/viewDiscussion.asp
*/

CREATE    PROCEDURE A_SP_DISCUSSION_GET_TREE_DATA
@ID nvarchar(50),
@strNTLogin nvarchar(50)
AS
SELECT * FROM A_V_DISCUSSION_GET_TREE_DATA 
WHERE ID=@ID
ORDER BY DATE_CREATED DESC