

/*
STORED PROCEDURE CALLED IN serviceCalls/editServiceCall.asp

*/
CREATE   PROCEDURE A_SP_SERVICE_CALL_GET_STATUS_HISTORY
@weeklyID varchar(50),
@strNtlogin varchar(50)
AS

SELECT * ,'WSCR_' + STATUS_CHANGED_TO AS PRINT_STAGE  
FROM A_V_SERVICE_CALL_STATUS_HISTORY_DATA
WHERE WEEKLY_ID = @weeklyID
ORDER BY DATE_CHANGED