

/*
STORED PROCEDURE CALLED IN meeting/emailMeeting.asp
*/
CREATE     PROCEDURE A_SP_MEETING_GET_INVITED_PEOPLE
@meetingID varchar(50),
@strNTLogin varchar(50)
AS
print 'inside A_SP_MEETING_EMAIL_GET_INVITED_PEOPLE'

print 'Create the temp table'
CREATE TABLE #T (
ID varchar (50)
)

print 'insert the host'
INSERT INTO #T SELECT HOST FROM A_MEETINGS WHERE ID = @meetingID
print 'insert the SCRIBE'
INSERT INTO #T SELECT SCRIBE FROM A_MEETINGS WHERE ID = @meetingID
print 'insert the TIME_KEEP'
INSERT INTO #T SELECT TIME_KEEP FROM A_MEETINGS WHERE ID = @meetingID
print 'insert the People invited'
INSERT INTO #T SELECT PEOPLE_ID FROM A_MEETING_INV_PEOPLE WHERE MEETING_ID = @meetingID
print 'insert the People invited through their roles'
INSERT INTO #T SELECT PERSON FROM A_V_ROLES_APPROVED_WITH_PEOPLE_IDS 
	WHERE ROLE_ID IN (SELECT ROLE_ID FROM A_MEETING_INV_ROLE WHERE MEETING_ID = @meetingID)
print 'insert the People invited through their companies'
INSERT INTO #T SELECT ID FROM A_V_PEOPLE_APPROVED_DATA 
	WHERE COMPANY IN (SELECT COMPANY_ID FROM A_MEETING_REALLY_INIVTED_COMPANY WHERE MEETING_ID = @meetingID)