

/*
STORED PROCEDURE CALLED IN meeting/editMeeting.asp
STORED PROCEDURE CALLED IN meeting/viewMeeting.asp
*/

CREATE       PROCEDURE A_SP_MEETING_GET_MEETING_BY_ID
@ID nvarchar(50),
@strNTLogin nvarchar(50)

AS
SELECT * ,dbo.timeToLocal(START_DATE, @strNTLogin) AS LOCAL_START_DATE,
dbo.timeToLocal(STOP_DATE, @strNTLogin) AS LOCAL_STOP_DATE,
dbo.timeToLocal(DATE_CREATED, @strNTLogin) AS LOCAL_DATE_CREATED
FROM A_V_MEETING_GET_BY_ID
WHERE ID=@ID