



CREATE     procedure A_SP_NEEDS_COPY_ONE
	@newObjID nvarchar(50) OUTPUT,
	@strID nvarchar(50),
	@strNTLogin nvarchar(50),
	@copyPrefix nvarchar(50)
as
--Make a new ID for the copy
declare @newID as nvarchar(50)
exec sp_getUniqueID3 @newID OUTPUT
--Insert the new one

INSERT INTO A_NEEDS_HISTORY 
([ID], [DESCRIPTION], [CUSTOMER_CO], [TIMEFRAME], [IMPORTANCE], 
[NEED_SIZE], [ADVERTISING_START_DATE], [ADVERTISING_STOP_DATE], [ADVERSTISE_PUBLICLY], 
[CONTACT_NAME], [CONTACT_EMAIL], [CONTACT_PHONE], [DRCM], [MODBY])
SELECT 
@newID as ID, @copyPrefix + [DESCRIPTION], 
[CUSTOMER_CO], [TIMEFRAME], [IMPORTANCE], 
[NEED_SIZE], [ADVERTISING_START_DATE], [ADVERTISING_STOP_DATE], [ADVERSTISE_PUBLICLY], 
[CONTACT_NAME], [CONTACT_EMAIL], [CONTACT_PHONE], getDate(), @strNTLogin
FROM A_NEEDS_HISTORY WHERE ID = @strID

--find out what object id the new one got
SELECT @newObjID = OBJECT_ID FROM A_NEEDS_HISTORY WHERE ID = @newID
print 'The new object ID is ' + @newObjID

print 'Copy all the companies allowed too'
INSERT INTO A_NEEDS_COMPANIES_ALLOWED (ID,NEED_ID,CO_ID,DRCM,MODBY)
SELECT newID(),@newID,CO_ID,DRCM,MODBY FROM A_NEEDS_COMPANIES_ALLOWED WHERE NEED_ID = @strID

print 'Copy all the people allowed too'
INSERT INTO A_NEEDS_PEOPLE_ALLOWED (ID,NEED_ID,PERSON_ID,DRCM,MODBY)
SELECT newID(),@newID,PERSON_ID,DRCM,MODBY FROM A_NEEDS_PEOPLE_ALLOWED WHERE NEED_ID = @strID