



CREATE        PROCEDURE A_SP_NEEDS_PUBLIC_ADS_COUNT
AS
declare @todaysPublicAdsCount int
declare @publicAdsCount int
SELECT 	@publicAdsCount = COUNT(ID) FROM A_O_NEEDS WHERE 
STATUS IN ('APPROVED','APPROVED_BUT_REVISING','APPROVED_BUT_DELETING') 
AND (GETDATE() BETWEEN ADVERTISING_START_DATE AND ADVERTISING_STOP_DATE OR 
	(ADVERTISING_START_DATE IS NULL AND ADVERTISING_STOP_DATE > GETDATE()) 
	OR 
	(ADVERTISING_STOP_DATE IS NULL AND ADVERTISING_START_DATE < GETDATE())
	)
AND ((ADVERSTISE_PUBLICLY = 'NEED_YES')
)

SELECT 	@todaysPublicAdsCount = COUNT(ID)
FROM A_O_NEEDS
WHERE (AGE < 2) AND 
STATUS IN ('APPROVED','APPROVED_BUT_REVISING','APPROVED_BUT_DELETING') 
AND 
	(GETDATE() BETWEEN ADVERTISING_START_DATE AND ADVERTISING_STOP_DATE OR 
		(ADVERTISING_START_DATE IS NULL AND ADVERTISING_STOP_DATE > GETDATE()) 
		OR 
		(ADVERTISING_STOP_DATE IS NULL AND ADVERTISING_START_DATE < GETDATE())
	)
AND ((ADVERSTISE_PUBLICLY = 'NEED_YES')
)
print '@todaysPublicAdsCount is ' + convert(varchar(50),isNull(@todaysPublicAdsCount,'NULL'))
print '@publicAdsCount is ' + convert(varchar(50),isNull(@publicAdsCount,'NULL'))
SELECT @todaysPublicAdsCount AS TODAY_COUNT, @publicAdsCount AS AD_COUNT