






/*
STORED PROCEDURE CALLED IN meeting/listAgendaMeeting.asp
*/
CREATE           PROCEDURE A_SP_MEETING_LIST_AGENDA_BY_ID_ORDER_BY_ITEM
@meetingID nvarchar(50),
@strNTLogin nvarchar(50)
AS
SELECT * FROM A_V_MEETING_GET_AGENDA 
WHERE M_ID=@meetingID
ORDER BY ITEM