



CREATE     PROCEDURE A_SP_NEEDS_GET_FILE_ATTACHMENTS
@needID nvarchar(50),
@strNTLogin nvarchar(50)
AS

SELECT  D.NAME AS SHOW, 
		D.DOC_ID AS VALUE,
		D.DESCRIPTION AS DESCRIPTION
	    FROM A_DOCUMENTS D, A_DOCUMENT_LINK DL
where   D.DOC_ID  = DL.LINKED_DOC_ID AND
		DL.OBJECT_ID = @needID