CREATE PROCEDURE DBO.A_SP_SERVICE_CALLS_SHOW_ALL_DATES_USED
AS
SELECT DISTINCT  START_DATE_STRING + ' (' + convert(nvarchar(2),datepart(ww,START_DATE_STRING)) + ')' AS  SHOW,
START_DATE_STRING AS VAL,
START_YEAR,START_MONTH,START_DAY
FROM
A_V_SERVICE_CALL_SEARCH_DATA
ORDER BY START_YEAR,START_MONTH,START_DAY