
/*
STORED PROCEDURE CALLED IN meeting/listRepondantsMeeting.asp
*/
CREATE      PROCEDURE A_SP_MEETING_GET_REPONDANT_LIST
@meetingID varchar(50),
@strNTLogin varchar(50)
AS
SELECT DISTINCT P_NAME, MEETING_ID, RESPONSE FROM A_V_MEETING_REPONDANT_DATA 
WHERE MEETING_ID = @meetingID
ORDER BY RESPONSE