USE [Answer2_Prod]
GO
/****** Object:  StoredProcedure [dbo].[Portal_GetTsrWipHistory]    Script Date: 8/14/2019 9:25:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[Portal_GetTsrWipHistory]

@fillID varchar(50)

AS

CREATE TABLE #TEMPTASKIDS (ID VARCHAR(50))
INSERT INTO #TEMPTASKIDS
SELECT TASK_ID
FROM A_TASK_ORDER_INFORMATION WITH (NOLOCK)
WHERE FILL_ITEM_ID = @FILLID

WHILE EXISTS(SELECT * FROM A_TASKS WHERE PARENT_ID COLLATE DATABASE_DEFAULT IN (SELECT ID FROM #TEMPTASKIDS) AND ID COLLATE DATABASE_DEFAULT NOT IN (SELECT ID FROM #TEMPTASKIDS))
BEGIN
	INSERT INTO #TEMPTASKIDS
	SELECT ID
	FROM A_TASKS WITH (NOLOCK)
	WHERE PARENT_ID COLLATE DATABASE_DEFAULT IN (SELECT ID FROM #TEMPTASKIDS) AND ID COLLATE DATABASE_DEFAULT NOT IN (SELECT ID FROM #TEMPTASKIDS)
END

CREATE TABLE #TEMPTASKS (SORTID INT NOT NULL IDENTITY(1, 1), ID varchar(50), ParentId varchar(50), DESCRIPTION nvarchar(2000), Title nvarchar(2000), STATUS varchar(50), REQUESTOR varchar(50), CompletedBy varchar(50), 
ActualStartDate datetime, ActualStopDate datetime, LatestRequesteeName nvarchar(200), HasFile tinyint, HasMonitor tinyint, Location nvarchar(100))

INSERT INTO #TEMPTASKS
SELECT T.ID
	, T.PARENT_ID
	--, PS.PRINT_ORDER
	--, DBO.A_FN_TASK_MAKE_PARENT_LIST(T.PARENT_ID) + T.PARENT_ID AS ORDERER
	, T.[DESCRIPTION]
	, T.TITLE
	, T.[STATUS]
	, T.REQUESTOR
	, T.COMPLETED_BY
	, T.ACTUAL_START_DATE
	, T.ACTUAL_STOP_DATE
	, T.LATEST_REQUESTEE_NAME
	, T.HAS_FILE
	, T.HAS_MONITOR
	, (SELECT NAME FROM DBO.A_LOCATIONS_HISTORY WHERE ID = (SELECT HISTORY_REF_ID FROM DBO.A_LOCATIONS WHERE ID = (SELECT SPECIFIC_LOCATION FROM DBO.A_PROCEDURE_STEPS WHERE ID = T.PROCEDURE_STEP_ID))) AS [LOCATION]
	-- , PS.*
FROM DBO.A_TASKS PARENT_TASK
RIGHT OUTER JOIN DBO.A_TASKS T ON PARENT_TASK.ID = T.PARENT_ID
INNER JOIN DBO.A_PROCEDURE_STEPS PS ON T.PROCEDURE_STEP_ID = PS.ID
WHERE T.ID IN (SELECT ID FROM #TEMPTASKIDS)
ORDER BY DBO.A_FN_TASK_MAKE_PARENT_LIST(T.ID) + T.ID, PS.PRINT_ORDER

--SELECT ID, PARENT_ID, 
--DESCRIPTION,
--Title,
--STATUS, REQUESTOR, COMPLETED_BY, ACTUAL_START_DATE, 
--ACTUAL_STOP_DATE, LATEST_REQUESTEE_NAME, HAS_FILE, HAS_MONITOR, (SELECT NAME FROM dbo.A_LOCATIONS_HISTORY WHERE ID = 
--(SELECT HISTORY_REF_ID FROM dbo.A_LOCATIONS WHERE ID = (SELECT SPECIFIC_LOCATION FROM dbo.A_PROCEDURE_STEPS WHERE ID = PROCEDURE_STEP_ID))) AS Location 
--FROM A_TASKS WHERE PARENT_ID = (SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION with (noLock) WHERE FILL_ITEM_ID = @fillID)


SELECT 
PURCH_ITEM_ID AS PurchaseItemId, 
SUP_NAME AS SupplierName, 
PROC_NAME AS ProcedureName, 
CUSTOMER_PERSON AS CustomerPerson, 
FILL_OBJ_DESC AS FillObjectDescription,
REV as Rev
FROM A_V_FILLS_SEARCH with (noLock)  WHERE ID = @fillID

SELECT * FROM #tempTasks ORDER BY SORTID

SELECT 
TASK_ID AS TaskId, 
ID,
MONITOR_TYPE AS MonitorType,
DESCRIPTION,
CASE WHEN MONITOR_TYPE = 'YES_NO' THEN REPLACE (REPLACE (YES_NO_ANSWER, 1, 'Yes'), 0, 'No') 
WHEN MONITOR_TYPE = 'USER_NUMBER' THEN CAST(NUM_VAL AS NVARCHAR) 
WHEN MONITOR_TYPE = 'NUMBER' THEN CAST(NUM_VAL AS NVARCHAR) 
WHEN MONITOR_TYPE = 'TEXT' THEN TEXT_VAL 
ELSE PRINT_RESULT END AS PrintResult, 
CASE
WHEN (MONITOR_TYPE = 'TEXT' AND (TEXT_TARGET IS NULL OR TEXT_TARGET = ''))  AND IS_PASSING  = 0 THEN  'Pass'
WHEN (MONITOR_TYPE = 'TEXT' AND (TEXT_TARGET IS NOT NULL OR TEXT_TARGET <> ''))  AND IS_PASSING  = 0 THEN  'Fail'
ELSE  REPLACE (REPLACE (IS_PASSING, 1, 'Pass'), 0, 'Fail')
END AS IsPassing,
TASK_STATUS As TaskStatus, 
YES_NO_ANSWER As YesNoAnswer, 
NUM_VAL AS NumValue, 
TEXT_VAL AS TextValue 
FROM A_V_MONITORS_WITH_TASK_AND_RESULT 
WHERE TASK_ID in (SELECT ID from #tempTasks)

DROP TABLE #TEMPTASKIDS
