CREATE PROCEDURE WIP_GET_STEP_DETAILS
	@STRNTLOGIN VARCHAR(50),
	@STEPID VARCHAR(50),
	@PHSTEPID VARCHAR(50),
	@FILLID VARCHAR(50),
	@PROCSTEPID NVARCHAR(50)
AS

EXEC DBO.PORTAL_GETSTEPDETAILS @STEPID, @PHSTEPID

EXEC DBO.A_SP_TASKS_FIND_FOR_PURCHASE_ITEM_AND_ACT_PART @FILLID, @STRNTLOGIN

EXEC DBO.A_SP_PROCEDURE_GET_REFERENCE_FILES	@PROCSTEPID, @STRNTLOGIN

SELECT L.THEORY_ID AS THEORYID
	, T.[NAME] AS THEORYNAME
	, T.[OBJECT_ID] AS OBJECTID
FROM A_V_THEORY_APPROVED_DATA T
INNER JOIN A_PROCEDURE_STEP_THEORY_LINK L ON L.THEORY_ID = T.ID 
WHERE L.PROC_STEP_ID = @STEPID

EXEC DBO.A_SP_MONITOR_TEMPLATES_GET_DATA_FOR_OBJECT NULL, NULL, @STEPID, @STRNTLOGIN

SELECT T.GROUP_REQUESTEE_ID, T.REQUESTEE_ID, T.[STATUS] FROM A_TASKS T WHERE T.ID = @STEPID

DECLARE @TASK_OBJECT_LINK_OBJECT_ID VARCHAR(50) = NULL

SELECT TOP 1 @TASK_OBJECT_LINK_OBJECT_ID = TOL.[OBJECT_ID]
FROM A_TASK_OBJECT_LINK TOL
WHERE TOL.TASK_ID = @STEPID

EXEC DBO.A_SP_ACTUAL_PARTS_SHOW_HIERARCHY NULL, @TASK_OBJECT_LINK_OBJECT_ID, @TASK_OBJECT_LINK_OBJECT_ID, @TASK_OBJECT_LINK_OBJECT_ID, @STRNTLOGIN

EXEC DBO.PORTAL_GETPURCHASEITEMDETAILS @FILLID

EXEC DBO.PORTAL_WORKITEMIMAGESBYID @STEPID

SELECT SCV.SENSORMAPPINGID, SCV.SITENAME, SCV.SENSORNAME, SCV.SENSORCURRENTVALUE FROM DBO.SENSOR_CURRENT_VALUES (NOLOCK) SCV

SELECT * FROM DBO.PORTAL_EQUIPMENTMAINTENANCEVIEW