import {
  StatusModel,
  TrackableModel,
  Role,
  FileModel,
} from '../../services/api.client.generated';

export class DocumentModel extends TrackableModel {
  id: number;
  name: string;
  revision: number;
  statusId: number;
  status: StatusModel | undefined;
  comments?: string | undefined;
  approvalDate: Date;
  roles: Role[] | undefined;
  referenceFiles: FileModel[] | undefined;
}

export class CreateDocumentRequest {}

export class UpdateDocumentRequest {}

export const gridDemoData = [
  {
    id: 1,
    name: 'Document -1',
    revision: 123,
    statusId: 1,
    status: new StatusModel({id: 1, name: "Approved"}),
    comments: 'Comment',
    approvalDate: new Date(),
    roles: undefined,
    referenceFiles: undefined,
    created: {
      accessFailedCount: 0,
      createdBy: 68,
      createdOn: "2020-07-01T18:46:35.967",
      customerId: 0,
      email: "Alexandre.Sanhaji@cmhworks.com",
      fileModel: null,
      firstName: "Alex",
      fullName: "Alex San",
      id: 154,
      isActive: true,
      isAnswerUser: true,
      lastName: "San",
      lastUpdatedBy: 154,
      lastUpdatedOn: "2020-07-05T22:16:40.993",
      locationId: 0,
      locationName: null,
      lockoutEnabled: false,
      lockoutEndDateUtc: null,
      phone: "1234567890",
      roles: [],
      securityStamp: null,
      supervisorId: null,
      supervisorName: null,
      timeZone: null,
      timeZoneId: 0,
      title: "Developer",
      userName: "asan",
      userRoleId: null,
    },
    createdBy: 154,
    createdOn: new Date("2020-09-12T00:00:00"),
    lastUpdated: {
      accessFailedCount: 0,
      createdBy: 68,
      createdOn: "2020-07-23T22:13:37.467",
      customerId: 0,
      email: "derek.otieno@cmhworks.com",
      fileModel: null,
      firstName: "Derek",
      fullName: "Derek Otieno",
      id: 165,
      isActive: true,
      isAnswerUser: true,
      lastName: "Otieno",
      lastUpdatedBy: 165,
      lastUpdatedOn: "2020-09-14T15:21:13.97",
      locationId: 0,
      locationName: null,
      lockoutEnabled: false,
      lockoutEndDateUtc: null,
      phone: "1234567890",
      roles: [],
      securityStamp: null,
      supervisorId: 45,
      supervisorName: null,
      timeZone: null,
      timeZoneId: 0,
      title: "Administrator",
      userName: "dotieno",
      userRoleId: null,
    },
    lastUpdatedBy: 165,
    lastUpdatedOn: new Date("2020-09-17T07:59:03.123"),
  },
  {
    id: 2,
    name: 'Document -2',
    revision: 123,
    statusId: 1,
    status: new StatusModel({id: 1, name: "Approved"}),
    comments: 'Comment',
    approvalDate: new Date(),
    roles: undefined,
    referenceFiles: undefined,
    created: {
      accessFailedCount: 0,
      createdBy: 68,
      createdOn: "2020-07-01T18:46:35.967",
      customerId: 0,
      email: "Alexandre.Sanhaji@cmhworks.com",
      fileModel: null,
      firstName: "Alex",
      fullName: "Alex San",
      id: 154,
      isActive: true,
      isAnswerUser: true,
      lastName: "San",
      lastUpdatedBy: 154,
      lastUpdatedOn: "2020-07-05T22:16:40.993",
      locationId: 0,
      locationName: null,
      lockoutEnabled: false,
      lockoutEndDateUtc: null,
      phone: "1234567890",
      roles: [],
      securityStamp: null,
      supervisorId: null,
      supervisorName: null,
      timeZone: null,
      timeZoneId: 0,
      title: "Developer",
      userName: "asan",
      userRoleId: null,
    },
    createdBy: 154,
    createdOn: new Date("2020-09-12T00:00:00"),
    lastUpdated: {
      accessFailedCount: 0,
      createdBy: 68,
      createdOn: "2020-07-23T22:13:37.467",
      customerId: 0,
      email: "derek.otieno@cmhworks.com",
      fileModel: null,
      firstName: "Derek",
      fullName: "Derek Otieno",
      id: 165,
      isActive: true,
      isAnswerUser: true,
      lastName: "Otieno",
      lastUpdatedBy: 165,
      lastUpdatedOn: "2020-09-14T15:21:13.97",
      locationId: 0,
      locationName: null,
      lockoutEnabled: false,
      lockoutEndDateUtc: null,
      phone: "1234567890",
      roles: [],
      securityStamp: null,
      supervisorId: 45,
      supervisorName: null,
      timeZone: null,
      timeZoneId: 0,
      title: "Administrator",
      userName: "dotieno",
      userRoleId: null,
    },
    lastUpdatedBy: 165,
    lastUpdatedOn: new Date("2020-09-17T07:59:03.123"),
  }
];
