/**
 * Parts, Procedures, and Monitors
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EnumMenuItem = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29 | 30 | 31 | 32;

export const EnumMenuItem = {
    NUMBER_0: 0 as EnumMenuItem,
    NUMBER_1: 1 as EnumMenuItem,
    NUMBER_2: 2 as EnumMenuItem,
    NUMBER_3: 3 as EnumMenuItem,
    NUMBER_4: 4 as EnumMenuItem,
    NUMBER_5: 5 as EnumMenuItem,
    NUMBER_6: 6 as EnumMenuItem,
    NUMBER_7: 7 as EnumMenuItem,
    NUMBER_8: 8 as EnumMenuItem,
    NUMBER_9: 9 as EnumMenuItem,
    NUMBER_10: 10 as EnumMenuItem,
    NUMBER_11: 11 as EnumMenuItem,
    NUMBER_12: 12 as EnumMenuItem,
    NUMBER_13: 13 as EnumMenuItem,
    NUMBER_14: 14 as EnumMenuItem,
    NUMBER_15: 15 as EnumMenuItem,
    NUMBER_16: 16 as EnumMenuItem,
    NUMBER_17: 17 as EnumMenuItem,
    NUMBER_18: 18 as EnumMenuItem,
    NUMBER_19: 19 as EnumMenuItem,
    NUMBER_20: 20 as EnumMenuItem,
    NUMBER_21: 21 as EnumMenuItem,
    NUMBER_22: 22 as EnumMenuItem,
    NUMBER_23: 23 as EnumMenuItem,
    NUMBER_24: 24 as EnumMenuItem,
    NUMBER_25: 25 as EnumMenuItem,
    NUMBER_26: 26 as EnumMenuItem,
    NUMBER_27: 27 as EnumMenuItem,
    NUMBER_28: 28 as EnumMenuItem,
    NUMBER_29: 29 as EnumMenuItem,
    NUMBER_30: 30 as EnumMenuItem,
    NUMBER_31: 31 as EnumMenuItem,
    NUMBER_32: 32 as EnumMenuItem
};
