/**
 * Parts, Procedures, and Monitors
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnumMenuItem } from './enumMenuItem';
import { MenuGroup } from './menuGroup';

export class MenuItem { 
    url?: string;
    name?: string;
    info?: string;
    icon?: string;
    orderNumber?: number;
    menuGroup?: MenuGroup;
    permissions?: Array<number>;
    enumMenuItem?: EnumMenuItem;
}