/**
 * Parts, Procedures, and Monitors
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';

export class Monitor { 
    id: number;
    description?: string;
    monitorType?: string;
    result?: string;
    passing?: boolean;
    taskCompleted?: Date;
    serialNumber?: string;
    workerName?: string;
}