/**
 * Parts, Procedures, and Monitors
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MenuItem } from './menuItem';

export class Role {
    id?: number;
    name?: string;
    isCertificationRole?: boolean;
    menus?: Array<MenuItem>;
}
