/**
 * Parts, Procedures, and Monitors
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';

export class UpdateProcedureStepRequest { 
    procedureId?: number;
    title?: string;
    text?: string;
    duration?: number;
    durationType?: string;
    printOrder?: number;
    predecessorStepId?: number;
    laborTime?: number;
    equipmentTime?: number;
    replacementCost?: number;
    utilizationTime?: number;
    usefulLife?: number;
    referenceFiles?: Array<any>;
    roles?: Array<Role>;
}