/**
 * Parts, Procedures, and Monitors
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';

export interface User { 
    id?: number;
    isActive?: boolean;
    userRoleId?: string;
    userName?: string;
    firstName?: string;
    lastName?: string;
    title?: string;
    email?: string;
    securityStamp?: string;
    phone?: string;
    supervisorId?: number;
    supervisorName?: string;
    locationId?: number;
    locationName?: string;
    isAnswerUser?: boolean;
    customerId?: number;
    lockoutEndDateUtc?: Date;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    timeZoneId?: number;
    lastUpdatedOn?: Date;
    lastUpdatedBy?: number;
    createdOn?: Date;
    createdBy?: number;
    roles?: Array<Role>;
}