version: 0.2

env:
  git-credential-helper: yes
  variables:
    ENVIRONMENT: "QA"
    ECS_CLUSTER: "answer-qa"
    ECS_CONFIG: "answer-config"
    ECS_PROFILE: "answer-profile"
    REGION: "us-west-2"
    UI_TARGET_ARN: "arn:aws:elasticloadbalancing:us-west-2:425480257575:targetgroup/qa-answer3-ui/72883ae73c748f58"
    PROJECT_UI: "qa-answer-ui"
    COMPOSE: "MSR.UI/MSR.UI.Answer/docker-compose-ui.yml"
    ECS_PARAMS: "MSR.UI/MSR.UI.Answer/ecs-params-ui.yml"
    UI_BUILD_ENV: "builddevprodsetting"
    ECR_URL: "425480257575.dkr.ecr.us-west-2.amazonaws.com"
    ECR_REPO: "msr-ui"
    TAG: 'latest'
    CONTAINER_NAME: "app"
    PORT: 80
    TIMEOUT: 15
  parameter-store:
    AWS_ACCESS_KEY_ID_PARAM: /JENKINS/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY_PARAM: /JENKINS/AWS_SECRET_ACCESS_KEY

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URL
  build:
    commands:
      - echo Git commit hash $TAG2
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd MSR.UI/MSR.UI.Answer && docker build --build-arg ENV=$UI_BUILD_ENV -t $ECR_REPO:$TAG .
      - docker tag $ECR_REPO:$TAG $ECR_URL/$ECR_REPO:$TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_URL/$ECR_REPO:$TAG
      - echo Updating $COMPOSE
      - cd ../../ && sh scripts/update_image.sh $ENVIRONMENT $TAG $COMPOSE
      - cat $COMPOSE
      - ecs-cli configure --cluster $ECS_CLUSTER --default-launch-type FARGATE --config-name $ECS_CONFIG --region $REGION
      - ecs-cli configure profile --access-key $AWS_ACCESS_KEY_ID_PARAM --secret-key $AWS_SECRET_ACCESS_KEY_PARAM --profile-name $ECS_PROFILE
      - ecs-cli compose --file $COMPOSE --ecs-params $ECS_PARAMS --project-name $PROJECT_UI service up --create-log-groups --cluster-config $ECS_CONFIG --ecs-profile $ECS_PROFILE --target-group-arn $UI_TARGET_ARN --container-name $CONTAINER_NAME --container-port $PORT --timeout $TIMEOUT
