version: 0.2

phases:
  install:
    commands:
      - cd ./MSR.UI/MSR.UI.Answer/
      - yarn install --frozen-lockfile
  pre_build:
    commands:
      - npm run lint
  build:
    commands:
      - ng build --configuration dev
      - aws s3 cp --recursive dist/  s3://answer-ui-prod
      - aws cloudfront create-invalidation --distribution-id E1C3X9JHVR2W91 --paths "/*"
