<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>7ea1ba21-5e38-4451-ad25-82ba8fe67778</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.10" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="5.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="5.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="5.3.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="V1\Extentions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSR.Application\MSR.Application.csproj" />
    <ProjectReference Include="..\MSR.Domain\MSR.Domain.csproj" />
  </ItemGroup>


</Project>
