

/*
NOTE: This stored procedure is called in 
A_SP_MEETING_UPDATE_ONE_ACTION_PLAN
A_SP_FILL_ASSIGN_PROCEDURE
Plesae update accordingly. 
*/

CREATE                                     PROCEDURE [dbo].[A_SP_TASKS_UPDATE_TASK]
@newID nvarchar(50) OUTPUT,
@messages nvarchar(2000) OUTPUT,
@ID nvarchar(50),
@PARENT_ID  varchar(50),
@REQUESTOR varchar(50),
@REQUESTEE_ID varchar(50),
@GROUP_REQUESTEE_ID varchar(50),
@DESCRIPTION nvarchar(4000),
@SYSTEM_TASK varchar(50),
@COMMENT nvarchar(4000),
@SECURITY_LEVEL varchar(50),
@COUNTER varchar(50),
@ORIG_PLANNED_START_DATE dateTime,
@ORIG_PLANNED_STOP_DATE dateTime,
@ORIG_PLANNED_COUNTER_START numeric,
@ORIG_PLANNED_COUNTER_STOP numeric,
@CUR_PLANNED_START_DATE dateTime,
@CUR_PLANNED_STOP_DATE dateTime,
@CUR_PLANNED_COUNTER_START numeric,
@CUR_PLANNED_COUNTER_STOP numeric,
@ACTUAL_START_DATE dateTime,
@ACTUAL_STOP_DATE dateTime,
@ACTUAL_COUNTER_START numeric,
@ACTUAL_COUNTER_STOP numeric,
@REF_PROC_LIST varchar(8000),
@REF_FILE_LIST varchar(8000),
@DISCUSSIONS varchar(8000),
@SURVEYS varchar(8000),
@MEETINGS varchar(8000),
@OBJECTS varchar(8000),
@COMPANIES varchar(8000),
@SYSTEM_PEOPLE_TO_EMAIL varchar(8000),
@PRIORITY smallInt,
@ADDITIONAL_ASSIGNEES varchar(8000),
@strNTLogin varchar(50)
AS
if @REQUESTOR is null
	set @REQUESTOR = @strNTLogin

--print 'Updating a Task'
--print 'Changing Dates to Grenich'
set @ORIG_PLANNED_START_DATE = dbo.timeToGrenich(@ORIG_PLANNED_START_DATE,@strNTLogin)
set @ORIG_PLANNED_STOP_DATE = dbo.timeToGrenich(@ORIG_PLANNED_STOP_DATE,@strNTLogin)
set @CUR_PLANNED_START_DATE = dbo.timeToGrenich(@CUR_PLANNED_START_DATE,@strNTLogin)
set @CUR_PLANNED_STOP_DATE = dbo.timeToGrenich(@CUR_PLANNED_STOP_DATE,@strNTLogin)
set @ACTUAL_START_DATE = dbo.timeToGrenich(@ACTUAL_START_DATE,@strNTLogin)
set @ACTUAL_STOP_DATE = dbo.timeToGrenich(@ACTUAL_STOP_DATE,@strNTLogin)

if @ID is null
	begin
	exec sp_GetUniqueID3 @newID OUTPUT
	INSERT INTO A_TASKS (ID,CREATED_BY,CREATE_DATE,STATUS,ORIG_REQUESTOR_ID) VALUES (@newID,@strNTLogin,getDate(),'CREATING',@REQUESTOR)
	set @ID = @newID
	end
else
	begin
		set @newID = @ID
	end

--Update the task with the actual data we are looking at
print 'About to update the task with the ID of ' + isNull(@newID,'NULL')
UPDATE A_TASKS SET
PARENT_ID = @PARENT_ID,
REQUESTOR = @REQUESTOR,
DESCRIPTION = @DESCRIPTION,
SYSTEM_TASK = @SYSTEM_TASK,
COMMENT = @COMMENT,
SECURITY_LEVEL = @SECURITY_LEVEL,
COUNTER = @COUNTER,
MODBY = @strNTLogin,
REQUESTEE_ID = @REQUESTEE_ID,
GROUP_REQUESTEE_ID = @GROUP_REQUESTEE_ID,
PRIORITY = @PRIORITY,
DRCM = getDate()
WHERE ID = @newID

print 'Updating Dates'
declare @taskOPSD as datetime,@taskOPSTD as datetime,@taskCPSD as datetime,@taskCPSTD as datetime,
@taskASD as datetime,@taskASTD as datetime
BEGIN TRY
SELECT @taskOPSD = ORIG_PLANNED_START_DATE, @taskOPSTD = ORIG_PLANNED_STOP_DATE,
 	@taskCPSD = CUR_PLANNED_START_DATE, @taskCPSTD = CUR_PLANNED_STOP_DATE,
	@taskASD = ACTUAL_START_DATE, @taskASTD = ACTUAL_STOP_DATE FROM A_TASKS WHERE ID = @newID
if isNull(@taskOPSD,'') <> isNull(@ORIG_PLANNED_START_DATE,'')
	begin
	exec A_SP_TASK_DATES_UPDATE @newID,'ORIG_PLANNED_START',@ORIG_PLANNED_START_DATE,@strNTLogin
	UPDATE A_TASKS SET ORIG_PLANNED_START_DATE = @ORIG_PLANNED_START_DATE WHERE ID = @newID
	end
if isNull(@taskOPSTD,'') <> isNull(@ORIG_PLANNED_STOP_DATE,'')
	begin
	exec A_SP_TASK_DATES_UPDATE @newID,'ORIG_PLANNED_STOP',@ORIG_PLANNED_STOP_DATE,@strNTLogin
	UPDATE A_TASKS SET ORIG_PLANNED_STOP_DATE = @ORIG_PLANNED_STOP_DATE WHERE ID = @newID
	end
set @CUR_PLANNED_START_DATE = isNull(@CUR_PLANNED_START_DATE,@ORIG_PLANNED_START_DATE)
if isNull(@taskCPSD,'') <> isNull(@CUR_PLANNED_START_DATE,'')
	begin
	exec A_SP_TASK_DATES_UPDATE @newID,'CUR_PLANNED_START',@CUR_PLANNED_START_DATE,@strNTLogin
	UPDATE A_TASKS SET CUR_PLANNED_START_DATE = @CUR_PLANNED_START_DATE WHERE ID = @newID
	end
set @CUR_PLANNED_STOP_DATE = isNull(@CUR_PLANNED_STOP_DATE,@ORIG_PLANNED_STOP_DATE)
if isNull(@taskCPSTD,'') <> isNull(@CUR_PLANNED_STOP_DATE,'')
	begin
	exec A_SP_TASK_DATES_UPDATE @newID,'CUR_PLANNED_STOP',@CUR_PLANNED_STOP_DATE,@strNTLogin
	UPDATE A_TASKS SET CUR_PLANNED_STOP_DATE = @CUR_PLANNED_STOP_DATE WHERE ID = @newID
	end
if isNull(@taskASD,'') <> isNull(@ACTUAL_START_DATE,'')
	begin
	exec A_SP_TASK_DATES_UPDATE @newID,'ACTUAL_START',@ACTUAL_START_DATE,@strNTLogin
	UPDATE A_TASKS SET ACTUAL_START_DATE = @ACTUAL_START_DATE WHERE ID = @newID
	end
if isNull(@taskASTD,'') <> isNull(@ACTUAL_STOP_DATE,'')
	begin
	exec A_SP_TASK_DATES_UPDATE @newID,'ACTUAL_STOP',@ACTUAL_STOP_DATE,@strNTLogin
	UPDATE A_TASKS SET ACTUAL_STOP_DATE = @ACTUAL_STOP_DATE WHERE ID = @newID
	end
END TRY
BEGIN CATCH
	print 'Error updating the dates'
END CATCH
print 'Updating Counters'
declare @cntOPSD as float,@cntOPSTD as float,@cntCPSD as float,@cntCPSTD as float,
@cntASD as float,@cntASTD as float
SELECT @cntOPSD = ORIG_PLANNED_COUNTER_START, @cntOPSTD = ORIG_PLANNED_COUNTER_STOP,
 	@cntCPSD = CUR_PLANNED_COUNTER_START, @cntCPSTD = CUR_PLANNED_COUNTER_STOP,
	@cntASD = ACTUAL_COUNTER_START, @cntASTD = ACTUAL_COUNTER_STOP FROM A_TASKS WHERE ID = @newID
if isNull(@cntOPSD,0) <> isNull(@ORIG_PLANNED_COUNTER_START,0)
	begin
	exec A_SP_TASK_COUNTER_UPDATE @newID,'ORIG_PLANNED_START',@ORIG_PLANNED_COUNTER_START,@strNTLogin
	UPDATE A_TASKS SET ORIG_PLANNED_COUNTER_START = @ORIG_PLANNED_COUNTER_START WHERE ID = @newID
	end
if isNull(@cntOPSTD,0) <> isNull(@ORIG_PLANNED_COUNTER_STOP,0)
	begin
	exec A_SP_TASK_COUNTER_UPDATE @newID,'ORIG_PLANNED_STOP',@ORIG_PLANNED_COUNTER_STOP,@strNTLogin
	UPDATE A_TASKS SET ORIG_PLANNED_COUNTER_STOP = @ORIG_PLANNED_COUNTER_STOP WHERE ID = @newID
	end
if isNull(@cntCPSD,0) <> isNull(@CUR_PLANNED_COUNTER_START,0)
	begin
	exec A_SP_TASK_COUNTER_UPDATE @newID,'CUR_PLANNED_START',@CUR_PLANNED_COUNTER_START,@strNTLogin
	UPDATE A_TASKS SET CUR_PLANNED_COUNTER_START = @CUR_PLANNED_COUNTER_START WHERE ID = @newID
	end
if isNull(@cntOPSTD,0) <> isNull(@CUR_PLANNED_COUNTER_STOP,0)
	begin
	exec A_SP_TASK_COUNTER_UPDATE @newID,'CUR_PLANNED_STOP',@CUR_PLANNED_COUNTER_STOP,@strNTLogin
	UPDATE A_TASKS SET CUR_PLANNED_COUNTER_STOP = @CUR_PLANNED_COUNTER_STOP WHERE ID = @newID
	end
if isNull(@cntASD,0) <> isNull(@ACTUAL_COUNTER_START,0)
	begin
	exec A_SP_TASK_COUNTER_UPDATE @newID,'ACTUAL_START',@ACTUAL_COUNTER_START,@strNTLogin
	UPDATE A_TASKS SET ACTUAL_COUNTER_START = @ACTUAL_COUNTER_START WHERE ID = @newID
	end
if isNull(@cntASD,0) <> isNull(@ACTUAL_COUNTER_STOP,0)
	begin
	exec A_SP_TASK_COUNTER_UPDATE @newID,'ACTUAL_STOP',@ACTUAL_COUNTER_STOP,@strNTLogin
	UPDATE A_TASKS SET ACTUAL_COUNTER_STOP = @ACTUAL_COUNTER_STOP WHERE ID = @newID
	end

--print 'Getting the latest and greatest dates and putting them in the main table'
--exec A_SP_TASK_UPDATE_ALL_DATES @newID,@strNTLogin
--print 'Getting the latest and greatest counters and putting them in the main table'
--exec A_SP_TASK_UPDATE_ALL_COUNTERS @newID,@strNTLogin

print 'Updating Reference Procedure List'
DELETE FROM A_TASK_REFERENCE_PROCEDURES WHERE TASK_ID = @newID
if @REF_PROC_LIST is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @REF_PROC_LIST,'A_TASK_REFERENCE_PROCEDURES','REF_PROCEDURE',@newID,@strNTLogin
print 'Updating Reference File List'
DELETE FROM A_TASK_REF_FILES WHERE TASK_ID = @newID
if @REF_FILE_LIST is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @REF_FILE_LIST,'A_TASK_REF_FILES','FILE_ID',@newID,@strNTLogin
print 'Updating Disussion List'
DELETE FROM A_TASK_DISCUSSION_LINK WHERE TASK_ID = @newID
if @DISCUSSIONS is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @DISCUSSIONS,'A_TASK_DISCUSSION_LINK','DISCUSSION_ID',@newID,@strNTLogin
print 'Updating Survey List'
DELETE FROM A_TASK_SURVEY_LINK WHERE TASK_ID = @newID
if @SURVEYS is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @SURVEYS,'A_TASK_SURVEY_LINK','SURVEY_ID',@newID,@strNTLogin
print 'Updating Meeting List'
DELETE FROM A_TASK_MEETING_LINK WHERE TASK_ID = @newID
if @MEETINGS is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @MEETINGS,'A_TASK_MEETING_LINK','MEETING_ID',@newID,@strNTLogin
print 'Updating Object List'
DELETE FROM A_TASK_OBJECT_LINK WHERE TASK_ID = @newID
if @OBJECTS is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @OBJECTS,'A_TASK_OBJECT_LINK','OBJECT_ID',@newID,@strNTLogin
print 'Updating Companies to View List'
DELETE FROM A_TASK_COMPANIES_TO_VIEW_LINK WHERE TASK_ID = @newID
if @COMPANIES is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @COMPANIES,'A_TASK_COMPANIES_TO_VIEW_LINK','CO_ID',@newID,@strNTLogin
print 'Updating People To Email List'
DELETE FROM A_TASK_EMAIL_PEOPLE_LINK WHERE TASK_ID = @newID
if @SYSTEM_PEOPLE_TO_EMAIL is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @SYSTEM_PEOPLE_TO_EMAIL,'A_TASK_EMAIL_PEOPLE_LINK','PERSON_ID',@newID,@strNTLogin
print 'Updating Additional Assignees'
DELETE FROM A_TASK_ADDITIONAL_ASSIGNEES_LINK WHERE TASK_ID = @newID
if @ADDITIONAL_ASSIGNEES is not null
	exec A_SP_TASK_UPDATE_RELATED_ITEM_LIST @ADDITIONAL_ASSIGNEES,'A_TASK_ADDITIONAL_ASSIGNEES_LINK','PERSON_ID',@newID,@strNTLogin
print 'Now we need to update the task_assignee table'
exec A_SP_TASK_UPDATE_TASK_ASSIGNEE @newID,@strNTLogin
print 'Calling A_SP_TASKS_UPDATE_DATA'
exec A_SP_TASKS_UPDATE_DATA @newID,@strNTLogin
print 'Calling A_SP_PROJECT_ITEM_CLEAN_UP_ALL_TAGS'
exec A_SP_PROJECT_ITEM_CLEAN_UP_ALL_TAGS @ID,'A_TASKS',@strNTLogin

if 'CREATING' = (SELECT STATUS FROM A_TASKS WHERE ID = @newID)
	begin
	print 'Calling A_SP_TASK_JUST_CREATED_DO_EVERYTHING_NECESSARY'
	exec A_SP_TASK_JUST_CREATED_DO_EVERYTHING_NECESSARY @newID,@strNTLogin
	end



declare @sql varchar(2000)
set @sql = 'exec A_SP_TASK_CHECK_RECURSION_STATUS ''' + @newID + ''''
exec A_SP_ADMIN_SQL_TO_RUN_QUE_UP @sql,@strNTLogin

