


CREATE    PROCEDURE A_SP_TASK_GET_RELATED_OBJECTS_FOR_ONE_TASK
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting Object'
SELECT p.ID AS [ID],p.OBJ_DESC AS NAME FROM A_V_APPROVED_OBJECTS p,A_TASK_OBJECT_LINK r WHERE
p.ID = r.OBJECT_ID AND r.TASK_ID = @ID



