


CREATE PROCEDURE A_SP_TASK_GET_COUNTER
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting Counter'
SELECT ID,NAME + isNULL('('+LTRIM(STR(CUR_VAL))+')','') AS COUNTER_NAME FROM A_V_COUNTERS_BY_APPROVED_ID WHERE ID = @ID 


