CREATE PROCEDURE dbo.A_SP_ZZ_EMAILS_TO_SEND_CONVERT_PEOPLE_TO_ADDRESSES
@emailID varchar(50)
AS
declare @hp tinyint,@ALL_ADDYS tinyint,@ADDY varchar(50)
SELECT @ALL_ADDYS = ALL_ADDIES,@ADDY=ADDY FROM A_Z_EMAILS_TO_SEND WHERE ID = @emailID

if @ALL_ADDYS = 1
	begin
		INSERT INTO A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO
			(ID,EMAIL_ID,EMAIL_ADDRESS,EMAIL_TYPE)
			SELECT newID(),@emailID,ADDY,EMAIL_BODY_TYPE
				FROM A_V_EMAILS_FOR_APPROVED_PEOPLE
				WHERE ID IN  
					(SELECT PERSON_ID FROM A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL 
						WHERE EMAIL_ID = @emailID)
	end
else
	begin
		INSERT INTO A_Z_EMAILS_TO_SEND_ADDRESSES_TO_SEND_TO
			(ID,EMAIL_ID,EMAIL_ADDRESS,EMAIL_TYPE)
			SELECT newID(),@emailID,ADDY,EMAIL_BODY_TYPE
				FROM A_V_EMAILS_FOR_APPROVED_PEOPLE
				WHERE ID IN  
					(SELECT PERSON_ID FROM A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL 
						WHERE EMAIL_ID = @emailID)
					and
					EMAIL_TYPE = @ADDY
	end	

