
CREATE  PROCEDURE DBO.A_SP_UNITS_GET_LIST
@strTypeList varchar(1000)
AS
CREATE TABLE #tempList(ID varchar(50))
INSERT INTO #tempList Exec A_SP_Z_SPLIT @strTypeList,','

if @strTypeList is not null
	SELECT * FROM A_UNIT_TYPES WHERE UNIT_TYPE IN(SELECT ID FROM #tempList) ORDER BY NUM 
else
	SELECT * FROM A_UNIT_TYPES ORDER BY NUM 


