

CREATE              PROCEDURE A_SP_THEORY_GET_PREVIOUS_PARAGRAPH_DATA
@TOID nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @lastParaID as nvarchar(50)
declare @strID as nvarchar(50)
SELECT @strID = ID FROM A_THEORY_HISTORY WHERE OBJECT_ID = @TOID

SELECT TOP 1 @lastParaID = ID FROM A_THEORY_PARAGRAPHS 
WHERE THEORY_ID=@strID ORDER BY PARAGRAPH_ORDER_NUMBER DESC

SELECT * FROM A_THEORY_PARAGRAPHS WHERE ID = @lastParaID

