





CREATE       PROCEDURE dbo.A_SP_Z_SYSTEM_TASKS_MAKE_ALL_FOR_EACH_COMPANY
AS
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_E_ACCESS','E-Access'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_PROVIDE_AND_CONSUMED','Provide and consume'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_PROVIDE_AND_STAY','Provide and stay'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_PROVIDE_TAKE_BACK','Provide and take back'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_RECEIVE','Receive'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_SEND','Send'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_SHIPPING','Shipping'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_REMOVE','Remove'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_INSTALL','Install'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_CONSUME','Consume'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_CREATE','Create'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_DNR','Diagnose and Repair'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_COMP_TEST','Computerized Test'
exec A_SP_Z_SYSTEM_PROCEDURE_ADD_NEW_ONE_FOR_ALL_COMPANIES 'SYS_SERIALIZE','Serialize Parts'












