

CREATE   PROCEDURE A_SP_TASK_GET_SURVEYS_FOR_ONE_TASK
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting SURVEYS'
SELECT p.ID AS [ID],p.SUBJECT AS NAME FROM A_SURVEYS p,A_TASK_SURVEY_LINK r WHERE
p.ID = r.SURVEY_ID AND r.TASK_ID = @ID


