









CREATE           procedure A_SP_THEORY_PARAGRAPH_COPY
	@oldParagraph nvarchar(50),
	@oldTheory nvarchar(50),
	@newTheory nvarchar(50),
	@strNTLogin nvarchar(50)
as
declare @newID as nvarchar(50)
exec sp_getUniqueID3 @newID OUTPUT

print 'inserting a new paragraph'
INSERT INTO A_THEORY_PARAGRAPHS([ID],[THEORY_ID],[PARAGRAPH_STYLE],[PARAGRAPH_NUMBER],[PARAGRAPH_INDENT],[PARAGRAPH_HEADING],[PARAGRAPH_SPACE_STYLE],[PARAGRAPH_TEXT],
[COMMENTS],[DRCM],[MODBY],[PRINT_ORDER],[OLD_THEORY_ID],[OLD_PARAGRAPH_ID],[PARAGRAPH_ORDER_NUMBER])
SELECT @newID,@newTheory,[PARAGRAPH_STYLE],[PARAGRAPH_NUMBER],[PARAGRAPH_INDENT],[PARAGRAPH_HEADING],[PARAGRAPH_SPACE_STYLE],[PARAGRAPH_TEXT],
[COMMENTS],getDate(),@strNTLogin,[PRINT_ORDER],@oldTheory,@oldParagraph,[PARAGRAPH_ORDER_NUMBER]
FROM A_THEORY_PARAGRAPHS WHERE ID = @oldParagraph


print 'Copying the Theory Paragraph Procedure Links'
INSERT INTO A_THEORY_PARAGRAPH_THEORY_LINK (ID,THEORY_PARAGRAPH,THEORY_LINK,DRCM,MODBY)
SELECT newID(),@newID,THEORY_LINK,getDate(),@strNTLogin FROM A_THEORY_PARAGRAPH_THEORY_LINK WHERE THEORY_PARAGRAPH = @oldParagraph

print 'Copy the ref objects'
INSERT INTO A_THEORY_PARAGRAPH_OBJECT_LINK (ID,THEORY_PARAGRAPH,OBJ_ID,DRCM,MODBY)
SELECT newID(),@newID,OBJ_ID,getDate(),@strNTLogin FROM A_THEORY_PARAGRAPH_OBJECT_LINK WHERE THEORY_PARAGRAPH = @oldParagraph

print 'copying the file links'
INSERT INTO A_THEORY_PARAGRAPH_FILE_LINK (ID,PARAGRAPH_ID,[FILE_ID],DRCM,MODBY)
SELECT newID(),@newID,[FILE_ID],getDate(),@strNTLogin FROM A_THEORY_PARAGRAPH_FILE_LINK WHERE PARAGRAPH_ID = @oldParagraph







