

CREATE        PROCEDURE [dbo].[A_SP_TASK_GET_HIEARCHY_FOR_ROOT_TASK]
@strRootCo varchar(50),
@strListToexpand varchar(8000),
@strExpandAllList varchar(8000),
@strNTLogin nvarchar(50)
AS
CREATE TABLE #tempExpandList(ID varchar(50))
INSERT INTO #tempExpandList Exec A_SP_Z_SPLIT @strListToexpand,','
CREATE TABLE #tempExpandAllList(ID varchar(50))
INSERT INTO #tempExpandAllList Exec A_SP_Z_SPLIT @strExpandAllList,','
CREATE TABLE #tempCoTree(ID varchar(50),LEV int,HAS_CHILD smallint,EXPANDED smallInt,IDENT int IDENTITY)
exec A_SP_TASK_ADD_TO_TREE_TABLE @strRootCo,0,0
SELECT 
DESCRIPTION AS DES,
case
when (CHARINDEX('<</bb>>',DESCRIPTION) > 0) then
	substring(DESCRIPTION,0,CHARINDEX('<</bb>>',DESCRIPTION)+7) 
else
	DESCRIPTION
end	
	AS STEP_TEXT_HTML,
isnull(ACTUAL_START_DATE,isNull(ACTUAL_STOP_DATE,ORIG_PLANNED_START_DATE)) AS SORT_DATE,
ACTUAL_STOP_DATE AS A_STOP,ACTUAL_START_DATE AS A_START,ORIG_PLANNED_START_DATE AS O_PLAN_START,
t.LEV AS TREE_LEVEL,t.EXPANDED AS EXPANDED,t.HAS_CHILD AS TREE_HAS_CHILD,
task.*,
pro.VERB_NAME,
pro.NAME as PROCEDURE_NAME
FROM 
#tempCoTree t
INNER JOIN A_V_TASK_SEARCH task ON task.ID = t.ID 
LEFT JOIN A_V_PROCEDURES_APPROVED_DATA pro on task.PROCEDURE_ID = pro.ID
ORDER BY IDENT
--isnull(ACTUAL_START_DATE,isNull(ACTUAL_STOP_DATE,isNull(ORIG_PLANNED_START_DATE,getDate()+40)))

--isnull(ORIG_PLANNED_START_DATE,isNull(ACTUAL_START_DATE,ACTUAL_STOP_DATE)),
--,SORT_ID

