

CREATE   PROCEDURE dbo.A_SP_THEORY_POPFILL_OBJECTS
@ID  varchar(50),
@strNTLogin varchar(50)
AS
SELECT o.OBJ_DESC as APP_OBJ_NAME,o.ID as APP_OBJECT
FROM A_OBJECTS o,A_THEORY_REFERENCE_OBJECTS l
WHERE l.THEORY_ID = @ID AND
l.OBJ_ID = o.ROOT


