





CREATE       PROCEDURE A_SP_TASK_GET_PERSONAL_COMMENT_BY_TASK_ID
@taskID nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @myRootCo varchar(50)
SELECT @myRootCo = ROOT_COMPANY FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @strNTLogin

SELECT C.ID,
		P.FULL_NAME AS WRITER_NAME ,
		DATE_CREATED AS DATE_CREATED,
		COMMENT, 
		WRITER,
		WRITER_COMPANY,
		ALLOWED_TO_VIEW  
FROM A_TASK_COMMENT C, A_V_PEOPLE_APPROVED_DATA P
WHERE TASK_ID = @taskID
AND WRITER = P.ID
AND
(
(ALLOWED_TO_VIEW = 'ALL') OR
(WRITER = @strNTLogin AND ALLOWED_TO_VIEW = 'ONLY_WRITER') OR
(@myRootCo = P.ROOT_COMPANY AND ALLOWED_TO_VIEW = 'ONLY_COMPANY')
)

ORDER BY DATE_CREATED 





