



CREATE  PROCEDURE A_SP_THEORY_COMMENTS_GET_DATA
@TOID nvarchar(50),
@strNTLogin nvarchar(50)
AS
declare @strID as nvarchar(50)
SELECT @strID = ID FROM A_THEORY_HISTORY WHERE OBJECT_ID = @TOID
SELECT * FROM A_THEORY_COMMENTS WHERE THEORY_HIST_ID = @strID ORDER BY LOC,PRINT_ORDER


