

CREATE   PROCEDURE A_SP_TASK_GET_PEOPLE_TO_EMAIL
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting People To Email'
SELECT p.ID AS [ID],p.FULL_NAME AS NAME FROM A_APPROVED_PEOPLE p,A_TASK_EMAIL_PEOPLE_LINK r WHERE
p.ID = r.PERSON_ID AND r.TASK_ID = @ID


