CREATE PROCEDURE dbo.A_SP_ZZ_EMAIL_ADD_PERSON
@ID varchar(50),
@PERSON_ID varchar(50),
@PAGE tinyInt,
@strNTLogin varchar(50)
AS
INSERT INTO A_Z_EMAILS_TO_SEND_PERSON_TO_EMAIL 
	(ID,EMAIL_ID,PERSON_ID,DRCM,MODBY,PAGE)
	VALUES 
	(newID(),@ID,@PERSON_ID,getDate(),@strNTLogin,@PAGE)

