CREATE PROCEDURE dbo.A_SP_TASKS_FOR_PURCH_ITEM_AND_PART_SHOW_ACTIVE_TASKS
@purchItem varchar(50),
@actPart varchar(50)
AS
create TABLE #tempTasks (ID varchar(50))
INSERT INTO #tempTasks 
	SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WHERE PURCHASE_ITEM_ID = @purchItem
INSERT INTO #tempTasks 
	SELECT ID FROM A_TASKS WHERE PARENT_ID IN 
	(SELECT ID FROM #tempTasks)

create TABLE #tempTasks2 (ID varchar(50))
if @actPart is not null
	begin
	INSERT INTO #tempTasks2
		SELECT TASK_ID FROM A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED WHERE ACTUAL_PART_ID = @actPart
	INSERT INTO #tempTasks2
		SELECT ID FROM A_TASKS WHERE PARENT_ID IN 
		(SELECT ID FROM #tempTasks2)
	end
else
	INSERT INTO #tempTasks2	SELECT ID FROM #tempTasks
	

SELECT DISTINCT 
[PARENT_ID], [STEP_ID], [DESCRIPTION], [STATUS], [REQUESTOR], [COMPLETED_BY], [PH_STEP_ID], 
[PRINT_ORDER], [RECURSION_NUMBER], [HAS_SURVEY], [HAS_CHILD], [HAS_REF_PROC], [HAS_FILE], 
[SYSTEM_TASK], [HAS_MONITOR] 
FROM A_V_TASKS_WITH_PROCEDURE_STEP_DATA 
	WHERE STEP_ID IN (SELECT t1.ID FROM #tempTasks t1,#tempTasks2 t2 WHERE t1.ID = t2.ID)
	AND STATUS IN ('REQUESTED','ACCEPTED')
ORDER BY PRINT_ORDER

