



CREATE      PROCEDURE A_SP_THEORY_GET_ROLES_TO_VIEW
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting Roles To View'
SELECT r.ID AS [ROLE_ID],r.NAME AS ROLE_NAME FROM A_APPROVED_ROLES r,A_THEORY_ROLES_ALLOWED t WHERE
r.ID = t.ROLE_ID AND t.THEORY_ID = @ID




