CREATE PROCEDURE [dbo].[A_SP_WF_ADD_STAGE_TO_WF]
	@STAGE_ID NVARCHAR(50),
	@WF_ID NVARCHAR(50),
	@NUM NUMERIC,
	@STRNTLOGIN NVARCHAR(50)
AS

IF @WF_ID IS NOT NULL
BEGIN

	SELECT @NUM = ISNULL(MAX(NUM), 0) + 1
	FROM A_WORKFLOW_STAGE_LINK
	WHERE WF_ID = @WF_ID
	
	INSERT INTO A_WORKFLOW_STAGE_LINK
	(WF_ID,WF_STAGE_ID,NUM,DRCM,MODBY)
	VALUES
	(@WF_ID,@STAGE_ID,@NUM,GETDATE(),@STRNTLOGIN)
	
END
ELSE
BEGIN
	SELECT 'NO ID TRYING TO INSERT STAGE ' + @STAGE_ID + ' INTO WF ' + @WF_ID + '.' AS ERROR
END

SELECT '' AS ERROR

GO








