



CREATE    PROCEDURE A_SP_THEORY_PARAGRAPH_GET_REFERENCE_FILES
	@theoryParagraphID nvarchar(50),
	@strNTLogin nvarchar(50)
AS

SELECT *,NAME AS SHOW, DOC_ID AS VALUE FROM A_V_THEORY_PARAGRAPH_DOCUMENT_DATA WHERE PARAGRAPH_ID = @theoryParagraphID






