

CREATE   PROCEDURE dbo.A_SP_THEORY_PARAGRAPH_GET_REF_OBJECTS
@ID  varchar(50),
@strNTLogin varchar(50)
AS
SELECT o.OBJ_DESC as APP_OBJ_NAME,o.ID as APP_OBJECT
FROM A_OBJECTS o,A_THEORY_PARAGRAPH_OBJECT_LINK l
WHERE l.THEORY_PARAGRAPH = @ID AND
l.OBJ_ID = o.ROOT


