CREATE PROCEDURE dbo.A_SP_ZZ_EMAILS_TO_SEND_CONVERT_ROLES_TO_PEOPLE
@emailID varchar(50)
AS
INSERT INTO A_Z_EMAILS_TO_SEND_PEOPLE_TO_EMAIL 
	(ID,PERSON_ID,EMAIL_ID,DRCM,MODBY)
	SELECT newID(),PERSON,@emailID,getDate(),'RoleConvert'
		FROM A_APPROVED_ROLE_ASSIGNEES
		WHERE ROLE_ID IN 
			(SELECT ROLE_ID FROM A_Z_EMAILS_TO_SEND_ROLES_TO_EMAIL 
				WHERE EMAIL_ID = @emailID)

