






CREATE      PROCEDURE A_SP_TASK_UPDATE_ALL_COUNTERS
@taskID varchar(50),
@strNTLogin varchar(50)
AS
declare @o1 as numeric
declare @o2 as numeric
declare @p1 as numeric
declare @p2 as numeric
declare @a1 as numeric
declare @a2 as numeric
declare @counterID as varchar(50)
declare @counterName as nvarchar(200)

print 'Updating all the counters'

SELECT @o1 = VAL FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID AND COUNTER_TYPE = 'ORIG_PLANNED_START' AND IS_CURRENT = 1
SELECT @o2 = VAL FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID AND COUNTER_TYPE = 'ORIG_PLANNED_STOP'  AND IS_CURRENT = 1
SELECT @p1 = VAL FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID AND COUNTER_TYPE = 'CUR_PLANNED_START'  AND IS_CURRENT = 1
SELECT @p2 = VAL FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID AND COUNTER_TYPE = 'CUR_PLANNED_STOP'  AND IS_CURRENT = 1
SELECT @a1 = VAL FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID AND COUNTER_TYPE = 'ACTUAL_START'  AND IS_CURRENT = 1
SELECT @a2 = VAL FROM A_TASK_COUNTERS WHERE TASK_ID = @taskID AND COUNTER_TYPE = 'ACTUAL_STOP'  AND IS_CURRENT = 1

SELECT @counterID = COUNTER_ID FROM A_V_TASK_EDIT_DATA WHERE ID = @taskID
SELECT @counterName = NAME FROM A_V_COUNTERS_BY_APPROVED_ID WHERE ID = @counterID





UPDATE A_TASKS SET
COUNTER_NAME = @counterName,
ORIG_PLANNED_COUNTER_START = @o1,
ORIG_PLANNED_COUNTER_STOP = @o2,
CUR_PLANNED_COUNTER_START = @p1,
CUR_PLANNED_COUNTER_STOP = @p2,
ACTUAL_COUNTER_START = @a1,
ACTUAL_COUNTER_STOP = @a2
WHERE ID = @taskID









