

CREATE   PROCEDURE A_SP_TASK_GET_REF_PROCEDURES_FOR_ONE_TASK
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting Ref Proedures'
SELECT p.ID AS ID,p.NAME AS NAME FROM A_APPROVED_PROCEDURES p,A_TASK_REFERENCE_PROCEDURES r WHERE
p.ID = r.REF_PROCEDURE AND r.TASK_ID = @ID


