


CREATE           PROCEDURE [dbo].[A_SP_TASKS_FIND_FOR_PURCHASE_ITEM_AND_ACT_PART]
@fillID varchar(50),
@strNTLogin varchar(50)
AS
create TABLE #tempTasks (ID varchar(50))
INSERT INTO #tempTasks 
	SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION with (noLock) WHERE FILL_ITEM_ID = @fillID
	
while exists(SELECT * FROM 	A_TASKS WHERE PARENT_ID in (SELECT ID FROM #tempTasks) and ID not in (SELECT ID FROM #tempTasks))
begin
	INSERT INTO #tempTasks 
		SELECT ID FROM A_TASKS with (noLock) WHERE PARENT_ID IN 
		(SELECT ID FROM #tempTasks) and ID not in (SELECT ID FROM #tempTasks)
end


SELECT DISTINCT 
 dbo.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID as ORDERER,[PARENT_ID], [STEP_ID], [DESCRIPTION], [STATUS], [REQUESTOR], [COMPLETED_BY],[PROC_HIST_ID], [PH_STEP_ID], 
[PRINT_ORDER], [RECURSION_NUMBER], [HAS_SURVEY], [HAS_CHILD], [HAS_REF_PROC], [HAS_FILE], 
[SYSTEM_TASK], [HAS_MONITOR], [REQUESTEE_ID], [GROUP_REQUESTEE_ID],
CHILD_STATUS, LATEST_REQUESTEE_NAME
FROM A_V_TASKS_WITH_PROCEDURE_STEP_DATA  with (noLock) 
	WHERE STEP_ID IN (SELECT t1.ID FROM #tempTasks t1)
ORDER BY dbo.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID, PRINT_ORDER










