

CREATE   PROCEDURE A_SP_TASK_GET_COMPANIES_TO_VIEW
@ID nvarchar(50),
@strNTLogin varchar(50)
AS
print 'Getting Companies To View'
SELECT p.ID AS [ID],p.NAME AS NAME FROM A_APPROVED_COMPANIES p,A_TASK_COMPANIES_TO_VIEW_LINK r WHERE
p.ID = r.CO_ID AND r.TASK_ID = @ID


