CREATE PROCEDURE DBO.A_TASK_FINISH
@ID varchar(50),
@strNTLogin varchar(50)
AS
UPDATE A_TASKS SET STATUS = 'FINISHED' WHERE ID = @ID
UPDATE A_TASK_ASSIGNEE SET STATUS = 'FINISHED' WHERE TASK_ID = @ID AND ACTIVE = 1
exec A_SP_TASK_JUST_FINISHED_DO_EVERYTHING_NECESSARY @ID,@strNTLogin
exec A_SP_TASK_SEND_EMAIL_UPDATE @ID,'finished',@strNTLogin

