

CREATE   PROCEDURE dbo.A_Z_UNIT_TYPES_CREATE_ONE
@UNIT_TYPE varchar(50),
@ID varchar(50),
@NAME varchar(50),
@num smallint
AS
INSERT INTO A_UNIT_TYPES (ID,NAME,DRCM,MODBY,NUM,UNIT_TYPE)
VALUES (@ID,@NAME,getdate(),'Sys',@num,@UNIT_TYPE)


