CREATE    PROCEDURE dbo.A_Z_MD_ON
AS
if not( exists (SELECT * FROM A_ADMIN_CONFIGURATION WHERE NAME = 'SP_DEBUG'))
	INSERT INTO A_ADMIN_CONFIGURATION (ID,NAME,VAL)	VALUES (newID(),'SP_DEBUG','1')
UPDATE A_ADMIN_CONFIGURATION SET VAL = '1' WHERE NAME = 'SP_DEBUG'



