CREATE PROCEDURE dbo.A_Z_PROCEDURE_STEP_DESTINATION_CREATE_ONE
@ID varchar(50),
@NAME varchar(50),
@num smallint
AS
INSERT INTO A_PROCEDURE_STEP_DESTINATION_TYPES (ID,NAME,DRCM,MODBY,NUM)
VALUES (@ID,@NAME,getdate(),'Sys',@num)
