CREATE PROCEDURE dbo.A_Z_PROCEDURE_STEP_DESTINATION_TYPES_CREATE
AS
exec A_Z_PROCEDURE_STEP_DESTINATION_CREATE_ONE 'AT_STEP','Decide when step assigned',0
exec A_Z_PROCEDURE_STEP_DESTINATION_CREATE_ONE 'PURCHASER_ADDRESS','Purchaser Address',1
exec A_Z_PROCEDURE_STEP_DESTINATION_CREATE_ONE 'SUPPLIER_ADDRESS','Supplier Address',2
exec A_Z_PROCEDURE_STEP_DESTINATION_CREATE_ONE 'ORIG_OBJ_LOCATION','Applicable Object Original Location',3
exec A_Z_PROCEDURE_STEP_DESTINATION_CREATE_ONE 'SPEC_LOCATION','Specified Location',4




