




CREATE      PROCEDURE dbo.A_Z_UNIT_TYPES_CREATE_ALL
AS
DELETE FROM A_UNIT_TYPES
exec A_Z_UNIT_TYPES_CREATE_ONE 'UNIT','UNIT','Ordering Unit Item',0
exec A_Z_UNIT_TYPES_CREATE_ONE 'WEIGHT','WT_OZ','Ounces',10
exec A_Z_UNIT_TYPES_CREATE_ONE 'WEIGHT','WT_LBS','POUNDS',11
exec A_Z_UNIT_TYPES_CREATE_ONE 'WEIGHT','WT_KG','Kilograms',12
exec A_Z_UNIT_TYPES_CREATE_ONE 'VOLUME','VOL_GALLONS','Gallons',50
exec A_Z_UNIT_TYPES_CREATE_ONE 'TIME','TIME_SYS_SECONDS','SYS_SECONDS',100
exec A_Z_UNIT_TYPES_CREATE_ONE 'TIME','TIME_SYS_MINUTES','SYS_MINUTES',101
exec A_Z_UNIT_TYPES_CREATE_ONE 'TIME','TIME_SYS_HOURS','SYS_HOURS',102
exec A_Z_UNIT_TYPES_CREATE_ONE 'TIME','TIME_SYS_DAYS','SYS_DAYS',103
exec A_Z_UNIT_TYPES_CREATE_ONE 'TIME','TIME_SYS_WEEKS','SYS_WEEKS',104

DELETE FROM A_UNIT_RELATIONS
INSERT INTO A_UNIT_RELATIONS values ('WT_OZ','WT_OZ',1,1)
INSERT INTO A_UNIT_RELATIONS values ('WT_OZ','WT_LBS',1,0.0625)
INSERT INTO A_UNIT_RELATIONS values ('WT_OZ','WT_KG',1,0.028349523)

INSERT INTO A_UNIT_RELATIONS values ('WT_LBS','WT_OZ',1,16)
INSERT INTO A_UNIT_RELATIONS values ('WT_LBS','WT_LBS',1,1)
INSERT INTO A_UNIT_RELATIONS values ('WT_LBS','WT_KG',1,.45359237)

INSERT INTO A_UNIT_RELATIONS values ('WT_KG','WT_OZ',1,35.27396195)
INSERT INTO A_UNIT_RELATIONS values ('WT_KG','WT_LBS',1,2.204622622)
INSERT INTO A_UNIT_RELATIONS values ('WT_KG','WT_KG',1,1)

INSERT INTO A_UNIT_RELATIONS values ('VOL_GALLONS','VOL_GALLONS',1,1)

INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_SECONDS','TIME_SYS_SECONDS',1,1)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_SECONDS','TIME_SYS_MINUTES',1,(1.0/60.0))
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_SECONDS','TIME_SYS_HOURS',1,((1.0/60.0)/60.0))
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_SECONDS','TIME_SYS_DAYS',1,(((1.0/60.0)/60.0)/24.0))
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_SECONDS','TIME_SYS_WEEKS',1,(((1.0/60.0)/60.0)/24.0)/7.0)

INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_MINUTES','TIME_SYS_SECONDS',1,60)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_MINUTES','TIME_SYS_MINUTES',1,1)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_MINUTES','TIME_SYS_HOURS',1,1.0/60.0)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_MINUTES','TIME_SYS_DAYS',1,1.0/60.0/24.0)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_MINUTES','TIME_SYS_WEEKS',1,1.0/60.0/24.0/7.0)

INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_HOURS','TIME_SYS_SECONDS',1,60*60)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_HOURS','TIME_SYS_MINUTES',1,60)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_HOURS','TIME_SYS_HOURS',1,1)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_HOURS','TIME_SYS_DAYS',1,1.0/24.0)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_HOURS','TIME_SYS_WEEKS',1,1.0/24.0/7.0)

INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_DAYS','TIME_SYS_SECONDS',1,60.0*60.0*24)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_DAYS','TIME_SYS_MINUTES',1,60.0*24)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_DAYS','TIME_SYS_HOURS',1,24)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_DAYS','TIME_SYS_DAYS',1,1)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_DAYS','TIME_SYS_WEEKS',1,1.0/7.0)

INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_WEEKS','TIME_SYS_SECONDS',1,60.0*60.0*24*7)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_WEEKS','TIME_SYS_MINUTES',1,60.0*24*7)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_WEEKS','TIME_SYS_HOURS',1,24*7)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_WEEKS','TIME_SYS_DAYS',1,7)
INSERT INTO A_UNIT_RELATIONS values ('TIME_SYS_WEEKS','TIME_SYS_WEEKS',1,1)

INSERT INTO A_UNIT_RELATIONS values ('UNIT','UNIT',1,1)






