CREATE    PROCEDURE dbo.A_Z_MD_OFF
AS
if not( exists (SELECT * FROM A_ADMIN_CONFIGURATION WHERE NAME = 'SP_DEBUG'))
	INSERT INTO A_ADMIN_CONFIGURATION (ID,NAME,VAL)	VALUES (newID(),'SP_DEBUG','0')
UPDATE A_ADMIN_CONFIGURATION SET VAL = '0' WHERE NAME = 'SP_DEBUG'



