






CREATE        PROCEDURE DBO.A_Z_UTIL_OBJECT_UPDATE_ALL_ROOT_STATUSES
AS
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_PROCEDURES'
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_PRODUCTS'
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_COMPANIES'
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_LOCATIONS'
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_PEOPLE'
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_PROD_PRICE_LIST'
exec A_Z_UTIL_OBJECT_UPDATE_ROOT_STATUS 'A_ACTUAL_PARTS'












