CREATE PROCEDURE DBO.OBJECTS_QUICK_APPROVE
@objID varchar(50),
@strNTLogin varchar(50)
AS
declare @rootID varchar(50)
SELECT @rootID = ROOT FROM A_OBJECTS WHERE ID = @objID
UPDATE A_OBJECTS SET STATUS = 'OLD' WHERE STATUS <> 'DELETED' AND ROOT = @rootID AND ID <> @objID
UPDATE A_OBJECTS SET 
	STATUS = 'APPROVED',
	APPROVAL_DATE = getDate(),
	LOCKED_BY = null,
	LOCKED_BY_NAME = null,
	UNLOCKED_BY = @strNTLogin
WHERE ID = @objID
	
