import { ColumnsSaved } from '../../../src/app/models/lib/ColumnsSaved';

describe('Parts Functionality', () => {
    it('TC73_AddPart', () => {
        cy.server();
        cy.route({
            method: 'GET',
            url: '/v1/Part',
            response: {
                "object": [{
                    "name": "DD Part B 1592421221",
                    "partNumber": "1592421221b",
                    "oemPartNumber": "1592421221b-OEM",
                    "isKit": false,
                    "nickName": "DD Part B Nick",
                    "maximumCycles": 9999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-06-17T19:18:20.603",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-17T19:18:20.603",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 3
                }, {
                    "name": "DD Part C 1592421221",
                    "partNumber": "1592421221c",
                    "oemPartNumber": "1592421221c-OEM",
                    "isKit": false,
                    "nickName": "DD Part C Nick",
                    "maximumCycles": 9999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-06-17T19:18:34.747",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-17T19:18:34.747",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 4
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:22:28.937",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:22:28.937",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 6
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:26:20.86",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:26:20.86",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 7
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:27:05.57",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:27:05.57",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 8
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:54:34.08",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:54:34.08",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 9
                }, {
                    "name": "lksdjflkj",
                    "partNumber": "NUMBERlkajsdf",
                    "oemPartNumber": "OEMskladfjk",
                    "isKit": false,
                    "nickName": "NICKalskdfj",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T13:57:52.7",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T13:57:52.7",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 10
                }, {
                    "name": "NAME159430341000000",
                    "partNumber": "PARTNUM159430341000000",
                    "oemPartNumber": "OEM159430341000000",
                    "isKit": false,
                    "nickName": "NICK159430341000000",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T14:03:38.34",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T14:03:38.34",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 11
                }, {
                    "name": "NAME159430341000001",
                    "partNumber": "PARTNUM159430341000001",
                    "oemPartNumber": "OEM159430341000001",
                    "isKit": false,
                    "nickName": "NICK159430341000001",
                    "maximumCycles": 999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-09T14:03:39.7",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-07-09T14:03:39.7",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 12
                }, {
                    "name": "TESTNAME1594327266",
                    "partNumber": "TESTPARTNUM1594327266",
                    "oemPartNumber": "TESTOEMPARTNUM1594327266",
                    "isKit": false,
                    "nickName": "DD Part A Nick",
                    "maximumCycles": 9999,
                    "createdByName": "David  Dombrowsky",
                    "lastUpdatedByName": "David  Dombrowsky",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-07-11T20:25:58.74",
                    "lastUpdatedBy": 43,
                    "lastUpdated": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "createdOn": "2020-06-17T19:17:55.29",
                    "createdBy": 43,
                    "created": {
                        "id": 43,
                        "isActive": true,
                        "userRoleId": "9465b3a8-b5bc-4afd-9874-6e1ec7d5a0d3",
                        "userName": "ddombrowsky",
                        "firstName": "David ",
                        "lastName": "Dombrowsky",
                        "fullName": "David  Dombrowsky",
                        "title": "Dev Administrator",
                        "email": "david.dombrowsky@cmhworks.com",
                        "securityStamp": "f4bf3b6e-84c9-4e04-8a8b-076a72f107eb",
                        "phone": null,
                        "supervisorId": 45,
                        "supervisorName": null,
                        "locationId": 0,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 0,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 100,
                        "lastUpdatedOn": "2020-06-16T16:33:31.757",
                        "lastUpdatedBy": 43,
                        "createdOn": "2019-11-22T15:39:38.633",
                        "createdBy": 71,
                        "roles": []
                    },
                    "id": 2
                }],
                "successMessage": null,
                "errorMessages": [],
                "id": 0,
                "hasErrors": false,
                "hasValidationErrors": false
            }
        });

        cy.route({
            method:'POST',
            url: '/v1/Part',
            response:{
                "object": {
                    "name": "testAbc",
                    "partNumber": "21412",
                    "oemPartNumber": "abc-oem",
                    "isKit": false,
                    "nickName": "tesTT",
                    "maximumCycles": 12,
                    "createdByName": "Alexanderrrrrgg Elliss",
                    "lastUpdatedByName": "Alexanderrrrrgg Elliss",
                    "createSubParts": [],
                    "files": [],
                    "isActive": null,
                    "lastUpdatedOn": "2020-08-19T21:10:38.6980626Z",
                    "lastUpdatedBy": 73,
                    "lastUpdated": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "createdOn": "2020-08-19T21:10:38.6980626Z",
                    "createdBy": 73,
                    "created": {
                        "id": 73,
                        "isActive": true,
                        "userRoleId": "e9a4c980-d2fb-443e-9af8-0458858316cd",
                        "userName": "alec",
                        "firstName": "Alexanderrrrrgg",
                        "lastName": "Elliss",
                        "fullName": "Alexanderrrrrgg Elliss",
                        "title": "Monkeyy",
                        "email": "alec.ellis@cmhworks.com",
                        "securityStamp": "8d5b9f07-af77-4dcd-b247-b047e67da3c9",
                        "phone": "9863592333",
                        "supervisorId": 35,
                        "supervisorName": null,
                        "locationId": 208,
                        "locationName": null,
                        "isAnswerUser": true,
                        "customerId": 22,
                        "lockoutEndDateUtc": null,
                        "lockoutEnabled": false,
                        "accessFailedCount": 0,
                        "timeZoneId": 0,
                        "lastUpdatedOn": "2020-07-24T02:24:24.37",
                        "lastUpdatedBy": 134,
                        "createdOn": "2020-07-10T01:46:56.043",
                        "createdBy": 73,
                        "roles": []
                    },
                    "id": 9287
                },
                "successMessage": "Part was successfully added.",
                "errorMessages": [],
                "id": 0,
                "hasErrors": false,
                "hasValidationErrors": false
            }
        });

        cy.beginWebConsoleTracking();
        cy.login('admin');
        cy.navigateToPage('Parts', 'Parts');

        const parts = [
            new ColumnsSaved({ id: 'id', label: 'Id', visible: true }),
            new ColumnsSaved({ id: 'name', label: 'Name', visible: true }),
            new ColumnsSaved({ id: 'partNumber', label: 'Part Number', visible: true }),
            new ColumnsSaved({ id: 'oemPartNumber', label: 'OEM Part Number', visible: true }),
            new ColumnsSaved({ id: 'isKit', label: 'Is Kit', visible: true }),
            new ColumnsSaved({ id: 'isActive', label: 'Is Active', visible: true }),
            new ColumnsSaved({ id: 'maximumCycles', label: 'Maximun Cycles', visible: true }),
            new ColumnsSaved({ id: 'files', label: 'Reference Files', visible: true }),
            new ColumnsSaved({ id: 'createdOn', label: 'Created On', visible: false }),
            new ColumnsSaved({ id: 'createdByName', label: 'Created By', visible: false }),
            new ColumnsSaved({ id: 'lastUpdatedOn', label: 'Updated On', visible: false }),
            new ColumnsSaved({ id: 'lastUpdatedByName', label: 'Updated By', visible: false })
        ];

        cy.showDropdownTrackableModel('usergrid-options');
        cy.get('[data-cy=add-button]').click();

        cy.writeAndValidate('name-input', 'testAbc');
        cy.writeAndValidate('partNr-input', '21412');
        cy.writeAndValidate('oemPartNumber-input', 'abc-oem');
        cy.writeAndValidate('nickName-input', 'tesTT');
        // cy.get('[data-cy=isActive-checkbox]').click();
        cy.writeAndValidate('maximumCycles-input', '12');

        cy.get('[data-cy=save-button]').click();

        cy.writeCommentAndClose('happyPart');

        cy.get(".ui-blockui-document", { timeout: 20000 }).should("not.be.visible");
        cy.writeAndValidate('id-grid','9287');
        cy.get('[data-cy=row]').find('td:first').contains('9287');

        cy.logout();
        cy.checkWebConsoleTracking();
    })
})

