<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <UserSecretsId>ec0b0540-4bf8-4425-a750-a65e7760e32d</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Projections\**" />
    <Compile Remove="Queries\**" />
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Projections\**" />
    <EmbeddedResource Remove="Queries\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Projections\**" />
    <None Remove="Queries\**" />
    <None Remove="Services\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Abstractions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.112" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.103.23" />
    <PackageReference Include="CsvHelper" Version="15.0.5" />
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
    <PackageReference Include="Serilog.Sinks.AwsCloudWatch" Version="4.0.159" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
  </ItemGroup>

</Project>
