CREATE TABLE [dbo].[UserApproval] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [OldId]             INT            NULL,
    [UserId]            INT            NOT NULL,
    [StatusId]          INT            NOT NULL,
    [UserRoleId]        VARCHAR (50)   NULL,
    [UserName]          NVARCHAR (MAX) NOT NULL,
    [FirstName]         NVARCHAR (MAX) NULL,
    [LastName]          NVARCHAR (MAX) NULL,
    [Title]             NVARCHAR (128) NULL,
    [Email]             NVARCHAR (256) NULL,
    [PasswordHash]      NVARCHAR (MAX) NULL,
    [SecurityStamp]     NVARCHAR (MAX) NULL,
    [Phone]             NVARCHAR (MAX) NULL,
    [SupervisorId]      INT            NULL,
    [LocationId]        INT            NULL,
    [IsActive]          BIT            NOT NULL,
    [IsAnswerUser]      BIT            NULL,
    [CustomerId]        INT            NULL,
    [LockoutEndDateUtc] DATETIME       NULL,
    [LockoutEnabled]    BIT            NOT NULL,
    [AccessFailedCount] INT            NOT NULL,
    [TimeZoneId]        INT            NULL,
    [CreatedBy]         INT            NOT NULL,
    [CreatedOn]         DATETIME       NOT NULL,
    [LastUpdatedBy]     INT            NULL,
    [LastUpdatedOn]     DATETIME       NULL,
    CONSTRAINT [PK_UserApproval] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_UserApprovalCreatedById] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_UserApprovalCustomerId] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer] ([Id]),
    CONSTRAINT [FK_UserApprovalLastUpdatedById] FOREIGN KEY ([LastUpdatedBy]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_UserApprovalLocationId] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([Id]),
    CONSTRAINT [FK_UserApprovalStatusId] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[Status] ([Id]),
    CONSTRAINT [FK_UserApprovalSupervisorId] FOREIGN KEY ([SupervisorId]) REFERENCES [dbo].[User] ([Id]),
    CONSTRAINT [FK_UserApprovalUserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([Id])
);

