CREATE TABLE [dbo].[User] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [OldId]             INT            NULL,
    [UserRoleId]        VARCHAR (50)   NULL,
    [UserName]          NVARCHAR (MAX) NOT NULL,
    [FirstName]         NVARCHAR (MAX) NULL,
    [LastName]          NVARCHAR (MAX) NULL,
    [Title]             NVARCHAR (128) NULL,
    [Email]             NVARCHAR (256) NULL,
    [PasswordHash]      NVARCHAR (MAX) NULL,
    [Password]          NVARCHAR (50)  NULL,
    [SecurityStamp]     NVARCHAR (MAX) NULL,
    [Phone]             NVARCHAR (MAX) NULL,
    [SupervisorId]      INT            NULL,
    [LocationId]        INT            NULL,
    [IsActive]          BIT            NOT NULL,
    [IsAnswerUser]      BIT            NULL,
    [CustomerId]        INT            NULL,
    [LockoutEndDateUtc] DATETIME       NULL,
    [LockoutEnabled]    BIT            NOT NULL,
    [AccessFailedCount] INT            NOT NULL,
    [TimeZoneId]        INT            NULL,
    [CreatedBy]         INT            NOT NULL,
    [CreatedOn]         DATETIME       NOT NULL,
    [LastUpdatedBy]     INT            NULL,
    [LastUpdatedOn]     DATETIME       NULL,
    CONSTRAINT [PK_PortalUser] PRIMARY KEY CLUSTERED ([Id] ASC)
);

