CREATE VIEW dbo.A_ACCOUNT_INVOICE_ITEMS_WITH_ACCT_AND_STATUS
AS
SELECT     dbo.A_ACCOUNT_INVOICES.ACCOUNT_ID, dbo.A_ACCOUNT_INVOICES.STATUS, dbo.A_ACCOUNT_INVOICE_ITEMS.AMOUNT, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS.TAX
FROM         dbo.A_ACCOUNT_INVOICE_ITEMS INNER JOIN
                      dbo.A_ACCOUNT_INVOICES ON dbo.A_ACCOUNT_INVOICE_ITEMS.INVOICE_ID = dbo.A_ACCOUNT_INVOICES.ID
