


CREATE VIEW dbo.A_APPROVED_PRODUCTS
AS
SELECT     dbo.A_PRODUCTS.ID, dbo.A_PRODUCTS.HISTORY_REF_ID, dbo.A_O_PRODUCTS.NAME, dbo.A_O_PRODUCTS.SUPPLIER_ID, 
                      dbo.A_O_PRODUCTS.COMMENTS, dbo.A_O_PRODUCTS.PROCEDURE_ID, dbo.A_O_PRODUCTS.APP_OBJECT, dbo.A_O_PRODUCTS.SHIP_OR_LABOR, 
                      dbo.A_O_PRODUCTS.CUSTOMIZABLE, dbo.A_O_PRODUCTS.REQ_FORM, dbo.A_O_PRODUCTS.MGR_TEAM, dbo.A_O_PRODUCTS.SALES_TAX, 
                      dbo.A_O_PRODUCTS.OBJECT_ID, dbo.A_O_PRODUCTS.PARENT_ID, dbo.A_O_PRODUCTS.LOCKED_BY, dbo.A_O_PRODUCTS.UNLOCKED_BY, 
                      dbo.A_O_PRODUCTS.CREATED_BY, dbo.A_O_PRODUCTS.CREATE_DATE, dbo.A_O_PRODUCTS.ROOT, dbo.A_O_PRODUCTS.CREATING_CO, 
                      dbo.A_O_PRODUCTS.REV_INFO, dbo.A_O_PRODUCTS.REV, dbo.A_O_PRODUCTS.STATUS, dbo.A_O_PRODUCTS.WFS_ID, 
                      dbo.A_O_PRODUCTS.LOCKED_BY_NAME, dbo.A_O_PRODUCTS.CREATING_CO_NAME, dbo.A_O_PRODUCTS.APPROVAL_ACTIVITY, 
                      dbo.A_PROCEDURES_HISTORY.SYSTEM_ID
FROM         dbo.A_PROCEDURES_HISTORY INNER JOIN
                      dbo.A_PROCEDURES ON dbo.A_PROCEDURES_HISTORY.ID = dbo.A_PROCEDURES.HISTORY_REF_ID RIGHT OUTER JOIN
                      dbo.A_O_PRODUCTS INNER JOIN
                      dbo.A_PRODUCTS ON dbo.A_O_PRODUCTS.ID = dbo.A_PRODUCTS.HISTORY_REF_ID ON 
                      dbo.A_PROCEDURES.ID = dbo.A_O_PRODUCTS.PROCEDURE_ID



