




CREATE VIEW dbo.A_APRROVED_PEOPLE
AS
SELECT     dbo.A_PEOPLE.ID, dbo.A_PEOPLE_HISTORY.LOGIN, dbo.A_PEOPLE_HISTORY.NAME, dbo.A_PEOPLE_HISTORY.PASSWORD, 
                      dbo.A_PEOPLE_HISTORY.BOSS, dbo.A_PEOPLE_HISTORY.SOURCE, dbo.A_PEOPLE_HISTORY.LAST_NAME, 
                      dbo.A_PEOPLE_HISTORY.MIDDLE_NAME, dbo.A_PEOPLE_HISTORY.NICK_NAME, dbo.A_PEOPLE_HISTORY.LANG, 
                      dbo.A_PEOPLE_HISTORY.HIRE_DATE, dbo.A_PEOPLE_HISTORY.DRCM, dbo.A_PEOPLE_HISTORY.MODBY, dbo.A_PEOPLE_HISTORY.OBJECT_ID, 
                      dbo.A_PEOPLE_HISTORY.COMPANY, dbo.A_PEOPLE_HISTORY.TIME_ZONE, dbo.A_PEOPLE_HISTORY.FULL_NAME, 
                      dbo.A_PEOPLE_HISTORY.SYSTEM_STATUS, dbo.A_PEOPLE_HISTORY.CO_POSITION, dbo.A_PEOPLE_HISTORY.ROOT_COMPANY
FROM         dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID





