


CREATE VIEW dbo.A_APPROVED_ROLE_ASSIGNEES
AS
SELECT     dbo.A_ROLES.ID AS ROLE_ID, dbo.A_ROLES_HISTORY.NAME AS ROLE_NAME, dbo.A_ROLE_ASSIGNEE.ROLE, dbo.A_ROLE_ASSIGNEE.PERSON, 
                      dbo.A_ROLE_ASSIGNEE.STATUS, dbo.A_ROLE_ASSIGNEE.ROLE_ASSIGNED, dbo.A_ROLE_ASSIGNEE.TYPE,
dbo.A_ROLE_ASSIGNEE.StartDate,
dbo.A_ROLE_ASSIGNEE.EndDate
FROM         dbo.A_ROLES INNER JOIN
                      dbo.A_ROLE_ASSIGNEE ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLE_ASSIGNEE.ROLE INNER JOIN
                      dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID
WHERE     (dbo.A_ROLE_ASSIGNEE.STATUS = N'ACTIVE')



