


CREATE VIEW dbo.A_APPROVED_ROLES_WITH_ASSIGNEES
AS
SELECT     dbo.A_APPROVED_ROLES.ID, dbo.A_APPROVED_ROLES.NAME, dbo.A_APPROVED_PEOPLE.FULL_NAME AS MEMBER_NAME, 
                      dbo.A_APPROVED_ROLES.CREATING_CO, dbo.A_APPROVED_ROLES.OBJECT_ID
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_ROLE_ASSIGNEE ON dbo.A_APPROVED_PEOPLE.ID = dbo.A_ROLE_ASSIGNEE.PERSON INNER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_ROLE_ASSIGNEE.ROLE = dbo.A_APPROVED_ROLES.HISTORY_REF_ID



