



CREATE VIEW dbo.A_APPROVED_PARTS
AS
SELECT     dbo.A_PARTS.ID AS APPROVED_ID, dbo.A_O_PARTS_HISTORY.*
FROM         dbo.A_PARTS INNER JOIN
                      dbo.A_O_PARTS_HISTORY ON dbo.A_PARTS.PARTS_HISTORY_ID = dbo.A_O_PARTS_HISTORY.ID




