CREATE VIEW dbo.A_APPROVED_COMPANIES
AS
SELECT     dbo.A_COMPANIES.ID, dbo.A_COMPANIES.HISTORY_REF_ID, dbo.A_COMPANIES_HISTORY.NAME, dbo.A_COMPANIES_HISTORY.CO_TYPE, 
                      dbo.A_COMPANIES_HISTORY.PARENT, dbo.A_COMPANIES_HISTORY.PHONE, dbo.A_COMPANIES_HISTORY.LOCATION, 
                      dbo.A_COMPANIES_HISTORY.LOCATION_NAME, dbo.A_COMPANIES_HISTORY.DRCM, dbo.A_COMPANIES_HISTORY.MODBY, 
                      dbo.A_COMPANIES_HISTORY.OBJECT_ID, dbo.A_OBJECTS.LOCKED_BY, dbo.A_OBJECTS.UNLOCKED_BY, dbo.A_OBJECTS.CREATED_BY, 
                      dbo.A_OBJECTS.CREATE_DATE, dbo.A_OBJECTS.REV_INFO, dbo.A_OBJECTS.CREATING_CO, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.REV, 
                      dbo.A_OBJECTS.WFS_ID, dbo.A_OBJECTS.LOCKED_BY_NAME, dbo.A_OBJECTS.CREATING_CO_NAME, dbo.A_OBJECTS.APPROVAL_ACTIVITY, 
                      dbo.A_COMPANIES.STATUS AS GENERAL_STATUS, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS PARENT_NAME, 
                      A_V_COMPANIES_APPROVED_DATA_1.NAME AS ROOT_CO_NAME, dbo.A_COMPANIES_HISTORY.ROOT_CO_ID
FROM         dbo.A_OBJECTS INNER JOIN
                      dbo.A_COMPANIES_HISTORY ON dbo.A_OBJECTS.ID = dbo.A_COMPANIES_HISTORY.OBJECT_ID INNER JOIN
                      dbo.A_COMPANIES ON dbo.A_COMPANIES_HISTORY.ID = dbo.A_COMPANIES.HISTORY_REF_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      dbo.A_COMPANIES_HISTORY.ROOT_CO_ID = A_V_COMPANIES_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_COMPANIES_HISTORY.PARENT = dbo.A_V_COMPANIES_APPROVED_DATA.ID
WHERE     (dbo.A_COMPANIES.STATUS = 'APPROVED')
