



CREATE VIEW dbo.A_APPROVED_NOUN_HIERARCHIES
AS
SELECT     dbo.A_NOUN_HIERARCHIES.ID, dbo.A_NOUN_HIERARCHIES.HISTORY_REF_ID, dbo.A_NOUN_HIERARCHIES.DRCM, 
                      dbo.A_NOUN_HIERARCHIES.MODBY, dbo.A_NOUN_HIERARCHY_CHILDREN.ID AS ROOT_CHILD, dbo.A_NOUN_HIERARCHY_CHILDREN.PARENT_ID, 
                      dbo.A_NOUN_HIERARCHIES_HISTORY.NAME, dbo.A_V_APPROVED_OBJECTS.OBJ_TABLE, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC, 
                      dbo.A_V_APPROVED_OBJECTS.OBJ_ID
FROM         dbo.A_NOUN_HIERARCHIES INNER JOIN
                      dbo.A_NOUN_HIERARCHIES_HISTORY ON dbo.A_NOUN_HIERARCHIES.HISTORY_REF_ID = dbo.A_NOUN_HIERARCHIES_HISTORY.ID INNER JOIN
                      dbo.A_NOUN_HIERARCHY_CHILDREN ON dbo.A_NOUN_HIERARCHIES.ID = dbo.A_NOUN_HIERARCHY_CHILDREN.HIERARCHY_ID INNER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_NOUN_HIERARCHY_CHILDREN.APPROVED_OBJ_ID = dbo.A_V_APPROVED_OBJECTS.ID
WHERE     (dbo.A_NOUN_HIERARCHY_CHILDREN.PARENT_ID IS NULL)




