



CREATE VIEW dbo.A_APPROVED_VERBS
AS
SELECT     dbo.A_O_TT_VERBS_HISTORY.NAME, dbo.A_TT_VERBS.ID, dbo.A_O_TT_VERBS_HISTORY.OBJECT_ID, dbo.A_O_TT_VERBS_HISTORY.LOCKED_BY, 
                      dbo.A_O_TT_VERBS_HISTORY.UNLOCKED_BY, dbo.A_O_TT_VERBS_HISTORY.CREATED_BY, dbo.A_O_TT_VERBS_HISTORY.CREATE_DATE, 
                      dbo.A_O_TT_VERBS_HISTORY.ROOT, dbo.A_O_TT_VERBS_HISTORY.REV_INFO, dbo.A_O_TT_VERBS_HISTORY.CREATING_CO, 
                      dbo.A_O_TT_VERBS_HISTORY.STATUS, dbo.A_O_TT_VERBS_HISTORY.REV, dbo.A_O_TT_VERBS_HISTORY.LOCKED_BY_NAME, 
                      dbo.A_O_TT_VERBS_HISTORY.APPROVAL_ACTIVITY, dbo.A_O_TT_VERBS_HISTORY.CREATING_CO_NAME, dbo.A_O_TT_VERBS_HISTORY.OBJ_ID, 
                      dbo.A_O_TT_VERBS_HISTORY.VERB_TYPE_NAME, dbo.A_O_TT_VERBS_HISTORY.VERB_TYPE
FROM         dbo.A_TT_VERBS INNER JOIN
                      dbo.A_O_TT_VERBS_HISTORY ON dbo.A_TT_VERBS.HISTORY_REF_ID = dbo.A_O_TT_VERBS_HISTORY.ID




