




CREATE VIEW dbo.A_APPROVED_REGIONS
AS
SELECT     r.ID, r.HISTORY_REF_ID, rh.OBJECT_ID, o.ID AS OBJ_ID, rh.NAME, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, 
                      o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY
FROM         dbo.A_REGIONS r INNER JOIN
                      dbo.A_REGIONS_HISTORY rh ON r.HISTORY_REF_ID = rh.ID INNER JOIN
                      dbo.A_OBJECTS o ON rh.OBJECT_ID = o.ID





