CREATE VIEW dbo.A_APPROVED_ROLES
AS
SELECT     dbo.A_ROLES.ID, dbo.A_ROLES_HISTORY.NAME, dbo.A_ROLES_HISTORY.SOURCE, dbo.A_ROLES_HISTORY.HIDDEN, 
                      dbo.A_ROLES_HISTORY.DRCM, dbo.A_ROLES_HISTORY.MODBY, dbo.A_ROLES_HISTORY.OBJECT_ID, dbo.A_OBJECTS.LOCKED_BY, 
                      dbo.A_OBJECTS.UNLOCKED_BY, dbo.A_OBJECTS.CREATED_BY, dbo.A_OBJECTS.CREATE_DATE, dbo.A_OBJECTS.ROOT, dbo.A_OBJECTS.REV_INFO,
                       dbo.A_OBJECTS.CREATING_CO, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.REV, dbo.A_OBJECTS.WFS_ID, dbo.A_OBJECTS.LOCKED_BY_NAME, 
                      dbo.A_OBJECTS.CREATING_CO_NAME, dbo.A_OBJECTS.APPROVAL_ACTIVITY, dbo.A_ROLES.HISTORY_REF_ID, dbo.A_ROLES_HISTORY.IS_ADMIN, 
                      dbo.A_ROLES_HISTORY.SECURITY_LEVEL, dbo.A_ROLES.STATUS AS DEL_STATUS
FROM         dbo.A_ROLES INNER JOIN
                      dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_ROLES_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID
WHERE     (dbo.A_ROLES.STATUS = 'APPROVED')
