



CREATE VIEW dbo.A_APPROVED_PROCEDURES
AS
SELECT     dbo.A_PROCEDURES.ID, dbo.A_PROCEDURES.HISTORY_REF_ID, dbo.A_PROCEDURES_HISTORY.OBJECT_ID, 
                      dbo.A_PROCEDURES_HISTORY.VERB, dbo.A_PROCEDURES_HISTORY.NAME, dbo.A_PROCEDURES_HISTORY.COMMENTS, 
                      dbo.A_PROCEDURES_HISTORY.SECURITY_LEVEL, dbo.A_PROCEDURES_HISTORY.STEPS_IN_AP, dbo.A_PROCEDURES_HISTORY.WIP_MSG, 
                      dbo.A_PROCEDURES_HISTORY.DRCM, dbo.A_PROCEDURES_HISTORY.MODBY
FROM         dbo.A_PROCEDURES INNER JOIN
                      dbo.A_PROCEDURES_HISTORY ON dbo.A_PROCEDURES.HISTORY_REF_ID = dbo.A_PROCEDURES_HISTORY.ID




