CREATE VIEW [dbo].[A_CUSTOMER_PART_FILE_LINK_2]
AS
SELECT     dbo.A_V_WIP_REPORT_VIEW.TASK_ID, dbo.A_V_WIP_REPORT_VIEW.CUST_ID, dbo.A_DOCUMENTS.NAME, 
                      dbo.A_V_WIP_REPORT_VIEW.CUSTOMER_NAME, dbo.A_V_WIP_REPORT_VIEW.SERIAL, dbo.A_V_WIP_REPORT_VIEW.COMPANY_PART_NUMBER, 
                      dbo.A_DOCUMENTS.SERVER_PATH
FROM         dbo.A_ACTUAL_PARTS_RELATED_FILES INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_ACTUAL_PARTS_RELATED_FILES.FILE_ID = dbo.A_DOCUMENTS.ID INNER JOIN
                      dbo.A_V_WIP_REPORT_VIEW INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON dbo.A_V_WIP_REPORT_VIEW.SERIAL = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL ON 
                      dbo.A_ACTUAL_PARTS_RELATED_FILES.ACTUAL_PART_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID