CREATE VIEW dbo.A_O_PRODUCTS
AS
SELECT     PH.ID, PH.NAME, PH.SUPPLIER_ID, PH.COMMENTS, PH.PROCEDURE_ID, PH.APP_OBJECT, PH.SHIP_OR_LABOR, PH.CUSTOMIZABLE, 
                      PH.REQ_FORM, PH.MGR_TEAM, PH.SALES_TAX, PH.OBJECT_ID, PH.PARENT_ID, O.LOCKED_BY, O.UNLOCKED_BY, O.CREATED_BY, 
                      O.CREATE_DATE, O.ROOT, O.CREATING_CO, O.REV_INFO, O.STATUS, O.REV, O.WFS_ID, O.LOCKED_BY_NAME, O.CREATING_CO_NAME, 
                      O.APPROVAL_ACTIVITY, dbo.A_FN_PRODUCT_WHERE_USED_CHECK(PH.ID) AS HAS_USAGE, PH.AVAILABILITY
FROM         dbo.A_PRODUCTS_HISTORY PH INNER JOIN
                      dbo.A_OBJECTS O ON PH.OBJECT_ID = O.ID
