CREATE VIEW dbo.A_O_ACCOUNTS
AS
SELECT     a.ID, a.OBJECT_ID, a.NAME, a.REFERENCE_PO, a.REFERENCE_NAME, dbo.d2v(a.OPEN_DATE) AS OPEN_DATE, dbo.d2v(a.CLOSE_DATE) 
                      AS CLOSE_DATE, a.SUPPLIER_CO, a.CUSTOMER_CO, a.CUSTOMER_BILL_CO, a.MAXIMUM_USES, a.TOTAL_PURCHASE_LIMIT, a.CREDIT_LIMIT, 
                      a.APPROVAL_WF, a.INVOICE_TRIGGER, a.INVOICE_PERIOD_NUMBER, a.INVOICE_PERIOD_TYPE, a.FIRST_INVOICE_DATE, a.NEXT_INVOICE_DATE, 
                      a.PAYMENT_GRACE_PERIOD, a.LATE_FEE_PERCENTAGE, a.REAPPLY_LATE_FEE, a.DRCM, a.MODBY, a.ACCT_TYPE, a.TOTAL_PURCHASES, 
                      a.BALANCE, a.AMT_INVOICED, a.ACCT_STATUS, sup.NAME AS SUPPLIER_NAME, co.NAME AS CUSTOMER_NAME, bill_co.NAME AS CUST_BILL_NAME,
                       o.ID AS OBJ_ID, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, 
                      o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, a.INVOICED_BALANCE, a.UNINVOICED_BALANCE, 
                      a.TOTAL_CREDITS, a.TOTAL_DEBITS, a.BILLING_EMAIL
FROM         dbo.A_ACCOUNTS_HISTORY a INNER JOIN
                      dbo.A_OBJECTS o ON a.OBJECT_ID = o.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA sup ON a.SUPPLIER_CO = sup.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA co ON a.CUSTOMER_CO = co.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA bill_co ON a.CUSTOMER_BILL_CO = bill_co.ID
