CREATE VIEW dbo.A_O_PROPOSALS
AS
SELECT     ph.ID AS HIST_ID, o.ROOT, ph.OBJECT_ID AS OBJ_ID, ph.CUSTOMER_CO, ph.SUPPLIER_CO, ph.PROP_DATE, ph.PROP_VALID_DATE, ph.NAME, 
                      ph.DRCM, ph.MODBY, ph.OPENING, ph.ADD_NOTES, ph.CLOSING, ph.CREATOR_ID, o.LOCKED_BY_NAME, o.STATUS, o.CREATING_CO, 
                      o.UNLOCKED_BY, o.LOCKED_BY, o.CREATING_CO_NAME, o.WFS_ID, o.REV, o.REV_INFO, o.CREATE_DATE, o.CREATED_BY, 
                      CUST.NAME AS CUST_NAME, SUP.NAME AS SUPPLIER_NAME, cre.FULL_NAME AS CREATOR_NAME, ph.OBJECT_ID, ph.CREATOR_TITLE
FROM         dbo.A_PROPOSALS_HISTORY ph INNER JOIN
                      dbo.A_OBJECTS o ON ph.OBJECT_ID = o.ID INNER JOIN
                      dbo.A_COMPANIES CUST ON ph.CUSTOMER_CO = CUST.ID INNER JOIN
                      dbo.A_COMPANIES SUP ON ph.SUPPLIER_CO = SUP.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_DATA_QUICK cre ON ph.CREATOR_ID = cre.ID
