



CREATE  VIEW dbo.A_O_EQUIP_EXP
AS
SELECT     	e.ID,
			e.OBJECT_ID, 
			e.PERSON_ID, 
			e.PART_ID, 
			e.FIRST_EXPOSURE_DATE, 
			e.LAST_EXPOSURE_DATE, 
			e.HW_INSTALL_EXP_LEVEL, 'EE_LEVEL_' + convert(nvarchar(50),e.HW_INSTALL_EXP_LEVEL) AS HW_INSTALL_EXP_LEVEL_SHOW, 
            e.PROCESS_SETUP_EXP_LEVEL, 'EE_LEVEL_' + convert(nvarchar(50),e.PROCESS_SETUP_EXP_LEVEL) AS PROCESS_SETUP_EXP_LEVEL_SHOW,
			e.OPERATION_EXP_LEVEL, 'EE_LEVEL_' + convert(nvarchar(50),e.OPERATION_EXP_LEVEL) AS OPERATION_EXP_LEVEL_SHOW, 
			e.SM_EXP_LEVEL, 'EE_LEVEL_' + convert(nvarchar(50),e.SM_EXP_LEVEL) AS SM_EXP_LEVEL_SHOW, 
			e.UM_EXP_LEVEL, 'EE_LEVEL_' + convert(nvarchar(50),e.UM_EXP_LEVEL) AS UM_EXP_LEVEL_SHOW, 
			e.FORMALLY_TRAINED,
			e.CERTIFIED,
            o.ID AS OBJ_ID, 
			o.LOCKED_BY, 
			o.UNLOCKED_BY, 
			o.CREATED_BY,
			o.CREATE_DATE, 
			o.ROOT, 
			o.REV_INFO, 
			o.CREATING_CO, 
			o.STATUS, o.REV, 
            o.WFS_ID, 
			o.LOCKED_BY_NAME, 
			o.CREATING_CO_NAME, 
			o.APPROVAL_ACTIVITY, 
			part.NAME AS PART_NAME, 
            e.HW_INSTALL_EXP_LEVEL + e.PROCESS_SETUP_EXP_LEVEL + e.OPERATION_EXP_LEVEL + e.SM_EXP_LEVEL + e.UM_EXP_LEVEL AS OVERALL_EXP_LEVEL,
			dbo.A_FN_EE_GET_OVERALL_SHOW(e.HW_INSTALL_EXP_LEVEL + e.PROCESS_SETUP_EXP_LEVEL + e.OPERATION_EXP_LEVEL + e.SM_EXP_LEVEL + e.UM_EXP_LEVEL) AS OVERALL_EXP_LEVEL_SHOW,
            DATEDIFF(m, e.FIRST_EXPOSURE_DATE, e.LAST_EXPOSURE_DATE) AS CUMULATIVE_EXPOSURE, 
			person.FULL_NAME AS PERSON_NAME
FROM        dbo.A_OBJECTS o INNER JOIN
            dbo.A_EQUIP_EXP_HISTORY e ON o.ID = e.OBJECT_ID LEFT OUTER JOIN
            dbo.A_V_PEOPLE_APPROVED_DATA person ON e.PERSON_ID = person.ID LEFT OUTER JOIN
            dbo.A_V_PART_DATA_BY_APPROVED_DATA part ON e.PART_ID = part.ID




