

CREATE VIEW dbo.A_O_PROD_PRICE_LISTS
AS
SELECT     O.ROOT, O.CREATING_CO, O.LOCKED_BY, O.UNLOCKED_BY, O.CREATED_BY, O.CREATE_DATE, O.REV_INFO, O.STATUS, O.REV, 
                      O.LOCKED_BY_NAME, O.CREATING_CO_NAME, dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, PL.ID, PL.PRODUCT, PL.UNIT, 
                      PL.MIN_QUANTITY, PL.UNIT_PRICE, PL.EST_UNIT_PRICE, PL.EST_LABOR_PRICE, PL.EST_PARTS_PROV_STAY, PL.EST_PARTS_CONSUMED, 
                      PL.EST_PARTS_PROV_TAKE_BACK, PL.INVOICE_FROM, PL.PRODUCTION_TIME, PL.PRODUCTION_TIME_UNIT, PL.CAPACITY, PL.CAPACITY_UNIT, 
                      PL.DRCM, PL.MODBY, PL.OBJECT_ID, O.OBJ_TABLE, O.ID AS OBJ_ID, dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.CUST_ID, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS CUSTOMER, dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID, 
                      A_V_COMPANIES_APPROVED_DATA_1.NAME AS SUPPLIER_NAME, PL.FOR_INDIVIDUAL_SALE
FROM         dbo.A_V_PRODUCTS_APPROVED_DATA INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID = A_V_COMPANIES_APPROVED_DATA_1.ID RIGHT OUTER JOIN
                      dbo.A_OBJECTS O INNER JOIN
                      dbo.A_PROD_PRICE_LIST_HISTORY PL ON O.ID = PL.OBJECT_ID LEFT OUTER JOIN
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.CUST_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID ON 
                      PL.ID = dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.PP_LIST_ID ON dbo.A_V_PRODUCTS_APPROVED_DATA.ID = PL.PRODUCT


