
CREATE  VIEW dbo.A_O_ORDERS
AS
SELECT     H.ID, H.OBJECT_ID, H.CUSTOMER_PERSON, H.CUSTOMER_CO, H.DESCRIPTION, H.BUDGETARY_ONLY, H.EXPIRATION_DATE, H.DRCM, H.MODBY, 
                      O.ID AS OBJ_ID, O.LOCKED_BY, O.UNLOCKED_BY, O.CREATED_BY, O.CREATE_DATE, O.ROOT, O.REV_INFO, O.CREATING_CO, O.STATUS, O.REV, 
                      O.WFS_ID, O.LOCKED_BY_NAME, O.CREATING_CO_NAME, O.APPROVAL_ACTIVITY, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS CUSTOMER_NAME, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS CUST_PERSON_NAME, 
                      H.PROGRESS, dbo.A_V_COMPANIES_APPROVED_DATA.ROOT_CO, A_V_COMPANIES_APPROVED_DATA_1.NAME AS CUSTOMER_ROOT_CO_NAME, 
                      dbo.A_QUOTES_HISTORY.OBJECT_ID AS QUOTE_ID, dbo.A_QUOTES_HISTORY.SUPPLIER_ID, H.PRICE, 
                      A_V_COMPANIES_APPROVED_DATA_2.NAME AS SUPPLIER_NAME
FROM         dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_2 INNER JOIN
                      dbo.A_QUOTES_HISTORY ON A_V_COMPANIES_APPROVED_DATA_2.ID = dbo.A_QUOTES_HISTORY.SUPPLIER_ID RIGHT OUTER JOIN
                      dbo.A_ORDERS_HISTORY H INNER JOIN
                      dbo.A_OBJECTS O ON H.OBJECT_ID = O.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON H.CUSTOMER_CO = dbo.A_V_COMPANIES_APPROVED_DATA.ID ON 
                      dbo.A_QUOTES_HISTORY.ORDER_ID = H.OBJECT_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      dbo.A_V_COMPANIES_APPROVED_DATA.ROOT_CO = A_V_COMPANIES_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON H.CUSTOMER_PERSON = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID

