

CREATE VIEW dbo.A_O_PROCEDURES
AS
SELECT     dbo.leadingSpaces(o.ROOT, 30) AS SPECIAL_ROOT, dbo.leadingSpaces(ph.ID, 30) AS SPECIAL_ID, ph.ID, ph.OBJECT_ID, ph.VERB, ph.NAME, 
                      ph.COMMENTS, ph.SECURITY_LEVEL, ph.STEPS_IN_AP, ph.WIP_MSG, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, 
                      o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, 
                      dbo.A_APPROVED_VERBS.NAME AS VERB_NAME, dbo.A_APPROVED_VERBS.ID AS VERB_ID, o.ID AS OBJ_ID, ph.CREATING_DEPT, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS DEPT_NAME, dbo.A_SECURITY_LEVELS.NAME AS SECURITY_NAME, ph.IS_SYSTEM, 
                      ph.SYSTEM_ID, ph.DURATION_TYPE, ph.DURATION, ph.Threshold
FROM         dbo.A_PROCEDURES_HISTORY ph INNER JOIN
                      dbo.A_OBJECTS o ON ph.OBJECT_ID = o.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON ph.CREATING_DEPT = dbo.A_V_COMPANIES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_SECURITY_LEVELS ON ph.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_VERBS ON ph.VERB = dbo.A_APPROVED_VERBS.ID


