
CREATE  VIEW dbo.A_O_ROLES
AS
SELECT     r.ID, r.NAME AS ROLE_NAME, r.OBJECT_ID AS OBJ_ID, o.STATUS, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, 
                      o.REV_INFO, o.CREATING_CO, o.REV, o.WFS_ID, r.HIDDEN, r.SOURCE, r.OBJECT_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, 
                      o.APPROVAL_ACTIVITY, r.SECURITY_LEVEL, r.IS_ADMIN, dbo.A_SECURITY_LEVELS.NAME AS SECURITY_LEVEL_NAME
FROM         dbo.A_ROLES_HISTORY r INNER JOIN
                      dbo.A_OBJECTS o ON r.OBJECT_ID = o.ID INNER JOIN
                      dbo.A_SECURITY_LEVELS ON r.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID

