CREATE VIEW dbo.A_O_PREPOP_HISTORY
AS
SELECT     p.ID, p.OBJECT_ID, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, 
                      o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, o.ID AS OBJ_ID, p.PROC_STEP_ID, 
                      dbo.A_PROCEDURE_STEPS.STEP_TEXT
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_PREPOP_HISTORY p ON o.ID = p.OBJECT_ID INNER JOIN
                      dbo.A_PROCEDURE_STEPS ON p.PROC_STEP_ID = dbo.A_PROCEDURE_STEPS.ID
