

CREATE VIEW dbo.A_O_LOCATIONS
AS
SELECT     p.*, o.ID AS OBJ_ID, o.LOCKED_BY AS LOCKED_BY, o.UNLOCKED_BY AS UNLOCKED_BY, o.CREATED_BY AS CREATED_BY, 
                      o.CREATE_DATE AS CREATE_DATE, o.ROOT AS ROOT, o.REV_INFO AS REV_INFO, o.CREATING_CO AS CREATING_CO, o.STATUS AS STATUS, 
                      dbo.isChildLocation(o.ROOT) AS isChildLocation, o.REV AS REV, o.WFS_ID AS WFS_ID, o.LOCKED_BY_NAME AS LOCKED_BY_NAME, 
                      o.CREATING_CO_NAME AS CREATING_CO_NAME
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_LOCATIONS_HISTORY p ON o.ID = p.OBJECT_ID


