CREATE VIEW dbo.A_O_PARTS_HISTORY
AS
SELECT     o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.WFS_ID, 
                      o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, PH.OBJECT_ID AS OBJ_ID, PH.ID, PH.UNIT, PH.NAME, PH.PART_TYPE, 
                      PH.TRACK_FROM_START, PH.COMPANY, PH.UNIT_SHIPPING_WEIGHT, PH.COMPANY_PART_NUMBER, PH.SUPPLIER_SEE_INSTALL_BASE, 
                      PH.SUPPLIER_SEE_AVAILABILITY, PH.CUSTOMER_SEE_AVAILABILITY, c.NAME AS COMPANY_NAME, PT.NAME AS PART_TYPE_NAME, PH.SPARE, 
                      PH.CONSUMABLE, PH.WEIGHT_TYPE, PARENT_CO.NAME AS ROOT_CO_NAME, dbo.A_UNIT_TYPES.NAME AS WEIGHT_TYPE_NAME
FROM         dbo.A_PARTS_HISTORY PH INNER JOIN
                      dbo.A_OBJECTS o ON PH.OBJECT_ID = o.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK c ON PH.COMPANY = c.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK PARENT_CO ON c.PARENT = PARENT_CO.ID LEFT OUTER JOIN
                      dbo.A_UNIT_TYPES ON PH.WEIGHT_TYPE = dbo.A_UNIT_TYPES.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_PART_TYPES PT ON PH.PART_TYPE = PT.ROOT
