CREATE VIEW dbo.A_O_PEOPLE
AS
SELECT     o.OBJ_ID AS OBJ_ID, o.LOCKED_BY AS LOCKED_BY, o.UNLOCKED_BY AS UNLOCKED_BY, o.CREATED_BY AS CREATED_BY, 
                      o.CREATE_DATE AS CREATE_DATE, o.ROOT AS ROOT, o.REV_INFO AS REV_INFO, o.CREATING_CO AS CREATING_CO, o.STATUS AS STATUS, 
                      o.REV AS REV, o.WFS_ID AS WFS_ID, dbo.isBoss(o.ROOT) AS isBoss, p.ID, p.LOGIN, p.NAME, p.PASSWORD, p.BOSS, p.SOURCE, p.LAST_NAME, 
                      p.MIDDLE_NAME, p.NICK_NAME, p.LANG, p.HIRE_DATE, p.DRCM, p.MODBY, p.OBJECT_ID, p.COMPANY, p.TIME_ZONE, p.FULL_NAME, 
                      p.SYSTEM_STATUS, p.CO_POSITION, p.ROOT_COMPANY, p.IS_HEAD, p.TOOL_BOX, p.INFO_BOX, p.ADV_SEARCH, p.COLOR_KEY, 
                      p.SCREEN_TYPE
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_PEOPLE_HISTORY p ON o.ID = p.OBJECT_ID
