


CREATE VIEW dbo.A_O_TT_VERBS_HISTORY
AS
SELECT     v.ID, v.NAME, v.OBJECT_ID, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, 
                      o.REV, o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, o.ID AS OBJ_ID, v.VERB_TYPE, 
                      t.NAME AS VERB_TYPE_NAME
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_TT_VERBS_HISTORY v ON o.ID = v.OBJECT_ID LEFT OUTER JOIN
                      dbo.A_TT_VERBS_TYPE_LOOKUP t ON v.VERB_TYPE = t.ID



