
CREATE  VIEW dbo.A_O_COMPANIES
AS
SELECT     o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.WFS_ID, 
                      o.LOCKED_BY_NAME, o.CREATING_CO_NAME, dbo.A_FN_COMPANY_HAS_CHILD(o.ROOT) AS CHILDREN_COUNT, 
                      dbo.A_FN_COMPANY_GET_TOP_COMPANY(c.ID) AS TOP_COMPANY, dbo.A_FN_FILES_SHOW_ALL_XML_DATA_FOR_OBJECT(c.OBJECT_ID, 'LOGO') 
                      AS picRecord, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS ROOT_CO_NAME, c.ID, c.NAME, c.CO_TYPE, c.PARENT, c.PHONE, c.LOCATION, 
                      c.LOCATION_NAME, c.DRCM, c.MODBY, c.OBJECT_ID, c.ROOT_CO_ID, A_V_COMPANIES_APPROVED_DATA_1.NAME AS PARENT_NAME, 
                      dbo.A_COMPANIES_IMPORT.EXTERNAL_ID
FROM         dbo.A_COMPANIES_HISTORY c INNER JOIN
                      dbo.A_OBJECTS o ON c.OBJECT_ID = o.ID LEFT OUTER JOIN
                      dbo.A_COMPANIES_IMPORT ON o.ROOT = dbo.A_COMPANIES_IMPORT.ROOT_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      c.PARENT = A_V_COMPANIES_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON c.ROOT_CO_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID

