


CREATE VIEW dbo.A_O_NEEDS
AS
SELECT     n.ID, o.ID AS OBJ_ID, n.OBJECT_ID, n.DESCRIPTION, n.CUSTOMER_CO, co.NAME AS CUSTOMER_NAME, n.TIMEFRAME, n.IMPORTANCE, 
                      n.NEED_SIZE, n.ADVERTISING_START_DATE, n.ADVERTISING_STOP_DATE, n.ADVERSTISE_PUBLICLY, n.CONTACT_NAME, n.CONTACT_EMAIL, 
                      n.CONTACT_PHONE, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, 
                      o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, o.APPROVAL_DATE, 
                      dbo.A_FN_NEEDS_GET_STANDARD_SEARCH_FLAG(n.ADVERTISING_START_DATE, n.ADVERTISING_STOP_DATE, GETDATE()) AS STANDARD_SORT, 
                      dbo.A_FN_NEEDS_HAS_DOCUMENT(n.OBJECT_ID) AS HAS_DOCUMENT, DATEDIFF(d, ISNULL(n.ADVERTISING_START_DATE, o.CREATE_DATE), 
                      GETDATE()) AS AGE
FROM         dbo.A_NEEDS_HISTORY n INNER JOIN
                      dbo.A_OBJECTS o ON n.OBJECT_ID = o.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA co ON n.CUSTOMER_CO = co.ID



