



CREATE VIEW dbo.A_O_NOUN_HIER_HISTORY
AS
SELECT     HierHistory.OBJECT_ID, HierHistory.ID, HierHistory.NAME, HIER_O.LOCKED_BY, HIER_O.UNLOCKED_BY, HIER_O.CREATED_BY, 
                      HIER_O.CREATE_DATE, HIER_O.ROOT, HIER_O.REV_INFO, HIER_O.CREATING_CO, HIER_O.STATUS, HIER_O.REV, HIER_O.WFS_ID, 
                      HIER_O.LOCKED_BY_NAME, HIER_O.CREATING_CO_NAME, HIER_O.APPROVAL_ACTIVITY, HIER_O.ID AS OBJ_ID, HierHistory.ROOT_CHILD, 
                      FIRST_CHILD_O.OBJ_DESC, FIRST_CHILD_O.OBJ_TABLE AS OBJ_TYPE
FROM         dbo.A_V_APPROVED_OBJECTS FIRST_CHILD_O INNER JOIN
                      dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING FIRST_CHILD ON FIRST_CHILD_O.ID = FIRST_CHILD.APPROVED_OBJ_ID RIGHT OUTER JOIN
                      dbo.A_NOUN_HIERARCHIES_HISTORY HierHistory INNER JOIN
                      dbo.A_OBJECTS HIER_O ON HierHistory.OBJECT_ID = HIER_O.ID ON FIRST_CHILD.HIERARCHY_ID = HierHistory.ID AND 
                      FIRST_CHILD.ID = HierHistory.ROOT_CHILD




