



CREATE VIEW dbo.A_O_NOUN_HIERARCHIES
AS
SELECT     nh.ID, nh.NAME, nh.ROOT_CHILD, nh.OBJECT_ID, o.ID AS OBJ_ID, o.LOCKED_BY, o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, 
                      o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.WFS_ID, o.LOCKED_BY_NAME, o.CREATING_CO_NAME, o.APPROVAL_ACTIVITY, 
                      c.APPROVED_OBJ_ID, A_OBJECTS_1.OBJ_DESC AS CHILD_DESC
FROM         dbo.A_NOUN_HIERARCHIES_HISTORY nh INNER JOIN
                      dbo.A_OBJECTS o ON nh.OBJECT_ID = o.ID INNER JOIN
                      dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING c ON nh.ROOT_CHILD = c.ID AND nh.ID = c.HIERARCHY_ID INNER JOIN
                      dbo.A_APPROVED_OBJECTS ON c.APPROVED_OBJ_ID = dbo.A_APPROVED_OBJECTS.ID INNER JOIN
                      dbo.A_OBJECTS A_OBJECTS_1 ON dbo.A_APPROVED_OBJECTS.OBJ_REF_ID = A_OBJECTS_1.ID




