CREATE VIEW [dbo].[A_O_PURCHASES]
AS

SELECT PH.ID
	, AH.[NAME] AS PURCHASE_ORDER_NAME
	, PH.DATE_CREATED
	, PH.PURCHASE_STATUS
	, PH.ORDER_ID
	, PH.DRCM
	, PH.MODBY
	, PH.[OBJECT_ID]
	, O.LOCKED_BY
	, O.UNLOCKED_BY
	, O.CREATED_BY
	, O.CREATE_DATE
	, O.[ROOT]
	, O.CREATING_CO
	, O.[STATUS]
	, O.LOCKED_BY_NAME
	, O.CREATING_CO_NAME
	, OH.CUSTOMER_PERSON
	, OH.CUSTOMER_CO
	, OH.[DESCRIPTION]
	, PH.PURCHASE_TOTAL
	, PH.PURCHASER
	, PH.PURCHASING_CO
	, PH.CUST_PURCH_NUM
	, PH.SUP_PURCH_NUM
	, O.REV
	, PH.ACCT_FOR_ALL
	, PH.DUE_DATE
FROM DBO.A_PURCHASES_HISTORY PH
INNER JOIN DBO.A_OBJECTS O ON PH.[OBJECT_ID] = O.ID
INNER JOIN DBO.A_V_ORDERS_APPROVED_DATA OH ON PH.ORDER_ID = OH.ID
LEFT JOIN DBO.A_ACCOUNTS_HISTORY AH ON AH.[OBJECT_ID] = PH.ACCT_FOR_ALL
