



CREATE VIEW dbo.A_O_DOCUMENTS
AS
SELECT     o.LOCKED_BY AS LOCKED_BY, o.UNLOCKED_BY AS UNLOCKED_BY, o.CREATED_BY AS CREATED_BY, o.CREATE_DATE AS CREATE_DATE, 
                      o.ROOT AS ROOT, o.REV_INFO AS REV_INFO, o.CREATING_CO AS CREATING_CO, o.STATUS AS STATUS, o.REV AS REV, o.WFS_ID AS WFS_ID, d.ID, 
                      d.DOC_ID, d.NAME, d.SOURCE_ID, d.DRCM, d.MODBY, d.DELETED, d.DOC_TYPE, d.SERVER_PATH, d.APPROVED, d.DESCRIPTION, d.ACTIVE, 
                      d.CONTENTTYPE, d.OBJECT_ID, d.CREATOR_ID
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_DOCUMENTS d ON o.ID = d.OBJECT_ID




