



CREATE VIEW dbo.A_O_FORECASTS
AS
SELECT     FH.*, O.ID AS OBJ_ID, O.LOCKED_BY AS LOCKED_BY, O.UNLOCKED_BY AS UNLOCKED_BY, O.CREATED_BY AS CREATED_BY, 
                      O.CREATE_DATE AS CREATE_DATE, O.ROOT AS ROOT, O.REV_INFO AS REV_INFO, O.CREATING_CO AS CREATING_CO, O.STATUS AS STATUS, 
                      O.REV AS REV, O.WFS_ID AS WFS_ID, O.LOCKED_BY_NAME AS LOCKED_BY_NAME, O.CREATING_CO_NAME AS CREATING_CO_NAME, 
                      O.APPROVAL_ACTIVITY AS APPROVAL_ACTIVITY
FROM         dbo.A_FORECASTS_HISTORY FH INNER JOIN
                      dbo.A_OBJECTS O ON FH.OBJECT_ID = O.ID




