

CREATE VIEW dbo.A_ORDERS_WITH_QUOTE_STATUS
AS
SELECT     dbo.A_ORDERS.ID AS ORDER_ID, dbo.A_ORDERS.HISTORY_REF_ID AS ORDER_HIST_ID, dbo.A_QUOTES.ID AS QUOTE_ID, 
                      dbo.A_QUOTES_HISTORY.ID AS QUOTE_HIST_ID, dbo.A_QUOTES_HISTORY.PROGRESS, dbo.A_QUOTES_HISTORY.EXPIRATION_DATE
FROM         dbo.A_ORDERS_HISTORY INNER JOIN
                      dbo.A_ORDERS ON dbo.A_ORDERS_HISTORY.ID = dbo.A_ORDERS.HISTORY_REF_ID INNER JOIN
                      dbo.A_QUOTES INNER JOIN
                      dbo.A_QUOTES_HISTORY ON dbo.A_QUOTES.HISTORY_REF_ID = dbo.A_QUOTES_HISTORY.ID INNER JOIN
                      dbo.A_QUOTE_ORDER_LINK ON dbo.A_QUOTES_HISTORY.ID = dbo.A_QUOTE_ORDER_LINK.QUOTE_ID ON 
                      dbo.A_ORDERS.ID = dbo.A_QUOTE_ORDER_LINK.ORDER_ID


