CREATE VIEW dbo.A_V_LOGOS
AS
SELECT     dbo.A_DOCUMENT_LINK.TYPE, dbo.A_DOCUMENT_LINK.OBJECT_ID, dbo.A_DOCUMENTS.ID, dbo.A_DOCUMENTS.NAME, 
                      dbo.A_DOCUMENTS.SERVER_PATH, dbo.A_DOCUMENTS.APPROVED, dbo.A_DOCUMENTS.DESCRIPTION, dbo.A_DOCUMENTS.ACTIVE, 
                      dbo.A_DOCUMENTS.CONTENTTYPE
FROM         dbo.A_DOCUMENTS INNER JOIN
                      dbo.A_DOCUMENT_LINK ON dbo.A_DOCUMENTS.ID = dbo.A_DOCUMENT_LINK.LINKED_DOC_ID
WHERE     (dbo.A_DOCUMENT_LINK.TYPE = N'LOGO')
