

CREATE VIEW dbo.A_V_TASK_WITH_QUOTE_ORDER_LINK_INFO
AS
SELECT     dbo.A_QUOTE_ORDER_LINK.ID AS QOL_ID, dbo.A_TASKS.*, dbo.A_QUOTE_ORDER_LINK.QUOTE_ID, dbo.A_QUOTE_ORDER_LINK.ORDER_ID, 
                      dbo.A_QUOTE_ORDER_LINK.STATUS AS QOL_STATUS, dbo.A_QUOTE_ORDER_LINK.CUSTOMER, dbo.A_QUOTE_ORDER_LINK.SUPPLIER
FROM         dbo.A_TASKS INNER JOIN
                      dbo.A_QUOTE_ORDER_LINK ON dbo.A_TASKS.ID = dbo.A_QUOTE_ORDER_LINK.TASK_ID


