CREATE VIEW dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK
AS
SELECT     dbo.A_ACCOUNTS.ID, dbo.A_ACCOUNTS.HISTORY_REF_ID, dbo.A_ACCOUNTS_HISTORY.OBJECT_ID, dbo.A_ACCOUNTS_HISTORY.NAME, 
                      dbo.A_ACCOUNTS_HISTORY.REFERENCE_PO, dbo.A_ACCOUNTS_HISTORY.REFERENCE_NAME, dbo.A_ACCOUNTS_HISTORY.OPEN_DATE, 
                      dbo.A_ACCOUNTS_HISTORY.SUPPLIER_CO, dbo.A_ACCOUNTS_HISTORY.CLOSE_DATE, dbo.A_ACCOUNTS_HISTORY.CUSTOMER_CO, 
                      dbo.A_ACCOUNTS_HISTORY.CUSTOMER_BILL_CO, dbo.A_ACCOUNTS_HISTORY.MAXIMUM_USES, 
                      dbo.A_ACCOUNTS_HISTORY.TOTAL_PURCHASE_LIMIT, dbo.A_ACCOUNTS_HISTORY.CREDIT_LIMIT, dbo.A_ACCOUNTS_HISTORY.APPROVAL_WF, 
                      dbo.A_ACCOUNTS_HISTORY.INVOICE_TRIGGER, dbo.A_ACCOUNTS_HISTORY.INVOICE_PERIOD_NUMBER, 
                      dbo.A_ACCOUNTS_HISTORY.INVOICE_PERIOD_TYPE, dbo.A_ACCOUNTS_HISTORY.FIRST_INVOICE_DATE, 
                      dbo.A_ACCOUNTS_HISTORY.NEXT_INVOICE_DATE, dbo.A_ACCOUNTS_HISTORY.PAYMENT_GRACE_PERIOD, 
                      dbo.A_ACCOUNTS_HISTORY.LATE_FEE_PERCENTAGE, dbo.A_ACCOUNTS_HISTORY.REAPPLY_LATE_FEE, dbo.A_ACCOUNTS_HISTORY.DRCM, 
                      dbo.A_ACCOUNTS_HISTORY.MODBY, dbo.A_ACCOUNTS_HISTORY.ACCT_TYPE, dbo.A_ACCOUNTS_HISTORY.TOTAL_PURCHASES, 
                      dbo.A_ACCOUNTS_HISTORY.BALANCE, dbo.A_ACCOUNTS_HISTORY.AMT_INVOICED, dbo.A_ACCOUNTS_HISTORY.ACCT_STATUS, 
                      dbo.A_ACCOUNTS_HISTORY.PRODUCT_ID, dbo.A_ACCOUNTS_HISTORY.PARENT_ACCOUNT, dbo.A_ACCOUNTS_HISTORY.LABOR_INCLUDED, 
                      dbo.A_ACCOUNTS_HISTORY.CONSUMABLES_INCLUDED, dbo.A_ACCOUNTS_HISTORY.NONCONSUMABLE_INCLUDED, 
                      dbo.A_ACCOUNTS_HISTORY.HAS_CHILD, dbo.A_ACCOUNTS_HISTORY.INVOICED_BALANCE, dbo.A_ACCOUNTS_HISTORY.UNINVOICED_BALANCE, 
                      dbo.A_ACCOUNTS_HISTORY.TOTAL_CREDITS, dbo.A_ACCOUNTS_HISTORY.TOTAL_DEBITS, dbo.A_ACCOUNTS_HISTORY.BILLING_EMAIL
FROM         dbo.A_ACCOUNTS INNER JOIN
                      dbo.A_ACCOUNTS_HISTORY ON dbo.A_ACCOUNTS.HISTORY_REF_ID = dbo.A_ACCOUNTS_HISTORY.ID
