



CREATE VIEW dbo.A_V_PROCEDURE_STEP_PREV_W_PRNT_ORDER
AS
SELECT     dbo.A_PROCEDURE_STEP_PRECEDING_STEPS.MY_STEP, dbo.A_PROCEDURE_STEP_PRECEDING_STEPS.PREV_STEP, 
                      dbo.A_PROCEDURE_STEPS.PRINT_ORDER
FROM         dbo.A_PROCEDURE_STEPS INNER JOIN
                      dbo.A_PROCEDURE_STEP_PRECEDING_STEPS ON dbo.A_PROCEDURE_STEPS.ID = dbo.A_PROCEDURE_STEP_PRECEDING_STEPS.PREV_STEP




