CREATE VIEW dbo.A_V_SERVICE_CALL_PERSON_TIME_DATA
AS
SELECT     WORKER.ID AS PERSON_ID, dbo.A_PEOPLE_HISTORY.NAME, dbo.A_PEOPLE_HISTORY.LAST_NAME, CONVERT(dateTime, CONVERT(varchar(10), 
                      tim.MO) + '/' + CONVERT(varchar(10), tim.D) + '/' + CONVERT(varchar(10), tim.YR)) AS ACTUAL_DATE, tim.HOUR_TYPE, tim.WEEKLY_ID, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.STATUS, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.WORK_TYPE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.WORK_TYPE_NAME, dbo.A_SERVICE_CALLS_WORK_TYPES.APPROVER_ROLE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.PAYER_ROLE, dbo.A_PEOPLE_HISTORY.BOSS, 
                      dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.RECIEVABLE_ROLE, cust.NAME AS CUSTOMER_NAME, sup.NAME AS SUPPLIER_NAME, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ACTUAL_START_DATE, dbo.A_SERVICE_CALLS_WORK_TYPES.HOUR_RATE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.OT_RATE, dbo.A_SERVICE_CALLS_WORK_TYPES.TAX_RATE, dbo.A_SERVICE_CALLS_WORK_TYPES.HIDE, 
                      dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME AS BOSS_NAME, dbo.A_FN_MAKE_ZERO_NULL(tim.HOURS) AS HOURS, tim.ID AS TID, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.SUPPLIER_ID, dbo.A_SERVICE_CALLS_WORK_TYPES.CUSTOMER_ID, 
                      dbo.A_PEOPLE_SEARCH_TABLE.LOCATION_ID, dbo.A_PEOPLE_SEARCH_TABLE.LOCATION_NAME
FROM         dbo.A_SERVICE_CALL_WORK_TIME tim INNER JOIN
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS ON tim.WEEKLY_ID = dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID INNER JOIN
                      dbo.A_PEOPLE WORKER ON dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.WORKER_ID = WORKER.ID INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON WORKER.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_SERVICE_CALLS_WORK_TYPES ON 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.WORK_TYPE = dbo.A_SERVICE_CALLS_WORK_TYPES.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA cust ON dbo.A_SERVICE_CALLS_WORK_TYPES.CUSTOMER_ID = cust.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA sup ON dbo.A_SERVICE_CALLS_WORK_TYPES.SUPPLIER_ID = sup.ID LEFT OUTER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE ON dbo.A_PEOPLE_HISTORY.ID = dbo.A_PEOPLE_SEARCH_TABLE.ID LEFT OUTER JOIN
                      dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE ON 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.SUPPLIER_ID = dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.COMPANY_ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ON dbo.A_PEOPLE_HISTORY.BOSS = dbo.A_V_PEOPLE_APPROVED_DATA.ID
WHERE     (WORKER.STATUS = 'APPROVED')