


CREATE VIEW dbo.A_V_SERVICE_CALL_ACC_RECIEVABLE_ROLE_NAMES
AS
SELECT     dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.COMPANY_ID, dbo.A_APPROVED_ROLES.NAME AS show, 
                      dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.RECIEVABLE_ROLE AS [value]
FROM         dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE INNER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.RECIEVABLE_ROLE = dbo.A_APPROVED_ROLES.ID