



CREATE VIEW dbo.A_V_Z_FAVORITES_PARTS_ITEMS
AS
SELECT     dbo.A_PEOPLES_FAVORITE_GROUPS.ID AS GROUP_ID, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.PERSON, dbo.A_PEOPLES_FAVORITES.ID, dbo.A_PEOPLES_FAVORITES.NUM, 
                      dbo.A_V_PART_DATA_BY_APPROVED_DATA.NAME
FROM         dbo.A_PEOPLES_FAVORITES INNER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS ON dbo.A_PEOPLES_FAVORITES.[GROUP] = dbo.A_PEOPLES_FAVORITE_GROUPS.ID INNER JOIN
                      dbo.A_V_PART_DATA_BY_APPROVED_DATA ON dbo.A_PEOPLES_FAVORITES.ITEM = dbo.A_V_PART_DATA_BY_APPROVED_DATA.ID