


CREATE VIEW dbo.A_V_SERVICE_CALL_STATUS_HISTORY_DATA
AS
SELECT     dbo.A_SERVICE_CALLS_STATUS_HISTORY.WEEKLY_ID, dbo.A_SERVICE_CALLS_STATUS_HISTORY.STATUS_CHANGED_TO, 
                      dbo.A_SERVICE_CALLS_STATUS_HISTORY.DATE_CHANGED, dbo.A_SERVICE_CALLS_STATUS_HISTORY.CHANGED_BY, 
                      dbo.A_SERVICE_CALLS_STATUS_HISTORY.REASON, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS CHANGED_BY_NAME, 
                      dbo.A_SERVICE_CALLS_STATUS_HISTORY.REASON_TYPE
FROM         dbo.A_SERVICE_CALLS_STATUS_HISTORY INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_SERVICE_CALLS_STATUS_HISTORY.CHANGED_BY = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID



