



CREATE VIEW dbo.A_V_POP_FILL_DISCUSSION_INVITED_COMPANY
AS
SELECT     dbo.A_DISCUSSION_INV_COMPANY.COMPANY_ID AS C_ID, dbo.A_DISCUSSION_INV_COMPANY.DISCUSSION_ID AS D_ID, 
                      dbo.A_APPROVED_COMPANIES.NAME AS COMPANY_NAME
FROM         dbo.A_APPROVED_COMPANIES INNER JOIN
                      dbo.A_DISCUSSION_INV_COMPANY ON dbo.A_APPROVED_COMPANIES.ID = dbo.A_DISCUSSION_INV_COMPANY.COMPANY_ID




