CREATE VIEW dbo.A_V_ACTUAL_PARTS_WITH_TASK_ID
AS
SELECT     dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.*, dbo.A_ACTUAL_PARTS_CALL_DATA.ROOT_TASK AS TASK_ID
FROM         dbo.A_V_ACTUAL_PARTS_APPROVED_DATA INNER JOIN
                      dbo.A_ACTUAL_PARTS_CALL_DATA ON dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID = dbo.A_ACTUAL_PARTS_CALL_DATA.ACTUAL_PART_ID
