


CREATE VIEW dbo.A_V_PART_TYPES_APPROVED_DATA
AS
SELECT     dbo.A_PART_TYPES.ID, dbo.A_PART_TYPES.HISTORY_REF_ID, dbo.A_PART_TYPES_HISTORY.NAME, dbo.A_PART_TYPES_HISTORY.SPARE, 
                      dbo.A_PART_TYPES_HISTORY.CONSUMABLE, dbo.A_PART_TYPES_HISTORY.DRCM, dbo.A_PART_TYPES_HISTORY.MODBY, 
                      dbo.A_PART_TYPES_HISTORY.OBJECT_ID, dbo.A_PART_TYPES_HISTORY.UNIT, dbo.A_PART_TYPES_HISTORY.UNIT_SHIPPING_WEIGHT
FROM         dbo.A_PART_TYPES INNER JOIN
                      dbo.A_PART_TYPES_HISTORY ON dbo.A_PART_TYPES.HISTORY_REF_ID = dbo.A_PART_TYPES_HISTORY.ID



