


CREATE VIEW dbo.A_V_PROCEDURE_ROLES_TO_VIEW
AS
SELECT     dbo.A_PROCEDURES_HISTORY.ID AS PROCEDURE_ID, dbo.A_APPROVED_ROLES.NAME AS ROLE_NAME, 
                      dbo.A_PROCEDURES_HISTORY.OBJECT_ID AS PROCEDURE_OBJ_ID, dbo.A_APPROVED_ROLES.ID AS ROLE_ID, 
                      dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP
FROM         dbo.A_PROCEDURES_HISTORY INNER JOIN
                      dbo.A_PROCEDURE_OBJECT_LINK ON dbo.A_PROCEDURES_HISTORY.ID = dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID INNER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID = dbo.A_APPROVED_ROLES.ID
WHERE     (dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP = N'ROLE_TO_VIEW')



