


CREATE VIEW dbo.A_V_DISCUSSION_GET_RESPONSE_DATA_BY_ID
AS
SELECT     dbo.A_DISCUSSION_RESPONSE.ID, dbo.A_DISCUSSION_RESPONSE.DRCM, dbo.A_DISCUSSION_RESPONSE.RESPONSE, 
                      dbo.A_DISCUSSION_RESPONSE.WRITER AS INITIATOR, dbo.A_DISCUSSION_ATTACHMENTS.DOC_ID, 
                      dbo.A_DISCUSSION_ATTACHMENTS.RESPONSE_ID, dbo.A_DISCUSSION_RESPONSE.COLOR, 
                      dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS WRITER_NAME, dbo.A_DISCUSSION_RESPONSE.DISCUSSION_ID, 
                      dbo.A_DISCUSSION_RESPONSE.PARENT_ID, dbo.A_DISCUSSIONS.STATUS
FROM         dbo.A_DISCUSSION_RESPONSE INNER JOIN
                      dbo.A_DISCUSSIONS ON dbo.A_DISCUSSION_RESPONSE.DISCUSSION_ID = dbo.A_DISCUSSIONS.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_DISCUSSION_RESPONSE.WRITER = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID LEFT OUTER JOIN
                      dbo.A_DISCUSSION_ATTACHMENTS ON dbo.A_DISCUSSION_RESPONSE.ID = dbo.A_DISCUSSION_ATTACHMENTS.RESPONSE_ID