CREATE VIEW dbo.A_V_PROCEDURE_STEPS_WITH_PREVIOUS_STEP
AS
SELECT     dbo.A_PROCEDURE_STEP_PRECEDING_STEPS.PREV_STEP AS PREV_STEP, dbo.A_PROCEDURE_STEPS.ID, 
                      dbo.A_PROCEDURE_STEPS.PROCEDURE_ID, dbo.A_PROCEDURE_STEPS.STEP_TEXT, dbo.A_PROCEDURE_STEPS.START_ON_COUNTER, 
                      dbo.A_PROCEDURE_STEPS.COUNTER_VALUE, dbo.A_PROCEDURE_STEPS.COUNTER_UNIT, dbo.A_PROCEDURE_STEPS.REL_OR_ABS, 
                      dbo.A_PROCEDURE_STEPS.FROM_START_OR_STOP, dbo.A_PROCEDURE_STEPS.SYSTEM_TASK, dbo.A_PROCEDURE_STEPS.DESTINATION, 
                      dbo.A_PROCEDURE_STEPS.SPECIFIC_LOCATION, dbo.A_PROCEDURE_STEPS.REFERENCE_VERB, 
                      dbo.A_PROCEDURE_STEPS.REFERENCE_OBJECT, dbo.A_PROCEDURE_STEPS.COMMENTS, dbo.A_PROCEDURE_STEPS.GOTO_STEP, 
                      dbo.A_PROCEDURE_STEPS.GOTO_STEP_ID, dbo.A_PROCEDURE_STEPS.CYCLES, dbo.A_PROCEDURE_STEPS.CYCLE_ON_COUNTER, 
                      dbo.A_PROCEDURE_STEPS.CYCLE_COUNT, dbo.A_PROCEDURE_STEPS.CYCLE_UNIT, dbo.A_PROCEDURE_STEPS.DRCM, 
                      dbo.A_PROCEDURE_STEPS.MODBY, dbo.A_PROCEDURE_STEPS.PRINT_ORDER, dbo.A_PROCEDURE_STEPS.OLD_PROCEDURE_ID, 
                      dbo.A_PROCEDURE_STEPS.OLD_STEP_ID, dbo.A_PROCEDURE_STEPS.DURATION, dbo.A_PROCEDURE_STEPS.DURATION_TYPE, 
                      dbo.A_PROCEDURE_STEPS.DATE_LAST_MODIFIED
FROM         dbo.A_PROCEDURE_STEPS LEFT OUTER JOIN
                      dbo.A_PROCEDURE_STEP_PRECEDING_STEPS ON dbo.A_PROCEDURE_STEPS.ID = dbo.A_PROCEDURE_STEP_PRECEDING_STEPS.MY_STEP
