CREATE VIEW dbo.A_V_TASK_REF_FILES
AS
SELECT     T.ID AS TASK_ID, T.DESCRIPTION, TRF.FILE_ID, TRF.STATUS, TRF.DELETED_BY_NAME, TRF.DATE_DELETED, TRF.DELETED_BY, 
                      D.NAME AS FILE_NAME, D.DESCRIPTION AS FILE_DESCRIPTION, TRF.ID, D.SERVER_PATH AS PATH, D.CONTENTTYPE, D.DRCM
FROM         dbo.A_TASK_REF_FILES TRF INNER JOIN
                      dbo.A_DOCUMENTS D ON TRF.FILE_ID = D.ID INNER JOIN
                      dbo.A_TASKS T ON TRF.TASK_ID = T.ID
