


CREATE VIEW dbo.A_V_MEETING_SEARCH
AS
SELECT     m.MEETING_NAME, m.START_DATE, m.STOP_DATE, m.OWNER, m.HOST, m.TIME_KEEP, m.SCRIBE, m.WEB_LOCATION, m.DATE_CREATED, 
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID.NAME AS LOCATION_NAME, m.SETTING, 
                      dbo.A_FN_MEETING_GET_STANDARD_SEARCH_FLAG(m.START_DATE, m.STOP_DATE, GETDATE()) AS STANDARD_SEARCH, m.ID, 
                      m.DATE_EMAIL_SENT, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS HOST_NAME
FROM         dbo.A_MEETINGS m INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON m.HOST = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID ON m.LOCATION = dbo.A_V_LOCATIONS_BY_APPROVED_ID.ID



