
CREATE VIEW dbo.A_V_OBJECT_REVISION_DATA
AS
SELECT     dbo.A_OBJECTS.ID AS OBJECT_ID, dbo.A_OBJECTS.OBJ_ID AS HIST_ID, dbo.A_OBJECTS.ROOT, dbo.A_OBJECTS.CREATED_BY, 
                      dbo.A_PEOPLE_HISTORY.FULL_NAME AS CREATOR_NAME, dbo.A_OBJECTS.REV_INFO, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.CREATE_DATE, 
                      dbo.A_OBJECTS.APPROVAL_DATE, dbo.A_WORKFLOWS.NAME AS WF_NAME, dbo.A_OBJECTS.REV
FROM         dbo.A_PEOPLE_HISTORY INNER JOIN
                      dbo.A_PEOPLE ON dbo.A_PEOPLE_HISTORY.ID = dbo.A_PEOPLE.HISTORY_REF_ID INNER JOIN
                      dbo.A_OBJECTS INNER JOIN
                      dbo.A_WORKFLOWS_STARTED ON dbo.A_OBJECTS.WFS_ID = dbo.A_WORKFLOWS_STARTED.ID INNER JOIN
                      dbo.A_WORKFLOWS ON dbo.A_WORKFLOWS_STARTED.WF_ID = dbo.A_WORKFLOWS.ID ON dbo.A_PEOPLE.ID = dbo.A_OBJECTS.CREATED_BY

