CREATE VIEW dbo.A_V_PROCEDURE_STEPS_WITH_LABOR_AND_PRINT_ORDER
AS
SELECT     dbo.A_V_PROCEDURE_STEP_PREV_W_PRNT_ORDER.PREV_STEP, 
                      dbo.A_V_PROCEDURE_STEP_PREV_W_PRNT_ORDER.PRINT_ORDER AS P_ORDER, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.LABOR_ROLE, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.RELATIONSHIP, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.OWNER_ROLE_ID, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.OWNER_LABOR_TIME, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.OWNER_LABOR_TYPE, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.ID, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.PROCEDURE_ID, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.STEP_TEXT, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.START_ON_COUNTER, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.COUNTER_VALUE, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.COUNTER_UNIT, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.REL_OR_ABS, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.FROM_START_OR_STOP, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.SYSTEM_TASK, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.DESTINATION, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.SPECIFIC_LOCATION, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.REFERENCE_VERB, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.REFERENCE_OBJECT, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.COMMENTS, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.GOTO_STEP, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.GOTO_STEP_ID, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.CYCLES, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.CYCLE_ON_COUNTER, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.CYCLE_COUNT, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.CYCLE_UNIT, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.DRCM, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.MODBY, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.PRINT_ORDER, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.OLD_PROCEDURE_ID, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.OLD_STEP_ID, dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.DURATION, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.DURATION_TYPE, 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.DATE_LAST_MODIFIED
FROM         dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR LEFT OUTER JOIN
                      dbo.A_V_PROCEDURE_STEP_PREV_W_PRNT_ORDER ON 
                      dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR.ID = dbo.A_V_PROCEDURE_STEP_PREV_W_PRNT_ORDER.MY_STEP
