


CREATE VIEW dbo.A_V_PROJECT_SEARCH_ALL_ALLOWED
AS
SELECT     p.ID, p.NAME, p.DATE_CREATED, p.ORIGINAL_PLANNED_STOP_DATE, p.CURRENT_PLANNED_STOP_DATE, p.ACTUAL_STOP_DATE, 
                      p.PRIORITY_LEVEL AS PRIORITY, p.LEADER, p.SUMMARY, p.STATUS, dbo.A_PROJECT_ALLOWED_PEOPLE.PEOPLE_ID AS INV_PEOPLE_ID, 
                      dbo.A_PROJECT_ALLOWED_ROLES.ROLE_ID, dbo.A_PROJECT_ALLOWED_COMPANIES.COMPANY_ID, 
                      dbo.A_PROJECT_SPONSORS.PEOPLE_ID AS SPONSOR_ID, dbo.A_PROJECT_MEMBERS.PEOPLE_ID AS MEMBER_ID, p.INITIATOR, 
                      dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS CURRENT_LEADER_NAME
FROM         dbo.A_PROJECTS p LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON p.LEADER = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID LEFT OUTER JOIN
                      dbo.A_PROJECT_MEMBERS ON p.ID = dbo.A_PROJECT_MEMBERS.PROJECT_ID LEFT OUTER JOIN
                      dbo.A_PROJECT_SPONSORS ON p.ID = dbo.A_PROJECT_SPONSORS.PROJECT_ID LEFT OUTER JOIN
                      dbo.A_PROJECT_ALLOWED_COMPANIES ON p.ID = dbo.A_PROJECT_ALLOWED_COMPANIES.PROJECT_ID LEFT OUTER JOIN
                      dbo.A_PROJECT_ALLOWED_PEOPLE ON p.ID = dbo.A_PROJECT_ALLOWED_PEOPLE.PROJECT_ID LEFT OUTER JOIN
                      dbo.A_PROJECT_ALLOWED_ROLES ON p.ID = dbo.A_PROJECT_ALLOWED_ROLES.PROJECT_ID



