CREATE VIEW dbo.A_V_PURCHASE_ITEM_WITH_SUP_AND_CUST
AS
SELECT     dbo.A_PURCHASES_HISTORY.PURCHASING_CO AS CUST_ID, dbo.A_V_PURCHASE_ITEMS_WITH_SUPPLIER_ID.SUPPLIER_ID, 
                      dbo.A_ORDER_ITEMS.ID, dbo.A_ORDER_ITEMS.ACCOUNT_ID
FROM         dbo.A_ORDER_ITEMS INNER JOIN
                      dbo.A_V_PURCHASE_ITEMS_WITH_SUPPLIER_ID ON dbo.A_ORDER_ITEMS.ID = dbo.A_V_PURCHASE_ITEMS_WITH_SUPPLIER_ID.ID INNER JOIN
                      dbo.A_PURCHASES_HISTORY ON dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID = dbo.A_PURCHASES_HISTORY.ID
