


CREATE VIEW dbo.A_V_THEORY_APPROVED_DATA
AS
SELECT     dbo.A_THEORY.ID, dbo.A_THEORY.HISTORY_REF_ID, dbo.A_THEORY_HISTORY.OBJECT_ID, dbo.A_THEORY_HISTORY.NAME, 
                      dbo.A_THEORY_HISTORY.COMMENTS, dbo.A_THEORY_HISTORY.SECURITY_LEVEL, dbo.A_THEORY_HISTORY.CREATING_DEPT, 
                      dbo.A_OBJECTS.CREATING_CO, dbo.A_THEORY_HISTORY.DRCM, dbo.A_THEORY_HISTORY.MODBY
FROM         dbo.A_THEORY INNER JOIN
                      dbo.A_THEORY_HISTORY ON dbo.A_THEORY.HISTORY_REF_ID = dbo.A_THEORY_HISTORY.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_THEORY_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID



