


CREATE VIEW dbo.A_V_PROJECT_DATA
AS
SELECT     dbo.A_PROJECTS.ID, dbo.A_PROJECTS.DATE_CREATED, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS INITIATOR_NAME, dbo.A_PROJECTS.NAME, 
                      dbo.A_PROJECTS.PRIORITY_LEVEL, dbo.A_PROJECTS.OBJECTIVE, dbo.A_PROJECTS.LEADER, 
                      A_V_PEOPLE_BY_NTLOGIN_1.P_NAME AS LEADER_NAME, dbo.A_SECURITY_LEVELS.NAME AS SECURITY_LEVEL_NAME, 
                      dbo.A_PROJECTS.SECURITY_LEVEL, dbo.A_PROJECTS.ORIGINAL_PLANNED_STOP_DATE, dbo.A_PROJECTS.CURRENT_PLANNED_STOP_DATE, 
                      dbo.A_PROJECTS.MONTH_GOALS, dbo.A_PROJECTS.ACTUAL_STOP_DATE, dbo.A_PROJECTS.ISSUES, dbo.A_PROJECTS.SUMMARY, 
                      dbo.A_PROJECTS.INITIATOR
FROM         dbo.A_PROJECTS LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_PROJECTS.INITIATOR = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN A_V_PEOPLE_BY_NTLOGIN_1 ON dbo.A_PROJECTS.LEADER = A_V_PEOPLE_BY_NTLOGIN_1.P_ID LEFT OUTER JOIN
                      dbo.A_SECURITY_LEVELS ON dbo.A_PROJECTS.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID



