CREATE VIEW dbo.A_V_ROLES_APPROVED_DPARTMENT_SUB_ROLES
AS
SELECT     dbo.A_V_ROLES_APPROVED_DATA_QUICK.ID, dbo.A_ROLES_DEPARTMENT_SUB_ROLES.DEPARTMENT, 
                      dbo.A_ROLES_DEPARTMENT_SUB_ROLES.SUB_ROLE
FROM         dbo.A_ROLES_DEPARTMENT_SUB_ROLES INNER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA_QUICK ON 
                      dbo.A_ROLES_DEPARTMENT_SUB_ROLES.ROLE_HIST_ID = dbo.A_V_ROLES_APPROVED_DATA_QUICK.HISTORY_REF_ID
