



CREATE VIEW dbo.A_V_MEETING_GET_HOST_NAME
AS
SELECT     dbo.A_APPROVED_PEOPLE.FULL_NAME AS HOST_NAME, dbo.A_MEETINGS.ID, dbo.A_MEETINGS.HOST AS H_ID
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_MEETINGS ON dbo.A_APPROVED_PEOPLE.ID = dbo.A_MEETINGS.HOST




