



CREATE VIEW dbo.A_V_POP_FILL_SURVEY_INVITED_ROLES
AS
SELECT     dbo.A_SURVEY_INV_ROLE.SURVEY_ID AS S_ID, dbo.A_SURVEY_INV_ROLE.ROLE_ID AS R_ID, 
                      dbo.A_APPROVED_ROLES.NAME AS ROLE_NAME
FROM         dbo.A_SURVEY_INV_ROLE INNER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_SURVEY_INV_ROLE.ROLE_ID = dbo.A_APPROVED_ROLES.ID




