



CREATE VIEW dbo.A_V_MEETING_LOC_WITH_NAMES
AS
SELECT     dbo.A_V_LOCATION_WITH_NAME.L_ID, dbo.A_V_LOCATION_WITH_NAME.LOCATION_NAME, dbo.A_MEETINGS.ID AS M_ID
FROM         dbo.A_MEETINGS LEFT OUTER JOIN
                      dbo.A_V_LOCATION_WITH_NAME ON dbo.A_MEETINGS.LOCATION = dbo.A_V_LOCATION_WITH_NAME.L_ID




