CREATE VIEW [dbo].[A_V_PARTS_APPROVED_DATA]
AS
SELECT     p.ID, p.PARTS_HISTORY_ID AS HISTORY_REF_ID, ph.UNIT, ph.NAME, ph.PART_TYPE, ph.SPARE, ph.CONSUMABLE, ph.TRACK_FROM_START, 
                      ph.DRCM, ph.MODBY, ph.COMPANY, ph.OBJECT_ID, ph.COMPANY_NAME, ph.PART_TYPE_NAME, ph.COMPANY_PART_NUMBER, 
                      ph.UNIT_SHIPPING_WEIGHT, ph.SUPPLIER_SEE_INSTALL_BASE, ph.SUPPLIER_SEE_AVAILABILITY, ph.CUSTOMER_SEE_AVAILABILITY, 
                      ph.WEIGHT_TYPE, u.NAME AS WEIGHT_TYPE_NAME, ph.NAME + '[' + ph.COMPANY_PART_NUMBER + '][ID:' + o.ID + ']' AS NAME_COMBO, o.STATUS, ph.OEM_PART_NUMBER
FROM         dbo.A_PARTS p INNER JOIN
                      dbo.A_PARTS_HISTORY ph ON p.PARTS_HISTORY_ID = ph.ID INNER JOIN
                      dbo.A_OBJECTS o ON ph.OBJECT_ID = o.ID LEFT OUTER JOIN
                      dbo.A_UNIT_TYPES u ON ph.WEIGHT_TYPE = u.ID
WHERE     (o.STATUS = 'APPROVED')

