CREATE VIEW [dbo].[A_V_DELIVERY_TICKET_PURCH_ITEM_INFO]
AS

SELECT DBO.A_V_PRODUCTS_APPROVED_DATA.[NAME] AS PROD_NAME
	, PURCHASE_ITEM.QTY AS PURCHASE_QTY
	, PURCHASE_ITEM.PURCHASE_HIST_ID
	, DBO.A_V_PROCEDURES_APPROVED_DATA.[NAME] AS PROC_NAME
	, DBO.A_V_PRODUCTS_APPROVED_DATA.HISTORY_REF_ID AS PROD_HIST_ID
	, PURCHASE_ITEM.CUST_LINE_ITEM
	, PURCHASE_ITEM.PARENT
	, PURCHASE_ITEM.MATERIAL_TRANSFER_TICKET_NUMBER
	, DBO.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL
	, DBO.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC
	, DBO.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_TYPE_NAME
	, DBO.A_V_ACTUAL_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER
	, PURCHASE_ITEM.ID AS PURCH_ITEM_ID
	, DBO.A_PURCHASES_HISTORY.CUST_PURCH_NUM
	, DBO.A_PURCHASES_HISTORY.[OBJECT_ID] AS PURCHASE_ID
	, FILLS.DONT_BILL
	, DBO.A_V_ACTUAL_PARTS_APPROVED_DATA.ID AS ACTUAL_PART_ID
	, DBO.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID
	, DBO.A_V_ACCOUNTS_APPROVED_DATA_QUICK.SUPPLIER_CO AS ACCT_SUPPLIER
	, DBO.A_V_ACCOUNTS_APPROVED_DATA_QUICK.CUSTOMER_CO AS ACCT_CUSTOMER
	, -1 AS PARENT_ID
	, -1 AS ID
FROM DBO.A_FILLS FILLS
INNER JOIN DBO.A_ORDER_ITEMS PURCHASE_ITEM ON FILLS.PURCH_ITEM_ID = PURCHASE_ITEM.ID
INNER JOIN DBO.A_PURCHASES_HISTORY ON PURCHASE_ITEM.PURCHASE_HIST_ID = DBO.A_PURCHASES_HISTORY.ID
INNER JOIN DBO.A_V_ACCOUNTS_APPROVED_DATA_QUICK ON PURCHASE_ITEM.ACCOUNT_ID = DBO.A_V_ACCOUNTS_APPROVED_DATA_QUICK.ID
LEFT OUTER JOIN DBO.A_V_ACTUAL_PARTS_APPROVED_DATA ON FILLS.FILL_OBJ_ID = DBO.A_V_ACTUAL_PARTS_APPROVED_DATA.ID
LEFT OUTER JOIN DBO.A_V_PRODUCTS_APPROVED_DATA
INNER JOIN DBO.A_V_PROCEDURES_APPROVED_DATA ON DBO.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID = DBO.A_V_PROCEDURES_APPROVED_DATA.ID ON PURCHASE_ITEM.PRODUCT_ID = DBO.A_V_PRODUCTS_APPROVED_DATA.ID
WHERE PURCHASE_ITEM.PARENT IS NULL

