

CREATE VIEW dbo.A_V_FILLS_WITH_PRECEDENTS
AS
SELECT     PREV_FILL.ID AS PREV_ID, FOL_FILL.ID AS FOL_ID, PREV_FILL.TASK_ID AS PREV_TASK_ID, FOL_FILL.TASK_ID AS FOL_TASK_ID, 
                      FOL_PURCH_ITEM.DEST AS FOL_DEST, PREV_PURCH_ITEM.DEST AS PREV_DEST, FOL_PURCH_ITEM.PURCHASE_HIST_ID
FROM         dbo.A_FILLS FOL_FILL INNER JOIN
                      dbo.A_ORDER_ITEMS FOL_PURCH_ITEM ON FOL_FILL.PURCH_ITEM_ID = FOL_PURCH_ITEM.ID LEFT OUTER JOIN
                      dbo.A_ORDER_ITEMS PREV_PURCH_ITEM INNER JOIN
                      dbo.A_ORDER_ITEM_PRECEDENTS Precedents ON PREV_PURCH_ITEM.ID = Precedents.PREV INNER JOIN
                      dbo.A_FILLS PREV_FILL ON PREV_PURCH_ITEM.ID = PREV_FILL.PURCH_ITEM_ID ON FOL_PURCH_ITEM.ID = Precedents.FOL


