CREATE VIEW dbo.A_V_PURCHASES_WITH_SUPPLIER_QUOTES
AS
SELECT     ph.ID AS PURCH_HIST_ID, ph.ORDER_ID, q.ID AS QUOTE_ID, qh.DESCRIPTION, qh.CUSTOMER_PERSON, qh.CUSTOMER_CO, qh.SUPPLIER_ID, 
                      qh.CREATION_DATE, c.NAME AS SUPPLIER_NAME, qh.ID AS QH_ID, dbo.A_PURCHASE_QUOTE_STATUS.STATUS AS ITEM_STATUS, 
                      dbo.A_PURCHASE_QUOTE_STATUS.ID, ph.PURCHASE_STATUS, ph.OBJECT_ID, dbo.A_OBJECTS.STATUS AS PURCHASE_OBJECT_STATUS, 
                      dbo.A_OBJECTS.LOCKED_BY, A_V_COMPANIES_APPROVED_DATA_1.NAME AS ROOT_CO_NAME, ph.CUST_PURCH_NUM, 
                      ph.SUP_PURCH_NUM
FROM         dbo.A_ORDERS o INNER JOIN
                      dbo.A_PURCHASES_HISTORY ph ON o.ID = ph.ORDER_ID INNER JOIN
                      dbo.A_QUOTES_HISTORY qh INNER JOIN
                      dbo.A_QUOTES q ON qh.ID = q.HISTORY_REF_ID ON o.ID = qh.ORDER_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA c ON qh.SUPPLIER_ID = c.ID INNER JOIN
                      dbo.A_PURCHASE_QUOTE_STATUS ON ph.ID = dbo.A_PURCHASE_QUOTE_STATUS.PURCHASE_ID AND 
                      qh.ID = dbo.A_PURCHASE_QUOTE_STATUS.QUOTE_ID INNER JOIN
                      dbo.A_OBJECTS ON ph.OBJECT_ID = dbo.A_OBJECTS.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON c.ROOT_CO = A_V_COMPANIES_APPROVED_DATA_1.ID
