

CREATE VIEW dbo.A_V_FORECAST_ITEMS_WITH_FORECAST_DATA
AS
SELECT     dbo.A_FORECAST_ITEMS.ACCOUNT_ID, dbo.A_FORECAST_ITEMS.ID AS FORECAST_ITEM_ID, 
                      dbo.A_FORECASTS_HISTORY.ID AS FORECAST_HIST_ID, dbo.A_FORECASTS_HISTORY.START_MONTH, dbo.A_FORECASTS_HISTORY.START_YEAR, 
                      dbo.A_FORECASTS_HISTORY.STOP_MONTH, dbo.A_FORECASTS_HISTORY.STOP_YEAR, dbo.A_FORECASTS_HISTORY.START_DATE, 
                      dbo.A_FORECASTS_HISTORY.STOP_DATE, dbo.A_FORECAST_ITEMS.F_TYPE AS FI_TYPE, dbo.A_FORECAST_ITEMS.QTY, 
                      dbo.A_FORECAST_ITEMS.F_AMT, dbo.A_FORECAST_ITEMS.PERCENT_OF_REV, dbo.A_FORECAST_ITEMS.PROGRESS, 
                      dbo.A_FORECAST_ITEMS.AMT_INVOICED, dbo.A_V_ACCOUNTS_APPROVED_DATA.NAME, dbo.A_V_ACCOUNTS_APPROVED_DATA.SUPPLIER_CO, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA.CUSTOMER_CO, dbo.A_V_ACCOUNTS_APPROVED_DATA.PRODUCT_ID
FROM         dbo.A_FORECASTS_HISTORY INNER JOIN
                      dbo.A_FORECAST_ITEMS ON dbo.A_FORECASTS_HISTORY.ID = dbo.A_FORECAST_ITEMS.FORECAST_ID INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA ON dbo.A_FORECAST_ITEMS.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA.ID


