CREATE VIEW dbo.A_V_PURCHASE_ITEMS_WITH_SUPPLIER_ID
AS
SELECT DISTINCT dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID, dbo.A_ORDER_ITEMS.ID, dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID
FROM         dbo.A_ORDER_ITEMS INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON dbo.A_ORDER_ITEMS.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID
WHERE     (NOT (dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID IS NULL))
