



CREATE VIEW dbo.A_V_NOUN_HIER_CHILDREN_EDITING_DATA
AS
SELECT     dbo.A_V_APPROVED_OBJECTS.OBJ_DESC AS NAME, dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.ID, 
                      dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.ROOT_ID, dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.APPROVED_OBJ_ID, 
                      dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.PARENT_ID, dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.HIERARCHY_ID, 
                      dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.DRCM, dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.MODBY, 
                      dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.BEEN_APPROVED, dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.HIDDEN
FROM         dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING INNER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_NOUN_HIERARCHY_CHILDREN_EDITING.APPROVED_OBJ_ID = dbo.A_V_APPROVED_OBJECTS.ID




