


CREATE VIEW dbo.A_V_DISCUSSION_SEARCH
AS
SELECT     d.ID, d.SUBJECT, d.INITIATOR AS I_ID, d.DATE_CREATED, dbo.A_FN_DISCUSSION_GET_STANDARD_SEARCH_FLAG(d.STATUS) 
                      AS STANDARD_SEARCH, d.DRCM, d.MODBY, d.STATUS, INITIATOR.FULL_NAME AS INITIATOR_NAME, dbo.A_TASK_DISCUSSION_LINK.TASK_ID, 
                      OPENING_STATEMENT.ID AS RESPONSE_ID, OPENING_STATEMENT.PARENT_ID, d.LAST_RESPONSE
FROM         dbo.A_DISCUSSIONS d LEFT OUTER JOIN
                      dbo.A_DISCUSSION_RESPONSE OPENING_STATEMENT ON d.ID = OPENING_STATEMENT.DISCUSSION_ID LEFT OUTER JOIN
                      dbo.A_TASK_DISCUSSION_LINK ON d.ID = dbo.A_TASK_DISCUSSION_LINK.DISCUSSION_ID LEFT OUTER JOIN
                      dbo.A_APPROVED_PEOPLE INITIATOR ON d.INITIATOR = INITIATOR.ID
WHERE     (OPENING_STATEMENT.PARENT_ID IS NULL)



