CREATE VIEW dbo.A_V_ENGINEER_REPORTS
AS
SELECT     dbo.A_V_PEOPLE_DATA_QUICK.FULL_NAME AS CREATOR_NAME, dbo.A_ENGINEER_SCREEN_REPORTS.ID, 
                      dbo.A_ENGINEER_SCREEN_REPORTS.NAME, dbo.A_ENGINEER_SCREEN_REPORTS.FILE_ID, dbo.A_ENGINEER_SCREEN_REPORTS.DESCRIPTION, 
                      dbo.A_ENGINEER_SCREEN_REPORTS.ROOT_COMPANY, dbo.A_ENGINEER_SCREEN_REPORTS.DATE_ADDED, 
                      dbo.A_ENGINEER_SCREEN_REPORTS.DATE_REMOVED, dbo.A_ENGINEER_SCREEN_REPORTS.ADDED_BY, 
                      dbo.A_ENGINEER_SCREEN_REPORTS.DRCM, dbo.A_ENGINEER_SCREEN_REPORTS.MODBY, dbo.A_DOCUMENTS.NAME AS FILE_NAME
FROM         dbo.A_ENGINEER_SCREEN_REPORTS LEFT OUTER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_ENGINEER_SCREEN_REPORTS.FILE_ID = dbo.A_DOCUMENTS.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_DATA_QUICK ON dbo.A_ENGINEER_SCREEN_REPORTS.ADDED_BY = dbo.A_V_PEOPLE_DATA_QUICK.ID
