CREATE VIEW dbo.A_V_PROPOSAL_ORDERS
AS
SELECT     dbo.A_PROPOSALS_QUOTE_LINK.PROP_HIST_ID, dbo.A_PROPOSALS_QUOTE_LINK.QUOTE_ID, 
                      dbo.A_V_ORDERS_APPROVED_DATA.DESCRIPTION
FROM         dbo.A_PROPOSALS_QUOTE_LINK INNER JOIN
                      dbo.A_V_ORDERS_APPROVED_DATA ON dbo.A_PROPOSALS_QUOTE_LINK.QUOTE_ID = dbo.A_V_ORDERS_APPROVED_DATA.OBJECT_ID
