




CREATE VIEW dbo.A_V_Z_FAV
AS
SELECT     f.[GROUP], f.ID, g.GROUP_NAME, g.FAV_TYPE, m.ROLE_NAME AS NAME, f.NUM
FROM         dbo.A_PEOPLES_FAVORITES f INNER JOIN
                      dbo.A_O_ROLES m ON f.ITEM = m.ID RIGHT OUTER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS g ON f.[GROUP] = g.ID
WHERE     (m.STATUS LIKE 'APPROVED%')