CREATE VIEW dbo.A_V_TASK_IS_QUICK_PRICE_CHECK
AS
SELECT     dbo.A_QUOTE_ORDER_LINK.TASK_ID, dbo.A_PRODUCTS_QUICK_PRICE.ORDER_ID
FROM         dbo.A_PRODUCTS_QUICK_PRICE INNER JOIN
                      dbo.A_QUOTE_ORDER_LINK ON dbo.A_PRODUCTS_QUICK_PRICE.ORDER_ID = dbo.A_QUOTE_ORDER_LINK.ORDER_ID
