CREATE VIEW dbo.A_V_WORKFLOWS_FOR_ACTIVITIES
AS
SELECT     dbo.A_WF_ACT_LINK.WF_ID, dbo.A_WF_ACT_LINK.ACT_ID, dbo.A_WF_ACTIVITIES.ACTIVITY, dbo.A_O_WORKFLOWS.CREATING_CO, 
                      dbo.A_O_WORKFLOWS.NAME AS WF_NAME, dbo.A_O_WORKFLOWS.HIDE
FROM         dbo.A_WF_ACT_LINK INNER JOIN
                      dbo.A_WF_ACTIVITIES ON dbo.A_WF_ACT_LINK.ACT_ID = dbo.A_WF_ACTIVITIES.ID INNER JOIN
                      dbo.A_O_WORKFLOWS ON dbo.A_WF_ACT_LINK.WF_ID = dbo.A_O_WORKFLOWS.ID
WHERE     (ISNULL(dbo.A_O_WORKFLOWS.HIDE, 0) = 0)
