

CREATE VIEW [dbo].[A_V_TASKS_WITH_PROCEDURE_STEP_DATA]
AS
SELECT     PARENT_TASK.ID AS PARENT_ID, STEP_TASK.ID AS STEP_ID, STEP_TASK.DESCRIPTION, STEP_TASK.STATUS, STEP_TASK.REQUESTOR, 
STEP_TASK.COMPLETED_BY, PROCEDURE_STEPS.ID AS PH_STEP_ID, PROCEDURE_STEPS.PRINT_ORDER, PROC_PREC_STEP_LINK.PREV_STEP, 
PREV_STEP_TASK.ID AS PREV_TASK_ID, PREV_STEP_TASK.STATUS AS PREV_TASK_STATUS, STEP_TASK.RECURSION_NUMBER, 
STEP_TASK.HAS_SURVEY, STEP_TASK.HAS_CHILD, STEP_TASK.HAS_REF_PROC, STEP_TASK.HAS_FILE, STEP_TASK.SYSTEM_TASK, 
STEP_TASK.HAS_MONITOR, STEP_TASK.REQUESTEE_ID, STEP_TASK.GROUP_REQUESTEE_ID, STEP_TASK.CHILD_STATUS, 
STEP_TASK.LATEST_REQUESTEE_NAME, PROCEDURE_STEPS.PROCEDURE_ID AS PROC_HIST_ID,oProc.VERB_NAME,
PROCEDURE_STEPS.TITLE,
PROCEDURE_STEPS.Roles,
PROCEDURE_STEPS.EquipmentTime,
PROCEDURE_STEPS.OLD_STEP_ID as OldStepId,
PROC_PREC_STEP_LINK.DRCM AS UpdatedDate
FROM         dbo.A_TASKS PARENT_TASK RIGHT OUTER JOIN
dbo.A_TASKS STEP_TASK ON PARENT_TASK.ID = STEP_TASK.PARENT_ID LEFT OUTER JOIN
dbo.A_PROCEDURE_STEP_PRECEDING_STEPS PROC_PREC_STEP_LINK INNER JOIN
dbo.A_TASKS PREV_STEP_TASK ON PROC_PREC_STEP_LINK.PREV_STEP = PREV_STEP_TASK.PROCEDURE_STEP_ID ON 
STEP_TASK.RECURSION_NUMBER = PREV_STEP_TASK.RECURSION_NUMBER AND 
STEP_TASK.PROCEDURE_STEP_ID = PROC_PREC_STEP_LINK.MY_STEP AND PARENT_TASK.ID = PREV_STEP_TASK.PARENT_ID LEFT OUTER JOIN
dbo.A_PROCEDURE_STEPS PROCEDURE_STEPS ON STEP_TASK.PROCEDURE_STEP_ID = PROCEDURE_STEPS.ID
LEFT JOIN dbo.A_V_PROCEDURES_APPROVED_DATA oProc on PROCEDURE_STEPS.PROCEDURE_ID = oProc.HISTORY_REF_ID

