

CREATE VIEW dbo.A_V_QUOTE_ITEM_PARENTS_USING_ORDER_ITEM_FOR_RELATIONSHIP
AS
SELECT     A_ORDER_ITEMS_1.ID AS PARENT_ID, A_ORDER_ITEMS_2.ID AS CHILD_ID, A_ORDER_ITEMS_2.QUOTE_ID
FROM         dbo.A_ORDER_ITEMS O_PARENT INNER JOIN
                      dbo.A_ORDER_ITEMS O_CHILD ON O_PARENT.ID = O_CHILD.PARENT INNER JOIN
                      dbo.A_ORDER_ITEMS A_ORDER_ITEMS_1 ON O_PARENT.ID = A_ORDER_ITEMS_1.SOURCE_ID INNER JOIN
                      dbo.A_ORDER_ITEMS A_ORDER_ITEMS_2 ON O_CHILD.ID = A_ORDER_ITEMS_2.SOURCE_ID


