CREATE VIEW dbo.A_V_PARTS_SAFETY_STOCK_LEVELS
AS
SELECT     l.ROOT AS LOCATION_ID, l.CREATING_CO, l.COMPLETE_NAME AS LOCATION_COMPLETE_NAME, l.NAME AS LOCATION_NAME, lev.PART_ID, 
                      p.NAME AS PART_NAME, lev.DRCM, lev.MODBY, lev.CUR_LEVEL, lev.MIN_WARNING_LEVEL, lev.MAX_WARNING_LEVEL, lev.MIN_LEVEL, 
                      lev.MAX_LEVEL, lev.ID, lev.PART_HIST_ID, lev.PART_OBJ_ID, lev.STATUS, l.STATUS AS LOC_STAT, lev.OLD_LEVEL
FROM         dbo.A_V_PARTS_APPROVED_DATA_QUICK p INNER JOIN
                      dbo.A_PARTS_SAFETY_STOCK_LEVELS lev ON p.ID = lev.PART_ID RIGHT OUTER JOIN
                      dbo.A_O_LOCATIONS l ON lev.LOCATION_ID = l.ROOT
WHERE     (l.STATUS LIKE 'APPROVED%')
