

CREATE VIEW dbo.A_V_APPROVED_PROCEDURE_STEPS
AS
SELECT     dbo.A_PROCEDURES.ID AS APPROVED_PROC_ID, dbo.A_PROCEDURES.HISTORY_REF_ID AS PROC_HIST_ID, 
                      dbo.A_PROCEDURES_HISTORY.NAME AS PROC_NAME, dbo.A_PROCEDURE_STEPS.ID AS STEP_ID, dbo.A_PROCEDURE_STEPS.STEP_TEXT
FROM         dbo.A_PROCEDURES INNER JOIN
                      dbo.A_PROCEDURES_HISTORY ON dbo.A_PROCEDURES.HISTORY_REF_ID = dbo.A_PROCEDURES_HISTORY.ID INNER JOIN
                      dbo.A_PROCEDURE_STEPS ON dbo.A_PROCEDURES_HISTORY.ID = dbo.A_PROCEDURE_STEPS.PROCEDURE_ID


