


CREATE VIEW dbo.A_V_PROD_REQ_FORM_DATES_WITH_PEOPLE_NAME
AS
SELECT     dbo.A_PROD_REQ_FORM_DATES.ID, dbo.A_PROD_REQ_FORM_DATES.PRF, dbo.A_PROD_REQ_FORM_DATES.DATE_TYPE, 
                      dbo.A_PROD_REQ_FORM_DATES.DT, dbo.A_PROD_REQ_FORM_DATES.DRCM, dbo.A_PROD_REQ_FORM_DATES.MODBY, 
                      dbo.A_PROD_REQ_FORM_DATES.PERSON, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME
FROM         dbo.A_PROD_REQ_FORM_DATES INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_PROD_REQ_FORM_DATES.PERSON = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID



