CREATE VIEW dbo.A_V_PRODUCTS_APPROVED_DATA
AS
SELECT     dbo.A_PRODUCTS.ID, dbo.A_PRODUCTS.HISTORY_REF_ID, dbo.A_PRODUCTS_HISTORY.NAME, dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID, 
                      dbo.A_PRODUCTS_HISTORY.COMMENTS, dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID, dbo.A_PRODUCTS_HISTORY.APP_OBJECT, 
                      dbo.A_PRODUCTS_HISTORY.SHIP_OR_LABOR, dbo.A_PRODUCTS_HISTORY.REQ_FORM, dbo.A_PRODUCTS_HISTORY.CUSTOMIZABLE, 
                      dbo.A_PRODUCTS_HISTORY.MGR_TEAM, dbo.A_PRODUCTS_HISTORY.SALES_TAX, dbo.A_PRODUCTS_HISTORY.DRCM, 
                      dbo.A_PRODUCTS_HISTORY.MODBY, dbo.A_PRODUCTS_HISTORY.OBJECT_ID, dbo.A_PRODUCTS_HISTORY.PARENT_ID, 
                      dbo.A_PRODUCTS_HISTORY.CUST_MGR_ROLE, dbo.A_PRODUCTS_HISTORY.SYSTEM_PROCEDURE, dbo.A_PRODUCTS.STATUS, 
                      dbo.A_PRODUCTS_HISTORY.PERSON_SUPPLIER, dbo.A_PRODUCTS_HISTORY.AVAILABILITY
FROM         dbo.A_PRODUCTS INNER JOIN
                      dbo.A_PRODUCTS_HISTORY ON dbo.A_PRODUCTS.HISTORY_REF_ID = dbo.A_PRODUCTS_HISTORY.ID
WHERE     (dbo.A_PRODUCTS.STATUS = 'APPROVED')
