CREATE VIEW dbo.A_V_WIP_REPORT_VIEW
AS
SELECT DISTINCT 
                      toi.PURCHASE_ITEM_ID, p.CUST_PURCH_NUM AS PO_NUMBER, i.DUE_DATE, t.ACTUAL_START_DATE, t.ACTUAL_STOP_DATE, 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL, c.NAME AS CUSTOMER_NAME, 
                      A_V_COMPANIES_APPROVED_DATA_QUICK_1.NAME AS SUPPLIER_NAME, dbo.A_V_PROCEDURES_DATA_QUICK.NAME AS PROC_NAME, 
                      dbo.A_FILLS.PRICE, dbo.A_ACCOUNT_INVOICE_ITEMS.AMOUNT AS INVOICE_AMOUNT, dbo.A_ACCOUNT_INVOICES.STATUS AS INVOICE_STATUS, 
                      dbo.A_ACCOUNT_INVOICES.INVOICE_DATE, dbo.A_ACCOUNT_INVOICES.DUE_DATE AS INVOICE_DUE_DATE, 
                      dbo.A_ACCOUNT_INVOICES.DATE_SENT_TO_CUSTOMER, dbo.A_ACCOUNT_INVOICE_ITEMS.FAILED_MONITOR, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS.INVOICE_ID, t.STATUS, i.MT_NUM, p.ID AS PURCHASE_ID, c.ID AS CUST_ID, t.ID AS TASK_ID, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.REFERENCE_PO AS BLANKET_PO, i.QTY, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.SUPPLIER_CO AS SUPPLIER_ID, p.HISTORY_REF_ID AS PURCH_HIST_ID, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC, dbo.A_TASK_COMPLETION_STATS.PERC_COMPLETE, 
                      dbo.A_TASK_COMPLETION_STATS.TIME_COMPLETE, dbo.A_TASK_COMPLETION_STATS.TOTAL_TIME, 
                      dbo.A_TASK_COMPLETION_STATS.NUM_SUB_TASKS, dbo.A_TASK_COMPLETION_STATS.MY_TOT_HOURS, 
                      dbo.A_TASK_COMPLETION_STATS.MY_COMP_HOURS, dbo.A_TASK_COMPLETION_STATS.NUM_SUB_TASKS_COMPLETE, 
                      dbo.A_TASK_COMPLETION_STATS.CUR_STEP_TEXT
FROM         dbo.A_TASK_COMPLETION_STATS INNER JOIN
                      dbo.A_FILLS INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION toi INNER JOIN
                      dbo.A_ORDER_ITEMS i ON toi.PURCHASE_ITEM_ID = i.ID INNER JOIN
                      dbo.A_TASKS t ON toi.TASK_ID = t.ID INNER JOIN
                      dbo.A_V_PURCHASES_APPROVED_DATA p ON toi.PURCHASE_HIST_ID = p.HISTORY_REF_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK c ON p.CUSTOMER_CO = c.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON i.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PROCEDURES_DATA_QUICK ON t.PROCEDURE_ID = dbo.A_V_PROCEDURES_DATA_QUICK.ID INNER JOIN
                      dbo.A_TASK_OBJECT_LINK ON t.ID = dbo.A_TASK_OBJECT_LINK.TASK_ID INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON dbo.A_TASK_OBJECT_LINK.OBJECT_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID ON 
                      dbo.A_FILLS.FILL_OBJ_ID = dbo.A_TASK_OBJECT_LINK.OBJECT_ID AND dbo.A_FILLS.ID = toi.FILL_ITEM_ID ON 
                      dbo.A_TASK_COMPLETION_STATS.TASK_ID = t.ID LEFT OUTER JOIN
                      dbo.A_ACCOUNT_INVOICES INNER JOIN
                      dbo.A_ACCOUNT_INVOICE_ITEMS ON dbo.A_ACCOUNT_INVOICES.ID = dbo.A_ACCOUNT_INVOICE_ITEMS.INVOICE_ID ON 
                      toi.FILL_ITEM_ID = dbo.A_ACCOUNT_INVOICE_ITEMS.FILL_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK A_V_COMPANIES_APPROVED_DATA_QUICK_1 INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK ON 
                      A_V_COMPANIES_APPROVED_DATA_QUICK_1.ID = dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.SUPPLIER_CO ON 
                      i.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.ID
WHERE     (toi.PURCHASE_ITEM_ID IS NOT NULL) AND (t.STATUS IN ('REQUESTED', 'ACCEPTED', 'CLOSED', 'FINISHED'))
