CREATE VIEW dbo.A_V_DOCUMENTS_WITH_LINKED_ITEM
AS
SELECT     
dbo.A_DOCUMENT_LINK.LINKED_DOC_ID,
dbo.A_DOCUMENTS.NAME, 
dbo.A_DOCUMENTS.DELETED,
dbo.A_DOCUMENTS.DOC_TYPE,
dbo.A_DOCUMENTS.CONTENTTYPE, 
dbo.A_DOCUMENTS.SERVER_PATH, 
dbo.A_DOCUMENT_LINK.TYPE,
dbo.A_DOCUMENT_LINK.OBJECT_ID
FROM dbo.A_DOCUMENT_LINK 
INNER JOIN dbo.A_DOCUMENTS ON dbo.A_DOCUMENT_LINK.LINKED_DOC_ID = dbo.A_DOCUMENTS.ID





