


CREATE VIEW dbo.A_V_PROJECT_ALLOWED_PEOPLE_DATA
AS
SELECT     dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS ALLOWED_PEOPLE_NAME, dbo.A_PROJECT_ALLOWED_PEOPLE.PEOPLE_ID AS ALLOWED_PEOPLE_ID,
                       dbo.A_PROJECT_ALLOWED_PEOPLE.PROJECT_ID
FROM         dbo.A_V_PEOPLE_BY_NTLOGIN INNER JOIN
                      dbo.A_PROJECT_ALLOWED_PEOPLE ON dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID = dbo.A_PROJECT_ALLOWED_PEOPLE.PEOPLE_ID



