


CREATE VIEW dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES
AS
SELECT     dbo.A_ROLES_HISTORY.NAME AS ROLE_NAME, dbo.A_ROLES.ID AS ROLE_ID, dbo.A_ROLE_ASSIGNEE.STATUS AS ROLE_STATUS, 
                      dbo.A_V_PEOPLE_OBJECT_SEARCH.*, dbo.A_PEOPLE_HISTORY.ROOT_COMPANY AS Expr1
FROM         dbo.A_ROLES_HISTORY INNER JOIN
                      dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_ROLE_ASSIGNEE ON dbo.A_PEOPLE.ID = dbo.A_ROLE_ASSIGNEE.PERSON ON 
                      dbo.A_ROLES_HISTORY.ID = dbo.A_ROLE_ASSIGNEE.ROLE INNER JOIN
                      dbo.A_ROLES ON dbo.A_ROLES_HISTORY.ID = dbo.A_ROLES.HISTORY_REF_ID INNER JOIN
                      dbo.A_V_PEOPLE_OBJECT_SEARCH ON dbo.A_PEOPLE_HISTORY.OBJECT_ID = dbo.A_V_PEOPLE_OBJECT_SEARCH.OBJ_ID



