
CREATE  VIEW dbo.A_V_PREPOP_QUICK
AS
SELECT     TOP 100 PERCENT dbo.A_PROCEDURE_STEPS.STEP_TEXT, dbo.A_PREPOP.ID, dbo.A_PREPOP.HISTORY_REF_ID, 
                      dbo.A_PREPOP_HISTORY.OBJECT_ID, dbo.A_PREPOP.CREATING_CO, dbo.A_PREPOP.STATUS, dbo.A_PROCEDURE_STEPS.ID AS STEP_ID,
					  TITLE
FROM         dbo.A_PREPOP INNER JOIN
                      dbo.A_PREPOP_HISTORY ON dbo.A_PREPOP.HISTORY_REF_ID = dbo.A_PREPOP_HISTORY.ID INNER JOIN
                      dbo.A_PROCEDURE_STEPS ON dbo.A_PREPOP_HISTORY.PROC_STEP_ID = dbo.A_PROCEDURE_STEPS.ID
WHERE     (dbo.A_PREPOP.STATUS = 'APPROVED')
ORDER BY dbo.A_PROCEDURE_STEPS.STEP_TEXT

