


CREATE VIEW dbo.A_V_ADMIN_ROLE_JOBS_WITH_CO_AND_ROLE
AS
SELECT     dbo.A_V_COMPANIES_APPROVED_DATA.ID AS CO_ID, dbo.A_V_ROLE_DATA_BY_APPROVED_ID.NAME AS ROLE_NAME, 
                      dbo.A_V_ROLE_DATA_BY_APPROVED_ID.ID AS ROLE_ID, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS CO_NAME, 
                      dbo.A_ADMIN_ROLE_JOBS.JOB
FROM         dbo.A_V_ROLE_DATA_BY_APPROVED_ID INNER JOIN
                      dbo.A_ADMIN_ROLE_JOBS ON dbo.A_V_ROLE_DATA_BY_APPROVED_ID.ID = dbo.A_ADMIN_ROLE_JOBS.ROLE_ID RIGHT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_ADMIN_ROLE_JOBS.CO_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID



