CREATE VIEW dbo.A_V_PURCHASE_ITEMS_WITH_ACCOUNT_SUPPLIER
AS
SELECT     i.ID AS PURCHASE_ITEM_ID, dbo.A_V_COMPANIES_APPROVED_DATA_QUICK.NAME AS SUPPLIER_NAME, a.SUPPLIER_CO AS SUPPLIER_ID
FROM         dbo.A_ORDER_ITEMS i INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK a ON i.ACCOUNT_ID = a.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK ON a.SUPPLIER_CO = dbo.A_V_COMPANIES_APPROVED_DATA_QUICK.ID
