
CREATE  VIEW dbo.A_V_PERSON_ROLES_WITH_SECURITY
AS
SELECT     dbo.A_PERSON_ROLES.PERSON_ID, dbo.A_PERSON_ROLES.ROLE_ID, dbo.A_V_ROLES_APPROVED_DATA.SECURITY_LEVEL, 
                      dbo.A_V_ROLES_APPROVED_DATA.IS_ADMIN, dbo.A_V_ROLES_APPROVED_DATA.NAME AS ROLE_NAME
FROM         dbo.A_PERSON_ROLES INNER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA ON dbo.A_PERSON_ROLES.ROLE_ID = dbo.A_V_ROLES_APPROVED_DATA.ID

