CREATE VIEW dbo.A_V_ACCOUNTS_APPROVED_DATA
AS
SELECT     a.OBJECT_ID, a.NAME, a.REFERENCE_PO, a.REFERENCE_NAME, a.OPEN_DATE, a.CLOSE_DATE, a.SUPPLIER_CO, a.CUSTOMER_CO, 
                      a.CUSTOMER_BILL_CO, a.MAXIMUM_USES, a.TOTAL_PURCHASE_LIMIT, a.CREDIT_LIMIT, a.APPROVAL_WF, a.INVOICE_TRIGGER, 
                      a.INVOICE_PERIOD_NUMBER, a.INVOICE_PERIOD_TYPE, a.FIRST_INVOICE_DATE, a.NEXT_INVOICE_DATE, a.PAYMENT_GRACE_PERIOD, 
                      a.LATE_FEE_PERCENTAGE, a.DRCM, a.MODBY, a.ACCT_TYPE, a.TOTAL_PURCHASES, a.BALANCE, a.AMT_INVOICED, a.ACCT_STATUS, 
                      sup.NAME AS SUPPLIER_NAME, co.NAME AS CUSTOMER_NAME, bill_co.NAME AS CUST_BILL_NAME, dbo.A_ACCOUNTS.ID, 
                      dbo.A_ACCOUNTS.HISTORY_REF_ID, a.REAPPLY_LATE_FEE, a.PRODUCT_ID, a.PARENT_ACCOUNT, dbo.A_OBJECTS.CREATING_CO, 
                      dbo.A_OBJECTS.STATUS, a.INVOICED_BALANCE, a.UNINVOICED_BALANCE, a.HAS_CHILD, a.NONCONSUMABLE_INCLUDED, 
                      a.CONSUMABLES_INCLUDED, a.LABOR_INCLUDED, a.TOTAL_CREDITS, a.TOTAL_DEBITS, a.BILLING_EMAIL, a.TAX_RATE
FROM         dbo.A_ACCOUNTS_HISTORY a INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA sup ON a.SUPPLIER_CO = sup.ID INNER JOIN
                      dbo.A_ACCOUNTS ON a.ID = dbo.A_ACCOUNTS.HISTORY_REF_ID INNER JOIN
                      dbo.A_OBJECTS ON a.OBJECT_ID = dbo.A_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA co ON a.CUSTOMER_CO = co.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA bill_co ON a.CUSTOMER_BILL_CO = bill_co.ID
WHERE     (dbo.A_OBJECTS.STATUS LIKE 'APPROVED%')
