CREATE VIEW dbo.A_V_ROLES_APPROVED_DATA_QUICK
AS
SELECT     dbo.A_OBJECTS.CREATING_CO, dbo.A_ROLES_HISTORY.NAME, dbo.A_ROLES.ID, dbo.A_ROLES.HISTORY_REF_ID
FROM         dbo.A_ROLES INNER JOIN
                      dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_ROLES_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID
