CREATE VIEW dbo.A_V_PURCHASES_APPROVED_DATA
AS
SELECT     dbo.A_PURCHASES.ID, dbo.A_PURCHASES.STATUS, dbo.A_PURCHASES.HISTORY_REF_ID, dbo.A_PURCHASES_HISTORY.DATE_CREATED, 
                      dbo.A_PURCHASES_HISTORY.PURCHASE_STATUS, dbo.A_PURCHASES_HISTORY.ORDER_ID, dbo.A_PURCHASES_HISTORY.OBJECT_ID, 
                      dbo.A_PURCHASES_HISTORY.PURCHASE_TOTAL, dbo.A_PURCHASES_HISTORY.PURCHASER, dbo.A_PURCHASES_HISTORY.PURCHASING_CO, 
                      dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_PERSON, dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_CO, 
                      dbo.A_V_ORDERS_APPROVED_DATA.DESCRIPTION, dbo.A_V_ORDERS_APPROVED_DATA.PROGRESS, 
                      dbo.A_PURCHASES_HISTORY.CUST_PURCH_NUM, dbo.A_PURCHASES_HISTORY.SUP_PURCH_NUM, 
                      dbo.A_PURCHASES_HISTORY.ACCT_FOR_ALL
FROM         dbo.A_PURCHASES INNER JOIN
                      dbo.A_PURCHASES_HISTORY ON dbo.A_PURCHASES.HISTORY_REF_ID = dbo.A_PURCHASES_HISTORY.ID INNER JOIN
                      dbo.A_V_ORDERS_APPROVED_DATA ON dbo.A_PURCHASES_HISTORY.ORDER_ID = dbo.A_V_ORDERS_APPROVED_DATA.ID
