
CREATE  VIEW dbo.A_V_THEORY_HISTORY_SEARCH
AS
SELECT     dbo.leadingSpaces(o.ROOT, '30') AS SPECIAL_ROOT, dbo.leadingSpaces(th.ID, '30') AS SPECIAL_ID, th.ID, th.OBJECT_ID, th.NAME, 
                      th.SECURITY_LEVEL, th.CREATING_DEPT, o.ID AS OBJ_ID, o.LOCKED_BY, o.CREATED_BY, o.ROOT, o.CREATING_CO, o.STATUS, o.REV, 
                      o.LOCKED_BY_NAME, o.CREATING_CO_NAME, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS DEPT_NAME, 
                      dbo.A_SECURITY_LEVELS.NAME AS SECURITY_NAME, o.APPROVAL_DATE
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_THEORY_HISTORY th ON o.ID = th.OBJECT_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON th.CREATING_DEPT = dbo.A_V_COMPANIES_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_SECURITY_LEVELS ON th.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID

