CREATE VIEW dbo.A_V_THEORY_HEADER_REF_THEORIES
AS
SELECT     dbo.A_THEORY_HISTORY.ID AS HIST_ID, dbo.A_THEORY_HISTORY.OBJECT_ID AS OBJECT_ID, dbo.A_THEORY.ID AS LINKED_THEORY_ID, 
                      A_THEORY_HISTORY_1.NAME AS LINKED_THEORY_NAME
FROM         dbo.A_THEORY INNER JOIN
                      dbo.A_THEORY_HISTORY A_THEORY_HISTORY_1 ON dbo.A_THEORY.HISTORY_REF_ID = A_THEORY_HISTORY_1.ID INNER JOIN
                      dbo.A_THEORY_HISTORY INNER JOIN
                      dbo.A_THEORY_REFERENCE_THEORY ON dbo.A_THEORY_HISTORY.ID = dbo.A_THEORY_REFERENCE_THEORY.THEORY_ID ON 
                      dbo.A_THEORY.ID = dbo.A_THEORY_REFERENCE_THEORY.THEORY_LINK
