




CREATE VIEW dbo.A_V_TIME_ZONE_WITH_PERSON_ID
AS
SELECT     dbo.A_APPROVED_PEOPLE.ID, dbo.A_TIME_ZONES.DESCRIPTION, dbo.A_TIME_ZONES.G_DIFF, dbo.A_TIME_ZONES.ID AS TIME_ZONE_ID
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_TIME_ZONES ON dbo.A_APPROVED_PEOPLE.TIME_ZONE = dbo.A_TIME_ZONES.ID





