


CREATE VIEW dbo.A_V_PEOPLE_PERFERENCES_GET_HISTORY_ID
AS
SELECT     dbo.A_OBJECTS.ID, dbo.A_OBJECTS.ROOT, dbo.A_OBJECTS.OBJ_ID AS peopleHistID
FROM         dbo.A_PEOPLE_HISTORY INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_PEOPLE_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID



