


CREATE VIEW dbo.A_V_QUOTES_APPROVED_DATA
AS
SELECT     dbo.A_QUOTES.ID, dbo.A_QUOTES.HISTORY_REF_ID, dbo.A_QUOTES_HISTORY.OBJECT_ID, dbo.A_QUOTES_HISTORY.DESCRIPTION, 
                      dbo.A_QUOTES_HISTORY.PROGRESS, dbo.A_QUOTES_HISTORY.ORDER_ID, dbo.A_QUOTES_HISTORY.CUSTOMER_PERSON, 
                      dbo.A_QUOTES_HISTORY.CUSTOMER_CO, dbo.A_QUOTES_HISTORY.BUGETARY_ONLY, dbo.A_QUOTES_HISTORY.EXPIRATION_DATE, 
                      dbo.A_QUOTES_HISTORY.MODBY, dbo.A_QUOTES_HISTORY.SUPPLIER_ID, dbo.A_QUOTES_HISTORY.CREATION_DATE, 
                      dbo.A_QUOTES_HISTORY.PERSON_SUPPLIER
FROM         dbo.A_QUOTES INNER JOIN
                      dbo.A_QUOTES_HISTORY ON dbo.A_QUOTES.HISTORY_REF_ID = dbo.A_QUOTES_HISTORY.ID



