CREATE VIEW dbo.A_V_EXTERNAL_PARTS_WITH_COMPANY
AS
SELECT     dbo.A_V_PARTS_EXTERNAL_PART_LOOKUP.INT_PART_ID, dbo.A_V_PARTS_EXTERNAL_PART_LOOKUP.EXT_PART_ID, 
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK.COMPANY AS INT_CO, dbo.A_V_PARTS_APPROVED_DATA_QUICK.COMPANY_NAME AS INT_CO_NAME, 
                      A_V_PARTS_APPROVED_DATA_QUICK_2.COMPANY AS EXT_CO, A_V_PARTS_APPROVED_DATA_QUICK_2.COMPANY_NAME AS EXT_CO_NAME, 
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK.NAME AS INT_NAME, A_V_PARTS_APPROVED_DATA_QUICK_2.NAME AS EXT_NAME
FROM         dbo.A_V_PARTS_APPROVED_DATA_QUICK INNER JOIN
                      dbo.A_V_PARTS_EXTERNAL_PART_LOOKUP ON 
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK.ID = dbo.A_V_PARTS_EXTERNAL_PART_LOOKUP.INT_PART_ID INNER JOIN
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK A_V_PARTS_APPROVED_DATA_QUICK_2 ON 
                      dbo.A_V_PARTS_EXTERNAL_PART_LOOKUP.EXT_PART_ID = A_V_PARTS_APPROVED_DATA_QUICK_2.ID
