



CREATE VIEW dbo.A_V_MEETING_GET_SCRIBE_NAME
AS
SELECT     dbo.A_APPROVED_PEOPLE.FULL_NAME AS SCRIBE_NAME, dbo.A_MEETINGS.SCRIBE AS S_ID, dbo.A_MEETINGS.ID
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_MEETINGS ON dbo.A_APPROVED_PEOPLE.ID = dbo.A_MEETINGS.SCRIBE