CREATE VIEW dbo.A_V_COUNTERS_BY_APPROVED_ID
AS
SELECT     dbo.A_COUNTERS.ID, dbo.A_COUNTERS.HISTORY_REF_ID, dbo.A_COUNTERS_HISTORY.NAME, dbo.A_COUNTERS_HISTORY.OBJECT_ID, 
                      dbo.A_COUNTERS_HISTORY.CUR_VAL, dbo.A_COUNTERS_HISTORY.DT_RECORDED, dbo.A_COUNTERS_HISTORY.REL_OBJECT_ID, 
                      dbo.A_COUNTERS_HISTORY.REL_OBJEC_NAME
FROM         dbo.A_COUNTERS INNER JOIN
                      dbo.A_COUNTERS_HISTORY ON dbo.A_COUNTERS.HISTORY_REF_ID = dbo.A_COUNTERS_HISTORY.ID
