

CREATE VIEW dbo.A_V_PURCHASE_HISTORY_WITH_ITEMS_AND_FILLS
AS
SELECT     dbo.A_PURCHASES_HISTORY.ID AS PURCHASE_HIST_ID, dbo.A_PURCHASES_HISTORY.PURCHASE_STATUS, 
                      dbo.A_PURCHASES_HISTORY.PURCHASER, dbo.A_ORDER_ITEMS.ID AS PURCHASE_ITEM_ID, dbo.A_FILLS.ID AS FILL_ID, dbo.A_FILLS.FILL_OBJ_ID, 
                      dbo.A_FILLS.MODBY
FROM         dbo.A_PURCHASES_HISTORY INNER JOIN
                      dbo.A_ORDER_ITEMS ON dbo.A_PURCHASES_HISTORY.ID = dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID LEFT OUTER JOIN
                      dbo.A_FILLS ON dbo.A_ORDER_ITEMS.ID = dbo.A_FILLS.PURCH_ITEM_ID


