


CREATE VIEW dbo.A_V_MEETING_EMAIL_DATA
AS
SELECT     m.ID, m.MEETING_NAME, m.COMMENT, m.START_DATE, m.STOP_DATE, m.OWNER, m.HOST, m.TIME_KEEP, m.SCRIBE, m.LOCATION, 
                      m.WEB_LOCATION, m.DATE_CREATED, dbo.A_FN_MEETING_GET_STANDARD_SEARCH_FLAG(m.START_DATE, m.STOP_DATE, GETDATE()) 
                      AS STANDARD_SEARCH, dbo.A_MEETING_INV_ROLE.ROLE_ID, dbo.A_V_LOCATIONS_BY_APPROVED_ID.NAME AS LOCATION_NAME, m.SETTING, 
                      dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS CREATOR_NAME, dbo.A_MEETING_INV_PEOPLE.PEOPLE_ID
FROM         dbo.A_MEETINGS m INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON m.OWNER = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID LEFT OUTER JOIN
                      dbo.A_MEETING_INV_PEOPLE ON m.ID = dbo.A_MEETING_INV_PEOPLE.MEETING_ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID ON m.LOCATION = dbo.A_V_LOCATIONS_BY_APPROVED_ID.ID LEFT OUTER JOIN
                      dbo.A_MEETING_INV_ROLE ON m.ID = dbo.A_MEETING_INV_ROLE.MEETING_ID