CREATE VIEW dbo.A_V_SERVICE_CALL_WORK_TYPE_DATA
AS
SELECT     dbo.A_SERVICE_CALLS_WORK_TYPES.ID, dbo.A_APPROVED_COMPANIES.NAME AS SUPPLIER_NAME, '$' + CONVERT(varchar(50), 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.HOUR_RATE) AS NORMAL_RATE, '$' + CONVERT(varchar(50), 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.OT_RATE) AS OVER_RATE, A_APPROVED_COMPANIES_1.NAME AS CUSTOMER_NAME, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.WORK_TYPE_NAME, dbo.A_APPROVED_ROLES.NAME AS APPROVER_ROLE_NAME, 
                      A_APPROVED_ROLES_1.NAME AS PAYER_ROLE_NAME, dbo.A_SERVICE_CALLS_WORK_TYPES.SUPPLIER_ID, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.CUSTOMER_ID, dbo.A_SERVICE_CALLS_WORK_TYPES.APPROVER_ROLE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.PAYER_ROLE, dbo.A_SERVICE_CALLS_WORK_TYPES.TAX_RATE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.HOUR_RATE, dbo.A_SERVICE_CALLS_WORK_TYPES.OT_RATE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.SKIP_BOSS, dbo.A_SERVICE_CALLS_WORK_TYPES.HIDE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.STATUS
FROM         dbo.A_APPROVED_COMPANIES RIGHT OUTER JOIN
                      dbo.A_SERVICE_CALLS_WORK_TYPES ON 
                      dbo.A_APPROVED_COMPANIES.ID = dbo.A_SERVICE_CALLS_WORK_TYPES.SUPPLIER_ID LEFT OUTER JOIN
                      dbo.A_APPROVED_COMPANIES A_APPROVED_COMPANIES_1 ON 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.CUSTOMER_ID = A_APPROVED_COMPANIES_1.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_SERVICE_CALLS_WORK_TYPES.APPROVER_ROLE = dbo.A_APPROVED_ROLES.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_ROLES A_APPROVED_ROLES_1 ON dbo.A_SERVICE_CALLS_WORK_TYPES.PAYER_ROLE = A_APPROVED_ROLES_1.ID