
CREATE  VIEW dbo.A_V_PROCEDURE_STEPS_PREV_STEP_BY_OLD_STEP_RELATIONSHIP
AS
SELECT     PREV_STEP.ID AS PREV_STEP, MY_STEP.ID AS MY_STEP, PREV_STEP.PROCEDURE_ID
FROM         dbo.A_PROCEDURE_STEPS MY_STEP INNER JOIN
                      dbo.A_PROCEDURE_STEP_PRECEDING_STEPS LINK ON MY_STEP.OLD_STEP_ID = LINK.MY_STEP INNER JOIN
                      dbo.A_PROCEDURE_STEPS PREV_STEP ON LINK.PREV_STEP = PREV_STEP.OLD_STEP_ID

