CREATE VIEW dbo.A_V_INVOICES_WITH_ACCT_INFORMATION
AS
SELECT     INVOICE.ID AS INVOICE_ID, ACCOUNT.NAME AS ACCT_NAME, INVOICE.INVOICE_DATE, INVOICE.STATUS, INVOICE.AMT_PAID, 
                      INVOICE.NEW_ITEMS_AMT, INVOICE.PREVIOUS_BALANCE, INVOICE.PAYMENT_AMOUNT, INVOICE.DISPUTED_AMOUNT, INVOICE.TOTAL_DUE, 
                      INVOICE.DUE_DATE, ACCOUNT.ACCT_TYPE, ACCOUNT.CREATING_CO, ACCOUNT.REFERENCE_PO, ACCOUNT.REFERENCE_NAME, 
                      ACCOUNT.OPEN_DATE, ACCOUNT.CLOSE_DATE, ACCOUNT.SUPPLIER_CO, ACCOUNT.CUSTOMER_CO, ACCOUNT.CUSTOMER_BILL_CO, 
                      ACCOUNT.TOTAL_PURCHASE_LIMIT, ACCOUNT.CREDIT_LIMIT, ACCOUNT.SUPPLIER_NAME, ACCOUNT.CUSTOMER_NAME, 
                      ACCOUNT.CUST_BILL_NAME, ACCOUNT.PRODUCT_ID, PROD.NAME AS PRODUCT_NAME, INVOICE.ACCOUNT_ID, INVOICE.LATE_FEES, 
                      ACCOUNT.TOTAL_PURCHASES, INVOICE.DATE_SENT_TO_CUSTOMER, INVOICE.PURCHASE_ID, INVOICE.NAME AS INVOICE_NAME, 
                      INVOICE.CREATE_DATE, INVOICE.INVOICE_TYPE, ACCOUNT.MAXIMUM_USES, ACCOUNT.INVOICE_TRIGGER, ACCOUNT.INVOICE_PERIOD_NUMBER, 
                      ACCOUNT.INVOICE_PERIOD_TYPE, ACCOUNT.FIRST_INVOICE_DATE, ACCOUNT.NEXT_INVOICE_DATE, ACCOUNT.PAYMENT_GRACE_PERIOD, 
                      ACCOUNT.LATE_FEE_PERCENTAGE, ACCOUNT.AMT_INVOICED, ACCOUNT.BALANCE, ACCOUNT.INVOICED_BALANCE, 
                      ACCOUNT.UNINVOICED_BALANCE, ACCOUNT.BILLING_EMAIL, ACCOUNT.TOTAL_DEBITS, ACCOUNT.TOTAL_CREDITS, 
                      PURCHASE.CUST_PURCH_NUM, INVOICE.INVOICE_BALANCE, INVOICE.TOTAL_TAX, INVOICE.PO_NUMBER
FROM         dbo.A_V_PURCHASES_APPROVED_DATA PURCHASE RIGHT OUTER JOIN
                      dbo.A_ACCOUNT_INVOICES INVOICE INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA ACCOUNT ON INVOICE.ACCOUNT_ID = ACCOUNT.ID ON 
                      PURCHASE.ID = INVOICE.PURCHASE_ID LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA PROD ON ACCOUNT.PRODUCT_ID = PROD.ID
