
CREATE  VIEW dbo.A_V_PEOPLE_APPROVED_DATA
AS
SELECT     p.ID, p.HISTORY_REF_ID, dbo.A_PEOPLE_HISTORY.LOGIN, dbo.A_PEOPLE_HISTORY.NAME, dbo.A_PEOPLE_HISTORY.BOSS, 
                      dbo.A_PEOPLE_HISTORY.SOURCE, dbo.A_PEOPLE_HISTORY.LAST_NAME, dbo.A_PEOPLE_HISTORY.MIDDLE_NAME, 
                      dbo.A_PEOPLE_HISTORY.NICK_NAME, dbo.A_PEOPLE_HISTORY.LANG, dbo.A_PEOPLE_HISTORY.HIRE_DATE, dbo.A_PEOPLE_HISTORY.DRCM, 
                      dbo.A_PEOPLE_HISTORY.MODBY, dbo.A_PEOPLE_HISTORY.OBJECT_ID, dbo.A_PEOPLE_HISTORY.COMPANY, 
                      dbo.A_PEOPLE_HISTORY.TIME_ZONE, dbo.A_PEOPLE_HISTORY.FULL_NAME, dbo.A_PEOPLE_HISTORY.SYSTEM_STATUS, 
                      dbo.A_PEOPLE_HISTORY.CO_POSITION, dbo.A_PEOPLE_HISTORY.ROOT_COMPANY, dbo.A_PEOPLE_HISTORY.IS_HEAD, p.STATUS, 
                      dbo.A_PEOPLE_HISTORY.TOOL_BOX, dbo.A_PEOPLE_HISTORY.INFO_BOX, dbo.A_PEOPLE_HISTORY.ADV_SEARCH, 
                      dbo.A_PEOPLE_HISTORY.COLOR_KEY, dbo.A_PEOPLE_HISTORY.SCREEN_TYPE
FROM         dbo.A_PEOPLE_HISTORY INNER JOIN
                      dbo.A_PEOPLE p ON dbo.A_PEOPLE_HISTORY.ID = p.HISTORY_REF_ID
WHERE     (dbo.A_PEOPLE_HISTORY.SYSTEM_STATUS = 'ACTIVE') AND (p.STATUS = 'APPROVED')

