

CREATE VIEW dbo.A_V_PEOPLE_ORG_CHART_TREE_DATA
AS
SELECT     dbo.A_APPROVED_PEOPLE.ID, dbo.A_APPROVED_PEOPLE.BOSS, dbo.A_ROLES_HISTORY.NAME AS TITLE, dbo.A_APPROVED_PEOPLE.NAME, 
                      dbo.A_APPROVED_PEOPLE.LAST_NAME, dbo.A_APPROVED_PEOPLE.SYSTEM_STATUS, dbo.A_APPROVED_PEOPLE.STATUS
FROM         dbo.A_ROLES_HISTORY INNER JOIN
                      dbo.A_ROLES ON dbo.A_ROLES_HISTORY.ID = dbo.A_ROLES.HISTORY_REF_ID RIGHT OUTER JOIN
                      dbo.A_APPROVED_PEOPLE ON dbo.A_ROLES.ID = dbo.A_APPROVED_PEOPLE.CO_POSITION
WHERE     (dbo.A_APPROVED_PEOPLE.STATUS = 'APPROVED')


