CREATE VIEW dbo.A_V_PEOPLE_ROLES
AS
SELECT     dbo.A_V_PEOPLE_DATA_QUICK.FULL_NAME AS PERSON_NAME, dbo.A_PERSON_ROLES.PERSON_ID, dbo.A_PERSON_ROLES.ROLE_ID, 
                      dbo.A_V_ROLES_APPROVED_DATA_QUICK.NAME AS ROLE_NAME
FROM         dbo.A_PERSON_ROLES INNER JOIN
                      dbo.A_V_PEOPLE_DATA_QUICK ON dbo.A_PERSON_ROLES.PERSON_ID = dbo.A_V_PEOPLE_DATA_QUICK.ID INNER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA_QUICK ON dbo.A_PERSON_ROLES.ROLE_ID = dbo.A_V_ROLES_APPROVED_DATA_QUICK.ID
