


CREATE VIEW dbo.A_V_SURVEY_BY_ID
AS
SELECT     s.ID, s.SUBJECT, s.OWNER, s.DATE_CREATED, dbo.A_FN_SURVEYS_GET_STANDARD_SEARCH_FLAG(s.STATUS) AS STANDARD_SEARCH, 
                      dbo.A_APPROVED_PEOPLE.FULL_NAME AS INITIATOR_NAME, s.STATUS
FROM         dbo.A_SURVEYS s LEFT OUTER JOIN
                      dbo.A_APPROVED_PEOPLE ON s.OWNER = dbo.A_APPROVED_PEOPLE.ID



