


CREATE VIEW dbo.A_V_ROLE_DATA_BY_APPROVED_ID
AS
SELECT     dbo.A_ROLES.ID, dbo.A_ROLES.HISTORY_REF_ID, dbo.A_ROLES_HISTORY.NAME, dbo.A_ROLES_HISTORY.OBJECT_ID, 
                      dbo.A_ROLES_HISTORY.IS_ADMIN, dbo.A_ROLES_HISTORY.SECURITY_LEVEL, dbo.A_ROLES_HISTORY.HIDDEN
FROM         dbo.A_ROLES INNER JOIN
                      dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID



