CREATE VIEW [dbo].[A_V_APPROVED_COMPANIES_WITH_ADDRESS_AND_LOGOS]
AS
SELECT     dbo.A_APPROVED_LOCATIONS.STATE, dbo.A_APPROVED_LOCATIONS.CITY, dbo.A_APPROVED_LOCATIONS.FULL_ADDRESS, 
                      dbo.A_APPROVED_LOCATIONS.COUNTRY, dbo.A_APPROVED_COMPANIES.ID, dbo.A_APPROVED_COMPANIES.NAME AS COMPANY_NAME, 
                      dbo.A_APPROVED_LOCATIONS.NAME AS LOCATION_NAME, dbo.A_APPROVED_LOCATIONS.ADDRESS_1, dbo.A_APPROVED_LOCATIONS.ADDRESS_2, 
                      dbo.A_APPROVED_LOCATIONS.POSTAL_CODE, dbo.A_APPROVED_LOCATIONS.REGION, dbo.A_APPROVED_LOCATIONS.REGION_NAME, 
                      dbo.A_APPROVED_LOCATIONS.INTERNAL_ADDRESS, dbo.A_APPROVED_COMPANIES.PHONE,
					  A_DOCUMENT_LINK.LINKED_DOC_ID as LOGO_ID
FROM         dbo.A_APPROVED_COMPANIES LEFT OUTER JOIN
                      dbo.A_APPROVED_LOCATIONS ON dbo.A_APPROVED_COMPANIES.LOCATION = dbo.A_APPROVED_LOCATIONS.ID
					  LEFT OUTER JOIN
					  dbo.A_DOCUMENT_LINK ON dbo.A_APPROVED_COMPANIES.OBJECT_ID = dbo.A_DOCUMENT_LINK.OBJECT_ID
					  AND (dbo.A_DOCUMENT_LINK.TYPE = N'LOGO')
