


CREATE VIEW dbo.A_V_PROJECT_SPONSOR_DATA
AS
SELECT     dbo.A_PROJECT_SPONSORS.PROJECT_ID, dbo.A_PROJECT_SPONSORS.PEOPLE_ID AS SPONSOR_ID, 
                      dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS SPONSOR_NAME
FROM         dbo.A_PROJECT_SPONSORS INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_PROJECT_SPONSORS.PEOPLE_ID = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID



