


CREATE VIEW dbo.A_V_SERVICE_CALL_TOTAL_HOURS
AS
SELECT     ot.OT_HOURS, n.ID, n.NORMAL_HOURS, ot.OT_HOURS + n.NORMAL_HOURS AS TOTAL_HOURS, n.START_DAY, n.START_MONTH, n.START_YEAR, 
                      NT_0.HOURS AS NT_0, NT_1.HOURS AS NT_1, NT_2.HOURS AS NT_2, NT_3.HOURS AS NT_3, NT_4.HOURS AS NT_4, NT_5.HOURS AS NT_5, 
                      NT_6.HOURS AS NT_6, OT_0.HOURS AS OT_0, OT_1.HOURS AS OT_1, OT_2.HOURS AS OT_2, OT_3.HOURS AS OT_3, OT_4.HOURS AS OT_4, 
                      OT_5.HOURS AS OT_5, OT_6.HOURS AS OT_6
FROM         dbo.A_V_SERVICE_CALL_TOTAL_OT_HOURS ot INNER JOIN
                      dbo.A_V_SERVICE_CALLS_WITH_NORMAL_HOURS n ON ot.ID = n.ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_0 ON DATEADD(dd, 0, n.START_DATE) = NT_0.DT AND 
                      n.ID = NT_0.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_1 ON DATEADD(dd, 1, n.START_DATE) = NT_1.DT AND 
                      n.ID = NT_1.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_2 ON DATEADD(dd, 2, n.START_DATE) = NT_2.DT AND 
                      n.ID = NT_2.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_3 ON DATEADD(dd, 3, n.START_DATE) = NT_3.DT AND 
                      n.ID = NT_3.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_4 ON DATEADD(dd, 4, n.START_DATE) = NT_4.DT AND 
                      n.ID = NT_4.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_5 ON DATEADD(dd, 5, n.START_DATE) = NT_5.DT AND 
                      n.ID = NT_5.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE NT_6 ON DATEADD(dd, 6, n.START_DATE) = NT_6.DT AND 
                      n.ID = NT_6.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_0 ON DATEADD(dd, 0, n.START_DATE) = OT_0.DT AND 
                      n.ID = OT_0.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_1 ON DATEADD(dd, 1, n.START_DATE) = OT_1.DT AND 
                      n.ID = OT_1.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_2 ON DATEADD(dd, 2, n.START_DATE) = OT_2.DT AND 
                      n.ID = OT_2.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_3 ON DATEADD(dd, 3, n.START_DATE) = OT_3.DT AND 
                      n.ID = OT_3.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_4 ON DATEADD(dd, 4, n.START_DATE) = OT_4.DT AND 
                      n.ID = OT_4.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_5 ON DATEADD(dd, 5, n.START_DATE) = OT_5.DT AND 
                      n.ID = OT_5.WEEKLY_ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE OT_6 ON DATEADD(dd, 6, n.START_DATE) = OT_6.DT AND n.ID = OT_6.WEEKLY_ID
WHERE     (NT_0.HOUR_TYPE = 'NORMAL') AND (NT_1.HOUR_TYPE = 'NORMAL') AND (NT_2.HOUR_TYPE = 'NORMAL') AND (NT_3.HOUR_TYPE = 'NORMAL') 
                      AND (NT_4.HOUR_TYPE = 'NORMAL') AND (NT_5.HOUR_TYPE = 'NORMAL') AND (NT_6.HOUR_TYPE = 'NORMAL') AND (OT_1.HOUR_TYPE = 'OVER') 
                      AND (OT_2.HOUR_TYPE = 'OVER') AND (OT_3.HOUR_TYPE = 'OVER') AND (OT_4.HOUR_TYPE = 'OVER') AND (OT_5.HOUR_TYPE = 'OVER') AND 
                      (OT_6.HOUR_TYPE = 'OVER') AND (OT_0.HOUR_TYPE = 'OVER')