CREATE VIEW dbo.A_V_PARTS_EXTERNAL_PART_LOOKUP
AS
SELECT     INT_PART.ID AS INT_PART_ID, INT_PH.ID AS INT_PH_ID, EXT_PART.ID AS EXT_PART_ID, EXT_PART_HIST.ID AS EXT_PH_ID, 
                      INT_PH.COMPANY AS INT_CO, EXT_PART_HIST.COMPANY AS EXT_CO
FROM         dbo.A_PARTS_EXTERNAL_EQUALS INNER JOIN
                      dbo.A_PARTS_HISTORY INT_PH ON dbo.A_PARTS_EXTERNAL_EQUALS.PART_ID = INT_PH.ID INNER JOIN
                      dbo.A_PARTS EXT_PART ON dbo.A_PARTS_EXTERNAL_EQUALS.EQUAL_PART_ID = EXT_PART.ID INNER JOIN
                      dbo.A_PARTS_HISTORY EXT_PART_HIST ON EXT_PART.PARTS_HISTORY_ID = EXT_PART_HIST.ID LEFT OUTER JOIN
                      dbo.A_PARTS INT_PART ON INT_PH.ID = INT_PART.PARTS_HISTORY_ID
