CREATE VIEW [dbo].[A_V_SERVICE_CALLS_ACC_RECEIVABLE_ROLE]
AS
SELECT     co.ID AS CO_ID, co.NAME AS CO_NAME, sc.ID, sc.RECIEVABLE_ROLE AS ROLE_ID, sc.PAYMENT_LOCATION AS LOCATION_ID, 
                      ro.NAME AS ROLE_NAME, l.NAME AS LOCATION_NAME
FROM         dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE sc RIGHT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA co ON sc.COMPANY_ID = co.ID LEFT OUTER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA ro ON sc.RECIEVABLE_ROLE = ro.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID l ON sc.PAYMENT_LOCATION = l.ID
GO


