



CREATE VIEW dbo.A_V_APPROVED_ROLES_DATA
AS
SELECT     dbo.A_ROLES.ID, dbo.A_ROLES.HISTORY_REF_ID, dbo.A_ROLES_HISTORY.NAME, dbo.A_ROLES_HISTORY.SOURCE, 
                      dbo.A_ROLES_HISTORY.HIDDEN, dbo.A_ROLES_HISTORY.DRCM, dbo.A_ROLES_HISTORY.MODBY, dbo.A_ROLES_HISTORY.OBJECT_ID, 
                      dbo.A_ROLES_HISTORY.SECURITY_LEVEL
FROM         dbo.A_ROLES INNER JOIN
                      dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID




