CREATE VIEW dbo.A_V_TASK_PURCHASE_INFORMATION
AS
SELECT     dbo.A_TASKS.ID, dbo.A_TASKS.DESCRIPTION, dbo.A_TASK_ORDER_INFORMATION.PURCHASE_HIST_ID, 
                      dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_PERSON, dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_CO, 
                      dbo.A_PURCHASES_HISTORY.PURCHASER, dbo.A_PURCHASES_HISTORY.PURCHASING_CO, dbo.A_PURCHASES_HISTORY.ORDER_ID, 
                      CUSTOMER_CO.NAME AS CUSTOMER_NAME, CUSTOMER.FULL_NAME AS CUSTOMER_PERSON_NAME, 
                      PURCHASER.FULL_NAME AS PURCHASER_PERSON_NAME, dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID, 
                      dbo.A_ORDER_ITEMS.ACCOUNT_ID, dbo.A_ORDER_ITEMS.BILL_TYPE, dbo.A_ORDER_ITEMS.TOTAL_PRICE, dbo.A_ORDER_ITEMS.PRODUCT_ID, 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, dbo.A_PURCHASES.ID AS PURCHASE_ID, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA.NAME AS ACCOUNT_NAME, dbo.A_V_ACCOUNTS_APPROVED_DATA.REFERENCE_PO AS ACCOUNT_REF_PO, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA.REFERENCE_NAME AS ACCOUNT_REF_NAME, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA.SUPPLIER_NAME AS ACCOUNT_SUPPLIER_NAME, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA.CUSTOMER_NAME AS ACCOUNT_CUST_NAME, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA.COMPLETE_NAME AS CUST_LOC_NAME, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA.FULL_ADDRESS AS CUST_ADDRESS, dbo.A_V_LOCATIONS_APPROVED_DATA.CITY AS CUST_CITY, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA.STATE AS CUST_STATE, dbo.A_V_LOCATIONS_APPROVED_DATA.COUNTRY AS CUST_COUNTRY, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA.POSTAL_CODE AS CUST_ZIP, SUPPLIER_CO.NAME AS SUPPLIER_NAME, 
                      A_V_LOCATIONS_APPROVED_DATA_1.COMPLETE_NAME AS SUPPLIER_LOC_NAME, 
                      A_V_LOCATIONS_APPROVED_DATA_1.ADDRESS_1 AS SUPPLIER_ADDRESS, A_V_LOCATIONS_APPROVED_DATA_1.CITY AS SUPPLIER_CITY, 
                      A_V_LOCATIONS_APPROVED_DATA_1.STATE AS SUPPLIER_STATE, A_V_LOCATIONS_APPROVED_DATA_1.COUNTRY AS SUPPLIER_COUNTRY, 
                      A_V_LOCATIONS_APPROVED_DATA_1.POSTAL_CODE AS SUPPLIER_ZIP, dbo.A_V_LOGOS.SERVER_PATH, dbo.A_V_LOGOS.ID AS LOGO_ID, 
                      SUPPLIER_CO.PHONE AS SUPPLIER_PHONE, dbo.A_PURCHASES_HISTORY.CUST_PURCH_NUM, dbo.A_PURCHASES_HISTORY.SUP_PURCH_NUM, 
                      SUPPLIER_CO.ID AS SUPPLIER_ID, CUSTOMER.ID AS CUSTOMER_ID
FROM         dbo.A_V_LOCATIONS_APPROVED_DATA A_V_LOCATIONS_APPROVED_DATA_1 RIGHT OUTER JOIN
                      dbo.A_V_LOGOS RIGHT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER_CO ON dbo.A_V_LOGOS.OBJECT_ID = SUPPLIER_CO.OBJECT_ID ON 
                      A_V_LOCATIONS_APPROVED_DATA_1.ID = SUPPLIER_CO.LOCATION RIGHT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA INNER JOIN
                      dbo.A_ORDER_ITEMS ON dbo.A_V_PRODUCTS_APPROVED_DATA.ID = dbo.A_ORDER_ITEMS.PRODUCT_ID ON 
                      SUPPLIER_CO.ID = dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID LEFT OUTER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA ON dbo.A_ORDER_ITEMS.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA.ID RIGHT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA RIGHT OUTER JOIN
                      dbo.A_PURCHASES_HISTORY INNER JOIN
                      dbo.A_PURCHASES ON dbo.A_PURCHASES_HISTORY.ID = dbo.A_PURCHASES.HISTORY_REF_ID INNER JOIN
                      dbo.A_TASKS INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION ON dbo.A_TASKS.ID = dbo.A_TASK_ORDER_INFORMATION.TASK_ID ON 
                      dbo.A_PURCHASES.HISTORY_REF_ID = dbo.A_TASK_ORDER_INFORMATION.PURCHASE_HIST_ID INNER JOIN
                      dbo.A_V_ORDERS_APPROVED_DATA ON dbo.A_PURCHASES_HISTORY.ORDER_ID = dbo.A_V_ORDERS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUSTOMER_CO ON dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_CO = CUSTOMER_CO.ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA PURCHASER ON dbo.A_PURCHASES_HISTORY.PURCHASER = PURCHASER.ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA CUSTOMER ON dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_PERSON = CUSTOMER.ID ON 
                      dbo.A_V_LOCATIONS_APPROVED_DATA.ID = CUSTOMER_CO.LOCATION ON 
                      dbo.A_ORDER_ITEMS.ID = dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID
