CREATE VIEW dbo.A_V_PURCHASE_ITEM_DATA
AS
SELECT     dbo.A_ORDER_ITEMS.ID, dbo.A_ORDER_ITEMS.ORDER_ID, dbo.A_ORDER_ITEMS.PRODUCT_ID, dbo.A_ORDER_ITEMS.QTY, 
                      dbo.A_ORDER_ITEMS.RECURRING, dbo.A_ORDER_ITEMS.RECUR_PERIOD, dbo.A_ORDER_ITEMS.RECUR_COUNT, 
                      dbo.A_ORDER_ITEMS.RECUR_START_DATE, dbo.A_ORDER_ITEMS.RECUR_STOP_DATE, dbo.A_ORDER_ITEMS.RECUR_ACCOUNT, 
                      dbo.A_ORDER_ITEMS.RECUR_AUTO_FILL, dbo.A_ORDER_ITEMS.SPECIAL_DISCOUNT, dbo.A_ORDER_ITEMS.SPECIAL_DISC_REASON, 
                      dbo.A_ORDER_ITEMS.UNIT_PRICE, dbo.A_ORDER_ITEMS.UNIT_ESTIMATE, dbo.A_ORDER_ITEMS.EXPEDITE_PRODUCTION, 
                      dbo.A_ORDER_ITEMS.EXPEDITE_REASON, dbo.A_ORDER_ITEMS.COMMENTS, dbo.A_ORDER_ITEMS.DRCM, dbo.A_ORDER_ITEMS.MODBY, 
                      dbo.A_ORDER_ITEMS.PARENT, dbo.A_ORDER_ITEMS.PROD_PRICE_LIST, dbo.A_ORDER_ITEMS.QUOTE_ID, dbo.A_ORDER_ITEMS.TOTAL_QTY, 
                      dbo.A_ORDER_ITEMS.TOTAL_PRICE, dbo.A_ORDER_ITEMS.PARENT_QTY, dbo.A_ORDER_ITEMS.PROC_SYS_ID, dbo.A_ORDER_ITEMS.DEST, 
                      dbo.A_ORDER_ITEMS.FROM_LOC, dbo.A_ORDER_ITEMS.TO_LOC, dbo.A_ORDER_ITEMS.ADD_COST_ID, dbo.A_ORDER_ITEMS.FLAT_RATE, 
                      dbo.A_ORDER_ITEMS.EX_DESC, dbo.A_ORDER_ITEMS.EST_WEIGHT, dbo.A_ORDER_ITEMS.EST_WEIGHT_UNIT, 
                      dbo.A_ORDER_ITEMS.PPL_HIST_ID, dbo.A_ORDER_ITEMS.SOURCE_ID, dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID, 
                      dbo.A_ORDER_ITEMS.ACCOUNT_ID, dbo.A_ORDER_ITEMS.BILL_TYPE, dbo.A_ORDER_ITEMS.QTY_FILLED, 
                      dbo.A_ORDER_ITEMS.QTY_NEEDS_FILLING, dbo.A_ORDER_ITEMS_PURCHASE_DATA.PRODUCT_HIST_ID, 
                      dbo.A_ORDER_ITEMS_PURCHASE_DATA.PROCEDURE_HIST_ID, dbo.A_ORDER_ITEMS.DUE_DATE, dbo.A_ORDER_ITEMS.ORIG_DUE_DATE, 
                      dbo.A_ORDER_ITEMS.ACT_DUE_DATE
FROM         dbo.A_ORDER_ITEMS INNER JOIN
                      dbo.A_ORDER_ITEMS_PURCHASE_DATA ON dbo.A_ORDER_ITEMS.ID = dbo.A_ORDER_ITEMS_PURCHASE_DATA.ORDER_ITEM_ID
