CREATE VIEW dbo.A_V_PRODUCTS_WITH_DATA
AS
SELECT     dbo.A_PRODUCTS_HISTORY.ID, dbo.A_PRODUCTS_HISTORY.NAME, dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID, 
                      dbo.A_PRODUCTS_HISTORY.COMMENTS, dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID, dbo.A_PRODUCTS_HISTORY.APP_OBJECT, 
                      dbo.A_PRODUCTS_HISTORY.SHIP_OR_LABOR, dbo.A_PRODUCTS_HISTORY.CUSTOMIZABLE, dbo.A_PRODUCTS_HISTORY.REQ_FORM, 
                      dbo.A_PRODUCTS_HISTORY.MGR_TEAM, dbo.A_PRODUCTS_HISTORY.SALES_TAX, dbo.A_PRODUCTS_HISTORY.DRCM, 
                      dbo.A_PRODUCTS_HISTORY.MODBY, dbo.A_PRODUCTS_HISTORY.OBJECT_ID, dbo.A_PRODUCTS_HISTORY.PARENT_ID, 
                      dbo.A_V_APPROVED_ROLES_DATA.NAME AS MGR_TEAM_NAME, SUPPLIER.NAME AS SUPPLIER_NAME, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROCEDURE_NAME, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC AS APP_OBJ_NAME, 
                      dbo.A_APPROVED_PRODUCTS.NAME AS PARENT_NAME, dbo.A_PRODUCTS_HISTORY.SYSTEM_PROCEDURE, 
                      dbo.A_PRODUCTS_HISTORY.CUST_MGR_ROLE, dbo.A_V_ROLE_DATA_BY_APPROVED_ID.NAME AS CUST_MGR_ROLE_NAME, 
                      dbo.A_PRODUCTS_HISTORY.PERSON_SUPPLIER, dbo.A_PRODUCTS_HISTORY.AVAILABILITY, dbo.A_PRODUCTS_HISTORY.OEM, 
                      dbo.A_PRODUCTS_HISTORY.MODEL, dbo.A_PRODUCTS_HISTORY.AREA, dbo.A_PRODUCTS_HISTORY.CU, dbo.A_PRODUCTS_HISTORY.MM
FROM         dbo.A_PRODUCTS_HISTORY LEFT OUTER JOIN
                      dbo.A_V_ROLE_DATA_BY_APPROVED_ID ON 
                      dbo.A_PRODUCTS_HISTORY.CUST_MGR_ROLE = dbo.A_V_ROLE_DATA_BY_APPROVED_ID.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_PRODUCTS ON dbo.A_PRODUCTS_HISTORY.PARENT_ID = dbo.A_APPROVED_PRODUCTS.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_PRODUCTS_HISTORY.APP_OBJECT = dbo.A_V_APPROVED_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER ON dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID = SUPPLIER.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_ROLES_DATA ON dbo.A_PRODUCTS_HISTORY.MGR_TEAM = dbo.A_V_APPROVED_ROLES_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID
