
CREATE  VIEW dbo.A_V_INVOICE_TASK_STOP_DATES
AS
SELECT     dbo.A_ACCOUNT_INVOICES.ID AS INVOICE_ID, dbo.A_TASKS.ACTUAL_STOP_DATE
FROM         dbo.A_TASKS INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION ON dbo.A_TASKS.ID = dbo.A_TASK_ORDER_INFORMATION.TASK_ID INNER JOIN
                      dbo.A_ACCOUNT_INVOICES INNER JOIN
                      dbo.A_ACCOUNT_INVOICE_ITEMS ON dbo.A_ACCOUNT_INVOICES.ID = dbo.A_ACCOUNT_INVOICE_ITEMS.INVOICE_ID ON 
                      dbo.A_TASK_ORDER_INFORMATION.FILL_ITEM_ID = dbo.A_ACCOUNT_INVOICE_ITEMS.FILL_ID

