CREATE VIEW dbo.A_V_ORDERS_WITH_ITEMS_AND_APPLICABLE_OBJECTS
AS
SELECT     dbo.A_V_ORDERS_APPROVED_DATA.ID AS ORDER_ID, dbo.A_V_ORDERS_APPROVED_DATA.HISTORY_REF_ID AS ORDER_HIST_REF_ID, 
                      dbo.A_ORDER_ITEMS.PRODUCT_ID, dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID, dbo.A_V_PRODUCTS_APPROVED_DATA.APP_OBJECT, 
                      dbo.A_V_ORDERS_APPROVED_DATA.DESCRIPTION, dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_CO, 
                      dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_PERSON, dbo.A_V_ORDERS_APPROVED_DATA.BUDGETARY_ONLY, 
                      dbo.A_V_ORDERS_APPROVED_DATA.EXPIRATION_DATE, dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, 
                      CUSTOMER.NAME AS CUSTOMER_NAME, SUPPLIER.NAME AS SUPPLIER_NAME, dbo.A_V_ORDERS_APPROVED_DATA.PROGRESS, 
                      dbo.A_ORDER_ITEMS.PROC_SYS_ID, dbo.A_ORDER_ITEMS.SOURCE_ID, dbo.A_ORDER_ITEMS.ADD_COST_ID, dbo.A_ORDER_ITEMS.PARENT, 
                      dbo.A_V_ORDERS_APPROVED_DATA.STATUS
FROM         dbo.A_V_ORDERS_APPROVED_DATA INNER JOIN
                      dbo.A_ORDER_ITEMS ON dbo.A_V_ORDERS_APPROVED_DATA.HISTORY_REF_ID = dbo.A_ORDER_ITEMS.ORDER_ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON dbo.A_ORDER_ITEMS.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUSTOMER ON dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_CO = CUSTOMER.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER ON dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID = SUPPLIER.ID
