


CREATE VIEW dbo.A_V_PROJECT_ALLOWED_COMPANIES_DATA
AS
SELECT     dbo.A_PROJECT_ALLOWED_COMPANIES.PROJECT_ID, dbo.A_PROJECT_ALLOWED_COMPANIES.COMPANY_ID, 
                      dbo.A_APPROVED_COMPANIES.NAME AS COMPANY_NAME
FROM         dbo.A_PROJECT_ALLOWED_COMPANIES INNER JOIN
                      dbo.A_APPROVED_COMPANIES ON dbo.A_PROJECT_ALLOWED_COMPANIES.COMPANY_ID = dbo.A_APPROVED_COMPANIES.ID



