


CREATE VIEW dbo.A_V_SURVEY_SEARCH_ALL_INVITED
AS
SELECT     s.ID, s.SUBJECT, s.OWNER, s.DATE_CREATED, s.STATUS, dbo.A_SURVEY_INV_PEOPLE.PEOPLE_ID AS P_ID, dbo.A_SURVEY_INV_ROLE.ROLE_ID, 
                      dbo.A_APPROVED_PEOPLE.FULL_NAME AS INITIATOR_NAME, dbo.A_TASK_SURVEY_LINK.TASK_ID, 
                      dbo.A_FN_SURVEYS_GET_STANDARD_SEARCH_FLAG(s.STATUS) AS STANDARD_SEARCH, 
                      dbo.A_SURVEY_REALLY_INIVTED_COMPANY.COMPANY_ID, dbo.A_SURVEY_REPLIES.AUTHOR, dbo.A_SURVEY_REPLIES.PARENT, 
                      dbo.A_SURVEY_REPLIES.NUM
FROM         dbo.A_SURVEYS s LEFT OUTER JOIN
                      dbo.A_SURVEY_REPLIES ON s.ID = dbo.A_SURVEY_REPLIES.ROOT LEFT OUTER JOIN
                      dbo.A_APPROVED_PEOPLE ON s.OWNER = dbo.A_APPROVED_PEOPLE.ID LEFT OUTER JOIN
                      dbo.A_SURVEY_REALLY_INIVTED_COMPANY ON s.ID = dbo.A_SURVEY_REALLY_INIVTED_COMPANY.SURVEY_ID LEFT OUTER JOIN
                      dbo.A_TASK_SURVEY_LINK ON s.ID = dbo.A_TASK_SURVEY_LINK.SURVEY_ID LEFT OUTER JOIN
                      dbo.A_SURVEY_INV_ROLE ON s.ID = dbo.A_SURVEY_INV_ROLE.SURVEY_ID LEFT OUTER JOIN
                      dbo.A_SURVEY_INV_PEOPLE ON s.ID = dbo.A_SURVEY_INV_PEOPLE.SURVEY_ID



