


CREATE VIEW dbo.A_V_PROJECT_ALLOWED_ROLES_DATA
AS
SELECT     dbo.A_PROJECT_ALLOWED_ROLES.ROLE_ID, dbo.A_APPROVED_ROLES.NAME AS ROLE_NAME, 
                      dbo.A_PROJECT_ALLOWED_ROLES.PROJECT_ID
FROM         dbo.A_PROJECT_ALLOWED_ROLES INNER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_PROJECT_ALLOWED_ROLES.ROLE_ID = dbo.A_APPROVED_ROLES.ID



