

CREATE VIEW dbo.A_V_TASK_QUOTE_ORDER_INFORMATION
AS
SELECT     dbo.A_QUOTE_ORDER_LINK.QUOTE_ID, dbo.A_QUOTE_ORDER_LINK.ORDER_ID, dbo.A_QUOTE_ORDER_LINK.STATUS, 
                      dbo.A_QUOTE_ORDER_LINK.CUSTOMER, dbo.A_QUOTE_ORDER_LINK.SUPPLIER, dbo.A_QUOTE_ORDER_LINK.TASK_ID, 
                      dbo.A_V_ORDERS_APPROVED_DATA.PROGRESS AS ORDER_PROGRESS, dbo.A_QUOTE_ORDER_LINK.ID, 
                      dbo.A_QUOTES_HISTORY.OBJECT_ID AS QUOTE_OBJECT_ID, dbo.A_QUOTES_HISTORY.PROGRESS AS QUOTE_PROGRESS, 
                      dbo.A_OBJECTS.STATUS AS QUOTE_STATUS, dbo.A_QUOTES_HISTORY.ID AS Expr1, dbo.A_OBJECTS.ROOT, 
                      dbo.A_QUOTE_ORDER_LINK.QA_TASK_ID
FROM         dbo.A_OBJECTS RIGHT OUTER JOIN
                      dbo.A_QUOTES_HISTORY ON dbo.A_OBJECTS.ID = dbo.A_QUOTES_HISTORY.OBJECT_ID RIGHT OUTER JOIN
                      dbo.A_TASKS INNER JOIN
                      dbo.A_QUOTE_ORDER_LINK ON dbo.A_TASKS.ID = dbo.A_QUOTE_ORDER_LINK.TASK_ID ON 
                      dbo.A_QUOTES_HISTORY.ORDER_ID = dbo.A_QUOTE_ORDER_LINK.ORDER_ID LEFT OUTER JOIN
                      dbo.A_V_ORDERS_APPROVED_DATA ON dbo.A_QUOTE_ORDER_LINK.ORDER_ID = dbo.A_V_ORDERS_APPROVED_DATA.ID


