



CREATE VIEW dbo.A_V_PROCEDURE_STEP_DOCUMENT_DATA
AS
SELECT     dbo.A_PROCEDURE_STEP_FILE_LINK.STEP_ID, dbo.A_DOCUMENTS.*
FROM         dbo.A_PROCEDURE_STEP_FILE_LINK INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_PROCEDURE_STEP_FILE_LINK.FILE_ID = dbo.A_DOCUMENTS.ID




