CREATE VIEW dbo.A_V_LOCATIONS_BY_APPROVED_ID
AS
SELECT     l.ID, l.HISTORY_REF_ID, lh.NAME, lh.PARENT_LOCATION, lh.PARENT_LOCATION_NAME, lh.ADDRESS_1, lh.ADDRESS_2, lh.FULL_ADDRESS, lh.CITY, 
                      lh.STATE, lh.COUNTRY, lh.POSTAL_CODE, lh.REGION, lh.REGION_NAME, lh.INTERNAL_ADDRESS, lh.OBJECT_ID, lh.DRCM, lh.MODBY, 
                      lh.PARENT_PATH, o.CREATING_CO, lh.COMPLETE_NAME
FROM         dbo.A_LOCATIONS l INNER JOIN
                      dbo.A_LOCATIONS_HISTORY lh ON l.HISTORY_REF_ID = lh.ID INNER JOIN
                      dbo.A_OBJECTS o ON lh.OBJECT_ID = o.ID
