CREATE VIEW dbo.A_V_PEOPLE_OBJECT_SEARCH
AS
SELECT     p.*, o.LOCKED_BY AS LOCKED_BY, o.UNLOCKED_BY AS UNLOCKED_BY, o.CREATED_BY AS CREATED_BY, o.CREATE_DATE AS CREATE_DATE, 
                      dbo.leadingSpaces(o.ROOT, 50) AS SORT_ROOT, LTRIM(STR(YEAR(p.HIRE_DATE))) + '-' + dbo.leadingZeros(LTRIM(STR(MONTH(p.HIRE_DATE))), 2) 
                      + '-' + dbo.leadingZeros(LTRIM(STR(DAY(p.HIRE_DATE))), 2) AS DATE_HIRED, o.ROOT AS ROOT, o.REV_INFO AS REV_INFO, 
                      o.CREATING_CO AS CREATING_CO, o.STATUS AS STATUS, o.REV AS REV, o.WFS_ID AS WFS_ID, o.LOCKED_BY_NAME AS LOCKED_BY_NAME, 
                      o.CREATING_CO_NAME AS CREATING_CO_NAME, dbo.isBoss(o.ROOT) AS isBoss, dbo.A_FN_FILES_SHOW_ALL_XML_DATA_FOR_OBJECT(p.OBJ_ID, 
                      'PICTURE') AS picRecord, dbo.A_PEOPLE_HISTORY.ROOT_COMPANY AS ROOT_CO_ID, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS ROOT_CO_NAME, dbo.A_PEOPLE_HISTORY.LOGIN AS LOGIN
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE p ON o.ID = p.OBJ_ID INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON p.ID = dbo.A_PEOPLE_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_PEOPLE_HISTORY.ROOT_COMPANY = dbo.A_V_COMPANIES_APPROVED_DATA.ID
