


CREATE VIEW dbo.A_V_QUOTE_ORDER_LINK_WITH_COMPANY_NAMES
AS
SELECT     QOL.QUOTE_ID, QOL.ORDER_ID, QOL.STATUS, QOL.CUSTOMER, QOL.SUPPLIER, C.NAME AS CUSTOMER_NAME, S.NAME AS SUPPLIER_NAME, 
                      ORD_HIST.DESCRIPTION AS ORDER_DESCRIPTION, ORD_HIST.CUSTOMER_PERSON, CUST_PERSON.P_NAME AS CUSTOMER_PERSON_NAME, 
                      ORD_HIST.BUDGETARY_ONLY, ORD_HIST.EXPIRATION_DATE, ORD_HIST.PROGRESS, 
                      dbo.A_V_QUOTE_ORDER_LINK_WITH_RESPONSIBLE_ROLE.ROLE_ID, dbo.A_V_QUOTE_ORDER_LINK_WITH_RESPONSIBLE_ROLE.ROLE_NAME, 
                      QOL.ID AS QOL_ID
FROM         dbo.A_QUOTE_ORDER_LINK QOL INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA C ON QOL.CUSTOMER = C.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA S ON QOL.SUPPLIER = S.ID INNER JOIN
                      dbo.A_ORDERS ORD ON QOL.ORDER_ID = ORD.ID INNER JOIN
                      dbo.A_ORDERS_HISTORY ORD_HIST ON ORD.HISTORY_REF_ID = ORD_HIST.ID INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN CUST_PERSON ON ORD_HIST.CUSTOMER_PERSON = CUST_PERSON.P_ID INNER JOIN
                      dbo.A_V_QUOTE_ORDER_LINK_WITH_RESPONSIBLE_ROLE ON QOL.ID = dbo.A_V_QUOTE_ORDER_LINK_WITH_RESPONSIBLE_ROLE.QOL_ID



