
CREATE VIEW dbo.A_V_ACTUAL_PARTS_WITH_RECENT_TASKS
AS
SELECT DISTINCT 
                      dbo.A_TASKS.PROCEDURE_ID, dbo.A_TASKS.ORIG_REQUESTOR_ID, dbo.A_TASKS.LAST_REQUEST_DATE, dbo.A_TASKS.GROUP_REQUESTEE_ID, 
                      dbo.A_TASKS.REQUESTEE_ID, dbo.A_ACTUAL_PARTS.ID AS ACTUAL_PART_ID
FROM         dbo.A_TASK_OBJECT_LINK INNER JOIN
                      dbo.A_TASKS ON dbo.A_TASK_OBJECT_LINK.TASK_ID = dbo.A_TASKS.ID INNER JOIN
                      dbo.A_ACTUAL_PARTS ON dbo.A_TASK_OBJECT_LINK.OBJECT_ID = dbo.A_ACTUAL_PARTS.ID
WHERE     (dbo.A_TASKS.LAST_REQUEST_DATE > DATEADD(n, - 20, GETDATE()))

