




CREATE VIEW dbo.A_V_DOCUMENTS_LINKED
AS
SELECT     dbo.A_DOCUMENTS.DOC_ID, dbo.A_DOCUMENTS.NAME AS DOC_NAME, dbo.A_DOCUMENT_LINK.TYPE, dbo.A_DOCUMENT_LINK.OBJECT_ID
FROM         dbo.A_DOCUMENTS INNER JOIN
                      dbo.A_DOCUMENT_LINK ON dbo.A_DOCUMENTS.ID = dbo.A_DOCUMENT_LINK.LINKED_DOC_ID





