CREATE VIEW dbo.A_V_TT_VERBS_APPROVED_DATA
AS
SELECT     dbo.A_TT_VERBS.ID, dbo.A_TT_VERBS_HISTORY.NAME, dbo.A_TT_VERBS_HISTORY.SHOW_NAME, dbo.A_OBJECTS.STATUS, 
                      dbo.A_OBJECTS.CREATING_CO
FROM         dbo.A_TT_VERBS INNER JOIN
                      dbo.A_TT_VERBS_HISTORY ON dbo.A_TT_VERBS.HISTORY_REF_ID = dbo.A_TT_VERBS_HISTORY.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_TT_VERBS_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID
WHERE     (dbo.A_OBJECTS.STATUS LIKE 'APPROVED%')
