


CREATE VIEW dbo.A_V_SERVICE_CALLS_WITH_NORMAL_HOURS
AS
SELECT     worker.BOSS, w_type.SUPPLIER_NAME, w_type.CUSTOMER_NAME, w_type.SUPPLIER_ID, w_type.CUSTOMER_ID, w_type.APPROVER_ROLE, 
                      w_type.TAX_RATE / 100 AS ACTUAL_TAX_RATE, w_type.PAYER_ROLE, w_type.APPROVER_ROLE_NAME AS APPROVER, 
                      w_type.PAYER_ROLE_NAME AS PAYER, SC.WORKER_ID, SC.ID, SC.MACHINE_NAME, worker.FULL_NAME, 
                      w_type.WORK_TYPE_NAME AS WORK_TYPE, SUM(n_hours.HOURS) AS NORMAL_HOURS, SC.STATUS, SC.START_DAY, SC.START_MONTH, 
                      SC.START_YEAR, SC.REASON, SC.CHECK_NUM, CONVERT(dateTime, STR(SC.START_MONTH) + '/' + STR(SC.START_DAY) 
                      + '/' + STR(SC.START_YEAR)) AS START_DATE, SC.HOUR_RATE_FIXED, SC.OT_RATE_FIXED, SC.ORDER_NUMBER, 
                      SC.WORK_TYPE AS WORK_TYPE_ID, w_type.TAX_RATE, SC.INVOICE_DATE, SC.EXPENSES_AMOUNT, SC.REASON_TYPE, SC.COMMENTS
FROM         dbo.A_V_SERVICE_CALL_WORK_TYPE_DATA w_type RIGHT OUTER JOIN
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS SC LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_SELF_BOSS_IF_NULL worker ON SC.WORKER_ID = worker.ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALLS_NORMAL_HOURS n_hours ON SC.ID = n_hours.WEEKLY_ID ON w_type.ID = SC.WORK_TYPE
GROUP BY worker.BOSS, w_type.SUPPLIER_NAME, w_type.CUSTOMER_NAME, w_type.SUPPLIER_ID, w_type.CUSTOMER_ID, w_type.APPROVER_ROLE, 
                      w_type.PAYER_ROLE, w_type.APPROVER_ROLE_NAME, SC.STATUS, SC.WORKER_ID, SC.ID, SC.MACHINE_NAME, worker.FULL_NAME, 
                      w_type.WORK_TYPE_NAME, w_type.PAYER_ROLE_NAME, SC.STATUS, SC.START_DAY, SC.START_MONTH, SC.START_YEAR, SC.REASON, 
                      SC.CHECK_NUM, SC.HOUR_RATE_FIXED, SC.OT_RATE_FIXED, SC.ORDER_NUMBER, SC.WORK_TYPE, w_type.TAX_RATE, SC.INVOICE_DATE, 
                      SC.EXPENSES_AMOUNT, SC.REASON_TYPE, SC.COMMENTS



