CREATE VIEW dbo.A_V_TASK_PART_PURCH_ITEM_QUICK
AS
SELECT     dbo.A_TASK_ORDER_INFORMATION.TASK_ID, dbo.A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED.ACTUAL_PART_ID, 
                      dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID, dbo.A_TASKS.STATUS
FROM         dbo.A_TASKS INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION ON dbo.A_TASKS.ID = dbo.A_TASK_ORDER_INFORMATION.TASK_ID INNER JOIN
                      dbo.A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED ON 
                      dbo.A_TASKS.ID = dbo.A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED.TASK_ID
WHERE     (dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID = '215214') AND 
                      (dbo.A_TASK_ACTUAL_PARTS_LINKED_WHEN_FINISHED.ACTUAL_PART_ID = '211377')
