



CREATE VIEW dbo.A_V_APPROVED_ROLES_WITH_NTLOGIN_ID
AS
SELECT     dbo.A_APPROVED_PEOPLE.ID AS PERSON, dbo.A_APPROVED_PEOPLE.FULL_NAME, 
                      dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.ROLE_NAME, dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.ROLE_ID AS ROLE, 
                      dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.BOSS_ID, dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.BOSS_NAME, 
                      dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.COMPANY_ID, dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.COMPANY_NAME, 
                      dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.POSITION_ID, dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.POSITION_NAME, 
                      dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.ROLE_STATUS, dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.OBJ_ID
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES ON 
                      dbo.A_APPROVED_PEOPLE.OBJECT_ID = dbo.A_V_PEOPLE_OBJECT_SEARCH_WITH_ROLES.OBJ_ID




