


CREATE VIEW dbo.A_V_ROLES_ASSIGNED_ROLES_TO_A_ROLE
AS
SELECT     TOP 100 PERCENT rh.ROLE_NAME, rh.STATUS, rh.ID AS ROLE_ID, ra.STATUS AS RA_STATUS, ra.ROLE AS ID, rh.OBJ_ID, 
                      ar.ID AS ROLE_ASSIGNED_ID, ar.HISTORY_REF_ID AS ROLE_ASSIGNED_HISTORY_REF_ID, rh.ROOT, ra.PERSON
FROM         dbo.A_APPROVED_ROLES ar RIGHT OUTER JOIN
                      dbo.A_ROLE_ASSIGNEE ra ON ar.ID = ra.ROLE_ASSIGNED RIGHT OUTER JOIN
                      dbo.A_O_ROLES rh ON ra.ROLE = rh.ID
WHERE     (rh.STATUS = 'APPROVED')



