CREATE VIEW dbo.A_V_TASK_OBJECT_LINK_ALL_DATA
AS
SELECT     TOP 100 PERCENT dbo.A_TASK_OBJECT_LINK.TASK_ID, dbo.A_TASK_OBJECT_LINK.OBJECT_ID, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC, 
                      dbo.A_V_APPROVED_OBJECTS.OBJ_TABLE, dbo.A_V_APPROVED_OBJECTS.OBJ_ID
FROM         dbo.A_TASK_OBJECT_LINK INNER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_TASK_OBJECT_LINK.OBJECT_ID = dbo.A_V_APPROVED_OBJECTS.ID
ORDER BY dbo.A_TASK_OBJECT_LINK.DRCM DESC
