


CREATE VIEW dbo.A_V_PROJECT_MEMBER_DATA
AS
SELECT     dbo.A_PROJECT_MEMBERS.PEOPLE_ID AS MEMBER_ID, dbo.A_PROJECT_MEMBERS.PROJECT_ID, 
                      dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS MEMBER_NAME
FROM         dbo.A_PROJECT_MEMBERS INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_PROJECT_MEMBERS.PEOPLE_ID = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID



