


CREATE VIEW dbo.A_V_POP_FILL_MEETING_INVITED_PEOPLE
AS
SELECT     dbo.A_MEETING_INV_PEOPLE.MEETING_ID AS M_ID, dbo.A_APPROVED_PEOPLE.FULL_NAME, dbo.A_APPROVED_PEOPLE.ID AS P_ID, 
                      dbo.A_MEETING_INV_PEOPLE.OPTIONAL
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_MEETING_INV_PEOPLE ON dbo.A_APPROVED_PEOPLE.ID = dbo.A_MEETING_INV_PEOPLE.PEOPLE_ID