CREATE VIEW dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK
AS
SELECT     dbo.A_LOCATIONS.ID, dbo.A_LOCATIONS.HISTORY_REF_ID, dbo.A_LOCATIONS_HISTORY.NAME, dbo.A_LOCATIONS_HISTORY.PARENT_LOCATION, 
                      dbo.A_LOCATIONS_HISTORY.PARENT_LOCATION_NAME, dbo.A_LOCATIONS_HISTORY.ADDRESS_1, dbo.A_LOCATIONS_HISTORY.ADDRESS_2, 
                      dbo.A_LOCATIONS_HISTORY.FULL_ADDRESS, dbo.A_LOCATIONS_HISTORY.CITY, dbo.A_LOCATIONS_HISTORY.STATE, 
                      dbo.A_LOCATIONS_HISTORY.COUNTRY, dbo.A_LOCATIONS_HISTORY.POSTAL_CODE, dbo.A_LOCATIONS_HISTORY.REGION, 
                      dbo.A_LOCATIONS_HISTORY.REGION_NAME, dbo.A_LOCATIONS_HISTORY.INTERNAL_ADDRESS, dbo.A_LOCATIONS_HISTORY.OBJECT_ID, 
                      dbo.A_LOCATIONS_HISTORY.PARENT_PATH, dbo.A_LOCATIONS_HISTORY.COMPLETE_NAME
FROM         dbo.A_LOCATIONS_HISTORY INNER JOIN
                      dbo.A_LOCATIONS ON dbo.A_LOCATIONS_HISTORY.ID = dbo.A_LOCATIONS.HISTORY_REF_ID
