CREATE VIEW dbo.A_V_PROCEDURE_STEPS_WITH_OWNER_LABOR
AS
SELECT     dbo.A_V_PROCEDURE_STEP_OWNER_ROLE.RELATIONSHIP AS RELATIONSHIP, 
                      dbo.A_V_PROCEDURE_STEP_OWNER_ROLE.LABOR_ROLE AS LABOR_ROLE, 
                      dbo.A_V_PROCEDURE_STEP_OWNER_ROLE.OWNER_ROLE_ID AS OWNER_ROLE_ID, 
                      dbo.A_V_PROCEDURE_STEP_OWNER_ROLE.QTY AS OWNER_LABOR_TIME, 
                      dbo.A_V_PROCEDURE_STEP_OWNER_ROLE.QTY_TYPE AS OWNER_LABOR_TYPE, dbo.A_PROCEDURE_STEPS.ID, 
                      dbo.A_PROCEDURE_STEPS.PROCEDURE_ID, 
					  dbo.A_PROCEDURE_STEPS.STEP_TEXT,
					  dbo.A_PROCEDURE_STEPS.TITLE,
					  dbo.A_PROCEDURE_STEPS.START_ON_COUNTER, 
                      dbo.A_PROCEDURE_STEPS.COUNTER_VALUE, dbo.A_PROCEDURE_STEPS.COUNTER_UNIT, dbo.A_PROCEDURE_STEPS.REL_OR_ABS, 
                      dbo.A_PROCEDURE_STEPS.FROM_START_OR_STOP, dbo.A_PROCEDURE_STEPS.SYSTEM_TASK, dbo.A_PROCEDURE_STEPS.DESTINATION, 
                      dbo.A_PROCEDURE_STEPS.SPECIFIC_LOCATION, dbo.A_PROCEDURE_STEPS.REFERENCE_VERB, 
                      dbo.A_PROCEDURE_STEPS.REFERENCE_OBJECT, dbo.A_PROCEDURE_STEPS.COMMENTS, dbo.A_PROCEDURE_STEPS.GOTO_STEP, 
                      dbo.A_PROCEDURE_STEPS.GOTO_STEP_ID, dbo.A_PROCEDURE_STEPS.CYCLES, dbo.A_PROCEDURE_STEPS.CYCLE_ON_COUNTER, 
                      dbo.A_PROCEDURE_STEPS.CYCLE_COUNT, dbo.A_PROCEDURE_STEPS.CYCLE_UNIT, dbo.A_PROCEDURE_STEPS.DRCM, 
                      dbo.A_PROCEDURE_STEPS.MODBY, dbo.A_PROCEDURE_STEPS.PRINT_ORDER, dbo.A_PROCEDURE_STEPS.OLD_PROCEDURE_ID, 
                      dbo.A_PROCEDURE_STEPS.OLD_STEP_ID, dbo.A_PROCEDURE_STEPS.DURATION, dbo.A_PROCEDURE_STEPS.DURATION_TYPE, 
                      dbo.A_PROCEDURE_STEPS.DATE_LAST_MODIFIED
FROM         dbo.A_PROCEDURE_STEPS LEFT OUTER JOIN
                      dbo.A_V_PROCEDURE_STEP_OWNER_ROLE ON dbo.A_PROCEDURE_STEPS.ID = dbo.A_V_PROCEDURE_STEP_OWNER_ROLE.STEP_ID
