


CREATE VIEW dbo.A_V_PROCEDURE_HEADER_REFERENCE_FILES
AS
SELECT     dbo.A_PROCEDURES_HISTORY.ID AS PROC_ID, dbo.A_DOCUMENTS.*, dbo.A_PROCEDURES_HISTORY.OBJECT_ID AS P_OBJ_ID
FROM         dbo.A_DOCUMENT_LINK INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_DOCUMENT_LINK.LINKED_DOC_ID = dbo.A_DOCUMENTS.ID INNER JOIN
                      dbo.A_PROCEDURES_HISTORY ON dbo.A_DOCUMENT_LINK.OBJECT_ID = dbo.A_PROCEDURES_HISTORY.OBJECT_ID



