CREATE VIEW dbo.A_V_FORECAST_ITEMS_WITH_PARENT_ITEM_NAM
AS
SELECT     dbo.A_FORECAST_ITEMS.ID AS CHILD_ID, A_FORECAST_ITEMS_1.ID AS PARENT_ID, 
                      A_ACCOUNTS_HISTORY_1.NAME AS PARENT_ACCOUNT_NAME
FROM         dbo.A_ACCOUNTS_HISTORY INNER JOIN
                      dbo.A_FORECAST_ITEMS INNER JOIN
                      dbo.A_ACCOUNTS ON dbo.A_FORECAST_ITEMS.ACCOUNT_ID = dbo.A_ACCOUNTS.ID ON 
                      dbo.A_ACCOUNTS_HISTORY.ID = dbo.A_ACCOUNTS.HISTORY_REF_ID INNER JOIN
                      dbo.A_ACCOUNTS A_ACCOUNTS_1 INNER JOIN
                      dbo.A_FORECAST_ITEMS A_FORECAST_ITEMS_1 ON A_ACCOUNTS_1.ID = A_FORECAST_ITEMS_1.ACCOUNT_ID ON 
                      dbo.A_ACCOUNTS_HISTORY.PARENT_ACCOUNT = A_ACCOUNTS_1.ID AND 
                      dbo.A_FORECAST_ITEMS.FORECAST_ID = A_FORECAST_ITEMS_1.FORECAST_ID INNER JOIN
                      dbo.A_ACCOUNTS_HISTORY A_ACCOUNTS_HISTORY_1 ON A_ACCOUNTS_1.HISTORY_REF_ID = A_ACCOUNTS_HISTORY_1.ID
