CREATE VIEW dbo.A_V_FILL_TASKS
AS
SELECT     dbo.A_TASKS.ID AS TASK_ID, dbo.A_FILLS.PURCH_ITEM_ID, dbo.A_TASKS.REQUESTEE_ID
FROM         dbo.A_FILLS INNER JOIN
                      dbo.A_TASKS ON dbo.A_FILLS.TASK_ID = dbo.A_TASKS.ID
