
CREATE  VIEW dbo.A_V_ROLES_WITH_ASSIGNEES
AS
SELECT     r.ROLE_NAME, r.STATUS, r.ID AS ROLE_ID, p.ID AS PERSON_ID, p.FULL_NAME AS MEMBER_NAME, ra.STATUS AS RA_STATUS, 
                      p.SYSTEM_STATUS AS PERSON_STATUS, r.CREATING_CO, r.HIDDEN, ra.ROLE AS ID, r.OBJ_ID, r.LOCKED_BY, r.UNLOCKED_BY, r.CREATED_BY, 
                      r.CREATE_DATE, r.ROOT, r.REV_INFO, r.SOURCE, r.LOCKED_BY_NAME, r.CREATING_CO_NAME, r.REV, r.WFS_ID, r.SECURITY_LEVEL, r.IS_ADMIN, 
                      r.SECURITY_LEVEL_NAME
FROM         dbo.A_APPROVED_PEOPLE p RIGHT OUTER JOIN
                      dbo.A_ROLE_ASSIGNEE ra ON p.ID = ra.PERSON RIGHT OUTER JOIN
                      dbo.A_O_ROLES r ON ra.ROLE = r.ID

