CREATE VIEW dbo.A_V_ACCOUNTS_PURCHASABLE_ORDERS
AS
SELECT     dbo.A_ACCOUNT_PURCHASABLE_ORDERS_LINK.ACCOUNT_ID AS ACCOUNT_OBJECT_ID, 
                      dbo.A_ACCOUNT_PURCHASABLE_ORDERS_LINK.ORDER_ID, dbo.A_V_ORDERS_LOOK_UP_FOR_ACCOUNT.NAME, 
                      dbo.A_V_ACCOUNTS_APPROVED_DATA.ID AS ACCT_ID, dbo.A_V_ORDERS_LOOK_UP_FOR_ACCOUNT.PROGRESS, 
                      dbo.A_V_ORDERS_LOOK_UP_FOR_ACCOUNT.EXPIRATION_DATE
FROM         dbo.A_V_ORDERS_LOOK_UP_FOR_ACCOUNT INNER JOIN
                      dbo.A_ACCOUNT_PURCHASABLE_ORDERS_LINK ON 
                      dbo.A_V_ORDERS_LOOK_UP_FOR_ACCOUNT.ORDER_ID = dbo.A_ACCOUNT_PURCHASABLE_ORDERS_LINK.ORDER_ID LEFT OUTER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA ON 
                      dbo.A_ACCOUNT_PURCHASABLE_ORDERS_LINK.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA.OBJECT_ID
WHERE     (dbo.A_V_ORDERS_LOOK_UP_FOR_ACCOUNT.PROGRESS = 'ALL_QUOTES_ACCEPTED')
