CREATE VIEW dbo.A_V_PRODUCTS_APPROVED_DATA_BY_ID
AS
SELECT     dbo.A_PRODUCTS.ID, dbo.A_PRODUCTS_HISTORY.NAME, dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS SUPPLIER_NAME, dbo.A_PRODUCTS_HISTORY.COMMENTS, 
                      dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID, dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROC_NAME, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.SYSTEM_ID AS PROC_SYS_ID, dbo.A_PRODUCTS_HISTORY.APP_OBJECT, 
                      dbo.A_PRODUCTS_HISTORY.SHIP_OR_LABOR, dbo.A_PRODUCTS_HISTORY.CUSTOMIZABLE, dbo.A_PRODUCTS_HISTORY.REQ_FORM, 
                      dbo.A_PRODUCTS_HISTORY.MGR_TEAM, dbo.A_PRODUCTS_HISTORY.SALES_TAX, dbo.A_PRODUCTS_HISTORY.OBJECT_ID AS PROD_OBJ_ID, 
                      dbo.A_PRODUCTS_HISTORY.PARENT_ID, dbo.A_PRODUCTS_HISTORY.CUST_MGR_ROLE, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.OBJECT_ID AS PROC_OBJ_ID, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.HISTORY_REF_ID AS PROC_HIST_ID, dbo.A_PRODUCTS_HISTORY.AVAILABILITY, 
                      dbo.A_PRODUCTS_HISTORY.PERSON_SUPPLIER, dbo.A_PRODUCTS_HISTORY.SYSTEM_PROCEDURE
FROM         dbo.A_PRODUCTS INNER JOIN
                      dbo.A_PRODUCTS_HISTORY ON dbo.A_PRODUCTS.HISTORY_REF_ID = dbo.A_PRODUCTS_HISTORY.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID
