CREATE VIEW dbo.A_V_DNR_ACTUAL_PARTS_INFO
AS
SELECT     dbo.A_DNR_PART_INFO.ACT_PART_ID, dbo.A_DNR_PART_INFO.DNR_ID, dbo.A_DNR_PART_INFO.TASK_ID, 
                      dbo.A_DNR_PART_INFO.CUR_OWNER_NAME, dbo.A_DNR_PART_INFO.CUR_OWNER_ID, dbo.A_DNR_PART_INFO.ORIG_OWNER_NAME, 
                      dbo.A_DNR_PART_INFO.ORIG_OWNER_ID, dbo.A_DNR_PART_INFO.DNR_STATUS, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.NICK_NAME, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.QTY, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.AP_STATUS, dbo.A_V_PARTS_APPROVED_DATA.NAME AS PART_NAME, 
                      dbo.A_V_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER
FROM         dbo.A_DNR_PART_INFO INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON dbo.A_DNR_PART_INFO.ACT_PART_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PARTS_APPROVED_DATA ON dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_ID = dbo.A_V_PARTS_APPROVED_DATA.ID
