



CREATE VIEW dbo.A_V_ORDERS_SHARED_SUPPLIER_LIST
AS
SELECT     dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS CO_NAME, dbo.A_V_COMPANIES_APPROVED_DATA.ID AS CO_ID, 
                      dbo.A_ORDERS_HISTORY.ID AS ORDER_ID
FROM         dbo.A_ORDERS_HISTORY INNER JOIN
                      dbo.A_ORDERS_SUPPLIERS_TO_SHARE_WITH ON 
                      dbo.A_ORDERS_HISTORY.ID = dbo.A_ORDERS_SUPPLIERS_TO_SHARE_WITH.ORDER_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON 
                      dbo.A_ORDERS_SUPPLIERS_TO_SHARE_WITH.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID




