CREATE VIEW dbo.A_V_PEOPLE_PERFERENCES_GET_DATA_BY_NTLOGIN
AS
SELECT     dbo.A_PEOPLE.ID, dbo.A_PEOPLE_HISTORY.LOGIN, dbo.A_PEOPLE_HISTORY.PASSWORD, dbo.A_PEOPLE_SEARCH_TABLE.TIME_ZONE, 
                      dbo.A_PEOPLE_HISTORY.LANG, dbo.A_PEOPLE_HISTORY.FULL_NAME, dbo.A_PEOPLE_HISTORY.TOOL_BOX
FROM         dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE ON dbo.A_PEOPLE_HISTORY.ID = dbo.A_PEOPLE_SEARCH_TABLE.ID
