


CREATE VIEW dbo.A_V_POP_FILL_MEETING_INVITED_COMPANY
AS
SELECT     dbo.A_APPROVED_COMPANIES.ID AS C_ID, dbo.A_MEETING_INV_COMPANY.MEETING_ID AS M_ID, 
                      dbo.A_APPROVED_COMPANIES.NAME AS COMPANY_NAME, dbo.A_MEETING_INV_COMPANY.OPTIONAL
FROM         dbo.A_MEETING_INV_COMPANY INNER JOIN
                      dbo.A_APPROVED_COMPANIES ON dbo.A_MEETING_INV_COMPANY.COMPANY_ID = dbo.A_APPROVED_COMPANIES.ID



