

CREATE VIEW dbo.A_V_TASK_EDIT_DATA
AS
SELECT     TASK.ID, TASK.PARENT_ID,
PARENT.DESCRIPTION AS PARENT_NAME,
TASK.Title, 
TASK.DESCRIPTION, 
TASK.STATUS, 
TASK.COMMENT,
TASK.REQUESTOR, 
TASK.COMPLETED_BY,
TASK.CHILD_ORDER, 
TASK.CREATED_BY, 
TASK.CREATE_DATE, 
TASK.CLOSED, 
TASK.OPENED_BY,
TASK.OPEN_DATE, 
TASK.SYSTEM_TASK,
TASK.PROCEDURE_ID, 
TASK.PROCEDURE_STEP_ID,
[PROC].NAME AS PROCEDURE_NAME, 
TASK.SECURITY_LEVEL, 
TASK.COUNTER AS COUNTER_ID,
REQUESTOR.P_NAME AS REQUESTOR_NAME,
TASK.REQUESTEE_ID, 
REQUESTEE.P_NAME AS REQUESTEE_NAME,
TASK.GROUP_REQUESTEE_ID, 
GROUP_REQUESTEE.NAME AS GROUP_REQUESTEE_NAME, 
TASK.COUNTER_NAME, 
TASK.COUNTER_VALUE, 
TASK.ORIG_PLANNED_START_DATE,
TASK.ORIG_PLANNED_STOP_DATE, 
TASK.CUR_PLANNED_START_DATE,
TASK.CUR_PLANNED_STOP_DATE, 
TASK.ACTUAL_START_DATE, 
TASK.ACTUAL_STOP_DATE, 
TASK.ORIG_PLANNED_COUNTER_START, 
TASK.ORIG_PLANNED_COUNTER_STOP,
TASK.CUR_PLANNED_COUNTER_START, 
TASK.CUR_PLANNED_COUNTER_STOP, 
TASK.ACTUAL_COUNTER_START, 
TASK.ACTUAL_COUNTER_STOP, 
TASK.LATEST_REQUESTEE_NAME, 
TASK.HAS_DISCUSSION,
TASK.HAS_SURVEY, 
TASK.HAS_CHILD, 
TASK.HAS_REF_PROC,
TASK.HAS_FILE, 
dbo.A_SECURITY_LEVELS.NAME AS SEC_LEV_NAME, 
TASK.ORIG_REQUESTOR_ID, 
TASK.HAS_REF_OBJ, 
TASK.HAS_MONITOR, 
ORIG_REQUESTOR.FULL_NAME AS ORIG_REQUESTOR_NAME, 
TASK.COLOR_CODE, 
dbo.A_TASK_SURVEY_LINK.SURVEY_ID,
TASK.LAST_REQUEST_DATE, 
TASK.PRIORITY,
TASK.IS_FILL, 
TASK.IS_QUOTE_ACCEPT, 
TASK.IS_QUOTE
FROM         dbo.A_TASK_SURVEY_LINK RIGHT OUTER JOIN
dbo.A_TASKS PARENT RIGHT OUTER JOIN
dbo.A_TASKS TASK ON PARENT.ID = TASK.PARENT_ID ON 
dbo.A_TASK_SURVEY_LINK.TASK_ID = TASK.ID LEFT OUTER JOIN
dbo.A_SECURITY_LEVELS ON TASK.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID LEFT OUTER JOIN
dbo.A_V_PEOPLE_APPROVED_DATA ORIG_REQUESTOR ON TASK.ORIG_REQUESTOR_ID = ORIG_REQUESTOR.ID LEFT OUTER JOIN
dbo.A_V_PEOPLE_BY_NTLOGIN REQUESTEE ON TASK.REQUESTEE_ID = REQUESTEE.P_ID LEFT OUTER JOIN
dbo.A_V_ROLE_DATA_BY_APPROVED_ID GROUP_REQUESTEE ON TASK.GROUP_REQUESTEE_ID = GROUP_REQUESTEE.ID LEFT OUTER JOIN
dbo.A_V_PEOPLE_BY_NTLOGIN REQUESTOR ON TASK.REQUESTOR = REQUESTOR.P_ID LEFT OUTER JOIN
dbo.A_APPROVED_PROCEDURES [PROC] ON TASK.PROCEDURE_ID = [PROC].ID


