




CREATE VIEW dbo.A_V_FAVORITE_MENU_ITEMS
AS
SELECT     dbo.A_MENUS.ID, dbo.A_MENUS.URL, dbo.A_MENUS.NAME, dbo.A_PEOPLES_FAVORITES.NUM, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.ID AS FAV_GROUP, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.PERSON
FROM         dbo.A_MENUS INNER JOIN
                      dbo.A_PEOPLES_FAVORITES ON dbo.A_MENUS.ID = dbo.A_PEOPLES_FAVORITES.ITEM RIGHT OUTER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS ON dbo.A_PEOPLES_FAVORITES.[GROUP] = dbo.A_PEOPLES_FAVORITE_GROUPS.ID