

CREATE VIEW dbo.A_V_ACTUAL_PARTS_CALL_DATA_COMPLETE
AS
SELECT     dbo.A_ACTUAL_PARTS_CALL_DATA.ACTUAL_PART_ID, dbo.A_ACTUAL_PARTS_CALL_DATA.PURCHASE_HIST_ID, 
                      dbo.A_ACTUAL_PARTS_CALL_DATA.ROOT_TASK, dbo.A_ACTUAL_PARTS_CALL_DATA.REASON, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.LOCATION,
                       dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.NICK_NAME, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_ID, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.QTY, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.CUR_OWNER, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.AP_STATUS, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_TYPE_NAME, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.CURRENT_OWNER_NAME, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.NAME AS AP_NAME
FROM         dbo.A_ACTUAL_PARTS_CALL_DATA INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON dbo.A_ACTUAL_PARTS_CALL_DATA.ACTUAL_PART_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID


