

CREATE VIEW dbo.A_V_FORECAST_ITEMS
AS
SELECT     dbo.A_FORECASTS_HISTORY.OBJECT_ID AS F_OBJ_ID, dbo.A_FORECASTS_HISTORY.NAME AS F_NAME, dbo.A_FORECAST_ITEMS.ID, 
                      dbo.A_FORECASTS_HISTORY.START_DATE, dbo.A_FORECASTS_HISTORY.STOP_DATE, dbo.A_FORECAST_ITEMS.ACCOUNT_ID, 
                      dbo.A_FORECAST_ITEMS.F_TYPE, dbo.A_FORECAST_ITEMS.QTY, dbo.A_FORECAST_ITEMS.F_AMT, dbo.A_FORECAST_ITEMS.PERCENT_OF_REV, 
                      dbo.A_FORECAST_ITEMS.PROGRESS, dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, C_ACCOUNT.NAME AS ACCOUNT_NAME, 
                      P_ACCOUNT.CUSTOMER_CO, P_ACCOUNT.SUPPLIER_CO, PROD_PRICE_LIST.UNIT_PRICE, P_ACCOUNT.PARENT_ACCOUNT, 
                      P_ACCOUNT.NAME AS PARENT_ACCT_NAME, SUPPLIER.NAME AS SUPPLIER_NAME, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS CUSTOMER_NAME, dbo.A_FORECAST_ITEMS.AVG_MONTHLY, 
                      dbo.A_FORECAST_ITEMS.CONFIDENCE, dbo.A_FORECAST_ITEMS.FORECAST_ID, dbo.A_FORECAST_ITEMS.NOTE, 
                      dbo.A_FORECAST_ITEMS.AMT_INVOICED, dbo.A_FORECAST_ITEMS.CUSTOMER_OWNER, dbo.A_FORECAST_ITEMS.SUPPLIER_OWNER, 
                      dbo.A_FORECAST_ITEMS.PRIORITY, dbo.A_FORECAST_ITEMS.STATUS, dbo.A_FORECAST_ITEMS.ACT_FIRST_PURCHASE_DATE, 
                      dbo.A_FORECAST_ITEMS.EST_FIRST_PURCHASE_DATE, dbo.A_FORECAST_ITEMS.ACT_QUAL_START_DATE, 
                      dbo.A_FORECAST_ITEMS.EST_QUAL_START_DATE, dbo.A_FORECAST_ITEMS.DATE_ADDED
FROM         dbo.A_FORECAST_ITEMS INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA C_ACCOUNT ON dbo.A_FORECAST_ITEMS.ACCOUNT_ID = C_ACCOUNT.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER ON C_ACCOUNT.SUPPLIER_CO = SUPPLIER.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON C_ACCOUNT.CUSTOMER_CO = dbo.A_V_COMPANIES_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA P_ACCOUNT ON C_ACCOUNT.PARENT_ACCOUNT = P_ACCOUNT.ID LEFT OUTER JOIN
                      dbo.A_V_PROD_PRICE_LIST_BY_APPROVED_ID PROD_PRICE_LIST ON C_ACCOUNT.CUSTOMER_CO = PROD_PRICE_LIST.CUSTOMER AND 
                      C_ACCOUNT.PRODUCT_ID = PROD_PRICE_LIST.PRODUCT LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON C_ACCOUNT.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_FORECASTS_HISTORY ON dbo.A_FORECAST_ITEMS.FORECAST_ID = dbo.A_FORECASTS_HISTORY.ID


