



CREATE VIEW dbo.A_V_DISCUSSION_GET_FILE_ATTACHMENT_INFO
AS
SELECT     dbo.A_DISCUSSION_RESPONSE.ID, dbo.A_DISCUSSION_ATTACHMENTS.DOC_ID AS VALUE, dbo.A_DOCUMENTS.NAME AS SHOW, 
                      dbo.A_DOCUMENTS.DESCRIPTION
FROM         dbo.A_DISCUSSION_RESPONSE INNER JOIN
                      dbo.A_DISCUSSION_ATTACHMENTS ON dbo.A_DISCUSSION_RESPONSE.ID = dbo.A_DISCUSSION_ATTACHMENTS.RESPONSE_ID INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_DISCUSSION_ATTACHMENTS.DOC_ID = dbo.A_DOCUMENTS.ID