


CREATE VIEW dbo.A_V_SERVICE_CALLS_OT_HOURS
AS
SELECT     SUM(HOURS) AS OT_HOURS, ID, WEEKLY_ID, D, MO, YR, HOUR_TYPE, HOURS
FROM         dbo.A_SERVICE_CALL_WORK_TIME
WHERE     (HOUR_TYPE = 'OVER')
GROUP BY ID, WEEKLY_ID, D, MO, YR, HOUR_TYPE, HOURS