

CREATE VIEW dbo.A_V_WF_GROUP_ROLE_LINK
AS
SELECT     l.WF_GROUP_ID AS GROUP_ID, l.ROLE_ID, dbo.A_V_ROLES_APPROVED_DATA.NAME AS ROLE_NAME
FROM         dbo.A_WF_GROUP_ROLE_LINK l INNER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA ON l.ROLE_ID = dbo.A_V_ROLES_APPROVED_DATA.ID


