



CREATE VIEW dbo.A_V_FORECASTS_APPROVED_DATA
AS
SELECT     dbo.A_FORECASTS.ID, dbo.A_FORECASTS.HISTORY_REF_ID, dbo.A_FORECASTS_HISTORY.OBJECT_ID, dbo.A_FORECASTS_HISTORY.NAME, 
                      dbo.A_FORECASTS_HISTORY.START_MONTH, dbo.A_FORECASTS_HISTORY.START_YEAR, dbo.A_FORECASTS_HISTORY.DRCM, 
                      dbo.A_FORECASTS_HISTORY.MODBY, dbo.A_FORECASTS_HISTORY.CO, dbo.A_FORECASTS_HISTORY.STOP_MONTH, 
                      dbo.A_FORECASTS_HISTORY.STOP_YEAR, dbo.A_FORECASTS_HISTORY.START_DATE, dbo.A_FORECASTS_HISTORY.STOP_DATE, 
                      dbo.A_FORECASTS_HISTORY.F_TYPE
FROM         dbo.A_FORECASTS INNER JOIN
                      dbo.A_FORECASTS_HISTORY ON dbo.A_FORECASTS.HISTORY_REF_ID = dbo.A_FORECASTS_HISTORY.ID




