


CREATE VIEW dbo.A_V_PROD_REQUEST_FORMS_WITH_ALL_DATA
AS
SELECT     PROD.NAME AS PRODUCT_NAME, PROD.ID AS PRODUCT_ID, REQ_FORM.ID, REQ_FORM.FILE_ID, REQ_FORM.FILE_KEYWORDS, 
                      REQ_FORM.CUST_PERSON_ID, dbo.A_DOCUMENTS.NAME AS FILE_NAME, A_V_COMPANIES_APPROVED_DATA_1.NAME AS CUSTOMER_NAME, 
                      REQ_FORM.CUSTOMER_CO, REQ_FORM.DATE_UPLOADED, RES_PROD_NAME.NAME AS RES_PROD_NAME, 
                      dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME AS CUST_PERSON_NAME, CUST_MGR_ROLE.NAME AS CUST_MGR_ROLE_NAME, 
                      REQ_FORM.PRODUCT_ID AS PROD_ID, REQ_FORM.RESULT_PRODUCT, REQ_FORM.DRCM, REQ_FORM.MODBY, REQ_FORM.PROGRESS, 
                      PROD.CUST_MGR_ROLE, REQ_FORM.UPLOADER, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS UPLOADER_NAME, PROD.SUPPLIER_ID, 
                      SUPPLIER.NAME AS SUPPLIER_NAME
FROM         dbo.A_V_ROLE_DATA_BY_APPROVED_ID CUST_MGR_ROLE INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA PROD ON CUST_MGR_ROLE.ID = PROD.CUST_MGR_ROLE LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER ON PROD.SUPPLIER_ID = SUPPLIER.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN RIGHT OUTER JOIN
                      dbo.A_PROD_REQ_FORMS REQ_FORM INNER JOIN
                      dbo.A_DOCUMENTS ON REQ_FORM.FILE_ID = dbo.A_DOCUMENTS.ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ON REQ_FORM.CUST_PERSON_ID = dbo.A_V_PEOPLE_APPROVED_DATA.ID ON 
                      dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID = REQ_FORM.UPLOADER LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      REQ_FORM.CUSTOMER_CO = A_V_COMPANIES_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA RES_PROD_NAME ON REQ_FORM.RESULT_PRODUCT = RES_PROD_NAME.ID ON 
                      PROD.ID = REQ_FORM.PRODUCT_ID



