



CREATE VIEW dbo.A_V_ACCOUNTS_WITH_RELATED_OBJECTS
AS
SELECT     dbo.A_ACCOUNTS_HISTORY.ID AS ACCT_ID, dbo.A_ACCOUNTS_RELATED_OBJECTS.OBJ_ID, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC
FROM         dbo.A_ACCOUNTS_HISTORY INNER JOIN
                      dbo.A_ACCOUNTS_RELATED_OBJECTS ON dbo.A_ACCOUNTS_HISTORY.ID = dbo.A_ACCOUNTS_RELATED_OBJECTS.ACCOUNT_ID INNER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_ACCOUNTS_RELATED_OBJECTS.OBJ_ID = dbo.A_V_APPROVED_OBJECTS.ID




