


CREATE VIEW dbo.A_V_MEETING_REPONDANT_DATA
AS
SELECT     dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME, dbo.A_MEETING_RESPONSES.MEETING_ID, dbo.A_MEETING_RESPONSES.RESPONSE
FROM         dbo.A_MEETING_RESPONSES INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_MEETING_RESPONSES.PERSON_ID = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID



