CREATE VIEW dbo.A_V_PROCEDURE_OBJECT_LINK_DATA
AS
SELECT     dbo.A_APPROVED_OBJECTS.OBJ_REF_ID, dbo.A_OBJECTS.OBJ_TABLE, dbo.A_OBJECTS.OBJ_ID, 
                      dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID, dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID, dbo.A_OBJECTS.OBJ_DESC, 
                      dbo.A_PROCEDURE_OBJECT_LINK.STEP_ID, dbo.A_PROCEDURE_OBJECT_LINK.QTY, dbo.A_PROCEDURE_OBJECT_LINK.QTY_TYPE, 
                      dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP, dbo.A_PROCEDURE_OBJECT_LINK.ID, dbo.A_PROCEDURE_OBJECT_LINK.LABOR_ROLE, 
                      dbo.A_PROCEDURES.ID AS APPROVED_PROC_ID, dbo.A_PROCEDURES_HISTORY.ID AS PROC_HIST_ID
FROM         dbo.A_APPROVED_OBJECTS INNER JOIN
                      dbo.A_PROCEDURE_OBJECT_LINK ON dbo.A_APPROVED_OBJECTS.ID = dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_APPROVED_OBJECTS.OBJ_REF_ID = dbo.A_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_PROCEDURES_HISTORY ON dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID = dbo.A_PROCEDURES_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_PROCEDURES ON dbo.A_PROCEDURES_HISTORY.ID = dbo.A_PROCEDURES.HISTORY_REF_ID
