


CREATE VIEW dbo.A_V_PARTS_WITH_RELATED_EXTERNAL_CO_INFO
AS
SELECT     dbo.A_OBJECTS.CREATING_CO AS EXTERNAL_CO, A_OBJECTS_1.CREATING_CO AS LOCAL_CO, A_OBJECTS_1.ROOT AS LOCAL_PART_ID, 
                      dbo.A_PARTS.ID AS EXTERNAL_PART_ID, dbo.A_PARTS_HISTORY.ID AS LOCAL_PH_ID, 
                      dbo.A_PARTS.PARTS_HISTORY_ID AS EXTERNAL_PH_ID
FROM         dbo.A_OBJECTS A_OBJECTS_1 INNER JOIN
                      dbo.A_PARTS_HISTORY ON A_OBJECTS_1.ID = dbo.A_PARTS_HISTORY.OBJECT_ID INNER JOIN
                      dbo.A_OBJECTS INNER JOIN
                      dbo.A_PARTS ON dbo.A_OBJECTS.ROOT = dbo.A_PARTS.ID INNER JOIN
                      dbo.A_PARTS_EXTERNAL_EQUALS ON dbo.A_PARTS.ID = dbo.A_PARTS_EXTERNAL_EQUALS.EQUAL_PART_ID ON 
                      dbo.A_PARTS_HISTORY.ID = dbo.A_PARTS_EXTERNAL_EQUALS.PART_ID



