


CREATE VIEW dbo.A_V_PROJECT_SEARCH
AS
SELECT     dbo.A_PROJECTS.ID, dbo.A_PROJECTS.NAME AS PROJECT_NAME, dbo.A_PROJECTS.DATE_CREATED, 
                      dbo.A_PROJECTS.ORIGINAL_PLANNED_STOP_DATE, dbo.A_PROJECTS.CURRENT_PLANNED_STOP_DATE, dbo.A_PROJECTS.ACTUAL_STOP_DATE, 
                      dbo.A_TASK_PRIORITY_LEVELS.NAME AS PRIORITY_NAME, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS LEADER_NAME, 
                      dbo.A_PROJECTS.SUMMARY
FROM         dbo.A_TASK_PRIORITY_LEVELS RIGHT OUTER JOIN
                      dbo.A_PROJECTS ON dbo.A_TASK_PRIORITY_LEVELS.ID = dbo.A_PROJECTS.PRIORITY_LEVEL LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON dbo.A_PROJECTS.LEADER = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID



