

CREATE VIEW dbo.A_V_PROCEDURE_STEP_APPLICABLE_OBJECTS
AS
SELECT     dbo.A_PROCEDURE_OBJECT_LINK.ID, dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID, dbo.A_PROCEDURE_OBJECT_LINK.STEP_ID, 
                      dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID, dbo.A_PROCEDURE_OBJECT_LINK.QTY, dbo.A_PROCEDURE_OBJECT_LINK.QTY_TYPE, 
                      dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC
FROM         dbo.A_PROCEDURE_OBJECT_LINK LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID = dbo.A_V_APPROVED_OBJECTS.ID
WHERE     (dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP = N'STEP_APPLICABLE_OBJECT')


