

CREATE VIEW dbo.A_V_PROD_PRICE_LIST_APPROVED_CHILDREN_WITH_PARENT
AS
SELECT     P.ID AS PARENT_ID, P.HISTORY_REF_ID, C.ID AS CHILD_ID, C.PRODUCT, C.UNIT_PRICE, C.PRODUCT_NAME, C.SUPPLIER_ID, L.APPROVED_OBJ_ID, 
                      L.RELATIONSHIP, L.UNIT_TYPE, dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.STD_UNIT_QTY, C.UNIT, 
                      L.QTY / dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.STD_UNIT_QTY AS QTY
FROM         dbo.A_V_PROD_PRICE_LIST_BY_APPROVED_ID P INNER JOIN
                      dbo.A_PROD_PRICE_LIST_SUB_PRICE_LISTS L ON P.HISTORY_REF_ID = L.PARENT INNER JOIN
                      dbo.A_V_PROD_PRICE_LIST_BY_APPROVED_ID C ON L.CHILD = C.ID INNER JOIN
                      dbo.A_Z_UNITS_BASE_UNIT_CONVERTER ON C.UNIT = dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.FROM_UNIT


