



CREATE VIEW dbo.A_V_LOCATION_WITH_NAME
AS
SELECT     dbo.A_LOCATIONS_HISTORY.NAME AS LOCATION_NAME, dbo.A_LOCATIONS.ID AS L_ID
FROM         dbo.A_LOCATIONS INNER JOIN
                      dbo.A_LOCATIONS_HISTORY ON dbo.A_LOCATIONS.HISTORY_REF_ID = dbo.A_LOCATIONS_HISTORY.ID




