

CREATE VIEW dbo.A_V_TASK_QUOTE_ACCEPT_INFORMATION
AS
SELECT     dbo.A_QUOTE_ORDER_LINK.QA_TASK_ID, dbo.A_QUOTE_ORDER_LINK.TASK_ID, dbo.A_QUOTE_ORDER_LINK.SUPPLIER, 
                      dbo.A_QUOTE_ORDER_LINK.CUSTOMER, dbo.A_QUOTE_ORDER_LINK.ORDER_ID, dbo.A_QUOTE_ORDER_LINK.QUOTE_ID AS QUOTE_HIST_ID, 
                      dbo.A_QUOTES_HISTORY.OBJECT_ID AS QUOTE_ID, dbo.A_QUOTES_HISTORY.PROGRESS AS QUOTE_PROGRESS, 
                      dbo.A_QUOTES_HISTORY.DESCRIPTION AS QUOTE_DESCRIPTION, dbo.A_TASKS.STATUS, dbo.A_TASKS.REQUESTEE_ID, 
                      dbo.A_TASKS.GROUP_REQUESTEE_ID, dbo.A_QUOTE_ORDER_LINK.ID
FROM         dbo.A_QUOTE_ORDER_LINK INNER JOIN
                      dbo.A_TASKS ON dbo.A_QUOTE_ORDER_LINK.QA_TASK_ID = dbo.A_TASKS.ID INNER JOIN
                      dbo.A_QUOTES_HISTORY ON dbo.A_QUOTE_ORDER_LINK.QUOTE_ID = dbo.A_QUOTES_HISTORY.ID


