


CREATE VIEW dbo.A_V_DISCUSSION_WITH_INITIAL_DATA
AS
SELECT     p.FULL_NAME AS INITIATOR_NAME, d.ID, d.SUBJECT, d.INITIATOR AS INITIATOR_ID, d.DATE_CREATED, d.STATUS, r.RESPONSE AS STATEMENT, 
                      r.COLOR, r.PARENT_ID, r.ID AS RESPONSE_ID, d.LAST_RESPONSE
FROM         dbo.A_APPROVED_PEOPLE p RIGHT OUTER JOIN
                      dbo.A_DISCUSSIONS d ON p.ID = d.INITIATOR LEFT OUTER JOIN
                      dbo.A_DISCUSSION_RESPONSE r ON d.ID = r.DISCUSSION_ID
WHERE     (r.PARENT_ID IS NULL)