CREATE VIEW dbo.A_V_COMPANIES_APPROVED_DATA_QUICK
AS
SELECT     dbo.A_COMPANIES.ID, dbo.A_COMPANIES.HISTORY_REF_ID, dbo.A_COMPANIES_HISTORY.OBJECT_ID, dbo.A_COMPANIES_HISTORY.NAME, 
                      dbo.A_COMPANIES_HISTORY.CO_TYPE, dbo.A_COMPANIES_HISTORY.PARENT, dbo.A_COMPANIES_HISTORY.PHONE, dbo.A_COMPANIES_HISTORY.LOCATION, 
                      dbo.A_COMPANIES_HISTORY.LOCATION_NAME, dbo.A_COMPANIES_HISTORY.PARENT_NAME, dbo.A_COMPANIES_HISTORY.DRCM, 
                      dbo.A_COMPANIES_HISTORY.MODBY, dbo.A_COMPANIES_HISTORY.ROOT_CO_ID
FROM         dbo.A_COMPANIES INNER JOIN
                      dbo.A_COMPANIES_HISTORY ON dbo.A_COMPANIES.HISTORY_REF_ID = dbo.A_COMPANIES_HISTORY.ID
WHERE     (dbo.A_COMPANIES.STATUS = 'APPROVED')

