

CREATE VIEW dbo.A_V_COMPANIES_APPROVED_DATA
AS
SELECT     c.ID, c.HISTORY_REF_ID, ch.NAME, ch.CO_TYPE, ch.PARENT, ch.PHONE, ch.LOCATION, ch.LOCATION_NAME, ch.DRCM, ch.MODBY, ch.OBJECT_ID, 
                      dbo.A_FN_COMPANY_APPROVED_GET_TOP_COMPANY(c.ID) AS ROOT_CO, c.STATUS, dbo.A_FN_COMPANY_GET_TOP_COMPANY(ch.ID) 
                      AS TOP_COMPANY, A_COMPANIES_HISTORY_1.NAME AS PARENT_NAME
FROM         dbo.A_COMPANIES_HISTORY A_COMPANIES_HISTORY_1 INNER JOIN
                      dbo.A_COMPANIES A_COMPANIES_1 ON A_COMPANIES_HISTORY_1.ID = A_COMPANIES_1.HISTORY_REF_ID RIGHT OUTER JOIN
                      dbo.A_COMPANIES c INNER JOIN
                      dbo.A_COMPANIES_HISTORY ch ON c.HISTORY_REF_ID = ch.ID ON A_COMPANIES_1.ID = ch.PARENT
WHERE     (c.STATUS = 'APPROVED')


