CREATE VIEW dbo.A_V_LINKED_LOGINS_PEOPLE_DATA
AS
SELECT     dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME AS ROOT_NAME, dbo.A_V_PEOPLE_APPROVED_DATA.ROOT_COMPANY AS ROOT_CO, 
                      A_V_PEOPLE_APPROVED_DATA_1.FULL_NAME AS LINKED_NAME, dbo.A_PEOPLE_LINKED_LOGINS.ROOT_ID, 
                      dbo.A_PEOPLE_LINKED_LOGINS.LINKED_ID, A_V_PEOPLE_APPROVED_DATA_1.ROOT_COMPANY AS LINKED_CO
FROM         dbo.A_PEOPLE_LINKED_LOGINS INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ON dbo.A_PEOPLE_LINKED_LOGINS.ROOT_ID = dbo.A_V_PEOPLE_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA A_V_PEOPLE_APPROVED_DATA_1 ON 
                      dbo.A_PEOPLE_LINKED_LOGINS.LINKED_ID = A_V_PEOPLE_APPROVED_DATA_1.ID
