


CREATE VIEW dbo.A_V_DISCUSSION_TASKS
AS
SELECT     dbo.A_TASKS.DESCRIPTION, dbo.A_TASK_DISCUSSION_LINK.DISCUSSION_ID, dbo.A_TASKS.STATUS, dbo.A_TASKS.REQUESTOR, 
                      dbo.A_TASKS.COMPLETED_BY, dbo.A_TASKS.LATEST_REQUESTEE_NAME
FROM         dbo.A_TASKS INNER JOIN
                      dbo.A_TASK_DISCUSSION_LINK ON dbo.A_TASKS.ID = dbo.A_TASK_DISCUSSION_LINK.TASK_ID



