CREATE VIEW dbo.A_V_PEOPLE_PAGE_HITS_RAW_DATA
AS
SELECT     TOP 100 PERCENT p.USER_ID, ph.FULL_NAME, p.DRCM, GETDATE() AS NOW_DATE, DATEDIFF(n, p.DRCM, GETDATE()) AS LAPSED, p.PAGE, 
                      MONTH(p.DRCM) AS MO, YEAR(p.DRCM) AS YR, ph.ROOT_COMPANY, co.NAME AS CO_NAME, dep.NAME AS DEPT_NAME, DAY(p.DRCM) AS DA, p.ID, 
                      p.QUERYSTRING
FROM         dbo.A_PEOPLE_PAGE_TRACKING p INNER JOIN
                      dbo.A_PEOPLE p_1 ON p.USER_ID = p_1.ID INNER JOIN
                      dbo.A_PEOPLE_HISTORY ph ON p_1.HISTORY_REF_ID = ph.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA co ON ph.ROOT_COMPANY = co.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA dep ON ph.COMPANY = dep.ID
ORDER BY p.DRCM DESC
