CREATE VIEW dbo.A_V_EMAILS_FOR_APPROVED_PEOPLE
AS
SELECT     dbo.A_PEOPLE.ID, dbo.A_EMAILS.ADDY, dbo.A_EMAILS.TYPE AS EMAIL_TYPE, dbo.A_EMAILS.EMAIL_TYPE AS EMAIL_BODY_TYPE
FROM         dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_EMAILS ON dbo.A_PEOPLE_HISTORY.OBJECT_ID = dbo.A_EMAILS.OBJECT_ID
