

CREATE VIEW dbo.A_V_PROD_PRICE_LIST_EXTRA_COST_DATA
AS
SELECT     dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCT, dbo.A_PROD_PRICE_LIST_HISTORY.CUSTOMER, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCT_NAME, dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.PROD_PRICE_LIST, 
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.DESCRIPTION, dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.PRICE_LIST_TYPE, 
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.ID AS EXTRA_COST_ID, dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.DRCM, 
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.MODBY, dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.UNIT, 
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.UNIT_PRICE
FROM         dbo.A_PROD_PRICE_LIST_HISTORY INNER JOIN
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS ON dbo.A_PROD_PRICE_LIST_HISTORY.ID = dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.PROD_PRICE_LIST


