
CREATE  VIEW dbo.A_V_TASK_SEARCH
AS
SELECT     TASK.DESCRIPTION, TASK.STATUS, TASK.REQUESTOR, TASK.CHILD_ORDER, TASK.CREATED_BY, TASK.CREATE_DATE, dbo.leadingSpaces(TASK.ID, 
                      50) AS SORT_ID, TASK.SYSTEM_TASK, TASK.PROCEDURE_ID, REQUESTOR.P_NAME AS REQUESTOR_NAME, TASK.REQUESTEE_ID, 
                      TASK.GROUP_REQUESTEE_ID, TASK.ORIG_PLANNED_START_DATE, TASK.ORIG_PLANNED_STOP_DATE, TASK.CUR_PLANNED_START_DATE, 
                      TASK.CUR_PLANNED_STOP_DATE, TASK.ACTUAL_START_DATE, TASK.ACTUAL_STOP_DATE, TASK.CUR_PLANNED_COUNTER_START, 
                      TASK.LATEST_REQUESTEE_NAME, TASK.HAS_DISCUSSION, TASK.HAS_SURVEY, TASK.HAS_CHILD, TASK.HAS_REF_PROC, TASK.HAS_FILE, 
                      TASK.ORIG_REQUESTOR_ID, TASK.HAS_REF_OBJ, TASK.HAS_MONITOR, ORIG_REQUESTOR.FULL_NAME AS ORIG_REQUESTOR_NAME, 
                      TASK.COLOR_CODE,  sur.SURVEY_ID, TASK.LAST_REQUEST_DATE,dbo.getTaskParentList(TASK.ID) 
                      AS PARENT_LIST, TASK.PARENT_ID, dbo.isParentTask(TASK.ID) AS isParent, TASK.PRIORITY, 
                      dbo.A_TASK_PRIORITY_LEVELS.NAME AS PRIORITY_NAME,
                      dbo.A_TASK_COMPANIES_TO_VIEW_LINK.CO_ID AS ALLOWED_CO_ID, 
                      dbo.A_V_CO_BY_NTLOGIN.CO_NAME AS COMPANY_NAME, proj.PROJECT_ID, TASK.ID, TASK.CHILD_STATUS, TASK.PROCEDURE_STEP_ID, 
                      dbo.A_TASK_EMAIL_PEOPLE_LINK.PERSON_ID AS SPECIFIED_PERSON_ID, dbo.A_TASK_COMMENT.COMMENT AS LAST_COMMENT, 
                      dbo.A_TASK_COMMENT.DRCM AS LAST_COMMENT_DRCM, A_V_PEOPLE_BY_NTLOGIN_1.P_NAME AS LAST_COMMENT_WRITER, TASK.IS_QUOTE, 
                      TASK.IS_QUOTE_ACCEPT, TASK.IS_FILL, dbo.A_V_CO_BY_NTLOGIN.CO_ID, dbo.A_TASK_ORDER_INFORMATION.PURCHASE_HIST_ID, 
                      dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID, dbo.A_TASK_ORDER_INFORMATION.FILL_ID, 
                      dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ROLE, TASK.RECURSION_NUMBER, ASSIGNEE.FULL_NAME AS ASSIGNEE_NAME, 
                      ASSIGNEE.ID AS ASSIGNEE_ID, ASSIGNEE.SYSTEM_STATUS AS ASSIGNEE_STATUS
FROM         dbo.A_V_PEOPLE_DATA_QUICK ASSIGNEE INNER JOIN
                      dbo.A_TASK_PROCEDURE_ASSIGNEE ON ASSIGNEE.ID = dbo.A_TASK_PROCEDURE_ASSIGNEE.ASSIGNEE_ID RIGHT OUTER JOIN
                      dbo.A_TASKS TASK ON dbo.A_TASK_PROCEDURE_ASSIGNEE.TASK_ID = TASK.ID LEFT OUTER JOIN
                      dbo.A_TASK_ORDER_INFORMATION ON TASK.ID = dbo.A_TASK_ORDER_INFORMATION.TASK_ID LEFT OUTER JOIN
                      dbo.A_TASK_LAST_COMMENT INNER JOIN
                      dbo.A_TASK_COMMENT ON dbo.A_TASK_LAST_COMMENT.COMMENT_ID = dbo.A_TASK_COMMENT.ID INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN A_V_PEOPLE_BY_NTLOGIN_1 ON dbo.A_TASK_COMMENT.MODBY = A_V_PEOPLE_BY_NTLOGIN_1.P_ID ON 
                      TASK.ID = dbo.A_TASK_LAST_COMMENT.TASK_ID LEFT OUTER JOIN
                      dbo.A_TASK_EMAIL_PEOPLE_LINK ON TASK.ID = dbo.A_TASK_EMAIL_PEOPLE_LINK.TASK_ID LEFT OUTER JOIN
                      dbo.A_TASK_PROJECT_LINK proj ON TASK.ID = proj.TASK_ID LEFT OUTER JOIN
                      dbo.A_V_CO_BY_NTLOGIN ON TASK.REQUESTEE_ID = dbo.A_V_CO_BY_NTLOGIN.ID LEFT OUTER JOIN
                      dbo.A_TASK_COMPANIES_TO_VIEW_LINK ON TASK.ID = dbo.A_TASK_COMPANIES_TO_VIEW_LINK.TASK_ID 
					  
					  LEFT OUTER JOIN
                      dbo.A_TASK_PRIORITY_LEVELS ON TASK.PRIORITY = dbo.A_TASK_PRIORITY_LEVELS.ID
					  
					  LEFT OUTER JOIN
                      dbo.A_TASK_SURVEY_LINK sur ON TASK.ID = sur.TASK_ID LEFT OUTER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE ORIG_REQUESTOR ON TASK.ORIG_REQUESTOR_ID = ORIG_REQUESTOR.OBJ_ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN REQUESTOR ON TASK.REQUESTOR = REQUESTOR.P_ID

