


CREATE VIEW dbo.A_V_NEEDS_APPROVED_DATA
AS
SELECT     dbo.A_NEEDS.ID, dbo.A_NEEDS.HISTORY_REF_ID, dbo.A_NEEDS_HISTORY.OBJECT_ID, dbo.A_NEEDS_HISTORY.DESCRIPTION, 
                      dbo.A_NEEDS_HISTORY.CUSTOMER_CO, dbo.A_NEEDS_HISTORY.TIMEFRAME, dbo.A_NEEDS_HISTORY.IMPORTANCE, 
                      dbo.A_NEEDS_HISTORY.NEED_SIZE, dbo.A_NEEDS_HISTORY.ADVERTISING_START_DATE, dbo.A_NEEDS_HISTORY.ADVERTISING_STOP_DATE, 
                      dbo.A_NEEDS_HISTORY.ADVERSTISE_PUBLICLY, dbo.A_NEEDS_HISTORY.CONTACT_NAME, dbo.A_NEEDS_HISTORY.CONTACT_EMAIL, 
                      dbo.A_NEEDS_HISTORY.CONTACT_PHONE, dbo.A_NEEDS_HISTORY.DRCM, dbo.A_NEEDS_HISTORY.MODBY
FROM         dbo.A_NEEDS INNER JOIN
                      dbo.A_NEEDS_HISTORY ON dbo.A_NEEDS.HISTORY_REF_ID = dbo.A_NEEDS_HISTORY.ID



