


CREATE VIEW dbo.A_V_QUOTE_ORDER_LINK_WITH_RESPONSIBLE_ROLE
AS
SELECT     L.QUOTE_ID, L.ORDER_ID, L.STATUS, L.CUSTOMER AS CUST_ID, L.SUPPLIER AS SUPPLIER_ID, J.ROLE_ID, R.NAME AS ROLE_NAME, 
                      C.NAME AS CUST_NAME, S.NAME AS SUPPLIER_NAME, L.ID AS QOL_ID, dbo.A_ORDERS.HISTORY_REF_ID AS ORDER_HIST_ID
FROM         dbo.A_QUOTE_ORDER_LINK L INNER JOIN
                      dbo.A_ADMIN_ROLE_JOBS J ON L.SUPPLIER = J.CO_ID INNER JOIN
                      dbo.A_V_ROLE_DATA_BY_APPROVED_ID R ON J.ROLE_ID = R.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA C ON L.CUSTOMER = C.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA S ON L.SUPPLIER = S.ID INNER JOIN
                      dbo.A_ORDERS ON L.ORDER_ID = dbo.A_ORDERS.ID



