


CREATE VIEW dbo.A_V_SERVICE_CALL_TOTAL_OT_HOURS
AS
SELECT     dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID, SUM(dbo.A_SERVICE_CALL_WORK_TIME.HOURS) AS OT_HOURS, 
                      dbo.A_SERVICE_CALL_WORK_TIME.HOUR_TYPE
FROM         dbo.A_SERVICE_CALLS_WEEKLY_REPORTS INNER JOIN
                      dbo.A_SERVICE_CALL_WORK_TIME ON dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID = dbo.A_SERVICE_CALL_WORK_TIME.WEEKLY_ID
GROUP BY dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID, dbo.A_SERVICE_CALL_WORK_TIME.HOUR_TYPE
HAVING      (dbo.A_SERVICE_CALL_WORK_TIME.HOUR_TYPE = 'OVER')