


CREATE VIEW dbo.A_V_PEOPLE_WITH_COMPANIES
AS
SELECT     p.NAME, c.NAME AS COMPANY_NAME, c.ID AS CO, p.ID AS PERSON
FROM         dbo.A_APPROVED_COMPANIES c INNER JOIN
                      dbo.A_APPROVED_PEOPLE p ON c.ID = p.ROOT_COMPANY



