
CREATE  VIEW dbo.A_V_THEORY_PARAGRAPH_WITH_REF_THEORY
AS
SELECT     dbo.A_THEORY_PARAGRAPHS.ID AS PARAGRAPH_ID, dbo.A_THEORY_PARAGRAPH_THEORY_LINK.THEORY_LINK, 
                      dbo.A_OBJECTS.OBJ_DESC AS THEORY_NAME, dbo.A_OBJECTS.ID AS THEORY_OBJ_ID, 
                      dbo.A_THEORY_HISTORY.NAME AS APPROVED_NAME
FROM         dbo.A_THEORY INNER JOIN
                      dbo.A_THEORY_HISTORY ON dbo.A_THEORY.HISTORY_REF_ID = dbo.A_THEORY_HISTORY.ID RIGHT OUTER JOIN
                      dbo.A_THEORY_PARAGRAPHS INNER JOIN
                      dbo.A_THEORY_PARAGRAPH_THEORY_LINK ON 
                      dbo.A_THEORY_PARAGRAPHS.ID = dbo.A_THEORY_PARAGRAPH_THEORY_LINK.THEORY_PARAGRAPH INNER JOIN
                      dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT ON 
                      dbo.A_THEORY_PARAGRAPH_THEORY_LINK.THEORY_LINK = dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ROOT INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ID = dbo.A_OBJECTS.ID ON 
                      dbo.A_THEORY.ID = dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ROOT

