



CREATE VIEW dbo.A_V_POP_FILL_DISCUSSION_INVITED_PEOPLE
AS
SELECT     A_APPROVED_PEOPLE_1.FULL_NAME AS NAME, A_DISCUSSION_INV_PEOPLE_1.DISCUSSION_ID AS D_ID, 
                      A_DISCUSSION_INV_PEOPLE_1.PEOPLE_ID
FROM         dbo.A_DISCUSSION_INV_PEOPLE A_DISCUSSION_INV_PEOPLE_1 INNER JOIN
                      dbo.A_APPROVED_PEOPLE A_APPROVED_PEOPLE_1 ON A_DISCUSSION_INV_PEOPLE_1.PEOPLE_ID = A_APPROVED_PEOPLE_1.ID