




CREATE VIEW dbo.A_V_APPROVED_PEOPLE_SIMPLE_SEARCH
AS
SELECT     dbo.A_PEOPLE.ID, dbo.A_PEOPLE_SEARCH_TABLE.NAME, dbo.A_PEOPLE_SEARCH_TABLE.LAST_NAME, 
                      dbo.A_PEOPLE_SEARCH_TABLE.MIDDLE_NAME, dbo.A_PEOPLE_SEARCH_TABLE.FULL_NAME, dbo.A_PEOPLE_SEARCH_TABLE.TIME_ZONE, 
                      dbo.A_PEOPLE_SEARCH_TABLE.SYSTEM_STATUS, dbo.A_PEOPLE_SEARCH_TABLE.BOSS_ID, dbo.A_PEOPLE_SEARCH_TABLE.BOSS_NAME, 
                      dbo.A_PEOPLE_SEARCH_TABLE.HIRE_DATE, dbo.A_PEOPLE_SEARCH_TABLE.COMPANY_ID, dbo.A_PEOPLE_SEARCH_TABLE.COMPANY_NAME, 
                      dbo.A_PEOPLE_SEARCH_TABLE.POSITION_ID, dbo.A_PEOPLE_SEARCH_TABLE.POSITION_NAME, dbo.A_PEOPLE_SEARCH_TABLE.LOCATION_ID, 
                      dbo.A_PEOPLE_SEARCH_TABLE.LOCATION_NAME, dbo.A_PEOPLE_SEARCH_TABLE.PRIMARY_PHONE_ID, 
                      dbo.A_PEOPLE_SEARCH_TABLE.PRIMARY_PHONE_NUMBER, dbo.A_PEOPLE_SEARCH_TABLE.SECONDARY_PHONE_ID, 
                      dbo.A_PEOPLE_SEARCH_TABLE.SECONDARY_PHONE_NUMBER, dbo.A_PEOPLE_SEARCH_TABLE.WORK_EMAIL_ID, 
                      dbo.A_PEOPLE_SEARCH_TABLE.WORK_EMAIL_ADDRESS
FROM         dbo.A_PEOPLE_SEARCH_TABLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE_SEARCH_TABLE.ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_PEOPLE ON dbo.A_PEOPLE_HISTORY.ID = dbo.A_PEOPLE.HISTORY_REF_ID





