CREATE VIEW dbo.A_V_PROD_SUPPLIER_APP_OBJ
AS
SELECT     dbo.A_V_PRODUCTS_APPROVED_DATA.APP_OBJECT, dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.CUST_ID, 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID
FROM         dbo.A_V_PRODUCTS_APPROVED_DATA INNER JOIN
                      dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.ID = dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.PRODUCT INNER JOIN
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS ON 
                      dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.HISTORY_REF_ID = dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.PP_LIST_ID
