

CREATE VIEW dbo.A_V_PRODUCTS_WITH_PRICE_AND_PROC_DATA
AS
SELECT     PROD.ID, PROD.NAME, PROD.SUPPLIER_ID, PROD.PROCEDURE_ID, PP_LIST.UNIT_PRICE, PROD.COMMENTS, [PROC].SYSTEM_ID, 
                      [PROC].NAME AS PROC_NAME, PROD.APP_OBJECT AS PART_ID, PP_LIST.ID AS PP_LIST_ID, 
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.CUST_ID, PP_LIST.UNIT, 
                      dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.STD_UNIT_QTY AS STD_UNIT_QTY
FROM         dbo.A_V_PRODUCTS_APPROVED_DATA PROD INNER JOIN
                      dbo.A_V_PROD_PRICE_LIST_BY_APPROVED_ID PP_LIST ON PROD.ID = PP_LIST.PRODUCT INNER JOIN
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS ON 
                      PP_LIST.HISTORY_REF_ID = dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.PP_LIST_ID INNER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA [PROC] ON PROD.PROCEDURE_ID = [PROC].ID INNER JOIN
                      dbo.A_Z_UNITS_BASE_UNIT_CONVERTER ON PP_LIST.UNIT = dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.FROM_UNIT


