



CREATE VIEW dbo.A_V_SURVEY_GET_FILE_ATTACHMENTS
AS
SELECT     dbo.A_SURVEYS.ID, dbo.A_DOCUMENTS.NAME AS SHOW, dbo.A_SURVEY_ATTACHMENTS.DOC_ID AS VALUE, 
                      dbo.A_SURVEY_ATTACHMENTS.RESPONSE_ID, dbo.A_SURVEY_ATTACHMENTS.SURVEY_ID
FROM         dbo.A_SURVEYS INNER JOIN
                      dbo.A_SURVEY_ATTACHMENTS ON dbo.A_SURVEYS.ID = dbo.A_SURVEY_ATTACHMENTS.SURVEY_ID INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_SURVEY_ATTACHMENTS.DOC_ID = dbo.A_DOCUMENTS.DOC_ID
WHERE     (dbo.A_SURVEY_ATTACHMENTS.RESPONSE_ID IS NULL)




