CREATE VIEW [dbo].[A_V_PRODUCT_SEARCH_DATA]
AS
SELECT     ph.ID, ph.OBJECT_ID, ph.PARENT_ID, ph.NAME, ph.SUPPLIER_ID, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS SUPPLIER_NAME, 
                      ph.COMMENTS, ph.PROCEDURE_ID, dbo.A_V_PROCEDURES_APPROVED_DATA.VERB, dbo.A_V_PROCEDURES_APPROVED_DATA.VERB_NAME, 
                      ph.APP_OBJECT, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC AS APP_OBJ_NAME, ph.SHIP_OR_LABOR, ph.CUSTOMIZABLE, ph.REQ_FORM, 
                      ph.MGR_TEAM, dbo.A_APPROVED_ROLES.NAME AS MGR_TEAM_NAME, ph.SALES_TAX, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROCEDURE_NAME, dbo.A_OBJECTS.ID AS OBJ_ID, dbo.A_OBJECTS.LOCKED_BY, 
                      dbo.A_OBJECTS.UNLOCKED_BY, dbo.A_OBJECTS.CREATED_BY, dbo.A_OBJECTS.CREATE_DATE, dbo.A_OBJECTS.ROOT, dbo.A_OBJECTS.REV_INFO,
                       dbo.A_OBJECTS.CREATING_CO, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.REV, dbo.A_OBJECTS.WFS_ID, dbo.A_OBJECTS.LOCKED_BY_NAME, 
                      dbo.A_OBJECTS.CREATING_CO_NAME, dbo.A_OBJECTS.APPROVAL_ACTIVITY, dbo.A_FN_PRODUCT_WHERE_USED_CHECK(ph.ID) AS HAS_USAGE, 
                      ph.CUST_MGR_ROLE,
					  ph.CustomerRequirementId,
					  ph.MaterialCost,
					  ph.TotalSalePrice,
					  ph.IsProduct,
					  ph.Division,
					  ph.LocationId,
					  PQP.CUST_ID AS CustomerId,
					  ph.CycleTime
FROM         dbo.A_OBJECTS INNER JOIN
                      dbo.A_PRODUCTS_HISTORY ph ON dbo.A_OBJECTS.ID = ph.OBJECT_ID LEFT OUTER JOIN
                      dbo.A_APPROVED_ROLES ON ph.MGR_TEAM = dbo.A_APPROVED_ROLES.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON ph.APP_OBJECT = dbo.A_V_APPROVED_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON ph.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON ph.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID LEFT OUTER JOIN 
					  dbo.A_PRODUCTS_QUICK_PRICE PQP ON ph.ID = PQP.PROD_HIST_ID



