



CREATE VIEW dbo.A_V_MEETING_GET_TKEEP_NAME
AS
SELECT     dbo.A_APPROVED_PEOPLE.FULL_NAME AS TKEEP_NAME, dbo.A_MEETINGS.TIME_KEEP AS T_ID, dbo.A_MEETINGS.ID
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_MEETINGS ON dbo.A_APPROVED_PEOPLE.ID = dbo.A_MEETINGS.TIME_KEEP