CREATE VIEW dbo.A_V_PROCEDURE_STEP_LABOR
AS
SELECT     dbo.A_V_ROLE_DATA_BY_APPROVED_ID.NAME AS ROLE_NAME, dbo.A_PROCEDURE_STEPS.PROCEDURE_ID, 
                      dbo.A_PROCEDURE_STEPS.ID AS STEP_ID, dbo.A_V_ROLE_DATA_BY_APPROVED_ID.ID AS ROLE_ID, 
                      dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP, dbo.A_PROCEDURE_OBJECT_LINK.LABOR_ROLE, dbo.A_PROCEDURE_OBJECT_LINK.QTY, 
                      dbo.A_PROCEDURE_OBJECT_LINK.QTY_TYPE, dbo.A_V_ROLE_DATA_BY_APPROVED_ID.ID AS OBJ_REF_ID, 
                      dbo.A_V_ROLE_DATA_BY_APPROVED_ID.HISTORY_REF_ID AS OBJ_ID, dbo.A_V_ROLE_DATA_BY_APPROVED_ID.NAME AS OBJ_DESC, 
                      dbo.A_PROCEDURE_OBJECT_LINK.ID
FROM         dbo.A_PROCEDURE_STEPS INNER JOIN
                      dbo.A_PROCEDURE_OBJECT_LINK ON dbo.A_PROCEDURE_STEPS.ID = dbo.A_PROCEDURE_OBJECT_LINK.STEP_ID INNER JOIN
                      dbo.A_V_ROLE_DATA_BY_APPROVED_ID ON 
                      dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID = dbo.A_V_ROLE_DATA_BY_APPROVED_ID.ID
