CREATE VIEW dbo.A_V_ORDER_MAIN_DATA_BY_APPROVED_ID
AS
SELECT     o.ID AS ORDER_ID, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS CUSTOMER_PERSON_NAME, c.NAME AS CUSTOMER_CO_NAME, h.ID, 
                      h.OBJECT_ID, h.CUSTOMER_PERSON, h.CUSTOMER_CO, h.DESCRIPTION, h.BUDGETARY_ONLY, h.EXPIRATION_DATE, h.DRCM, h.MODBY, 
                      h.PROGRESS, h.RFQ_ID, h.SUPPLIER_ID, h.CREATION_DATE, h.PERSON_SUPPLIER, h.TYPE, h.PRICE
FROM         dbo.A_ORDERS o INNER JOIN
                      dbo.A_ORDERS_HISTORY h ON o.HISTORY_REF_ID = h.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA c ON h.CUSTOMER_CO = c.ID INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON h.CUSTOMER_PERSON = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID
