

CREATE VIEW dbo.A_V_PROD_PRICE_LIST_CHILDREN_PROD_FILLS
AS
SELECT     OBJ.OBJ_DESC, L.ID, L.PARENT, L.CHILD, CHILD.PRODUCT, CHILD.UNIT_PRICE, CHILD.PRODUCT_NAME, CHILD.UNIT AS PROD_UNIT, 
                      L.APPROVED_OBJ_ID, L.QTY, L.RELATIONSHIP, CHILD.UNIT_PRICE * (L.QTY / b.STD_UNIT_QTY) AS PRICE, b.STD_UNIT_QTY
FROM         dbo.A_Z_UNITS_BASE_UNIT_CONVERTER b RIGHT OUTER JOIN
                      dbo.A_V_PROD_PRICE_LIST_BY_APPROVED_ID CHILD ON b.FROM_UNIT = CHILD.UNIT RIGHT OUTER JOIN
                      dbo.A_OBJECTS OBJ INNER JOIN
                      dbo.A_PROD_PRICE_LIST_SUB_PRICE_LISTS L ON OBJ.ID = L.APPROVED_OBJ_ID ON CHILD.ID = L.CHILD


