CREATE VIEW dbo.A_V_PARTS_APPROVED_DATA_QUICK
AS
SELECT     dbo.A_PARTS.ID, dbo.A_PARTS.PARTS_HISTORY_ID AS HISTORY_REF_ID, dbo.A_PARTS_HISTORY.OBJECT_ID, dbo.A_PARTS_HISTORY.UNIT, 
                      dbo.A_PARTS_HISTORY.NAME, dbo.A_PARTS_HISTORY.PART_TYPE, dbo.A_PARTS_HISTORY.SPARE, dbo.A_PARTS_HISTORY.CONSUMABLE, 
                      dbo.A_PARTS_HISTORY.TRACK_FROM_START, dbo.A_PARTS_HISTORY.COMPANY, dbo.A_PARTS_HISTORY.COMPANY_NAME, 
                      dbo.A_PARTS_HISTORY.PART_TYPE_NAME, dbo.A_PARTS_HISTORY.UNIT_SHIPPING_WEIGHT, dbo.A_PARTS_HISTORY.COMPANY_PART_NUMBER, 
                      dbo.A_PARTS_HISTORY.SUPPLIER_SEE_INSTALL_BASE, dbo.A_PARTS_HISTORY.SUPPLIER_SEE_AVAILABILITY, 
                      dbo.A_PARTS_HISTORY.CUSTOMER_SEE_AVAILABILITY, dbo.A_PARTS_HISTORY.WEIGHT_TYPE, dbo.A_PARTS_HISTORY.CREATE_PROD, 
                      dbo.A_PARTS_HISTORY.SUPPLIER_CO, dbo.A_PARTS_HISTORY.PRODUCT_TYPE, dbo.A_PARTS_HISTORY.PROC_VERB, 
                      dbo.A_PARTS_HISTORY.PRICE
FROM         dbo.A_PARTS INNER JOIN
                      dbo.A_PARTS_HISTORY ON dbo.A_PARTS.PARTS_HISTORY_ID = dbo.A_PARTS_HISTORY.ID
