

CREATE VIEW dbo.A_V_PROD_PRICE_LIST_EXTRA_COSTS_PRICE_TABLE_STANDARDIZED
AS
SELECT     TAB.ID, TAB.MIN_NUM * BASE.STD_UNIT_QTY AS MIN_NUM, TAB.MAX_NUM * BASE.STD_UNIT_QTY AS MAX_NUM, TAB.PER_UNIT_COST, 
                      TAB.FLAT_RATE, TAB.PER_UNIT_APPLIES_OVER * BASE.STD_UNIT_QTY AS PER_UNIT_APPLIES_OVER, PPLEC.UNIT AS ORIG_UNIT, 
                      BASE.STD_UNIT, TAB.PPLEC_ID, TAB.MIN_NUM AS Expr1, TAB.MAX_NUM AS Expr2, BASE.STD_UNIT_QTY, 
                      TAB.PER_UNIT_APPLIES_OVER AS Expr3
FROM         dbo.A_PROD_PRICE_LIST_EXTRA_COSTS_PRICE_TABLE TAB INNER JOIN
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS PPLEC ON TAB.PPLEC_ID = PPLEC.ID INNER JOIN
                      dbo.A_Z_UNITS_BASE_UNIT_CONVERTER BASE ON PPLEC.UNIT = BASE.FROM_UNIT


