


CREATE VIEW dbo.A_V_POP_FILL_MEETING_INVITED_ROLES
AS
SELECT     dbo.A_MEETING_INV_ROLE.MEETING_ID AS M_ID, dbo.A_APPROVED_ROLES.ID AS R_ID, dbo.A_APPROVED_ROLES.NAME AS ROLE_NAME, 
                      dbo.A_MEETING_INV_ROLE.OPTIONAL
FROM         dbo.A_APPROVED_ROLES INNER JOIN
                      dbo.A_MEETING_INV_ROLE ON dbo.A_APPROVED_ROLES.ID = dbo.A_MEETING_INV_ROLE.ROLE_ID



