CREATE VIEW dbo.A_V_SERVICE_CALLS_WEEKLY_DATA
AS
SELECT     SERVICE_CALL.ACTUAL_START_DATE, SERVICE_CALL.ID, SERVICE_CALL.WORKER_ID, WORKER.NAME AS WORKER_FIRST_NAME, 
                      SERVICE_CALL.MACHINE_NAME, SERVICE_CALL.COMMENTS, SERVICE_CALL.WORK_TYPE, WORK_TYPES.SUPPLIER_ID, 
                      SUPPLIER.NAME AS SUPPLIER_NAME, CUSTOMER.NAME AS CUSTOMER_NAME, WORK_TYPES.CUSTOMER_ID, WORK_TYPES.WORK_TYPE_NAME,
                       WORK_TYPES.APPROVER_ROLE, CUSTOMER_APPROVER_ROLE.NAME AS APPROVER_ROLE_NAME, WORK_TYPES.PAYER_ROLE, 
                      PAYER_ROLE.NAME AS PAYER_ROLE_NAME, WORK_TYPES.HOUR_RATE, WORK_TYPES.SKIP_BOSS, SERVICE_CALL_HOURS.NT_0, 
                      SERVICE_CALL_HOURS.NT_1, SERVICE_CALL_HOURS.NT_2, SERVICE_CALL_HOURS.NT_3, SERVICE_CALL_HOURS.NT_4, 
                      SERVICE_CALL_HOURS.NT_5, SERVICE_CALL_HOURS.NT_6, SERVICE_CALL_HOURS.NORMAL_HOURS, SERVICE_CALL.INVOICE_DATE, 
                      SERVICE_CALL.ORDER_NUMBER, SERVICE_CALL.REASON_TYPE, SERVICE_CALL.REASON, SERVICE_CALL.STATUS, SERVICE_CALL.CHECK_NUM, 
                      SERVICE_CALL.EXPENSES_AMOUNT, SERVICE_CALL.EXPENSES_DESCRIPTION, WORKER.BOSS, BOSS.NAME AS BOSS_NAME, 
                      ACCTS_RECEIVABLE.ROLE_ID AS RECEIVABLE_ROLE, ACCTS_RECEIVABLE.ROLE_NAME AS RECEIVABLE_ROLE_NAME, 
                      WORKER.LAST_NAME AS WORKER_LAST_NAME, WORKER.FULL_NAME AS WORKER_NAME, SERVICE_CALL_HOURS.OT_0, 
                      SERVICE_CALL_HOURS.OT_1, SERVICE_CALL_HOURS.OT_2, SERVICE_CALL_HOURS.OT_3, SERVICE_CALL_HOURS.OT_4, 
                      SERVICE_CALL_HOURS.OT_5, SERVICE_CALL_HOURS.OT_6, SERVICE_CALL_HOURS.OT_HOURS, SERVICE_CALL_HOURS.TOTAL_HOURS
FROM         dbo.A_SERVICE_CALLS_WEEKLY_REPORTS SERVICE_CALL INNER JOIN
                      dbo.A_SERVICE_CALLS_TOTAL_HOURS SERVICE_CALL_HOURS ON SERVICE_CALL.ID = SERVICE_CALL_HOURS.WEEKLY_ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA WORKER ON SERVICE_CALL.WORKER_ID = WORKER.ID INNER JOIN
                      dbo.A_SERVICE_CALLS_WORK_TYPES WORK_TYPES ON SERVICE_CALL.WORK_TYPE = WORK_TYPES.ID LEFT OUTER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA CUSTOMER_APPROVER_ROLE ON 
                      WORK_TYPES.APPROVER_ROLE = CUSTOMER_APPROVER_ROLE.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER ON WORK_TYPES.SUPPLIER_ID = SUPPLIER.ID LEFT OUTER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA PAYER_ROLE ON WORK_TYPES.PAYER_ROLE = PAYER_ROLE.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUSTOMER ON WORK_TYPES.CUSTOMER_ID = CUSTOMER.ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALLS_ACC_RECEIVABLE_ROLE ACCTS_RECEIVABLE ON 
                      WORK_TYPES.SUPPLIER_ID = ACCTS_RECEIVABLE.CO_ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA BOSS ON WORKER.BOSS = BOSS.ID
