



CREATE VIEW dbo.A_V_SURVEY_REPLIES_GET_FILE_ATTACHMENT_INFO
AS
SELECT     dbo.A_SURVEY_REPLIES.ID, dbo.A_SURVEY_ATTACHMENTS.DOC_ID AS VALUE, dbo.A_DOCUMENTS.NAME AS SHOW, 
                      dbo.A_SURVEY_ATTACHMENTS.RESPONSE_ID, dbo.A_DOCUMENTS.DESCRIPTION
FROM         dbo.A_SURVEY_ATTACHMENTS INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_SURVEY_ATTACHMENTS.DOC_ID = dbo.A_DOCUMENTS.ID INNER JOIN
                      dbo.A_SURVEY_REPLIES ON dbo.A_SURVEY_ATTACHMENTS.RESPONSE_ID = dbo.A_SURVEY_REPLIES.ID




