CREATE VIEW dbo.A_V_MONITOR_LABEL_PURCHASE_ITEMS
AS
SELECT     dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER, PURCHASE_ITEM.ID AS PURCH_ITEM_ID, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID AS ACTUAL_PART_ID, dbo.A_MONITOR_TEMPLATES.DESCRIPTION, 
                      dbo.A_TASKS.LATEST_REQUESTEE_NAME, dbo.A_MONITOR_RESULTS.PRINT_RESULT, dbo.A_MONITOR_TEMPLATES.IS_PASSING, 
                      dbo.A_MONITOR_TEMPLATES.MY_ANSWER, dbo.A_MONITOR_TEMPLATES.MONITOR_TYPE, dbo.A_MONITOR_TEMPLATES.HIGHEST_THRESHOLD, 
                      dbo.A_MONITOR_TEMPLATES.HIGH_THRESHOLD, dbo.A_MONITOR_TEMPLATES.TARGET, dbo.A_MONITOR_TEMPLATES.LOW_THRESHOLD, 
                      dbo.A_MONITOR_TEMPLATES.LOWEST_THRESHOLD, dbo.A_MONITOR_TEMPLATES.SHOULD_BE, PURCHASE_ITEM.PURCHASE_HIST_ID, 
                      dbo.A_TASKS.ACTUAL_STOP_DATE, dbo.A_TASKS.DESCRIPTION AS TASK_DESCRIPTION, dbo.A_MONITOR_RESULTS.COMMENT, 
                      dbo.A_MONITOR_TEMPLATES.YES_NO_ANSWER
FROM         dbo.A_MONITOR_RESULTS INNER JOIN
                      dbo.A_MONITOR_TEMPLATES ON dbo.A_MONITOR_RESULTS.MONITOR_TEMPLATE_ID = dbo.A_MONITOR_TEMPLATES.ID INNER JOIN
                      dbo.A_TASKS ON dbo.A_MONITOR_TEMPLATES.TASK_ID = dbo.A_TASKS.ID INNER JOIN
                      dbo.A_FILLS FILLS INNER JOIN
                      dbo.A_ORDER_ITEMS PURCHASE_ITEM ON FILLS.PURCH_ITEM_ID = PURCHASE_ITEM.ID INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION ON PURCHASE_ITEM.ID = dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID ON 
                      dbo.A_TASKS.PARENT_ID = dbo.A_TASK_ORDER_INFORMATION.TASK_ID LEFT OUTER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON FILLS.FILL_OBJ_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID
