



CREATE VIEW dbo.A_V_MEETING_AGENDA_ITEM_GET_DOC_INFO
AS
SELECT     dbo.A_DOCUMENTS.ID, dbo.A_DOCUMENTS.NAME AS SHOW, dbo.A_DOCUMENTS.DESCRIPTION, 
                      dbo.A_MEETING_AGENDA_ITEM_DOC_LINK.AGENDA_ID, dbo.A_MEETING_AGENDA_ITEM_DOC_LINK.DOC_ID AS VALUE, 
                      dbo.A_MEETING_AGENDA_ITEM_DOC_LINK.CREATOR_ID
FROM         dbo.A_MEETING_AGENDA_ITEM_DOC_LINK LEFT OUTER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_MEETING_AGENDA_ITEM_DOC_LINK.DOC_ID = dbo.A_DOCUMENTS.DOC_ID




