

CREATE VIEW dbo.A_V_FORECAST_ITEMS_WITH_ACCOUNT_PARENTS
AS
SELECT     dbo.A_V_FORECAST_ITEMS.F_NAME, dbo.A_V_FORECAST_ITEMS.ID, dbo.A_V_FORECAST_ITEMS.START_DATE, 
                      dbo.A_V_FORECAST_ITEMS.STOP_DATE, dbo.A_V_FORECAST_ITEMS.ACCOUNT_ID, dbo.A_V_FORECAST_ITEMS.SUPPLIER_NAME, 
                      dbo.A_V_FORECAST_ITEMS.CUSTOMER_NAME, dbo.A_V_FORECAST_ITEMS.F_TYPE, dbo.A_V_FORECAST_ITEMS.QTY, 
                      dbo.A_V_FORECAST_ITEMS.F_AMT, dbo.A_V_FORECAST_ITEMS.PERCENT_OF_REV, dbo.A_V_FORECAST_ITEMS.PROGRESS, 
                      dbo.A_V_FORECAST_ITEMS.PRODUCT_NAME, dbo.A_V_FORECAST_ITEMS.ACCOUNT_NAME, 
                      A_V_FORECAST_ITEMS_1.ID AS PARENT_FORECAST_ITEM, dbo.A_V_FORECAST_ITEMS.F_OBJ_ID, dbo.A_V_FORECAST_ITEMS.AVG_MONTHLY, 
                      dbo.A_V_FORECAST_ITEMS.CONFIDENCE, dbo.A_V_FORECAST_ITEMS.FORECAST_ID, dbo.A_V_FORECAST_ITEMS.NOTE, 
                      dbo.A_V_FORECAST_ITEMS.AMT_INVOICED, dbo.A_V_FORECAST_ITEMS.DATE_ADDED, dbo.A_V_FORECAST_ITEMS.EST_QUAL_START_DATE, 
                      dbo.A_V_FORECAST_ITEMS.ACT_QUAL_START_DATE, dbo.A_V_FORECAST_ITEMS.EST_FIRST_PURCHASE_DATE, 
                      dbo.A_V_FORECAST_ITEMS.ACT_FIRST_PURCHASE_DATE, dbo.A_V_FORECAST_ITEMS.STATUS, dbo.A_V_FORECAST_ITEMS.PRIORITY, 
                      dbo.A_V_FORECAST_ITEMS.SUPPLIER_OWNER, dbo.A_V_FORECAST_ITEMS.CUSTOMER_OWNER
FROM         dbo.A_ACCOUNTS_HISTORY INNER JOIN
                      dbo.A_ACCOUNTS ON dbo.A_ACCOUNTS_HISTORY.ID = dbo.A_ACCOUNTS.HISTORY_REF_ID INNER JOIN
                      dbo.A_V_FORECAST_ITEMS ON dbo.A_ACCOUNTS.ID = dbo.A_V_FORECAST_ITEMS.ACCOUNT_ID LEFT OUTER JOIN
                      dbo.A_V_FORECAST_ITEMS A_V_FORECAST_ITEMS_1 ON 
                      dbo.A_ACCOUNTS_HISTORY.PARENT_ACCOUNT = A_V_FORECAST_ITEMS_1.ACCOUNT_ID AND 
                      dbo.A_V_FORECAST_ITEMS.F_OBJ_ID = A_V_FORECAST_ITEMS_1.F_OBJ_ID


