CREATE VIEW dbo.A_V_COMPANY_LOGOS
AS
SELECT     dbo.A_DOCUMENT_LINK.TYPE, dbo.A_COMPANIES.ID AS CO_ID, dbo.A_DOCUMENT_LINK.LINKED_DOC_ID
FROM         dbo.A_COMPANIES INNER JOIN
                      dbo.A_COMPANIES_HISTORY ON dbo.A_COMPANIES.HISTORY_REF_ID = dbo.A_COMPANIES_HISTORY.ID INNER JOIN
                      dbo.A_DOCUMENT_LINK ON dbo.A_COMPANIES_HISTORY.OBJECT_ID = dbo.A_DOCUMENT_LINK.OBJECT_ID
WHERE     (dbo.A_DOCUMENT_LINK.TYPE = N'LOGO')
