




CREATE VIEW dbo.A_V_Z_FAVORITES_MENU_ITEMS
AS
SELECT     dbo.A_PEOPLES_FAVORITES.[GROUP], dbo.A_PEOPLES_FAVORITES.ID, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.FAV_TYPE, dbo.A_MENUS.NAME, dbo.A_PEOPLES_FAVORITES.NUM
FROM         dbo.A_PEOPLES_FAVORITES INNER JOIN
                      dbo.A_MENUS ON dbo.A_PEOPLES_FAVORITES.ITEM = dbo.A_MENUS.ID RIGHT OUTER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS ON dbo.A_PEOPLES_FAVORITES.[GROUP] = dbo.A_PEOPLES_FAVORITE_GROUPS.ID