


CREATE VIEW dbo.A_V_PEOPLE_BOSS_SUB_LOOKUP
AS
SELECT     TOP 100 PERCENT B.ID AS BOSS_ID, B.FULL_NAME AS BOSS, S.ID AS SUB_ID, S.FULL_NAME AS SUB
FROM         dbo.A_APPROVED_PEOPLE B INNER JOIN
                      dbo.A_PEOPLE_SUB_LOOKUP_TABLE l ON B.ID = l.BOSS INNER JOIN
                      dbo.A_APPROVED_PEOPLE S ON l.SUBORDINATE = S.ID
ORDER BY B.FULL_NAME



