CREATE VIEW dbo.A_V_DNR_TASKS_WITH_CORRECTIVE_ACTIONS_INFO
AS
SELECT DISTINCT 
                      task.ID AS TASK_ID, task.PARENT_ID AS PARENT_TASK_ID, task.DESCRIPTION AS TASK_DESCRIPTION, task.STATUS AS TASK_STATUS, 
                      task.SYSTEM_TASK, task.PROCEDURE_ID, task.ACTUAL_START_DATE, task.ACTUAL_STOP_DATE, DNR_TASK_INFO.DNR_ID, 
                      DNR_TASK_INFO.DNR_STATUS, DNR_TASK_INFO.TASK_TYPE, [proc].HISTORY_REF_ID AS PROC_HIST_ID, [proc].NAME AS PROC_NAME
FROM         dbo.A_TASKS task INNER JOIN
                      dbo.A_DNR_TASK_INFO DNR_TASK_INFO ON task.ID = DNR_TASK_INFO.TASK_ID INNER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA [proc] ON task.PROCEDURE_ID = [proc].ID
WHERE     (DNR_TASK_INFO.TASK_TYPE = 'Corrective Action')
