CREATE VIEW dbo.A_V_WF_GROUP_ROLES_WITH_MEMBERS
AS
SELECT     dbo.A_V_WF_GROUP_ROLE_LINK.GROUP_ID, dbo.A_V_WF_GROUP_ROLE_LINK.ROLE_ID, p.FULL_NAME, 
                      dbo.A_V_ROLES_APPROVED_WITH_PEOPLE_IDS.PERSON
FROM         dbo.A_V_ROLES_APPROVED_WITH_PEOPLE_IDS INNER JOIN
                      dbo.A_V_WF_GROUP_ROLE_LINK ON 
                      dbo.A_V_ROLES_APPROVED_WITH_PEOPLE_IDS.ROLE_ID = dbo.A_V_WF_GROUP_ROLE_LINK.ROLE_ID INNER JOIN
                      dbo.A_APPROVED_PEOPLE p ON dbo.A_V_ROLES_APPROVED_WITH_PEOPLE_IDS.PERSON = p.ID
