CREATE VIEW dbo.A_V_WORKFLOWS_WITH_STAGES
AS
SELECT     dbo.A_WORKFLOW_STAGE_LINK.WF_ID, dbo.A_WORKFLOW_STAGE_LINK.WF_STAGE_ID, dbo.A_WORKFLOWS.NAME AS WF_NAME, 
                      dbo.A_WF_STAGES.NAME AS WF_STAGE_NAME, dbo.A_WORKFLOW_STAGE_LINK.NUM, dbo.A_WF_STAGES.HIDE AS STAGE_HIDE, 
                      dbo.A_WORKFLOWS.HIDE
FROM         dbo.A_WORKFLOWS INNER JOIN
                      dbo.A_WORKFLOW_STAGE_LINK ON dbo.A_WORKFLOWS.ID = dbo.A_WORKFLOW_STAGE_LINK.WF_ID INNER JOIN
                      dbo.A_WF_STAGES ON dbo.A_WORKFLOW_STAGE_LINK.WF_STAGE_ID = dbo.A_WF_STAGES.ID
