CREATE VIEW dbo.A_V_SERVICE_CALLS_BASIC_DATA
AS
SELECT     dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME AS WORKER_NAME, A_V_PEOPLE_APPROVED_DATA_1.FULL_NAME AS BOSS_NAME, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.WORKER_ID, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.MACHINE_NAME, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.COMMENTS, 
                      Sup.NAME AS SUPPLIER_NAME, Cust.NAME AS CUSTOMER_NAME, dbo.A_SERVICE_CALLS_WORK_TYPES.WORK_TYPE_NAME, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.INVOICE_DATE, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ORDER_NUMBER, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.START_DAY, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.START_MONTH, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.START_YEAR, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.EXPENSES_DESCRIPTION, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.EXPENSES_AMOUNT, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.HOUR_RATE_FIXED, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.OT_RATE_FIXED, dbo.A_SERVICE_CALLS_WORK_TYPES.HOUR_RATE, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.OT_RATE, dbo.A_SERVICE_CALLS_WORK_TYPES.TAX_RATE, CONVERT(dateTime, CONVERT(varchar(2), 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.START_MONTH) + '/' + CONVERT(varchar(2), dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.START_DAY) 
                      + '/' + CONVERT(varchar(4), dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.START_YEAR)) AS START_DATE, 
                      dbo.A_V_PEOPLE_APPROVED_DATA.LAST_NAME AS WORKER_LAST_NAME, dbo.A_V_PEOPLE_APPROVED_DATA.NAME AS WORKER_FIRST_NAME, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.STATUS
FROM         dbo.A_SERVICE_CALLS_WEEKLY_REPORTS INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ON 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.WORKER_ID = dbo.A_V_PEOPLE_APPROVED_DATA.ID INNER JOIN
                      dbo.A_SERVICE_CALLS_WORK_TYPES ON 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.WORK_TYPE = dbo.A_SERVICE_CALLS_WORK_TYPES.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA Sup ON dbo.A_SERVICE_CALLS_WORK_TYPES.SUPPLIER_ID = Sup.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA Cust ON dbo.A_SERVICE_CALLS_WORK_TYPES.CUSTOMER_ID = Cust.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA A_V_PEOPLE_APPROVED_DATA_1 ON 
                      dbo.A_V_PEOPLE_APPROVED_DATA.BOSS = A_V_PEOPLE_APPROVED_DATA_1.ID
