CREATE VIEW dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA
AS
SELECT     ppl.ID, ppl.HISTORY_REF_ID, h.PRODUCT, h.CUSTOMER, h.UNIT, h.MIN_QUANTITY, h.UNIT_PRICE, h.EST_UNIT_PRICE, h.EST_LABOR_PRICE, 
                      h.EST_PARTS_PROV_STAY, h.EST_PARTS_PROV_TAKE_BACK, h.EST_PARTS_CONSUMED, h.INVOICE_FROM, h.PRODUCTION_TIME, 
                      h.PRODUCTION_TIME_UNIT, h.CAPACITY, h.CAPACITY_UNIT, h.DRCM, h.MODBY, h.OBJECT_ID, h.PRODUCT_NAME, h.CUSTOMER_NAME, 
                      prod.SUPPLIER_ID, ppl.STATUS
FROM         dbo.A_PROD_PRICE_LIST ppl INNER JOIN
                      dbo.A_PROD_PRICE_LIST_HISTORY h ON ppl.HISTORY_REF_ID = h.ID LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA prod ON h.PRODUCT = prod.ID
WHERE     (ppl.STATUS = 'APPROVED')
