

CREATE VIEW dbo.A_V_ORDER_WITH_QUOTE_ITEMS
AS
SELECT     qI.ID, dbo.A_QUOTE_ORDER_LINK.ORDER_ID, dbo.A_QUOTE_ORDER_LINK.QUOTE_ID AS QUOTE_HIST_ID, q.ID AS QUOTE_ID, qI.PARENT, 
                      qI.PARENT_QTY, qI.PRODUCT_ID, qI.PROD_PRICE_LIST, qI.PROC_SYS_ID, qI.ADD_COST_ID, qI.TOTAL_QTY, qI.QTY, qI.UNIT_PRICE, 
                      qI.UNIT_ESTIMATE, qI.COMMENTS, qI.DRCM, qI.MODBY, qI.TOTAL_PRICE, qI.DEST, qI.FROM_LOC, qI.TO_LOC, qI.SPECIAL_DISCOUNT, 
                      qI.SPECIAL_DISC_REASON, qI.EXPEDITE_PRODUCTION, qI.EXPEDITE_REASON, qI.FLAT_RATE, qI.EX_DESC, qI.EST_WEIGHT, qI.EST_WEIGHT_UNIT, 
                      qI.PPL_HIST_ID, qI.RECURRING, qI.RECUR_PERIOD, qI.RECUR_COUNT, qI.RECUR_START_DATE, qI.RECUR_STOP_DATE, qI.RECUR_ACCOUNT, 
                      qI.RECUR_AUTO_FILL, qI.SOURCE_ID, qI.PURCHASE_HIST_ID
FROM         dbo.A_V_QUOTES_APPROVED_DATA q RIGHT OUTER JOIN
                      dbo.A_ORDER_ITEMS qI INNER JOIN
                      dbo.A_QUOTE_ORDER_LINK ON qI.QUOTE_ID = dbo.A_QUOTE_ORDER_LINK.QUOTE_ID ON q.HISTORY_REF_ID = qI.QUOTE_ID


