

CREATE VIEW dbo.A_V_TASK_ACTION_OBJECT_LINK_ALL_DATA
AS
SELECT     dbo.A_TASK_ACTION_OBJECT_LINK.TASK_ID, dbo.A_TASK_ACTION_OBJECT_LINK.OBJECT_ID, dbo.A_TASK_ACTION_OBJECT_LINK.RELATIONSHIP, 
                      dbo.A_V_APPROVED_OBJECTS.OBJ_DESC, dbo.A_TASKS.DESCRIPTION AS TASK_DESCRIPTION, dbo.A_TASK_ACTION_OBJECT_LINK.QTY, 
                      dbo.A_TASK_ACTION_OBJECT_LINK.ID
FROM         dbo.A_TASK_ACTION_OBJECT_LINK INNER JOIN
                      dbo.A_TASKS ON dbo.A_TASK_ACTION_OBJECT_LINK.TASK_ID = dbo.A_TASKS.ID INNER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_TASK_ACTION_OBJECT_LINK.OBJECT_ID = dbo.A_V_APPROVED_OBJECTS.ID


