CREATE VIEW dbo.A_V_NOTES_SEARCH_DATA
AS
SELECT     dbo.A_NOTES.ID, dbo.A_NOTES.TXT, dbo.A_NOTES.PEOPLE_SECURE, dbo.A_NOTES.COMPANY_SECURE, dbo.A_NOTES.ROLE_SECURE, 
                      dbo.A_NOTES.SECURITY_LEVEL, dbo.A_NOTES.NOTE_TYPE, dbo.A_NOTES.SECURITY_TYPE, dbo.A_NOTES.RESPONSE_ALLOWED, 
                      dbo.A_NOTES.STATUS, dbo.A_NOTES.AUTHOR, dbo.A_NOTES.REVISION, dbo.A_NOTES.TO_READ_COUNT, dbo.A_NOTES.DATE_CREATED, 
                      dbo.A_NOTES.HIDE_NOTE, dbo.A_NOTES.DATE_SENT, dbo.A_NOTES.NOTIFY, dbo.A_SECURITY_LEVELS.NAME AS SECURITY_LEVEL_NAME, 
                      dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME AS AUTHOR_NAME
FROM         dbo.A_NOTES INNER JOIN
                      dbo.A_SECURITY_LEVELS ON dbo.A_NOTES.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ON dbo.A_NOTES.AUTHOR = dbo.A_V_PEOPLE_APPROVED_DATA.ID
