CREATE VIEW dbo.A_V_BATCH_TASK_CHILDREN
AS
SELECT     BATCH_TOI.TASK_ID AS BATCH_TASK_ID, CHILD_TOI.TASK_ID AS CHILD_TASK_ID
FROM         dbo.A_FILLS F INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION CHILD_TOI ON F.ID = CHILD_TOI.FILL_ITEM_ID INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION BATCH_TOI ON F.BATCH_PARENT = BATCH_TOI.FILL_ITEM_ID
