CREATE VIEW dbo.A_V_MEETING_TASKS
AS
SELECT     TASK.DESCRIPTION, dbo.A_TASK_MEETING_LINK.MEETING_ID, TASK.STATUS, TASK.REQUESTOR, TASK.COMPLETED_BY, 
                      TASK.LATEST_REQUESTEE_NAME, dbo.A_V_PEOPLE_BY_NTLOGIN.P_NAME AS ORIG_REQUESTOR_NAME, dbo.A_TASK_COMMENT.COMMENT, 
                      TASK.ID AS TASK_ID, dbo.A_TASK_LAST_COMMENT.COMMENT_ID
FROM         dbo.A_TASK_COMMENT INNER JOIN
                      dbo.A_TASK_LAST_COMMENT ON dbo.A_TASK_COMMENT.ID = dbo.A_TASK_LAST_COMMENT.COMMENT_ID RIGHT OUTER JOIN
                      dbo.A_TASK_MEETING_LINK INNER JOIN
                      dbo.A_TASKS TASK ON dbo.A_TASK_MEETING_LINK.TASK_ID = TASK.ID ON dbo.A_TASK_LAST_COMMENT.TASK_ID = TASK.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN ON TASK.REQUESTOR = dbo.A_V_PEOPLE_BY_NTLOGIN.P_ID