

CREATE VIEW dbo.A_V_QUOTE_PRECEDENTS_FROM_ORDER_IDS
AS
SELECT     PREV.ID AS PREV_ID, PREV.QUOTE_ID, FOL.ID AS FOL_ID, PREV.PURCHASE_HIST_ID
FROM         dbo.A_ORDER_ITEMS FOL INNER JOIN
                      dbo.A_ORDER_ITEM_PRECEDENTS ON FOL.SOURCE_ID = dbo.A_ORDER_ITEM_PRECEDENTS.FOL INNER JOIN
                      dbo.A_ORDER_ITEMS PREV ON dbo.A_ORDER_ITEM_PRECEDENTS.PREV = PREV.SOURCE_ID


