


CREATE VIEW dbo.A_V_ORDER_ITEM_TRAVEL_TO
AS
SELECT     I.ID, I.PROC_SYS_ID, I.DEST, I.PARENT, I.PRODUCT_ID, P.NAME AS PROD_NAME
FROM         dbo.A_ORDER_ITEMS I INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA P ON I.PRODUCT_ID = P.ID
WHERE     (I.DEST = 'to') AND (I.PROC_SYS_ID = 'SYS_TRAVEL')



