CREATE VIEW dbo.A_V_INVOICE_ITEMS_WITH_SUPPLIER_DATA
AS
SELECT     dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID, dbo.A_ACCOUNT_INVOICE_ITEMS.INVOICE_ID, dbo.A_ACCOUNT_INVOICE_ITEMS.ID, 
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK.NAME AS SUP_NAME, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ADDRESS_1, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ADDRESS_2, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.CITY, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.STATE, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.COUNTRY, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.POSTAL_CODE, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.INTERNAL_ADDRESS, 
                      dbo.A_DOCUMENT_LINK.LINKED_DOC_ID
FROM         dbo.A_ACCOUNT_INVOICE_ITEMS INNER JOIN
                      dbo.A_ORDER_ITEMS ON dbo.A_ACCOUNT_INVOICE_ITEMS.PURCH_ITEM_ID = dbo.A_ORDER_ITEMS.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON dbo.A_ORDER_ITEMS.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA_QUICK.ID INNER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK ON 
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK.LOCATION = dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ID LEFT OUTER JOIN
                      dbo.A_DOCUMENT_LINK ON dbo.A_V_COMPANIES_APPROVED_DATA_QUICK.OBJECT_ID = dbo.A_DOCUMENT_LINK.OBJECT_ID
WHERE     (dbo.A_DOCUMENT_LINK.TYPE = N'LOGO')
