


CREATE VIEW dbo.A_V_SURVEY_WITH_INITIAL_DATA
AS
SELECT     dbo.A_SURVEYS.ID AS S_ID, dbo.A_SURVEYS.OWNER AS INITIATOR_ID, dbo.A_SURVEYS.SUBJECT, dbo.A_SURVEYS.DATE_CREATED, 
                      dbo.A_SURVEY_REPLIES.ROOT, dbo.A_SURVEY_REPLIES.TEXT, dbo.A_APPROVED_PEOPLE.FULL_NAME AS INITIATOR_NAME, 
                      dbo.A_SURVEYS.STATUS, dbo.A_APPROVED_PEOPLE.ID AS P_ID, dbo.A_SURVEYS.DRCM, dbo.A_SURVEY_REPLIES.ID AS R_ID, 
                      dbo.A_SURVEY_REPLIES.NUM
FROM         dbo.A_SURVEYS LEFT OUTER JOIN
                      dbo.A_APPROVED_PEOPLE ON dbo.A_SURVEYS.OWNER = dbo.A_APPROVED_PEOPLE.ID LEFT OUTER JOIN
                      dbo.A_SURVEY_REPLIES ON dbo.A_SURVEYS.ID = dbo.A_SURVEY_REPLIES.ROOT



