CREATE VIEW dbo.A_V_WF_GROUPS
AS
SELECT     dbo.A_OBJECTS.OBJ_TABLE, dbo.A_OBJECTS.ID AS OBJ_ID, dbo.A_OBJECTS.OBJ_ID AS ID, dbo.A_OBJECTS.OBJ_DESC, dbo.A_OBJECTS.DRCM, 
                      dbo.A_OBJECTS.MODBY, dbo.A_OBJECTS.CO_PART_NUM, dbo.A_OBJECTS.PART_TYPE, dbo.A_OBJECTS.PART_CO, dbo.A_OBJECTS.LOCKED_BY, 
                      dbo.A_OBJECTS.UNLOCKED_BY, dbo.A_OBJECTS.CREATED_BY, dbo.A_OBJECTS.CREATE_DATE, dbo.A_OBJECTS.ROOT, dbo.A_OBJECTS.REV_INFO,
                       dbo.A_OBJECTS.CREATING_CO, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.REV, dbo.A_OBJECTS.WFS_ID, dbo.A_WF_GROUPS.NAME, 
                      dbo.A_WF_GROUPS.HIDE
FROM         dbo.A_OBJECTS INNER JOIN
                      dbo.A_WF_GROUPS ON dbo.A_OBJECTS.ID = dbo.A_WF_GROUPS.OBJECT_ID
WHERE     (dbo.A_OBJECTS.OBJ_TABLE = N'A_WF_GROUPS')
