CREATE VIEW dbo.A_V_SERVICE_CALL_INVOICE_DATA
AS
SELECT     dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.ID, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.WORKER_ID, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.WORKER_NAME, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.NORMAL_HOURS, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.CUSTOMER_NAME, ca.ADDRESS_1 AS CUSTOMER_ADDRESS, ca.CITY AS CUSTOMER_CITY, 
                      ca.STATE AS CUSTOMER_STATE, ca.POSTAL_CODE AS CUSTOMER_POSTAL_CODE, ca.PHONE AS CUSTOMER_PHONE, 
                      supplier_payment_location.RECIEVABLE_ROLE, supplier_payment_location.PAYMENT_LOCATION, 
                      supplier_payment_location.SUPPLIER_LOCATION_NAME, supplier_payment_location.SUPPLIER_ADDRESS, 
                      supplier_payment_location.SUPPLIER_CITY, supplier_payment_location.SUPPLIER_STATE, supplier_payment_location.SUPPLIER_POSTAL_CODE, 
                      supplier_payment_location.SUPPLIER_PHONE, supplier_payment_location.LINKED_DOC_ID AS LOGO_ID, 
                      dbo.A_SERVICE_CALLS_WORK_TYPES.HOUR_RATE, dbo.A_SERVICE_CALLS_WORK_TYPES.TAX_RATE, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.BOSS, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.RECEIVABLE_ROLE, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.PAYER_ROLE, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.APPROVER_ROLE, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.SUPPLIER_ID, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.CUSTOMER_ID, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.ACTUAL_START_DATE, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.STATUS, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.SUPPLIER_NAME, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.INVOICE_DATE, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.ORDER_NUMBER, dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.WORK_TYPE_NAME, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.HOUR_RATE * ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.NORMAL_HOURS, 0) 
                      + ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.EXPENSES_AMOUNT, 0) AS SUB_TOTAL, 
                      (ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.HOUR_RATE, 0) * ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.NORMAL_HOURS, 0) 
                      + ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.EXPENSES_AMOUNT, 0)) * (ISNULL(dbo.A_SERVICE_CALLS_WORK_TYPES.TAX_RATE, 0) / 100) 
                      AS TAXES, ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.HOUR_RATE, 0) * ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.NORMAL_HOURS, 
                      0) + ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.EXPENSES_AMOUNT, 0) + (ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.HOUR_RATE, 0) 
                      * ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.NORMAL_HOURS, 0) + ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.EXPENSES_AMOUNT, 
                      0)) * (ISNULL(dbo.A_SERVICE_CALLS_WORK_TYPES.TAX_RATE, 0) / 100) AS TOTAL, 
                      ISNULL(dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.EXPENSES_AMOUNT, 0) AS EXPENSES_AMOUNT, 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.EXPENSES_DESCRIPTION
FROM         dbo.A_V_SERVICE_CALLS_WEEKLY_DATA INNER JOIN
                      dbo.A_SERVICE_CALLS_WORK_TYPES ON 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.WORK_TYPE = dbo.A_SERVICE_CALLS_WORK_TYPES.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_LOCATION_ADDRESSES ca ON dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.CUSTOMER_ID = ca.ID LEFT OUTER JOIN
                      dbo.A_V_SERVICE_CALL_PAYMENT_LOCATIONS supplier_payment_location ON 
                      dbo.A_V_SERVICE_CALLS_WEEKLY_DATA.SUPPLIER_ID = supplier_payment_location.COMPANY_ID
