


CREATE VIEW dbo.A_V_DISCUSSION_GET_TREE_DATA
AS
SELECT     dbo.A_V_DISCUSSION_WITH_INITIAL_DATA.INITIATOR_NAME AS WRITER_NAME, 
                      dbo.A_V_DISCUSSION_WITH_INITIAL_DATA.INITIATOR_ID AS INITIATOR, dbo.A_DISCUSSION_RESPONSE.DRCM, 
                      dbo.A_V_DISCUSSION_WITH_INITIAL_DATA.ID, dbo.A_DISCUSSION_RESPONSE.ID AS R_ID, 
                      dbo.A_V_DISCUSSION_WITH_INITIAL_DATA.DATE_CREATED, dbo.A_DISCUSSION_ATTACHMENTS.DOC_ID, dbo.A_DISCUSSION_RESPONSE.COLOR, 
                      dbo.A_DISCUSSION_RESPONSE.RESPONSE
FROM         dbo.A_V_DISCUSSION_WITH_INITIAL_DATA LEFT OUTER JOIN
                      dbo.A_DISCUSSION_RESPONSE ON 
                      dbo.A_V_DISCUSSION_WITH_INITIAL_DATA.RESPONSE_ID = dbo.A_DISCUSSION_RESPONSE.ID LEFT OUTER JOIN
                      dbo.A_DISCUSSION_ATTACHMENTS ON dbo.A_DISCUSSION_RESPONSE.ID = dbo.A_DISCUSSION_ATTACHMENTS.RESPONSE_ID



