


CREATE VIEW dbo.A_V_THEORY_PARAGRAPH_DOCUMENT_DATA
AS
SELECT     dbo.A_THEORY_PARAGRAPH_FILE_LINK.PARAGRAPH_ID, dbo.A_DOCUMENTS.*
FROM         dbo.A_THEORY_PARAGRAPH_FILE_LINK INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_THEORY_PARAGRAPH_FILE_LINK.FILE_ID = dbo.A_DOCUMENTS.ID



