


CREATE VIEW dbo.A_V_ROLES_APPROVED_WITH_PEOPLE_IDS
AS
SELECT     dbo.A_ROLES.ID AS ROLE_ID, dbo.A_ROLES.HISTORY_REF_ID, dbo.A_ROLE_ASSIGNEE.PERSON, dbo.A_ROLES_HISTORY.IS_ADMIN
FROM         dbo.A_ROLES INNER JOIN
                      dbo.A_ROLES_HISTORY ON dbo.A_ROLES.HISTORY_REF_ID = dbo.A_ROLES_HISTORY.ID INNER JOIN
                      dbo.A_ROLE_ASSIGNEE ON dbo.A_ROLES_HISTORY.ID = dbo.A_ROLE_ASSIGNEE.ROLE



