CREATE VIEW dbo.A_V_PRODUCTS_WITH_ACTUAL_PARTS_THEY_ARE_USED_ON
AS
SELECT     P_OBJ_USED_ON.OBJECT_ID, PTS.ID AS PART_ID, PH.NAME AS PART_NAME, PROD_HIST.NAME AS PRODUCT_NAME, PROD.ID AS PRODUCT_ID, 
                      APH.LOCATION, APH.NICK_NAME, APH.PART_ID AS AP_PART_ID, APH.QTY, APH.SERIAL, APH.CUR_OWNER, APH.ASSEMBLY_WT, APH.AP_STATUS, 
                      APH.ROOT_ID, APH.ROOT_STATUS, PRO_PART_LINK.ID AS INSTALLED_ID, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS OWNER_NAME, 
                      dbo.A_V_LOCATION_WITH_NAME.LOCATION_NAME, APH.OBJECT_ID AS AP_OBJECT_ID, dbo.A_FN_ACTUAL_PART_HAS_CHILD(AP.ID) AS HAS_CHILD, 
                      APH.PARENT_ID, dbo.A_FN_PRODUCT_INSTALLED_STATUS(PRO_PART_LINK.ID) AS PROD_STATUS, AP.ID AS AP_ID, o.LOCKED_BY, 
                      o.UNLOCKED_BY, o.CREATED_BY, o.CREATE_DATE, o.ROOT, o.REV_INFO, o.CREATING_CO, o.STATUS, o.REV, o.LOCKED_BY_NAME, 
                      o.CREATING_CO_NAME, o.ID AS OBJ_ID, ISNULL('(' + AP.ID + ')', '') + ISNULL(' ' + APH.NICK_NAME, '') + ISNULL(' (' + APH.SERIAL + ')', '') 
                      + ISNULL(' [' + PH.NAME + '] ', '') AS AP_DESC, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.NAME AS PARENT_NAME
FROM         dbo.A_PRODUCTS PROD INNER JOIN
                      dbo.A_PARTS_HISTORY PH INNER JOIN
                      dbo.A_PARTS PTS ON PH.ID = PTS.PARTS_HISTORY_ID INNER JOIN
                      dbo.A_PRODUCT_OBJ_USED_ON_LINK P_OBJ_USED_ON ON PTS.ID = P_OBJ_USED_ON.OBJECT_ID INNER JOIN
                      dbo.A_PRODUCTS_HISTORY PROD_HIST ON P_OBJ_USED_ON.PRODUCT_ID = PROD_HIST.ID INNER JOIN
                      dbo.A_ACTUAL_PARTS AP INNER JOIN
                      dbo.A_ACTUAL_PARTS_HISTORY APH ON AP.HISTORY_REF_ID = APH.ID ON PTS.ID = APH.PART_ID ON 
                      PROD.HISTORY_REF_ID = PROD_HIST.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON APH.CUR_OWNER = dbo.A_V_COMPANIES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_LOCATION_WITH_NAME ON APH.LOCATION = dbo.A_V_LOCATION_WITH_NAME.L_ID INNER JOIN
                      dbo.A_OBJECTS o ON APH.OBJECT_ID = o.ID LEFT OUTER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON APH.PARENT_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_ACTUAL_PART_PRODUCTS_INSIDE_LINK PRO_PART_LINK ON PROD.ID = PRO_PART_LINK.PRODUCT_ID AND 
                      APH.ID = PRO_PART_LINK.ACTUAL_PART_ID
