CREATE VIEW dbo.A_V_FORECAST_ITEM_EDIT_DATA
AS
SELECT     ACCOUNTS.SUPPLIER_NAME, ACCOUNTS.CUSTOMER_NAME, F_ITEM.*, PRODUCTS.NAME AS PRODUCT_NAME, PRODUCTS.ID AS PRODUCT_ID, 
                      ACCOUNTS.NAME AS ACCT_NAME, ACCOUNTS.CUSTOMER_CO AS CUSTOMER_ID, ACCOUNTS.SUPPLIER_CO AS SUPPLIER_ID, 
                      dbo.A_FORECASTS_HISTORY.CO AS FORECAST_CO
FROM         dbo.A_FORECAST_ITEMS F_ITEM INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA ACCOUNTS ON F_ITEM.ACCOUNT_ID = ACCOUNTS.ID INNER JOIN
                      dbo.A_FORECASTS_HISTORY ON F_ITEM.FORECAST_ID = dbo.A_FORECASTS_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA PRODUCTS ON ACCOUNTS.PRODUCT_ID = PRODUCTS.ID
