


CREATE VIEW dbo.A_V_APPROVALS_PENDING
AS
SELECT     O.OBJ_TABLE AS ITEM_TYPE, O.OBJ_DESC AS ITEM_NAME, O.ROOT AS ITEM_NUMBER, wf.NAME AS WF_NAME, s.NAME AS STAGE_NAME, 
                      g.NAME AS GROUP_NAME, STARTER.FULL_NAME AS INITIATOR, APPROVER.FULL_NAME AS APPROVER_NAME, wfs.START_DATE AS DATE_STARTED,
                       wfs.STATUS_ON_COMPLETION AS STATUS, O.ID AS OBJECT_ID, O.REV AS REVISION, d.PERSON AS PERSON_ID, gs.WFS_ID, gs.WF_STAGE_ID, 
                      gs.WF_GROUP_ID, gs.APPROVER, O.REV_INFO
FROM         dbo.A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS d INNER JOIN
                      dbo.A_WORKFLOW_GROUP_STARTED gs ON d.WFGS_ID = gs.ID INNER JOIN
                      dbo.A_WF_STAGES s ON gs.WF_STAGE_ID = s.ID INNER JOIN
                      dbo.A_WF_GROUPS g ON gs.WF_GROUP_ID = g.ID INNER JOIN
                      dbo.A_WORKFLOWS_STARTED wfs ON gs.WFS_ID = wfs.ID INNER JOIN
                      dbo.A_WORKFLOWS wf ON wfs.WF_ID = wf.ID INNER JOIN
                      dbo.A_APPROVED_PEOPLE APPROVER ON d.PERSON = APPROVER.ID INNER JOIN
                      dbo.A_OBJECTS O ON wfs.ID = O.WFS_ID INNER JOIN
                      dbo.A_APPROVED_PEOPLE STARTER ON wfs.STARTED_BY = STARTER.ID



