CREATE VIEW dbo.A_V_INVOICES
AS
SELECT     dbo.A_ACCOUNT_INVOICES.ID, dbo.A_ACCOUNT_INVOICES.ACCOUNT_ID, dbo.A_ACCOUNT_INVOICES.INVOICE_DATE, 
                      dbo.A_ACCOUNT_INVOICES.DRCM, dbo.A_ACCOUNT_INVOICES.MODBY, dbo.A_ACCOUNT_INVOICES.STATUS, dbo.A_ACCOUNT_INVOICES.AMT_PAID, 
                      dbo.A_ACCOUNT_INVOICES.NEW_ITEMS_AMT, dbo.A_ACCOUNT_INVOICES.PREVIOUS_BALANCE, dbo.A_ACCOUNT_INVOICES.PAYMENT_AMOUNT, 
                      dbo.A_ACCOUNT_INVOICES.DISPUTED_AMOUNT, dbo.A_ACCOUNT_INVOICES.TOTAL_DUE, dbo.A_ACCOUNT_INVOICES.DUE_DATE, 
                      dbo.A_ACCOUNT_INVOICES.LATE_FEES, dbo.A_ACCOUNT_INVOICES.DATE_SENT_TO_CUSTOMER, dbo.A_ACCOUNT_INVOICES.PURCHASE_ID, 
                      dbo.A_V_PURCHASES_APPROVED_DATA.STATUS AS Expr1, dbo.A_V_PURCHASES_APPROVED_DATA.CUST_PURCH_NUM, 
                      dbo.A_V_PURCHASES_APPROVED_DATA.SUP_PURCH_NUM, dbo.A_ACCOUNT_INVOICES.NAME, dbo.A_ACCOUNT_INVOICES.INVOICE_TYPE
FROM         dbo.A_ACCOUNT_INVOICES LEFT OUTER JOIN
                      dbo.A_V_PURCHASES_APPROVED_DATA ON dbo.A_ACCOUNT_INVOICES.PURCHASE_ID = dbo.A_V_PURCHASES_APPROVED_DATA.ID
