CREATE VIEW dbo.A_V_WF_STAGES_WITH_GROUPS
AS
SELECT     l.WF_GROUP_ID, g.NAME AS GROUP_NAME, dbo.A_O_WF_STAGES.CREATING_CO, dbo.A_O_WF_STAGES.NAME AS STAGE_NAME, 
                      dbo.A_O_WF_STAGES.ID AS STAGE_ID, dbo.A_O_WF_STAGES.HIDE, g.HIDE AS GROUP_HIDE
FROM         dbo.A_WF_STAGE_GROUP_LINK l INNER JOIN
                      dbo.A_WF_GROUPS g ON l.WF_GROUP_ID = g.ID RIGHT OUTER JOIN
                      dbo.A_O_WF_STAGES ON l.WF_STAGE_ID = dbo.A_O_WF_STAGES.ID
