


CREATE VIEW dbo.A_V_SERVICE_CALL_ACC_RECIEVABLE_PAYMENT_LOCATION_NAMES
AS
SELECT     dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.COMPANY_ID, dbo.A_APPROVED_LOCATIONS.NAME AS show, 
                      dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.PAYMENT_LOCATION AS [value]
FROM         dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE INNER JOIN
                      dbo.A_APPROVED_LOCATIONS ON dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE.PAYMENT_LOCATION = dbo.A_APPROVED_LOCATIONS.ID