

CREATE VIEW dbo.A_V_PROCEDURE_STEP_OWNER_ROLE
AS
SELECT     RELATIONSHIP, LABOR_ROLE, APPROVED_OBJECT_ID AS OWNER_ROLE_ID, STEP_ID, QTY, QTY_TYPE
FROM         dbo.A_PROCEDURE_OBJECT_LINK
WHERE     (RELATIONSHIP = N'LABOR_PROVIDE_TAKE_BACK') AND (LABOR_ROLE = 'LABOR_OWNER')


