



CREATE  VIEW dbo.A_V_PROCEDURE_STEP_WITH_REF_PROCEDURES
AS
SELECT     dbo.A_PROCEDURE_STEPS.ID AS STEP_ID, dbo.A_PROCEDURE_STEP_PROCEDURE_LINK.PROCEDURE_LINK, 
                      dbo.A_OBJECTS.OBJ_DESC AS PROC_NAME, dbo.A_OBJECTS.ID AS PROC_OBJ_ID
FROM         dbo.A_OBJECTS INNER JOIN
                      dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT ON dbo.A_OBJECTS.ID = dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ID INNER JOIN
                      dbo.A_PROCEDURE_STEPS INNER JOIN
                      dbo.A_PROCEDURE_STEP_PROCEDURE_LINK ON 
                      dbo.A_PROCEDURE_STEPS.ID = dbo.A_PROCEDURE_STEP_PROCEDURE_LINK.PROCEDURE_STEP ON 
                      dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ROOT = dbo.A_PROCEDURE_STEP_PROCEDURE_LINK.PROCEDURE_LINK




