



CREATE VIEW dbo.A_V_POP_FILL_DISCUSSION_INVITED_ROLES
AS
SELECT     dbo.A_DISCUSSION_INV_ROLE.DISCUSSION_ID AS D_ID, dbo.A_APPROVED_ROLES.ID AS R_ID, 
                      dbo.A_APPROVED_ROLES.NAME AS ROLE_NAME
FROM         dbo.A_APPROVED_ROLES INNER JOIN
                      dbo.A_DISCUSSION_INV_ROLE ON dbo.A_APPROVED_ROLES.ID = dbo.A_DISCUSSION_INV_ROLE.ROLE_ID




