CREATE VIEW dbo.A_V_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFORMATION
AS
SELECT     dbo.A_ACCOUNT_INVOICE_ITEMS.ID, dbo.A_ACCOUNT_INVOICE_ITEMS.INVOICE_ID, dbo.A_ACCOUNT_INVOICE_ITEMS.ACCOUNT_ID, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS.PURCH_ITEM_ID, dbo.A_ACCOUNT_INVOICE_ITEMS.STATUS, dbo.A_ACCOUNT_INVOICE_ITEMS.DRCM, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS.MODBY, dbo.A_ACCOUNT_INVOICE_ITEMS.AMOUNT, dbo.A_ACCOUNT_INVOICE_ITEMS.DESCRIPTION, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS.DATE_INVOICED, dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.PAYMENT_METHOD, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.CHECK_NO, dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.EXP_MO, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.EXP_YEAR, dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.RECORDED_BY, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.CC_NO, dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME, 
                      dbo.A_ACCOUNT_INVOICE_ITEMS.DATE_POSTED, dbo.A_ACCOUNT_INVOICE_ITEMS.COMMENTS
FROM         dbo.A_V_PEOPLE_APPROVED_DATA INNER JOIN
                      dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO ON 
                      dbo.A_V_PEOPLE_APPROVED_DATA.ID = dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.RECORDED_BY INNER JOIN
                      dbo.A_ACCOUNT_INVOICE_ITEMS ON dbo.A_ACCOUNT_INVOICE_ITEMS_PAYMENT_INFO.INVOICE_ITEM_ID = dbo.A_ACCOUNT_INVOICE_ITEMS.ID
