


CREATE VIEW dbo.A_V_SERVICE_CALL_WORK_TIME_WITH_DATE
AS
SELECT     ID, WEEKLY_ID, D, MO, YR, HOUR_TYPE, HOURS, CONVERT(datetime, STR(MO) + '/' + STR(D) + '/' + STR(YR)) AS DT
FROM         dbo.A_SERVICE_CALL_WORK_TIME



