


CREATE VIEW dbo.A_V_FORECAST_ITEMS_WITH_PRODUCTS
AS
SELECT     F_ITEMS.ID AS F_ITEM_ID, F_ITEMS.FORECAST_ID, F_HISTORY.OBJECT_ID AS FORECAST_OBJECT_ID, F_ITEMS.ACCOUNT_ID, 
                      ACCTS_HIST.NAME AS ACCT_NAME, PROD_HIST.NAME AS PROD_NAME, PRODS.ID AS PROD_ID, PRICE_HIST.ID AS PRICE_ID, 
                      PRICE_HIST.UNIT_PRICE, PRICE_HIST.EST_UNIT_PRICE, CUSTOMER.NAME AS CUSTOMER_NAME, PROD_HIST.SUPPLIER_ID, 
                      SUPPLIER.NAME AS SUPPLIER_NAME, F_ITEMS.F_TYPE, F_ITEMS.QTY, F_ITEMS.F_AMT, F_ITEMS.PERCENT_OF_REV, F_ITEMS.PROGRESS, 
                      ACCTS_HIST.CUSTOMER_CO AS CUSTOMER_ID, F_ITEMS.CONFIDENCE, F_ITEMS.AVG_MONTHLY, F_HISTORY.CO AS FORECAST_CO, 
                      F_ITEMS.NOTE, F_ITEMS.AMT_INVOICED
FROM         dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUSTOMER ON dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.CUST_ID = CUSTOMER.ID RIGHT OUTER JOIN
                      dbo.A_FORECASTS_HISTORY F_HISTORY INNER JOIN
                      dbo.A_FORECAST_ITEMS F_ITEMS INNER JOIN
                      dbo.A_ACCOUNTS ACCTS ON F_ITEMS.ACCOUNT_ID = ACCTS.ID INNER JOIN
                      dbo.A_ACCOUNTS_HISTORY ACCTS_HIST ON ACCTS.HISTORY_REF_ID = ACCTS_HIST.ID ON 
                      F_HISTORY.ID = F_ITEMS.FORECAST_ID LEFT OUTER JOIN
                      dbo.A_PRODUCTS_HISTORY PROD_HIST INNER JOIN
                      dbo.A_PRODUCTS PRODS ON PROD_HIST.ID = PRODS.HISTORY_REF_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER ON PROD_HIST.SUPPLIER_ID = SUPPLIER.ID ON 
                      ACCTS_HIST.PRODUCT_ID = PRODS.ID LEFT OUTER JOIN
                      dbo.A_PROD_PRICE_LIST PRICE_LIST INNER JOIN
                      dbo.A_PROD_PRICE_LIST_HISTORY PRICE_HIST ON PRICE_LIST.HISTORY_REF_ID = PRICE_HIST.ID ON PRODS.ID = PRICE_HIST.PRODUCT ON 
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.PP_LIST_ID = PRICE_HIST.ID AND 
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS.CUST_ID = ACCTS_HIST.CUSTOMER_CO



