

CREATE VIEW dbo.A_V_PURCHASE_QUOTE_STATUS
AS
SELECT     ph.ID AS PURCHASE_HIST_ID, p.ID AS PURCHASE_ID, ph.PURCHASE_STATUS, qH.ID AS QUOTE_HIST_ID, qH.PROGRESS AS QUOTE_PROGRESS, 
                      PQ_STAT.STATUS AS PQ_STATUS, q.ID AS QUOTE_ID
FROM         dbo.A_PURCHASE_QUOTE_STATUS PQ_STAT INNER JOIN
                      dbo.A_PURCHASES_HISTORY ph ON PQ_STAT.PURCHASE_ID = ph.ID INNER JOIN
                      dbo.A_QUOTES_HISTORY qH ON PQ_STAT.QUOTE_ID = qH.ID INNER JOIN
                      dbo.A_QUOTES q ON qH.ID = q.HISTORY_REF_ID LEFT OUTER JOIN
                      dbo.A_PURCHASES p ON ph.ID = p.HISTORY_REF_ID


