CREATE VIEW dbo.A_V_SERVICE_CALL_SEARCH_DATA
AS
SELECT     sc.BOSS, sc.SUPPLIER_NAME, CONVERT(VARCHAR(50), sc.START_DATE, 1) AS START_DATE_STRING, sc.WORK_TYPE, 
                      dbo.A_FN_SERVICE_CALL_GET_STANDARD_SEARCH_FLAG(sc.STATUS) AS STANDARD_SEARCH, sc.CUSTOMER_NAME, sc.SUPPLIER_ID, 
                      sc.CUSTOMER_ID, sc.APPROVER_ROLE, sc.PAYER_ROLE, sc.APPROVER AS APPROVER_NAME, sc.PAYER AS PAYER_NAME, sc.WORKER_ID, sc.ID, 
                      sc.MACHINE_NAME, sc.FULL_NAME, sc.STATUS, sc.REASON, worker_name.P_NAME AS WORKER_NAME, sc.START_DAY, sc.START_YEAR, 
                      sc.START_MONTH, sc.START_DATE, ac_ar_link.RECIEVABLE_ROLE, sc.REASON_TYPE, ar.NAME AS AR_NAME, sc.COMMENTS, 
                      boss_name.P_NAME AS BOSS_NAME, sc.ORDER_NUMBER, dbo.A_PEOPLES_FAVORITES.[GROUP] AS GROUP_ID, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.FAV_TYPE, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.PERSON, dbo.A_SERVICE_CALLS_TOTAL_HOURS.NORMAL_HOURS, 
                      dbo.A_SERVICE_CALLS_TOTAL_HOURS.OT_HOURS, dbo.A_SERVICE_CALLS_TOTAL_HOURS.TOTAL_HOURS, 
                      sc.EXPENSES_AMOUNT AS EXPENSES
FROM         dbo.A_V_PEOPLE_BY_NTLOGIN boss_name RIGHT OUTER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS INNER JOIN
                      dbo.A_PEOPLES_FAVORITES ON dbo.A_PEOPLES_FAVORITE_GROUPS.ID = dbo.A_PEOPLES_FAVORITES.[GROUP] RIGHT OUTER JOIN
                      dbo.A_V_SERVICE_CALLS_WITH_NORMAL_HOURS sc INNER JOIN
                      dbo.A_SERVICE_CALLS_TOTAL_HOURS ON sc.ID = dbo.A_SERVICE_CALLS_TOTAL_HOURS.WEEKLY_ID ON 
                      dbo.A_PEOPLES_FAVORITES.ITEM = sc.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN worker_name ON sc.WORKER_ID = worker_name.P_ID ON boss_name.P_ID = sc.BOSS LEFT OUTER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA ar INNER JOIN
                      dbo.A_SERVICE_CALLS_ACC_RECIEVABLE_ROLE ac_ar_link ON ar.ID = ac_ar_link.RECIEVABLE_ROLE ON sc.SUPPLIER_ID = ac_ar_link.COMPANY_ID
