

CREATE VIEW dbo.A_V_PROD_PRICE_LIST_BY_APPROVED_ID
AS
SELECT     dbo.A_PROD_PRICE_LIST.ID, dbo.A_PROD_PRICE_LIST.HISTORY_REF_ID, dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCT, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.CUSTOMER, dbo.A_PROD_PRICE_LIST_HISTORY.UNIT, dbo.A_PROD_PRICE_LIST_HISTORY.MIN_QUANTITY, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.UNIT_PRICE, dbo.A_PROD_PRICE_LIST_HISTORY.EST_UNIT_PRICE, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.EST_LABOR_PRICE, dbo.A_PROD_PRICE_LIST_HISTORY.EST_PARTS_PROV_STAY, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.EST_PARTS_PROV_TAKE_BACK, dbo.A_PROD_PRICE_LIST_HISTORY.EST_PARTS_CONSUMED, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.INVOICE_FROM, dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCTION_TIME, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCTION_TIME_UNIT, dbo.A_PROD_PRICE_LIST_HISTORY.CAPACITY, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.CAPACITY_UNIT, dbo.A_PROD_PRICE_LIST_HISTORY.DRCM, dbo.A_PROD_PRICE_LIST_HISTORY.MODBY, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.OBJECT_ID, dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCT_NAME, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.CUSTOMER_NAME, dbo.A_V_PRODUCTS_APPROVED_DATA.SUPPLIER_ID, dbo.A_PROD_PRICE_LIST.STATUS, 
                      dbo.A_PROD_PRICE_LIST_HISTORY.FOR_INDIVIDUAL_SALE
FROM         dbo.A_PROD_PRICE_LIST INNER JOIN
                      dbo.A_PROD_PRICE_LIST_HISTORY ON dbo.A_PROD_PRICE_LIST.HISTORY_REF_ID = dbo.A_PROD_PRICE_LIST_HISTORY.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON dbo.A_PROD_PRICE_LIST_HISTORY.PRODUCT = dbo.A_V_PRODUCTS_APPROVED_DATA.ID
WHERE     (dbo.A_PROD_PRICE_LIST.STATUS = 'APPROVED')


