CREATE VIEW dbo.A_V_FILLS_SEARCH
AS
SELECT     CUST.NAME AS CUST_NAME, SUP.NAME AS SUP_NAME, parts.SYS_NAME AS FILL_OBJ_DESC, FILL_PERSON.FULL_NAME AS FILLER_NAME, 
                      PURCHASE_ITEM.PRODUCT_ID AS PROD_ID, dbo.A_PURCHASES_HISTORY.PURCHASER AS PURCHASER_ID, 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PROD_NAME, dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID AS PROC_ID, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.SYSTEM_ID AS SYS_PROC_ID, A_V_APPROVED_OBJECTS_1.OBJ_DESC AS APP_OBJ_DESC, 
                      PURCHASE_ITEM.ADD_COST_ID AS PRICING_TABLE_ID, dbo.A_QUOTES_HISTORY.CUSTOMER_CO AS CUSTOMER, 
                      dbo.A_QUOTES_HISTORY.SUPPLIER_ID AS SUPPLIER, PURCHASE_ITEM.QTY AS PURCHASE_QTY, PURCHASE_ITEM.UNIT_PRICE, 
                      PURCHASE_ITEM.TOTAL_PRICE, PURCHASE_ITEM.DEST, PURCHASE_ITEM.FROM_LOC, PURCHASE_ITEM.TO_LOC, 
                      PURCHASE_ITEM.PURCHASE_HIST_ID, PURCHASE_ITEM.ACCOUNT_ID, PURCHASE_ITEM.TOTAL_QTY AS TOT_QTY, PURCHASE_ITEM.PARENT_QTY, 
                      PURCHASE_ITEM.EST_WEIGHT AS WEIGHT, PURCHASE_ITEM.EST_WEIGHT_UNIT AS WEIGHT_UNIT, 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.APP_OBJECT AS OBJ_PROD_APPLIES_TO, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.HISTORY_REF_ID AS PROCEDURE_HIST_ID, dbo.A_V_PROCEDURES_APPROVED_DATA.STEPS_IN_AP, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROC_NAME, dbo.A_V_PRODUCTS_APPROVED_DATA.HISTORY_REF_ID AS PROD_HIST_ID, 
                      dbo.A_QUOTES_HISTORY.CUSTOMER_PERSON, dbo.A_PURCHASES_HISTORY.OBJECT_ID AS PURCHASE_ID, FILLS.ID, FILLS.PURCH_ITEM_ID, 
                      FILLS.FILL_BY, FILLS.FILL_OBJ_ID, FILLS.FILL_QTY, FILLS.FILLER, FILLS.TASK_ID, PURCHASE_ITEM.QTY_FILLED, 
                      PURCHASE_ITEM.QTY_NEEDS_FILLING, FILLS.SUB_FILL_FOR, FILLS.DRCM AS FILL_DATE, 
                      PURCHASE_ITEM.PARENT AS PURCHASE_ITEM_PARENT_ID, PURCHASE_ITEM.PROD_PRICE_LIST, PURCHASE_ITEM.CUST_LINE_ITEM, 
                      FILLS.BATCH_FILL, FILLS.BATCH_PARENT,
					  dbo.A_V_PROCEDURES_APPROVED_DATA.OBJECT_ID as ProcObjId,
					  dbo.A_V_PROCEDURES_APPROVED_DATA.REV,
					  PURCHASE_ITEM.GroupWO
FROM         dbo.A_V_PRODUCTS_APPROVED_DATA LEFT OUTER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS A_V_APPROVED_OBJECTS_1 ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.APP_OBJECT = A_V_APPROVED_OBJECTS_1.ID RIGHT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS FILL_OBJ RIGHT OUTER JOIN
                      dbo.A_FILLS FILLS LEFT OUTER JOIN
                      dbo.A_PURCHASES_HISTORY INNER JOIN
                      dbo.A_QUOTES_HISTORY INNER JOIN
                      dbo.A_ORDER_ITEMS PURCHASE_ITEM ON dbo.A_QUOTES_HISTORY.ID = PURCHASE_ITEM.QUOTE_ID ON 
                      dbo.A_PURCHASES_HISTORY.ID = PURCHASE_ITEM.PURCHASE_HIST_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUST ON dbo.A_QUOTES_HISTORY.CUSTOMER_CO = CUST.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUP ON dbo.A_QUOTES_HISTORY.SUPPLIER_ID = SUP.ID ON 
                      FILLS.PURCH_ITEM_ID = PURCHASE_ITEM.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA FILL_PERSON ON FILLS.FILLER = FILL_PERSON.ID ON FILL_OBJ.ID = FILLS.FILL_OBJ_ID ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.ID = PURCHASE_ITEM.PRODUCT_ID LEFT JOIN 
					  A_V_ACTUAL_PARTS_APPROVED_DATA parts ON FILLS.FILL_OBJ_ID = parts.ID
