
CREATE  VIEW dbo.A_V_NAV_HISTORY_WITH_NAMES
AS
SELECT     TOP 100 PERCENT dbo.A_NAV_HISTORY.DRCM, dbo.A_V_PEOPLE_DATA_QUICK.FULL_NAME, DATEDIFF(n, dbo.A_NAV_HISTORY.DRCM, GETDATE()) 
                      AS myMins, GETDATE() AS NOW_DATE, dbo.A_NAV_HISTORY.PAGE, dbo.A_NAV_HISTORY.QS
FROM         dbo.A_NAV_HISTORY INNER JOIN
                      dbo.A_V_PEOPLE_DATA_QUICK ON dbo.A_NAV_HISTORY.USER_ID = dbo.A_V_PEOPLE_DATA_QUICK.ID
ORDER BY DATEDIFF(ss, dbo.A_NAV_HISTORY.DRCM, GETDATE())

