


CREATE VIEW dbo.A_V_Z_FAVORITES_SURVEYS_ITEMS
AS
SELECT     dbo.A_PEOPLES_FAVORITE_GROUPS.ID AS GROUP_ID, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.PERSON, dbo.A_PEOPLES_FAVORITES.ID, dbo.A_SURVEYS.ID AS ITEM_ID, 
                      dbo.A_SURVEYS.SUBJECT AS NAME, dbo.A_PEOPLES_FAVORITES.NUM
FROM         dbo.A_PEOPLES_FAVORITES INNER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS ON dbo.A_PEOPLES_FAVORITES.[GROUP] = dbo.A_PEOPLES_FAVORITE_GROUPS.ID INNER JOIN
                      dbo.A_SURVEYS ON dbo.A_PEOPLES_FAVORITES.ITEM = dbo.A_SURVEYS.ID