CREATE VIEW [dbo].[A_V_DELIVERY_TICKET_PURCH_ITEM_INFO]
AS
SELECT   
dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PROD_NAME,
PURCHASE_ITEM.QTY AS PURCHASE_QTY,
PURCHASE_ITEM.PURCHASE_HIST_ID, 
dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROC_NAME,
dbo.A_V_PRODUCTS_APPROVED_DATA.HISTORY_REF_ID AS PROD_HIST_ID, 
PURCHASE_ITEM.CUST_LINE_ITEM,
 PURCHASE_ITEM.PARENT, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_TYPE_NAME, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER,
PURCHASE_ITEM.ID AS PURCH_ITEM_ID, 
dbo.A_PURCHASES_HISTORY.CUST_PURCH_NUM,
dbo.A_PURCHASES_HISTORY.OBJECT_ID AS PURCHASE_ID, 
FILLS.DONT_BILL, 
dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID AS ACTUAL_PART_ID,
dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID, 
dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.SUPPLIER_CO AS ACCT_SUPPLIER, 
dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.CUSTOMER_CO AS ACCT_CUSTOMER,
-1 AS PARENT_ID,
-1 AS ID
FROM         dbo.A_FILLS FILLS INNER JOIN
                      dbo.A_ORDER_ITEMS PURCHASE_ITEM ON FILLS.PURCH_ITEM_ID = PURCHASE_ITEM.ID INNER JOIN
                      dbo.A_PURCHASES_HISTORY ON PURCHASE_ITEM.PURCHASE_HIST_ID = dbo.A_PURCHASES_HISTORY.ID INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK ON 
                      PURCHASE_ITEM.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.ID LEFT OUTER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON FILLS.FILL_OBJ_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA INNER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID ON 
                      PURCHASE_ITEM.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID
WHERE     (PURCHASE_ITEM.PARENT IS NULL)

