CREATE VIEW dbo.A_V_TASK_WITH_ORDER_INFORMATION
AS
SELECT     T.ID, TOI.TASK_ID, TOI.FILL_ID, TOI.ACTUAL_TO_LOC, TOI.ACTUAL_FROM_LOC, T.PARENT_ID, T.DESCRIPTION, T.STATUS AS TASK_STATUS, 
                      T.SYSTEM_TASK, T.PROCEDURE_ID, T.PROCEDURE_STEP_ID, T.REQUESTOR, T.REQUESTEE_ID, T.GROUP_REQUESTEE_ID, 
                      TOI.PURCHASE_ITEM_ID, TOI.PURCHASE_HIST_ID, dbo.A_V_ORDERS_APPROVED_DATA.CUSTOMER_CO, TOI.PURCHASE_ITEM_ROLE, 
                      TOI.FILL_ITEM_ID
FROM         dbo.A_PURCHASES_HISTORY INNER JOIN
                      dbo.A_ORDER_ITEMS ON dbo.A_PURCHASES_HISTORY.ID = dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID INNER JOIN
                      dbo.A_V_ORDERS_APPROVED_DATA ON dbo.A_PURCHASES_HISTORY.ORDER_ID = dbo.A_V_ORDERS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_TASKS T INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION TOI ON T.ID = TOI.TASK_ID ON dbo.A_ORDER_ITEMS.ID = TOI.PURCHASE_ITEM_ID
