CREATE VIEW dbo.A_V_PEOPLE_WITH_EMAILS
AS
SELECT     dbo.A_EMAILS.ADDY, dbo.A_EMAILS.TYPE, dbo.A_PEOPLE_HISTORY.FULL_NAME, dbo.A_PEOPLE.ID
FROM         dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_EMAILS ON dbo.A_PEOPLE_HISTORY.OBJECT_ID = dbo.A_EMAILS.OBJECT_ID
