


CREATE VIEW dbo.A_V_JOB_DESCRIPTION_SEARCH_DATA
AS
SELECT     dbo.A_APPROVED_PROCEDURES.ID, dbo.A_APPROVED_PROCEDURES.NAME AS PROCEDURE_NAME, 
                      dbo.A_PROCEDURE_STEPS.STEP_TEXT AS DESCRIPTION, dbo.A_PROCEDURE_STEPS.ID AS STEP_NUMBER, 
                      dbo.A_APPROVED_ROLES.NAME AS ROLE_NAME, dbo.A_APPROVED_ROLES.ID AS ROLE_ID, procedureObjects.CREATING_CO, 
                      procedureObjects.LOCKED_BY, procedureObjects.STATUS, dbo.A_APPROVED_ROLES.SECURITY_LEVEL
FROM         dbo.A_PROCEDURE_STEPS INNER JOIN
                      dbo.A_PROCEDURE_OBJECT_LINK ON dbo.A_PROCEDURE_STEPS.ID = dbo.A_PROCEDURE_OBJECT_LINK.STEP_ID INNER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID = dbo.A_APPROVED_ROLES.ID INNER JOIN
                      dbo.A_OBJECTS procedureObjects ON dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID = procedureObjects.OBJ_ID RIGHT OUTER JOIN
                      dbo.A_APPROVED_PROCEDURES ON 
                      dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID = dbo.A_APPROVED_PROCEDURES.HISTORY_REF_ID
WHERE     (dbo.A_PROCEDURE_STEPS.ID IS NOT NULL)



