CREATE VIEW dbo.A_V_LOCATIONS_DROP_DOWN_DATA
AS
SELECT     o.STATUS, o.REV, o.CREATING_CO_NAME, o.CREATING_CO, dbo.A_LOCATIONS.ID, dbo.A_LOCATIONS.HISTORY_REF_ID, p.NAME, 
                      p.COMPLETE_NAME
FROM         dbo.A_OBJECTS o INNER JOIN
                      dbo.A_LOCATIONS_HISTORY p ON o.ID = p.OBJECT_ID INNER JOIN
                      dbo.A_LOCATIONS ON p.ID = dbo.A_LOCATIONS.HISTORY_REF_ID
WHERE     (o.STATUS LIKE 'APPROVED%')
