

CREATE VIEW dbo.A_V_QUOTE_HISTORY_SEARCH
AS
SELECT     dbo.A_QUOTES_HISTORY.ID, dbo.A_QUOTES_HISTORY.OBJECT_ID, dbo.A_QUOTES_HISTORY.DESCRIPTION, 
                      dbo.A_QUOTES_HISTORY.PROGRESS AS QUOTE_PROGRESS, dbo.A_QUOTES_HISTORY.ORDER_ID, 
                      CUST_PERSON.FULL_NAME AS CUST_PERSON_NAME, dbo.A_QUOTES_HISTORY.CUSTOMER_PERSON AS CUST_PERSON_ID, 
                      dbo.A_QUOTES_HISTORY.CUSTOMER_CO AS CUST_CO_ID, CUST.NAME AS CUST_CO_NAME, dbo.A_QUOTES_HISTORY.SUPPLIER_ID, 
                      SUP.NAME AS SUPPLIER_NAME, dbo.A_QUOTES_HISTORY.BUGETARY_ONLY, dbo.A_QUOTES_HISTORY.EXPIRATION_DATE, 
                      dbo.A_QUOTES_HISTORY.CREATION_DATE, dbo.A_ORDERS_HISTORY.DESCRIPTION AS ORDER_DESCRIPTION, dbo.A_OBJECTS.LOCKED_BY, 
                      dbo.A_OBJECTS.UNLOCKED_BY, dbo.A_OBJECTS.CREATED_BY, dbo.A_OBJECTS.CREATE_DATE, dbo.A_OBJECTS.ROOT, dbo.A_OBJECTS.REV_INFO,
                       dbo.A_OBJECTS.CREATING_CO, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.REV, dbo.A_OBJECTS.WFS_ID, dbo.A_OBJECTS.LOCKED_BY_NAME, 
                      dbo.A_OBJECTS.CREATING_CO_NAME, dbo.A_OBJECTS.APPROVAL_ACTIVITY, dbo.A_OBJECTS.APPROVAL_DATE, 
                      dbo.A_QUOTES_HISTORY.OBJECT_ID AS OBJ_ID
FROM         dbo.A_QUOTES_HISTORY INNER JOIN
                      dbo.A_ORDERS ON dbo.A_QUOTES_HISTORY.ORDER_ID = dbo.A_ORDERS.ID INNER JOIN
                      dbo.A_ORDERS_HISTORY ON dbo.A_ORDERS.HISTORY_REF_ID = dbo.A_ORDERS_HISTORY.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUST ON dbo.A_QUOTES_HISTORY.CUSTOMER_CO = CUST.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUP ON dbo.A_QUOTES_HISTORY.SUPPLIER_ID = SUP.ID INNER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA CUST_PERSON ON dbo.A_QUOTES_HISTORY.CUSTOMER_PERSON = CUST_PERSON.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_QUOTES_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID


