CREATE VIEW dbo.A_V_ACCOUNT_INVOICE_ITEMS_ALL_DATA
AS
SELECT     dbo.A_V_PEOPLE_APPROVED_DATA.FULL_NAME AS PURCHASER_NAME, dbo.A_V_PURCHASES_APPROVED_DATA.CUST_PURCH_NUM, 
                      dbo.A_V_PURCHASES_APPROVED_DATA.SUP_PURCH_NUM, dbo.A_V_PURCHASES_APPROVED_DATA.DATE_CREATED, 
                      dbo.A_V_PURCHASES_APPROVED_DATA.PURCHASE_STATUS, I.ID, I.INVOICE_ID, I.ACCOUNT_ID, I.PURCH_ITEM_ID, I.STATUS, I.DRCM, I.MODBY, 
                      I.AMOUNT, I.DESCRIPTION, I.DATE_INVOICED, I.AMT_PAID, I.LATE_FEES, I.TOTAL, I.PURCHASER_ID, I.DISPUTED_LINK, I.COMMENTS, 
                      I.PURCHASE_ID, I.ITEM_TYPE, I.CUSTOMER_CO, I.SUPPLIER_CO, I.QUOTE_ID, I.DATE_POSTED, dbo.A_ORDER_ITEMS.CUST_LINE_ITEM, I.FILL_ID, 
                      I.FAILED_MONITOR, CUSTOMER.NAME AS CUSTOMER_NAME, SUPPLIER.NAME AS SUPPLIER_NAME, I.TAX, I.TAX_RATE, I.QTY, I.UNIT_PRICE
FROM         dbo.A_ACCOUNT_INVOICE_ITEMS I LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK CUSTOMER ON I.CUSTOMER_CO = CUSTOMER.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK SUPPLIER ON I.SUPPLIER_CO = SUPPLIER.ID LEFT OUTER JOIN
                      dbo.A_ORDER_ITEMS ON I.PURCH_ITEM_ID = dbo.A_ORDER_ITEMS.ID LEFT OUTER JOIN
                      dbo.A_V_PURCHASES_APPROVED_DATA ON I.PURCHASE_ID = dbo.A_V_PURCHASES_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ON I.PURCHASER_ID = dbo.A_V_PEOPLE_APPROVED_DATA.ID
