CREATE VIEW dbo.A_V_A_CUSTOMER_PART_FILE_LINK
AS
SELECT     dbo.A_V_WIP_REPORT_VIEW.TASK_ID, dbo.A_V_WIP_REPORT_VIEW.CUST_ID, dbo.A_TASK_REF_FILES.FILE_ID, dbo.A_DOCUMENTS.NAME, 
                      dbo.A_V_WIP_REPORT_VIEW.CUSTOMER_NAME, dbo.A_V_WIP_REPORT_VIEW.SERIAL, dbo.A_V_WIP_REPORT_VIEW.COMPANY_PART_NUMBER, 
                      dbo.A_DOCUMENTS.SERVER_PATH
FROM         dbo.A_DOCUMENTS INNER JOIN
                      dbo.A_TASK_REF_FILES ON dbo.A_DOCUMENTS.ID = dbo.A_TASK_REF_FILES.FILE_ID INNER JOIN
                      dbo.A_V_WIP_REPORT_VIEW ON dbo.A_TASK_REF_FILES.TASK_ID = dbo.A_V_WIP_REPORT_VIEW.TASK_ID
