


CREATE VIEW dbo.A_V_ORDER_ITEM_TRAVEL_FROM
AS
SELECT     i.ID, i.PROC_SYS_ID, i.DEST, i.PARENT, i.PRODUCT_ID, p.NAME AS PROD_NAME
FROM         dbo.A_ORDER_ITEMS i INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA p ON i.PRODUCT_ID = p.ID
WHERE     (i.DEST = 'from') AND (i.PROC_SYS_ID = 'SYS_TRAVEL')



