CREATE VIEW dbo.A_V_ORDER_ITEMS_ALL_DATA
AS
SELECT     PROD.NAME AS PRODUCT_NAME, PROD.SUPPLIER_ID, SUPPLIER.NAME AS SUPPLIER_NAME, PROD.PROCEDURE_ID, 
                      [PROCEDURE].NAME AS PROC_NAME, dbo.A_OBJECTS.OBJ_DESC AS OBJ_PROD_APPLIES_TO, PROD.HISTORY_REF_ID, 
                      [PROCEDURE].VERB AS PROC_TYPE, dbo.A_ORDERS_HISTORY.OBJECT_ID AS ORDER_OBJ_ID, 
                      dbo.A_FN_ORDER_ITEM_GET_PARENT_LIST(Items.ID) AS PARENT_LIST, [PROCEDURE].SYSTEM_ID, dbo.A_OBJECTS.OBJ_TABLE, 
                      dbo.A_UNIT_TYPES.NAME AS WT_UNIT_NAME, Items.ID, Items.PARENT, Items.PARENT_QTY, Items.ORDER_ID, Items.PRODUCT_ID, 
                      Items.PROD_PRICE_LIST, Items.QUOTE_ID, Items.ADD_COST_ID, Items.TOTAL_QTY, Items.QTY, Items.UNIT_PRICE, Items.UNIT_ESTIMATE, 
                      Items.COMMENTS, CONVERT(money, Items.TOTAL_PRICE) AS TOTAL_PRICE, Items.DEST, Items.FROM_LOC, Items.TO_LOC, 
                      Items.SPECIAL_DISCOUNT, Items.SPECIAL_DISC_REASON, Items.EXPEDITE_PRODUCTION, Items.EXPEDITE_REASON, Items.FLAT_RATE, 
                      Items.EX_DESC, Items.EST_WEIGHT, Items.EST_WEIGHT_UNIT, Items.PPL_HIST_ID, Items.RECURRING, Items.RECUR_PERIOD, 
                      Items.RECUR_COUNT, Items.RECUR_START_DATE, Items.RECUR_STOP_DATE, Items.RECUR_ACCOUNT, Items.RECUR_AUTO_FILL, 
                      Items.SOURCE_ID, Items.PURCHASE_HIST_ID, Items.ACCOUNT_ID, ACCOUNT.NAME AS ACCT_NAME, [PROCEDURE].SYSTEM_ID AS PROC_SYS_ID, 
                      dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.MIN_QUANTITY, dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.CAPACITY, 
                      dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.CAPACITY_UNIT, dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.PRODUCTION_TIME, 
                      dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.PRODUCTION_TIME_UNIT, dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.UNIT AS PROD_UNIT, 
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.PRICE_LIST_TYPE, PROD.NAME + N'(' + ISNULL([PROCEDURE].OBJECT_ID, N'') 
                      + N')' AS PROD_SHOW_NAME, Items.BILL_TYPE, dbo.A_OBJECTS.ROOT AS OBJ_PROD_APPLIES_TO_ID, 
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK.UNIT, dbo.A_V_PARTS_APPROVED_DATA_QUICK.NAME, 
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK.COMPANY_PART_NUMBER, Items.DUE_DATE, Items.ORIG_DUE_DATE, Items.ACT_DUE_DATE, 
                      Items.PROD_TIME, Items.PROD_TIME_UNIT, Items.CUST_LINE_ITEM
FROM         dbo.A_OBJECTS LEFT OUTER JOIN
                      dbo.A_V_PARTS_APPROVED_DATA_QUICK ON dbo.A_OBJECTS.ID = dbo.A_V_PARTS_APPROVED_DATA_QUICK.ID RIGHT OUTER JOIN
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS RIGHT OUTER JOIN
                      dbo.A_ORDER_ITEMS Items INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUPPLIER INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA PROD ON SUPPLIER.ID = PROD.SUPPLIER_ID ON Items.PRODUCT_ID = PROD.ID INNER JOIN
                      dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA ON Items.PROD_PRICE_LIST = dbo.A_V_PROD_PRICE_LIST_APPROVED_DATA.ID ON 
                      dbo.A_PROD_PRICE_LIST_EXTRA_COSTS.ID = Items.ADD_COST_ID ON dbo.A_OBJECTS.ID = PROD.APP_OBJECT LEFT OUTER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA ACCOUNT ON Items.ACCOUNT_ID = ACCOUNT.ID LEFT OUTER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA [PROCEDURE] ON PROD.PROCEDURE_ID = [PROCEDURE].ID LEFT OUTER JOIN
                      dbo.A_QUOTES_HISTORY ON Items.QUOTE_ID = dbo.A_QUOTES_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_ORDERS_HISTORY ON Items.ORDER_ID = dbo.A_ORDERS_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_UNIT_TYPES ON Items.EST_WEIGHT_UNIT = dbo.A_UNIT_TYPES.ID
