CREATE VIEW [dbo].[A_V_ACTUAL_PARTS_APPROVED_DATA]
AS
SELECT 
	AP.ID,
	AP.HISTORY_REF_ID, 
	AP.OBJECT_ID, 
	AP.LOCATION, 
	AP.NICK_NAME, 
	AP.MERGABLE, 
	AP.PARENT_ID, 
	AP.PART_ID, 
	AP.QTY, 
	AP.SERIAL, 
    AP.CUR_OWNER, 
	AP.ASSEMBLY_WT, 
	AP.AP_STATUS, 
	AP.ROOT_ID, 
	AP.ROOT_STATUS, 
	AP.MODIFIED, 
	CAST(CASE WHEN part.COMPANY_PART_NUMBER IS NOT NULL THEN 'Customer Part # ' + part.COMPANY_PART_NUMBER + ', ' ELSE '' END +
	CASE WHEN AP.NICK_NAME IS NOT NULL THEN '(Nick: ' + AP.NICK_NAME + '), ' ELSE '' END +
	CASE WHEN AP.SERIAL IS NOT NULL THEN '(S/N:' + AP.SERIAL + '), ' ELSE '' END +
	CASE WHEN part.NAME IS NOT NULL THEN ' ' + part.NAME ELSE '' END AS VARCHAR(255)) AS SYS_NAME,
	AP.PREV_OWNER, 
    AP.SUB_PART_ACTION, 
	dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS CURRENT_OWNER_NAME,
	part.NAME AS PART_DESC, 
    part.PART_TYPE_NAME,
	loc.NAME AS LOCATION_NAME,
	CAST(CASE WHEN part.COMPANY_PART_NUMBER IS NOT NULL THEN 'Customer Part # ' + part.COMPANY_PART_NUMBER + ', ' ELSE '' END +
	CASE WHEN AP.NICK_NAME IS NOT NULL THEN '(Nick: ' + AP.NICK_NAME + '), ' ELSE '' END +
	CASE WHEN AP.SERIAL IS NOT NULL THEN '(S/N:' + AP.SERIAL + '), ' ELSE '' END +
	CASE WHEN part.NAME IS NOT NULL THEN ' ' + part.NAME ELSE '' END +
	CASE WHEN cycle.CycleCount IS NOT NULL THEN '(Cycle Count: ' + CAST(cycle.CycleCount as varchar(10)) + ') ' ELSE '' END AS VARCHAR(255)) AS NAME,
	AP.STATUS, 
    part.COMPANY_PART_NUMBER,
	AP.HAS_CHILD,
	AP.RESPONSIBLE_PERSON,
	part.OEM_PART_NUMBER,
	cycle.CycleCount AS CYCLE_COUNT
FROM         dbo.A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK AP INNER JOIN
                      dbo.A_V_PARTS_APPROVED_DATA part ON AP.PART_ID = part.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA loc ON AP.LOCATION = loc.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON AP.CUR_OWNER = dbo.A_V_COMPANIES_APPROVED_DATA.ID
OUTER APPLY (
(SELECT count(1) as CycleCount 
	FROM PartsTransactionLog p WHERE p.serialnumber = AP.SERIAL AND p.partid = part.ID) 
) cycle
WHERE     (AP.STATUS = 'APPROVED')
