



CREATE VIEW dbo.A_V_POP_FILL_SURVEY_INVITED_COMPANY
AS
SELECT     dbo.A_SURVEY_INV_COMPANY.SURVEY_ID AS S_ID, dbo.A_SURVEY_INV_COMPANY.COMPANY_ID AS C_ID, 
                      dbo.A_APPROVED_COMPANIES.NAME AS COMPANY_NAME
FROM         dbo.A_SURVEY_INV_COMPANY INNER JOIN
                      dbo.A_APPROVED_COMPANIES ON dbo.A_SURVEY_INV_COMPANY.COMPANY_ID = dbo.A_APPROVED_COMPANIES.ID




