


CREATE VIEW dbo.A_V_FILES_SEARCH_BY_SUBORDINATE
AS
SELECT     dbo.A_V_FILES_WITH_SOURCE.ID, dbo.A_V_FILES_WITH_SOURCE.NAME, dbo.A_V_FILES_WITH_SOURCE.DESCRIPTION, 
                      dbo.leadingSpaces(dbo.A_V_FILES_WITH_SOURCE.ID, 50) AS SORT_ID, dbo.A_V_FILES_WITH_SOURCE.SRC_NAME, 
                      dbo.A_PEOPLE_SUB_LOOKUP_TABLE.BOSS, dbo.A_V_FILES_WITH_SOURCE.CREATOR_ID, dbo.A_V_FILES_WITH_SOURCE.SRC_ID
FROM         dbo.A_PEOPLE_SUB_LOOKUP_TABLE RIGHT OUTER JOIN
                      dbo.A_V_FILES_WITH_SOURCE ON dbo.A_PEOPLE_SUB_LOOKUP_TABLE.SUBORDINATE = dbo.A_V_FILES_WITH_SOURCE.CREATOR_ID



