CREATE VIEW dbo.A_V_QUOTE_ITEMS_WITH_QUOTE_DATA
AS
SELECT     dbo.A_QUOTES.ID AS QUOTE_ID, dbo.A_QUOTES.HISTORY_REF_ID AS QUOTE_HIST_ID, dbo.A_ORDER_ITEMS.PROD_PRICE_LIST, 
                      dbo.A_QUOTES_HISTORY.DESCRIPTION, dbo.A_ORDER_ITEMS.ADD_COST_ID, dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID, 
                      dbo.A_ORDER_ITEMS.PPL_HIST_ID, dbo.A_QUOTES_HISTORY.PROGRESS, dbo.A_QUOTES_HISTORY.EXPIRATION_DATE, 
                      dbo.A_QUOTES_HISTORY.CREATION_DATE, dbo.A_QUOTES_HISTORY.CUSTOMER_CO, 
                      dbo.A_ORDERS_HISTORY.DESCRIPTION AS ORDER_DESCRIPTION, dbo.A_ORDERS.ID AS ORDER_ID, 
                      dbo.A_ORDERS.HISTORY_REF_ID AS ORDER_HIST_ID, dbo.A_ORDERS_HISTORY.OBJECT_ID AS ORDER_OBJ_ID, 
                      dbo.A_QUOTES_HISTORY.OBJECT_ID AS QUOTE_OBJ_ID, dbo.A_OBJECTS.STATUS
FROM         dbo.A_QUOTES_HISTORY INNER JOIN
                      dbo.A_QUOTES ON dbo.A_QUOTES_HISTORY.ID = dbo.A_QUOTES.HISTORY_REF_ID INNER JOIN
                      dbo.A_ORDER_ITEMS ON dbo.A_QUOTES_HISTORY.ID = dbo.A_ORDER_ITEMS.QUOTE_ID INNER JOIN
                      dbo.A_ORDERS INNER JOIN
                      dbo.A_ORDERS_HISTORY ON dbo.A_ORDERS.HISTORY_REF_ID = dbo.A_ORDERS_HISTORY.ID INNER JOIN
                      dbo.A_QUOTE_ORDER_LINK ON dbo.A_ORDERS.ID = dbo.A_QUOTE_ORDER_LINK.ORDER_ID ON 
                      dbo.A_QUOTES_HISTORY.ID = dbo.A_QUOTE_ORDER_LINK.QUOTE_ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_ORDERS_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID
WHERE     (dbo.A_ORDER_ITEMS.ADD_COST_ID IS NULL) AND (dbo.A_ORDER_ITEMS.PURCHASE_HIST_ID IS NULL)
