CREATE VIEW dbo.A_V_PEOPLE_DATA_QUICK
AS
SELECT     dbo.A_PEOPLE.ID, dbo.A_PEOPLE.HISTORY_REF_ID, dbo.A_PEOPLE_HISTORY.NAME, dbo.A_PEOPLE_HISTORY.LAST_NAME, 
                      dbo.A_PEOPLE_HISTORY.MIDDLE_NAME, dbo.A_PEOPLE_HISTORY.COMPANY, dbo.A_PEOPLE_HISTORY.TIME_ZONE, 
                      dbo.A_PEOPLE_HISTORY.FULL_NAME, dbo.A_PEOPLE_HISTORY.SYSTEM_STATUS, dbo.A_PEOPLE_HISTORY.CO_POSITION, 
                      dbo.A_PEOPLE_HISTORY.ROOT_COMPANY, dbo.A_PEOPLE_HISTORY.TOOL_BOX, dbo.A_PEOPLE_HISTORY.INFO_BOX, 
                      dbo.A_PEOPLE_HISTORY.ADV_SEARCH, dbo.A_PEOPLE_HISTORY.COLOR_KEY, dbo.A_PEOPLE_HISTORY.LOGIN
FROM         dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID
