
CREATE  VIEW dbo.A_V_PRODUCTS_FOR_PURCHASING_DATA
AS
SELECT     PROD.ID, PROD_HIST.NAME AS PRODUCT_NAME, PROD_HIST.SUPPLIER_ID, PPL_CUST.CUST_ID AS CUSTOMER_ID, 
                      SUP_CO.NAME AS SUPPLIER_NAME, PPL_H.UNIT_PRICE, PROD_HIST.CUSTOMIZABLE, PPL_H.UNIT, PPL_H.MIN_QUANTITY, 
                      PPL_H.EST_UNIT_PRICE, PPL_H.EST_LABOR_PRICE, PPL_H.EST_PARTS_PROV_STAY, PPL_H.EST_PARTS_PROV_TAKE_BACK, 
                      PPL_H.EST_PARTS_CONSUMED, PPL_H.PRODUCTION_TIME, PPL_H.PRODUCTION_TIME_UNIT, PPL_H.CAPACITY, PPL_H.CAPACITY_UNIT, 
                      PPL_H.CUSTOMER_NAME, PROD_HIST.SALES_TAX, PROD_HIST.REQ_FORM, PROD_HIST.CUST_MGR_ROLE, PROD_HIST.PROCEDURE_ID, 
                      [PROC].SYSTEM_ID AS PROC_SYS_ID, [PROC].NAME AS PROC_NAME, PPL.ID AS PRICE_LIST_ID, CUSTOMER.NAME AS CUST_NAME, PROD.STATUS, 
                      SUP_CO.ROOT_CO AS SUP_ROOT_CO, A_V_COMPANIES_APPROVED_DATA_1.NAME AS SUP_ROOT_CO_NAME, PPL_H.FOR_INDIVIDUAL_SALE, 
                      PPL.STATUS AS PPL_STAT, dbo.A_V_APPROVED_OBJECTS.ID AS APP_OBJ_ID, ISNULL(dbo.A_PARTS_HISTORY.NAME + N' ', N'') 
                      + ISNULL(N'(' + dbo.A_PARTS_HISTORY.COMPANY_PART_NUMBER + N') ', N'') AS APP_OBJ_PART_DESC, dbo.A_V_APPROVED_OBJECTS.OBJ_DESC,
                       PROD_HIST.AVAILABILITY, PROD_HIST.OBJECT_ID AS OBJ_ID, PROD_HIST.OEM, PROD_HIST.MODEL, PROD_HIST.AREA, PROD_HIST.CU, 
                      PROD_HIST.MM
FROM         dbo.A_PRODUCTS PROD INNER JOIN
                      dbo.A_PRODUCTS_HISTORY PROD_HIST ON PROD.HISTORY_REF_ID = PROD_HIST.ID INNER JOIN
                      dbo.A_PROD_PRICE_LIST_HISTORY PPL_H ON PROD.ID = PPL_H.PRODUCT INNER JOIN
                      dbo.A_PROD_PRICE_LIST PPL ON PPL_H.ID = PPL.HISTORY_REF_ID INNER JOIN
                      dbo.A_PROD_PRICE_LIST_REAL_CUSTOMERS PPL_CUST ON PPL_H.ID = PPL_CUST.PP_LIST_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA SUP_CO ON PROD_HIST.SUPPLIER_ID = SUP_CO.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA CUSTOMER ON PPL_CUST.CUST_ID = CUSTOMER.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      SUP_CO.ROOT_CO = A_V_COMPANIES_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON PROD_HIST.APP_OBJECT = dbo.A_V_APPROVED_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_PARTS_HISTORY ON dbo.A_V_APPROVED_OBJECTS.OBJ_ID = dbo.A_PARTS_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA [PROC] ON PROD_HIST.PROCEDURE_ID = [PROC].ID
WHERE     (PROD.STATUS = 'APPROVED') AND (PPL.STATUS = 'APPROVED')

