
CREATE VIEW dbo.A_V_THEORY_HEADER_WITH_REF_THEORY
AS
SELECT     dbo.A_OBJECTS.OBJ_DESC AS THEORY_NAME, dbo.A_OBJECTS.ID AS LINKED_THEORY_OBJ_ID, 
                      dbo.A_THEORY_HISTORY.ID AS THEORY_HIST_ID, dbo.A_THEORY_REFERENCE_THEORY.THEORY_ID, 
                      dbo.A_THEORY_REFERENCE_THEORY.THEORY_LINK, dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ROOT, 
                      dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ID AS MAX_ID
FROM         dbo.A_THEORY_REFERENCE_THEORY INNER JOIN
                      dbo.A_THEORY_HISTORY ON dbo.A_THEORY_REFERENCE_THEORY.THEORY_ID = dbo.A_THEORY_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ID = dbo.A_OBJECTS.ID ON 
                      dbo.A_THEORY_REFERENCE_THEORY.THEORY_LINK = dbo.A_V_OBJECTS_MAX_ID_WITH_ROOT.ROOT

