CREATE VIEW [dbo].[A_V_PRODUCT_SEARCH_DATA]
AS

SELECT PH.ID
	, PH.[OBJECT_ID]
	, PH.PARENT_ID, PH.[NAME]
	--, PQP.CUST_ID AS CUSTOMERID
	, PQP_BASE.CUST_ID AS CUSTOMERID
	, PH.SUPPLIER_ID
	, CAD.[NAME] AS SUPPLIER_NAME
	, PH.COMMENTS
	, PH.PROCEDURE_ID
	, PAD.VERB
	, PAD.VERB_NAME
	, PH.APP_OBJECT
	, AO.OBJ_DESC AS APP_OBJ_NAME
	, PH.SHIP_OR_LABOR
	, PH.CUSTOMIZABLE
	, PH.REQ_FORM
	, PH.MGR_TEAM
	, AR.[NAME] AS MGR_TEAM_NAME
	, PH.SALES_TAX
	, PAD.[NAME] AS [PROCEDURE_NAME]
	, O.ID AS OBJ_ID
	, O.LOCKED_BY
	, O.UNLOCKED_BY
	, O.CREATED_BY
	, O.CREATE_DATE
	, O.[ROOT]
	, O.REV_INFO
	, O.CREATING_CO
	, O.[STATUS]
	, O.REV
	, O.WFS_ID
	, O.LOCKED_BY_NAME
	, O.CREATING_CO_NAME
	, O.APPROVAL_ACTIVITY
	, DBO.A_FN_PRODUCT_WHERE_USED_CHECK(PH.ID) AS HAS_USAGE
	, PH.CUST_MGR_ROLE
	, PH.CUSTOMERREQUIREMENTID
	, PH.MATERIALCOST
	, PH.TOTALSALEPRICE
	, PH.ISPRODUCT
	, PH.DIVISION
	, PH.LOCATIONID
	, PH.CYCLETIME
FROM DBO.A_OBJECTS O
INNER JOIN DBO.A_PRODUCTS_HISTORY PH ON O.ID = PH.[OBJECT_ID]
LEFT OUTER JOIN DBO.A_APPROVED_ROLES AR ON PH.MGR_TEAM = AR.ID
LEFT OUTER JOIN DBO.A_V_APPROVED_OBJECTS AO ON PH.APP_OBJECT = AO.ID
LEFT OUTER JOIN DBO.A_V_COMPANIES_APPROVED_DATA CAD ON PH.SUPPLIER_ID = CAD.ID
LEFT OUTER JOIN DBO.A_V_PROCEDURES_APPROVED_DATA PAD ON PH.PROCEDURE_ID = PAD.ID
--LEFT OUTER JOIN DBO.A_PRODUCTS_QUICK_PRICE PQP ON PH.ID = PQP.PROD_HIST_ID
LEFT OUTER JOIN DBO.A_OBJECTS O_BASE ON O_BASE.ID = O.[ROOT]
LEFT OUTER JOIN DBO.A_PRODUCTS_QUICK_PRICE PQP_BASE ON O_BASE.OBJ_ID = PQP_BASE.PROD_HIST_ID



