CREATE VIEW [dbo].[A_V_PROCEDURE_STEPS]
AS
SELECT     s.ID, s.PROCEDURE_ID, s.STEP_TEXT, s.START_ON_COUNTER, s.COUNTER_VALUE, s.REL_OR_ABS, s.COUNTER_UNIT, s.FROM_START_OR_STOP, 
                      s.SYSTEM_TASK, s.DESTINATION, s.SPECIFIC_LOCATION, s.REFERENCE_VERB, s.REFERENCE_OBJECT, s.COMMENTS, s.GOTO_STEP, 
                      s.GOTO_STEP_ID, s.CYCLES, s.CYCLE_ON_COUNTER, s.CYCLE_COUNT, s.CYCLE_UNIT, s.DRCM, s.MODBY, s.PRINT_ORDER, 
                      dbo.A_FN_PROCEDURE_STEPS_MAKE_PRECEDING_LIST(s.ID) AS PRE_STEP, s.DURATION, s.DURATION_TYPE, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA.COMPLETE_NAME AS SPEC_LOC_NAME, dbo.A_DURATION_TYPES.NAME AS DURATION_TYPE_NAME, 
                      dbo.A_DURATION_TYPES.SECS,s.TITLE
FROM         dbo.A_PROCEDURE_STEPS s LEFT OUTER JOIN
                      dbo.A_DURATION_TYPES ON s.DURATION_TYPE = dbo.A_DURATION_TYPES.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA ON s.SPECIFIC_LOCATION = dbo.A_V_LOCATIONS_APPROVED_DATA.ID


