CREATE VIEW dbo.A_V_PROCEDURE_STEPS_WITH_PROC_DATA
AS
SELECT     dbo.A_PROCEDURE_STEPS.ID AS STEP_ID, dbo.A_PROCEDURE_STEPS.STEP_TEXT, dbo.A_PROCEDURE_STEPS.SYSTEM_TASK, 
                      dbo.A_OBJECTS.CREATING_CO, dbo.A_PROCEDURES_HISTORY.ID AS PROC_HIST_ID
FROM         dbo.A_PROCEDURE_STEPS INNER JOIN
                      dbo.A_PROCEDURES_HISTORY ON dbo.A_PROCEDURE_STEPS.PROCEDURE_ID = dbo.A_PROCEDURES_HISTORY.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_PROCEDURES_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID
