


CREATE VIEW dbo.A_V_Z_FAVORITES_SERVICE_CALLS_ITEMS
AS
SELECT     dbo.A_PEOPLES_FAVORITE_GROUPS.ID AS GROUP_ID, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.PERSON, dbo.A_PEOPLES_FAVORITES.ID, dbo.A_PEOPLES_FAVORITES.NUM, 
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID AS ITEM_ID, dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.MACHINE_NAME AS NAME
FROM         dbo.A_PEOPLES_FAVORITES INNER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS ON dbo.A_PEOPLES_FAVORITES.[GROUP] = dbo.A_PEOPLES_FAVORITE_GROUPS.ID INNER JOIN
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS ON dbo.A_PEOPLES_FAVORITES.ITEM = dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID



