CREATE VIEW dbo.A_V_PART_DATA_BY_APPROVED_DATA
AS
SELECT     dbo.A_PARTS.ID, dbo.A_PARTS.PARTS_HISTORY_ID, dbo.A_PARTS_HISTORY.UNIT, dbo.A_PARTS_HISTORY.COMPANY_PART_NUMBER, 
                      dbo.A_PARTS_HISTORY.NAME, dbo.A_PARTS_HISTORY.PART_TYPE, dbo.A_PARTS_HISTORY.SPARE, dbo.A_PARTS_HISTORY.CONSUMABLE, 
                      dbo.A_PARTS_HISTORY.TRACK_FROM_START, dbo.A_PARTS_HISTORY.DRCM, dbo.A_PARTS_HISTORY.MODBY, dbo.A_PARTS_HISTORY.COMPANY, 
                      dbo.A_PARTS_HISTORY.OBJECT_ID, dbo.A_PARTS_HISTORY.PART_TYPE_NAME, dbo.A_PARTS_HISTORY.UNIT_SHIPPING_WEIGHT, 
                      dbo.A_OBJECTS.CREATING_CO, dbo.A_PARTS_HISTORY.WEIGHT_TYPE, dbo.A_PARTS_HISTORY.CUSTOMER_SEE_AVAILABILITY, 
                      dbo.A_PARTS_HISTORY.SUPPLIER_SEE_AVAILABILITY, dbo.A_PARTS_HISTORY.SUPPLIER_SEE_INSTALL_BASE, 
                      A_V_COMPANIES_APPROVED_DATA_1.NAME AS ROOT_CO_NAME, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS COMPANY_NAME, 
                      dbo.A_UNIT_TYPES.NAME AS WT_TYPE_NAME, dbo.A_OBJECTS.STATUS
FROM         dbo.A_PARTS INNER JOIN
                      dbo.A_PARTS_HISTORY ON dbo.A_PARTS.PARTS_HISTORY_ID = dbo.A_PARTS_HISTORY.ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_PARTS_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_PARTS_HISTORY.COMPANY = dbo.A_V_COMPANIES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA A_V_COMPANIES_APPROVED_DATA_1 ON 
                      dbo.A_V_COMPANIES_APPROVED_DATA.ROOT_CO = A_V_COMPANIES_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_UNIT_TYPES ON dbo.A_PARTS_HISTORY.WEIGHT_TYPE = dbo.A_UNIT_TYPES.ID
