CREATE VIEW dbo.A_V_PROCEDURES_SELECT_SEARCH
AS
SELECT     dbo.leadingSpaces(o.ROOT, 30) AS SPECIAL_ROOT, dbo.leadingSpaces(ph.ID, 30) AS SPECIAL_ID, ph.ID, ph.OBJECT_ID, ph.VERB, ph.NAME, 
                      dbo.A_APPROVED_VERBS.NAME AS VERB_NAME, o.ID AS OBJ_ID, ph.CREATING_DEPT, 
                      dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS DEPT_NAME, dbo.A_SECURITY_LEVELS.NAME AS SECURITY_NAME, ph.IS_SYSTEM, 
                      ph.SECURITY_LEVEL, o.CREATING_CO, o.STATUS, o.ROOT, o.LOCKED_BY, o.CREATING_CO_NAME, dbo.A_APPROVED_VERBS.VERB_TYPE_NAME, 
                      dbo.A_APPROVED_VERBS.VERB_TYPE
FROM         dbo.A_PROCEDURES_HISTORY ph INNER JOIN
                      dbo.A_OBJECTS o ON ph.OBJECT_ID = o.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON ph.CREATING_DEPT = dbo.A_V_COMPANIES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_SECURITY_LEVELS ON ph.SECURITY_LEVEL = dbo.A_SECURITY_LEVELS.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_VERBS ON ph.VERB = dbo.A_APPROVED_VERBS.ID
