



CREATE VIEW dbo.A_V_FILES_WITH_SOURCE
AS
SELECT     DOC.ID, DOC.NAME, DOC.SOURCE_ID, DOC.DESCRIPTION, DOC.ACTIVE, SOURCE.NAME AS SRC_NAME, SOURCE.ID AS SRC_ID, 
                      SOURCE.DESCRIPTION AS SRC_DESCRIPTION, DOC.CREATOR_ID
FROM         dbo.A_DOCUMENTS DOC LEFT OUTER JOIN
                      dbo.A_DOCUMENTS SOURCE ON DOC.SOURCE_ID = SOURCE.ID AND DOC.SOURCE_ID = SOURCE.ID




