CREATE VIEW dbo.A_V_TASK_SEARCH_STREAM_LINED
AS
SELECT     TASK.DESCRIPTION, TASK.STATUS, TASK.REQUESTOR, TASK.CHILD_ORDER, TASK.CREATED_BY, TASK.CREATE_DATE, dbo.leadingSpaces(TASK.ID, 
                      50) AS SORT_ID, TASK.SYSTEM_TASK, TASK.PROCEDURE_ID, REQUESTOR.P_NAME AS REQUESTOR_NAME, TASK.REQUESTEE_ID, 
                      TASK.GROUP_REQUESTEE_ID, TASK.ORIG_PLANNED_START_DATE, TASK.ORIG_PLANNED_STOP_DATE, TASK.CUR_PLANNED_START_DATE, 
                      TASK.CUR_PLANNED_STOP_DATE, TASK.ACTUAL_START_DATE, TASK.ACTUAL_STOP_DATE, TASK.CUR_PLANNED_COUNTER_START, 
                      TASK.LATEST_REQUESTEE_NAME, TASK.HAS_DISCUSSION, TASK.HAS_SURVEY, TASK.HAS_CHILD, TASK.HAS_REF_PROC, TASK.HAS_FILE, 
                      TASK.ORIG_REQUESTOR_ID, TASK.HAS_REF_OBJ, TASK.HAS_MONITOR, ORIG_REQUESTOR.FULL_NAME AS ORIG_REQUESTOR_NAME, 
                      TASK.COLOR_CODE, TASK.LAST_REQUEST_DATE, dbo.getTaskParentList(TASK.ID) AS PARENT_LIST, TASK.PARENT_ID, dbo.isParentTask(TASK.ID) 
                      AS isParent, TASK.PRIORITY, dbo.A_TASK_PRIORITY_LEVELS.NAME AS PRIORITY_NAME, 
                      dbo.A_TASK_COMPANIES_TO_VIEW_LINK.CO_ID AS ALLOWED_CO_ID, TASK_CO.COMPANY_NAME, TASK.ID, TASK.CHILD_STATUS, 
                      TASK.PROCEDURE_STEP_ID, T_EMAIL_LINK.PERSON_ID AS SPECIFIED_PERSON_ID, dbo.A_TASK_COMMENT.COMMENT AS LAST_COMMENT, 
                      dbo.A_TASK_COMMENT.DRCM AS LAST_COMMENT_DRCM, TASK.IS_QUOTE, TASK.IS_QUOTE_ACCEPT, TASK.IS_FILL, 
                      TASK_CO.COMPANY_ID AS CO_ID, dbo.A_TASK_ORDER_INFORMATION.PURCHASE_HIST_ID, 
                      dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ID, dbo.A_TASK_ORDER_INFORMATION.FILL_ID, 
                      dbo.A_TASK_ORDER_INFORMATION.PURCHASE_ITEM_ROLE, TASK.RECURSION_NUMBER, ASSIGNEE.FULL_NAME AS ASSIGNEE_NAME, 
                      ASSIGNEE.SYSTEM_STATUS AS ASSIGNEE_STATUS, dbo.A_PEOPLE_SEARCH_TABLE.NAME AS LAST_COMMENT_WRITER, 
                      dbo.A_TASK_PROCEDURE_ASSIGNEE.ASSIGNEE_ID
FROM         dbo.A_PEOPLE_SEARCH_TABLE INNER JOIN
                      dbo.A_TASK_LAST_COMMENT INNER JOIN
                      dbo.A_TASK_COMMENT ON dbo.A_TASK_LAST_COMMENT.COMMENT_ID = dbo.A_TASK_COMMENT.ID ON 
                      dbo.A_PEOPLE_SEARCH_TABLE.ID = dbo.A_TASK_COMMENT.WRITER RIGHT OUTER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE ASSIGNEE INNER JOIN
                      dbo.A_TASK_PROCEDURE_ASSIGNEE ON ASSIGNEE.ID = dbo.A_TASK_PROCEDURE_ASSIGNEE.ASSIGNEE_ID RIGHT OUTER JOIN
                      dbo.A_TASKS TASK ON dbo.A_TASK_PROCEDURE_ASSIGNEE.TASK_ID = TASK.ID LEFT OUTER JOIN
                      dbo.A_TASK_ORDER_INFORMATION ON TASK.ID = dbo.A_TASK_ORDER_INFORMATION.TASK_ID ON 
                      dbo.A_TASK_LAST_COMMENT.TASK_ID = TASK.ID LEFT OUTER JOIN
                      dbo.A_TASK_EMAIL_PEOPLE_LINK T_EMAIL_LINK ON TASK.ID = T_EMAIL_LINK.TASK_ID LEFT OUTER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE TASK_CO ON TASK.REQUESTEE_ID = TASK_CO.ID LEFT OUTER JOIN
                      dbo.A_TASK_COMPANIES_TO_VIEW_LINK ON TASK.ID = dbo.A_TASK_COMPANIES_TO_VIEW_LINK.TASK_ID LEFT OUTER JOIN
                      dbo.A_TASK_PRIORITY_LEVELS ON TASK.PRIORITY = dbo.A_TASK_PRIORITY_LEVELS.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA ORIG_REQUESTOR ON TASK.ORIG_REQUESTOR_ID = ORIG_REQUESTOR.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN REQUESTOR ON TASK.REQUESTOR = REQUESTOR.P_ID
