CREATE VIEW dbo.A_V_PRODUCTS_APPROVED_SELECT_DATA
AS
SELECT     dbo.A_PRODUCTS_HISTORY.OBJECT_ID, dbo.A_PRODUCTS_HISTORY.PARENT_ID, dbo.A_PRODUCTS_HISTORY.NAME, 
                      dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID, dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS SUPPLIER_NAME, 
                      dbo.A_PRODUCTS_HISTORY.COMMENTS, dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID, dbo.A_V_PROCEDURES_APPROVED_DATA.VERB, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.VERB_NAME, dbo.A_PRODUCTS_HISTORY.APP_OBJECT, 
                      dbo.A_V_APPROVED_OBJECTS.OBJ_DESC AS APP_OBJ_NAME, dbo.A_PRODUCTS_HISTORY.SHIP_OR_LABOR, 
                      dbo.A_PRODUCTS_HISTORY.CUSTOMIZABLE, dbo.A_PRODUCTS_HISTORY.REQ_FORM, dbo.A_PRODUCTS_HISTORY.MGR_TEAM, 
                      dbo.A_APPROVED_ROLES.NAME AS MGR_TEAM_NAME, dbo.A_PRODUCTS_HISTORY.SALES_TAX, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROCEDURE_NAME, dbo.A_PRODUCTS.ID, dbo.A_PRODUCTS.HISTORY_REF_ID, 
                      dbo.A_OBJECTS.CREATING_CO_NAME, dbo.A_OBJECTS.CREATING_CO, dbo.A_PRODUCTS_HISTORY.CUST_MGR_ROLE, dbo.A_PRODUCTS.STATUS, 
                      dbo.A_PRODUCTS_HISTORY.PERSON_SUPPLIER, dbo.A_PRODUCTS_HISTORY.AVAILABILITY, 
                      dbo.A_PRODUCTS_HISTORY.SYSTEM_PROCEDURE,
					  dbo.A_PRODUCTS_HISTORY.CustomerRequirementId
FROM         dbo.A_PRODUCTS_HISTORY INNER JOIN
                      dbo.A_PRODUCTS ON dbo.A_PRODUCTS_HISTORY.ID = dbo.A_PRODUCTS.HISTORY_REF_ID INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_PRODUCTS_HISTORY.OBJECT_ID = dbo.A_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_APPROVED_ROLES ON dbo.A_PRODUCTS_HISTORY.MGR_TEAM = dbo.A_APPROVED_ROLES.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_PRODUCTS_HISTORY.APP_OBJECT = dbo.A_V_APPROVED_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON 
                      dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID
WHERE     (dbo.A_PRODUCTS.STATUS = 'APPROVED')
