


CREATE VIEW dbo.A_V_MEETING_GET_AGENDA
AS
SELECT     I.ID AS A_ID, I.TEXT, I.FACILITATOR, I.START_DATE, I.DURATION, I.ITEM, I.ROOT AS M_ID, I.PARENT, I.AUTHOR, I.DRCM, dbo.A_MEETINGS.SCRIBE, 
                      dbo.A_MEETINGS.HOST, I.MODBY, I.RELATED_ITEM, HOST.P_NAME AS HOST_NAME, 
                      A_V_PEOPLE_BY_NTLOGIN_1.P_NAME AS FACILITATOR_NAME,
                          (SELECT     TOP 1 DOC_ID
                            FROM          A_MEETING_AGENDA_ITEM_DOC_LINK
                            WHERE      AGENDA_ID = I.ID) AS HAS_DOC, dbo.A_MEETINGS.MEETING_NAME
FROM         dbo.A_V_PEOPLE_BY_NTLOGIN A_V_PEOPLE_BY_NTLOGIN_1 RIGHT OUTER JOIN
                      dbo.A_MEETING_AGENDA_ITEMS I ON A_V_PEOPLE_BY_NTLOGIN_1.P_ID = I.FACILITATOR LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN HOST INNER JOIN
                      dbo.A_MEETINGS ON HOST.P_ID = dbo.A_MEETINGS.HOST ON I.ROOT = dbo.A_MEETINGS.ID



