CREATE VIEW dbo.A_V_ORDER_ITEMS_DATA_WITH_SHIPPING
AS
SELECT     TRAVEL_FROM.ID AS TRAV_FROM_ID, TRAVEL_FROM.PROD_NAME AS TRAV_FROM_NAME, SHIP_TO.ID AS SHIP_TO_ID, SHIP_TO.PROD_NAME AS SHIP_TO_NAME, 
                      TRAVEL_TO.ID AS TRAV_TO_ID, TRAVEL_TO.PROD_NAME AS TRAV_TO_NAME, SHIP_FROM.ID AS SHIP_FROM_ID, SHIP_FROM.PROD_NAME AS SHIP_FROM_NAME, 
                      dbo.A_FN_ORDER_ITEM_GET_PRECEDENT_LIST(O.ID) AS PREC, ISNULL(oO.LOCKED_BY, '') + ISNULL(qO.LOCKED_BY, '') AS LOCKED_BY, ISNULL(oO.STATUS, '') 
                      + ISNULL(qO.STATUS, '') AS STATUS, TO_LOC.COMPLETE_NAME AS TO_LOC_NAME, FROM_LOC.COMPLETE_NAME AS FROM_LOC_NAME, O.PRODUCT_NAME, 
                      O.SUPPLIER_ID, O.SUPPLIER_NAME, O.PROCEDURE_ID, O.PROC_NAME, O.OBJ_PROD_APPLIES_TO, O.HISTORY_REF_ID, O.PROC_TYPE, O.ORDER_OBJ_ID, 
                      O.PARENT_LIST, O.SYSTEM_ID, O.OBJ_TABLE, O.WT_UNIT_NAME, O.ID, O.PARENT, O.PARENT_QTY, O.ORDER_ID, O.PRODUCT_ID, O.PROD_PRICE_LIST, 
                      O.QUOTE_ID, O.ADD_COST_ID, O.TOTAL_QTY, O.QTY, O.UNIT_PRICE, O.UNIT_ESTIMATE, O.COMMENTS, O.TOTAL_PRICE, O.DEST, O.FROM_LOC, O.TO_LOC, 
                      O.SPECIAL_DISCOUNT, O.SPECIAL_DISC_REASON, O.EXPEDITE_PRODUCTION, O.EXPEDITE_REASON, O.FLAT_RATE, O.EX_DESC, O.EST_WEIGHT, 
                      O.EST_WEIGHT_UNIT, O.PPL_HIST_ID, O.RECURRING, O.RECUR_PERIOD, O.RECUR_COUNT, O.RECUR_START_DATE, O.RECUR_STOP_DATE, O.RECUR_ACCOUNT, 
                      O.RECUR_AUTO_FILL, O.SOURCE_ID, O.PURCHASE_HIST_ID, O.ACCOUNT_ID, O.ACCT_NAME, O.PROC_SYS_ID, O.MIN_QUANTITY, O.CAPACITY, O.CAPACITY_UNIT, 
                      O.PRODUCTION_TIME, O.PRODUCTION_TIME_UNIT, O.PROD_UNIT, O.PRICE_LIST_TYPE, O.PROD_SHOW_NAME, O.BILL_TYPE, O.OBJ_PROD_APPLIES_TO_ID, 
                      O.UNIT, O.NAME, O.COMPANY_PART_NUMBER, O.DUE_DATE, O.ORIG_DUE_DATE, O.ACT_DUE_DATE, O.PROD_TIME, O.PROD_TIME_UNIT, O.CUST_LINE_ITEM, 
                      dbo.A_V_APPROVED_OBJECTS.OBJ_DESC AS APP_OBJ_DESC,
                          (SELECT     NAME
                            FROM          dbo.A_V_COMPANIES_APPROVED_DATA_QUICK
                            WHERE      (ID = dbo.A_V_COMPANIES_APPROVED_DATA.ROOT_CO)) AS SUPPLIER_ROOT_CO_NAME
FROM         dbo.A_V_ORDER_ITEMS_ALL_DATA AS O INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON O.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON O.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_V_PRODUCTS_APPROVED_DATA.APP_OBJECT = dbo.A_V_APPROVED_OBJECTS.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA AS FROM_LOC ON O.FROM_LOC = FROM_LOC.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA AS TO_LOC ON O.TO_LOC = TO_LOC.ID LEFT OUTER JOIN
                      dbo.A_QUOTES_HISTORY INNER JOIN
                      dbo.A_OBJECTS AS qO ON dbo.A_QUOTES_HISTORY.OBJECT_ID = qO.ID ON O.QUOTE_ID = dbo.A_QUOTES_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_OBJECTS AS oO INNER JOIN
                      dbo.A_ORDERS_HISTORY ON oO.ID = dbo.A_ORDERS_HISTORY.OBJECT_ID ON O.ORDER_ID = dbo.A_ORDERS_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_V_ORDER_ITEM_TRAVEL_FROM AS TRAVEL_FROM ON O.ID = TRAVEL_FROM.PARENT LEFT OUTER JOIN
                      dbo.A_V_ORDER_ITEM_SHIPPING AS SHIP_TO ON O.ID = SHIP_TO.PARENT LEFT OUTER JOIN
                      dbo.A_V_ORDER_ITEM_SHIPPING_FROM AS SHIP_FROM ON O.ID = SHIP_FROM.PARENT LEFT OUTER JOIN
                      dbo.A_V_ORDER_ITEM_TRAVEL_FROM AS TRAVEL_TO ON O.ID = TRAVEL_TO.PARENT
