


CREATE VIEW dbo.A_V_SURVEY_WITH_AUTHOR_NAMES
AS
SELECT     dbo.A_SURVEY_REPLIES.ID AS R_ID, dbo.A_SURVEY_REPLIES.TEXT, dbo.A_SURVEY_REPLIES.ROOT, dbo.A_SURVEY_REPLIES.PARENT, 
                      dbo.A_SURVEY_REPLIES.AUTHOR, dbo.A_APRROVED_PEOPLE.FULL_NAME AS AUTHOR_NAME, dbo.A_SURVEY_REPLIES.DRCM, 
                      dbo.A_SURVEY_ATTACHMENTS.DOC_ID, dbo.A_SURVEY_REPLIES.COLOR
FROM         dbo.A_SURVEY_REPLIES INNER JOIN
                      dbo.A_APRROVED_PEOPLE ON dbo.A_SURVEY_REPLIES.AUTHOR = dbo.A_APRROVED_PEOPLE.ID LEFT OUTER JOIN
                      dbo.A_SURVEY_ATTACHMENTS ON dbo.A_SURVEY_REPLIES.ID = dbo.A_SURVEY_ATTACHMENTS.RESPONSE_ID



