




CREATE VIEW dbo.A_V_WF_PENDING_APPROVALS_WITH_STARTER_AND_INITER
AS
SELECT     dbo.A_WORKFLOWS_STARTED.STARTED_BY, dbo.A_WORKFLOW_GROUP_STARTED.WFS_ID, 
                      dbo.A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS.PERSON, dbo.A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS.WFGS_ID
FROM         dbo.A_WORKFLOWS_STARTED INNER JOIN
                      dbo.A_WORKFLOW_GROUP_STARTED ON dbo.A_WORKFLOWS_STARTED.ID = dbo.A_WORKFLOW_GROUP_STARTED.WFS_ID INNER JOIN
                      dbo.A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS ON 
                      dbo.A_WORKFLOW_GROUP_STARTED.ID = dbo.A_WF_GROUP_PEOPLE_WITH_PENDING_APPROVALS.WFGS_ID





