CREATE VIEW dbo.A_V_PARTS_SAFETY_STOCK_ROLES
AS
SELECT     dbo.A_PARTS_SAFETY_STOCK_ROLES.SAFETY_STOCK_ID, dbo.A_V_ROLES_APPROVED_DATA_QUICK.NAME AS ROLE_NAME, 
                      dbo.A_PARTS_SAFETY_STOCK_ROLES.ROLE_ID, dbo.A_PARTS_SAFETY_STOCK_ROLES.EMAIL_TYPE, 
                      dbo.A_PARTS_SAFETY_STOCK_LEVELS.PART_ID
FROM         dbo.A_PARTS_SAFETY_STOCK_LEVELS INNER JOIN
                      dbo.A_PARTS_SAFETY_STOCK_ROLES ON 
                      dbo.A_PARTS_SAFETY_STOCK_LEVELS.ID = dbo.A_PARTS_SAFETY_STOCK_ROLES.SAFETY_STOCK_ID INNER JOIN
                      dbo.A_V_ROLES_APPROVED_DATA_QUICK ON dbo.A_PARTS_SAFETY_STOCK_ROLES.ROLE_ID = dbo.A_V_ROLES_APPROVED_DATA_QUICK.ID
