CREATE VIEW A_V_PROCEDURES_APPROVED_DATA_DROP_DOWN AS
--This view is for the drop down page on products
SELECT NAME + ' [ID:' + ID + ']' AS SHOWNAME
	  ,[ID]
      ,[HISTORY_REF_ID]
      ,[OBJECT_ID]
      ,[VERB]
      ,[NAME]
      ,[COMMENTS]
      ,[SECURITY_LEVEL]
      ,[STEPS_IN_AP]
      ,[WIP_MSG]
      ,[DRCM]
      ,[MODBY]
      ,[VERB_NAME]
      ,[SYSTEM_ID]
      ,[CREATING_DEPT]
      ,[IS_SYSTEM]
      ,[CREATING_CO]
      ,[STATUS]
      ,[DURATION]
      ,[DURATION_TYPE]
  FROM [dbo].[A_V_PROCEDURES_APPROVED_DATA]
