



CREATE VIEW dbo.A_V_TASK_ASSIGNMENT_HISTORY
AS
SELECT     ta.ID, ta.TASK_ID, ta.PERSON_ASSIGNED, ta.ROLE_ASSIGNED, p.FULL_NAME AS REQUESTEE_NAME, ta.REQUEST_DATE, ta.ACCEPTED_DATE, 
                      ta.REJECTION_DATE, ta.REASON_REJECTED, ta.REQUESTOR, ISNULL(r.NAME, '') + ISNULL(p.FULL_NAME, '') AS REQ_NAME, r.NAME, 
                      A_V_PEOPLE_APPROVED_DATA_1.FULL_NAME AS REQUESTOR_NAME, ta.STATUS
FROM         dbo.A_TASK_ASSIGNEE ta LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA A_V_PEOPLE_APPROVED_DATA_1 ON ta.REQUESTOR = A_V_PEOPLE_APPROVED_DATA_1.ID LEFT OUTER JOIN
                      dbo.A_V_ROLE_DATA_BY_APPROVED_ID r ON ta.ROLE_ASSIGNED = r.ID LEFT OUTER JOIN
                      dbo.A_V_PEOPLE_APPROVED_DATA p ON ta.PERSON_ASSIGNED = p.ID




