




CREATE VIEW dbo.A_V_OBJECTS_WITH_LOCKED_BY_BOSS
AS
SELECT     A_PEOPLE_1.ID AS BOSS_ID, dbo.A_OBJECTS.*
FROM         dbo.A_OBJECTS INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_OBJECTS.LOCKED_BY = dbo.A_PEOPLE_HISTORY.ID LEFT OUTER JOIN
                      dbo.A_PEOPLE_HISTORY A_PEOPLE_1 ON dbo.A_PEOPLE_HISTORY.BOSS = A_PEOPLE_1.ID





