



CREATE VIEW dbo.A_V_POP_FILL_SURVEY_INVITED_PEOPLE
AS
SELECT     dbo.A_SURVEY_INV_PEOPLE.SURVEY_ID AS S_ID, dbo.A_SURVEY_INV_PEOPLE.PEOPLE_ID AS P_ID, 
                      dbo.A_APPROVED_PEOPLE.FULL_NAME AS NAME
FROM         dbo.A_APPROVED_PEOPLE INNER JOIN
                      dbo.A_SURVEY_INV_PEOPLE ON dbo.A_APPROVED_PEOPLE.ID = dbo.A_SURVEY_INV_PEOPLE.PEOPLE_ID




