


CREATE VIEW dbo.A_V_PRODUCT_WITH_SUPPLIER_INFO
AS
SELECT     dbo.A_V_COMPANIES_APPROVED_DATA.NAME AS SUPPLIER_NAME, dbo.A_PRODUCTS.ID, dbo.A_PRODUCTS_HISTORY.NAME AS PRODUCT_NAME, 
                      dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID, dbo.A_PRODUCTS_HISTORY.COMMENTS, dbo.A_PRODUCTS_HISTORY.PROCEDURE_ID, 
                      dbo.A_PRODUCTS_HISTORY.APP_OBJECT, dbo.A_PRODUCTS_HISTORY.SHIP_OR_LABOR, dbo.A_PRODUCTS_HISTORY.CUSTOMIZABLE, 
                      dbo.A_PRODUCTS_HISTORY.REQ_FORM, dbo.A_PRODUCTS_HISTORY.MGR_TEAM, dbo.A_PRODUCTS_HISTORY.SALES_TAX, 
                      dbo.A_PRODUCTS_HISTORY.DRCM, dbo.A_PRODUCTS_HISTORY.MODBY, dbo.A_PRODUCTS_HISTORY.OBJECT_ID, 
                      dbo.A_PRODUCTS_HISTORY.PARENT_ID, dbo.A_PRODUCTS_HISTORY.SYSTEM_PROCEDURE, dbo.A_PRODUCTS_HISTORY.CUST_MGR_ROLE
FROM         dbo.A_PRODUCTS INNER JOIN
                      dbo.A_PRODUCTS_HISTORY ON dbo.A_PRODUCTS.HISTORY_REF_ID = dbo.A_PRODUCTS_HISTORY.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON dbo.A_PRODUCTS_HISTORY.SUPPLIER_ID = dbo.A_V_COMPANIES_APPROVED_DATA.ID



