


CREATE VIEW dbo.A_V_SURVEY_GET_QUESTIONS
AS
SELECT     dbo.A_SURVEYS.ID AS S_ID, dbo.A_SURVEY_REPLIES.ID AS R_ID, dbo.A_SURVEY_REPLIES.TEXT, dbo.A_SURVEY_REPLIES.NUM, 
                      dbo.A_SURVEY_REPLIES.ROOT, dbo.A_SURVEY_REPLIES.COLOR, dbo.A_SURVEY_REPLIES.PARENT, dbo.A_SURVEY_REPLIES.AUTHOR, 
                      dbo.A_SURVEY_REPLIES.MODBY, dbo.A_SURVEY_ATTACHMENTS.DOC_ID, dbo.A_SURVEY_REPLIES.DRCM
FROM         dbo.A_SURVEYS INNER JOIN
                      dbo.A_SURVEY_REPLIES ON dbo.A_SURVEYS.ID = dbo.A_SURVEY_REPLIES.ROOT LEFT OUTER JOIN
                      dbo.A_SURVEY_ATTACHMENTS ON dbo.A_SURVEY_REPLIES.ID = dbo.A_SURVEY_ATTACHMENTS.RESPONSE_ID
WHERE     (dbo.A_SURVEY_REPLIES.PARENT IS NULL)



