CREATE VIEW dbo.A_V_WORKER_SCREEN_TASKS
AS
SELECT DISTINCT 
                      p.ID AS PURCHASE_ID, toi.PURCHASE_HIST_ID, toi.PURCHASE_ITEM_ID, c.NAME AS CUSTOMER_NAME, i.DUE_DATE, i.ORIG_DUE_DATE, 
                      t.PROCEDURE_ID AS PROC_ID, c.ID AS CUST_ID, dbo.A_FN_DATE_TIME_ADD_USING_UNITS(i.PROD_TIME_UNIT, i.DUE_DATE, - i.PROD_TIME) 
                      AS START_DATE, t.STATUS, t.REQUESTEE_ID, t.GROUP_REQUESTEE_ID, dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, t.ID, 
                      p.CUST_PURCH_NUM, i.ACCOUNT_ID, dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.REFERENCE_PO, 
                      dbo.A_V_PROCEDURES_DATA_QUICK.NAME AS PROC_NAME, i.QTY, t.ACTUAL_START_DATE, t.ACTUAL_STOP_DATE, i.MT_NUM, 
                      dbo.A_TASK_OBJECT_LINK.OBJECT_ID AS ACTUAL_PART_ID, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK.SERIAL
FROM         dbo.A_TASK_ORDER_INFORMATION toi INNER JOIN
                      dbo.A_ORDER_ITEMS i ON toi.PURCHASE_ITEM_ID = i.ID INNER JOIN
                      dbo.A_TASKS t ON toi.TASK_ID = t.ID INNER JOIN
                      dbo.A_V_PURCHASES_APPROVED_DATA p ON toi.PURCHASE_HIST_ID = p.HISTORY_REF_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK c ON p.CUSTOMER_CO = c.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON i.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PROCEDURES_DATA_QUICK ON t.PROCEDURE_ID = dbo.A_V_PROCEDURES_DATA_QUICK.ID INNER JOIN
                      dbo.A_TASK_OBJECT_LINK ON t.ID = dbo.A_TASK_OBJECT_LINK.TASK_ID INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK ON 
                      dbo.A_TASK_OBJECT_LINK.OBJECT_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK.ID LEFT OUTER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK ON i.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.ID
WHERE     (toi.PURCHASE_ITEM_ID IS NOT NULL) AND (t.STATUS IN ('REQUESTED', 'ACCEPTED', 'CLOSED', 'FINISHED'))
