


CREATE VIEW dbo.A_V_MEETING_GET_BY_ID
AS
SELECT     dbo.A_MEETINGS.ID, dbo.A_MEETINGS.MEETING_NAME, dbo.A_MEETINGS.COMMENT, dbo.A_MEETINGS.START_DATE, 
                      dbo.A_MEETINGS.STOP_DATE, dbo.A_MEETINGS.OWNER, dbo.A_MEETINGS.SCRIBE, dbo.A_MEETINGS.LOCATION, 
                      dbo.A_MEETINGS.WEB_LOCATION, dbo.A_MEETINGS.DATE_CREATED, dbo.A_MEETINGS.STATUS, dbo.A_MEETINGS.DRCM, dbo.A_MEETINGS.HOST, 
                      dbo.A_MEETINGS.TIME_KEEP, dbo.A_V_LOCATION_WITH_NAME.LOCATION_NAME, dbo.A_V_MEETING_GET_HOST_NAME.HOST_NAME, 
                      dbo.A_V_MEETING_GET_TKEEP_NAME.TKEEP_NAME, dbo.A_V_MEETING_GET_SCRIBE_NAME.SCRIBE_NAME, dbo.A_MEETINGS.SETTING, 
                      initiator_name.P_NAME AS INITIATOR_NAME
FROM         dbo.A_MEETINGS INNER JOIN
                      dbo.A_V_PEOPLE_BY_NTLOGIN initiator_name ON dbo.A_MEETINGS.OWNER = initiator_name.P_ID LEFT OUTER JOIN
                      dbo.A_V_MEETING_GET_HOST_NAME ON dbo.A_MEETINGS.ID = dbo.A_V_MEETING_GET_HOST_NAME.ID LEFT OUTER JOIN
                      dbo.A_V_MEETING_GET_TKEEP_NAME ON dbo.A_MEETINGS.ID = dbo.A_V_MEETING_GET_TKEEP_NAME.ID LEFT OUTER JOIN
                      dbo.A_V_MEETING_GET_SCRIBE_NAME ON dbo.A_MEETINGS.ID = dbo.A_V_MEETING_GET_SCRIBE_NAME.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATION_WITH_NAME ON dbo.A_MEETINGS.LOCATION = dbo.A_V_LOCATION_WITH_NAME.L_ID