


CREATE VIEW dbo.A_V_APPROVED_OBJECTS
AS
SELECT     dbo.A_APPROVED_OBJECTS.ID, dbo.A_APPROVED_OBJECTS.OBJ_REF_ID, dbo.A_OBJECTS.OBJ_TABLE, dbo.A_OBJECTS.OBJ_ID, 
                      dbo.A_OBJECTS.OBJ_DESC, dbo.A_OBJECTS.STATUS, dbo.A_OBJECTS.CREATING_CO, dbo.A_OBJECTS.REV, 
                      dbo.A_OBJECTS.CREATING_CO_NAME
FROM         dbo.A_APPROVED_OBJECTS INNER JOIN
                      dbo.A_OBJECTS ON dbo.A_APPROVED_OBJECTS.OBJ_REF_ID = dbo.A_OBJECTS.ID
WHERE     (dbo.A_OBJECTS.STATUS LIKE 'APPROVED%')



