




CREATE VIEW dbo.A_V_FAVORITES_COMPLETE
AS
SELECT     g.FAV_TYPE, g.GROUP_NAME, g.PERSON, f.ITEM, f.NUM, g.ID
FROM         dbo.A_PEOPLES_FAVORITES f RIGHT OUTER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS g ON f.[GROUP] = g.ID





