



CREATE VIEW [dbo].[A_V_APPROVED_COMPANIES_WITH_LOGOS]
AS
SELECT     dbo.A_COMPANIES.ID, dbo.A_DOCUMENT_LINK.LINKED_DOC_ID, dbo.A_DOCUMENT_LINK.TYPE, dbo.A_COMPANIES.HISTORY_REF_ID, 
                      dbo.A_COMPANIES_HISTORY.OBJECT_ID AS OBJID, dbo.A_V_LOCATIONS_BY_APPROVED_ID.NAME AS LOC_NAME, 
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID.ADDRESS_1, dbo.A_V_LOCATIONS_BY_APPROVED_ID.FULL_ADDRESS, 
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID.ADDRESS_2, dbo.A_V_LOCATIONS_BY_APPROVED_ID.CITY, 
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID.STATE, dbo.A_V_LOCATIONS_BY_APPROVED_ID.COUNTRY, 
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID.POSTAL_CODE, dbo.A_V_LOCATIONS_BY_APPROVED_ID.INTERNAL_ADDRESS, 
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID.PARENT_PATH, dbo.A_COMPANIES_HISTORY.LOCATION, dbo.A_COMPANIES_HISTORY.NAME AS CO_NAME, 
                      dbo.A_COMPANIES_HISTORY.PHONE, dbo.A_COMPANIES.STATUS
FROM         dbo.A_COMPANIES_HISTORY INNER JOIN
                      dbo.A_COMPANIES ON dbo.A_COMPANIES_HISTORY.ID = dbo.A_COMPANIES.HISTORY_REF_ID INNER JOIN
                      dbo.A_DOCUMENT_LINK ON dbo.A_COMPANIES_HISTORY.OBJECT_ID = dbo.A_DOCUMENT_LINK.OBJECT_ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_BY_APPROVED_ID ON dbo.A_COMPANIES_HISTORY.LOCATION = dbo.A_V_LOCATIONS_BY_APPROVED_ID.ID
WHERE     (dbo.A_DOCUMENT_LINK.TYPE = N'LOGO') AND (dbo.A_COMPANIES.STATUS = 'APPROVED')


