

CREATE VIEW dbo.A_V_PROCEDURE_OBJ_LINK_DATA_FOR_SUMMING
AS
SELECT     l.ID, ISNULL(l.QTY * dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.STD_UNIT_QTY, 0) AS QTY, l.PROCEDURE_ID, l.RELATIONSHIP, 
                      l.APPROVED_OBJECT_ID, dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.STD_UNIT, dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.STD_UNIT_QTY, 
                      dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.UNIT_TYPE
FROM         dbo.A_PROCEDURE_OBJECT_LINK l INNER JOIN
                      dbo.A_Z_UNITS_BASE_UNIT_CONVERTER ON l.QTY_TYPE = dbo.A_Z_UNITS_BASE_UNIT_CONVERTER.FROM_UNIT


