CREATE VIEW dbo.A_V_LINKED_IDS
AS
SELECT     TOP 100 PERCENT ll.ID, ll.ROOT_ID, ll.LINKED_ID, ll.NICK_NAME, ll.LINKED_PASS, ll.DRCM, ll.MODBY, 
                      dbo.A_COMPANIES_IMPORT.EXTERNAL_ID AS EXT_CO_ID
FROM         dbo.A_V_PEOPLE_APPROVED_DATA p INNER JOIN
                      dbo.A_PEOPLE_LINKED_LOGINS ll ON p.ID = ll.LINKED_ID LEFT OUTER JOIN
                      dbo.A_COMPANIES_IMPORT ON p.ROOT_COMPANY = dbo.A_COMPANIES_IMPORT.ROOT_ID
ORDER BY p.NICK_NAME
