


CREATE VIEW dbo.A_V_PEOPLE_BY_NTLOGIN
AS
SELECT     dbo.A_PEOPLE.ID AS P_ID, dbo.A_PEOPLE_HISTORY.FULL_NAME AS P_NAME, dbo.A_PEOPLE_HISTORY.LAST_NAME
FROM         dbo.A_PEOPLE INNER JOIN
                      dbo.A_PEOPLE_HISTORY ON dbo.A_PEOPLE.HISTORY_REF_ID = dbo.A_PEOPLE_HISTORY.ID INNER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE ON dbo.A_PEOPLE_HISTORY.ID = dbo.A_PEOPLE_SEARCH_TABLE.ID



