


CREATE VIEW dbo.A_V_ACTUAL_PARTS_WITH_INSTALLED_PRODUCTS
AS
SELECT     dbo.A_ACTUAL_PART_PRODUCTS_INSIDE_LINK.PRODUCT_ID AS PRODUCT_ID, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.*, 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME
FROM         dbo.A_V_ACTUAL_PARTS_APPROVED_DATA INNER JOIN
                      dbo.A_ACTUAL_PART_PRODUCTS_INSIDE_LINK ON 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID = dbo.A_ACTUAL_PART_PRODUCTS_INSIDE_LINK.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON dbo.A_ACTUAL_PART_PRODUCTS_INSIDE_LINK.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID



