



CREATE VIEW dbo.A_V_Z_FAVORITES_MEETINGS_ITEMS
AS
SELECT     dbo.A_PEOPLES_FAVORITE_GROUPS.ID AS GROUP_ID, dbo.A_PEOPLES_FAVORITE_GROUPS.GROUP_NAME, 
                      dbo.A_PEOPLES_FAVORITE_GROUPS.PERSON, dbo.A_PEOPLES_FAVORITES.ID, dbo.A_PEOPLES_FAVORITES.NUM, 
                      dbo.A_MEETINGS.MEETING_NAME AS NAME, dbo.A_MEETINGS.ID AS ITEM_ID
FROM         dbo.A_PEOPLES_FAVORITES INNER JOIN
                      dbo.A_PEOPLES_FAVORITE_GROUPS ON dbo.A_PEOPLES_FAVORITES.[GROUP] = dbo.A_PEOPLES_FAVORITE_GROUPS.ID INNER JOIN
                      dbo.A_MEETINGS ON dbo.A_PEOPLES_FAVORITES.ITEM = dbo.A_MEETINGS.ID




