
CREATE VIEW [dbo].[A_V_ACTUAL_PARTS_APPROVED_DATA_FOR_EACH_PART_1]
AS

SELECT     
distinct
dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PROD_NAME,
AP.QTY AS PURCHASE_QTY,
dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROC_NAME,
dbo.A_V_PRODUCTS_APPROVED_DATA.HISTORY_REF_ID AS PROD_HIST_ID, 
PURCHASE_ITEM.CUST_LINE_ITEM,
PURCHASE_ITEM.PARENT, 
AP.SERIAL, 
part.NAME AS PART_DESC, 
part.PART_TYPE_NAME,
part.COMPANY_PART_NUMBER,
PURCHASE_ITEM.ID AS PURCH_ITEM_ID,
dbo.A_PURCHASES_HISTORY.CUST_PURCH_NUM,
dbo.A_PURCHASES_HISTORY.OBJECT_ID AS PURCHASE_ID, 
af.DONT_BILL,
AP.PART_ID AS ACTUAL_PART_ID,
dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID,
dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.SUPPLIER_CO AS ACCT_SUPPLIER, 
dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.CUSTOMER_CO AS ACCT_CUSTOMER,
AP.PARENT_ID,
AP.ID
		

FROM         dbo.A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK AP INNER JOIN
                      dbo.A_V_PARTS_APPROVED_DATA part ON AP.PART_ID = part.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA loc ON AP.LOCATION = loc.ID LEFT OUTER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA ON AP.CUR_OWNER = dbo.A_V_COMPANIES_APPROVED_DATA.ID	
					  inner join A_FILLS af on af.FILL_OBJ_ID= ap.PARENT_ID  OR af.FILL_OBJ_ID =ap.id
					  inner join dbo.A_ORDER_ITEMS PURCHASE_ITEM ON af.PURCH_ITEM_ID = PURCHASE_ITEM.ID INNER JOIN
                      dbo.A_PURCHASES_HISTORY ON PURCHASE_ITEM.PURCHASE_HIST_ID = dbo.A_PURCHASES_HISTORY.ID INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK ON 
                      PURCHASE_ITEM.ACCOUNT_ID = dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK.ID LEFT OUTER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON af.FILL_OBJ_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID LEFT OUTER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA INNER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID ON 
                      PURCHASE_ITEM.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID
WHERE     (AP.STATUS = 'APPROVED')