CREATE VIEW dbo.A_V_SHIPPER_TASKS
AS
SELECT     task.ID AS TASK_ID, task.SYSTEM_TASK, cust.NAME AS CUST_NAME, sup.NAME AS SUP_NAME, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.LOCATION_NAME, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.SERIAL, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.CURRENT_OWNER_NAME, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.PART_DESC, 
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.COMPANY_PART_NUMBER, dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.QTY, toi.PURCHASE_ITEM_ID, 
                      task.PARENT_ID AS PARENT_TASK_ID, dbo.A_V_PRODUCTS_APPROVED_DATA.NAME AS PRODUCT_NAME, 
                      dbo.A_V_PROCEDURES_APPROVED_DATA.NAME AS PROCEDURE_NAME, task.REQUESTEE_ID, task.GROUP_REQUESTEE_ID, 
                      dbo.A_PURCHASES_HISTORY.CUST_PURCH_NUM, pi.MT_NUM, task.STATUS, pi.DUE_DATE, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.NAME AS DEST_NAME, SUPPLIER_LOC.NAME AS FROM_NAME, 
                      SUPPLIER_LOC.ADDRESS_1 AS FROM_ADD_1, SUPPLIER_LOC.ADDRESS_2 AS FROM_ADD_2, SUPPLIER_LOC.CITY AS FROM_CITY, 
                      SUPPLIER_LOC.STATE AS FROM_STATE, SUPPLIER_LOC.COUNTRY AS FROM_COUNTRY, SUPPLIER_LOC.POSTAL_CODE AS FROM_ZIP, 
                      SUPPLIER_LOC.INTERNAL_ADDRESS AS FROM_INTERNAL, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ADDRESS_1 AS TO_ADD_1, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ADDRESS_2 AS TO_ADD_2, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.CITY AS TO_CITY, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.STATE AS TO_STATE, dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.COUNTRY AS TO_COUNTRY, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.POSTAL_CODE AS TO_ZIP, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.INTERNAL_ADDRESS AS TO_INTERNAL, 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ID AS TO_LOC_ID, SUPPLIER_LOC.ID AS FROM_LOC_ID, 
                      dbo.A_PURCHASES_HISTORY.OBJECT_ID AS PURCHASE_ID, dbo.A_V_COMPANY_LOGOS.LINKED_DOC_ID AS SUP_LOGO, 
                      A_V_COMPANY_LOGOS_1.LINKED_DOC_ID AS CUST_LOGO, A_V_COMPANY_LOGOS_2.LINKED_DOC_ID AS SUP_ROOT_LOGO, pi.SHIP_DATE, 
                      sup.PHONE AS FROM_PHONE, pi.CUST_LINE_ITEM, toi.FILL_ITEM_ID
FROM         dbo.A_TASKS task INNER JOIN
                      dbo.A_TASK_OBJECT_LINK INNER JOIN
                      dbo.A_TASK_ORDER_INFORMATION toi INNER JOIN
                      dbo.A_TASKS parent ON toi.TASK_ID = parent.ID INNER JOIN
                      dbo.A_V_ACCOUNTS_APPROVED_DATA_QUICK acc INNER JOIN
                      dbo.A_ORDER_ITEMS pi ON acc.ID = pi.ACCOUNT_ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK sup ON acc.SUPPLIER_CO = sup.ID INNER JOIN
                      dbo.A_V_COMPANIES_APPROVED_DATA_QUICK cust ON acc.CUSTOMER_CO = cust.ID ON toi.PURCHASE_ITEM_ID = pi.ID ON 
                      dbo.A_TASK_OBJECT_LINK.TASK_ID = parent.ID INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA ON dbo.A_TASK_OBJECT_LINK.OBJECT_ID = dbo.A_V_ACTUAL_PARTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PRODUCTS_APPROVED_DATA ON pi.PRODUCT_ID = dbo.A_V_PRODUCTS_APPROVED_DATA.ID INNER JOIN
                      dbo.A_V_PROCEDURES_APPROVED_DATA ON 
                      dbo.A_V_PRODUCTS_APPROVED_DATA.PROCEDURE_ID = dbo.A_V_PROCEDURES_APPROVED_DATA.ID INNER JOIN
                      dbo.A_PURCHASES_HISTORY ON pi.PURCHASE_HIST_ID = dbo.A_PURCHASES_HISTORY.ID INNER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK SUPPLIER_LOC ON sup.LOCATION = SUPPLIER_LOC.ID ON 
                      task.PARENT_ID = parent.ID LEFT OUTER JOIN
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK RIGHT OUTER JOIN
                      dbo.A_TASK_ORDER_INFORMATION A_TASK_ORDER_INFORMATION_1 ON 
                      dbo.A_V_LOCATIONS_APPROVED_DATA_QUICK.ID = A_TASK_ORDER_INFORMATION_1.ACTUAL_TO_LOC ON 
                      task.ID = A_TASK_ORDER_INFORMATION_1.TASK_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANY_LOGOS ON sup.ID = dbo.A_V_COMPANY_LOGOS.CO_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANY_LOGOS A_V_COMPANY_LOGOS_2 ON sup.ROOT_CO_ID = A_V_COMPANY_LOGOS_2.CO_ID LEFT OUTER JOIN
                      dbo.A_V_COMPANY_LOGOS A_V_COMPANY_LOGOS_1 ON cust.ID = A_V_COMPANY_LOGOS_1.CO_ID
WHERE     (task.STATUS IN ('REQUESTED', 'ACCEPTED')) AND (task.SYSTEM_TASK IN ('SYS_RECEIVE', 'SYS_SEND'))
