CREATE VIEW dbo.A_V_ACTUAL_PARTS_APPROVED_DATA_QUICK
AS
SELECT     dbo.A_ACTUAL_PARTS.ID, dbo.A_ACTUAL_PARTS.HISTORY_REF_ID, dbo.A_ACTUAL_PARTS_HISTORY.OBJECT_ID, 
                      dbo.A_ACTUAL_PARTS_HISTORY.LOCATION, dbo.A_ACTUAL_PARTS_HISTORY.NICK_NAME, dbo.A_ACTUAL_PARTS_HISTORY.MERGABLE, 
                      dbo.A_ACTUAL_PARTS_HISTORY.PARENT_ID, dbo.A_ACTUAL_PARTS_HISTORY.PART_ID, dbo.A_ACTUAL_PARTS_HISTORY.QTY, 
                      dbo.A_ACTUAL_PARTS_HISTORY.SERIAL, dbo.A_ACTUAL_PARTS_HISTORY.CUR_OWNER, dbo.A_ACTUAL_PARTS_HISTORY.ASSEMBLY_WT, 
                      dbo.A_ACTUAL_PARTS_HISTORY.AP_STATUS, dbo.A_ACTUAL_PARTS_HISTORY.ROOT_ID, dbo.A_ACTUAL_PARTS_HISTORY.ROOT_STATUS, 
                      dbo.A_ACTUAL_PARTS_HISTORY.MODIFIED, dbo.A_ACTUAL_PARTS_HISTORY.SYS_NAME, dbo.A_ACTUAL_PARTS_HISTORY.PREV_OWNER, 
                      dbo.A_ACTUAL_PARTS_HISTORY.SUB_PART_ACTION, dbo.A_ACTUAL_PARTS.STATUS, dbo.A_ACTUAL_PARTS_HISTORY.HAS_CHILD, 
                      dbo.A_ACTUAL_PARTS_HISTORY.RESPONSIBLE_PERSON
FROM         dbo.A_ACTUAL_PARTS_HISTORY INNER JOIN
                      dbo.A_ACTUAL_PARTS ON dbo.A_ACTUAL_PARTS_HISTORY.ID = dbo.A_ACTUAL_PARTS.HISTORY_REF_ID
WHERE     (dbo.A_ACTUAL_PARTS.STATUS = 'APPROVED')
