


CREATE VIEW dbo.A_V_THEORY_HEADER_REFERENCE_FILES
AS
SELECT     h.ID AS PROC_ID, d.*, h.OBJECT_ID AS P_OBJ_ID
FROM         dbo.A_DOCUMENT_LINK dl INNER JOIN
                      dbo.A_DOCUMENTS d ON dl.LINKED_DOC_ID = d.ID INNER JOIN
                      dbo.A_THEORY_HISTORY h ON dl.OBJECT_ID = h.OBJECT_ID



