CREATE VIEW dbo.A_V_ORDERS_APPROVED_DATA
AS
SELECT     dbo.A_ORDERS.ID, dbo.A_ORDERS.HISTORY_REF_ID, dbo.A_ORDERS_HISTORY.OBJECT_ID, dbo.A_ORDERS_HISTORY.CUSTOMER_PERSON, 
                      dbo.A_ORDERS_HISTORY.CUSTOMER_CO, dbo.A_ORDERS_HISTORY.DESCRIPTION, dbo.A_ORDERS_HISTORY.BUDGETARY_ONLY, 
                      dbo.A_ORDERS_HISTORY.EXPIRATION_DATE, dbo.A_ORDERS_HISTORY.PROGRESS, dbo.A_ORDERS_HISTORY.DRCM, 
                      dbo.A_ORDERS_HISTORY.MODBY, dbo.A_ORDERS.STATUS, dbo.A_ORDERS_HISTORY.RFQ_ID, dbo.A_ORDERS_HISTORY.SUPPLIER_ID, 
                      dbo.A_ORDERS_HISTORY.CREATION_DATE, dbo.A_ORDERS_HISTORY.PERSON_SUPPLIER, dbo.A_ORDERS_HISTORY.TYPE, 
                      dbo.A_ORDERS_HISTORY.PRICE
FROM         dbo.A_ORDERS INNER JOIN
                      dbo.A_ORDERS_HISTORY ON dbo.A_ORDERS.HISTORY_REF_ID = dbo.A_ORDERS_HISTORY.ID
WHERE     (dbo.A_ORDERS.STATUS = 'APPROVED')
