

CREATE VIEW dbo.A_V_PROCEDURE_LABOR
AS
SELECT     dbo.A_PROCEDURES_HISTORY.NAME AS PROCEDURE_NAME, dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID AS PROC_ID, 
                      dbo.A_PROCEDURE_OBJECT_LINK.STEP_ID AS PROC_STEP, dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID AS ROLE_ID, 
                      dbo.A_V_APPROVED_OBJECTS.OBJ_DESC AS ROLE_NAME, dbo.A_PROCEDURE_OBJECT_LINK.QTY, dbo.A_PROCEDURE_OBJECT_LINK.QTY_TYPE, 
                      dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP, dbo.A_PROCEDURE_OBJECT_LINK.LABOR_ROLE
FROM         dbo.A_PROCEDURES_HISTORY INNER JOIN
                      dbo.A_PROCEDURE_OBJECT_LINK ON dbo.A_PROCEDURES_HISTORY.ID = dbo.A_PROCEDURE_OBJECT_LINK.PROCEDURE_ID INNER JOIN
                      dbo.A_V_APPROVED_OBJECTS ON dbo.A_PROCEDURE_OBJECT_LINK.APPROVED_OBJECT_ID = dbo.A_V_APPROVED_OBJECTS.ID
WHERE     (dbo.A_PROCEDURE_OBJECT_LINK.RELATIONSHIP = N'LABOR_PROVIDE_TAKE_BACK')


