

CREATE VIEW dbo.A_V_TASKS_WITH_PROCEDURE_STEP_ORDER_II
AS
SELECT     dbo.A_PROCEDURE_STEPS.PRINT_ORDER AS STEP_ORDER, dbo.A_TASKS.*
FROM         dbo.A_TASKS LEFT OUTER JOIN
                      dbo.A_PROCEDURE_STEPS ON dbo.A_TASKS.PROCEDURE_STEP_ID = dbo.A_PROCEDURE_STEPS.ID


