


CREATE VIEW dbo.A_V_SERVICE_CALLS_ATTACHMENT_DATA
AS
SELECT     dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID, dbo.A_SERVICE_CALLS_ATTACHMENTS.DOC_ID AS [VALUE], dbo.A_DOCUMENTS.NAME AS SHOW, 
                      dbo.A_DOCUMENTS.DESCRIPTION
FROM         dbo.A_SERVICE_CALLS_ATTACHMENTS INNER JOIN
                      dbo.A_DOCUMENTS ON dbo.A_SERVICE_CALLS_ATTACHMENTS.DOC_ID = dbo.A_DOCUMENTS.ID INNER JOIN
                      dbo.A_SERVICE_CALLS_WEEKLY_REPORTS ON 
                      dbo.A_SERVICE_CALLS_ATTACHMENTS.WEEKLY_ID = dbo.A_SERVICE_CALLS_WEEKLY_REPORTS.ID