CREATE VIEW dbo.A_V_ACTUAL_PARTS_RELATED_FILES
AS
SELECT     AP.ID AS ACTUAL_PART_ID, AP.LOCATION_NAME, AP.COMPANY_PART_NUMBER, AP.NICK_NAME, AP.QTY, AP.SERIAL, AP.CURRENT_OWNER_NAME, 
                      AP.PART_DESC, AP.NAME, APRF.ID AS FILE_LINK_ID, APRF.FILE_ID, APRF.STATUS, APRF.DATE_DELETED, APRF.DELETED_BY, 
                      D.NAME AS FILE_NAME, D.DESCRIPTION AS FILE_DESCRIPTION, P.FULL_NAME AS DELETED_BY_NAME, D.CREATOR_ID
FROM         dbo.A_ACTUAL_PARTS_RELATED_FILES APRF INNER JOIN
                      dbo.A_DOCUMENTS D ON APRF.FILE_ID = D.ID INNER JOIN
                      dbo.A_V_ACTUAL_PARTS_APPROVED_DATA AP ON APRF.ACTUAL_PART_ID = AP.ID LEFT OUTER JOIN
                      dbo.A_PEOPLE_SEARCH_TABLE P ON APRF.DELETED_BY = P.OBJ_ID
