

CREATE VIEW dbo.A_Z_UNITS_BASE_UNIT_CONVERTER
AS
SELECT     dbo.A_UNIT_RELATIONS.FIRST_UNIT AS FROM_UNIT, dbo.A_UNIT_RELATIONS.SECOND_UNIT AS STD_UNIT, 
                      dbo.A_UNIT_RELATIONS.X_SECOND AS STD_UNIT_QTY, dbo.A_UNIT_TYPES.UNIT_TYPE
FROM         dbo.A_UNIT_RELATIONS INNER JOIN
                      dbo.A_UNIT_TYPES ON dbo.A_UNIT_RELATIONS.FIRST_UNIT = dbo.A_UNIT_TYPES.ID
WHERE     (dbo.A_UNIT_RELATIONS.SECOND_UNIT IN ('TIME_SYS_SECONDS', 'UNIT', 'VOL_GALLONS', 'WT_OZ'))


