

CREATE VIEW dbo.A_Z_UNITS_TIME_TO_SECS
AS
SELECT     A_UNIT_TYPES_1.NAME AS FROM_NAME, dbo.A_UNIT_RELATIONS.FIRST_UNIT AS FROM_UNIT, 
                      dbo.A_UNIT_RELATIONS.SECOND_UNIT AS TO_UNIT, dbo.A_UNIT_TYPES.NAME AS TO_NAME, dbo.A_UNIT_RELATIONS.X_SECOND AS SECS
FROM         dbo.A_UNIT_TYPES INNER JOIN
                      dbo.A_UNIT_RELATIONS INNER JOIN
                      dbo.A_UNIT_TYPES A_UNIT_TYPES_1 ON dbo.A_UNIT_RELATIONS.FIRST_UNIT = A_UNIT_TYPES_1.ID ON 
                      dbo.A_UNIT_TYPES.ID = dbo.A_UNIT_RELATIONS.SECOND_UNIT
WHERE     (dbo.A_UNIT_RELATIONS.SECOND_UNIT IN ('TIME_SYS_SECONDS', 'UNIT', 'VOL_GALLONS', 'WT_OZ'))


