CREATE VIEW [dbo].[Portal_CustomerRequirementView]
AS

SELECT NEWID() AS ID
	, C.ID AS CUSTOMERSUBMITID
	, SUP.ROOT_NAME AS COMPANY
	, C.[DESCRIPTION]
	, P.SUPPLIER_ID AS SUPPLIERID
	, P.SUPPLIER_NAME AS SUPPLIERNAME
	, P.CUSTOMERID
	, CUS.[NAME] AS CUSTOMERNAME
	, P.LOCATIONID
	, C.SUBMITTEDDATE
	, P.PROCEDURE_ID AS PROCEDUREID
	, P.[PROCEDURE_NAME] AS PROCEDURENAME
	, P.APP_OBJECT AS PARTID
	, C.QUOTEJSON
	, C.CUSTOMERREQUIREMENTJSON
	, P.[NAME] AS PRODUCTNAME
	, P.ID AS PRODUCTID
	, C.RESPRESENTATIVE
	, P.DIVISION
	, C.PARTKITNO
	, C.SUBMITTEDBY
	, P.TOTALSALEPRICE
	, C.PRICE
	, P.MATERIALCOST
	, C.LEADTIME
	, C.PRODUCTWORKFLOWID
	, P.REV AS REV
	, P.ISPRODUCT
	, P.[STATUS]
	, P.[OBJECT_ID] AS OBJECTID
	--, PQP.CUST_ID AS CUSTOMERID
	--, CUSTOMER.NAME AS CUSTOMERNAME
	, P.CYCLETIME
FROM A_V_PRODUCT_SEARCH_DATA P
INNER JOIN DBO.PORTAL_CUSTOMERSUBMITTEDREQUIREMENT C ON C.ID = P.CUSTOMERREQUIREMENTID
LEFT JOIN PORTAL_PROCEDURESVIEW PV ON P.PROCEDURE_ID = PV.OBJECTID
LEFT JOIN A_V_COMPANIES_DROP_SEARCH SUP ON SUP.ID = P.SUPPLIER_ID
LEFT JOIN A_V_COMPANIES_DROP_SEARCH CUS ON CUS.ID = P.CUSTOMERID
LEFT JOIN A_PRODUCTS_QUICK_PRICE PQP ON P.ID = PQP.PROD_HIST_ID
-- OUTER APPLY (SELECT CUS.NAME FROM A_V_COMPANIES_DROP_SEARCH CUS	WHERE CUS.ID= PQP.CUST_ID) AS CUSTOMER
GO
