CREATE VIEW Portal_NotificationView
AS

SELECT
NEWID() AS Id,
pa.ItemType,
wf.Title,
COUNT(*) ItemCount 
FROM [Protal_PendingApprovals] pa 
INNER JOIN[A_WF_ACTIVITIES] wf ON wf.ACTIVITY = pa.ItemType 
WHERE ItemType IN (
'A_PROCEDURES_HISTORY',
'A_PARTS_HISTORY',
'A_PART_TYPES_HISTORY',
'A_ROLES_HISTORY',
'A_PEOPLE_HISTORY',
'A_REGIONS_HISTORY',
'A_LOCATIONS_HISTORY',
'A_COMPANIES_HISTORY',
'A_THEORY_HISTORY',
'A_ACCOUNTS_HISTORY', --'Purchase Orders
'A_PRODUCTS_HISTORY'
)
GROUP BY pa.ItemType, wf.Title