CREATE VIEW [dbo].[Report_WorkOrdersWithoutInvoices]
AS

SELECT DISTINCT 
	ROW_NUMBER() OVER(ORDER BY WO.LOCATIONNAME ASC) AS Id
	, WO.LOCATIONNAME AS LOCATION_NAME
	, WO.CUSTOMERNAME AS CUSTOMER_NAME
	, WO.REFERENCEPO AS CUST_PURCH_NUM
	, WO.WOITEM AS WORK_ORDER_ITEM
	, CASE WHEN (WO.PRODUCTNAME IS NULL) THEN N'' ELSE WO.PRODUCTNAME END + N'(' + CASE WHEN (WO.PROCOBJID IS NULL) THEN N'' ELSE WO.PROCOBJID END + N')' AS PRODUCT_NAME
	, FORMAT(WO.TOTALSALEPRICE, 'C') AS TOTAL_SALE_PRICE
	, FORMAT(WO.ACTUALSTOPDATE, 'MM/dd/yyyy') AS WORK_ORDER_COMPLETED_DATE
	--, WO.FILLITEMID
	--, WO.REFERENCEPO
	--, WO.PURCHASEID
	--, PO.OPENDATE
	--, WO.PURCHASEITEMID
	--, CASE WHEN (WO.PRODUCTNAME IS NULL) THEN N'' ELSE WO.PRODUCTNAME END + N'(' + CASE WHEN (WO.PROCOBJID IS NULL) THEN N'' ELSE WO.PROCOBJID END + N')' AS C2
	--, WO.FILLQTY
	--, WO.TOTALSALEPRICE
	--, WO.AMOUNT
	--, WO.[STATUS]
FROM DBO.PORTAL_WORKORDERS AS WO
INNER JOIN DBO.PORTAL_PURCHASEORDERS AS PO ON (WO.REFERENCEPO = PO.REFERENCEPO) OR ((WO.REFERENCEPO IS NULL) AND (PO.REFERENCEPO IS NULL))
WHERE WO.[STATUS] = 'FINISHED'
AND WO.FILLITEMID NOT IN (SELECT ITEMID FROM PORTAL_INVOICEWORKITEM)
AND WO.ACTUALSTOPDATE > '2019-08-01'
--SELECT P.ID AS PURCHASE_ID
--	, P.HISTORY_REF_ID AS PURCHASE_HISTORY_ID
--	, P.ORDER_ID
--	, P.CUST_PURCH_NUM
--	, P.PURCHASE_STATUS
--	, C.[NAME] + '-' + (SELECT TOP 1 TOI.PURCHASE_ITEM_ID FROM A_TASK_ORDER_INFORMATION TOI WHERE TOI.PURCHASE_HIST_ID = P.HISTORY_REF_ID AND TOI.PURCHASE_ITEM_ID IS NOT NULL) AS WORK_ORDER_ITEM
--	--, (SELECT TOP 1 CLOSE_DATE FROM A_V_ACCOUNTS_APPROVED_DATA_QUICK A WHERE A.REFERENCE_PO = P.CUST_PURCH_NUM) AS CLOSE_DATE
--	, P.[DESCRIPTION] AS PRODUCT_NAME
--	, NULL AS CLOSED_BY_CODE
--	, FORMAT((SELECT TOP 1 PH.TOTALSALEPRICE
--			FROM A_PRODUCTS_HISTORY PH
--			INNER JOIN A_OBJECTS O ON O.ID = PH.OBJECT_ID
--			INNER JOIN A_PRODUCTS_QUICK_PRICE QP ON QP.PROD_HIST_ID = PH.ID
--			INNER JOIN A_ORDERS_HISTORY OH ON OH.OBJECT_ID = QP.ORDER_ID
--			WHERE OH.OBJECT_ID = P.ORDER_ID)
--	, 'C') AS TOTAL_SALE_PRICE
--	, FORMAT((
--		SELECT MAX(T.ACTUAL_STOP_DATE)
--		FROM A_TASK_ORDER_INFORMATION TOI
--		INNER JOIN A_TASKS T ON T.ID = TOI.TASK_ID
--		WHERE TOI.PURCHASE_HIST_ID = P.HISTORY_REF_ID)
--	, 'MM/dd/yyyy') AS WORK_ORDER_COMPLETED_DATE
--FROM A_V_PURCHASES_APPROVED_DATA P
--INNER JOIN A_V_COMPANIES_APPROVED_DATA_QUICK C ON P.CUSTOMER_CO = C.ID
--LEFT JOIN A_V_ORDER_ITEMS_ALL_DATA OI ON OI.ORDER_ID = P.ORDER_ID
--WHERE P.PURCHASE_STATUS IN ('FINISHED', 'CLOSED')



GO