

CREATE VIEW [dbo].[Report_WorkOrdersWithoutInvoices]
AS
SELECT ROW_NUMBER() OVER(ORDER BY A.WORK_ORDER_ITEM ASC) AS Id, *
FROM (
SELECT DISTINCT 
	WO.LOCATIONNAME AS LOCATION_NAME
	, WO.CUSTOMERNAME AS CUSTOMER_NAME
	, WO.REFERENCEPO AS CUST_PURCH_NUM
	, WO.WOITEM AS WORK_ORDER_ITEM
	, CASE WHEN (WO.PRODUCTNAME IS NULL) THEN N'' ELSE WO.PRODUCTNAME END + N'(' + CASE WHEN (WO.PROCOBJID IS NULL) THEN N'' ELSE WO.PROCOBJID END + N')' AS PRODUCT_NAME
	, FORMAT(WO.TOTALSALEPRICE, 'C') AS TOTAL_SALE_PRICE
	, WO.ACTUALSTOPDATE AS WORK_ORDER_COMPLETED_DATE
FROM DBO.PORTAL_WORKORDERS AS WO
INNER JOIN DBO.PORTAL_PURCHASEORDERS AS PO ON (WO.REFERENCEPO = PO.REFERENCEPO) OR ((WO.REFERENCEPO IS NULL) AND (PO.REFERENCEPO IS NULL))
WHERE WO.[STATUS] = 'FINISHED'
AND WO.FILLITEMID NOT IN (SELECT ITEMID FROM PORTAL_INVOICEWORKITEM)
AND WO.ACTUALSTOPDATE > '2019-08-01'
)A



GO