CREATE VIEW [dbo].[Sensor_Current_Values]
AS

SELECT S.SENSORMAPPINGID
	, S.[SITE] AS SITENAME
	, S.SENSORNAME
	, M.ITEMCURRENTVALUE AS SENSORCURRENTVALUE
FROM DBO.SENSOR_MAPPING AS S
INNER JOIN [$(EquipmentMonitoring)].DBO.HILLSBORO_UPDATETABLE AS M ON M.ITEMID = S.MONITORINGID
GO