CREATE VIEW [dbo].[Sensor_Current_Values]
AS

SELECT 1 as dummy;

-- the table HILLSBORO_UPDATETABLE doesn't exist!

--SELECT S.SENSORMAPPINGID
--	, S.[SITE] AS SITENAME
--	, S.SENSORNAME
--	, M.ITEMCURRENTVALUE AS SENSORCURRENTVALUE
--FROM DBO.SENSOR_MAPPING AS S
--INNER JOIN EQUIPMENTMONITORING.DBO.HILLSBORO_UPDATETABLE AS M ON M.ITEMID = S.MONITORINGID