/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using NSwag.Annotations;
using MSR.Answer.API.V1.Models;
using MSR.Answer.API.Attributes;
using System;
using MSR.Domain.Models;
using MSR.Domain.Abstractions.Services;
using MSR.Domain.Commands;
using System.Threading.Tasks;
using MSR.Domain.Commanding.Abstractions;
using MSR.Answer.API.V1.Extentions;

namespace MSR.Answer.API.V1.Controllers
{

    /// <summary>
    ///
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class MonitorController : BaseApiController
    {
        private readonly ICommandDispatcher _dispatcher;

        /// <summary>
        /// MonitorController Constructor
        /// </summary>
        public MonitorController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        /// Get data on a specific monitor, including the serial # of
        /// the part and the result of the test.
        /// </summary>
        /// <param name="id">ProcedureSteMonitor ID</param>
        /// <response code="200"></response>
        [HttpGet]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<MonitorModel>>))]
        public async Task<IActionResult> MonitorGetMonitor([FromQuery]int id)
        {
            var ret = await _dispatcher.DispatchAsync(new GetMonitorModel(){
                    procedureStepMonitorId = id
                }
            );

            return ret.ToOkObjectResponse<MonitorModel>();
        }
    }
}
