/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using NSwag.Annotations;

namespace IO.Swagger.Controllers
{ 

    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class MonitorApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="version"></param>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/v{version}/Monitor")]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfMonitor))]
        public virtual IActionResult MonitorGetMonitor([FromRoute][Required]string version, [FromQuery]int? id)
        { 
            var example = new AuditActionResultOfICollectionOfMonitor();
            example.Object = new List<Monitor>(){
                new Monitor() {
                    Id = 1,
                    Description = "alsdkjflaskdjf"
                }
            };
            return new ObjectResult(example);
        }
    }
}
