/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using NSwag.Annotations;
using MSR.Answer.API.V1.Models;
using MSR.Answer.API.Attributes;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using MSR.Domain.Commands;
using MSR.Domain.Commanding.Abstractions;
using MSR.Answer.API.V1.Extentions;
using MSR.Domain.Models;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// Procedure template API
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class ProcedureTemplateController : BaseApiController
    {
        private ICommandDispatcher _dispatcher;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="dispatcher"></param>
        public ProcedureTemplateController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        /// Create a procedure template
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPost]
        [SwaggerResponse(typeof(AuditActionResult<ProcedureStepTemplateModel>))]
        public async Task<IActionResult> CreateProcedureTemplate([FromBody]CreateProcedureTemplateRequest body)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete a procedure template
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpDelete]
        [SwaggerResponse(typeof(AuditActionResult))]
        public virtual IActionResult DeleteProcedureTemplate([FromRoute][Required]int? id)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get a procedure template
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<ProcedureStepTemplateModel>>))]
        public async Task<IActionResult> GetProcedureTemplate([FromQuery]int? id)
        {
            var command = new GetProcedureStepTemplate() { Id = id };
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<ICollection<ProcedureStepTemplateModel>>();
        }

        /// <summary>
        /// Update a procedure template
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<ProcedureStepTemplateModel>))]
        public async Task<IActionResult> UpdateProcedureTemplate([FromBody]UpdateProcedureTemplateRequest body)
        {
            throw new NotImplementedException();
        }
    }
}
