/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Models;
using NSwag.Annotations;

namespace IO.Swagger.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class ProcedureTemplateApiController : ControllerBase
    {
        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPost]
        [Route("/v{version}/ProcedureTemplate")]
        [ValidateModelState]
        [SwaggerResponse(typeof(AuditActionResultOfProcedureTemplate))]
        public virtual IActionResult ProcedureTemplateCreateProcedureTemplate([FromBody]CreateProcedureTemplateRequest body, [FromRoute][Required]string version)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfProcedureTemplate));
            string exampleJson = null;
            exampleJson = "\"\"";

                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfProcedureTemplate>(exampleJson)
                        : default(AuditActionResultOfProcedureTemplate);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="id"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpDelete]
        [Route("/Robert5/msr-api/v1/v{version}/ProcedureTemplate/{id}")]
        [SwaggerResponse(typeof(AuditActionResult))]
        public virtual IActionResult ProcedureTemplateDeactivateProcedureTemplate([FromRoute][Required]int? id, [FromRoute][Required]string version)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResult));
            string exampleJson = null;
            exampleJson = "{\n  \"errorMessages\" : [ {\n    \"number\" : 0,\n    \"message\" : \"message\",\n    \"isValidationMessage\" : true\n  }, {\n    \"number\" : 0,\n    \"message\" : \"message\",\n    \"isValidationMessage\" : true\n  } ],\n  \"hasValidationErrors\" : true,\n  \"hasErrors\" : true,\n  \"id\" : 6,\n  \"successMessage\" : \"successMessage\"\n}";

                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResult>(exampleJson)
                        : default(AuditActionResult);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="version"></param>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/v{version}/ProcedureTemplate")]
        [ValidateModelState]
        [SwaggerOperation("ProcedureTemplateGetProcedureTemplate")]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfProcedureTemplate))]
        public virtual IActionResult ProcedureTemplateGetProcedureTemplate([FromRoute][Required]string version, [FromQuery]int? id)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfICollectionOfProcedureTemplate));
            string exampleJson = null;
            exampleJson = "\"\"";

                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfICollectionOfProcedureTemplate>(exampleJson)
                        : default(AuditActionResultOfICollectionOfProcedureTemplate);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [Route("/v{version}/ProcedureTemplate")]
        [ValidateModelState]
        [SwaggerOperation("ProcedureTemplateUpdateProcedureTemplate")]
        [SwaggerResponse(typeof(AuditActionResultOfProcedureTemplate))]
        public virtual IActionResult ProcedureTemplateUpdateProcedureTemplate([FromBody]UpdateProcedureTemplateRequest body, [FromRoute][Required]string version)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfProcedureTemplate));
            string exampleJson = null;
            exampleJson = "\"\"";

                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfProcedureTemplate>(exampleJson)
                        : default(AuditActionResultOfProcedureTemplate);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
