/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using NSwag.Annotations;
using MSR.Answer.API.V1.Models;
using MSR.Answer.API.Attributes;
using System.Threading.Tasks;
using System.Collections.Generic;
using MSR.Domain.Commands;
using MSR.Domain.Commanding.Abstractions;
using MSR.Answer.API.V1.Extentions;
using MSR.Domain.Models;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// Procedure step type API
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class ProcedureStepTypeController : BaseApiController
    {
        ICommandDispatcher _dispatcher;

        /// <summary>
        ///
        /// </summary>
        /// <param name="dispatcher"></param>
        public ProcedureStepTypeController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        /// Get procedure step type
        /// </summary>
        /// <param name="version"></param>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<ProcedureStepTypeModel>>))]
        public async Task<IActionResult> GetProcedureStepType([FromQuery]int? id)
        {
            var command = new GetProcedureStepType() { Id = id };
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<ICollection<ProcedureStepTypeModel>>();
        }
    }
}
