/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using NSwag.Annotations;
using MSR.Answer.API.V1.Models;
using MSR.Answer.API.Attributes;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// Procedure template API
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class ProcedureTemplateController : BaseApiController
    {
        /// <summary>
        /// Create a procedure template
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPost]
        [Route("/ProcedureTemplate")]
        [SwaggerResponse(typeof(AuditActionResult<ProcedureTemplate>))]
        public async Task<IActionResult> CreateProcedureTemplate([FromBody]CreateProcedureTemplateRequest body)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete a procedure template
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpDelete]
        [Route("/ProcedureTemplate/{id}")]
        [SwaggerResponse(typeof(AuditActionResult))]
        public virtual IActionResult DeleteProcedureTemplate([FromRoute][Required]int? id)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Get a procedure template
        /// </summary>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/ProcedureTemplate")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<ProcedureTemplate>>))]
        public virtual IActionResult ProcedureTemplateGetProcedureTemplate([FromQuery]int? id)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Update a procedure template
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [Route("/ProcedureTemplate")]
        [SwaggerResponse(typeof(AuditActionResult<ProcedureTemplate>))]
        public async Task<IActionResult> UpdateProcedureTemplate([FromBody]UpdateProcedureTemplateRequest body)
        {
            throw new NotImplementedException();
        }
    }
}
