/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using NSwag.Annotations;
using MSR.Answer.API.V1.Models;

namespace MSR.Answer.API.V1.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ProcedureStepTypeApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="version"></param>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/v{version}/ProcedureStepType")]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfProcedureStepType))]
        public virtual IActionResult ProcedureStepTypeGetProcedureStepType([FromRoute][Required]string version, [FromQuery]int? id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfICollectionOfProcedureStepType));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfICollectionOfProcedureStepType>(exampleJson)
                        : default(AuditActionResultOfICollectionOfProcedureStepType);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
