/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using NSwag.Annotations;
using MSR.Answer.API.V1.Models;
using MSR.Answer.API.Attributes;
using System;
using System.Threading.Tasks;

namespace MSR.Answer.API.V1.Controllers
{ 
    /// <summary>
    /// Procedure step type API
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class ProcedureStepTypeController : BaseApiController
    { 
        /// <summary>
        /// Get procedure step type
        /// </summary>
        /// <param name="version"></param>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/ProcedureStepType")]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfProcedureStepType))]
        public async Task<IActionResult> GetProcedureStepType([FromQuery]int? id)
        { 
            throw new NotImplementedException();
        }
    }
}
