/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.Filters;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Commanding.Abstractions;
using MSR.Domain.Commanding.Enums;
using MSR.Domain.Commands;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// WorkOrderController
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderController : BaseApiController
    {
        private ICommandDispatcher _dispatcher;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="dispatcher"></param>
        public WorkOrderController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        /// Returns a summary of COMPLETED or CANCELLED WorkOrders
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpGet("History")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderGridSummary>>))]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        public async Task<IActionResult> WorkOrderGetHistory([FromRoute][Required]string version)
        {
            var ret = await _dispatcher.DispatchAsync(new GetWorkOrderView(){
                IsHistory = true
            });
            return ret.ToOkObjectResponse<ICollection<WorkOrderModel>>();
        }

        /// <summary>
        /// Returns a summary of WorkOrders IN PROGRESS or WAITING
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpGet("Menu")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderGridSummary>>))]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        public async Task<IActionResult> WorkOrderGetMenu([FromRoute][Required]string version)
        {
            var ret = await _dispatcher.DispatchAsync(new GetWorkOrderView(){
                IsHistory = false
            });
            return ret.ToOkObjectResponse<ICollection<WorkOrderModel>>();
        }

        /// <summary>
        /// This endpoint returns a ViewModel of data from various Domain Objects. Naming is [domainobject][PropertyOfDomainObject]
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200">This endpoint returns a ViewModel of data from various Domain Objects. Naming is [domainobject][PropertyOfDomainObject]</response>
        [HttpGet("Status")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderStatus>>))]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        public virtual IActionResult WorkOrderGetStatus()
        {
            // TODO: MOCKED
            WorkOrderStatus w = new WorkOrderStatus() {
                LocationName = "LocationName",
                ProductName = "ProductName",
                ProcedureName = "ProcedureName",
                PartNumber = "PartNumber",
                WorkOrderSummary = new WorkOrderSummary() {
                    WorkOrderStatus = "In Progress"
                }
            };
            List<WorkOrderStatus> example = new List<WorkOrderStatus>();
            example.Add(w);
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get work order list by id, customerid, locationid, or date
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpGet]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderModel>>))]
        public async Task<IActionResult> GetWorkOrder([FromQuery] GetWorkOrderRequest request)
        {
            var command = request.ToGetWorkOrderCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<ICollection<WorkOrderModel>>();
        }

    }
}
