/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;
using System.ComponentModel.DataAnnotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderTaskController : ControllerBase
    {
        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPost]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskModel>))]
        public virtual IActionResult WorkOrderTaskCreateWorkOrderTask([FromBody]CreateWorkOrderTaskRequest body, [FromRoute][Required]string version)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfWorkOrderTask));
            string exampleJson = null;
            exampleJson = "\"\"";

                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResult<WorkOrderTaskModel>>(exampleJson)
                        : default(AuditActionResult<WorkOrderTaskModel>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskModel>))]
        public virtual IActionResult WorkOrderTaskUpdateWorkOrderTask([FromBody]UpdateWorkOrderTaskRequest body, [FromRoute][Required]string version)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfWorkOrderTask));
            string exampleJson = null;
            exampleJson = "\"\"";

                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResult<WorkOrderTaskModel>>(exampleJson)
                        : default(AuditActionResult<WorkOrderTaskModel>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
