/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;
using System.ComponentModel.DataAnnotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// WorkOrderTaskMonitorController
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderTaskMonitorController : BaseApiController
    {
        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskMonitorModel>))]
        public virtual IActionResult WorkOrderTaskMonitorUpdateWorkOrderTaskMonitor([FromBody]UpdateWorkOrderTaskMonitorRequest body, [FromRoute][Required]string version)
        {
            var example = new WorkOrderTaskMonitorModel() {
                WorkOrderTaskId = 1,
                ProcedureMonitorId = 2,
                NumVal = 333,
                TextVal = "LOOKIEHERE",
                MultiVal = "MULTIPASS",
                SensorMappingId = 1,
                Comment = "Comment This",
                SensorValue = "SensorValue",
                SensorName = "SensorName "
            };
            return new ObjectResult(example);
        }
    }
}
