/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.Filters;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Commanding;
using MSR.Domain.Commanding.Abstractions;
using MSR.Domain.Commanding.Enums;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// WorkOrderController
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderController : BaseApiController
    {
        private ICommandDispatcher _dispatcher;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="dispatcher"></param>
        public WorkOrderController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        /// Returns a summary of COMPLETED or CANCELLED WorkOrders
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpGet("History")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderGridSummary>>))]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        public virtual IActionResult WorkOrderGetHistory([FromRoute][Required]string version)
        {
            List<WorkOrderGridSummary> example = new List<WorkOrderGridSummary>();
            for (int i = 0; i < 100; i++) {
                WorkOrderGridSummary w = new WorkOrderGridSummary() {
                    Id = 1,
                    PurchaseId = 2,
                    WorkOrderItemNumber  = $"WOIN{i}",
                    CustomerName = "CustomerName",
                    LocationName = "LocationName",
                    SerialNumber = "SerialNumber",
                    PurchaseOrderNumber = 3,
                     Quantity = 1234,
                    ScheduledStartDate = DateTime.Now,
                    ScheduledEndDate = DateTime.Now,
                    ActualStartDate = DateTime.Now.AddMinutes(30),
                    ActualEndDate = DateTime.Now.AddMinutes(30),
                    ProductName = "ProductName",
                    ProcedureName = "ProcedureName",
                    Status = "complete",
                    Disposition = "Disposition",
                    CurrentActiveTaskName = "CurrentActiveTaskName",
                    PercentageOfTasksCompleted = (decimal)12.34,
                    PercentageOfExpectedDurationTimeLogged = (decimal)23.45,
                    HasNcr = (i%2) == 0
                };
                example.Add(w);
            }

            var ret = new CommandResponse<ICollection<WorkOrderGridSummary>>(example);
            return ret.ToOkObjectResponse<ICollection<WorkOrderGridSummary>>();
        }

        /// <summary>
        /// Returns a summary of WorkOrders IN PROGRESS or WAITING
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpGet("Menu")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderGridSummary>>))]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        public virtual IActionResult WorkOrderGetMenu([FromRoute][Required]string version)
        {
            List<WorkOrderGridSummary> example = new List<WorkOrderGridSummary>();
            for (int i = 0; i < 100; i++) {
                WorkOrderGridSummary w = new WorkOrderGridSummary() {
                    Id = 1,
                    PurchaseId = 2,
                    WorkOrderItemNumber  = $"WOIN{i}",
                    CustomerName = "CustomerName",
                    LocationName = "LocationName",
                    SerialNumber = "SerialNumber",
                    PurchaseOrderNumber = 3,
                     Quantity = 1234,
                    ScheduledStartDate = DateTime.Now,
                    ScheduledEndDate = DateTime.Now,
                    ActualStartDate = DateTime.Now.AddMinutes(30),
                    ActualEndDate = DateTime.Now.AddMinutes(30),
                    ProductName = "ProductName",
                    ProcedureName = "ProcedureName",
                    Status = "inprogress",
                    Disposition = "Disposition",
                    CurrentActiveTaskName = "CurrentActiveTaskName",
                    PercentageOfTasksCompleted = (decimal)12.34,
                    PercentageOfExpectedDurationTimeLogged = (decimal)23.45,
                    HasNcr = (i%2) == 0
                };
                example.Add(w);
            }

            var ret = new CommandResponse<ICollection<WorkOrderGridSummary>>(example);
            return ret.ToOkObjectResponse<ICollection<WorkOrderGridSummary>>();
        }

        /// <summary>
        /// Returns the WorkOrders that are either waiting to start or in Process.
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200">The WorkOrders that are either waiting to start or in Process</response>
        [HttpGet("Status")]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderStatus>>))]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        public virtual IActionResult WorkOrderGetStatus()
        {
            WorkOrderStatus w = new WorkOrderStatus() {
                LocationName = "LocationName",
                ProductName = "ProductName",
                ProcedureName = "ProcedureName",
                PartNumber = "PartNumber",
                WorkOrderSummary = new WorkOrderSummary() {
                    WorkOrderId = 123,
                    WorkOrderItemNumber = "NUM123",
                    PurchaseOrderLineNumber = "LINE1",
                    WorkOrderPartSerialNumber = "SERIAL1600187570",
                    WorkOrderStatus = "In Progress",
                    WorkOrderAssignedTo = "Frank",
                    WorkOrderHasNcr = true,
                    WorkOrderScheduledEndDate = DateTime.Now.AddDays(1)
                }
            };
            List<WorkOrderStatus> example = new List<WorkOrderStatus>();
            example.Add(w);
            var ret = new CommandResponse<ICollection<WorkOrderStatus>>(example);
            return ret.ToOkObjectResponse<ICollection<WorkOrderStatus>>();
        }

        /// <summary>
        /// Get work order list by id, customerid, locationid, or date
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpGet]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderModel>>))]
        public async Task<IActionResult> GetWorkOrder([FromQuery] GetWorkOrderRequest request)
        {
            var command = request.ToGetWorkOrderCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<ICollection<WorkOrderModel>>();
        }

    }
}
