/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Commanding;
using MSR.Domain.Commanding.Abstractions;
using MSR.Domain.Commands;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// WorkOrderTaskMonitorController
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderTaskMonitorController : BaseApiController
    {
        private ICommandDispatcher _dispatcher;

        /// <summary>
        /// WorkOrderTaskMonitorController Constructor
        /// </summary>
        /// <param name="dispatcher"></param>
        public WorkOrderTaskMonitorController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskMonitorModel>))]
        public async Task<IActionResult> WorkOrderTaskMonitorUpdateWorkOrderTaskMonitor([FromBody] UpdateWorkOrderTaskMonitorRequest body, [FromRoute][Required] string version)
        {
            UpdateWorkOrderTaskMonitor command = body.ToUpdateWorkOrderTaskMonitorCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<WorkOrderTaskMonitorModel>("Work Order Task Monitor Updated");
        }
    }
}
