/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Application.Abstractions;
using MSR.Domain.Commanding.Abstractions;
using MSR.Domain.Commands;
using MSR.Domain.Models;
using MSR.Domain.Views;
using Newtonsoft.Json;
using NSwag.Annotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderPartController : BaseApiController
    {
        private ICommandDispatcher _dispatcher;
        private IWorkOrderPartViewService _viewService;

        /// <summary>
        /// WorkOrderPartController Constructor
        /// </summary>
        /// <param name="dispatcher"></param>
        /// <param name="viewService"></param>
        public WorkOrderPartController(ICommandDispatcher dispatcher, IWorkOrderPartViewService viewService)
        {
            _dispatcher = dispatcher;
            _viewService = viewService;
        }

        [HttpGet]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderPartModel>>))]
        public async Task<IActionResult> Get([FromQuery, Required] GetWorkOrderPartRequest request)
        {
            var command = request.ToGetWorkOrderPartCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<ICollection<WorkOrderPartModel>>();
        }

        /// <summary>
        /// WorkOrderPartUpdateWorkOrderPart
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderPartModel>))]
        public async Task<IActionResult> WorkOrderPartUpdateWorkOrderPart([FromBody] UpdateWorkOrderPartRequest body, [FromRoute][Required] string version)
        {
            UpdateWorkOrderPart command = body.ToUpdateWorkOrderPartCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<WorkOrderPartModel>("Work Order Part Updated");
        }

        [HttpGet("Detail/{id}")]
        [SwaggerResponse(typeof(AuditActionResult<NCRPartWODetailView>))]
        public async Task<IActionResult> GetWorkOrderPartDetails([FromRoute]int id)
        {
            var ret = await _viewService.GetNCRPartWODetail(id);
            return Ok(new AuditActionResult<NCRPartWODetailView>()
            {
                Object = ret
            });
        }
    }
}
