/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Commanding;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderPartController : ControllerBase
    {
        /// <summary>
        /// WorkOrderPartUpdateWorkOrderPart
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderPartModel>))]
        public virtual IActionResult WorkOrderPartUpdateWorkOrderPart([FromBody]UpdateWorkOrderPartRequest body, [FromRoute][Required]string version)
        {
            var example = new WorkOrderPartModel() {
                WorkOrderId = 1,
                PartId = 2,
                ParentId = null,
                SerialNumber = "SERIAL12345",
                Part = new PartModel(),
                WorkOrder = new WorkOrderModel(),
                Children = new List<WorkOrderPartModel>(),
                Parent = null
            };
            var ret = new CommandResponse<WorkOrderPartModel>(example);
            return ret.ToOkObjectResponse<WorkOrderPartModel>();
        }
    }
}
