/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.Filters;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Commanding.Abstractions;
using MSR.Domain.Commanding.Enums;
using MSR.Domain.Commands;
using MSR.Domain.Models;
using NSwag.Annotations;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    /// WorkOrderController 
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderController : BaseApiController
    {
        private ICommandDispatcher _dispatcher;

        public WorkOrderController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        [HttpGet()]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanRead)]
        [SwaggerResponse(typeof(AuditActionResult<ICollection<WorkOrderModel>>))]
        public async Task<IActionResult> GetWorkOrder([FromQuery] GetWorkOrderRequest request)
        {
            var command = request.ToGetWorkOrderCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<ICollection<WorkOrderModel>>();
        }

        [HttpPost]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanCreate)]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderModel>))]
        public async Task<IActionResult> AddWorkOrder(CreateWorkOrderRequest request)
        {
            var command = request.ToCreateWorkOrderCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<WorkOrderModel>("WorkOrder created succesfully");
        }

        [HttpPatch]
        [HasPrivilegeApi("WipStatus", EnumPrivilege.CanEdit)]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderModel>))]
        public async Task<IActionResult> UpdateWorkOrder(UpdateWorkOrderRequest request)
        {
            var command = request.ToUpdateWorkOrderCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<WorkOrderModel>("WorkOrder updated successfully");
        }

        /// <summary>
        /// This endpoint returns a View which is a Summary of WorkOrders for Grids
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200">This endpoint returns a View which is a Summary of WorkOrders for Grids</response>
        [HttpGet]
        [Route("/v{version}/WorkOrder/History")]
        [ValidateModelState]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfWorkOrderGridSummary))]
        public virtual IActionResult WorkOrderGetHistory([FromRoute][Required]string version)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfICollectionOfWorkOrderGridSummary));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfICollectionOfWorkOrderGridSummary>(exampleJson)
                        : default(AuditActionResultOfICollectionOfWorkOrderGridSummary);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// This endpoint returns a View which is a Summary of WorkOrders for Grids
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200">This endpoint returns a View which is a Summary of WorkOrders for Grids</response>
        [HttpGet]
        [Route("/v{version}/WorkOrder/Menu")]
        [ValidateModelState]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfWorkOrderGridSummary))]
        public virtual IActionResult WorkOrderGetMenu([FromRoute][Required]string version)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfICollectionOfWorkOrderGridSummary));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfICollectionOfWorkOrderGridSummary>(exampleJson)
                        : default(AuditActionResultOfICollectionOfWorkOrderGridSummary);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// This endpoint returns a ViewModel of data from various Domain Objects. Naming is [domainobject][PropertyOfDomainObject]
        /// </summary>
        /// <param name="version"></param>
        /// <response code="200">This endpoint returns a ViewModel of data from various Domain Objects. Naming is [domainobject][PropertyOfDomainObject]</response>
        [HttpGet]
        [Route("/v{version}/WorkOrder/Status")]
        [ValidateModelState]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfWorkOrderStatus))]
        public virtual IActionResult WorkOrderGetStatus([FromRoute][Required]string version)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfICollectionOfWorkOrderStatus));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfICollectionOfWorkOrderStatus>(exampleJson)
                        : default(AuditActionResultOfICollectionOfWorkOrderStatus);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="version"></param>
        /// <param name="id"></param>
        /// <param name="customerId"></param>
        /// <param name="locationId"></param>
        /// <param name="invoiceDate"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/v{version}/WorkOrder")]
        [ValidateModelState]
        [SwaggerResponse(typeof(AuditActionResultOfICollectionOfWorkOrderModel))]
        public virtual IActionResult WorkOrderGetWorkOrder([FromRoute][Required]string version, [FromQuery]GetWorkOrderRequest request)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfICollectionOfWorkOrderModel));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfICollectionOfWorkOrderModel>(exampleJson)
                        : default(AuditActionResultOfICollectionOfWorkOrderModel);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
