/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Extentions;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Commanding;
using MSR.Domain.Commanding.Abstractions;
using MSR.Domain.Commands;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderTaskController : ControllerBase
    {
        private ICommandDispatcher _dispatcher;

        /// <summary>
        /// WorkOrderTaskController Constructor
        /// </summary>
        /// <param name="dispatcher"></param>
        public WorkOrderTaskController(ICommandDispatcher dispatcher)
        {
            _dispatcher = dispatcher;
        }

        /// <summary>
        /// WorkOrderTaskCreateWorkOrderTask
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPost]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskModel>))]
        public async Task<IActionResult> WorkOrderTaskCreateWorkOrderTask([FromBody] CreateWorkOrderTaskRequest body)
        {
            CreateWorkOrderTask command = body.ToCreateWorkOrderTaskCommand();

            // some additional defaults
            command.StatusId = 1;
            command.ProcedureStepTypeId = 1;

            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<WorkOrderTaskModel>();
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskModel>))]
        public async Task<IActionResult> WorkOrderTaskUpdateWorkOrderTask([FromBody] UpdateWorkOrderTaskRequest body)
        {
            UpdateWorkOrderTask command = body.ToUpdateWorkOrderTaskCommand();
            var ret = await _dispatcher.DispatchAsync(command);
            return ret.ToOkObjectResponse<WorkOrderTaskModel>();
        }
    }
}
