/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using MSR.Answer.API.Attributes;
using MSR.Answer.API.V1.Models;
using MSR.Domain.Models;
using Newtonsoft.Json;
using NSwag.Annotations;
using System.ComponentModel.DataAnnotations;

namespace MSR.Answer.API.V1.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiVersion("1.0")]
    [VersionedRoute("[controller]")]
    public class WorkOrderTaskController : ControllerBase
    {
        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPost]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskModel>))]
        public virtual IActionResult WorkOrderTaskCreateWorkOrderTask([FromBody]CreateWorkOrderTaskRequest body)
        {
            var example = new WorkOrderTaskModel() {
                WorkOrderId = 1,
                ProcedureStepId = 2,
                ProcedureStepTypeId = 3,
                StatusId = 1
            };
            return new ObjectResult(example);
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [SwaggerResponse(typeof(AuditActionResult<WorkOrderTaskModel>))]
        public virtual IActionResult WorkOrderTaskUpdateWorkOrderTask([FromBody]UpdateWorkOrderTaskRequest body)
        {
            var example = new WorkOrderTaskModel() {
                WorkOrderId = 10,
                ProcedureStepId = 20,
                ProcedureStepTypeId = 30,
                StatusId = 1
            };
            return new ObjectResult(example);
        }
    }
}
