/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using NSwag.Annotations;

namespace MSR.Answer.API.V1.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class WorkOrderTaskMonitorController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version"></param>
        /// <response code="200"></response>
        [HttpPatch]
        [Route("/v{version}/WorkOrderTaskMonitor")]
        [ValidateModelState]
        [SwaggerResponse(typeof(AuditActionResultOfWorkOrderTaskMonitor))]
        public virtual IActionResult WorkOrderTaskMonitorUpdateWorkOrderTaskMonitor([FromBody]UpdateWorkOrderTaskMonitorRequest body, [FromRoute][Required]string version)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(AuditActionResultOfWorkOrderTaskMonitor));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<AuditActionResultOfWorkOrderTaskMonitor>(exampleJson)
                        : default(AuditActionResultOfWorkOrderTaskMonitor);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
