/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class AccountService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5001";
    }

    login(request: SystemLoginRequest, version: string): Observable<AuditActionResultOfString> {
        let url_ = this.baseUrl + "/v{version}/Account/login";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLogin(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLogin(<any>response_);
                } catch (e) {
                    return <Observable<AuditActionResultOfString>><any>_observableThrow(e);
                }
            } else
                return <Observable<AuditActionResultOfString>><any>_observableThrow(response_);
        }));
    }

    protected processLogin(response: HttpResponseBase): Observable<AuditActionResultOfString> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuditActionResultOfString.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<AuditActionResultOfString>(<any>null);
    }

    forgotpassword(request: ForgotPasswordRequest, version: string): Observable<void> {
        let url_ = this.baseUrl + "/v{version}/Account/forgotpassword";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processForgotpassword(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processForgotpassword(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processForgotpassword(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    forgotusername(request: ForgotUserNameRequest, version: string): Observable<void> {
        let url_ = this.baseUrl + "/v{version}/Account/forgotusername";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processForgotusername(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processForgotusername(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processForgotusername(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    resetpassword(request: ResetPasswordRequest, version: string): Observable<void> {
        let url_ = this.baseUrl + "/v{version}/Account/resetpassword";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
            })
        };

        return this.http.request("patch", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processResetpassword(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processResetpassword(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processResetpassword(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }
}

@Injectable()
export class MenuService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5001";
    }

    menu(version: string): Observable<FileResponse | null> {
        let url_ = this.baseUrl + "/v{version}/Menu";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processMenu(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processMenu(<any>response_);
                } catch (e) {
                    return <Observable<FileResponse | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<FileResponse | null>><any>_observableThrow(response_);
        }));
    }

    protected processMenu(response: HttpResponseBase): Observable<FileResponse | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return _observableOf({ fileName: fileName, data: <any>responseBlob, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<FileResponse | null>(<any>null);
    }
}

@Injectable()
export class UserService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5001";
    }

    userGet(id: number | null | undefined, firstName: string | null | undefined, lastName: string | null | undefined, userName: string | null | undefined, title: string | null | undefined, supervisor: number | null | undefined, primaryPhone: string | null | undefined, email: string | null | undefined, version: string): Observable<AuditActionResultOfICollectionOfUser> {
        let url_ = this.baseUrl + "/v{version}/User?";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        if (id !== undefined && id !== null)
            url_ += "Id=" + encodeURIComponent("" + id) + "&";
        if (firstName !== undefined && firstName !== null)
            url_ += "FirstName=" + encodeURIComponent("" + firstName) + "&";
        if (lastName !== undefined && lastName !== null)
            url_ += "LastName=" + encodeURIComponent("" + lastName) + "&";
        if (userName !== undefined && userName !== null)
            url_ += "UserName=" + encodeURIComponent("" + userName) + "&";
        if (title !== undefined && title !== null)
            url_ += "Title=" + encodeURIComponent("" + title) + "&";
        if (supervisor !== undefined && supervisor !== null)
            url_ += "Supervisor=" + encodeURIComponent("" + supervisor) + "&";
        if (primaryPhone !== undefined && primaryPhone !== null)
            url_ += "PrimaryPhone=" + encodeURIComponent("" + primaryPhone) + "&";
        if (email !== undefined && email !== null)
            url_ += "Email=" + encodeURIComponent("" + email) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserGet(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserGet(<any>response_);
                } catch (e) {
                    return <Observable<AuditActionResultOfICollectionOfUser>><any>_observableThrow(e);
                }
            } else
                return <Observable<AuditActionResultOfICollectionOfUser>><any>_observableThrow(response_);
        }));
    }

    protected processUserGet(response: HttpResponseBase): Observable<AuditActionResultOfICollectionOfUser> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuditActionResultOfICollectionOfUser.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<AuditActionResultOfICollectionOfUser>(<any>null);
    }

    userPost(request: CreateUserRequest, version: string): Observable<AuditActionResultOfUser> {
        let url_ = this.baseUrl + "/v{version}/User";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserPost(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserPost(<any>response_);
                } catch (e) {
                    return <Observable<AuditActionResultOfUser>><any>_observableThrow(e);
                }
            } else
                return <Observable<AuditActionResultOfUser>><any>_observableThrow(response_);
        }));
    }

    protected processUserPost(response: HttpResponseBase): Observable<AuditActionResultOfUser> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuditActionResultOfUser.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<AuditActionResultOfUser>(<any>null);
    }

    userPatch(request: UpdateUserRequest, version: string): Observable<AuditActionResultOfUser> {
        let url_ = this.baseUrl + "/v{version}/User";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("patch", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserPatch(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserPatch(<any>response_);
                } catch (e) {
                    return <Observable<AuditActionResultOfUser>><any>_observableThrow(e);
                }
            } else
                return <Observable<AuditActionResultOfUser>><any>_observableThrow(response_);
        }));
    }

    protected processUserPatch(response: HttpResponseBase): Observable<AuditActionResultOfUser> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuditActionResultOfUser.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<AuditActionResultOfUser>(<any>null);
    }

    loggedInUser(version: string): Observable<AuditActionResultOfUser> {
        let url_ = this.baseUrl + "/v{version}/User/LoggedInUser";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLoggedInUser(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLoggedInUser(<any>response_);
                } catch (e) {
                    return <Observable<AuditActionResultOfUser>><any>_observableThrow(e);
                }
            } else
                return <Observable<AuditActionResultOfUser>><any>_observableThrow(response_);
        }));
    }

    protected processLoggedInUser(response: HttpResponseBase): Observable<AuditActionResultOfUser> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuditActionResultOfUser.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<AuditActionResultOfUser>(<any>null);
    }

    userDelete(accountId: number, version: string): Observable<void> {
        let url_ = this.baseUrl + "/v{version}/User/{accountId}";
        if (accountId === undefined || accountId === null)
            throw new Error("The parameter 'accountId' must be defined.");
        url_ = url_.replace("{accountId}", encodeURIComponent("" + accountId));
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processUserDelete(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processUserDelete(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processUserDelete(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }
}

@Injectable()
export class WorkflowService {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5001";
    }

    pending(version: string): Observable<AuditActionResultOfPendingApprovalNotification> {
        let url_ = this.baseUrl + "/v{version}/Workflow/pending";
        if (version === undefined || version === null)
            throw new Error("The parameter 'version' must be defined.");
        url_ = url_.replace("{version}", encodeURIComponent("" + version));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processPending(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processPending(<any>response_);
                } catch (e) {
                    return <Observable<AuditActionResultOfPendingApprovalNotification>><any>_observableThrow(e);
                }
            } else
                return <Observable<AuditActionResultOfPendingApprovalNotification>><any>_observableThrow(response_);
        }));
    }

    protected processPending(response: HttpResponseBase): Observable<AuditActionResultOfPendingApprovalNotification> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = AuditActionResultOfPendingApprovalNotification.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<AuditActionResultOfPendingApprovalNotification>(<any>null);
    }
}

export class AuditActionResult implements IAuditActionResult {
    returnedObject?: any | undefined;
    successMessage?: string | undefined;
    errorMessages?: ErrorMessage[] | undefined;
    id!: number;
    hasErrors!: boolean;
    hasValidationErrors!: boolean;

    constructor(data?: IAuditActionResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.returnedObject = _data["returnedObject"];
            this.successMessage = _data["successMessage"];
            if (Array.isArray(_data["errorMessages"])) {
                this.errorMessages = [] as any;
                for (let item of _data["errorMessages"])
                    this.errorMessages!.push(ErrorMessage.fromJS(item));
            }
            this.id = _data["id"];
            this.hasErrors = _data["hasErrors"];
            this.hasValidationErrors = _data["hasValidationErrors"];
        }
    }

    static fromJS(data: any): AuditActionResult {
        data = typeof data === 'object' ? data : {};
        let result = new AuditActionResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["returnedObject"] = this.returnedObject;
        data["successMessage"] = this.successMessage;
        if (Array.isArray(this.errorMessages)) {
            data["errorMessages"] = [];
            for (let item of this.errorMessages)
                data["errorMessages"].push(item.toJSON());
        }
        data["id"] = this.id;
        data["hasErrors"] = this.hasErrors;
        data["hasValidationErrors"] = this.hasValidationErrors;
        return data; 
    }
}

export interface IAuditActionResult {
    returnedObject?: any | undefined;
    successMessage?: string | undefined;
    errorMessages?: ErrorMessage[] | undefined;
    id: number;
    hasErrors: boolean;
    hasValidationErrors: boolean;
}

export class AuditActionResultOfString extends AuditActionResult implements IAuditActionResultOfString {
    object?: string | undefined;
    returnedObject?: any | undefined;

    constructor(data?: IAuditActionResultOfString) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.object = _data["object"];
            this.returnedObject = _data["returnedObject"];
        }
    }

    static fromJS(data: any): AuditActionResultOfString {
        data = typeof data === 'object' ? data : {};
        let result = new AuditActionResultOfString();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["object"] = this.object;
        data["returnedObject"] = this.returnedObject;
        super.toJSON(data);
        return data; 
    }
}

export interface IAuditActionResultOfString extends IAuditActionResult {
    object?: string | undefined;
    returnedObject?: any | undefined;
}

export class ErrorMessage implements IErrorMessage {
    number!: number;
    message?: string | undefined;
    exception?: Exception | undefined;
    isValidationMessage!: boolean;

    constructor(data?: IErrorMessage) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.number = _data["number"];
            this.message = _data["message"];
            this.exception = _data["exception"] ? Exception.fromJS(_data["exception"]) : <any>undefined;
            this.isValidationMessage = _data["isValidationMessage"];
        }
    }

    static fromJS(data: any): ErrorMessage {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorMessage();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["number"] = this.number;
        data["message"] = this.message;
        data["exception"] = this.exception ? this.exception.toJSON() : <any>undefined;
        data["isValidationMessage"] = this.isValidationMessage;
        return data; 
    }
}

export interface IErrorMessage {
    number: number;
    message?: string | undefined;
    exception?: Exception | undefined;
    isValidationMessage: boolean;
}

export class Exception implements IException {
    stackTrace?: string | undefined;
    message!: string;
    innerException?: Exception | undefined;
    source?: string | undefined;

    constructor(data?: IException) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.stackTrace = _data["StackTrace"];
            this.message = _data["Message"];
            this.innerException = _data["InnerException"] ? Exception.fromJS(_data["InnerException"]) : <any>undefined;
            this.source = _data["Source"];
        }
    }

    static fromJS(data: any): Exception {
        data = typeof data === 'object' ? data : {};
        let result = new Exception();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["StackTrace"] = this.stackTrace;
        data["Message"] = this.message;
        data["InnerException"] = this.innerException ? this.innerException.toJSON() : <any>undefined;
        data["Source"] = this.source;
        return data; 
    }
}

export interface IException {
    stackTrace?: string | undefined;
    message: string;
    innerException?: Exception | undefined;
    source?: string | undefined;
}

export class SystemLoginRequest implements ISystemLoginRequest {
    userName!: string;
    password!: string;

    constructor(data?: ISystemLoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): SystemLoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SystemLoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["password"] = this.password;
        return data; 
    }
}

export interface ISystemLoginRequest {
    userName: string;
    password: string;
}

export class ForgotPasswordRequest implements IForgotPasswordRequest {
    userName!: string;

    constructor(data?: IForgotPasswordRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
        }
    }

    static fromJS(data: any): ForgotPasswordRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ForgotPasswordRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        return data; 
    }
}

export interface IForgotPasswordRequest {
    userName: string;
}

export class ForgotUserNameRequest implements IForgotUserNameRequest {
    email!: string;

    constructor(data?: IForgotUserNameRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
        }
    }

    static fromJS(data: any): ForgotUserNameRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ForgotUserNameRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        return data; 
    }
}

export interface IForgotUserNameRequest {
    email: string;
}

export class ResetPasswordRequest implements IResetPasswordRequest {
    token!: string;
    newPassword!: string;

    constructor(data?: IResetPasswordRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.token = _data["token"];
            this.newPassword = _data["newPassword"];
        }
    }

    static fromJS(data: any): ResetPasswordRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ResetPasswordRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["token"] = this.token;
        data["newPassword"] = this.newPassword;
        return data; 
    }
}

export interface IResetPasswordRequest {
    token: string;
    newPassword: string;
}

export class AuditActionResultOfICollectionOfUser extends AuditActionResult implements IAuditActionResultOfICollectionOfUser {
    object?: User[] | undefined;
    returnedObject?: any | undefined;

    constructor(data?: IAuditActionResultOfICollectionOfUser) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["object"])) {
                this.object = [] as any;
                for (let item of _data["object"])
                    this.object!.push(User.fromJS(item));
            }
            this.returnedObject = _data["returnedObject"];
        }
    }

    static fromJS(data: any): AuditActionResultOfICollectionOfUser {
        data = typeof data === 'object' ? data : {};
        let result = new AuditActionResultOfICollectionOfUser();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.object)) {
            data["object"] = [];
            for (let item of this.object)
                data["object"].push(item.toJSON());
        }
        data["returnedObject"] = this.returnedObject;
        super.toJSON(data);
        return data; 
    }
}

export interface IAuditActionResultOfICollectionOfUser extends IAuditActionResult {
    object?: User[] | undefined;
    returnedObject?: any | undefined;
}

export class User implements IUser {
    id!: number;
    isActive!: boolean;
    userRoleId?: string | undefined;
    userName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    title?: string | undefined;
    email?: string | undefined;
    securityStamp?: string | undefined;
    phone?: string | undefined;
    supervisorId?: number | undefined;
    locationId!: number;
    isAnswerUser!: boolean;
    customerId!: number;
    lockoutEndDateUtc?: Date | undefined;
    lockoutEnabled!: boolean;
    accessFailedCount!: number;
    timeZoneId!: number;
    lastUpdatedOn!: Date;
    lastUpdatedBy?: number | undefined;
    createdOn!: Date;
    createdBy?: number | undefined;
    roles?: Role[] | undefined;

    constructor(data?: IUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.isActive = _data["isActive"];
            this.userRoleId = _data["userRoleId"];
            this.userName = _data["userName"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.title = _data["title"];
            this.email = _data["email"];
            this.securityStamp = _data["securityStamp"];
            this.phone = _data["phone"];
            this.supervisorId = _data["supervisorId"];
            this.locationId = _data["locationId"];
            this.isAnswerUser = _data["isAnswerUser"];
            this.customerId = _data["customerId"];
            this.lockoutEndDateUtc = _data["lockoutEndDateUtc"] ? new Date(_data["lockoutEndDateUtc"].toString()) : <any>undefined;
            this.lockoutEnabled = _data["lockoutEnabled"];
            this.accessFailedCount = _data["accessFailedCount"];
            this.timeZoneId = _data["timeZoneId"];
            this.lastUpdatedOn = _data["lastUpdatedOn"] ? new Date(_data["lastUpdatedOn"].toString()) : <any>undefined;
            this.lastUpdatedBy = _data["lastUpdatedBy"];
            this.createdOn = _data["createdOn"] ? new Date(_data["createdOn"].toString()) : <any>undefined;
            this.createdBy = _data["createdBy"];
            if (Array.isArray(_data["roles"])) {
                this.roles = [] as any;
                for (let item of _data["roles"])
                    this.roles!.push(Role.fromJS(item));
            }
        }
    }

    static fromJS(data: any): User {
        data = typeof data === 'object' ? data : {};
        let result = new User();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["isActive"] = this.isActive;
        data["userRoleId"] = this.userRoleId;
        data["userName"] = this.userName;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["title"] = this.title;
        data["email"] = this.email;
        data["securityStamp"] = this.securityStamp;
        data["phone"] = this.phone;
        data["supervisorId"] = this.supervisorId;
        data["locationId"] = this.locationId;
        data["isAnswerUser"] = this.isAnswerUser;
        data["customerId"] = this.customerId;
        data["lockoutEndDateUtc"] = this.lockoutEndDateUtc ? this.lockoutEndDateUtc.toISOString() : <any>undefined;
        data["lockoutEnabled"] = this.lockoutEnabled;
        data["accessFailedCount"] = this.accessFailedCount;
        data["timeZoneId"] = this.timeZoneId;
        data["lastUpdatedOn"] = this.lastUpdatedOn ? this.lastUpdatedOn.toISOString() : <any>undefined;
        data["lastUpdatedBy"] = this.lastUpdatedBy;
        data["createdOn"] = this.createdOn ? this.createdOn.toISOString() : <any>undefined;
        data["createdBy"] = this.createdBy;
        if (Array.isArray(this.roles)) {
            data["roles"] = [];
            for (let item of this.roles)
                data["roles"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IUser {
    id: number;
    isActive: boolean;
    userRoleId?: string | undefined;
    userName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    title?: string | undefined;
    email?: string | undefined;
    securityStamp?: string | undefined;
    phone?: string | undefined;
    supervisorId?: number | undefined;
    locationId: number;
    isAnswerUser: boolean;
    customerId: number;
    lockoutEndDateUtc?: Date | undefined;
    lockoutEnabled: boolean;
    accessFailedCount: number;
    timeZoneId: number;
    lastUpdatedOn: Date;
    lastUpdatedBy?: number | undefined;
    createdOn: Date;
    createdBy?: number | undefined;
    roles?: Role[] | undefined;
}

export class Role implements IRole {
    name?: string | undefined;
    isCertificationRole?: boolean | undefined;
    menus?: MenuItem[] | undefined;

    constructor(data?: IRole) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.isCertificationRole = _data["isCertificationRole"];
            if (Array.isArray(_data["menus"])) {
                this.menus = [] as any;
                for (let item of _data["menus"])
                    this.menus!.push(MenuItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Role {
        data = typeof data === 'object' ? data : {};
        let result = new Role();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["isCertificationRole"] = this.isCertificationRole;
        if (Array.isArray(this.menus)) {
            data["menus"] = [];
            for (let item of this.menus)
                data["menus"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IRole {
    name?: string | undefined;
    isCertificationRole?: boolean | undefined;
    menus?: MenuItem[] | undefined;
}

export class MenuItem implements IMenuItem {
    url?: string | undefined;
    name?: string | undefined;
    info?: string | undefined;
    icon?: string | undefined;
    orderNumber!: number;
    menuGroup?: MenuGroup | undefined;
    permissions?: number[] | undefined;
    enumMenuItem!: EnumMenuItem;

    constructor(data?: IMenuItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.url = _data["url"];
            this.name = _data["name"];
            this.info = _data["info"];
            this.icon = _data["icon"];
            this.orderNumber = _data["orderNumber"];
            this.menuGroup = _data["menuGroup"] ? MenuGroup.fromJS(_data["menuGroup"]) : <any>undefined;
            if (Array.isArray(_data["permissions"])) {
                this.permissions = [] as any;
                for (let item of _data["permissions"])
                    this.permissions!.push(item);
            }
            this.enumMenuItem = _data["enumMenuItem"];
        }
    }

    static fromJS(data: any): MenuItem {
        data = typeof data === 'object' ? data : {};
        let result = new MenuItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["url"] = this.url;
        data["name"] = this.name;
        data["info"] = this.info;
        data["icon"] = this.icon;
        data["orderNumber"] = this.orderNumber;
        data["menuGroup"] = this.menuGroup ? this.menuGroup.toJSON() : <any>undefined;
        if (Array.isArray(this.permissions)) {
            data["permissions"] = [];
            for (let item of this.permissions)
                data["permissions"].push(item);
        }
        data["enumMenuItem"] = this.enumMenuItem;
        return data; 
    }
}

export interface IMenuItem {
    url?: string | undefined;
    name?: string | undefined;
    info?: string | undefined;
    icon?: string | undefined;
    orderNumber: number;
    menuGroup?: MenuGroup | undefined;
    permissions?: number[] | undefined;
    enumMenuItem: EnumMenuItem;
}

export class MenuGroup implements IMenuGroup {
    url?: string | undefined;
    name?: string | undefined;
    info?: string | undefined;
    icon?: string | undefined;
    orderNumber!: number;

    constructor(data?: IMenuGroup) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.url = _data["url"];
            this.name = _data["name"];
            this.info = _data["info"];
            this.icon = _data["icon"];
            this.orderNumber = _data["orderNumber"];
        }
    }

    static fromJS(data: any): MenuGroup {
        data = typeof data === 'object' ? data : {};
        let result = new MenuGroup();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["url"] = this.url;
        data["name"] = this.name;
        data["info"] = this.info;
        data["icon"] = this.icon;
        data["orderNumber"] = this.orderNumber;
        return data; 
    }
}

export interface IMenuGroup {
    url?: string | undefined;
    name?: string | undefined;
    info?: string | undefined;
    icon?: string | undefined;
    orderNumber: number;
}

export enum EnumMenuItem {
    AdminCostSettings = 0,
    ApprovalGroups = 1,
    ApprovalStages = 2,
    ApprovalWorkflows = 3,
    CustomersDepartments = 4,
    Documents = 5,
    EquipmentMaintenance = 6,
    Financial = 7,
    FreeformQuote = 8,
    HelpPages = 9,
    Invoices = 10,
    Locations = 11,
    Monitors = 12,
    Operational = 13,
    Parts = 14,
    PendingApprovals = 15,
    ProcedureTypes = 16,
    PurchaseOrders = 17,
    Purchases = 18,
    QuotesProducts = 19,
    Reports = 20,
    RoleModulePermission = 21,
    RunnableProcedures = 22,
    SupportTicket = 23,
    Templates = 24,
    TrainingCertifications = 25,
    UserRoles = 26,
    Users = 27,
    WIPHistory = 28,
    WIPMenu = 29,
    WipStatus = 30,
}

export class AuditActionResultOfUser extends AuditActionResult implements IAuditActionResultOfUser {
    object?: User | undefined;
    returnedObject?: any | undefined;

    constructor(data?: IAuditActionResultOfUser) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.object = _data["object"] ? User.fromJS(_data["object"]) : <any>undefined;
            this.returnedObject = _data["returnedObject"];
        }
    }

    static fromJS(data: any): AuditActionResultOfUser {
        data = typeof data === 'object' ? data : {};
        let result = new AuditActionResultOfUser();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["object"] = this.object ? this.object.toJSON() : <any>undefined;
        data["returnedObject"] = this.returnedObject;
        super.toJSON(data);
        return data; 
    }
}

export interface IAuditActionResultOfUser extends IAuditActionResult {
    object?: User | undefined;
    returnedObject?: any | undefined;
}

export class CreateUserRequest implements ICreateUserRequest {
    userName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    title?: string | undefined;
    email?: string | undefined;
    securityStamp?: string | undefined;
    phone?: string | undefined;
    supervisorId?: number | undefined;
    locationId?: number | undefined;
    isActive!: boolean;
    isAnswerUser?: boolean | undefined;
    customerId?: number | undefined;
    lockoutEndDateUtc?: Date | undefined;
    lockoutEnabled!: boolean;
    accessFailedCount!: number;
    timeZoneId?: number | undefined;

    constructor(data?: ICreateUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userName = _data["userName"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.title = _data["title"];
            this.email = _data["email"];
            this.securityStamp = _data["securityStamp"];
            this.phone = _data["phone"];
            this.supervisorId = _data["supervisorId"];
            this.locationId = _data["locationId"];
            this.isActive = _data["isActive"];
            this.isAnswerUser = _data["isAnswerUser"];
            this.customerId = _data["customerId"];
            this.lockoutEndDateUtc = _data["lockoutEndDateUtc"] ? new Date(_data["lockoutEndDateUtc"].toString()) : <any>undefined;
            this.lockoutEnabled = _data["lockoutEnabled"];
            this.accessFailedCount = _data["accessFailedCount"];
            this.timeZoneId = _data["timeZoneId"];
        }
    }

    static fromJS(data: any): CreateUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userName"] = this.userName;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["title"] = this.title;
        data["email"] = this.email;
        data["securityStamp"] = this.securityStamp;
        data["phone"] = this.phone;
        data["supervisorId"] = this.supervisorId;
        data["locationId"] = this.locationId;
        data["isActive"] = this.isActive;
        data["isAnswerUser"] = this.isAnswerUser;
        data["customerId"] = this.customerId;
        data["lockoutEndDateUtc"] = this.lockoutEndDateUtc ? this.lockoutEndDateUtc.toISOString() : <any>undefined;
        data["lockoutEnabled"] = this.lockoutEnabled;
        data["accessFailedCount"] = this.accessFailedCount;
        data["timeZoneId"] = this.timeZoneId;
        return data; 
    }
}

export interface ICreateUserRequest {
    userName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    title?: string | undefined;
    email?: string | undefined;
    securityStamp?: string | undefined;
    phone?: string | undefined;
    supervisorId?: number | undefined;
    locationId?: number | undefined;
    isActive: boolean;
    isAnswerUser?: boolean | undefined;
    customerId?: number | undefined;
    lockoutEndDateUtc?: Date | undefined;
    lockoutEnabled: boolean;
    accessFailedCount: number;
    timeZoneId?: number | undefined;
}

export class UpdateUserRequest extends CreateUserRequest implements IUpdateUserRequest {
    id!: number;

    constructor(data?: IUpdateUserRequest) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.id = _data["id"];
        }
    }

    static fromJS(data: any): UpdateUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        super.toJSON(data);
        return data; 
    }
}

export interface IUpdateUserRequest extends ICreateUserRequest {
    id: number;
}

export class AuditActionResultOfPendingApprovalNotification extends AuditActionResult implements IAuditActionResultOfPendingApprovalNotification {
    object?: PendingApprovalNotification | undefined;
    returnedObject?: any | undefined;

    constructor(data?: IAuditActionResultOfPendingApprovalNotification) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.object = _data["object"] ? PendingApprovalNotification.fromJS(_data["object"]) : <any>undefined;
            this.returnedObject = _data["returnedObject"];
        }
    }

    static fromJS(data: any): AuditActionResultOfPendingApprovalNotification {
        data = typeof data === 'object' ? data : {};
        let result = new AuditActionResultOfPendingApprovalNotification();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["object"] = this.object ? this.object.toJSON() : <any>undefined;
        data["returnedObject"] = this.returnedObject;
        super.toJSON(data);
        return data; 
    }
}

export interface IAuditActionResultOfPendingApprovalNotification extends IAuditActionResult {
    object?: PendingApprovalNotification | undefined;
    returnedObject?: any | undefined;
}

export class PendingApprovalNotification implements IPendingApprovalNotification {
    customers!: number;
    locations!: number;
    parts!: number;
    procedures!: number;
    purchaseOrders!: number;
    users!: number;

    constructor(data?: IPendingApprovalNotification) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.customers = _data["customers"];
            this.locations = _data["locations"];
            this.parts = _data["parts"];
            this.procedures = _data["procedures"];
            this.purchaseOrders = _data["purchaseOrders"];
            this.users = _data["users"];
        }
    }

    static fromJS(data: any): PendingApprovalNotification {
        data = typeof data === 'object' ? data : {};
        let result = new PendingApprovalNotification();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["customers"] = this.customers;
        data["locations"] = this.locations;
        data["parts"] = this.parts;
        data["procedures"] = this.procedures;
        data["purchaseOrders"] = this.purchaseOrders;
        data["users"] = this.users;
        return data; 
    }
}

export interface IPendingApprovalNotification {
    customers: number;
    locations: number;
    parts: number;
    procedures: number;
    purchaseOrders: number;
    users: number;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}