version: 0.2

env:
  git-credential-helper: yes
  variables:
    REGION: "us-west-2"
    DOCKERFILE: "MSR.Answer.API/Dockerfile"
    ECR_REPO_RP: "msr-api"
    TAG: 'latest'

phases:
  build:
    commands:
      - echo Git commit hash $TAG
      - echo Build started on `date` for Answer3 API
      - echo Building the API Docker image...
      - docker build -f $DOCKERFILE .
      - echo Build completed on `date`