version: 0.2

env:
  git-credential-helper: yes
  variables:
    REGION: "us-west-2"
    UI_BUILD_ENV: "builddevprodsetting"
    ECR_REPO_RP: "msr-portal-ui"
    TAG: 'latest'
  parameter-store:
    AWS_ACCESS_KEY_ID_PARAM: /JENKINS/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY_PARAM: /JENKINS/AWS_SECRET_ACCESS_KEY

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URL

  build:
    commands:
      - echo Git commit hash $TAG
      - echo Build started on `date`
      - echo Building Portal UI Docker image...
      - cd MSR.UI/MSR.UI.Portal && docker build --build-arg ENV=$UI_BUILD_ENV .
