CREATE PROCEDURE [dbo].[GetMonitorLabelTsrDetails]
	@fillId VARCHAR(50)
AS
	DECLARE 
	@purchaseItemId VARCHAR(50),
	@purchaseHistoryId VARCHAR(50);

	SELECT @purchaseItemId = PURCH_ITEM_ID FROM A_FILLS WHERE ID = @fillId;
	SELECT TOP 1 @purchaseHistoryId = PURCHASE_HIST_ID FROM A_ORDER_ITEMS WHERE ID = @purchaseItemId AND PURCHASE_HIST_ID IS NOT NULL ORDER BY DRCM;
	SELECT COMPANY_PART_NUMBER, PART_DESC, PURCH_ITEM_ID, DESCRIPTION, LATEST_REQUESTEE_NAME, ACTUAL_STOP_DATE, TASK_DESCRIPTION FROM A_V_MONITOR_LABEL_PURCHASE_ITEMS WHERE PURCHASE_HIST_ID = @purchaseHistoryId AND PURCH_ITEM_ID = @purchaseItemId