create PROCEDURE [dbo].[Portal_DeleteWorkItemImagesById1]
	@fileLinkId nvarchar(50),
	@strNTLogin varchar(50)
AS
BEGIN
	
	SET NOCOUNT ON;

	DECLARE @FileId nvarchar(100),@Id NVARCHAR(100)


	UPDATE A_TASK_REF_FILES SET 
	STATUS = 'DELETED', 
	DRCM = getDate(), 
	DATE_DELETED = getDate(),
	DELETED_BY = @strNTLogin,
	DELETED_BY_NAME = (SELECT FULL_NAME FROM A_V_PEOPLE_APPROVED_DATA WHERE ID = @strNTLogin),
	MODBY = @strNTLogin 
	WHERE ID = @fileLinkId

	SELECT @FileId=FILE_ID FROM A_TASK_REF_FILES 
	WHERE ID=@fileLinkId

	SELECT @Id= ID FROM A_ACTUAL_PARTS_RELATED_FILES 
	WHERE FILE_ID=@FileId

	UPDATE A_ACTUAL_PARTS_RELATED_FILES SET 
	STATUS = 'DELETED', 
	DRCM = GETDATE(),
	DATE_DELETED = GETDATE(),
	DELETED_BY = @strNTLogin, 
	MODBY = @strNTLogin 
	WHERE ID = @Id
END