CREATE PROCEDURE [dbo].[Portal_GetDeliveryTsrDetails]
	@FILLID VARCHAR(50)
AS

DECLARE @PURCHASEITEMID VARCHAR(50)
DECLARE @PURCHASEHISTORYID VARCHAR(50)
DECLARE @COMPANYID VARCHAR(50)
DECLARE @GETDATE DATETIME

SET @GETDATE = GETDATE();

SELECT @PURCHASEITEMID = F.PURCH_ITEM_ID
FROM A_FILLS F
WHERE F.ID = @FILLID;

SELECT TOP 1 @PURCHASEHISTORYID = OI.PURCHASE_HIST_ID
FROM A_ORDER_ITEMS OI
WHERE	OI.ID = @PURCHASEITEMID
AND		OI.PURCHASE_HIST_ID IS NOT NULL
ORDER BY OI.DRCM;

SELECT P.OBJECT_ID AS PURCHASENUMBER
	, P.ROOT_CO_NAME AS SHIPFROM
	, P.CUST_PURCH_NUM AS CUSTOMERPO
	, CONVERT(VARCHAR(10), @GETDATE, 101) + ' ' + LTRIM(RIGHT(CONVERT(CHAR(20), @GETDATE, 22), 11)) AS SHIPDATE
FROM A_V_PURCHASES_WITH_SUPPLIER_QUOTES P
WHERE P.PURCH_HIST_ID = @PURCHASEHISTORYID

UPDATE A_ORDER_ITEMS SET
SHIP_DATE = @GETDATE
WHERE ID = @PURCHASEITEMID;

SELECT CA.[NAME] AS COMPANYNAME
	, CONCAT(DT.PROD_NAME, '-', DT.PROC_NAME) AS [DESCRIPTION]
	, DT.MATERIAL_TRANSFER_TICKET_NUMBER
	, DT.CUST_LINE_ITEM AS CUSTLINEITEM
	, DT.PURCHASE_QTY AS QUANTITY
	, DT.PURCH_ITEM_ID AS CUSTOMERWOITEMNUMBER
	, DT.COMPANY_PART_NUMBER AS COMPANYPARTNUMBER
	, DT.SERIAL AS SERIAL
	, DT.MATERIAL_TRANSFER_TICKET_NUMBER AS MATERIALTRANSFERTICKETNUMBER
FROM A_V_DELIVERY_TICKET_PURCH_ITEM_INFO DT
JOIN A_V_COMPANIES_APPROVED_DATA_QUICK CA ON DT.ACCT_CUSTOMER = CA.ID
WHERE	DT.PURCHASE_HIST_ID = @PURCHASEHISTORYID 
AND		DT.PURCH_ITEM_ID = @PURCHASEITEMID