CREATE PROCEDURE [dbo].[Portal_UpdateOrderItem]
	@DUE_DATE DATETIME = NULL,
	@QTY FLOAT,
	@CUST_LINE_ITEM VARCHAR(50) = NULL,
	@MATERIAL_TRANSFER_TICKET_NUMBER VARCHAR(50) = NULL,
	@ID VARCHAR(50)
AS 

UPDATE A_ORDER_ITEMS SET
DUE_DATE = @DUE_DATE,
QTY = @QTY,
CUST_LINE_ITEM = @CUST_LINE_ITEM,
MATERIAL_TRANSFER_TICKET_NUMBER = @MATERIAL_TRANSFER_TICKET_NUMBER
WHERE ID = @ID
