CREATE PROCEDURE [dbo].[Portal_GetPurchaseItemDetails]
	@FILEID INT
AS

--DECLARE @OBJECTID VARCHAR(50)

--SELECT @OBJECTID = FILL_OBJ_ID
--FROM A_V_FILLS_SEARCH WITH (NOLOCK)
--WHERE ID = @FILEID

SELECT FILL_OBJ_DESC AS FILLOBJDESC
	, CUST_NAME AS CUSTOMERNAME
	, PROD_NAME AS PRODUCTNAME
	, PROC_NAME AS PROCEDURENAME
	, PURCH_ITEM_ID AS PURCHITEMID
	, FILL_QTY AS QTY
	, FILL_OBJ_ID AS FILLOBJECTID
	, PROC_ID AS PROCID
	, PROCOBJID
	, REV AS REV
FROM A_V_FILLS_SEARCH WITH (NOLOCK)
WHERE ID = @FILEID

SELECT [NAME]
FROM A_V_ACTUAL_PARTS_APPROVED_DATA WITH (NOLOCK)
--WHERE PARENT_ID = @OBJECTID
WHERE PARENT_ID = (SELECT TOP 1 FILL_OBJ_ID FROM A_V_FILLS_SEARCH WITH (NOLOCK) WHERE ID = @FILEID)

--CREATE TABLE #TEMPTASKS (ID VARCHAR(50))
--INSERT INTO #TEMPTASKS 
--	SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WITH (NOLOCK) WHERE FILL_ITEM_ID = @FILEID
	
--WHILE EXISTS(SELECT * FROM 	A_TASKS WHERE PARENT_ID COLLATE DATABASE_DEFAULT IN (SELECT ID FROM #TEMPTASKS) AND ID COLLATE DATABASE_DEFAULT NOT IN (SELECT ID FROM #TEMPTASKS))
--BEGIN
--	INSERT INTO #TEMPTASKS 
--		SELECT ID FROM A_TASKS WITH (NOLOCK) WHERE PARENT_ID COLLATE DATABASE_DEFAULT IN 
--		(SELECT ID FROM #TEMPTASKS) AND ID COLLATE DATABASE_DEFAULT NOT IN (SELECT ID FROM #TEMPTASKS)
--END

;WITH TASK_CTE (TASK_ID, PARENT_TASK_ID, TASKTITLE, [LEVEL], [TASK_PATH])
AS
(
SELECT ID, PARENT_ID, TITLE, 0 AS [LEVEL], CAST(ID AS VARCHAR(255)) AS [TASK_PATH]
FROM A_TASKS
WHERE ID IN (SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WITH (NOLOCK) WHERE FILL_ITEM_ID = @FILEID)

UNION ALL

SELECT T.ID, T.PARENT_ID, T.TITLE, [LEVEL] + 1, CAST([TASK_PATH] + '.' + CAST(T.ID AS VARCHAR(255)) AS VARCHAR(255))
FROM A_TASKS T
INNER JOIN TASK_CTE TC ON TC.TASK_ID = T.PARENT_ID
-- WHERE PARENT_ID = 161715
)

-- USE THE CTE TO GET ALL SUPPLIERS IN A SUPPLY CHAIN WITH LEVELS

--SELECT T.*, P.*
SELECT DISTINCT [DESCRIPTION] AS [DESCRIPTION]
	, [DESCRIPTION] RAWDESCRIPTION
	, DBO.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID AS ORDERER
	, [PARENT_ID]
	, [STEP_ID] AS STEPID
	, [STATUS]
	, [REQUESTOR]
	, [COMPLETED_BY]
	, [PROC_HIST_ID]
	, [PH_STEP_ID] AS PHSTEPID
	, [PRINT_ORDER]
	, [RECURSION_NUMBER]
	, [HAS_SURVEY]
	, [HAS_CHILD]
	, [HAS_REF_PROC]
	, [HAS_FILE]
	, [SYSTEM_TASK]
	, [HAS_MONITOR]
	, [REQUESTEE_ID]
	, [GROUP_REQUESTEE_ID]
	, CHILD_STATUS
	, LATEST_REQUESTEE_NAME
	, TITLE
	, ROLES
	, TASK_PATH
FROM TASK_CTE T
INNER JOIN A_V_TASKS_WITH_PROCEDURE_STEP_DATA P ON T.TASK_ID = P.STEP_ID
ORDER BY TASK_PATH

--SELECT DISTINCT 
-- [DESCRIPTION] AS DESCRIPTION,
-- [DESCRIPTION] RAWDESCRIPTION,
-- DBO.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID AS ORDERER,[PARENT_ID], [STEP_ID] AS STEPID, [STATUS], [REQUESTOR], [COMPLETED_BY],[PROC_HIST_ID], [PH_STEP_ID] AS PHSTEPID, 
--[PRINT_ORDER], [RECURSION_NUMBER], [HAS_SURVEY], [HAS_CHILD], [HAS_REF_PROC], [HAS_FILE], 
--[SYSTEM_TASK], [HAS_MONITOR], [REQUESTEE_ID], [GROUP_REQUESTEE_ID],
--CHILD_STATUS, LATEST_REQUESTEE_NAME,TITLE,
--ROLES
--FROM A_V_TASKS_WITH_PROCEDURE_STEP_DATA WITH (NOLOCK) 
--	WHERE STEP_ID COLLATE DATABASE_DEFAULT IN (SELECT T1.ID FROM #TEMPTASKS T1)
--ORDER BY DBO.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID, PRINT_ORDER

GO