CREATE PROCEDURE [dbo].[Portal_GetDeliveryTsrDetails]
	@fillId VARCHAR(50)
AS
	DECLARE 
	@purchaseItemId VARCHAR(50),
	@purchaseHistoryId VARCHAR(50),
	@companyId VARCHAR(50),
	@getDate DATETIME;

	SET @getDate = GETDATE();
	SELECT @purchaseItemId = PURCH_ITEM_ID FROM A_FILLS WHERE ID = @fillId;
	SELECT TOP 1 @purchaseHistoryId = PURCHASE_HIST_ID FROM A_ORDER_ITEMS WHERE ID = @purchaseItemId AND PURCHASE_HIST_ID IS NOT NULL ORDER BY DRCM;
	SELECT OBJECT_ID AS PurchaseNumber, ROOT_CO_NAME AS ShipFrom, CUST_PURCH_NUM AS CustomerPo, CONVERT(VARCHAR(10), @getDate, 101) + ' ' 
       + LTRIM(RIGHT(CONVERT(CHAR(20), @getDate, 22), 11)) AS ShipDate FROM A_V_PURCHASES_WITH_SUPPLIER_QUOTES  WHERE PURCH_HIST_ID = @purchaseHistoryId
	UPDATE A_ORDER_ITEMS SET SHIP_DATE = @getDate WHERE ID = @purchaseItemId;
	SELECT ca.NAME AS CompanyName, CONCAT(dt.PROD_NAME, '-', dt.PROC_NAME) AS Description,dt.CUST_LINE_ITEM AS CustLineItem, dt.PURCHASE_QTY As Quantity, dt.PURCH_ITEM_ID AS CustomerWoItemNumber, dt.COMPANY_PART_NUMBER AS CompanyPartNumber, 
	dt.SERIAL AS Serial FROM A_V_DELIVERY_TICKET_PURCH_ITEM_INFO dt JOIN A_V_COMPANIES_APPROVED_DATA_QUICK ca ON dt.ACCT_CUSTOMER = ca.ID WHERE dt.PURCHASE_HIST_ID = @purchaseHistoryId 
	AND dt.PURCH_ITEM_ID = @purchaseItemId