CREATE PROCEDURE [dbo].[Portal_GetTaskWithMonitors]
	@FILLID VARCHAR(50)
AS

CREATE TABLE #TEMPTASKS (ID VARCHAR(50))
INSERT INTO #TEMPTASKS 
SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WITH (NOLOCK) WHERE FILL_ITEM_ID = @FILLID

WHILE EXISTS(SELECT * FROM A_TASKS WHERE PARENT_ID IN (SELECT ID FROM #TEMPTASKS) AND ID NOT IN (SELECT ID FROM #TEMPTASKS))
BEGIN
	INSERT INTO #TEMPTASKS 
	SELECT ID FROM A_TASKS WITH (NOLOCK) WHERE PARENT_ID IN 
	(SELECT ID FROM #TEMPTASKS) AND ID NOT IN (SELECT ID FROM #TEMPTASKS)
END

SELECT DISTINCT T.STEP_ID AS TASKID
	, T.TITLE AS TASKTITLE
	, T.[DESCRIPTION]
	, T.VERB
	, T.*
FROM A_V_TASKS_WITH_PROCEDURE_STEP_DATA T WITH (NOLOCK) 
WHERE	T.STEP_ID IN (SELECT T1.ID FROM #TEMPTASKS T1)
AND		T.VERB = 123004 -- VERB IS THE PROCEDURE TYPE AND 123004 IS THE NCR PROCEDURE TYPE
--AND		T.[DESCRIPTION] LIKE '%NCR%'
--AND		HAS_MONITOR = 1

GO




