CREATE PROCEDURE [dbo].[Portal_PeopleReassignBoss] 
@newID varchar(50) OUTPUT,
@msg varchar(2000) OUTPUT,
@FROM_BOSS varchar(50),
@TO_BOSS varchar(50),
@strNTLogin varchar(50)

AS

SELECT @newID = COUNT(ID) FROM A_PEOPLE_HISTORY WHERE BOSS=@FROM_BOSS AND SYSTEM_STATUS = 'ACTIVE'
	AND ID IN (SELECT HISTORY_REF_ID FROM A_PEOPLE WHERE STATUS ='APPROVED')

SELECT ID as Id,FULL_NAME as FullName FROM A_PEOPLE_HISTORY WHERE BOSS=@FROM_BOSS AND SYSTEM_STATUS = 'ACTIVE'
	AND ID IN (SELECT HISTORY_REF_ID FROM A_PEOPLE WHERE STATUS ='APPROVED')

declare @curs cursor,@it varchar(50)
set @curs = CURSOR FOR SELECT ID FROM A_PEOPLE_HISTORY WHERE BOSS=@FROM_BOSS  AND SYSTEM_STATUS = 'ACTIVE'
	AND ID IN (SELECT HISTORY_REF_ID FROM A_PEOPLE WHERE STATUS ='APPROVED')
open @curs
fetch next from @curs into @it
while @@fetch_status = 0
	begin
	UPDATE A_PEOPLE_HISTORY SET BOSS = @TO_BOSS WHERE ID = @it
	fetch next from @curs into @it
	end