CREATE PROCEDURE [dbo].[Portal_GetStepDetails]
	@stepId varchar(50),
	@phStepId varchar(50)
AS
	SELECT 
	GROUP_REQUESTEE_ID AS GroupRequesteeId , 
	Title as StepTitle,
	DESCRIPTION,
	STATUS,
	LATEST_REQUESTEE_NAME AS Assignee,
	Has_Monitor AS HasMonitor,
	System_Task AS SystemTask,
	Requestee_Id AS RequesteeId,
	PARENT_ID AS ParentId
	FROM A_V_TASK_EDIT_DATA
	WHERE ID = @stepId

	SELECT ID AS Id, DESCRIPTION, COMMENT, PRINT_RESULT As PrintResult, TARGET, MONITOR_TYPE AS MonitorType, FAIL_ACTION AS FailAction, TARGET, TOLERANCE
	 FROM A_V_MONITOR_TEMPLATES_WITH_RESULTS WHERE TASK_ID = @stepId ORDER BY PRINT_ORDER
	SELECT * FROM A_V_PROCEDURE_STEP_DOCUMENT_DATA WHERE STEP_ID = @phStepId
	GO