CREATE PROCEDURE [dbo].[Portal_GetStepDetails]
	@stepId varchar(50),
	@phStepId varchar(50)
AS
	SELECT DESCRIPTION, STATUS, LATEST_REQUESTEE_NAME AS Assignee FROM A_V_TASK_EDIT_DATA WHERE ID = @stepId	
	SELECT * FROM A_V_PROCEDURE_STEP_DOCUMENT_DATA WHERE STEP_ID = @phStepId
	GO