CREATE PROCEDURE [dbo].[Portal_GetPurchaseItemDetails]
	@FILEID INT
AS


DECLARE @PURCHASE_HISTORY_ID VARCHAR(50)
DECLARE @PRODUCT_NAME VARCHAR(50)

SELECT TOP 1 @PURCHASE_HISTORY_ID = F.PURCHASE_HIST_ID
FROM A_V_FILLS_SEARCH F
WHERE ID = @FILEID

SELECT TOP 1 parts.NAME AS FILLOBJDESC
	, CUST_NAME AS CUSTOMERNAME
	, PROD_NAME AS PRODUCTNAME
	, PROC_NAME AS PROCEDURENAME
	, PURCH_ITEM_ID AS PURCHITEMID
	, FILL_QTY AS QTY
	, FILL_OBJ_ID AS FILLOBJECTID
	, PROC_ID AS PROCID
	, PROCOBJID
	, REV AS REV
FROM A_V_FILLS_SEARCH fill WITH (NOLOCK)
LEFT JOIN A_V_ACTUAL_PARTS_APPROVED_DATA parts
	ON FILL_OBJ_ID = parts.ID
WHERE fill.ID = @FILEID

SELECT [Name]
FROM A_V_ACTUAL_PARTS_APPROVED_DATA WITH (NOLOCK)
WHERE PARENT_ID = (SELECT TOP 1 FILL_OBJ_ID FROM A_V_FILLS_SEARCH WITH (NOLOCK) WHERE ID = @FILEID)

;WITH TASK_CTE (TASK_ID, PARENT_TASK_ID, TASKTITLE, [LEVEL], [TASK_PATH])
AS
(
	SELECT ID, PARENT_ID, TITLE, 0 AS [LEVEL], CAST(ID AS VARCHAR(255)) AS [TASK_PATH]
	FROM A_TASKS
	WHERE ID IN (SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION WITH (NOLOCK) WHERE FILL_ITEM_ID = @FILEID)

	UNION ALL

	SELECT T.ID, T.PARENT_ID, T.TITLE, [LEVEL] + 1, CAST([TASK_PATH] + '.' + CAST(T.ID AS VARCHAR(255)) AS VARCHAR(255))
	FROM A_TASKS T
	INNER JOIN TASK_CTE TC ON TC.TASK_ID = T.PARENT_ID
)

-- USE THE CTE TO GET ALL SUPPLIERS IN A SUPPLY CHAIN WITH LEVELS
SELECT DISTINCT T.TASK_ID
	, T.TASK_ID AS TASKID
	, TITLE
	, [DESCRIPTION] AS [DESCRIPTION]
	, [DESCRIPTION] RAWDESCRIPTION
	, DBO.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID AS ORDERER
	, [PARENT_ID]
	, [STEP_ID] AS STEPID
	, [STATUS]
	, [REQUESTOR]
	, [COMPLETED_BY]
	, [PROC_HIST_ID]
	, [PH_STEP_ID] AS PHSTEPID
	, [PRINT_ORDER]
	, [RECURSION_NUMBER]
	, [HAS_SURVEY]
	, [HAS_CHILD]
	, [HAS_REF_PROC]
	, [HAS_FILE]
	, [SYSTEM_TASK]
	, [HAS_MONITOR]
	, [REQUESTEE_ID]
	, [GROUP_REQUESTEE_ID]
	, CHILD_STATUS
	, LATEST_REQUESTEE_NAME
	, ROLES
	, TASK_PATH
	, P.VERB
	, P.VERB_NAME
FROM TASK_CTE T
INNER JOIN A_V_TASKS_WITH_PROCEDURE_STEP_DATA P ON T.TASK_ID = P.STEP_ID
WHERE P.TITLE IS NOT NULL
ORDER BY T.TASK_PATH, P.PRINT_ORDER
GO