ALTER Procedure [dbo].[Portal_Check_Login]
@LOGIN as nvarchar(50),
@PASSWORD as nvarchar(50),
@PASSWORD_NON_ENCRYPT as nvarchar(50)
AS
	

	if Exists(SELECT ID FROM A_ADMIN_CONFIGURATION WHERE NAME = 'ALL_PASS' AND VAL = @PASSWORD_NON_ENCRYPT)
	begin
	print 'All PAss'
	SELECT ID,NAME,LAST_NAME AS LastName,LOGIN
	FROM A_APPROVED_PEOPLE 
	WHERE SYSTEM_STATUS = 'ACTIVE' AND LOGIN = @LOGIN
	end
else
	begin
	SELECT ID,NAME,LAST_NAME AS LastName,LOGIN
	FROM A_APPROVED_PEOPLE 
	WHERE SYSTEM_STATUS = 'ACTIVE' AND LOGIN = @LOGIN and PASSWORD = @PASSWORD
	end





