CREATE PROCEDURE [dbo].[Portal_WorkItemImagesById]
	@taskId varchar(50)
AS
BEGIN
	SELECT * FROM A_V_TASK_REF_FILES WHERE TASK_ID = @taskId AND (STATUS = 'ACTIVE' OR STATUS IS NULL) ORDER BY FILE_NAME,FILE_DESCRIPTION

END

GO