CREATE procedure [dbo].[Portal_GetPurchaseItemDetails]
@fileId int
AS

DECLARE @objectid VARCHAR(50);

SELECT  @objectid = FILL_OBJ_ID FROM A_V_FILLS_SEARCH with (noLock)  WHERE ID = @fileId

SELECT FILL_OBJ_DESC AS FillObjDesc, CUST_NAME AS CustomerName, PROD_NAME AS ProductName, PROC_NAME AS ProcedureName, PURCH_ITEM_ID AS PurchItemId, FILL_QTY AS Qty, FILL_OBJ_ID AS FillObjectId FROM A_V_FILLS_SEARCH with (noLock)  WHERE ID = @fileId

SELECT Name FROM A_V_ACTUAL_PARTS_APPROVED_DATA with (noLock)  WHERE PARENT_ID = @objectid

create TABLE #tempTasks (ID varchar(50))
INSERT INTO #tempTasks 
	SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION with (noLock) WHERE FILL_ITEM_ID = @fileId
	
while exists(SELECT * FROM 	A_TASKS WHERE PARENT_ID COLLATE DATABASE_DEFAULT in (SELECT ID FROM #tempTasks) and ID COLLATE DATABASE_DEFAULT not in (SELECT ID FROM #tempTasks))
begin
	INSERT INTO #tempTasks 
		SELECT ID FROM A_TASKS with (noLock) WHERE PARENT_ID COLLATE DATABASE_DEFAULT IN 
		(SELECT ID FROM #tempTasks) and ID COLLATE DATABASE_DEFAULT not in (SELECT ID FROM #tempTasks)
end


SELECT DISTINCT 
 LTRIM(RTRIM(REPLACE(REPLACE((CASE WHEN CHARINDEX('<<nl/>>', [DESCRIPTION]) > 0 THEN SUBSTRING([DESCRIPTION], 0, CHARINDEX('<<nl/>>', [DESCRIPTION] )) ELSE [DESCRIPTION] END),'<<bb>>','') ,'<</bb>>',''))) as Description,
 [DESCRIPTION] RawDescription,
 dbo.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID as ORDERER,[PARENT_ID], [STEP_ID] AS StepId, [STATUS], [REQUESTOR], [COMPLETED_BY],[PROC_HIST_ID], [PH_STEP_ID] AS PhStepId, 
[PRINT_ORDER], [RECURSION_NUMBER], [HAS_SURVEY], [HAS_CHILD], [HAS_REF_PROC], [HAS_FILE], 
[SYSTEM_TASK], [HAS_MONITOR], [REQUESTEE_ID], [GROUP_REQUESTEE_ID],
CHILD_STATUS, LATEST_REQUESTEE_NAME,[StepTitle]
FROM A_V_TASKS_WITH_PROCEDURE_STEP_DATA  with (noLock) 
	WHERE STEP_ID COLLATE DATABASE_DEFAULT IN (SELECT t1.ID FROM #tempTasks t1)
ORDER BY dbo.A_FN_TASK_MAKE_PARENT_LIST(STEP_ID) + STEP_ID, PRINT_ORDER

-- leGetPurchaseItemDetails '110691'

GO