CREATE procedure [dbo].[Portal_GetTsrWipHistory]

@fillID varchar(50)

AS

create TABLE #tempTasks (ID varchar(50), ParentId varchar(50), DESCRIPTION nvarchar(2000), STATUS varchar(50), REQUESTOR varchar(50), CompletedBy varchar(50), 
ActualStartDate datetime, ActualStopDate datetime, LatestRequesteeName nvarchar(200), HasFile tinyint, HasMonitor tinyint, Location nvarchar(100))

INSERT INTO #tempTasks
SELECT ID, PARENT_ID, CASE WHEN CHARINDEX ('<</bb>>', DESCRIPTION) > 0 THEN REPLACE (LEFT (DESCRIPTION, CHARINDEX ('<</bb>>', DESCRIPTION)-1), '<<bb>>', '') 
ELSE CASE WHEN LEN(DESCRIPTION)> 50 THEN LEFT(DESCRIPTION, 47) + '...' ELSE DESCRIPTION END END AS DESCRIPTION, STATUS, REQUESTOR, COMPLETED_BY, ACTUAL_START_DATE, 
ACTUAL_STOP_DATE, LATEST_REQUESTEE_NAME, HAS_FILE, HAS_MONITOR, (SELECT NAME FROM dbo.A_LOCATIONS_HISTORY WHERE ID = 
(SELECT HISTORY_REF_ID FROM dbo.A_LOCATIONS WHERE ID = (SELECT SPECIFIC_LOCATION FROM dbo.A_PROCEDURE_STEPS WHERE ID = PROCEDURE_STEP_ID))) AS Location 
FROM A_TASKS WHERE PARENT_ID = (SELECT TASK_ID FROM A_TASK_ORDER_INFORMATION with (noLock) WHERE FILL_ITEM_ID = @fillID)

SELECT PURCH_ITEM_ID AS PurchaseItemId, SUP_NAME AS SupplierName, PROC_NAME AS ProcedureName, CUSTOMER_PERSON AS CustomerPerson, FILL_OBJ_DESC AS FillObjectDescription FROM A_V_FILLS_SEARCH with (noLock)  WHERE ID = @fillID

SELECT * FROM #tempTasks

SELECT TASK_ID AS TaskId, ID, MONITOR_TYPE AS MonitorType, DESCRIPTION, CASE WHEN MONITOR_TYPE = 'YES_NO' THEN REPLACE (REPLACE (YES_NO_ANSWER, 1, 'Yes'), 0, 'No') 
WHEN MONITOR_TYPE = 'USER_NUMBER' THEN CAST(NUM_VAL AS NVARCHAR) WHEN MONITOR_TYPE = 'NUMBER' THEN CAST(NUM_VAL AS NVARCHAR) 
WHEN MONITOR_TYPE = 'TEXT' THEN TEXT_VAL ELSE PRINT_RESULT END AS PrintResult, REPLACE (REPLACE (IS_PASSING, 1, 'Pass'), 0, 'Fail') AS IsPassing, TASK_STATUS As TaskStatus, 
YES_NO_ANSWER As YesNoAnswer, NUM_VAL AS NumValue, TEXT_VAL AS TextValue FROM A_V_MONITORS_WITH_TASK_AND_RESULT WHERE TASK_ID in (SELECT ID from #tempTasks)