/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AuditActionResultOfProcedureStepMonitor : AuditActionResult, IEquatable<AuditActionResultOfProcedureStepMonitor>
    { 
        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [DataMember(Name="object")]
        public ProcedureStepMonitorRequest Object { get; set; }

        /// <summary>
        /// Gets or Sets ReturnedObject
        /// </summary>
        [DataMember(Name="returnedObject")]
        public ProcedureStepMonitorRequest ReturnedObject { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuditActionResultOfProcedureStepMonitor {\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  ReturnedObject: ").Append(ReturnedObject).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AuditActionResultOfProcedureStepMonitor)obj);
        }

        /// <summary>
        /// Returns true if AuditActionResultOfProcedureStepMonitor instances are equal
        /// </summary>
        /// <param name="other">Instance of AuditActionResultOfProcedureStepMonitor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuditActionResultOfProcedureStepMonitor other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Object == other.Object ||
                    Object != null &&
                    Object.Equals(other.Object)
                ) && 
                (
                    ReturnedObject == other.ReturnedObject ||
                    ReturnedObject != null &&
                    ReturnedObject.Equals(other.ReturnedObject)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Object != null)
                    hashCode = hashCode * 59 + Object.GetHashCode();
                    if (ReturnedObject != null)
                    hashCode = hashCode * 59 + ReturnedObject.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AuditActionResultOfProcedureStepMonitor left, AuditActionResultOfProcedureStepMonitor right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AuditActionResultOfProcedureStepMonitor left, AuditActionResultOfProcedureStepMonitor right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
