/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{
    public partial class CreateProcedureStepRequest
    {
        public int? ProcedureId { get; set; }

        public string Title { get; set; }

        public string StepText { get; set; }

        public double? Duration { get; set; }

        public string DurationType { get; set; }

        public int? ProcedureStepTypeId { get; set; }

        public int? PrintOrder { get; set; }

        public int? PredecessorStepId { get; set; }

        public double? LaborTime { get; set; }

        public int? EquipmentTime { get; set; }

        public double? ReplacementCost { get; set; }

        public float? Utilization { get; set; }

        public int? UsefulLife { get; set; }

        public List<FileRequest> ReferenceFiles { get; set; }

        public ICollection<int> ReferenceFileIds { get; set; }

        public List<RoleRequest> Roles { get; set; }

        public List<int> ReferenceDocumentIds { get; set; }
    }
}
