/*
 * MSR API
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateUtilityRequest : IEquatable<CreateUtilityRequest>
    { 
        /// <summary>
        /// Gets or Sets LocationId
        /// </summary>
        [Required]
        [DataMember(Name="locationId")]
        public int? LocationId { get; set; }

        /// <summary>
        /// Gets or Sets AssignedToId
        /// </summary>
        [DataMember(Name="assignedToId")]
        public int? AssignedToId { get; set; }

        /// <summary>
        /// Gets or Sets TroubleState
        /// </summary>
        [DataMember(Name="troubleState")]
        public bool? TroubleState { get; set; }

        /// <summary>
        /// Gets or Sets MaintenanceTask
        /// </summary>
        [DataMember(Name="maintenanceTask")]
        public string MaintenanceTask { get; set; }

        /// <summary>
        /// Gets or Sets StatusId
        /// </summary>
        [Required]
        [DataMember(Name="statusId")]
        public int? StatusId { get; set; }

        /// <summary>
        /// Gets or Sets PemLastCompletedDate
        /// </summary>
        [DataMember(Name="pemLastCompletedDate")]
        public DateTime? PemLastCompletedDate { get; set; }

        /// <summary>
        /// Gets or Sets FrequencyField
        /// </summary>
        [Required]
        [DataMember(Name="frequencyField")]
        public int? FrequencyField { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments")]
        public string Comments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateUtilityRequest {\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  AssignedToId: ").Append(AssignedToId).Append("\n");
            sb.Append("  TroubleState: ").Append(TroubleState).Append("\n");
            sb.Append("  MaintenanceTask: ").Append(MaintenanceTask).Append("\n");
            sb.Append("  StatusId: ").Append(StatusId).Append("\n");
            sb.Append("  PemLastCompletedDate: ").Append(PemLastCompletedDate).Append("\n");
            sb.Append("  FrequencyField: ").Append(FrequencyField).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateUtilityRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateUtilityRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateUtilityRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateUtilityRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LocationId == other.LocationId ||
                    LocationId != null &&
                    LocationId.Equals(other.LocationId)
                ) && 
                (
                    AssignedToId == other.AssignedToId ||
                    AssignedToId != null &&
                    AssignedToId.Equals(other.AssignedToId)
                ) && 
                (
                    TroubleState == other.TroubleState ||
                    TroubleState != null &&
                    TroubleState.Equals(other.TroubleState)
                ) && 
                (
                    MaintenanceTask == other.MaintenanceTask ||
                    MaintenanceTask != null &&
                    MaintenanceTask.Equals(other.MaintenanceTask)
                ) && 
                (
                    StatusId == other.StatusId ||
                    StatusId != null &&
                    StatusId.Equals(other.StatusId)
                ) && 
                (
                    PemLastCompletedDate == other.PemLastCompletedDate ||
                    PemLastCompletedDate != null &&
                    PemLastCompletedDate.Equals(other.PemLastCompletedDate)
                ) && 
                (
                    FrequencyField == other.FrequencyField ||
                    FrequencyField != null &&
                    FrequencyField.Equals(other.FrequencyField)
                ) && 
                (
                    Comments == other.Comments ||
                    Comments != null &&
                    Comments.Equals(other.Comments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LocationId != null)
                    hashCode = hashCode * 59 + LocationId.GetHashCode();
                    if (AssignedToId != null)
                    hashCode = hashCode * 59 + AssignedToId.GetHashCode();
                    if (TroubleState != null)
                    hashCode = hashCode * 59 + TroubleState.GetHashCode();
                    if (MaintenanceTask != null)
                    hashCode = hashCode * 59 + MaintenanceTask.GetHashCode();
                    if (StatusId != null)
                    hashCode = hashCode * 59 + StatusId.GetHashCode();
                    if (PemLastCompletedDate != null)
                    hashCode = hashCode * 59 + PemLastCompletedDate.GetHashCode();
                    if (FrequencyField != null)
                    hashCode = hashCode * 59 + FrequencyField.GetHashCode();
                    if (Comments != null)
                    hashCode = hashCode * 59 + Comments.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateUtilityRequest left, CreateUtilityRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateUtilityRequest left, CreateUtilityRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
