/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public class CreateWorkOrderTaskRequest
    {
        /// <summary>
        /// WorkOrder we are adding the Procedure Step to
        /// </summary>
        /// <value>WorkOrder we are adding the Procedure Step to</value>
        [DataMember(Name="workOrderId")]
        public int? WorkOrderId { get; set; }

        /// <summary>
        /// The Procedure the ProcedureStep is related to
        /// </summary>
        /// <value>The Procedure the ProcedureStep is related to</value>
        [DataMember(Name="procedureId")]
        public int? ProcedureId { get; set; }

        /// <summary>
        /// The ProcedureStep we are adding which will be a task of the WorkOrder
        /// </summary>
        /// <value>The ProcedureStep we are adding which will be a task of the WorkOrder</value>
        [DataMember(Name="procedureStepId")]
        public int? ProcedureStepId { get; set; }

        /// <summary>
        /// The Task Step Order number of the Procedure Step. Tasks after this will use another request to update their order
        /// </summary>
        /// <value>The Task Step Order number of the Procedure Step. Tasks after this will use another request to update their order</value>
        [DataMember(Name="taskStepOrder")]
        public int? TaskStepOrder { get; set; }
    }
}
