/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class CreateProcedureRequest : IEquatable<CreateProcedureRequest>
    {
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>NAME1598366448</example>
        [Required]
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ProcedureTypeId
        /// </summary>
        /// <example>1</example>
        [DataMember(Name="procedureTypeId")]
        public int? ProcedureTypeId { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        /// <example>A comment 1598366448</example>
        [DataMember(Name="comments")]
        public string Comments { get; set; }

        /// <summary>
        /// Gets or Sets RoleIds
        /// </summary>
        /// <example>[1,2,3]</example>
        [DataMember(Name="roleIds")]
        public List<int?> RoleIds { get; set; }

        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        /// <example>5.2</example>
        [DataMember(Name="duration")]
        public double? Duration { get; set; }

        /// <summary>
        /// Gets or Sets DurationType
        /// </summary>
        /// <example>hours</example>
        [Required]
        [DataMember(Name="durationType")]
        public string DurationType { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceFiles
        /// </summary>
        [DataMember(Name="referenceFiles")]
        public List<FileRequest> ReferenceFiles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateProcedureRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ProcedureTypeId: ").Append(ProcedureTypeId).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  RoleIds: ").Append(RoleIds).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  DurationType: ").Append(DurationType).Append("\n");
            sb.Append("  ReferenceFiles: ").Append(ReferenceFiles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateProcedureRequest)obj);
        }

        /// <summary>
        /// Returns true if CreateProcedureRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateProcedureRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateProcedureRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    ProcedureTypeId == other.ProcedureTypeId ||
                    ProcedureTypeId != null &&
                    ProcedureTypeId.Equals(other.ProcedureTypeId)
                ) &&
                (
                    Comments == other.Comments ||
                    Comments != null &&
                    Comments.Equals(other.Comments)
                ) &&
                (
                    RoleIds == other.RoleIds ||
                    RoleIds != null &&
                    RoleIds.SequenceEqual(other.RoleIds)
                ) &&
                (
                    Duration == other.Duration ||
                    Duration != null &&
                    Duration.Equals(other.Duration)
                ) &&
                (
                    DurationType == other.DurationType ||
                    DurationType != null &&
                    DurationType.Equals(other.DurationType)
                ) &&
                (
                    ReferenceFiles == other.ReferenceFiles ||
                    ReferenceFiles != null &&
                    ReferenceFiles.SequenceEqual(other.ReferenceFiles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (ProcedureTypeId != null)
                    hashCode = hashCode * 59 + ProcedureTypeId.GetHashCode();
                    if (Comments != null)
                    hashCode = hashCode * 59 + Comments.GetHashCode();
                    if (RoleIds != null)
                    hashCode = hashCode * 59 + RoleIds.GetHashCode();
                    if (Duration != null)
                    hashCode = hashCode * 59 + Duration.GetHashCode();
                    if (DurationType != null)
                    hashCode = hashCode * 59 + DurationType.GetHashCode();
                    if (ReferenceFiles != null)
                    hashCode = hashCode * 59 + ReferenceFiles.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateProcedureRequest left, CreateProcedureRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateProcedureRequest left, CreateProcedureRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
