/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    /// GetWorkOrderRequest
    /// </summary>
    public class GetWorkOrderRequest
    {
        /// <summary>
        /// Get work order by ID
        /// </summary>
        public int? id { get; set; }
    }
}
