/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace IO.Swagger.Models
{
    /// <summary>
    /// GetWorkOrderRequest
    /// </summary>
    public class GetWorkOrderRequest
    {
        /// <summary>
        /// Get work order by ID
        /// </summary>
        public int? id;

        /// <summary>
        /// Get work orders by customer ID
        /// </summary>
        public int? customerId;

        /// <summary>
        /// Get work orders by location ID
        /// </summary>
        public int? locationId;

        /// <summary>
        /// Get work orders by invoice Date
        /// </summary>
        public string invoiceDate;
    }
}
