/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class RoleRequest : IEquatable<RoleRequest>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets IsCertificationRole
        /// </summary>
        [DataMember(Name="isCertificationRole")]
        public bool? IsCertificationRole { get; set; }

        /// <summary>
        /// Gets or Sets Menus
        /// </summary>
        [DataMember(Name="menus")]
        public List<MenuItemRequest> Menus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RoleRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsCertificationRole: ").Append(IsCertificationRole).Append("\n");
            sb.Append("  Menus: ").Append(Menus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RoleRequest)obj);
        }

        /// <summary>
        /// Returns true if RoleRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of RoleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RoleRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    IsCertificationRole == other.IsCertificationRole ||
                    IsCertificationRole != null &&
                    IsCertificationRole.Equals(other.IsCertificationRole)
                ) &&
                (
                    Menus == other.Menus ||
                    Menus != null &&
                    Menus.SequenceEqual(other.Menus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (IsCertificationRole != null)
                    hashCode = hashCode * 59 + IsCertificationRole.GetHashCode();
                    if (Menus != null)
                    hashCode = hashCode * 59 + Menus.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RoleRequest left, RoleRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RoleRequest left, RoleRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
