/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public class UpdateWorkOrderTaskMonitorRequest
    {
        /// <summary>
        /// Gets or Sets WorkOrderTaskMonitorId
        /// </summary>
        [DataMember(Name="workOrderTaskMonitorId")]
        public int? WorkOrderTaskMonitorId { get; set; }

        /// <summary>
        /// Gets or Sets NumVal
        /// </summary>
        [DataMember(Name="numVal")]
        public int? NumVal { get; set; }

        /// <summary>
        /// Gets or Sets TextVal
        /// </summary>
        [DataMember(Name="textVal")]
        public string TextVal { get; set; }

        /// <summary>
        /// Gets or Sets MultiVal
        /// </summary>
        [DataMember(Name="multiVal")]
        public string MultiVal { get; set; }

        /// <summary>
        /// Gets or Sets SensorValue
        /// </summary>
        [DataMember(Name="sensorValue")]
        public string SensorValue { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name="comment")]
        public string Comment { get; set; }
    }
}
