/*
 * WIP API Specification
 *
 * WIP API Specifications
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public class UpdateWorkOrderTaskRequest
    {
        /// <summary>
        /// Gets or Sets WorkOrderTaskId
        /// </summary>
        [DataMember(Name="workOrderTaskId")]
        public int? WorkOrderTaskId { get; set; }

        /// <summary>
        /// Gets or Sets TaskStepOrder
        /// </summary>
        [DataMember(Name="taskStepOrder")]
        public int? TaskStepOrder { get; set; }

        /// <summary>
        /// Gets or Sets AssignedUserId
        /// </summary>
        [DataMember(Name="assignedUserId")]
        public int? AssignedUserId { get; set; }

        /// <summary>
        /// Gets or Sets TaskIsRunning
        /// </summary>
        [DataMember(Name="taskIsRunning")]
        public bool? TaskIsRunning { get; set; }

        /// <summary>
        /// Gets or Sets TaskRunningSince
        /// </summary>
        [DataMember(Name="taskRunningSince")]
        public DateTime TaskRunningSince { get; set; }

        /// <summary>
        /// Gets or Sets StartedOn
        /// </summary>
        [DataMember(Name="startedOn ")]
        public DateTime StartedOn { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Get or set TotalTaskTime
        /// </summary>
        [DataMember(Name="totalTaskTime")]
        public decimal? TotalTaskTime { get; set; }
    }
}
