/*
 * Parts, Procedures, and Monitors
 *
 * REST API Answer 3
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;

namespace MSR.Answer.API.V1.Models
{
    /// <summary>
    ///
    /// </summary>
    [DataContract]
    public partial class UpdateProcedureStepMonitorRequest
    {
        /// <summary>
        /// Procedure step monitor Id
        /// </summary>
        [DataMember(Name="id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets InputType string
        /// </summary>
        /// <example>manual</example>
        [DataMember(Name="inputType")]
        public string InputType { get; set; }

        /// <summary>
        /// Sensor Name
        /// </summary>
        /// <description>
        /// Sensor Name is only valid if this monitor is
        /// of input type == sensor.
        /// </description>
        [DataMember(Name="sensorName")]
        public string SensorName { get; set; }

        /// <summary>
        /// Gets or Sets MonitorType string
        /// </summary>
        /// <example>equipment</example>
        [DataMember(Name="monitorType")]
        public string MonitorType { get; set; }

        /// <summary>
        /// Gets or Sets ShouldBe
        /// </summary>
        [DataMember(Name="shouldBe")]
        public string ShouldBe { get; set; }

        /// <summary>
        /// Gets or Sets TargetValue
        /// </summary>
        [DataMember(Name="targetValue")]
        public string TargetValue { get; set; }

        /// <summary>
        /// Gets or Sets FaultHandling
        /// </summary>
        [DataMember(Name="faultHandling")]
        public string FaultHandling { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets SendEmailNotification
        /// </summary>
        [DataMember(Name="sendEmailNotification")]
        public bool? SendEmailNotification { get; set; }

        /// <summary>
        /// HighTarget
        /// </summary>
        [DataMember(Name="highTarget")]
        public float? HighTarget { get; set; }

        /// <summary>
        /// LowTarget
        /// </summary>
        [DataMember(Name="lowTarget")]
        public float? LowTarget { get; set; }
    }
}
