
IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_ROLES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title])
		VALUES ('1', 'A_ROLES_HISTORY', GETDATE(), '7', 'Roles')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_ROLES_HISTORY',
		[DRCM]=GETDATE(),
		[MODBY]='7',
	    [Title]='Roles'
		WHERE ID='1'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_NOUN_HIERARCHIES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title])
		VALUES ('10', 'A_NOUN_HIERARCHIES_HISTORY', GETDATE(), '7', 'A_NOUN_HIERARCHIES_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_NOUN_HIERARCHIES_HISTORY',
		[DRCM]=GETDATE(),
		[MODBY]='7',
		[Title]='A_NOUN_HIERARCHIES_HISTORY'
		WHERE ID='10'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PROCEDURES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title])
		VALUES ('11', 'A_PROCEDURES_HISTORY', GETDATE(), '7', 'Procedures')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PROCEDURES_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Procedures' 
		WHERE ID='11'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PRODUCTS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('12', 'A_PRODUCTS_HISTORY', GETDATE(), '7', 'Products')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PRODUCTS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Products' 
		WHERE ID='12'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_ACTUAL_PARTS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('13', 'A_ACTUAL_PARTS_HISTORY', GETDATE(), '7', 'Actual Parts')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_ACTUAL_PARTS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Actual Parts' 
		WHERE ID='13'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PROD_PRICE_LIST_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('14', 'A_PROD_PRICE_LIST_HISTORY', GETDATE(), '7', 'A_PROD_PRICE_LIST_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PROD_PRICE_LIST_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_PROD_PRICE_LIST_HISTORY' 
		WHERE ID='14'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_ACCOUNTS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('15', 'A_ACCOUNTS_HISTORY', GETDATE(), '7', 'A_ACCOUNTS_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_ACCOUNTS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Purchase Orders' 
		WHERE ID='15'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='ACCOUNT_PAYMENT_APPROVAL')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('16', N'ACCOUNT_PAYMENT_APPROVAL', GETDATE(), N'7', N'ACCOUNT_PAYMENT_APPROVAL')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='ACCOUNT_PAYMENT_APPROVAL', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='ACCOUNT_PAYMENT_APPROVAL' 
		WHERE ID='16'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_FORECASTS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('17', 'A_FORECASTS_HISTORY', GETDATE(), '7', 'A_FORECASTS_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_FORECASTS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_FORECASTS_HISTORY' 
		WHERE ID='17'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_ORDERS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('18', 'A_ORDERS_HISTORY', GETDATE(), '7', 'A_ORDERS_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_ORDERS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_ORDERS_HISTORY' 
		WHERE ID='18'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_QUOTES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('19', 'A_QUOTES_HISTORY', GETDATE(), '7', 'Quotes')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_QUOTES_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Quotes' 
		WHERE ID='19'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PEOPLE_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('2', 'A_PEOPLE_HISTORY', GETDATE(), '7', 'People')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PEOPLE_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='People' 
		WHERE ID='2'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PURCHASES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('20', 'A_PURCHASES_HISTORY', GETDATE(), '7', 'Purchases')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PURCHASES_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Purchases' 
		WHERE ID='20'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_EQUIP_EXP_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('21', 'A_EQUIP_EXP_HISTORY', GETDATE(), '7', 'A_EQUIP_EXP_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_EQUIP_EXP_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_EQUIP_EXP_HISTORY' 
		WHERE ID='21'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_NEEDS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('22', 'A_NEEDS_HISTORY', GETDATE(), '7', 'Needs')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_NEEDS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Needs' 
		WHERE ID='22'
END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_THEORY_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('23', 'A_THEORY_HISTORY', GETDATE(), '7', 'Documents')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_THEORY_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Documents' 
		WHERE ID='23'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PREPOP_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('24', 'A_PREPOP_HISTORY', GETDATE(), '7', 'A_PREPOP_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PREPOP_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_PREPOP_HISTORY' 
		WHERE ID='24'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PROPOSALS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('25', 'A_PROPOSALS_HISTORY', GETDATE(), '7', 'A_PROPOSALS_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PROPOSALS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_PROPOSALS_HISTORY' 
		WHERE ID='25'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_LOCATIONS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('3', 'A_LOCATIONS_HISTORY', GETDATE(), '7', 'Locations')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_LOCATIONS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Locations' 
		WHERE ID='3'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_REGIONS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('4', 'A_REGIONS_HISTORY', GETDATE(), '7', 'Regions')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_REGIONS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Regions' 
		WHERE ID='4'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_COMPANIES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('5', 'A_COMPANIES_HISTORY', GETDATE(), '7', 'Companies')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_COMPANIES_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Companies' 
		WHERE ID='5'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_TEMPLATE_TASKS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('6', 'A_TEMPLATE_TASKS_HISTORY', GETDATE(), '7', 'A_TEMPLATE_TASKS_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_TEMPLATE_TASKS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_TEMPLATE_TASKS_HISTORY' 
		WHERE ID='6'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PARTS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('7', 'A_PARTS_HISTORY', GETDATE(), '7', 'Parts')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PARTS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Parts' 
		WHERE ID='7'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_PART_TYPES_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('8', 'A_PART_TYPES_HISTORY', GETDATE(), '7', 'Part Types')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_PART_TYPES_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='Part Types' 
		WHERE ID='8'
	END
GO


IF NOT EXISTS(SELECT * FROM [dbo].[A_WF_ACTIVITIES] WHERE ACTIVITY='A_TT_VERBS_HISTORY')
	BEGIN
		INSERT [dbo].[A_WF_ACTIVITIES] ([ID], [ACTIVITY], [DRCM], [MODBY], [Title]) 
		VALUES ('9', 'A_TT_VERBS_HISTORY', GETDATE(), '7', 'A_TT_VERBS_HISTORY')
	END
ELSE
	BEGIN
		UPDATE  [dbo].[A_WF_ACTIVITIES] 
		SET 
		[ACTIVITY]='A_TT_VERBS_HISTORY', 
		[DRCM]=GETDATE(), 
		[MODBY]='7', 
		[Title]='A_TT_VERBS_HISTORY' 
		WHERE ID='9'
	END
GO
