service: MSRReporting

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
# Athena permissions
        - "athena:*"
        - "s3:*"
        - "glue:*"
      Resource:
        - "*"
# When you uncomment vpc please make sure lambda has access to internet: https://medium.com/@philippholly/aws-lambda-enable-outgoing-internet-access-within-vpc-8dd250e11e12
  vpc:
    securityGroupIds:
#     - sg-385a655f
     - sg-0fb3803144f799766 # Your DB and Redis security groups here
    subnetIds:
     - subnet-04fda441407cd0e2f # Put here subnet with access to your DB, Redis and internet. For internet access 0.0.0.0/0 should be routed through NAT only for this subnet!
     - subnet-0623594db3b2a5d51
  environment:
    CUBEJS_DB_HOST: bang.msr-fsr.com
    CUBEJS_DB_NAME: Answer3_Dev
    CUBEJS_DB_USER: msrfsr
    CUBEJS_DB_PASS: snRvf2rFVG7rGAVE
    CUBEJS_DB_PORT: 1433
    REDIS_URL: answer-reporting-ro.8mpabp.ng.0001.usw2.cache.amazonaws.com:6379
    CUBEJS_DB_TYPE: athena
    CUBEJS_API_SECRET: 0a232a72ef2bbe49946e3fd3ee1cfd0d13e6d25529ae8810d28e924f2b630edf029369af5451ac8107108c776bd58ec0ecbb252d2d6759efe08635ee525802a3
    CUBEJS_APP: "${self:service.name}-${self:provider.stage}"
    NODE_ENV: production
    AWS_ACCOUNT_ID:
      Fn::Join:
        - ""
        - - Ref: "AWS::AccountId"

functions:
  cubejs:
    handler: cube.api
    timeout: 30
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: ANY
  cubejsProcess:
    handler: cube.process
    timeout: 630
    events:
      - sns: "${self:service.name}-${self:provider.stage}-process"

plugins:
  - serverless-express
